### PR TITLE
Added three fuzzers to the fluent-bit project.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Also cleaned up the `make || true` by disabling plugins we do not need as we fuzz the core.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@DavidKorczynski - can you please add the developer/integrator here (in a comment) so that they can approve your changes. That speeds up the process as otherwise we have to find them.

**Comment by DavidKorczynski** [comment]
Cross-referencing PR on upstream where the fuzzers were accepted: https://github.com/fluent/fluent-bit/pull/2114

Cross-referencing @edsiper and @fujimotos

Cross-referencing some of the heap-overflows that were found and fixed in order for the fuzzers to get merged to OSS-Fuzz: 
https://github.com/fluent/fluent-bit/commit/e055944e3ccd60996a3aa333fa14be12cbc6972f
https://github.com/fluent/fluent-bit/commit/81deab2bb042c814cee964563c12e8bdd55d8af3
https://github.com/fluent/fluent-bit/commit/38f2be4d0a8a7be68b7ba31cd3dec884ae78776d

**Comment by DavidKorczynski** [comment]
Hi @edsiper  could you please confirm here that you are alright with having OSS-Fuzz run the Fluent-bit fuzzers?

**Comment by edsiper** [comment]
I am pretty fine with it! go ahead and find those bugs!

**Comment by inferno-chromium** [comment]
@edsiper and @fujimotos, can you review the change as well, does build side changes look ok to you.

**Comment by edsiper** [comment]
lgtm

**Pull request merged**
