### PR TITLE
Changes needed to find libkqueue-dev package in the Network Radius ex…

### PR DESCRIPTION
**Pull request by mrw42**
…tras distribution.

These changes fix the problem that is currently causing the freeradius project not to build properly.  I am a consultant working with Network RADIUS, and I am submitting this pull request on their behalf.

### CODE REVIEW

**Comment by mrw42** [comment]
FYI -- I have completed the CLA for Painless Security, LLC.

**Comment by mrw42** [comment]
Hi.  I have updated the code in an effort to fix the earlier build problems.  Do I need to do anything to trigger the checks to be run again?

**Comment by DavidKorczynski** [comment]
> Hi. I have updated the code in an effort to fix the earlier build problems. Do I need to do anything to trigger the checks to be run again?

reran the CI now :) For future reference, you can re-trigger the checks yourself by closing and re-opening the PR

**Comment by mrw42** [comment]
Closing and opening to get the test to run again.

**Comment by DavidKorczynski** [comment]
> Closing and opening to get the test to run again.

sorry, my advice was incorrect -- it will only work once you have done a first commit.

I've restarted the CI again, please ping if need more reruns

**Comment by mrw42** [comment]
Thanks, David.  As you have probably guessed, we are making changes on the freeradius end to get the checks to pass.  I greatly appreciate your help with this.

**Comment by DavidKorczynski** [comment]
> Thanks, David. As you have probably guessed, we are making changes on the freeradius end to get the checks to pass. I greatly appreciate your help with this.

My pleasure!

I can see it currently fails due to:
```
fuzzer: Failed initializing test point decode_ctx: /usr/local/lib/libfreeradius-radius.so: cannot open shared object file: No such file or directory
Failed loading dictionary validation library "libfreeradius-radius"
```

This is because the shared library is not accessible in the runtime environment. Two options: either compile the library statically so it's part of the binary, or, use the options described here (which also has further details): https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/#runtime-dependencies

**Comment by mrw42** [comment]
We have done some updates on our end.  Could you please rerun the checks?

**Comment by DavidKorczynski** [comment]
> We have done some updates on our end. Could you please rerun the checks?

done

**Comment by mrw42** [comment]
I'm sorry, but could you please run the checks again?

**Comment by DavidKorczynski** [comment]
> I'm sorry, but could you please run the checks again?

done

**Comment by DavidKorczynski** [comment]
It;s passing :D Is this ready for merge?

**Comment by mrw42** [comment]
We are passing the checks now.  Thank you so much for your help, David!

**Review by DavidKorczynski — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Thanks @mrw42 !

**Pull request merged**
