### PR TITLE
[trial-builds] Speed up first trial build by using real image as cache

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py wasmtime skcms --sanitizer coverage address --fuzzing-engine libfuzzer

**Review by Alan32Liu — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
I don't think this actually resulted in a speed up.

**Comment by jonathanmetzman** [comment]
I think one reason the cache get invalidated a lot is when ubuntu:20.04 gets updated. Maybe we should pin it? @oliverchang ?

**Comment by oliverchang** [comment]
> I think one reason the cache get invalidated a lot is when ubuntu:20.04 gets updated. Maybe we should pin it? @oliverchang ?

Yeah let's pin.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py wasmtime skcms --sanitizer coverage address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py wasmtime skcms --sanitizer coverage address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py wasmtime skcms --sanitizer coverage address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py wasmtime skcms --sanitizer coverage address --fuzzing-engine libfuzzer

**Review by Alan32Liu — COMMENTED** [review]
LGTM

**Pull request merged**
