### PR TITLE
Add missing blog posts

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by oliverchang** [comment]
@hayleycd FYI!

**Review by Alan32Liu — APPROVED** [review]

**Comment by hayleycd** [comment]
Nice! Do we want to add them to the docs as well?

**Comment by oliverchang** [comment]
> Nice! Do we want to add them to the docs as well?
> 
> There is a blog list here too: https://github.com/google/oss-fuzz/blob/master/docs/reference/useful_links.md

Good catch, fixed. thanks!

**Review by jonathanmetzman — COMMENTED** [review]
lgtm
Thanks!

**Pull request merged**
