### PR TITLE
update libreoffice build-dependency cache

### PR DESCRIPTION
**Pull request by caolanm**
speed up the build a titch

### CODE REVIEW

**Comment by caolanm** [comment]
pre-check failures look unrelated, possibly OOM at link time

**Comment by DavidKorczynski** [comment]
> pre-check failures look unrelated, possibly OOM at link time

Did you verify they build locally? i.e. 
```
python infra/helper.py build_fuzzers libreoffice 
python infra/helper.py check_build libreoffice

...
python infra/helper.py build_fuzzers --sanitizer=undefined libreoffice
```

**Comment by caolanm** [comment]
> Did you verify they build locally? i.e.
> python infra/helper.py build_fuzzers libreoffice 
> python infra/helper.py check_build libreoffice
> python infra/helper.py build_fuzzers --sanitizer=undefined libreoffice
Yes, they all pass locally

**Comment by DavidKorczynski** [comment]
> > Did you verify they build locally? i.e.
> > python infra/helper.py build_fuzzers libreoffice
> > python infra/helper.py check_build libreoffice
> > python infra/helper.py build_fuzzers --sanitizer=undefined libreoffice
> > Yes, they all pass locally

Sounds good. I build the ASAN locally as well and verified it works. 
LGTM.

**Review by DavidKorczynski — APPROVED** [review]

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
