### PR TITLE
[htmlunit] add primary contact

### PR DESCRIPTION
**Pull request by 0roman**

### CODE REVIEW

**Comment by Navidem** [comment]
CLA is not signed, please fix it.

**Comment by 0roman** [comment]
@rbri

**Comment by rbri** [comment]
@0roman CLA should be there now

**Review by rbri — APPROVED** [review]

**Comment by Alan32Liu** [comment]
CLA still seems to be missing : ) @rbri @0roman

**Review by Alan32Liu — APPROVED** [review]
LGTM

**Pull request merged**
