### PR TITLE
infra: base-builder: refine fuzz-introspector building

### PR DESCRIPTION
**Pull request by DavidKorczynski**
- Pass coverage_url to both c/c++ and python report generation.
- Remove a double calling of introspector report generation.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@Navidem I noticed we call `/fuzz-introspector/src/main.py report` twice, where only once is needed. This could have significant impact on https://github.com/ossf/fuzz-introspector/issues/585

**Comment by Navidem** [comment]
> @Navidem I noticed we call `/fuzz-introspector/src/main.py report` twice, where only once is needed. This could have significant impact on [ossf/fuzz-introspector#585](https://github.com/ossf/fuzz-introspector/issues/585)

Good catch!

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib aspell idna xpdf --sanitizer coverage address introspector --fuzzing-engine libfuzzer

**Comment by DavidKorczynski** [comment]
There were some issues with gitlab.gnome.org earlier today so if any issues fail because of that (e.g. the infra tests) then restarting the CI and trial builds should be fine as gitlab.gnome.org is not displaying issues atm. Am not restarting the CI myself right now as I don't know what effect it has on the trial build which is running.

**Comment by Navidem** [comment]
> There were some issues with gitlab.gnome.org earlier today so if any issues fail because of that (e.g. the infra tests) then restarting the CI and trial builds should be fine as gitlab.gnome.org is not displaying issues atm. Am not restarting the CI myself right now as I don't know what effect it has on the trial build which is running.

I will restart that exact failing test.

**Comment by DavidKorczynski** [comment]
> I will restart that exact failing test.

Awesome, thanks!

**Comment by DavidKorczynski** [comment]
@Navidem I pushed one more commit as I noticed an issue had started to appear for the `glom` project.

**Comment by Navidem** [comment]
> @Navidem I pushed one more commit as I noticed an issue had started to appear for the `glom` project.

Sure, let's make sure trial_builds pass.

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib aspell idna glom --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib aspell idna glom --sanitizer coverage --fuzzing-engine libfuzzer

**Pull request merged**
