### PR TITLE
Golang signal handler builds fixes

### PR DESCRIPTION
**Pull request by catenacyber**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59153 : ecc-diff-fuzzer: Fuzzing build failure
And https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=59157 cel-go: Coverage build failure

 Fixes https://github.com/google/oss-fuzz/pull/10314 cc @Alan32Liu

### CODE REVIEW

**Comment by catenacyber** [comment]
Otherwise, the fix looks good : https://oss-fuzz.com/testcase-detail/4960752475963392 has the latest revision that found the bug to be on 17th on May

And this seems to be the cases for all bugs in https://oss-fuzz.com/testcases?project=gonids&open=yes

**Review by Alan32Liu — APPROVED** [review]

**Comment by catenacyber** [comment]
CI all green :-)

**Comment by catenacyber** [comment]
@Alan32Liu would you have a way to check all unreproducible bugs for all golang projects and what their latest revision is ?

**Comment by Alan32Liu** [comment]
> @Alan32Liu would you have a way to check all unreproducible bugs for all golang projects and what their latest revision is ?

I am not sure... @jonathanmetzman might have some ideas?

**Comment by catenacyber** [comment]
For instance, I see go-json-iterator has https://oss-fuzz.com/testcase-detail/6232318378115072 which looks to be fixed by this signal handler

**Comment by catenacyber** [comment]
Another example https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56814

**Comment by catenacyber** [comment]
Should I wait one week or 2 and check https://bugs.chromium.org/p/oss-fuzz/issues/list?sort=-closed%20-id&q=label%3AUnreproducible%20status%3DWontFix%20go&can=1&colspec=ID%20Type%20Component%20Status%20Proj%20Reported%20Owner%20Summary%20Closed ?

**Pull request merged**
