### PR TITLE
ecc-diff-fuzzer buils nettle without openssl

### PR DESCRIPTION
**Pull request by catenacyber**
Should fix build failure 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22819

### CODE REVIEW

**Comment by catenacyber** [comment]
CI failed because of job length :
> The job exceeded the maximum log length, and has been terminated.

**Comment by inferno-chromium** [comment]
> CI failed because of job length :
> 
> > The job exceeded the maximum log length, and has been terminated.

Travis is good at everything except this. Wonder if someone has some brilliant workaround on this (that shows both realtime logs and not run into limit).

**Comment by catenacyber** [comment]
> Wonder if someone has some brilliant workaround on this (that shows both realtime logs and not run into limit).

Not brilliant, but I can make this project build less verbose, should I ?

**Comment by inferno-chromium** [comment]
> > Wonder if someone has some brilliant workaround on this (that shows both realtime logs and not run into limit).
> 
> Not brilliant, but I can make this project build less verbose, should I ?

We want a generic solution, dont want project developers to go through this pain , just to workaround travis.

**Pull request merged**
