### PR TITLE
ci: Double free space from 30 GB to 60 GB

### PR DESCRIPTION
**Pull request by MarcoFalke**
My understanding is that basically only `git docker.io python` are needed for oss-fuzz, so 5 GB of the largest packages and 20+ GB of folders can be dropped from the CI image to make room for other stuff.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Thanks. I think i'll probably accept this but it does seem to slow things down a bit

**Comment by fanquake** [comment]
cc @dergoegge

**Comment by jonathanmetzman** [comment]
Nice!

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
