### PR TITLE
Add vendor to zstd

### PR DESCRIPTION
**Pull request by jonathanmetzman**
CC @terrelln

### CODE REVIEW

**Comment by terrelln** [comment]
I assume thats @danlark1, is that right?

**Comment by jonathanmetzman** [comment]
Yup

**Comment by jonathanmetzman** [comment]
Do you have any objections?

**Comment by terrelln** [comment]
LGTM!

**Review by jonathanmetzman — COMMENTED** [review]
lgtm

**Review by Navidem — APPROVED** [review]
LGTM

**Pull request merged**
