### PR TITLE
apache-commons: Fix build failures and configure all apache-commons projects correctly

### PR DESCRIPTION
**Pull request by henryrneh**
Fix build failure for:
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51576

And make all apache-commons projects more manageable by using projects/apache-commons as the main directory for all the apache-commons components.

### CODE REVIEW

**Comment by henryrneh** [comment]
Rebased the branch based on master.

**Comment by jonathanmetzman** [comment]
We're gonna have to think about this one. Maybe listing out the pros and cons can help us decide?

**Comment by oliverchang** [comment]
It would be a lot more preferable to keep these folders separate, particularly when the metadata (CCs + others) are likely not the same for all of these distinct projects.

Are we able to revert that change in particular, and just change the build failure(s) in question?

What benefits to this approach does this PR give you? Is it a matter of code duplication reduction? We could also potentially reduce duplication without changing the folder structure here.

**Comment by 0roman** [comment]
@oliverchang we've got a request by the apache-commons team to move all apache commons components under one folder. I will forward you the request. One benefit is that new onboardings in apache-commons would automatically include the primary contact "security@commons.apache.org".

**Comment by Alan32Liu** [comment]
Please let me know once the decision has been made : )
I will approve / close this PR accordingly.

**Comment by henryrneh** [comment]
https://github.com/google/oss-fuzz/pull/8967 will replace this PR.

**Pull request closed without merging**
