### PR TITLE
add project ntpsec https://ntpsec.org

### PR DESCRIPTION
**Pull request by fallenpegasus**
I am the project manager for the NTPsec Project, webpage at http://ntpsec.org/

NTPsec is a secure, hardened, and improved implementation of Network Time Protocol derived from NTP Classic, Dave Mills’s original.  NTPsec, as its name implies, is a more secure NTP. Towards that end we seek out and apply best practices in secure software development, including fuzz testing.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Can you comment on which are the current large consumers of ntpsec ?

**Comment by inferno-chromium** [comment]
friendly ping!

**Comment by Dor1s** [comment]
@fallenpegasus, are you still interested in OSS-Fuzz participation?

**Comment by mikea** [comment]
I'm closing this pr as non-active. Feel free to reopen if you decide to move forward.

**Comment by fallenpegasus** [comment]
We would like to move forward.

**Pull request closed without merging**
