### PR TITLE
[wolfssl] Update auto_ccs

### PR DESCRIPTION
**Pull request by philljj**
Add jordan to wolfSSL auto_ccs.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Please sign the CLA

**Comment by jonathanmetzman** [comment]
@Uriah-wolfSSL @tim-weller-wolfssl @ejohnstown do you approve?

**Comment by ejohnstown** [comment]
I approve.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
