### PR TITLE
infra: rust coverage option is now stable

### PR DESCRIPTION
**Pull request by catenacyber**
Hoping to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=48744

as the warning goes `warning: `-Z instrument-coverage` is deprecated; use `-C instrument-coverage`

### CODE REVIEW

**Comment by catenacyber** [comment]
cf https://github.com/rust-lang/rust/issues/98928

**Comment by Navidem** [comment]
/gcbrun trial_build.py wasmtime servo oak --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
Could you please look into trial build failure?

**Comment by catenacyber** [comment]
> Could you please look into trial build failure?

I did not access the logs.

But `git grep instrument-coverage` shows oak does something.
So I am pushing a new version

As the coverage is stable, is should now work on all crates hopefully (or a bug report should be opened in rustc)

**Comment by catenacyber** [comment]
friendly ping @Navidem ?

**Comment by Navidem** [comment]
> friendly ping @Navidem ?

Thanks! lets test it with trial_build.

**Comment by Navidem** [comment]
/gcbrun trial_build.py wasmtime servo oak --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by catenacyber** [comment]
What does gcbrun say ? I do not have access to the logs...

**Comment by catenacyber** [comment]
friendly ping @Navidem ?

**Comment by catenacyber** [comment]
friendly ping @Navidem ?

**Comment by catenacyber** [comment]
@Alan32Liu what do you think about this PR ?

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py wasmtime servo oak --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by Alan32Liu** [comment]
> @Alan32Liu what do you think about this PR ?

Navid's GCB run has expired, re-running it to figure out the failure.

**Comment by Alan32Liu** [comment]
@catenacyber
I will merge the `master` branch to your branch and re-run the GCB, as I don't think the current GCB error is caused by your code.

The current GCB failed on `gcr.io/oss-fuzz-base/trial-build` with the following error:
```
Step #1: Step #3: #6 13.28 /usr/local/bin/install_go.sh: line 36: cd: addimport: No such file or directory
```

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py wasmtime servo oak --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by Alan32Liu** [comment]
> @catenacyber I will merge the `master` branch to your branch and re-run the GCB, as I don't think the current GCB error is caused by your code.

GDB passed after updating your branch.
Please have a look at the other errors : )

**Comment by catenacyber** [comment]
Looks like linkerd2-proxy is forcing the installation of not the newest rust toolchain...

**Comment by catenacyber** [comment]
Thanks @Alan32Liu 
All green now, except you need to run gcb again...

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py wasmtime servo oak --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
I think now you should actually be able to see the logs: https://github.com/google/oss-fuzz/pull/7950/checks?check_run_id=11262995668

**Comment by jonathanmetzman** [comment]
(after this completes)

**Comment by catenacyber** [comment]
I can see the logs and it is green

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py rust --sanitizer coverage address --fuzzing-engine libfuzzer

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
