### PR TITLE
[grok] Try enabling dataflow and MSan configurations (#3569).

### PR DESCRIPTION
**Pull request by Dor1s**
Was requested in https://github.com/google/oss-fuzz/issues/3569, //cc @boxerab

### CODE REVIEW

**Comment by Dor1s** [comment]
@boxerab please take a look at the build failures, e.g.

```
CMake Error in src/lib/jp2/CMakeLists.txt:
  Target "grok" requires the language dialect "CXX20" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.
CMake Error in src/lib/jp2/CMakeLists.txt:
  Target "grok_static" requires the language dialect "CXX20" (with compiler
  extensions), but CMake does not know the compile flags to use to enable it.
```

I'll fix the presubmit error

**Comment by boxerab** [comment]
@Dor1s thanks, it looks like you need to grab the latest commit - I had an issue with osx but fixed on HEAD of master.

**Comment by boxerab** [comment]
Actually, issue is with `clang`, which doesn't support  `c++20`, or at least this version of cmake doesn't know the right compiler setting.

**Comment by boxerab** [comment]
I have upgraded to `cmake 3.17`, if that doesn't work with `clang` I can drop the c++ version back to `c++14`

**Comment by boxerab** [comment]
@Dor1s I now have my osx travis job working with latest `cmake 3.17`, `clang 10` and `c++20` enabled, so if you rebase the PR to the latest, it should work.

**Comment by boxerab** [comment]
btw, I now have build failure as oss-fuzz cmake version is 3.5. Can the grok oss-fuzz image use latest cmake version - 3.17 ?

**Comment by Dor1s** [comment]
> btw, I now have build failure as oss-fuzz cmake version is 3.5. Can the grok oss-fuzz image use latest cmake version - 3.17 ?

We would need to manually install them in the Dockerfile. Let me try updating this PR

**Comment by Dor1s** [comment]
Superseded by https://github.com/google/oss-fuzz/pull/3580

**Pull request closed without merging**
