### PR TITLE
jwt-verify-lib: OSS-fuzz integration for bazel project

### PR DESCRIPTION
**Pull request by nareddyt**
Following https://google.github.io/oss-fuzz/getting-started/new-project-guide/bazel/

Signed-off-by: Teju Nareddy <nareddyt@google.com>

### CODE REVIEW

**Comment by nareddyt** [comment]
cc @qiwzhang

**Comment by nareddyt** [comment]
PTAL. All tests should be passing

**Comment by nareddyt** [comment]
@jonathanmetzman can you help with the fuzzer failures? All jobs passed before I merged in master. This seems like a problem with the underlying OSS fuzz infra

Maybe related to https://github.com/google/oss-fuzz/pull/8916

**Comment by nareddyt** [comment]
Ah, i found https://github.com/google/oss-fuzz/issues/8915 and pushed the same workaround

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
