### PR TITLE
Revert "[upb] New Project: upb  (#2538)"

### PR DESCRIPTION
**Pull request by jonathanmetzman**
This reverts commit d5992e4ef57ef2493c160fb22de1ce8542041f35.

Upb is causing exceptions in ClusterFuzz and is completely broken
for AFL and libFuzzer.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
PTAL.

You can test what I mean about the fuzzers being totally broken by downloading a build. `gs://clusterfuzz-builds/upb/upb-address-201906300322.zip ` or `gs://clusterfuzz-builds-afl/upb/upb-address-201906300322.zip` for example.

CC @Google-Autofuzz

**Comment by jonathanmetzman** [comment]
Travis is failing because it can't handle reverts of new projects.

**Comment by jonathanmetzman** [comment]
Ping @Google-Autofuzz
Do you plan on relanding this?

**Comment by Google-Autofuzz** [comment]
Yes, will look into it. Currently, working on other projects. Thanks!

**Pull request merged**
