### PR TITLE
Fix broken Go coverage reports

### PR DESCRIPTION
**Pull request by AdamKorcz**
Fixes https://github.com/google/oss-fuzz/issues/10916

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py go --sanitizer address coverage --fuzzing-engines libfuzzer

**Comment by DavidKorczynski** [comment]
Looking at the failed trial build there is only 1 project that fails:

```
Step #1: INFO:root:Summary: trial build failed
Step #1: Failed builds: 1/89, {'kubeedge': 'https://oss-fuzz-gcb-logs.storage.googleapis.com/log-9df7ee5c-7c56-4471-a821-39ad0ccc8f8e.txt'}
Finished Step #1
```

The log for this project is:
```
tep #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/klog\./\/\/klog\./g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/device.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/\"k8s\.io\/klog\/v2"/\/\/\"k8s\.io\/klog\/v2\"/g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/device.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ compile_go_fuzzer github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager FuzzdealTwinActions fuzz_deal_twin_actions
Step #19 - "compile-libfuzzer-address-x86_64": /usr/local/bin/compile_go_fuzzer: line 28: cd: /root/go/src/github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager: No such file or directory
Step #19 - "compile-libfuzzer-address-x86_64": github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager
Step #19 - "compile-libfuzzer-address-x86_64": github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager
Step #19 - "compile-libfuzzer-address-x86_64": Running go-fuzz -tags gofuzz -func FuzzdealTwinActions -o fuzz_deal_twin_actions.a github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager
Step #19 - "compile-libfuzzer-address-x86_64": # github.com/cilium/ebpf/internal/btf
Step #19 - "compile-libfuzzer-address-x86_64": vendor/github.com/cilium/ebpf/internal/btf/fuzz.go:20:15: undefined: loadNakedSpec
Step #19 - "compile-libfuzzer-address-x86_64": 2023/09/13 14:07:12 failed to build packages:exit status 2
Step #19 - "compile-libfuzzer-address-x86_64": ********************************************************************************
Step #19 - "compile-libfuzzer-address-x86_64": Failed to build.
Step #19 - "compile-libfuzzer-address-x86_64": To reproduce, run:
Step #19 - "compile-libfuzzer-address-x86_64": python infra/helper.py build_image kubeedge
```

This seems unrelated, @AdamKorcz can you confirm?

**Comment by jonathanmetzman** [comment]
This failed also here: https://github.com/google/oss-fuzz/pull/10920 must be a FP.
Let me merge that PR first and then reconfirm this works.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py go --sanitizer address coverage --fuzzing-engines libfuzzer

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
