### PR TITLE
Add skia-ftz

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Add a variant of skia that will use -l:crtfastmath to find ffast-math issues.
This is @moyix's idea and I implemented it for him so he wouldn't have to deal with ossfuzz

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@moyix did I do this right: https://github.com/google/oss-fuzz/pull/8464/files#diff-b963ecaea13e3c22734e5a2e91080d8c1dd64bc8222a1d26d867bb5c5cb27a10R66

**Comment by moyix** [comment]
> @moyix did I do this right: https://github.com/google/oss-fuzz/pull/8464/files#diff-b963ecaea13e3c22734e5a2e91080d8c1dd64bc8222a1d26d867bb5c5cb27a10R66

Looks right to me :) If you want to be sure you can do

```
objdump --disassemble=set_fast_math
```

on one of the fuzzer binaries it generates and check that it includes the `set_fast_math` constructor:

```
$ objdump --disassemble=set_fast_math out/asan/api_polyutils 

out/asan/api_polyutils:     file format elf64-x86-64


Disassembly of section .text:

000000000069e0d0 <set_fast_math>:
  69e0d0:       f3 0f 1e fa             endbr64 
  69e0d4:       0f ae 5c 24 fc          stmxcsr -0x4(%rsp)
  69e0d9:       81 4c 24 fc 40 80 00    orl    $0x8040,-0x4(%rsp)
  69e0e0:       00 
  69e0e1:       0f ae 54 24 fc          ldmxcsr -0x4(%rsp)
  69e0e6:       c3                      retq   
```

**Comment by jonathanmetzman** [comment]
I disassembled a few of them and they had it. objdump --disassemble=set_fast_math build/out/skia-fast-math/* | grep fast_math | wc -l turns up 39

**Comment by jonathanmetzman** [comment]
@oliverchang SHould this be fuzzed on OSS-Fuzz already?

**Comment by oliverchang** [comment]
This is likely a continuation of https://github.com/google/clusterfuzz/issues/2775. There was likely some race condition between my cleanup of the existing IAM roles and deployment. I'll kick off the cleanup again, which should unblock this.

**Comment by jonathanmetzman** [comment]
Still no job or builds.

**Pull request merged**
