### PR TITLE
Add Rust-specific setup instructions

### PR DESCRIPTION
**Pull request by alexcrichton**
This is a follow-up to [this comment][1] which provides some intro docs
for how to get started quickly with a Rust project, explaining `cargo
fuzz` and some basic setup steps.

[1]: https://github.com/google/oss-fuzz/issues/3383#issuecomment-642137449

### CODE REVIEW

**Comment by alexcrichton** [comment]
> Do you enable memory sanitizer with wasmtime

Currently I don't think we explicitly do, but I don't think there's any reason for that beyond we just didn't realize it's something to do. I think we'll need to tweak the instructions to pass the right `--sanitizer` argument to `cargo fuzz build`, but beyond that it may just work!

According to https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html#example though it may require recompiling the standard library which currently isn't done.

> Is there any reason why leaksanitizer is seperate in Rust than addresssanitizer 

I'm not sure myself, but given that Rust's sanitization support is intended to simply mirror clang's, this is probably a bug worth filing for upstream rustc.

**Comment by inferno-chromium** [comment]
> > Do you enable memory sanitizer with wasmtime
> 
> Currently I don't think we explicitly do, but I don't think there's any reason for that beyond we just didn't realize it's something to do. I think we'll need to tweak the instructions to pass the right `--sanitizer` argument to `cargo fuzz build`, but beyond that it may just work!

Does it not use RUSTFLAGS, we pass that already, so you can try enabling memory for wasmtime ?

export RUSTFLAGS="--cfg fuzzing -Zsanitizer=${SANITIZER} -Cdebuginfo=1 -Cforce-frame-pointers"
https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/compile#L71

> 
> According to https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html#example though it may require recompiling the standard library which currently isn't done.
> 
> > Is there any reason why leaksanitizer is seperate in Rust than addresssanitizer
> 
> I'm not sure myself, but given that Rust's sanitization support is intended to simply mirror clang's, this is probably a bug worth filing for upstream rustc.

Location to file bug ?

**Comment by alexcrichton** [comment]
> Does it not use RUSTFLAGS, we pass that already, so you can try enabling memory for wasmtime ?

Aha good point! It looks like [that's all `cargo fuzz` does anyway](https://github.com/rust-fuzz/cargo-fuzz/blob/87c36a1deee8ca9b550fe034623a7445d7e8c770/src/project.rs#L163-L169) so you're right, there's no need to tweak the `cargo fuzz` invocation with `RUSTFLAGS` already set.

To enable for wasmtime should we just expand the `project.yaml`? Or is there anything else to do?

> Location to file bug ?

https://github.com/rust-lang/rust/issues/new is likely the best place for that.

**Comment by inferno-chromium** [comment]
> > Does it not use RUSTFLAGS, we pass that already, so you can try enabling memory for wasmtime ?
> 
> Aha good point! It looks like [that's all `cargo fuzz` does anyway](https://github.com/rust-fuzz/cargo-fuzz/blob/87c36a1deee8ca9b550fe034623a7445d7e8c770/src/project.rs#L163-L169) so you're right, there's no need to tweak the `cargo fuzz` invocation with `RUSTFLAGS` already set.
> 
> To enable for wasmtime should we just expand the `project.yaml`? Or is there anything else to do?

just add "- memory" in the sanitizers field.

> 
> > Location to file bug ?
> 
> https://github.com/rust-lang/rust/issues/new is likely the best place for that.

Ok, filed https://github.com/rust-lang/rust/issues/73294

**Pull request merged**
