### PR TITLE
Fixes code coverage for gitoxide

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
CC @Byron

**Comment by silvergasp** [comment]
I've tested this locally and this should fix https://github.com/Byron/gitoxide/issues/719

**Review by Byron — APPROVED** [review]
Thank you, LGTM.
`auto_ccs` seems like a great idea, too.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by silvergasp** [comment]
> Hi @silvergasp @Byron did this fix work for you? I'm getting the same error as this for wasmer( a rust project). In my case coverage build is working fine, but the `infra/helper.py coverage` throws error as `thread/local.rs no such file or directory`

Nope, still having issues... I've got a few more things to try, but if those don't work I'll open an issue with oss-fuzz tommorow.

**Pull request merged**
