### PR TITLE
[django] Fixed pyinstaller creation to include neccessary translations.

### PR DESCRIPTION
**Pull request by apollo13**
This fixes https://oss-fuzz.com/testcase-detail/6112062398398464

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Can you push again? CI seems borked

**Comment by jonathanmetzman** [comment]
Just force push or make a dummy commit please.

**Comment by apollo13** [comment]
Done, let's see…

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
