### PR TITLE
[nestegg] Add Dockerfile and build.sh

### PR DESCRIPTION
**Pull request by tysmith**

### CODE REVIEW

**Comment by tysmith** [comment]
Thanks Kostya!

**Comment by kcc** [comment]
This doesn't compile :( 

```
clang-7: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
src/nestegg.c:434:3: error: cannot initialize a member subobject of type 'enum ebml_type_enum' with an rvalue of type 'int'
  E_LAST
  ^~~~~~
```
Probably because we attempt to build a C file with clang++, should be easy fix

**Comment by kcc** [comment]
Pushed the fix: https://github.com/google/oss-fuzz/commit/cccb5e9450dff3987178d0fad4c5d05bb895477b
build.sh also use wrong paths to the tests. 

next time you change something here, please use the following command to verify correctness of the scripts:
```
./infra/helper.py build_image nestegg && ./infra/helper.py build_fuzzers nestegg
```

**Comment by kcc** [comment]
Seems to be working fine!

**Pull request merged**
