### PR TITLE
Upgrade to Go 1.22

### LINKED ISSUE #11661: Upgrade to Golang 1.22
Opening a tracking issue for upgrade of Go 1.22. I assume this would look something like https://github.com/google/oss-fuzz/pull/10920, though I am not an expert here.

### PR DESCRIPTION
**Pull request by justindhillon**
New version of Go came out, so I have upgrade the version used in this project from 1.21 --> 1.22.

This PR is very similar to #10920

This fixes #11661

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py go --engine libfuzzer --sanitizer address

**Comment by justindhillon** [comment]
> /gcbrun trial_build.py go --engine libfuzzer --sanitizer address

I'm sorry, what does this mean?

**Comment by DavidKorczynski** [comment]
> 
> I'm sorry, what does this mean?

It's something internal to do testing on the infrastructure (please don't type the commands as one needs permissions)

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py go --fuzzing-engines libfuzzer --sanitizers coverage address

**Comment by jonathanmetzman** [comment]
I think this introduces a build error in cryptofuzz but otherwise looks OK to merge.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py golang litmuschaos --fuzzing-engines libfuzzer --sanitizers coverage address

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py golang litmuschaos --fuzzing-engines libfuzzer --sanitizers coverage address

**Comment by jonathanmetzman** [comment]
@catenacyber @guidovranken @AdamKorcz Could one of you PTAL at the golang failures caused by this PR? It's the only project that is failing.

**Pull request merged**
