### PR TITLE
[libvips] Add libjxl (for JPEG-XL) as a dependency

### PR DESCRIPTION
**Pull request by lovell**
/cc @jcupitt

### CODE REVIEW

**Comment by jcupitt** [comment]
This could well explode! But let's try it.

**Comment by lovell** [comment]
It looks like some of the address sanitisers are failing to link properly. I tried adding `-DCMAKE_THREAD_LIBS_INIT="-lpthread" -DCMAKE_USE_PTHREADS_INIT=1` but hit the next wall:
```
/usr/local/lib/clang/12.0.0/lib/linux/libclang_rt.asan-x86_64.a(asan_linux.cpp.o): In function `__asan::AsanDoesNotSupportStaticLinkage()':
/src/llvm-project/compiler-rt/lib/asan/asan_linux.cpp:88: undefined reference to `_DYNAMIC'
```
I'll update this PR to conditionally skip the libjxl dependency for address sanitisers until we can work out what's failing. That should also hopefully reduce the initial bug count ;)

**Comment by lovell** [comment]
Everything is linking properly now (there was a libbrotli-dev version mismatch) so prepare for the deluge.

**Review by DavidKorczynski — APPROVED** [review]
LGTM!

**Pull request merged**
