### PR TITLE
Fix helper.py

### PR DESCRIPTION
**Pull request by jonathanmetzman**
https://github.com/google/oss-fuzz/pull/4774 added python3-only code. 
This PR makes code compatible with Python2. 
Fixes https://github.com/google/oss-fuzz/issues/4792

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
TBR

**Review by inferno-chromium — COMMENTED** [review]
Thanks a lot!

**Comment by oliverchang** [comment]
Thanks! I do think we shouldn't put too much effort into supporting python 2 anymore though. It's EOL and we should just only support Python 3.

**Comment by jonathanmetzman** [comment]
OK. I'll probably revert these changes and change shebang to python3.

**Pull request merged**
