### PR TITLE
Adds project fast-dds

### PR DESCRIPTION
**Pull request by catenacyber**
cc @EduPonz @MiguelCompany
Would you be interested in continuous fuzzing for fast-dds ?
This PR enables it with one simple fuzz target about `processCDRMsg` where previous bugs had been found by fuzzing

### CODE REVIEW

**Review by MiguelCompany — APPROVED** [review]
@catenacyber This is awesome! Thanks!

**Comment by jonathanmetzman** [comment]
@catenacyber or @MiguelCompany could you please explain who are some of the big users of fast-dds?
Is it widely used? Are there some big companies that use it? Why would you say this is critical software?

**Comment by EduPonz** [comment]
Hi @joachimmetz ,

Fast DDS is the default middleware in all ROS 2 releases, and as such it has a rather large user-based in the robotics community, both among education, research, industry and hobbyists. Looking at the ROS 2 Technical Steering Committee members, you'd find several of the biggest corporations in the world, such as Microsoft, Samsung, Bosch, Sony, etc. We'd say that Fast DDS is critical software since many robotics industrial deployments are using it through ROS 2. Furthermore, we have direct costumers in various sectors such as robotics, defense, aeronautics, etc.

Please do not hesitate in asking for more detailed information if you need it!

**Comment by joachimmetz** [comment]
@EduPonz I assume you mean @jonathanmetzman

**Comment by jonathanmetzman** [comment]
> Hi @joachimmetz ,
> 
> Fast DDS is the default middleware in all ROS 2 releases, and as such it has a rather large user-based in the robotics community, both among education, research, industry and hobbyists. Looking at the [ROS 2 Technical Steering Committee](https://docs.ros.org/en/foxy/Governance.html) members, you'd find several of the biggest corporations in the world, such as Microsoft, Samsung, Bosch, Sony, etc. We'd say that Fast DDS is critical software since many robotics industrial deployments are using it through ROS 2. Furthermore, we have direct costumers in various sectors such as robotics, defense, aeronautics, etc.
> 
> Please do not hesitate in asking for more detailed information if you need it!

This is sufficient. Thanks!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
