### PR TITLE
Add casync project

### PR DESCRIPTION
**Pull request by keszybz**
The necessary counterpart in casync:
https://github.com/systemd/casync/pull/193.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Looks cool. Who are some of the project's users?

**Comment by keszybz** [comment]
It's still a fairly young project, so people are more in the phase of experimenting with it rather then using it in production. Also, right now it only has a command-line API, with a library interface planned for later, so dependencies are not strictly visible. Thus, I can't point out many public references, but it's certainly interest and experimentation

We have packages for major distros (https://packages.debian.org/sid/casync, https://src.fedoraproject.org/rpms/casync, https://aur.archlinux.org/packages/casync), and various talks on conferences (e.g. https://www.youtube.com/watch?v=9o5mFTE6KJc from AllSystemsGo this year, https://www.youtube.com/watch?v=9o5mFTE6KJc at fosdem). Other people are experimenting with distributing OS images (for containers and such).

**Comment by poettering** [comment]
@jonathanmetzman At Red Hat we have a project for using casync for OCI/containers. And Collabora has a project for this too, right, @elboulangero

**Comment by elboulangero** [comment]
@jonathanmetzman Yep we also use casync at Collabora. Additionally the [RAUC](https://github.com/rauc/rauc) updater can be used with casync, to there might be people from Pengutronix using it as well, right @ejoerns?

**Comment by ejoerns** [comment]
Yes, we do have support for casync in RAUC, the embedded Linux update framework. For those who are interested: https://rauc.readthedocs.io/en/latest/advanced.html#rauc-casync-support. This is the only use case we have for it until now, but I assume this to be a fairly good one case already ;)

**Comment by jonathanmetzman** [comment]
Thanks all, this seems widely used enough to me.

**Pull request merged**
