### PR TITLE
Cancel CFLAGS temporarly for capstone

### PR DESCRIPTION
**Pull request by catenacyber**
To build standalone shared library for python bindings

Following #1527 
See https://github.com/aquynh/capstone/pull/1188 as well

@jonathanmetzman what do you think ?

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Not sure. Where is `test_corpus.py` and what does it do? It compiles something?

**Comment by catenacyber** [comment]
https://github.com/aquynh/capstone/blob/master/suite/test_corpus.py

It creates the corpus out of the unit tests samples
(see https://github.com/aquynh/capstone/blob/master/suite/test_mc.py for the unit tests)

**Comment by jonathanmetzman** [comment]
How does `CFLAGS` affect it though? Theres some library that gets compiled when the capstone module is imported?

**Comment by catenacyber** [comment]
Well seen. CFLAGS are used when the library is compiled.
But problem arises when library is imported (see #1527 for example)

**Comment by jonathanmetzman** [comment]
>But problem arises when library is imported (see #1527 for example)

Right, I was just trying to come up with a possible explanation for why the change made sense.
I guess the explanation didn't work because the change had the issue you fixed. 

Just confirming, did this change solve the issue for you locally?

**Comment by catenacyber** [comment]
I can not test locally for the moment, but I remembered that I was not having this issue at all locally since #1527.

**Pull request merged**
