### PR TITLE
[clib] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds initial integration of clib.

We are currently working with upstream maintainers on the fuzzer.

@jwerle @stephenmathieson @Isty001 I am tagging you to let you know of these integration files in this PR. They will allow OSS-fuzz to run the fuzzer in https://github.com/clibs/clib/pull/224 once it has been merged in. If you have any questions, feel free to ask them here or in the PR on the clib repository.

### CODE REVIEW

**Comment by stephenmathieson** [comment]
Just merged https://github.com/clibs/clib/commit/e9573338c8b7ae9858d51f262b78f4d46161f28d in. I don't know what next steps are. Let me know if you need anything else from the `clib` side of things!

**Comment by AdamKorcz** [comment]
@stephenmathieson Thank you for the heads up! To finalize the integration we need at least one maintainers email address for the `project.yaml` file. All email addresses added in project.yaml have access to bugs reports. Please note that I have added myself to see the integration through to completion, and this means that I will be able to see bug reports as well including security vulnerabilities. If you prefer me off the list, I will be happy to remove my email, but it will also mean that I will not have access to fuzzing stats either which is useful for me at this stage.

**Comment by jwerle** [comment]
@stephenmathieson @AdamKorcz feel free to include me and @isty001 too :pray:

**Comment by AdamKorcz** [comment]
@jwerle Sure! Could you please share your and @Isty001's email addresses here?

**Comment by jwerle** [comment]
@AdamKorcz joseph.werle@gmail.com isty001@gmail.com

**Comment by AdamKorcz** [comment]
@inferno-chromium Would you be so kind and take a look at this one? It is ready for review.

**Comment by stephenmathieson** [comment]
> Please note that I have added myself to see the integration through to completion, and this means that I will be able to see bug reports as well including security vulnerabilities.

I have no objections to this, and it seems the other Clib maintainers are comfortable with it too.

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
