### PR TITLE
Use hdf5_1_14 for fuzzing

### PR DESCRIPTION
**Pull request by sashashura**
Requires https://github.com/tbeu/matio/pull/211 /cc @tbeu 

The following OSS-Fuzz issues are not reproducible with the latest HDF5. I.e. most probably were found and fixed independently. By fuzzing with the latest version of HDF5 they will be automatically closed in OSS-Fuzz.

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29776
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53690
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37185
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41590
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39869
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38041
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=45177
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37536
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30749
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=38686
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41318
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=30184
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=37318
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=41576

### CODE REVIEW

**Review by tbeu — COMMENTED** [review]
I'd prefer to always used tagged releases of zlib and hdf5 dependencies. Otherwise it is likely to observe errors due to development changes.

**Comment by tbeu** [comment]
> As a side note zlib is consumed from master currently.

I am aware of it. zlib author M. Adler only pushes releases from develop branch to master. Hence, fine to keep it as is.

**Comment by sashashura** [comment]
Do you approve the usage of the hdf5_1_14 branch?

**Comment by tbeu** [comment]
How often is the Docker image built?

**Review by tbeu — APPROVED** [review]

**Comment by sashashura** [comment]
The image is built every time OSS-Fuzz starts over fuzzing. Approximately once per day https://oss-fuzz-build-logs.storage.googleapis.com/index.html#matio

**Comment by sashashura** [comment]
@jonathanmetzman could you please merge?

**Review by Alan32Liu — APPROVED** [review]

**Comment by Alan32Liu** [comment]
Sorry about the delay, we were occupied by another task.
Merged now.

**Comment by sashashura** [comment]
No worries, thank you!

**Pull request merged**
