### PR TITLE
Reland "Upload per target coverage report. (#7389)" (#7400)"

### PR DESCRIPTION
**Pull request by oliverchang**
Only upload per-target reports for C/C++.

This reverts commit 1ae57df24d9d0146d6a2486bdb6e01ca7157ccef.

### CODE REVIEW

**Review by Alan32Liu — APPROVED** [review]
LGTM

**Review by jonathanmetzman — COMMENTED** [review]
lgtm

**Comment by rlohning** [comment]
Will these reports be generated and shown online automatically or do I need to configure anything? Can I find convenient links anywhere? The Fuzzer Statistics for Qt seem to link to the global coverage reports only.

**Comment by jonathanmetzman** [comment]
We haven't linked to it publicly yet. But the per target reports are being generate for qt.
See https://storage.googleapis.com/oss-fuzz-coverage/qt/reports-by-target/20220325/qtsvg_svg_qsvgrenderer_render/linux/report.html for example.

**Comment by jonathanmetzman** [comment]
But I agree we should link to it from somewhere otherwise its worthless

**Comment by rlohning** [comment]
Thank you for the link.

There seems to be something wrong, though:
While the coverage of the actual library code seems reasonable, LLVMFuzzerTestOneInput functions of _other_ fuzzers seem to be covered in all reports. An example following the link you posted is https://storage.googleapis.com/oss-fuzz-coverage/qt/reports-by-target/20220325/qtsvg_svg_qsvgrenderer_render/linux/src/qtbase/tests/libfuzzer/corelib/text/qregularexpression/optimize/main.cpp.html

Should I search for mistakes in my build script or might the data be imprecise?

**Comment by rlohning** [comment]
Might this happen because I build all the fuzzers in the same path? I mean, it's always a clean directory, but it always has the same name. It's like:

```
for all fuzzers:
    mkdir build_dir
    cd build_dir
    build current fuzzer
    copy current fuzzer to $OUT
    cd ..
    rm -r build_dir
```

Should I use build directories with individual names instead?

**Comment by rlohning** [comment]
I do now, and it doesn't make difference.

**Comment by rlohning** [comment]
> functions of other fuzzers seem to be covered in all reports

Looks fine now. Thank you.

**Pull request merged**
