### PR TITLE
[envoy] fix envoy build

### PR DESCRIPTION
**Pull request by asraa**
Fix envoy build. A recent bump in our absl library along with changing to C++17 caused a build failure.

Tested this locally with undefined sanitizer, hoping to wait for address/undefined to pass on CI.

Signed-off-by: Asra Ali <asraa@google.com>

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
merging when CI completes.

**Comment by asraa** [comment]
Thanks! It looks like I messed up when I was in the shell debugging. only address works, undefined is still broken. Will push an update.

**Comment by asraa** [comment]
Should be all set now. The problem was Absl library uses these macros to enable address sanitizer builds, we were using those for all builds (including ubsan). That broke our ubsan build.
Fix: filter those options for only address sanitizer builds

**Comment by asraa** [comment]
Looks like address/undefined/coverage are now good to go locally!

**Comment by Dor1s** [comment]
> merging when CI completes.

Is CI now able to complete the builds for large projects such as envoy? I remember Travis was timing out.

**Comment by asraa** [comment]
It looks like they timed out on my previous runs, but sometimes the address one will finish in time.

**Comment by Dor1s** [comment]
Thanks @asraa, in such case I think we can just merge this, given that you tested locally.

**Pull request merged**
