### PR TITLE
Update ownership of Meta projects.

### PR DESCRIPTION
**Pull request by mhlakhani**
I'll no longer be working on fuzzing at Meta, so updating the ownership lists to add more folks from my team.
I added the vendor_cc list where it was missing.
I also removed a few employees that no longer are at Meta from the proxygen project list.

### CODE REVIEW

**Comment by mhlakhani** [comment]
The build failures are pre-existing and outside the scope of this PR I believe

**Comment by jonathanmetzman** [comment]
> I'll no longer be working on fuzzing at Meta, so updating the ownership lists to add more folks from my team. I added the vendor_cc list where it was missing. I also removed a few employees that no longer are at Meta from the proxygen project list.

Ah sad. Don't be a stranger!

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by mhlakhani** [comment]
> Ah sad. Don't be a stranger!

Will still stay in touch and be around!

**Pull request merged**
