### PR TITLE
update zlib-ng git repo path

### PR DESCRIPTION
**Pull request by sebpop**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
please sign the cla and then we can merge. i thought you did sign it at some point, is this pr with a different email ?

**Comment by sebpop** [comment]
I moved from samsung to amazon.
I opened an internal ticket to get permission to sign the cla and be able to continue contributing to oss-fuzz.

**Comment by inferno-chromium** [comment]
to unblock you, i committed this simple change - https://github.com/google/oss-fuzz/commit/d4e47289000325d64273f89593a148d49ca2a91c. thanks for applying for cla.

**Comment by sebpop** [comment]
Thanks!
I will be signing the cla in the next few days.

**Comment by sebpop** [comment]
My email address was added to the Amazon CCLA Authorized Contributors group.

**Pull request closed without merging**
