### PR TITLE
Fix bad build check breakage

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
I wonder why CI didn't catch this earlier in: https://github.com/google/oss-fuzz/pull/8188

**Comment by jonathanmetzman** [comment]
Looks like we weren't testing changes to base-runner correctly.

**Comment by jonathanmetzman** [comment]
Lol there looks like some ubuntu apt outage now

**Comment by jonathanmetzman** [comment]
> Looks like we weren't testing changes to base-runner correctly.

Fix https://github.com/google/oss-fuzz/pull/8199

**Comment by jonathanmetzman** [comment]
Build failures are Ubuntu's fault

**Review by oliverchang — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

**Pull request merged**
