### PR TITLE
xxhash: Initial integration

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
cc Primary author: @Cyan4973

**Comment by silvergasp** [comment]
xxhash is a popular hashing library that is critical to global IT infrastructure. It is used in various high profile projects including;
- [ceph/ceph](https://github.com/ceph/ceph/tree/03caf0772e4ab97b73a0ada383a6f73721c601b7/src)
- [envoyproxy/envoy](https://github.com/envoyproxy/envoy/blob/448cbd60ee4e1af1f869f9f519095680b233f1e2/source/common/common/hash.h#L14)
- [Clickhouse/Clickhouse](https://github.com/ClickHouse/ClickHouse/blob/07ba672e37221195ee3430fd38e0f118d802babe/src/Functions/FunctionsHashingMisc.cpp#L41)
- [nem0/LumixEngine](https://github.com/nem0/LumixEngine)

**Comment by DavidKorczynski** [comment]
This was previously suggested, but was considered too small -- https://github.com/google/oss-fuzz/pull/4982

Maybe CFLite would be more appropriate

**Comment by silvergasp** [comment]
No worries. Not sure how I missed that. Shall I close this out then?

**Comment by silvergasp** [comment]
>This was previously suggested, but was considered too small -- https://github.com/google/oss-fuzz/pull/4982

Out of interest what where does a repo go from `small->to_small_to_be_worth_integrating` ?

**Comment by DonggeLiu** [comment]
> No worries. Not sure how I missed that. Shall I close this out then?

Yep, thanks!

> Out of interest what where does a repo go from small->to_small_to_be_worth_integrating ?

The panel discusses this case-by-case : )

**Pull request closed without merging**
