### PR TITLE
[qt] Get a shallow clone of qtbase

### PR DESCRIPTION
**Pull request by rlohning**
Reduces the size by more than 270 MB

### CODE REVIEW

**Comment by rlohning** [comment]
Seems to fail because of old git: https://stackoverflow.com/questions/2144406/how-to-make-shallow-git-submodules

**Comment by inferno-chromium** [comment]
can you update git version in your DockerFile. we can update in base image later.

**Comment by rlohning** [comment]
This is not urgent, I can wait.

**Comment by Dor1s** [comment]
I don't think we're going to update the git in the base images any time soon, so if this requires any custom version it'd be better to install it in per project basis.

**Pull request closed without merging**
