### PR TITLE
Centipede fixes.

### PR DESCRIPTION
**Pull request by oliverchang**
- Replace newlines with spaces in centipede/clang-flags.txt. Build
  systems don't like them.

- Fix a missing newline in output logs.

### CODE REVIEW

**Review by Alan32Liu — APPROVED** [review]
Thanks!

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Review by jonathanmetzman — COMMENTED** [review]
LGTM

**Pull request merged**
