### PR TITLE
[apache-commons] Initial integration

### PR DESCRIPTION
**Pull request by fmeum**
Please wait for @bodewig (who is [bodewig at apache](https://lists.apache.org/thread.html/r67968b72b85fd42046d4483c2588116b89f6fe6ede968e70d4bb0772%40%3Cdev.commons.apache.org%3E)) to sign off on this PR.

### CODE REVIEW

**Review by bodewig — APPROVED** [review]
LGTM

**Comment by DavidKorczynski** [comment]
I think it would make sense to combine this project with the one in your other PR https://github.com/google/oss-fuzz/pull/5632 - then simply use a `commons` or `apache-commons` project. Similar to how we do with the Servo project https://github.com/google/oss-fuzz/blob/master/projects/servo/Dockerfile

**Comment by fmeum** [comment]
> I think it would make sense to combine this project with the one in your other PR #5632 - then simply use a `commons` or `apache-commons` project. Similar to how we do with the Servo project https://github.com/google/oss-fuzz/blob/master/projects/servo/Dockerfile

I'm open to doing this, but don't know whether it fits the project structure that well. Apart from being part of the Apache Commons collection of libraries, imaging and compress don't seem to have much in common (separate set of core developers, relatively unrelated scopes). But I also don't know the project internals that well, @bodewig could you say more about this?

Would merging the projects into one have any technical implications?

**Comment by DavidKorczynski** [comment]
Hmm - is this somewhat comparable to boost? We have a single project for boost as well https://github.com/google/oss-fuzz/blob/master/projects/boost/Dockerfile which in itself is an umbrella repository for all the affiliated libraries (https://github.com/boostorg/boost/tree/master/libs)

**Comment by fmeum** [comment]
> Hmm - is this somewhat comparable to boost? We have a single project for boost as well https://github.com/google/oss-fuzz/blob/master/projects/boost/Dockerfile which in itself is an umbrella repository for all the affiliated libraries (https://github.com/boostorg/boost/tree/master/libs)

Yes, it's more comparable to Boost. Unlike Boost, it doesn't have a common source code repository though that I could list as `main_repo` ([this](https://gitbox.apache.org/repos/#commons) is the list of all repos). Do you have a recommendation on how to handle that situation in the `project.yaml`? Would the affected revision detection still work?

**Comment by DavidKorczynski** [comment]
Given that there are 51 associated repos with apache commons I think the idea of an umbrella repository holds (let's assume we are going to integrate all then it becomes tedious with 51 different project folders). This is unless there are some technical aspects that would make it not possible or say organisational, e.g. embargo on security issues. With regards to `main_repo` I would just pick one of the repos and then leave it at that.

**Comment by fmeum** [comment]
@DavidKorczynski I pushed a new commit that merges the two PRs into the current one.

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski I pushed a new commit that merges the two PRs into the current one.

Awesome, thanks!

**Review by DavidKorczynski — APPROVED** [review]

**Comment by bodewig** [comment]
Just to answer the question (I'm fine with how you've set things up): the Apache Commons project has a shared governance structure with the Project Management Committee being responsible for oversight. All projects share the same processes for handling security issues and we've deliberately set up a shared mailing list for reports of all components.

The development communities of the individual components sometimes overlap but it is pretty common that some people concentrate on a single component or a handful of them. It will be the responsibility of the people subscribed to the fuzz-testing@commons list to nudge the component developers if necessary.

**Pull request merged**
