### PR TITLE
infra: bump fuzz introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Contains bug fixes for failed Python and Java projects

### CODE REVIEW

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
The second bump broke almost everywhere because of a race condition where introspector needs coverage to be run earlier that day

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
Lots of build failures.

**Comment by jonathanmetzman** [comment]
zxing
zip4j
xz-java
xmlpull
xerces
unit
stringtemplate4
spring-retry
snappy-java
snakeyaml
slf4j-api
python-email-validator
protobuf-python
numexpr
lark-parser
kryo
jupyter-nbconvert
junrar
jul-to-slf4j
jsoup
json-smart-v2
json-sanitizer
json-java
jsign
jline3
jettison
jdom
javassist
jakarta-mail-api
gson
greenmail
cron-utils
cbor-java
apache-felix-dev
apache-commons-logging
apache-commons-lang
apache-commons-io
apache-commons-imaging
apache-commons-geometry
apache-commons-csv
apache-commons-compress
apache-commons-codec
apache-commons-cli
antlr4-java
antlr3-java

**Comment by DavidKorczynski** [comment]
> Contains bug fixes for failed Python and Java projects

Thanks! We should have addressed those now -- in particular the ones that succeeded already.

In addition to this we also added return types for functions in the `summary.json` which can be digested by the web app APIs.

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by DavidKorczynski** [comment]
Did the projects succeed now? If it's just timeouts that causes the red cross then this has happened before: https://github.com/google/oss-fuzz/pull/10007#issuecomment-1498537785

**Comment by jonathanmetzman** [comment]
This failed again due to the race condition I mentioned before.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
Latest trial build timed out on:

```
Step #1: INFO:root:Polling: defaultdict(<class 'list'>, {'hsqldb': ['f8811ae3-2c86-4dbb-ad28-a446e0c4b482'], 'openssl': ['c1cd969f-fce2-4b40-9fb6-31f6b439df6d'], 'spring-retry': ['2a766711-a0d9-4cb1-94f0-c2442be69529'], 'toolbelt': ['5b25c962-5486-4649-825e-68b031cf6075'], 'tor': ['377d981e-29b5-4848-accc-95f9493a636e']})
```

Which seems small enough.

@jonathanmetzman @hogo6002 I think we need a smarter way to handle these timeouts as part of the new trial build output improvements. e.g. if a build is known to be fairly slow we can skip marking those as blockign failures.

**Comment by oliverchang** [comment]
(sorry for the slow turnaround on these btw! @hogo6002 is working on some UX fixes to make these failures surfaced to the public).

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
@DavidKorczynski can you please take a look at the failure / timeout logs? The GitHub logs should be much improved now and provide public links to the failed project builds.

**Comment by oliverchang** [comment]
@DavidKorczynski friendly ping!

**Comment by DavidKorczynski** [comment]
Apologies for the delay! The new info looks nice, thank you!

Am slightly confused about some of the specifics, so will write a bit verbose in case I get something wrong. I'll write it in a comment below, but at the moment all java projects are currently failing Fuzz Introspector following https://github.com/google/oss-fuzz/pull/10538

```bash
Step #6 - "compile-libfuzzer-introspector-x86_64": ---------------------------------------------------------------
Step #6 - "compile-libfuzzer-introspector-x86_64": chmod: cannot access '/workspace/out/libfuzzer-introspector-x86_64/jazzer_driver_with_sanitizer': No such file or directory
Step #6 - "compile-libfuzzer-introspector-x86_64": ********************************************************************************
```

There is a missing "introspector" conditional in https://github.com/google/oss-fuzz/blob/6922c8c1ac27c9a459ce41201991e296a6bace54/infra/base-images/base-builder/compile#L152-L171

This causes line 171 to fail.

You can search for "jvm" in the table here https://introspector.oss-fuzz.com/indexing-overview which will show the introspector build status is red for all.

**Comment by oliverchang** [comment]
Thanks for the analysis and feedback! CC @jonathanmetzman @hogo6002 for the feedback on the trial build logs. At the very least perhaps we need to clarify that the timeout for the trial build is shorter than the timeout for the actual underlying builds, which is why some builds end up succeeding even if the trial build times out.

**Pull request merged**
