### PR TITLE
[expat] Build 6 fuzz targets for different encoding types.

### PR DESCRIPTION
**Pull request by Dor1s**
It obviously makes fuzzing faster and corpus should become more precise.

### CODE REVIEW

**Comment by Dor1s** [comment]
Reminder to myself: copy existing corpus into 6 new directories once we land this.

**Comment by inferno-chromium** [comment]
The explosion in number of fuzz targets worries me here! Lets see what others think.

**Comment by Dor1s** [comment]
Assuming that our computing resources do not change (i.e. the same number of CPUs will be shared between 6 different fuzz targets instead of one), the total execution speed won't change significantly, but, each fuzz target will be roughly 5-6 times faster than existing one. 

Regarding corpus, let's look at UTF-16BE and UTF-16LE, for example. BigEndian corpus doesn't make much sense for LowEndian encoding, and vice versa. But in current implementation, we put both variants to the same folder, and libFuzzer should understand all these significantly different data formats. So, when libFuzzer generates a new input which is valid only for BigEndian, it sees new coverage. This new coverage comes from `xmlReadMemory` call from a corresponding iteration of the loop (when BigEndian encoding has been used). All the other iteration are waste of time, as most likely they returned an error on the first bytes of the input. Also, due to different data formats stored in the same folder, libFuzzer can generate inputs that are useless for both encoding formats, e.g. a cross-over of BigEndian and LowEndian inputs, or concatenation of two testcases in different encoding.

I believe that faster execution speed together with smaller search spaces should increase speed of discovering new units.

And as we say: the smaller fuzz target is, the better it is :)

**Comment by kcc** [comment]
I agree with the above comment in general, but the existing fuzz target looks small enough already. 
Most likely this change *will* bring some value, but as any splitting will pose some difficulties 
(e.g. I hope that upstream will eventually take ownership of the fuzz targets: will it be easier
to convince them to take one or 6). 

May I ask you to perform a manual experiment: 
* take the existing converged corpus and verify that you can not easily gain any new coverage
* split the target into 6 and fuzz them for a few days
* see if the coverage for the original target has increased. If so, we'll have a good proof that splitting there is worth it.

**Comment by Dor1s** [comment]
I've noticed that there is a bug that we trigger too often with an existing corpus, so I've launched testing yesterday with an empty corpus.

### Existing version has been launched in the following configuration:
```bash
expat_xml_parse_fuzzer -print_final_stats=1 -rss_limit_mb=4096 -timeout=25 -max_total_time=57600 -jobs=6 -workers=6 -reload=3600 -dict=expat_xml_parse_fuzzer.dict ./empty_corpus_for_old_version
```
i.e. 6 processes, 16 hours total time, reload corpus directory every hour to be similar to what we do on CF.

Please note that I've removed `"INVALIDENCODING"` from existing version since it appears to be useless, there is no coverage. This could slightly speed up old version (6-in-1).

### New versions have been launched in the following way:
```bash
expat_xml_parse_%ENCODING%_fuzzer -print_final_stats=1 -rss_limit_mb=4096 -timeout=25 -max_total_time=57600 -dict=expat_xml_parse_fuzzer.dict ./c1_for_new
```
Separate empty corpus directories, the same dictionary, 16 hours.


# Summary
## General stats. Pruning and coverage done with existing 6-in-1 target.
```csv
Version   | testcases executed | avg. speed | new units | pruned | coverage |
============================================================================|
1 target  |    1,587,234,673   |    4,592   |   40,192  |  7,864 |   3,780  |
6 targets |    7,027,105,341   |   20,332   |   45,765  |  7,451 |   3,805  |
============================================================================|
delta, %  |           342.73   |   342.76   |    13.87  |  -5.25 |    0.66  |
```

I've got surprised by the size of pruned corpus, but after re-checking I'm sure that it's correct.
Thus, it looks like granular approach gives us smaller corpus with a better coverage.


## Pruning and coverage stats for different tartets.
```csv
           ||  CORPUS FROM OLD TARGET  || CORPUS FROM NEW TARGETS  ||    DELTA, %   |
Target     || # files | pruned |  cov. || # files | pruned | cov.  || pruned | cov. |
====================================================================================|
Old 6-in-1 ||  40,192 |  7,864 | 3,780 || 45,765  |  7,451 | 3,805 ||  -5.25 | 0.66 |
-----------||---------|--------|-------||---------|--------|-------||---------------|
UTF-16     ||  40,192 |  4,418 | 3,709 ||  7,603  |  4,577 | 3,728 ||   3.60 | 0.51 |
UTF-8      ||  40,192 |  6,065 | 3,741 ||  7,712  |  5,530 | 3,752 ||  -8.82 | 0.29 |
ISO-8859-1 ||  40,192 |  6,032 | 3,756 ||  7,660  |  5,416 | 3,737 || -10.21 |-0.51 |
US-ASCII   ||  40,192 |  5,810 | 3,746 ||  7,665  |  5,541 | 3,742 ||  -4.63 |-0.11 |
UTF-16BE   ||  40,192 |  4,423 | 3,708 ||  7,597  |  5,519 | 3,722 ||  24.78 | 0.38 |
UTF-16-LE  ||  40,192 |  4,419 | 3,708 ||  7,506  |  5,231 | 3,721 ||  18.38 | 0.35 |
```

Similar to what we've seen above. Smaller fuzz targets running on the same amount of CPUs give better coverage.

Regarding two cases `ISO-8859-1` and `US-ASCII`. They show negative coverage delta because these are simple 8-bit encodings. Thus, any trash data might be looking as something interesting for then, and they can get new coverage from other encoding.

**Comment by Dor1s** [comment]
I've just launched similar processes but with `max_len=5000`. Will see tomorrow what it shows. I expect the same results with a slightly bigger delta.

A few more thoughts on splitting targets.

Pros of smaller targets:
- smaller corpus directory: faster checkout/upload time, faster pruning
- if there is a stupid bug in one encoding, we'll be crashing only 1 / 6 of runs, not each run
- smaller and better dictionaries, as they use only proper encoding for each target

Cons of smaller targets:
- more directories in GCS (not an issue, everything gets created automatically)
- more jobs: corpus pruning, logs analysis (not an issue, they run once per day)

**Comment by Dor1s** [comment]
Despite the easy crash in the target, I've performed testing requested by @kcc in https://github.com/google/oss-fuzz/pull/431#issuecomment-284588628:

### Running the existing target (6-in-1) on converged corpus in 6 processes
* all processes crashed, average time to crash is **128s**
* generated **138 new units** in total
* gained **0 new coverage edges**
* peak rss mb is **2400+** for each process, i.e. all processes would simply die with OOM on CF

### Running 6 new targets on converged corpus, 1 process per target
 * all processes crashed, average time to crash is **152s**
 * generated **3851 new units** in total
 * each target gained new coverage, gain in **range [0.10% .. 0.13%]**
 * peak rss mb is in** range [1400 .. 1815]**, i.e. all targets would work on CF

### Coverage of the existing 6-in-1 target
 * on existing converged corpus: 4039
 * on corpus generated by existing target: 4039, **0% gain**
 * on corpus generated by 6 separate targets: 4045, **0.15% gain**

### Summary
A known crash in expat does not make it possible to run the experiment for a while, but anyway we can see several advantages of running separate fuzz targets:
 * they fit into `rss_limit_mb=2048`, while existing target does not
 * they generate much more new units
 * they are able to gain new coverage faster than the existing 6-in-1 target

**Comment by Dor1s** [comment]
Testing with an empty corpus and `-max_len=5000` (similarly to https://github.com/google/oss-fuzz/pull/431#issuecomment-284742942) has been very helpful to realize that I should convert the dictionaries. After 16 hours of fuzzing, `UTF-16LE` target has reached only 2357 cov. edges (compare it with 3700+ reached by other targets). But when I've converted the dictionary to `UTF-16LE`, the fuzz target reached 2400+ cov. edges in a couple of minutes.

**Comment by Dor1s** [comment]
I've updated the PR with dictionaries in different encodings. I'm quite confident to insist that we should split the target.

**Comment by Dor1s** [comment]
As a bonus, separate targets with converted dictionaries find that known crash in less than 1 hour (it took from 5.5 to 57 minutes for different runs) starting from an empty corpus. The existing target cannot find that crash even after 16 hours of fuzzing with 6 processes.

**Comment by Dor1s** [comment]
Is anybody against landing this?

**Comment by kcc** [comment]
Go for it, I think you have convincing data. Thanks!

**Comment by Dor1s** [comment]
Thanks! The build is successful. I've pruned existing corpus for each target and uploaded to the GCS. Let's see how it goes...

**Comment by inferno-chromium** [comment]
Ok size multiplies by the number of fuzz targets. Here might be ok, but lets push back on this for larger targets, see blow up in https://bugs.chromium.org/p/chromium/issues/detail?id=702485.

  expat-address-201703150200.zip	3.54 MB	application/zip	Multi-Regional	3/14/17, 7:09 PM	 
  expat-address-201703151018.zip	21.21 MB	application/zip	Multi-Regional	3/15/17, 4:23 AM

@kcc @mikea @oliverchang - fyi

**Pull request merged**
