### PR TITLE
Fix UBSAN error with function argument casting.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@nikias - just as fyi. Please do run the builds locally with ubsan config as well. One of the fuzzers crashes on an integer overflow really quick.

**Comment by nikias** [comment]
Will have a look, didn't realize. Also I fixed some issues already, when will it pick up the latest commits from git?

**Comment by inferno-chromium** [comment]
It automatically picks up new build multiple times a day (usually 3-4 times).

**Comment by nikias** [comment]
Just asking because I committed something ~12 hours ago and nothing changed.

**Comment by inferno-chromium** [comment]
You can reproduce the ubsan failure with

python infra/helper.py build_fuzzers -e SANITIZER=undefined libplist
python infra/helper.py run_fuzzer libplist xplist_fuzzer

Instantly crashes on 
xplist.c:989:37: runtime error: negation of -9223372036854775808 cannot be represented in type 'int64_t' (aka 'long'); cast to an unsigned type to negate this value to itself
    #0 0x470950 in node_from_xml /src/libplist/src/xplist.c:989:37
    #1 0x47231c in node_from_xml /src/libplist/src/xplist.c:1171:25
    #2 0x470003 in node_from_xml /src/libplist/src/xplist.c:937:21

ASAN build is not impacted and you might have already seen the awesome flow of bugs there :)

**Comment by nikias** [comment]
Already reproduced. Testing a fix.

**Comment by nikias** [comment]
And fixed in git master.

**Pull request merged**
