### PR TITLE
[infra] Extend set of UBSan checks enabled.

### PR DESCRIPTION
**Pull request by Dor1s**
Please don't land until #569 gets fixed.

### CODE REVIEW

**Comment by kcc** [comment]
I would be more careful and enable these one by one, and also with prior testing on some targets. 
Not all of the UBSAN features are equally well tested and may contain false positives (or at least report bugs that are unlikely to be fixed)

**Comment by Dor1s** [comment]
Ok, let's start with `bounds`, `float-divide-by-zero`, `integer-divide-by-zero`, `null`. I've tested them on several `ffmpeg` targets, `gnutls`, `freetype2`, nothing blows up so far.

**Comment by oliverchang** [comment]
For some reason, we're getting this error on several project (at leat libprotobuf-mutator, tmp2, libarchive)

```
clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=bool,bounds,float-divide-by-zero,function,integer-divide-by-zero,null,shift,signed-integer-overflow,vla-bound,vptr -fno-sanitize-recover=undefined -fsanitize-coverage=trace-pc-guard,trace-cmp -Wall -Werror -fPIC -c -MMD -MF /work/tpm2/ActivateCredential.d -o /work/tpm2/ActivateCredential.o ActivateCredential.c
clang-5.0: error: argument unused during compilation: '-fsanitize-coverage=trace-pc-guard,trace-cmp' [-Werror,-Wunused-command-line-argument]
```

Reverting this commit seems to fix the issue.. Could you please investigate Max? :)

**Comment by oliverchang** [comment]
(not reverting for now to prevent existing bugs from getting incorrectly closed)

**Comment by inferno-chromium** [comment]
To add to previous comments, targets broken include

strongswan
skia
libprotobuf-mutator
tpm2
libarchive
libteken

**Comment by Dor1s** [comment]
Strange... At least for libteken the error disappears if I remove `bounds` from `-fsanitize=`. Looking more into this.

**Comment by Dor1s** [comment]
Same thing for libarchive. But some targets don't have this issue. I guess that other flags (e.g. some `-W...`) affect this behavior.

**Comment by Dor1s** [comment]
Since we have 9 index-out-of-bounds bugs reported over 4 different targets, I still don't want to simply remove that flag and hope to fix clang (lol).

The warning comes from here: https://github.com/llvm-mirror/clang/blob/f2ee5f1a8ec33b9bab98782596fe6872a6da7cc0/lib/Driver/Driver.cpp#L2808

**Comment by Dor1s** [comment]
`bounds` check consists of two different "sanitizers":
```cpp
SANITIZER_GROUP("bounds", Bounds, ArrayBounds | LocalBounds)
```

they are:

```cpp
SANITIZER("array-bounds", ArrayBounds)
// <...>
SANITIZER("local-bounds", LocalBounds)
```

`ArrayBounds` works fine with `fsanitize-coverage=` option, only `LocalBounds` causes that problem.

**Comment by Dor1s** [comment]
If we don't use `local-bounds` (or `bounds` group), `fsanitize-coverage` argument is being claimed here: https://github.com/llvm-mirror/clang/blob/f2ee5f1a8ec33b9bab98782596fe6872a6da7cc0/lib/Driver/SanitizerArgs.cpp#L508

When `local-bounds` is used, `fsanitize-coverage` is not being claimed, i.e. it is unused.

**Comment by Dor1s** [comment]
This thing drives me crazy. The following code takes two different branches for different inputs:

```cpp
      // Disable coverage and not claim the flags if there is at least one
      // non-supporting sanitizer.
      if (!(AllAddedKinds & ~setGroupBits(SupportsCoverage))) {
        Arg->claim();
      } else {
        CoverageFeatures = 0;
      }

```

### 1st case

```
$ ./clang -fsanitize=array-bounds -fsanitize-coverage=trace-pc-guard wtf.c 
AllAddedKinds: 0000000000000080
SupportsCoverage: 00000000FDF7FFE5
setGroupBits: 00000000FFFFFFE5
~setGroupBits: 000000000000001A
	& result: 0000000000000000
	!& result: 0000000000000001
IF IS TRUE: claim() 503: fsanitize-coverage=
```

### 2nd case

```
$ ./clang -fsanitize=local-bounds -fsanitize-coverage=trace-pc-guard wtf.c 
AllAddedKinds: 0000000000000000
SupportsCoverage: 00000000FDF7FFE5
setGroupBits: 00000000FFFFFFE5
~setGroupBits: 000000000000001A
	& result: 0000000000000000
	!& result: 0000000000000000
IF IS FALSE: CoverageFeatures = 0;
clang-5.0: warning: argument unused during compilation: '-fsanitize-coverage=trace-pc-guard' [-Wunused-command-line-argument]
```


However, in both of the cases `AllAddedKinds & ~setGroupBits(SupportsCoverage)` should be zero (i.e. `0 & 0x1A` or `0x80 & 0x1A`. Thus, `!0` should be `true` for both cases, but it is not for the second one!

**Comment by Dor1s** [comment]
For instance:

```bash
$ cat wtf.c 
#include <stdio.h>

int main() {
	if (!(0 & 0x1A)) {
		printf("0 -> true\n");
	} else {
		printf("0 -> false\n");
	}
	if (!(0x80 & 0x1A)) {
		printf("0x80 -> true\n");
	} else {
		printf("0x80 -> false\n");
	}
	return 0;
}


$ clang wtf.c -o wtf && ./wtf
0 -> true
0x80 -> true
```

**Comment by Dor1s** [comment]
Ok, debugging is hard. There are 64bit values actually:

`0x0000000000000080 & 0xfffee8ff0000001a` -> `0x0`

and

`0x0000080000000000 & 0xfffee8ff0000001a` -> `0x0000080000000000`

So, it's fair behavior.

**Comment by Dor1s** [comment]
https://github.com/llvm-mirror/clang/commit/69170e6e41e72c84fe5303540c1aa7ca9944ff18 this is when and why `local-bounds` became a separate "sanitizer" and has been removed from coverage support.

Looks like `-fsanitize=bounds` is a bad idea, but `-fsanitize=array-bounds` sounds good.

**Comment by Dor1s** [comment]
I've checked one of 9 bugs we have, it is reproducible with `array-bounds`. Hopefully others are reproducible with `array-bounds` as well. But if some of them are not, they are likely to be false positives, so it should be fine to lose them.

**Comment by Dor1s** [comment]
@kcc would it make sense to update [UBSan's documentation](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#available-checks) to prevent other users from suffering, since warning message is not too descriptive?

**Comment by oliverchang** [comment]
Thanks for investigating Max! Do you know why we were only seeing warnings for some projects but not all?

**Comment by Dor1s** [comment]
I think that warnings were everywhere (I checked a couple of logs), but not all projects used `-Wextra`, so not all builds were failed due to the warnings.

**Pull request merged**
