### PR TITLE
add: project skipper

### PR DESCRIPTION
**Pull request by szuecs**
add: project skipper

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman good question. There are a bunch of companies using it to built their own http proxies and ingress controllers. For example it's also listed in https://kubernetes.io/docs/concepts/services-networking/ingress-controllers/ .
> 
> Not sure if this is a good enough answer. Let me know and I can try to elaborate more :)

Could you elaborate more. If you name one big-ish company using it that's probably sufficient.

**Comment by szuecs** [comment]
Zalando SE with ~35 million active customers in Europe.

**Comment by szuecs** [comment]
@jonathanmetzman ping :)

**Comment by jonathanmetzman** [comment]
Sounds OK to me. You still have build failures to fix before we can merge.

**Comment by szuecs** [comment]
I am testing locally how to execute the tests correctly.
We have a Makefile target but I think I have to read the conditions and test the changes to make it work.
```
.PHONY: fuzz
fuzz: ## run all fuzz tests
        for p in $(PACKAGES); do go test -run=NONE -fuzz=Fuzz -fuzztime 30s $$p; done
```

I will update the PR when I am done locally and push the changes that should fix the build/test run

**Comment by szuecs** [comment]
@jonathanmetzman I hope I fixed now the PR with the help of an internal colleague. Can you mark it as ok to run, please?

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
Ping me again if this passes but doesn't merge.

**Pull request merged**
