### PR TITLE
[clickhouse] Fix build

### PR DESCRIPTION
**Pull request by nikitamikhaylov**

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@jonathanmetzman I finally fixed build failures, could you please merge?

**Comment by nikitamikhaylov** [comment]
Mean build is failed due to OOM

**Comment by nikitamikhaylov** [comment]
@DavidKorczynski Sorry for tagging, but you merged my several previous PRs. Could you please merge this one?

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman I finally fixed build failures, could you please merge?

Sorry for the late reply.

**Pull request merged**
