### PR TITLE
New fuzzers for Poppler

### PR DESCRIPTION
**Pull request by ecalp-tps**
Hello,

I am a Software Engineering Intern at Google, working with the Third Party Security (TPS) team. As part of my internship I am working on fuzzing GNOME/freedesktop libraries and poppler is one of the libraries that we have picked for this work.

As part of my this, I prepared fuzzers for Poppler's three stable APIs: cpp, glib and qt5. You can find the MR for integrating my fuzzers into the main Poppler repository [here](https://gitlab.freedesktop.org/poppler/poppler/-/merge_requests/658).

Since they would like to see the patch I create in OSS-Fuzz before approving my MR, I’m fetching the Poppler repo from my personal fork in the Dockerfile. Once I get the approval from the Poppler folks, I will update this PR with the link to the main Poppler repo.

I also want to check with you the best practice for preparing a seed corpus that is used by multiple fuzzers. What I understand from the OSS-Fuzz [documentation](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#seed-corpus) is that the fuzz target and the corpus ZIP file that it uses need to have matching names. Since I have multiple fuzzers, should I create copies of the same ZIP file in my build.sh file?

Thanks!
Ceyhun
ceyhunalp@google.com

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Please check CI failures.

**Comment by ecalp-tps** [comment]
> Please check CI failures.

@inferno-chromium I fixed the CI failures.

**Review by Google-Autofuzz — APPROVED** [review]

**Comment by albert-astals-cid-kdab** [comment]
Why was the memory sanitzer removed?

**Comment by tsdgeos** [comment]
I find it kind of unacceptable that this was merged without contacting me, the person that is working on this.

**Comment by tsdgeos** [comment]
And on top of that ossfuzz now runs from https://gitlab.freedesktop.org/ceyhunalp/poppler.git instead of from the actual poppler repository


*WHAT*

**Comment by ecalp-tps** [comment]
> Why was the memory sanitzer removed?

I had to disable it for now since it caused errors in building glib from the source.

**Comment by ecalp-tps** [comment]
> And on top of that ossfuzz now runs from https://gitlab.freedesktop.org/ceyhunalp/poppler.git instead of from the actual poppler repository
> 
> _WHAT_

I was still working on the PR to fix this issue when the merge happened. Please find the new PR [here](https://github.com/google/oss-fuzz/pull/4724) that fetches Poppler from the original master branch and moves the fuzz targets into my OSS-Fuzz repository. Sorry if this created any inconvenience on your side.

**Comment by inferno-chromium** [comment]
> And on top of that ossfuzz now runs from https://gitlab.freedesktop.org/ceyhunalp/poppler.git instead of from the actual poppler repository
> 
> _WHAT_

I am really sorry about this. My mistake, i should have looked closely. I have reverted it now - https://github.com/google/oss-fuzz/pull/4726. Lets try to get these fuzzers reviewed and landed in upstream. No rush, whenever you have time.

**Pull request merged**
