### PR TITLE
Add project utf8proc

### PR DESCRIPTION
**Pull request by randy408**
utf8proc is a small, clean C library that provides Unicode normalization, case-folding, and other operations for data in the UTF-8 encoding.

utf8proc is used for basic Unicode support in the [Julia language](http://julialang.org/).

I intend to integrate this project.

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
Did you get approval from maintainer ? Can you ask them to leave a comment here.

**Comment by randy408** [comment]
Are afl builds currently broken? Anyway the upstreamed build script is no good for some engines, worked around it for now.

https://github.com/JuliaStrings/utf8proc/pull/216

**Comment by inferno-chromium** [comment]
Removed afl sanitizer, have no clue on failure, maybe @jonathanmetzman can check - https://github.com/google/oss-fuzz/pull/5030/checks?check_run_id=1794519005 and have seen it before, so will let him comment.

**Comment by jonathanmetzman** [comment]
Sorry, just saw this message now.
The failing line is ```clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-coverage=trace-pc-guard -I/src/utf8proc /src/utf8proc/test/fuzzer.c -o /out/utf8proc_fuzzer /usr/lib/libFuzzingEngine.a /src/utf8proc/build/libutf8proc.a```

The failures look like this:
```
/usr/local/bin/../include/c++/v1/iosfwd:144: undefined reference to `std::__1::basic_istream<char, std::__1::char_traits<char> >::~basic_istream()'
```
I think the issue is that libFuzzingEngine.a is linked with `clang` instead of `clang++`.

**Comment by randy408** [comment]
Does that mean the fuzz target should be built manually? https://github.com/JuliaStrings/utf8proc/blob/master/test/ossfuzz.sh#L7

**Comment by jonathanmetzman** [comment]
Yes I think so.
It actually might be worth trying AFL builds again without changing anything.
We switched to AFL++ and the libFuzzingEngine.a for AFL++ is pure C. So linking against it may work with clang instead of clang++.

**Pull request merged**
