### PR TITLE
fasthttp: update fuzz targets

### PR DESCRIPTION
**Pull request by erikdubbelboer**
See: https://github.com/valyala/fasthttp/pull/1687

### CODE REVIEW

**Comment by erikdubbelboer** [comment]
Not sure why it is failing with:
```
./fuzzcookieparse_test.go:63:19: cannot use data (variable of type []byte) as *testing.F value in argument to FuzzCookieParse
```
Looks like it's using some old state and still trying to use https://github.com/dvyukov/go-fuzz instead of native Go fuzzing. Anything I need to do to fix that?

**Comment by AdamKorcz** [comment]
> [

I will have a look this week at this.

**Comment by AdamKorcz** [comment]
@erikdubbelboer if these are Native go fuzzers, could you try using `build_native_go_fuzzer` instead of `build_go_fuzzer`?

**Comment by erikdubbelboer** [comment]
I have changed it to use `compile_native_go_fuzzer`.

**Review by AdamKorcz — APPROVED** [review]

**Pull request merged**
