### PR TITLE
Remove unneeded honggfuzz examples from base-builder.

### PR DESCRIPTION
**Pull request by inferno-chromium**
Save 177Mb.

```
root@eca2ea09a598:/src/honggfuzz/examples# du -h
16K	./glibc
8.0K	./libxml2
2.4M	./openssl/corpus_privkey
5.1M	./openssl/corpus_x509
18M	./openssl/corpus_client
27M	./openssl/corpus_server
52M	./openssl
16K	./externalfuzzers
12K	./libpng
25M	./bind/corpus
25M	./bind
29M	./linux_kernel_ip/corpus
30M	./linux_kernel_ip
16K	./libjpeg
20K	./terminal-emulators
33M	./apache-httpd/corpus_http1
39M	./apache-httpd/corpus_http2
72M	./apache-httpd
12K	./file
16K	./badcode/targets
8.0K	./badcode/inputfiles
36K	./badcode
177M	.
```

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

Thanks a lot!

**Comment by inferno-chromium** [comment]
Also filed https://github.com/google/oss-fuzz/issues/5012

**Comment by jonathanmetzman** [comment]
Wait I have another idea here.

**Comment by jonathanmetzman** [comment]
> > Wait I have another idea here.
> > Why don't we just copy those scripts before downloading honggfuzz, then we run precompile_honggfuzz and delete the source code in the same step.
> 
> I can do this, but it will just save 5 mb of source, maybe good to keep source to help in debugging (like matching crashing lines, etc). We also keep source for afl and libfuzzer around too.

If it's just 5mb it's probably not worth it. But the main reason we keep around the source code is because we don't precompile those fuzzers.
Frankly, it might even be worth downloading AFL and honggfuzz only when needed (when compile is called).

**Comment by inferno-chromium** [comment]
> > > Wait I have another idea here.
> > > Why don't we just copy those scripts before downloading honggfuzz, then we run precompile_honggfuzz and delete the source code in the same step.
> > 
> > 
> > I can do this, but it will just save 5 mb of source, maybe good to keep source to help in debugging (like matching crashing lines, etc). We also keep source for afl and libfuzzer around too.
> 
> If it's just 5mb it's probably not worth it as its unlikely to make a difference anyone notices.
> But the main reason we keep around the source code is because we don't precompile those fuzzers.
> It's probably ideal to do downloading of AFL and honggfuzz only when needed (when compile is called).

Yes can do later, not worth atm.

**Comment by inferno-chromium** [comment]
> > > Wait I have another idea here.
> > > Why don't we just copy those scripts before downloading honggfuzz, then we run precompile_honggfuzz and delete the source code in the same step.
> > 
> > 
> > I can do this, but it will just save 5 mb of source, maybe good to keep source to help in debugging (like matching crashing lines, etc). We also keep source for afl and libfuzzer around too.
> 
> If it's just 5mb it's probably not worth it as its unlikely to make a difference anyone notices.
> But the main reason we keep around the source code is because we don't precompile those fuzzers.
> It's probably ideal to do downloading of AFL and honggfuzz only when needed (when compile is called).

Those downloads will flake and cause too much network traffic. Best to keep in image to avoid that.

**Pull request merged**
