### PR TITLE
[cairo] Add to CC list

### PR DESCRIPTION
**Pull request by tysmith**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Who is this you are adding to auto_ccs? Are they a project maintainer?

**Comment by psychon** [comment]
Hi,

I'm the only one from cairo who so far reacted to this fuzzer stuff that was given to / forced upon us. I fixed a [couple of issues](https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests?scope=all&utf8=%E2%9C%93&state=all&search=oss-fuzz) already. My process was originally to visit the oss-fuzz bug tracker regularly and see if the 90 days for anything new expired. Thanks to me, cairo issues are not public immediately so that I do not have to wait 90 days (link is in the list below and also see #4990). @tysmith is so kind to turn this from "I have to poll the website" to "I get some kind of push notification (by mail)", which sounds quite a lot better.

Feel free to read all of https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/69 for more information. Specifically, here are my suggestions (that were ignored) on mail addresses to use for new issues:
- https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/69#note_727143
- https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/69#note_768634

And this is me stumbling upon the "make issues public by default"-knob which turned into #4990:
- https://gitlab.freedesktop.org/cairo/cairo/-/merge_requests/69#note_768642

My mail address appears in https://gitlab.freedesktop.org/cairo/cairo/-/commit/a7c49ec86117bdf1702f9118add187af2582455f. That is at least "some" connection between me and cairo. Alternatively, I can offer the following. Feel free to suggest other ways to prove who I am (whoever that is - I am just a random person who started working on cairo some years back and then was given direct access after I submited enough good-looking patches).
```
$ git shortlog -sn --author=psychon@znc.in
   323  Uli Schlachter
```
(Wow, I didn't know that I am on the 7th place on `git shortlog -sn`. Seems like I really did some work on cairo... :-) )

**Comment by tysmith** [comment]
@jonathanmetzman, Yes sorry I should have added more details in the description. @psychon Thank you for adding the details.

**Comment by jonathanmetzman** [comment]
@psychon Thanks for the detailed explanation.
I was just asking because I couldn't tell from the project.yaml who was the owner of this project in OSS-Fuzz.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by psychon** [comment]
> I was just asking because I couldn't tell from the project.yaml who was the owner of this project in OSS-Fuzz.

AFAIK it is unowned and unmaintained. Google had some intern write code, I said the code is bad and didn't merge it into cairo, so it was merged into OSS-Fuzz instead (apparently with the hope that eventually it will be merged into cairo). No idea whether the internship is over or not.

Of course I think that fuzzing cairo is a good idea, but it also quite non-trivial. In other words: I have no idea what good and useful fuzz targets would be, so I cannot really write any. (Also: No time)

The most interesting/relevant issues were so far found by fuzzing poppler, but sadly that only hits the font handling in cairo ("here is a big binary blob, please try interpreting it as a font").

**Comment by jonathanmetzman** [comment]
> > I was just asking because I couldn't tell from the project.yaml who was the owner of this project in OSS-Fuzz.
> 
> AFAIK it is unowned and unmaintained. Google had some intern write code, I said the code is bad and didn't merge it into cairo, so it was merged into OSS-Fuzz instead (apparently with the hope that eventually it will be merged into cairo). No idea whether the internship is over or not.

Pretty sure it is.

> 
> Of course I think that fuzzing cairo is a good idea, but it also quite non-trivial. In other words: I have no idea what good and useful fuzz targets would be, so I cannot really write any. (Also: No time)
> 
> The most interesting/relevant issues were so far found by fuzzing poppler, but sadly that only hits the font handling in cairo ("here is a big binary blob, please try interpreting it as a font").

No worries.

**Comment by psychon** [comment]
Hi, sorry for writing this comment in an old issue, but that's my best idea for contacting someone.

I just received a notification for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=39209. When I click the link for "reproducer testcase" (https://oss-fuzz.com/download?testcase_id=6233382279839744), I end up at http://oss-fuzz.com/login. That page has a header saying "Log in" and a button saying "Sign in with Google". Cairo's issues are public by default since #4990, but apparently the reproducers aren't...? Will this only be public in 90 days? Is there a way to avoid these problems?

(Yes, I tried logging in with one random account. No, that account is not authorizes to access this page. No, I don't want that account's mail address in a public file on github.)

**Comment by DavidKorczynski** [comment]
The `view_restrictions: none` label will only make the data on monorail publicly available, not the data on oss-fuzz.com which is where the reproducer case and detailed report is. 

The solution is to put an email in the `project.yaml` (either under `primary_contact` or `auto_ccs`) and then this email will be able to access the oss-fuzz.com data.

**Comment by psychon** [comment]
Okay, thanks for that info

**Pull request merged**
