### PR TITLE
[brpc] Coverage build fix .

### PR DESCRIPTION
**Pull request by 0x34d**
Working on possible fix : https://github.com/google/oss-fuzz/issues/9154

Signed-off-by: Arjun Singh <ajsinghyadav00@gmail.com>

### CODE REVIEW

**Comment by Alan32Liu** [comment]
Thanks!
I noticed that you change the title to 'Working on ...', is it because it is still a work in progress?

**Comment by 0x34d** [comment]
> Thanks! I noticed that you change the title to 'Working on ...', is it because it is still a work in progress?

yes, Past few weeks I was working on something else, I will try to fix the issue in the next 2-5 days.

**Comment by Alan32Liu** [comment]
> > Thanks! I noticed that you change the title to 'Working on ...', is it because it is still a work in progress?
> 
> yes, Past few weeks I was working on something else, I will try to fix the issue in the next 2-5 days.
> 
> And thanks for the reminder.

Thanks, please take you time : )

**Comment by 0x34d** [comment]
> Thanks, please take you time : )
Done buddy.
As always it was a simple fix with hours of debugging.

**Review by Alan32Liu — APPROVED** [review]
LGTM

**Pull request merged**
