### PR TITLE
Initial integration for PcapPlusPlus

### PR DESCRIPTION
**Pull request by oliverchang**
Accidentally merged this before, recreating PR to assess inclusion in OSS-Fuzz.

### CODE REVIEW

**Comment by oliverchang** [comment]
https://github.com/google/oss-fuzz/pull/3695 @zlowram is the original author

**Comment by inferno-chromium** [comment]
+1 to OSS-Fuzz inclusion

**Comment by zlowram** [comment]
By the way, I'm currently looking to help integrate more projects into OSS-Fuzz during my free time. I have some in mind but since I already integrated two I thought I'd ask if you have any interesting projects that you'd like to prioritize.

Also I'm interested in learning more about custom mutators so if there's any project in OSS-Fuzz that you think that could be a good target for that (e.g. they use structures) I'd also like to give them a go.

**Comment by inferno-chromium** [comment]
@zlowram - thank you for considering new projects. we really appreciate your efforts, please check the list of projects here - https://github.com/google/oss-fuzz/issues/402#issue-208584560

**Pull request merged**
