### PR TITLE
Fix https://crbug.com/oss-fuzz/55617

### PR DESCRIPTION
**Pull request by afq984**

### CODE REVIEW

**Comment by afq984** [comment]
Verified that https://crbug.com/oss-fuzz/55617 is not reproducible.

**Comment by afq984** [comment]
libfuzzer, coverage, x86_64 does not reproduce, weird.

**Comment by jonathanmetzman** [comment]
That's because you need to also run the coverage command. The CI just does the build.

**Comment by afq984** [comment]
Fixing in https://github.com/google/oss-fuzz/pull/9649.

**Pull request closed without merging**
