### PR TITLE
Extend java coverage reports to include non-covered files

### PR DESCRIPTION
**Pull request by arthurscchan**
Jacoco is used for code coverage report generation of JVM projects. It will make use of the dumped class file to generate the report. But only java classes covered by at least one fuzzer will be included in the report, other files in the project will be ignored. This PR aims to point the Jacoco class file discovery folder to the original compiled project jar file in order to force Jacoco to generate coverage report with source for all java class of the project.
This came as a need from Fuzz Introspector where we noticed some discrepancies between the static analysis and the code coverage reports.

Signed-off-by: Arthur Chan <arthur.chan@adalogics.com>

### CODE REVIEW

**Comment by arthurscchan** [comment]
Old version:


New version:
image

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by oliverchang** [comment]
/gcbrun trial_build.py python --fuzzing-engine libfuzzer --sanitizers coverage

**Comment by oliverchang** [comment]
/gcbrun trial_build.py glom h2o zip4j igraph h2o gpac --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
/gcbrun trial_build.py jvm --fuzzing-engine libfuzzer --sanitizers coverage

**Comment by DavidKorczynski** [comment]
@jonathanmetzman @oliverchang we went over some of the projects that had `False` next to them from the trial run. They are working for us locally -- am not sure if some other things made them fail at the given moment. Could we rerun the trial run?

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jvm --fuzzing-engine libfuzzer --sanitizers coverage

**Comment by jonathanmetzman** [comment]
This is still failing for like half of projects.

**Comment by jonathanmetzman** [comment]
```
Already have image (with digest): gcr.io/oss-fuzz-base/base-runner-testing-fix-jacoco
Running SimpleJsonSerializerFuzzer
[INFO] Loading execution data file /workspace/out/libfuzzer-coverage-x86_64/dumps/SimpleJsonSerializerFuzzer.exec.
[INFO] Analyzing 86 classes.
[INFO] Loading execution data file /workspace/out/libfuzzer-coverage-x86_64/dumps/SimpleJsonSerializerFuzzer.exec.
[INFO] Writing execution data to /workspace/out/libfuzzer-coverage-x86_64/dumps/jacoco.merged.exec.
[INFO] Loading execution data file /workspace/out/libfuzzer-coverage-x86_64/dumps/jacoco.merged.exec.
Exception in thread "main" java.io.IOException: Error while analyzing /workspace/out/libfuzzer-coverage-x86_64/spring-integration-core.jar@kotlin/coroutines/jvm/internal/DebugProbesKt.class.
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzerError(Analyzer.java:162)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:134)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:157)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:193)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeZip(Analyzer.java:265)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:196)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeAll(Analyzer.java:226)
	at org.jacoco.cli.internal.commands.Report.analyze(Report.java:110)
	at org.jacoco.cli.internal.commands.Report.execute(Report.java:84)
	at org.jacoco.cli.internal.Main.execute(Main.java:90)
	at org.jacoco.cli.internal.Main.main(Main.java:105)
Caused by: java.lang.IllegalStateException: Can't add different class with same name: kotlin/coroutines/jvm/internal/DebugProbesKt
	at org.jacoco.cli.internal.core.analysis.CoverageBuilder.visitCoverage(CoverageBuilder.java:106)
	at org.jacoco.cli.internal.core.analysis.Analyzer$1.visitEnd(Analyzer.java:99)
	at org.jacoco.cli.internal.asm.ClassVisitor.visitEnd(ClassVisitor.java:377)
	at org.jacoco.cli.internal.core.internal.flow.ClassProbesAdapter.visitEnd(ClassProbesAdapter.java:100)
	at org.jacoco.cli.internal.asm.ClassReader.accept(ClassReader.java:725)
	at org.jacoco.cli.internal.asm.ClassReader.accept(ClassReader.java:401)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:116)
	at org.jacoco.cli.internal.core.analysis.Analyzer.analyzeClass(Analyzer.java:132)
	... 9 more
```

**Comment by DavidKorczynski** [comment]
Thanks @jonathanmetzman -- we'll update here shortly.

**Comment by DavidKorczynski** [comment]
@jonathanmetzman we've pushed some changes to avoid the error -- the current state works well for us locally, could we rerun the trial run?

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jvm --fuzzing-engine libfuzzer --sanitizers coverage

**Comment by DavidKorczynski** [comment]
ugh, I may have been a bit too fast here -- was testing on some more of the failed ones in https://github.com/google/oss-fuzz/runs/12160764388 and am seeing some issues persist. We'll go over this again

**Comment by DavidKorczynski** [comment]
@arthurscchan could you rebase this and update if needed? It would be great if we can get this landed

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jvm --fuzzing-engine libfuzzer --sanitizers coverage

**Comment by DavidKorczynski** [comment]
@arthurscchan the permissions of coverage is changed and it's no longer executable causing the coverage builds to fail.

**Comment by DavidKorczynski** [comment]
@arthurscchan I made a commit to your branch to fix the permissions.

@jonathanmetzman could we rerun the trial build? I've verified locally it works on a handful of project.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jvm --fuzzing-engine libfuzzer --sanitizers coverage

**Comment by DavidKorczynski** [comment]
`spring-data-redis` and `feign` failed in the trial build.

`spring-data-redis` looks to be a timeout. I tested it locally and can confirm it works.

`feign` is a project resulting from auto-fuzz from Fuzz Introspector. I'm happy to leave it for now and we'll address that later and perhaps in the `feign` build itself.

**Pull request merged**
