### PR TITLE
[h3] Add @nrabinowitz to the list of H3 maintainers

### PR DESCRIPTION
**Pull request by nrabinowitz**
Adds [nrabinowitz](https://github.com/nrabinowitz) to the list of maintainers for https://github.com/uber/h3

cc @isaacbrodsky

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Please sign the CLA

**Comment by jonathanmetzman** [comment]
Do you approve @isaacbrodsky @ajfriend ?

**Review by ajfriend — APPROVED** [review]

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by isaacbrodsky** [comment]
post-facto yes I approve

**Pull request merged**
