### PR TITLE
Add WeeChat

### PR DESCRIPTION
**Pull request by txtsd**

### CODE REVIEW

**Comment by txtsd** [comment]
I'm unable to sign it. The cla page spits this: `A server error occurred, please try your request again.`
All fields are populated.

**Comment by inferno-chromium** [comment]
@txtsd - can you try signing again on https://cla.developers.google.com/ or are you still getting this error.

**Comment by txtsd** [comment]
@inferno-chromium I tried again, but I'm still getting the same error. What do?

**Comment by inferno-chromium** [comment]
txtsd - i have mailed our CLA team to debug this. You CL is already accepted, so you can continue to work on the fuzz target.

**Comment by inferno-chromium** [comment]
@txtsd - can you try once more. CLA team has added more logging to debug this and they need you to try again. Sorry for inconvenience.

**Comment by txtsd** [comment]
@inferno-chromium It went through!

**Pull request merged**
