### PR TITLE
[aflplusplus] Remove 32 MB from image size by deleting .git

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer afl

**Comment by jonathanmetzman** [comment]
I guess one sideeffect this will have is the AFL commit wont appear in the revision range for every bug like it currently does (I consider this a positive though)

**Comment by jonathanmetzman** [comment]
CC @vanhauser-thc

**Comment by jonathanmetzman** [comment]
Build failures are spurious.

**Review by Alan32Liu — APPROVED** [review]

**Pull request merged**
