### PR TITLE
python-pypdf: initial integration

### PR DESCRIPTION
**Pull request by bluemarco**

### CODE REVIEW

**Comment by hogo6002** [comment]
> bluemarco is integrating a new project, but the `main_repo` is missing. The criticality score cannot be computed.

It only obtains `main_repo` from project.**yaml** file

**Comment by Alan32Liu** [comment]
Hi @bluemarco, thanks for integrating this.
Did you have approval from the project maintainers? Thanks : )

**Comment by bluemarco** [comment]
Hi @Alan32Liu, this is my first time integrating a project to oss-fuzz and I want to know the next step.

**Comment by Alan32Liu** [comment]
> Hi @Alan32Liu, this is my first time integrating a project to oss-fuzz and I want to know the next step.

Hi @bluemarco, thanks for the PR!

The OSS-Fuzz panel has approved this PR, so I enabled auto-merge.
It should be merged shortly after passing all CI checks, its build status will be visible on [OSS-Fuzz build status page](https://oss-fuzz-build-logs.storage.googleapis.com/index.html), and crashes&errors (if any) will be sent to the contacts.

**Review by Alan32Liu — APPROVED** [review]

**Pull request merged**
