### PR TITLE
Fixes afl++ installation

### PR DESCRIPTION
**Pull request by vanhauser-thc**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Since https://github.com/google/oss-fuzz/commit/b19e7001928b08f9ae8fd3c017688cd5edf96cb2 is reverted, can you revert that and reupload as part of this cl. Thanks a lot. Do this fix meson failure too, e.g. systemd project?

**Comment by vanhauser-thc** [comment]
hard to say. I have another fix that needs a new git from afl++ (some weird targets do something that result in double afl-clang-fast, afl-clang-fast calling afl-clang-fast instead of afl-clang. 

where can I fix that -fsanitize=fuzzer... is set?

You could then merge it into a branch and test it on all targets?
I do not have these resources ;)

**Comment by vanhauser-thc** [comment]
items like protobuf-c and tss compile fine for me with this.
this checkout id also has the change that tries to make AFL_MAP_SIZE obsolete, so testing this PR on all targets would be great, something like fuzzbench `make test-run-...` ?

**Comment by evverx** [comment]
> Do this fix meson failure too, e.g. systemd project?

No, it doesn't. With this patch applied and https://github.com/google/oss-fuzz/commit/b19e7001928b08f9ae8fd3c017688cd5edf96cb2 reverted (with the base-builder image rebuilt manually), `systemd` is still failing to compile with
```
Compiler stdout:

Compiler stderr:
 clang-12: error: /src/aflplusplus/afl-compiler-rt.o: 'linker' input unused [-Werror,-Wunused-command-line-argument]
clang-12: error: -Wl,--dynamic-list=/src/aflplusplus/dynamic_list.txt: 'linker' input unused [-Werror,-Wunused-command-line-argument]


meson.build:647:16: ERROR: Problem encountered: unable to determine gperf len type
+ exit 1
Building fuzzers failed.
```

`dav1d` is failing to compile as well with
```
Checking if "GCC-style atomics" compiles: NO

meson.build:189:8: ERROR: Problem encountered: Atomics not supported

A full log can be found at /work/build/meson-logs/meson-log.txt
Building fuzzers failed.
```
which I think boils down to the same unused argument.

I haven't built the other project using `meson` but I'm pretty sure they are most likely affected

**Comment by evverx** [comment]
`tpm2-tss` is failing to compile too:
```
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(aflpp_driver.o): In function `main':
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:236: undefined reference to `__afl_manual_init'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:244: undefined reference to `__afl_manual_init'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:262: undefined reference to `__afl_fuzz_len'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:265: undefined reference to `__afl_fuzz_ptr'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:14835: recipe for target 'test/fuzz/Tss2_Sys_Startup_Prepare.fuzz' failed
make: *** [test/fuzz/Tss2_Sys_Startup_Prepare.fuzz] Error 1
make: *** Waiting for unfinished jobs....
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(aflpp_driver.o): In function `main':
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:236: undefined reference to `__afl_manual_init'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:244: undefined reference to `__afl_manual_init'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:262: undefined reference to `__afl_fuzz_len'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:265: undefined reference to `__afl_fuzz_ptr'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:14827: recipe for target 'test/fuzz/Tss2_Sys_Startup_Complete.fuzz' failed
make: *** [test/fuzz/Tss2_Sys_Startup_Complete.fuzz] Error 1
Building fuzzers failed.
```
Looks like they compiled successfully because https://github.com/google/oss-fuzz/commit/b19e7001928b08f9ae8fd3c017688cd5edf96cb2 wasn't reverted in the latest version of the base-builder image on top of which the first commit of this PR was rebuilt.

**Comment by vanhauser-thc** [comment]
@evverx yes I did not revert, I just replaced the file with what it should be, and that worked for me.
I have never used oss-fuzz, so what I did was:
1. this PR state
2. python infra/helper.py pull_images
3. python infra/helper.py build_image base-builder
4. python infra/helper.py build_fuzzers --sanitizer address --engine afl --architecture x86_64 protobuf-c
5. python infra/helper.py shell --sanitizer address --engine afl --architecture x86_64 protobuf-c
  => compile

did I do something wrong?

**Comment by evverx** [comment]
@vanhauser-thc I think when `pull_images` pulled the latest images they already contained https://github.com/google/oss-fuzz/commit/b19e7001928b08f9ae8fd3c017688cd5edf96cb2 so to test the commit where the .txt files were installed, b19e7001928b08f9ae8fd3c017688cd5edf96cb2 should have probably been reverted before `build_image base-builde` was run.

**Comment by evverx** [comment]
@vanhauser-thc I didn't notice you pushed another commit that effectively reverts https://github.com/google/oss-fuzz/commit/b19e7001928b08f9ae8fd3c017688cd5edf96cb2. With it it should be enough to just run all the commands you mentioned once again to reproduce those issues.

**Comment by vanhauser-thc** [comment]
so you mean `python infra/helper.py pull_images` was wrong by me?
how do I build the images then?

**Comment by jonathanmetzman** [comment]
> so you mean `python infra/helper.py pull_images` was wrong by me?
> how do I build the images then?

To test your change on a project you need to do:
```
python infra/helper.py build_image base-builder
python infra/helper.py build_image <test-project>
python infra/helper.py build_fuzzers <test-project> --engine afl
```
If you get asked about pulling latest images, say no because they will clobber your build of base-builder

**Comment by evverx** [comment]
> so you mean python infra/helper.py pull_images was wrong by me?

Sorry. I was just kind of trying to figure out what could have gone wrong there and probably wasn't clear enough. There was nothing wrong with pull_images. It's just that with the first version of the PR on top of `master` with  https://github.com/google/oss-fuzz/commit/b19e7001928b08f9ae8fd3c017688cd5edf96cb2 `build_image` couldn't build an image to test `afl-clang-fast`.

> If you get asked about pulling latest images, say no because they will clobber your build of base-builder

I don't think they will if `build_image base-builder` is run right after that. And given how often `pull_images` helps to fix weird issues by keeping local oss-fuzz repositories and the images in sync I'd say `pull_images` should always be run first :-)

**Comment by vanhauser-thc** [comment]
I made some changes to the afl++ compiler wrapper, now systemd compiles too:
```
[624/625] /src/aflplusplus/afl-clang-fast++  -o fuzz-udev-rules fuzz-udev-rules.p/src_udev_fuzz-udev-rules.c.o -L/usr/lib/clang/12.0.0/lib/linux -Wl,--as-needed -Wl,--allow-shlib-undefined -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -Wl,--start-group src/udev/libudev-core.a src/shared/libsystemd-shared-247.so -pthread -lFuzzingEngine -Wl,--end-group '-Wl,-rpath,$ORIGIN/src/shared' -Wl,-rpath-link,/work/build/src/shared
[624/625] /usr/local/bin/meson --internal commandrunner /src/systemd /work/build '' /usr/local/bin/meson true
[...]
+ find /work/build -maxdepth 1 -type f -executable -name 'fuzz-*' -exec mv '{}' /out ';'
+ find src -type f -name 'fuzz-*.dict' -exec cp '{}' /out ';'
+ cp src/fuzz/fuzz-env-file.options /out
```
so I think this is now ready to be broadly tested if anything else is still breaking. incl. running them for 15 seconds. can you guys do that?

**Review by inferno-chromium — APPROVED** [review]
Thanks a lot (sorry for slow response, i was ooo). Removed dictionary link addition, i will just fix qt next. adding afl dir makes two afls show in regression range components, so unneeded.

**Comment by inferno-chromium** [comment]
@rlohning - can you please qt's build.sh to not use dict from /src/afl. we shouldn't be relying on /src location, best to download dict in qt's Dockerfile and then use in build.sh. or can keep dict in your src code.

**Comment by evverx** [comment]
@vanhauser-thc thanks! I was able to build `systemd` and `dav1d`. `check_build` seems to have passed there as well.

`tpm2-tss` is still failing to compile though with
```
  CXXLD    test/fuzz/Tss2_Sys_Startup_Prepare.fuzz
  CXXLD    test/fuzz/Tss2_Sys_Startup_Complete.fuzz
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(aflpp_driver.o): In function `main':
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:236: undefined reference to `__afl_manual_init'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:244: undefined reference to `__afl_manual_init'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:262: undefined reference to `__afl_fuzz_len'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:265: undefined reference to `__afl_fuzz_ptr'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:14835: recipe for target 'test/fuzz/Tss2_Sys_Startup_Prepare.fuzz' failed
make: *** [test/fuzz/Tss2_Sys_Startup_Prepare.fuzz] Error 1
make: *** Waiting for unfinished jobs....
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(aflpp_driver.o): In function `main':
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:236: undefined reference to `__afl_manual_init'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:244: undefined reference to `__afl_manual_init'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:251: undefined reference to `__afl_persistent_loop'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:262: undefined reference to `__afl_fuzz_len'
/src/aflplusplus/utils/aflpp_driver/aflpp_driver.c:265: undefined reference to `__afl_fuzz_ptr'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:14827: recipe for target 'test/fuzz/Tss2_Sys_Startup_Complete.fuzz' failed
make: *** [test/fuzz/Tss2_Sys_Startup_Complete.fuzz] Error 1
Building fuzzers failed.
```

**Comment by rlohning** [comment]
@inferno-chromium 

> @rlohning - can you please qt's build.sh to not use dict from /src/afl.

I already did yesterday: https://codereview.qt-project.org/c/qt/qtqa/+/332195
I expect the build to pass again today. Thank you for the reminder.

>  we shouldn't be relying on /src location, best to download dict in qt's Dockerfile and then use in build.sh. or can keep dict in your src code.

So it's preferable to do my own clone of aflplusplus repo instead of using the one from base-image? Okay, I'll do so.

**Comment by vanhauser-thc** [comment]
@rlohning I think he means just to wget the .dicts you need in the Dockerfile if your build, e.g.
`wget https://raw.githubusercontent.com/AFLplusplus/AFLplusplus/stable/dictionaries/regexp.dict`. In case the fuzzers in /src change this would not impact you.

**Comment by inferno-chromium** [comment]
> @rlohning I think he means just to wget the .dicts you need in the Dockerfile if your build, e.g.
> `wget https://raw.githubusercontent.com/AFLplusplus/AFLplusplus/stable/dictionaries/regexp.dict`. In case the fuzzers in /src change this would not impact you.

Yes exactly. @rlohning fyi.

**Comment by rlohning** [comment]
> 
> 
> > @rlohning I think he means just to wget the .dicts you need in the Dockerfile if your build, e.g.
> > `wget https://raw.githubusercontent.com/AFLplusplus/AFLplusplus/stable/dictionaries/regexp.dict`. In case the fuzzers in /src change this would not impact you.
> 
> Yes exactly. @rlohning fyi.

raw.githubusercontent.com does not allow recursive copying of directories, does it? So I'd have to copy each and every file myself.

**Comment by jonathanmetzman** [comment]
> > > @rlohning I think he means just to wget the .dicts you need in the Dockerfile if your build, e.g.
> > > `wget https://raw.githubusercontent.com/AFLplusplus/AFLplusplus/stable/dictionaries/regexp.dict`. In case the fuzzers in /src change this would not impact you.
> > 
> > 
> > Yes exactly. @rlohning fyi.
> 
> raw.githubusercontent.com does not allow recursive copying of directories, does it? So I'd have to copy each and every file myself.

You could also clone github.com/google/AFL and then you don't need to wget each dict.

**Pull request merged**
