### PR TITLE
ns10 is an output buffer 3x  the length of s11

### PR DESCRIPTION
**Pull request by covener**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Thanks @covener - could you sign the CLA then I will merge this in

**Comment by covener** [comment]
@googlebot I signed it!

**Comment by DavidKorczynski** [comment]
CI fails: 
```
/src/fuzz_utils.c:67:15: error: expected ';' after expression
    free(ns10)
```

**Comment by DavidKorczynski** [comment]
Thanks @covener - the current error is not due to your code. 

@jonathanmetzman @inferno-chromium coverage is breaking, are we missing a coverage sanitizer here?:
https://github.com/google/oss-fuzz/blob/8a566fccd5bbebd3a478d82a35e084b7a03f42ef/infra/constants.py#L34

**Review by DavidKorczynski — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
@covener I deployed another fix here: https://github.com/google/oss-fuzz/pull/6176 which takes into account the length of `ns11` rather the `size` variable, as they are not the same. The CI here also seem to have gotten stuck. 

Closing this one.

**Pull request closed without merging**
