### PR TITLE
initial integration for fuzzing zip4j

### PR DESCRIPTION
**Pull request by happy-qop**
Adds the [zip4j](https://github.com/srikanth-lingala/zip4j) fuzzer implementation to oss-fuzz. Passed testing on ubuntu 18.04 X64 following this [link](https://google.github.io/oss-fuzz/getting-started/new-project-guide/).

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Thanks @happy-qop! Could you clarify who are the customers of zip4j?

**Review by Alan32Liu — APPROVED** [review]
Approved.

**Comment by Alan32Liu** [comment]
> Thank you, may I know what does g3 stand for? @Alan32Liu

Ah, please ignore that.
It's just a reminder for me : )

**Comment by occia** [comment]
I see, thanks anyway.

**Pull request merged**
