### PR TITLE
Add tzdata to match clusterfuzz

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Fixes https://github.com/google/oss-fuzz/issues/9280

### CODE REVIEW

**Comment by evverx** [comment]
@jonathanmetzman thanks! It should make it easier to reproduce issues like that locally. But given that OSS-Fuzz keeps opening those issues (it filed https://github.com/systemd/systemd/issues/25872 and https://github.com/systemd/systemd/issues/25868 today) `tzdata` doesn't seem to be always installed on ClusterFuzz. I wonder if it would be possible to install it there explicitly as well?

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman thanks! It should make it easier to reproduce issues like that locally. But given that OSS-Fuzz keeps opening those issues (it filed [systemd/systemd#25872](https://github.com/systemd/systemd/issues/25872) and [systemd/systemd#25868](https://github.com/systemd/systemd/issues/25868) today) `tzdata` doesn't seem to be always installed on ClusterFuzz. I wonder if it would be possible to install it there explicitly as well?

That's surpising to me. I think it should always be installed. The only thing that comes to mind is possibly that some of our instances are in different timezones.

**Comment by evverx** [comment]
> The only thing that comes to mind is possibly that some of our instances are in different timezones.

I don't think it should affect the fuzz target in the sense that it just goes over `/usr/share/zoneinfo/` when it sees explicit timezones so as long as `tzdata` is installed it should always fail under MSan regardless of the timezone. OSS-Fuzz marks those issues flaky eventually and as far as I understand it can only happen when `tzdata` is missing.

**Comment by evverx** [comment]
Just to clarify those issues should be fixed by systemd and there are two PRs at the moment where they are addressed one way or another. It's just that it isn't clear which one should be merged: https://github.com/systemd/systemd/pull/25844#issuecomment-1365494235. But I think it would be great to fix the tzdata issue somehow to prevent new issues in that parser (should they be found there) from being reported over and over again.

**Review by Navidem — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
The errors look spurious.

**Comment by evverx** [comment]
Looks like `tzdata` was indeed fine. I suspect OSS-Fuzz kept reporting those issues because I removed the "security" tag to prevent those false positives from ending up in the OSV database. The elfutils ran into that in https://github.com/google/oss-fuzz/issues/9769 and it obviously has nothing to do with `tzdata`.

**Comment by jonathanmetzman** [comment]
What do you mean "was indeed fine", did my fix work? Or is it unnecessary.

**Comment by evverx** [comment]
Sorry! What I was trying to say is that `tzdata` is installed on ClusterFuzz. It's just that I thought that those issues were reported because `tzdata` wasn't installed but it turns out it isn't the case.

> did my fix work?

Yes, it did. With this PR applied it's possible to reproduce those issues locally using `helper.py`. Thanks!

**Pull request merged**
