### PR TITLE
[avahi] modernize fuzz targets

### PR DESCRIPTION
**Pull request by evverx**
The idea is to make it easier to move the fuzzing infrastructure to the avahi repository where new fuzz targets can be added to catch and prevent various crashes, segfaults and stuff like that.

[avahi] switch fuzz targets to C

Avahi is written in C so its fuzz targets should probably be written in
C as well to make it easier to add new fuzz targets. It should also make
it easier to integrate the fuzzing infrastructure into the build system
eventually.

My guess would be that it was written this way because it was based on
the toy example from https://llvm.org/docs/LibFuzzer.html#toy-example.

[avahi] use headers and static libraries from build directory

It should make it easier to figure out what the build script does. For
some reason it patched a makefile, pointed the config script to $WORK,
installed the headers and libraries there and then used them. It kind of
works but it doesn't make much sense to jump through hoops when all
those headers and libraries can be taken from the build directory
directly.

cc @pemensik @adriancable

### CODE REVIEW

**Comment by pemensik** [comment]
Now that we have access to original avahi repository, it might make sense to add fuzzer tests to Avahi project directly. Have for example make fuzzers target to build fuzzers there.

**Comment by evverx** [comment]
> it might make sense to add fuzzer tests to Avahi project directly

I'm planning to move them there and turn on https://google.github.io/oss-fuzz/getting-started/continuous-integration/. The idea behind this PR is to prepare everything for the move.

**Comment by evverx** [comment]
I'm going to put this PR on hold. I think GHActions should be sorted out in the avahi repository first.

**Comment by evverx** [comment]
I'll pick it up once https://github.com/lathiat/avahi/pull/413 is resolved somehow

**Comment by evverx** [comment]
Since `avahi` isn't actively maintained any more I'm not sure it makes much sense to improve and roll out the fuzz targets to accumulate even more unaddressed bug reports on top of all the known issues. Closing.

**Pull request closed without merging**
