### PR TITLE
[libxml2] [libxslt] Remove myself as contact

### PR DESCRIPTION
**Pull request by nwellnhof**
I'm not involved in these projects anymore.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
is there another primary contact we could use?

**Comment by nwellnhof** [comment]
No, libxml2 and libxslt are unmaintained for now.

**Comment by DavidKorczynski** [comment]
okay, I will let others chime in here on whether the projects should be disabled entirely then or something else, since no maintainers will be fixing bugs.

**Comment by sftim** [comment]
Does remind me of
Someday ImageMagick will finally break for good and we'll have a long period of scrambling as we try to reassemble civilization from the rubble.
 (https://xkcd.com/2347/)

**Comment by DavidKorczynski** [comment]
> Does remind me of
> Someday ImageMagick will finally break for good and we'll have a long period of scrambling as we try to reassemble civilization from the rubble.
> (https://xkcd.com/2347/)

Spot on

**Review by inferno-chromium — APPROVED** [review]

**Comment by mablue** [comment]
> Does remind me of
> Someday ImageMagick will finally break for good and we'll have a long period of scrambling as we try to reassemble civilization from the rubble.
> (https://xkcd.com/2347/)

we cant Let's hesitate freedome of peoples that do not want to continue. its good to share your ideas with world and take a break.;)

**Pull request merged**
