### PR TITLE
apache-commons: update project.yaml

### PR DESCRIPTION
**Pull request by henryrneh**
Update primary_contact and auto_ccs as requested by apache commons.

### CODE REVIEW

**Comment by henryrneh** [comment]
@markt-asf We've done the update as you requested, putting security email to auto_ccs and fuzz-testing email to primary_contact. Should we also do this change to Apache Tomcat?

**Comment by markt-asf** [comment]
Thanks, but not at this time. The Tomcat security team have expressed similar concerns about message volume and false positive rates so I'll start a discussion to see if they want top adopt a similar solution to commons.

**Comment by henryrneh** [comment]
> Thanks, but not at this time. The Tomcat security team have expressed similar concerns about message volume and false positive rates so I'll start a discussion to see if they want top adopt a similar solution to commons.

Thanks for your feedback!

**Comment by henryrneh** [comment]
Ready for merge

**Comment by henryrneh** [comment]
@oliverchang What do you think? Thanks!

**Comment by markt-asf** [comment]
As this hasn't been merged yet, please can you add the same changes for Tomcat:
fuzz-testing@tomcat.apache.org should be the primary contact and security@tomcat.apache.org cc'd for all Apache Tomcat components configured for fuzz-testing.

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
