### PR TITLE
update afl++ commit id

### PR DESCRIPTION
**Pull request by vanhauser-thc**
this fixes a bug that affects coverage.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@jonathanmetzman this should be merged (bugfixes and improvements)

**Comment by vanhauser-thc** [comment]
@jonathanmetzman why is this not being merged?
the new commit also fixed llvm 15 so you should be able to upgrade to any version you want.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman why is this not being merged? the new commit also fixed llvm 15 so you should be able to upgrade to any version you want.

I mustve lost track sorry

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
Not gonna merge this till monday and after https://github.com/google/oss-fuzz/pull/8519 so I can test this.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine afl

**Comment by vanhauser-thc** [comment]
btw do you need LLVMFuzzerRunDriver support in oss-fuzz the next weeks?
I can push the commit id if you do, otherwise I would keep that for the next update.

**Comment by jonathanmetzman** [comment]
> btw do you need LLVMFuzzerRunDriver support in oss-fuzz the next weeks? I can push the commit id if you do, otherwise I would keep that for the next update.

Not that I know of.

**Comment by jonathanmetzman** [comment]
Only build failure was due to the weird IPV6 bug in GCB: https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/140df47a-4f47-491a-9a6a-35fbed92c03d;step=17?project=oss-fuzz

**Pull request merged**
