### PR TITLE
xmlsec: oss-fuzz integration

### PR DESCRIPTION
**Pull request by bshastry**
This PR

- Enrolls xmlsec into oss-fuzz

### CODE REVIEW

**Comment by bshastry** [comment]
Paging @lsh123 who is the maintainer of xmlsec

**Comment by lsh123** [comment]
If you are asking about xmlsec library customers, probably the biggest open source customer is LibreOffice. There are a few libraries for SOAP, etc. that depend on xmlsec.

**Comment by jonathanmetzman** [comment]
@bshastry 
I reverted this commit because it was a broken build.
The issue is that `xmlsec_fuzzer` depends on `libxslt.so.1` being available on the machine the fuzzer runs on. But this is not the case.
Note that you can only install packages to the machine that builds your fuzzer, not the machine that it runs on.

To reproduce the issue, run 
```
python infra/helper.py check_build --sanitizer --sanitizer address xmlsec
```
after building.

To fix the problem, I recommend linking statically instead of dynamically.

**Comment by bshastry** [comment]
Hey @jonathanmetzman Thanks for helping me debug. I changed `build.sh` to link `libxslt` statically now and verified fuzzer may be run on a different machine by running:

```
bhargava@x230:~/work/github/oss-fuzz$ python infra/helper.py check_build --sanitizer address xmlsec
Running: docker run --rm -i --privileged -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -v /home/bhargava/work/github/oss-fuzz/build/out/xmlsec:/out -t gcr.io/oss-fuzz-base/base-runner test_all
Unable to find image 'gcr.io/oss-fuzz-base/base-runner:latest' locally
latest: Pulling from oss-fuzz-base/base-runner
b234f539f7a1: Already exists 
55172d420b43: Already exists 
5ba5bbeb6b91: Already exists 
43ae2841ad7a: Already exists 
f6c9c6de4190: Already exists 
35893ea29b4f: Already exists 
510a3dcea9ed: Already exists 
8eb3e1f10be7: Pull complete 
771d79ed3720: Pull complete 
Digest: sha256:60d62e8e6c2cccca7dc8ecc95b6a17da7f032f4bc360ad0826405660739fee47
Status: Downloaded newer image for gcr.io/oss-fuzz-base/base-runner:latest
INFO: performing bad build checks for /out/xmlsec_fuzzer.
1 fuzzers total, 0 seem to be broken (0%).
Check build passed.
```

**Pull request merged**
