### PR TITLE
Add "fanningpj@gmail.com" as auto_cc for jackson-core, jackson-databind

### PR DESCRIPTION
**Pull request by cowtowncoder**
Apologies for possibly doing this wrong, but I would like to give (at least read) access to fuzz issues to PJ Fanning.
I am the primary contact for these projects.
If there is a better way to request/grant access, please let me know.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
@cowtowncoder This is the correct way to manage access to OSS-Fuzz issues.

Could you sign the CLA to get this through the CI?

**Comment by cowtowncoder** [comment]
Thank you for quick follow up @AdamKorcz!

Added CLA for my main gmail address (and Github account); not sure how to trigger re-run of the workflow here.

**Comment by AdamKorcz** [comment]
Not sure why the CLA is still red. AFAIK it should turn green automatically. Have you had to also sign a CLA for your iki.fi email in the past?

**Comment by cowtowncoder** [comment]
I don't have much experience with automated CLA checkers. "iki.fi" address was included as alternate email for CLA when submitting so it should be covered I'd think.

**Comment by cowtowncoder** [comment]
Ah. I forgot to click a button that was mentioned for re-scan. Seems to work now.

**Review by AdamKorcz — APPROVED** [review]

**Comment by cowtowncoder** [comment]
@pjfanning I think you should now have access. Issue I commented on is this one:

https://oss-fuzz.com/testcase-detail/6259527141425152

under `projects/jackson-core`.

**Pull request merged**
