### PR TITLE
[Initial integration] npm/qs

### PR DESCRIPTION
**Pull request by ljharb**

### CODE REVIEW

**Comment by DonggeLiu** [comment]
Thanks, @ljharb.
Could you share more about the project's primary users?

**Comment by ljharb** [comment]
Anyone who uses JavaScript to parse or create query strings, such as used in URLs - in the browser or on the server.

**Comment by ljharb** [comment]
any update?

**Comment by DonggeLiu** [comment]
Yep, the panel has approved.
Please proceed, thanks :)

**Comment by ljharb** [comment]
Thanks! I’ll take a look at the guide - i gather that i should update this PR, and that it won’t be approved and merged until later? (I’d have expected this PR to be landed, and for me to need to open another PR for the integration step)

**Comment by DonggeLiu** [comment]
>  i gather that i should update this PR, and that it won’t be approved and merged until later? 

Yes, please push all integration commits to this PR : )
Speaking of that, could you please add 'initial integration' in the PR title? We would appreciate that!

**Pull request merged**
