### PR TITLE
[Litmus]: Added initial integration 

### PR DESCRIPTION
**Pull request by Saranya-jena**
[Litmus](https://litmuschaos.io/) is an open source Chaos Engineering platform that enables teams to identify weaknesses & potential outages in infrastructures by inducing chaos tests in a controlled way.

Developers & SREs can simply execute Chaos Engineering with Litmus as it is easy to use, based on modern chaos engineering practices & community collaborated. Litmus is 100% open source & CNCF-incubated.

Github repo: https://github.com/litmuschaos/litmus
Documentation: https://docs.litmuschaos.io/

### CODE REVIEW

**Comment by prithvi1307** [comment]
Hello @DonggeLiu would you be able to help review this? Thanks for all the amazing work you have been helping with!

**Comment by DonggeLiu** [comment]
Thanks for the PR!
Let me check if the panel would like to accept this.

> Hello @DonggeLiu would you be able to help review this? Thanks for all the amazing work you have been helping with!

**Comment by prithvi1307** [comment]
Hey @DonggeLiu 
This is the main LitmusChaos repo and as a CNCF incubating project it is being used by many users. We are looking to apply for graduation once our fuzzing suite is ready and audited. The users include: Alstom, Liberty Mutual Insurance, RedHat, Infracloud, IFS, Ericsson, Nokia, Flipkart, FIS, Adidas and so many more community users. This is an urgent PR we are trying to raise for the project.

**Review by DonggeLiu — APPROVED** [review]
Thanks, the panel has approved!

**Pull request merged**
