### PR TITLE
rapidjson: enable extended fuzzer

### PR DESCRIPTION
**Pull request by tyler92**
There are no compilation errors with the latest builder image so we can reenable extended fuzzer for rapidjson. This patch also contains cosmetic improvements for the compilation command.

### CODE REVIEW

**Comment by DonggeLiu** [comment]
Gentle ping @guidovranken @miloyip

**Review by guidovranken — APPROVED** [review]

**Comment by guidovranken** [comment]
Approved. I will be deleting all my Github repositories shortly. Take anything you need asap.

**Comment by DonggeLiu** [comment]
> Approved. I will be deleting all my Github repositories shortly. Take anything you need asap.

Thanks for the information!

@tyler92 would you mind relocating [these two repos](https://github.com/google/oss-fuzz/blob/d41dd0fd50a082957bd8cc35defc389ff2f3026f/projects/rapidjson/Dockerfile#L20-L21) elsewhere (e.g., in the project under test), given guidovranken will remove them shortly? Much appreciated.

**Comment by tyler92** [comment]
I forked these two repositories just in case, but here’s how I see the situation:

There are two fuzzers for `rapidjson`: `fuzzer` and `fuzzer-extended` (currently disabled). The first fuzzer is simple and can easily be hosted in the `rapidjson` repository. The second fuzzer is more complex and uses a custom "engine" written by guidovranken. This engine is universal and works with any JSON parsing library, so the `rapidjson` repository is not the best place for it.

Based on this, I did the following: I copied `fuzzer.cpp` into the `oss-fuzz` repository and improved it to achieve much better coverage. Ideally, this fuzzer should be in the `rapidjson` repository, and I will try to move it there. However, I think this could take a while.

For now, I suggest merging this PR because it’s better than not building the project at all. This PR can still be considered a fuzzing improvement, even without these two repositories.

**Comment by DonggeLiu** [comment]
Thanks for the detailed description and look forward to your follow-up PR to relocate `fuzzer.cpp` at your convenience, @tyler92 !

I will merge this PR so that project can at least build, we appreciate your effort in fixing that.

**Review by DonggeLiu — APPROVED** [review]

**Pull request merged**
