### PR TITLE
simdutf: Initial integration

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
cc @lemire, thoughts on integrating simdutf?

TODOs:
- [ ] Switch over `git clone` to use main fork instead of my personal fork once https://github.com/simdutf/simdutf/pull/221 is merged.

This project is critical to global IT infrastructure and is used in the following projects;
- [Node.js](https://nodejs.org/en/) (19.4.0 or better), a standard JavaScript runtime environment (e.g., buffer.isUtf8(...), buffer.isAscii(...), TextDecoder calls simdutf),
- [Bun](https://bun.sh/), a fast JavaScript runtime environment,
- [haskell/text](https://github.com/haskell/text), a library for fast operations over Unicode text,
- [klogg](https://github.com/variar/klogg), a Really fast log explorer,
- [Pixie](https://github.com/pixie-io/pixie), observability tool for Kubernetes applications.

**Comment by lemire** [comment]
Of course! Great idea!

**Comment by jonathanmetzman** [comment]
Is there a lot of arch-specific ASM code in this project? we can't guarantee what type of x86_64 CPU stuff gets run on so we don't really allow things like -mnative

**Comment by silvergasp** [comment]
> WHo are some of the users of simdtuf?

The major projects that use simdutf are listed in https://github.com/google/oss-fuzz/pull/9942#issuecomment-1474211283. I think even just the Node.js and Bun integrations cover a pretty large user base.

 * [Node.js](https://nodejs.org/en/) (19.4.0 or better), a standard JavaScript runtime environment (e.g., buffer.isUtf8(...), buffer.isAscii(...), TextDecoder calls simdutf),
 * [Bun](https://bun.sh/), a fast JavaScript runtime environment,
 * [haskell/text](https://github.com/haskell/text), a library for fast operations over Unicode text,
 * [klogg](https://github.com/variar/klogg), a Really fast log explorer,
 * [Pixie](https://github.com/pixie-io/pixie), observability tool for Kubernetes applications.

> Is there a lot of arch-specific ASM code in this project? we can't guarantee what type of x86_64 CPU stuff gets run on so we don't really allow things like -mnative

@lemire feel free to correct me anywhere here. There is arch-specific code in this project. But as far as I'm aware the different implementations of arch-specific code are enabled/disabled at runtime based on the CPUID rather than using `-march=native` etc. I believe there is also a fallback version in case the CPU does not support SIMD extensions. This project should run on most CPUs. In fact, it would probably benefit the project if it was fuzzed on multiple different CPUs as there is a chance that different sections of code may be exercised depending on the CPU extensions available. Although I'd anticipate that there may be some funky code-coverage results depending on which CPU it runs on.

**Comment by lemire** [comment]
Two libraries I work on are tested as part of oss-fuzz, simdjson and CRoaring. Both rely on runtime dispatching. The simdjson library has been fuzzed by  oss-fuzz for quite a long time at this point.

Please see 

https://github.com/simdjson/simdjson/tree/master/fuzz

> Is there a lot of arch-specific ASM code in this project? 

There is no assembly code whatsoever. It is pure C++. It runs on a wide range of C++ compilers.

> I think even just the Node.js and Bun integrations cover a pretty large user base.

Indeed. It has been released as part of Node.js LTS releases.

>  as I'm aware the different implementations of arch-specific code are enabled/disabled at runtime based 

That's correct. And that's only an issue under x64 where we support legacy x86, SSE2-era processors, AVX2-era processors (haswell), and recent AVX-512 processors.

On ARM processors, there is no runtime dispatching as it is not needed. E.g., on my macbook, we just use NEON.

> The bigger problem is when you find a crash.

Runtime dispatching (the technique used by simdutf) is not unique to simdutf and it has been tested in production for decades at this point. Languages like Go, Java, C/C++... do use  runtime feature detection as part of the core libraries. In Go, runtime function dispatching is effectively built into the language. LLVM and GCC have functionalities built in the compiler too. [Glibc uses runtime dispatching](https://github.com/ihtsae/glibc/commit/5f3d0b78e011d2a72f9e88b0e9ef5bc081d18f97) to pick the most optimized function based on the hardware (for things like memcpy and string operations). [Java](http://hg.openjdk.java.net/jdk8u/jdk8u/hotspot/file/c1374141598c/src/cpu/x86/vm/stubGenerator_x86_64.cpp#l1297) is great at runtime dispatching, and so forth.  [Even PHP uses SIMD instructions for some string algorithms](https://github.com/php/php-src/blob/e5cb53ec68603d4dbdd780fd3ecfca943b4fd383/ext/standard/string.c).  So you will find functions like ` is_avx_supported(void)` in PHP for this reason. In a programming language like Java, it is amazing because the Java code will get compiled to the system, using the instructions available to the system (including even the fanciful AVX-512).


The way we deal with the issue you address is that we test *all* kernels. Obviously, this means that reproducibility is slightly harder... but only slightly so.


Anyhow, my core point is that _simdutf_ is not using anything weird that people are not commonly using in production. It is likely that many libraries being tested by oss-fuzz have some form of runtime dispatching based on CPU features, and even when they do not, glibc does... 

cc @jan-wassenberg

**Comment by jan-wassenberg** [comment]
Just a quick comment that runtime dispatch is increasingly common and important, because CPU baselines (minimum requirements) are advancing very very slowly (>10 years old) and using only the lowest-common denominator features would leave too much performance on the table.

As to concerns about reproducibility: how about we print which arch is being used (eg when an error is encountered) and make sure we test on that same arch when reproducing/declaring it fixed?

**Comment by silvergasp** [comment]
> It's worse than code coverage being an issue. The bigger problem is when you find a crash. CF my try to repro on a different CPU and then think a crash was fixed.

@jonathanmetzman what if by convention @lemire and I were to simply ignore the reproducibility tags on each of the crashes, with the knowledge that some crashes may be real bugs but not be reproducible? Would that solve the problem or are there other concerns? I'm aware that there are differing automatic disclosure timelines for bugs that are fixed vs. unfixed bugs, but I'm not entirely sure about the specifics.

If the OSS-fuzz project is specifically disallowing projects using SIMD extensions does that then extend to their dependants e.g. Node.js?

**Comment by lemire** [comment]
Under x64, we have 4 distinct kernels. One can specify them at runtime. So if a bug is reported, you can (in the worst case) try all four kernels.

The simdutf library is rather simple. All code is deterministic. There is no randomness or multithreading involved. Same input should produce same output, always.

> As to concerns about reproducibility: how about we print which arch is being used (eg when an error is encountered) and make sure we test on that same arch when reproducing/declaring it fixed?

We can print the active kernel like so:

```C++
        const implementation *impl = simdutf::active_implementation;
        cout << "simdutf is optimized for " << impl->name() << "(" << impl->description() << ")" << endl;
```

I have not modified the code because I don't know whether we should print out anything during the normal course of a check.

**Comment by silvergasp** [comment]
> Under x64, we have 4 distinct kernels. One can specify them at runtime. So if a bug is reported, you can (in the worst case) try all four kernels.

If it's possible to manually specify the kernel at runtime, I could probably modify the fuzzer to choose the kernel based on the fuzzed data. Something like [PickValueInArray](https://github.com/llvm/llvm-project/blob/main/compiler-rt/include/fuzzer/FuzzedDataProvider.h#L75) comes to mind. At least that way the choice of which kernel is used would be deterministic (based on the fuzzed data). It would also have the side affect that if OSS-fuzz decided that it wanted to use a different CPU to "reproduce" a bug it would fail with some kind of invalid instruction error, so It would still show up as a reproducible bug. But I'm unsure how to handle the opposite where we would need to "catch" invalid instruction errors.

**Comment by silvergasp** [comment]
> So you can check all possible kernels... of course, this depends on the underlying CPU architecture. E.g., you cannot test a kernel that requires AVX-512 on a processor that does not support AVX-512. (Well, you could, but you'd have to use Intel's emulator... or something of the sort... but that's not very practical of fuzzing...)

Ok well, that sounds reasonable. Let's see what the verdict is from @jonathanmetzman and then we can move forward from there :) Worst case scenario if it's still not going to be a good fit for oss-fuzz I'll make a [clusterfuzz lite config](https://google.github.io/clusterfuzzlite/), which is essentially a scaled-down version of OSS-fuzz that runs on github actions.

**Comment by lemire** [comment]
I should stress that simdjson has worked well with oss-fuzz for a really long time, and it is basically an identical mechanism. I am a little be unsure about what the problem is. I have not looked at the set of libraries that oss-fuzz supports, but I would be very surprised if these were the only ones support runtime dispatching. It is definitive quite standard at this point in time. Again: it is part of our standard runtime librairies.

**Comment by jonathanmetzman** [comment]
> I should stress that simdjson has worked well with oss-fuzz for a really long time, and it is basically an identical mechanism. I am a little be unsure about what the problem is. I have not looked at the set of libraries that oss-fuzz supports, but I would be very surprised if these were the only ones support runtime dispatching. It is definitive quite standard at this point in time. Again: it is part of our standard runtime librairies.

OK, then this should probably work then

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
