### PR TITLE
[bignum-fuzzer] Update mpdecimal to version 4.0.0

### PR DESCRIPTION
**Pull request by skrah**
mpdecimal-4.0.0 has been released:

https://www.bytereef.org/mpdecimal/changelog.html

It would be nice to update the fuzzer.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@guidovranken do you approve?

**Comment by guidovranken** [comment]
> @guidovranken do you approve?
Yes please merge, thanks @skrah

**Comment by guidovranken** [comment]
Wait. @skrah can you do the same in the `cryptofuzz` project please?

**Comment by guidovranken** [comment]
> Wait. @skrah can you do the same in the `cryptofuzz` project please?

Just do this

```diff
diff --git a/projects/cryptofuzz/Dockerfile b/projects/cryptofuzz/Dockerfile
index 9d3e11796..3d058de30 100644
--- a/projects/cryptofuzz/Dockerfile
+++ b/projects/cryptofuzz/Dockerfile
@@ -48,7 +48,7 @@ RUN git clone --depth 1 https://github.com/libtom/libtomcrypt.git
 RUN git clone --depth 1 https://github.com/microsoft/SymCrypt.git
 RUN hg clone https://gmplib.org/repo/gmp/ libgmp/ || \
     (wget 'https://ftp.gnu.org/gnu/gmp/gmp-6.2.1.tar.lz' && tar xf gmp-6.2.1.tar.lz && mv $SRC/gmp-6.2.1/ $SRC/libgmp/)
-RUN wget https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-2.5.1.tar.gz
+RUN wget https://www.bytereef.org/software/mpdecimal/releases/mpdecimal-4.0.0.tar.gz
 RUN git clone --depth 1 https://github.com/indutny/bn.js.git
 RUN git clone --depth 1 https://github.com/MikeMcl/bignumber.js.git
 RUN git clone --depth 1 https://github.com/guidovranken/libfuzzer-js.git
diff --git a/projects/cryptofuzz/build.sh b/projects/cryptofuzz/build.sh
index 653387101..8d8d327c2 100755
--- a/projects/cryptofuzz/build.sh
+++ b/projects/cryptofuzz/build.sh
@@ -322,8 +322,8 @@ make -B
 
 # Compile mpdecimal
 cd $SRC/
-tar zxf mpdecimal-2.5.1.tar.gz
-cd mpdecimal-2.5.1/
+tar zxf mpdecimal-4.0.0.tar.gz
+cd mpdecimal-4.0.0/
 ./configure
 cd libmpdec/
 make libmpdec.a -j$(nproc)
```

**Comment by skrah** [comment]
@guidovranken Thanks, done!

**Review by DavidKorczynski — APPROVED** [review]

**Comment by skrah** [comment]
@guidovranken All functions in `mpdecimal` use base `10**19` (64-bit build) or base `10**9` (32-bit build). This is because all functions are required to round in base 10.

If the internal calculations were in, say, base `2**64`, then the result would have to be converted before every rounding step and that would be slower (base conversions are very slow).  Decimal libraries just cannot compete with binary arithmetic. I'm actually surprised that the difference isn't larger.

`mpd_qpowmod` is a bit of an odd one because it only accepts integers and produces an integer result. But even then the results need to be in base 10 for use of other functions.

If you have a faster *algorithm* in mind, of course I'd be interested.

**Pull request merged**
