### PR TITLE
Fix go coverage build regression.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Review by oliverchang — COMMENTED** [review]
Thanks! I think this needs to be copied into `base-builder-new` instead, to handle multi-language projects. @jonathanmetzman is this correct?

**Review by oliverchang — APPROVED** [review]
thanks a lot!

**Comment by inferno-chromium** [comment]
> Thanks! I think this needs to be copied into `base-builder-new` instead, to handle multi-language projects. @jonathanmetzman is this correct?

yes right!

**Comment by inferno-chromium** [comment]
verified locally, so merging to start builds.

**Comment by catenacyber** [comment]
Thanks :-)

**Pull request merged**
