### PR TITLE
Add options, dictionaries, and seed corpuses to gRPC

### PR DESCRIPTION
**Pull request by matt-kwong**
In addition to the changes described in the title, `test/core/security/ssl_server_fuzzer.c` will be temporarily disabled with the issue described in #373 and will be enabled in a future PR after gRPC Bazel rules are written for fuzzing.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
It is recommended to move the all *.options file in your own repo. is that doable, or this is ok for now...

**Comment by inferno-chromium** [comment]
Lets take these for now, *.options can be moved into your repo later.

**Comment by matt-kwong** [comment]
I can move the *.options files to gRPC's repo. I'll remove the files in a future PR.

**Comment by inferno-chromium** [comment]
Thanks @matt-kwong !

**Pull request merged**
