### PR TITLE
[rdkit] Re-enable memory and i386 architecture

### PR DESCRIPTION
**Pull request by intrigus-lgtm**
Re-enable memory sanitizer.
Re-enable i386 architecture.
Fix copyright notice year.
Build boost in `build.sh` instead of Dockerfile.

### CODE REVIEW

**Comment by intrigus-lgtm** [comment]
Hey @jonathanmetzman could (or anybody else) help me here?
I don't understand why boost is suddenly not finding `zlib`.
Here (This PR):
`    - zlib                     : no`
https://travis-ci.org/github/google/oss-fuzz/jobs/689407400#L562


VS. (https://github.com/google/oss-fuzz/pull/3747) (Initial PR)
`    - zlib                     : yes`
https://travis-ci.org/github/google/oss-fuzz/jobs/686491075#L520

The only change should be that boost is now build in `build.sh` and not in `Dockerfile`.
`zlib` itself seems to be properly installed in both cases, i.e. `dpkg -L zlib1g-dev` returns the same paths.

**Comment by inferno-chromium** [comment]
> Hey @jonathanmetzman could (or anybody else) help me here?
> I don't understand why boost is suddenly not finding `zlib`.
> Here (This PR):
> ` - zlib : no`
> https://travis-ci.org/github/google/oss-fuzz/jobs/689407400#L562
> 
> VS. (#3747) (Initial PR)
> ` - zlib : yes`
> https://travis-ci.org/github/google/oss-fuzz/jobs/686491075#L520
> 
> The only change should be that boost is now build in `build.sh` and not in `Dockerfile`.
> `zlib` itself seems to be properly installed in both cases, i.e. `dpkg -L zlib1g-dev` returns the same paths.

This is my mistake. When i was adding python 3.8 support, i left the dependencies in the docker image. https://github.com/google/oss-fuzz/commit/37fbb75094f376001580a8138f6bc59849d11726 cleans those up. So, you need to explicitly install your dependencies in your Dockerfile.

**Comment by intrigus-lgtm** [comment]
> > Hey @jonathanmetzman could (or anybody else) help me here?
> > I don't understand why boost is suddenly not finding `zlib`.
> > Here (This PR):
> > ` - zlib : no`
> > https://travis-ci.org/github/google/oss-fuzz/jobs/689407400#L562
> > VS. (#3747) (Initial PR)
> > ` - zlib : yes`
> > https://travis-ci.org/github/google/oss-fuzz/jobs/686491075#L520
> > The only change should be that boost is now build in `build.sh` and not in `Dockerfile`.
> > `zlib` itself seems to be properly installed in both cases, i.e. `dpkg -L zlib1g-dev` returns the same paths.
> 
> This is my mistake. When i was adding python 3.8 support, i left the dependencies in the docker image. [37fbb75](https://github.com/google/oss-fuzz/commit/37fbb75094f376001580a8138f6bc59849d11726) cleans those up. So, you need to explicitly install your dependencies in your Dockerfile. install libbz2-dev as well.

That does not seem to be the problem.

The problem seems to be that boost (if build with all flags applied by oss-fuzz inside `build.sh`) can not find `zlib`.
If I build boost inside the `Dockerfile` none of these extra flags are applied and boost properly finds zlib...
I'm investigating which flag boost doesn't like.

**Comment by intrigus-lgtm** [comment]
Compiling without the commented flags works.
So it looks like boost doesn't like sanitizer flags!?
````bash
# -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link
./b2 -q -j$(nproc) toolset=clang cxxflags="-fPIC -O1 -fno-omit-frame-pointer -gline-tables-only -stdlib=libc++ -stdlib=libc++" link=static install --debug-configuration

**Comment by inferno-chromium** [comment]
> Compiling without the commented flags works.
> So it looks like boost doesn't like sanitizer flags!?
> 
> ```shell
> # -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link
> ./b2 -q -j$(nproc) toolset=clang cxxflags="-fPIC -O1 -fno-omit-frame-pointer -gline-tables-only -stdlib=libc++ -stdlib=libc++" link=static install --debug-configuration
> ```

boost is a project in OSS-Fuzz, so you can consult the build.sh there.

**Comment by intrigus-lgtm** [comment]
Fixed CLA requirements by opening https://github.com/google/oss-fuzz/pull/3955 from my other account...

**Pull request closed without merging**
