### PR TITLE
GLib

### PR DESCRIPTION
**Pull request by pdknsk**
[The authors have agreed.](https://gitlab.gnome.org/GNOME/glib/issues/1463) There are 2-3 targets here (parsers). I'll add them once approved.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
We approve of adding this project.

**Comment by pdknsk** [comment]
Please take a look.

**Comment by pdknsk** [comment]
Done.

**Comment by jonathanmetzman** [comment]
Thanks!

**Pull request merged**
