### PR TITLE
[libvips] remove unused giflib dependency

### PR DESCRIPTION
**Pull request by lovell**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32999

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Thanks! It's failing across the fuzzers with the following:
```
sed -e '/^#/d' remove-potcdate.sin > t-remove-potcdate.sed
mv t-remove-potcdate.sed remove-potcdate.sed
/usr/bin/xgettext --default-domain=libexif-12 --directory=.. \
  --add-comments=TRANSLATORS: --keyword=_ --keyword=N_ \
  --files-from=./POTFILES.in \
  --copyright-holder='Lutz Mueller and others' \
  --msgid-bugs-address='libexif-devel@lists.sourceforge.net'
/usr/bin/xgettext: Non-ASCII string at libexif/exif-tag.c:550.
                   Please specify the source encoding through --from-code.
Makefile:161: recipe for target 'libexif-12.pot-update' failed
make[3]: *** [libexif-12.pot-update] Error 1
make[3]: Leaving directory '/src/libexif/po'
Makefile:185: recipe for target 'libexif-12.pot' failed
make[2]: *** [libexif-12.pot] Error 2
make[2]: Leaving directory '/src/libexif/po'
Makefile:521: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/src/libexif'
Makefile:405: recipe for target 'all' failed
```

**Comment by lovell** [comment]
It looks like the libexif master branch is currently broken due to https://github.com/libexif/libexif/pull/61

**Comment by DavidKorczynski** [comment]
> It looks like the libexif master branch is currently broken due to [libexif/libexif#61](https://github.com/libexif/libexif/pull/61)

Good catch. Let's see if they respond to your request.

**Comment by DavidKorczynski** [comment]
Waiting for this https://github.com/libexif/libexif/pull/62 to merge and then we can trigger CI again.

**Comment by DavidKorczynski** [comment]
Thanks @lovell

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
