### PR TITLE
Fuzz minizip

### PR DESCRIPTION
**Pull request by nmoinvaz**
This pull request adds the minizip project to oss-fuzz. #1940

### CODE REVIEW

**Comment by nmoinvaz** [comment]
I signed it!

**Comment by jonathanmetzman** [comment]
Hmmm... It looks like the cla bot says you still haven't signed.
Can you verify that you have signed the agreement with the email address associated with this GitHub account?

**Comment by nmoinvaz** [comment]
My other email address should now be associated with it.

**Comment by Dor1s** [comment]
Thanks for the fixes. Looking at your upstream patch, I don't think that you need the following line: https://github.com/nmoinvaz/minizip/commit/1f9efeae4f053bcc57be5c2dcb512a83a49a330c#diff-af3b638bc2a3e6c650974192a53c7291R610

```cmake
        set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -fsanitize=fuzzer")
```

`-fsanitize=fuzzer` enables libFuzzer-specific instrumentation (and we use another instrumentation flags for AFL), so it's essentially hardcoding some libFuzzer specific, which we should avoid when building the projects. All the flags are controlled by OSS-Fuzz builder (and can be expanded to even more fuzzing engines / instrumentation types). The projects should just use CFLAGS / CXXFLAGS and link against `-lFuzzingEngine` which again is controlled by OSS-Fuzz and can be silently upgraded, etc.

**Comment by nmoinvaz** [comment]
That should be resolved now too. Let me know if there is anything else.

**Pull request merged**
