### PR TITLE
suricata: clean some disk space while building

### PR DESCRIPTION
**Pull request by catenacyber**
As done by openssl in https://github.com/google/oss-fuzz/pull/11618

Is there a way from build.sh to know if we are built by CIFuzz ? Like environment variable `CFL_PLATFORM` ?
Because I do not think we want to build other branches than master for CIFuzz

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
> As done by openssl in #11618
> 
> Is there a way from build.sh to know if we are built by CIFuzz ? Like environment variable `CFL_PLATFORM` ? Because I do not think we want to build other branches than master for CIFuzz

There is, let me get it for you

**Comment by catenacyber** [comment]
> > As done by openssl in #11618
> > Is there a way from build.sh to know if we are built by CIFuzz ? Like environment variable `CFL_PLATFORM` ? Because I do not think we want to build other branches than master for CIFuzz
> 
> There is, let me get it for you

@jonathanmetzman did you find it ?

**Comment by catenacyber** [comment]
Thanks @kleisauke cf #11800

**Comment by catenacyber** [comment]
This seems to have broken coverage build despite green CI cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=68045

`make clean` removes some generated code files like `gen/rust-bindings.h' so we get

> Step #5: [0m[0;31merror: /workspace/out/libfuzzer-coverage-x86_64/src/suricata7/rust/gen/rust-bindings.h: No such file or directory

Fix pushed in #11800

**Pull request merged**
