### PR TITLE
Solidity: Enable abiv2 proto fuzzer

### PR DESCRIPTION
**Pull request by bshastry**
This PR
  - instruments evmone and its dependencies
  - enables abiv2 proto fuzzer

CC @chriseth

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Waiting for travis to give the OK before merging.

**Comment by bshastry** [comment]
I see the following message from the failing travis CI

> The job exceeded the maximum time limit for jobs, and has been terminated.

This is for afl, x86_64, asan setup. Would it be possible to rerun this job with a higher timeout limit?

**Comment by jonathanmetzman** [comment]
Looks like the failure was caused by a timeout only on AFL. Probably safe to land.

**Comment by jonathanmetzman** [comment]
Worth adding that you probably shouldn't build this fuzzer with AFL (don't know if you are) since AFL doesn't work with LPM.

**Comment by jonathanmetzman** [comment]
> I see the following message from the failing travis CI
> 
> > The job exceeded the maximum time limit for jobs, and has been terminated.
> 
> This is for afl, x86_64, asan setup. Would it be possible to rerun this job with a higher timeout limit?

Didn't see this before I replied. I don't think travis allows one to raise the timeout limit, but I haven't looked into this recently.

**Pull request merged**
