### PR TITLE
OSS_FUZZ integration for CROARING

### PR DESCRIPTION
**Pull request by K2**
Initial implementation to be expanded for coverage over time

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Thanks @K2 ! Could you write a few points on the clients of CROARING, i.e. why it's a security critical project?

**Comment by K2** [comment]
Were a highly used native C/C++ library used to optimize access to large data set's (a quick gtithub search resulted in 3000+ code hits).  As such many modern large data warehousing applications incorporate it's use to optimize access to data sets. Featured in https://github.com/oz123/awesome-c list and nearly 1000+ github *'s. If any flaws are present in it's memory handling of our library would possibly compromise the, extensive list of, applications using our library.

**Comment by DavidKorczynski** [comment]
> extensive list of, applications using our library.

I found client list is here http://roaringbitmap.org/ and examples include 
```
Google Procella: YouTube’s SQL Engine,
Apache Lucene and derivative systems such as Solr and Elasticsearch,
Apache Druid,
Apache Spark,
Apache Hive,
Apache Tez,
Apache Zeppelin,
Apache Doris,
Apache CarbonData,
Yandex ClickHouse,
Netflix Atlas,
LinkedIn Pinot,
OpenSearchServer,
Cloud Torrent,
Whoosh,
InfluxDB,
Pilosa,
Bleve,
Microsoft Visual Studio Team Services (VSTS),
Intel’s Optimized Analytics Package (OAP),
Tablesaw,
Jive Miru,
Gaffer,
Apache Hivemall,
lindb,
Elasticell,
SourceGraph,
M3,
trident,
```

**Comment by DavidKorczynski** [comment]
@K2 can you confirm you maintainers of the project are happy with this, and also that you will be receiving details about the potential issues?

**Comment by jonathanmetzman** [comment]
Deferring merging this until we know maintainers are OK with accepting.
We are OK with accepting for the record.

**Comment by K2** [comment]
@lemire This is the minimal test case (deserialize only) that we wrote a few weeks ago and can expand on as we broaden the garuntee's for additional interfaces. If you could respond to the thread here to get it merged, thanks.

**Comment by lemire** [comment]
Sorry. Yes. This is good. (I am the 'main' maintainer of the project.)

OK OK OK

(Sorry for the delay.)

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
