### PR TITLE
fluent-bit: added dependency (openssl)

### PR DESCRIPTION
**Pull request by leonardo-albertovich**
fluent-bit is transitioning from mbedtls to openssl making the latter mandatory and completely remove the former.
 
Signed-off-by: Leonardo Alminana <leonardo@calyptia.com>

### CODE REVIEW

**Comment by leonardo-albertovich** [comment]
I have already signed the CLA and there seems to be a build issue that's unrelated to my PR. This PR is meant to keep this system working once the mbedtls deprecation PR is merged but that is not the case at the moment so I don't think the failure should be taken in account.

**Comment by jonathanmetzman** [comment]
Please fix build failure

**Comment by leonardo-albertovich** [comment]
It's complicated because the PR I'm working on actually fixes (removing mbedtls) but has not been merged yet, should I notify you once that PR is merged? I thought updating oss-fuzz before was the right thing so it could properly run on the PRs CI tasks before the PR is merged. 

It's kind of an egg and hen situation so could you please tell me what to do?

**Comment by DavidKorczynski** [comment]
This is to protect CIFuzz? I've done a lot of the Fluent-bit work and I think it has failed at times in the past so I wouldn't be too worried.

A solution to this chicken and egg situation is to move the entire logic of `build.sh` into https://github.com/fluent/fluent-bit/tree/master/tests/internal/fuzzers Then, we can simply have a build script in OSS-Fuzz that calls the script in fluent-bit/tests/internal/fuzzers and on the Fluent-bit side you can remove mbedtls and update the build script in the same PR.

**Comment by leonardo-albertovich** [comment]
Alrighty, I'll get this sorted out and ping you once the tests are passing, thanks for your help!

**Comment by leonardo-albertovich** [comment]
@jonathanmetzman I noticed that when triggered through [this](https://github.com/fluent/fluent-bit/blob/e972819043f17a62d9c37249e9debc862d6909e8/.github/workflows/pr-fuzz.yaml) CI workflow oss-fuzz acts on master regardless of being "called" by a PR.

I managed to reproduce the scenario locally using the python scripts and modifying `build.sh` so it stalls instead of running make so I could manually inspect everything and switch to the PR branch (which worked btw).

I hope I'm being clear enough, I would like to modify the configuration so it checks out the appropriate PR branch but I don't know how to do it, would you be able to point me in the right direction? 

Thanks!

**Comment by leonardo-albertovich** [comment]
The master branch in fluent-bit has been updated and this should work fine now.

**Comment by leonardo-albertovich** [comment]
Hey @jonathanmetzman since tests are passing now, could we have this merged? Please let me know if you need me to do anything else.

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
