### PR TITLE
Prepare for JavaScript fuzzing

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Related: #8324

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @fmeum

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by fmeum** [comment]
CC @bertschneider

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py zlib --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py zlib --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py zlib --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Review by Navidem — APPROVED** [review]

**Review by oliverchang — COMMENTED** [review]
Amazing!

**Pull request merged**
