### PR TITLE
projects: add celestiaorg/smt

### PR DESCRIPTION
**Pull request by cuonglm**
This project is an implementation of Sparse Merkle tree, which will be
used by Celestia, Cosmos SDK, ... and maybe other blockchain ecosystem.
We want to make sure the code is fuzzed to catch highly impacted bug as
soon as possible.

See:
 - https://github.com/celestiaorg
 - https://docs.cosmos.network/v0.42/

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em

**Review by odeke-em — APPROVED** [review]
LGTM, thank you @cuonglm!

To oss-fuzz Maintainers, thank you for all the great work, oss-fuzz is the gift that keeps on giving. celestiaorg/smt is in the critical path of dependencies of high value infrastructure but it is also general purpose and usable in diverse crytopgraphic purposes. Please accept our PR. Thank you.

**Comment by jonathanmetzman** [comment]
>To oss-fuzz Maintainers, thank you for all the great work, oss-fuzz is the gift that keeps on giving.

:-)


>diverse crytopgraphic purposes

Could you elaborate on this? E.g. who is using it? Is it telcos? Banks? tech companies, why is it important?

**Comment by adlerjohn** [comment]
> Could you elaborate on this? E.g. who is using it? Is it telcos? Banks? tech companies, why is it important?

Contemporary blockchains (such as Celestia and Ethereum) [commit](https://en.wikipedia.org/wiki/Commitment_scheme) to their state ([reference](https://eprint.iacr.org/2018/1188)), usually with some form of a [Merkle tree](https://en.wikipedia.org/wiki/Merkle_tree). The _Sparse Merkle Tree_ (SMT) implemented in https://github.com/celestiaorg/smt is the highest-performance design that is currently known for a state commitment.

This design and implementation will be used in the near future across a large number of projects in the [Celestia](https://celestia.org/), [Cosmos](https://cosmos.network/), and [Ethereum](https://ethereum.org/en/) ecosystems, just to name a few. At the time of writing, more than a quarter of a trillion US dollars is handled across these ecosystems, and that number is only expected to grow in the coming years.

**Comment by liamsi** [comment]
Google even has its own SMT implementation (as part of https://github.com/google/trillian) with slightly other tradeoffs as far as I remember.

**Comment by cuonglm** [comment]
Kindly ping @jonathanmetzman 😃

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
