### PR TITLE
[wasmtime] initial integration

### PR DESCRIPTION
**Pull request by jfoote**
Hello all,

This is an initial PR for wasmtime Rust fuzz targets, as discussed on https://github.com/google/oss-fuzz/pull/3285. ([Bytecode Alliance tracking issue](https://github.com/bytecodealliance/wasmtime/issues/611#issuecomment-566574017)).

I didn't see clear consensus on whether to use the cargo-fuzz-bundled libfuzzer or linking the oss-fuzz version via `LIB_FUZZING_ENGINE_DEPRECATED`, so I left the code as-is using `LIB_FUZZING_ENGINE_DEPRECATED` for now. Pardon if I misunderstood there -- if we should change it for this PR or anytime please just let me know.

cc @fitzgen @jonathanmetzman 

Thanks,
Jon

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Will wait for travis to finish to merge

**Comment by jonathanmetzman** [comment]
> Hello all,
> 
> This is an initial PR for wasmtime Rust fuzz targets, as discussed on #3285. ([Bytecode Alliance tracking issue](https://github.com/bytecodealliance/wasmtime/issues/611#issuecomment-566574017)).
> 
> I didn't see clear consensus on whether to use the cargo-fuzz-bundled libfuzzer or linking the oss-fuzz version via `LIB_FUZZING_ENGINE_DEPRECATED`, so I left the code as-is using `LIB_FUZZING_ENGINE_DEPRECATED` for now. Pardon if I misunderstood there -- if we should change it for this PR or anytime please just let me know.

Sorry for not being clear. You should leave as is and use LIB_FUZZING_ENGINE_DEPRECATED.

**Comment by jonathanmetzman** [comment]
I think we want to specify libfuzzer under engines otherwise honggfuzz and afl builds will be done as well.

**Comment by jonathanmetzman** [comment]
The libFuzzer ASAN build passed last time: https://travis-ci.org/google/oss-fuzz/jobs/641563087?utm_medium=notification&utm_source=github_status

**Comment by jfoote** [comment]
If you need anything else here just LMK.

**Comment by jonathanmetzman** [comment]
Don't need anything else. Sorry I didn't get to merge this before the weekend.

**Comment by jonathanmetzman** [comment]
Looks like build is failing. 
https://oss-fuzz-build-logs.storage.googleapis.com/log-336d15f7-d5fb-4db2-ae8a-49e9b990147a.txt

We (OSS-Fuzz devs) probably need to look into this since it passed on travis.

**Comment by jfoote** [comment]
Thanks for looking into this @jonathanmetzman and @alexcrichton! For posterity, @alexcrichton is taking a shot at fixing this issue in https://github.com/google/oss-fuzz/pull/3298.

The build succeeds for me locally, both for https://github.com/google/oss-fuzz/pull/3292/commits/a9febdfcd3afaedcb743714b47ca85c2880ba71f (tested previously) and Alex's https://github.com/alexcrichton/oss-fuzz/commit/1365cfd65cc0f16a219920b8d87361782392f44f (tested presently).

It is not clear to me why this is failing. I noted that `msan-builder` is referenced in the build log but we intended [to build the fuzz target only with asan](https://github.com/google/oss-fuzz/pull/3292/files#diff-4a99f29f81d9e6d4d614a03bc0b5b493R7). I'm not sure if that is related to the issue though. It isn't clear to me why building with msan would be generating the error that the build exits on regardless.

**Pull request merged**
