### PR TITLE
switch to AFL++'s new pcguard instrumentation

### PR DESCRIPTION
**Pull request by vanhauser-thc**
See discussion in #9461
@jonathanmetzman please merge soon.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
A few breakages
[breaks2.zip](https://github.com/google/oss-fuzz/files/11626727/breaks2.zip)

**Comment by vanhauser-thc** [comment]
I would say only one of these is a potential afl++ issue:

cairo+glib+ostree:
Step #19 - "compile-afl-address-x86_64": /usr/bin/ld: gio/tests/test_resources2.o:(.data._ZN11__sanitizer15IOCTL_KDGKBSENTE+0x0): multiple definition of `__sanitizer::IOCTL_KDGKBSENT'; /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25

how could that be an afl++ problem?


flexc:
Step #17:E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/d/dvisvgm/dvisvgm_2.8.1-1build1_amd64.deb  Undetermined Error [IP: 91.189.91.39 80]
Step #17: E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

It would be good if such errors could automatically be detected and handled.


freetype:
Step #19 - "compile-afl-address-x86_64": In file included from /src/freetype2-testing/external/llvm-project/libcxxabi/src/cxa_virtual.cpp:9:
Step #19 - "compile-afl-address-x86_64": ESC[1m/src/freetype2-testing/external/llvm-project/libcxxabi/include/cxxabi.h:43:26: error: unknown type name 'size_t'

does not look like an afl++ issue either


gpsd:
Step #19 - "compile-afl-address-x86_64": /src/aflplusplus/afl-clang-fast++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope   -L../gpsd-3.25.1~dev/ -o FuzzJson FuzzJson.o  /usr/lib/libFuzzingEngine.a -lgpsd -lgps_static
Step #19 - "compile-afl-address-x86_64": /usr/bin/ld: __sancov_guards has both ordered [`__sancov_guards[json_toff_read]' in ../gpsd-3.25.1~dev/libgps_static.a(libgps_json.o)] and unordered [`__sancov_guards[LLVMFuzzerTestOneInput]' in FuzzJson.o] sections
Step #19 - "compile-afl-address-x86_64": /usr/bin/ld: final link failed: bad value
Step #19 - "compile-afl-address-x86_64": clang-15: Error: linker command failed with exit code 1 (use -v to see invocation)

this one could be an afl++ issue, but I rather think that the project sets itself sancov options and then they collide.

**Comment by vanhauser-thc** [comment]
as it is llvm's internal implementation there wont be issues even with llvm 20 :)

**Comment by jonathanmetzman** [comment]
> I would say only one of these is a potential afl++ issue:
> 
> cairo+glib+ostree: Step #19 - "compile-afl-address-x86_64": /usr/bin/ld: gio/tests/test_resources2.o:(.data._ZN11__sanitizer15IOCTL_KDGKBSENTE+0x0): multiple definition of `__sanitizer::IOCTL_KDGKBSENT'; /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
> 
> how could that be an afl++ problem?

I don't know, but if this change breaks things, I still can't merge it.


> 
> freetype: Step #19 - "compile-afl-address-x86_64": In file included from /src/freetype2-testing/external/llvm-project/libcxxabi/src/cxa_virtual.cpp:9: Step #19 - "compile-afl-address-x86_64": ESC[1m/src/freetype2-testing/external/llvm-project/libcxxabi/include/cxxabi.h:43:26: error: unknown type name 'size_t'
> 
> does not look like an afl++ issue either

Hopefully this is gone

**Comment by jonathanmetzman** [comment]
Can't merge this with ~8 failures.

**Comment by vanhauser-thc** [comment]
@jonathanmetzman can you try this one?
I reimplemented pcguard, so updated our own pcguard implementation. this one should not have these assembly errors anymore.

**Pull request merged**
