### PR TITLE
[Zlog] Added project for initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
Hereby submitting Zlog for initial integration.

As agreed with deemar (https://github.com/HardySimpson/zlog/pull/172), the fuzzers can be placed on the upstream repository.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Please provide some information on the customers / users of zlog library.

**Comment by AdamKorcz** [comment]
@deemar @HardySimpson 
Do you have information about the userbase of Zlog?

**Comment by deemar** [comment]
Zlog is used by some Chinese companies include Huawei @AdamKorcz

**Comment by inferno-chromium** [comment]
Unfortunately, this project does not meet our selection criteria. See https://google.github.io/oss-fuzz/faq/#what-kind-of-projects-are-you-accepting. We still recommend running the fuzzers in upstream CI for the project.

**Pull request closed without merging**
