### PR TITLE
[ots] Enable more fuzzers

### PR DESCRIPTION
**Pull request by ebraminio**
As https://github.com/google/oss-fuzz/pull/4076 was following ots approach, let me see if things are okay here or needs similar fixes also.

### CODE REVIEW

**Comment by ebraminio** [comment]
Same fixes are indeed needed, proposed https://github.com/khaledhosny/ots/pull/214

**Comment by ebraminio** [comment]
That patch is merged, now should work

**Comment by ebraminio** [comment]
Still not able to expand '-Wl,-rpath,$ORIGIN/:/usr/lib/x86_64-linux-gnu', oh well :/

**Comment by inferno-chromium** [comment]
i386 and dataflow builds are failing, want to disable/remove those ?

**Comment by ebraminio** [comment]
> i386 and dataflow builds are failing, want to disable/remove those ? 

I like to have it fixed :/

On dataflow one,

`clang++  -o ots-fuzzer 'ots-fuzzer@exe/util_ots-fuzzer.cc.o' -Wl,--as-needed -Wl,--no-undefined -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=dataflow -fsanitize-coverage=trace-pc-guard,pc-table,bb,trace-cmp -stdlib=libc++ -Wl,--start-group libots.a libbrotli.a libwoff2.a liblz4.a /usr/lib/DataFlow.o /usr/lib/DataFlowCallbacks.o /usr/lib/x86_64-linux-gnu/libz.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/' -Wl,-rpath-link,/work/build/`

How ORIGIN environement variable went there without getting expanded first? Where is that coming from, CXXFLAGS? That shouldn't happen in `fuzzer_ldflags` as its `-Dfuzzer_ldflags="$(echo $LIB_FUZZING_ENGINE)"`, should I do that for other CXXFLAGS or CFLAGS or LDFLAGS? Isn't better to not send things needs to be evaluated to build systems anyway?

On i386 case,

`clang++  -o ots-fuzzer 'ots-fuzzer@exe/util_ots-fuzzer.cc.o' -Wl,--as-needed -Wl,--no-undefined -m32 -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -Wl,--start-group libots.a libbrotli.a libwoff2.a liblz4.a -fsanitize=fuzzer /usr/lib/x86_64-linux-gnu/libz.so -Wl,--end-group '-Wl,-rpath,$ORIGIN/:/usr/lib/x86_64-linux-gnu' -Wl,-rpath-link,/work/build/ -Wl,-rpath-link,/usr/lib/x86_64-linux-gnu`

apparently z's lib is fetched from system that isn't i386 which obviously is wrong.

**Comment by ebraminio** [comment]
Fixed i386 issue using forcefallback @khaledhosny, dataflow issue is still there, https://github.com/google/oss-fuzz/pull/4089/checks?check_run_id=869057472 okay let me comment that one

**Comment by khaledhosny** [comment]
I can’t make any sense of these build errors, sorry.

**Comment by ebraminio** [comment]
> I can’t make any sense of these build errors, sorry.

Oh, I just want to let you know it will download zlib dependency for the fuzzer. @inferno-chromium suggested to disable dataflow for now which is ok (however I wanted to make it work, just like harfbuzz)

**Comment by inferno-chromium** [comment]
Looks like everything is working, thanks for fixes

**Pull request merged**
