### PR TITLE
[Build fix] cups, gpsd, krb5, libmodbus, ntpsec, pupnp, unit

### PR DESCRIPTION
**Pull request by pkillarjun**
Hello oss-fuzz team,
As I already told @jonathanmetzman, That my GitHub account '0x34d' is flagged. So i will be using this one instead.

Sorry boys :)

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Hey do you still have the email you used in the past? Can you send me an email to confirm this PR is yours.
My address is metzman [at] google [dot] com

**Comment by pkillarjun** [comment]
> Hey do you still have the email you used in the past? Can you send me an email to confirm this PR is yours. My address is metzman [at] google [dot] com

Done.
Can you verify me on this PR, so vendors don't panic and ask who the f*** this guy is?

**Comment by pkillarjun** [comment]
Note for myself: I used [this](https://github.com/ntpsec/ntpsec/commit/3282d6a41519e6f85ed6364f4cb5d4bb04c5033d#diff-d7056b5bab5024d83def823b0d058e1a92154232bd6ecc0ef4f74032a032853a
) to fix the linker error of netsec.

**Comment by pkillarjun** [comment]
Don't merge;

**Comment by pkillarjun** [comment]
My old account is back @0x34d, but from now on, I will be using this one instead, due to email privacy and other things; it's just a little hurdle.

**Comment by oliverchang** [comment]
> My old account is back @0x34d, but from now on, I will be using this one instead, due to email privacy and other things; it's just a little hurdle.

Are you able to make a reply here using your old account so we can verify that you're the same person? Thanks!

**Comment by 0x34d** [comment]
> Are you able to make a reply here using your old account so we can verify that you're the same person? Thanks!

Hello;

**Pull request merged**
