### PR TITLE
[boost] add fuzzers for boost property tree parsers

### PR DESCRIPTION
**Pull request by pauldreik**

### CODE REVIEW

**Comment by pauldreik** [comment]
I signed it!

**Comment by inferno-chromium** [comment]
@kcc - looks like you integrated boost. do you have the github ids of the maintainers that can review this or you want to review it ?

**Comment by pauldreik** [comment]
The build fails [(link to logfile)](https://oss-fuzz-build-logs.storage.googleapis.com/log-26cd1061-cadd-474a-807f-ed03b5bcf540.txt), and I think the reason is that I missed to add the files to the COPY command in Dockerfile. 

The last line of Dockerfile should be changed from
`COPY build.sh boost_regex_fuzzer.cc $SRC/`
to
`COPY build.sh *.cc $SRC/`

Sorry about the mistake. Do you want me to make another pull request, or fix it yourself?

**Comment by kcc** [comment]
yes, please send a PR

**Comment by pauldreik** [comment]
Here is the PR: https://github.com/google/oss-fuzz/pull/1828

**Pull request merged**
