### PR TITLE
MapServer: initial integration

### PR DESCRIPTION
**Pull request by 0x34d**
Hello, MapServer team @sdlime @MaxKellermann @geographika @jmckenna
Do you approve this commit For MapServer Fuzzing in oss-fuzz infrastructure?

Hello, OSS-Fuzz Team.
I'm not using the inbuild fuzzer of MapServer, Application uses predefined flags.

Signed-off-by: 0x34d <ajsinghyadav00@gmail.com>

### CODE REVIEW

**Comment by sdlime** [comment]
Seems like this integration is jumping the gun: Max still had comments on the MapServer repo pull request. @rouault, did you get to this point back when you were investigating using dynamic linking?

**Comment by rouault** [comment]
@sdlime See https://github.com/MapServer/MapServer/pull/6594#issuecomment-1220733580

@0x34d Please add me too in the vendor_ccs list: even.rouault@spatialys.com

**Comment by 0x34d** [comment]
Greate This Project has more than 120+ dependencies. https://github.com/google/oss-fuzz/issues/8304

**Comment by 0x34d** [comment]
Not Working This way.

**Comment by 0x34d** [comment]
@jonathanmetzman check this out.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by geographika** [comment]
@0x34d - could you change my email in https://github.com/google/oss-fuzz/blob/master/projects/mapserver/project.yaml to geographika@gmail.com - I can't log in to see the alerts with sethg@geographika.co.uk (it is a secondary GitHub email).

**Comment by 0x34d** [comment]
> @0x34d For your information during today Mapserver project steering committe meeting, we have decided that we would move mapfuzzer.c to mapserver repository. We'll also modify Mapserver build logic so that it generates binaries that can take as input a reproducer file generated by ossfuzz and run it through the LLVMFuzzerTestOneInput() function of each fuzzer, so it can be reproduced against a mapserver development build (which makes it easier to analyze and fix issues) rather than going through https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally . I'll take care of those changes

I appreciate your efforts. 
If any help is needed from my side, please ping me. 
Regards, Arjun.

**Comment by sdlime** [comment]
@0x34d - can max kellermann be removed from the cc: list? He's not a formal project member and has indicated he doesn't want to see all the messaging.

**Comment by sdlime** [comment]
> @0x34d - can max kellermann be removed from the cc: list? He's not a formal project member and has indicated he doesn't want to see all the messaging.

I created a pull request against google:master for that change.

**Pull request merged**
