### PR TITLE
GSoC Adding retriever into OSS Fuzz

### PR DESCRIPTION
**Pull request by PatriceJada**
Main Maintainer @henrykironde

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Do you have a link to the GSoC project you are working on.
Also, could we try to integrate the projects one at a time? It's a lot to integrate ~10 projects.

**Comment by PatriceJada** [comment]
@jonathanmetzman This is the link to the GSoC page https://github.com/numfocus/gsoc/wiki/GSoC-2024-GOSST and this is the issue https://github.com/numfocus/gsoc/issues/470

**Comment by jonathanmetzman** [comment]
Does the main maintainer approve?

**Comment by henrykironde** [comment]
@jonathanmetzman , I approve.

**Comment by PatriceJada** [comment]
> How about you keep open these PRs and the first projects you make progress on, I'll merge those PRs.

@jonathanmetzman Correct me if I'm wrong but my understanding was that for the project to be accepted we need to follow these steps https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/. Then once the project is merged we move to these steps https://google.github.io/oss-fuzz/getting-started/new-project-guide/

**Comment by jonathanmetzman** [comment]
> > How about you keep open these PRs and the first projects you make progress on, I'll merge those PRs.
> 
> @jonathanmetzman Correct me if I'm wrong but my understanding was that for the project to be accepted we need to follow these steps https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/. Then once the project is merged we move to these steps https://google.github.io/oss-fuzz/getting-started/new-project-guide/

That is the correct procedure, but to be honest, no one else has tried to integrate ~10 projects at once.
For each project someone tries to add to oss-fuzz, we need to discuss whether to accept it.
This is potentially a lot of work for us. I'd rather you integrate projects one at a time so we don't spend time discussing project integrations that don't get completed.
Also, doing integrations one at a time would make it easier to incorporate feedback. For example, I think the "MSAN" option doesn't make sense here, and you should also say why the project is important and/or critical infra.

**Comment by DonggeLiu** [comment]
> > > How about you keep open these PRs and the first projects you make progress on, I'll merge those PRs.
> > 
> > 
> > @jonathanmetzman Correct me if I'm wrong but my understanding was that for the project to be accepted we need to follow these steps https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/. Then once the project is merged we move to these steps https://google.github.io/oss-fuzz/getting-started/new-project-guide/
> 
> That is the correct procedure, but to be honest, no one else has tried to integrate ~10 projects at once. For each project someone tries to add to oss-fuzz, we need to discuss whether to accept it. This is potentially a lot of work for us. I'd rather you integrate projects one at a time so we don't spend time discussing project integrations that don't get completed. Also, doing integrations one at a time would make it easier to incorporate feedback. For example, I think the "MSAN" option doesn't make sense here, and you should also say why the project is important and/or critical infra.

Rejecting the following PRs (including this PR) accordingly:
* https://github.com/google/oss-fuzz/pull/12053
* https://github.com/google/oss-fuzz/pull/12054
* https://github.com/google/oss-fuzz/pull/12055
* https://github.com/google/oss-fuzz/pull/12056
* https://github.com/google/oss-fuzz/pull/12057
* https://github.com/google/oss-fuzz/pull/12058
* https://github.com/google/oss-fuzz/pull/12059
* https://github.com/google/oss-fuzz/pull/12060
* https://github.com/google/oss-fuzz/pull/12062
* https://github.com/google/oss-fuzz/pull/12063
* https://github.com/google/oss-fuzz/pull/12064
* https://github.com/google/oss-fuzz/pull/12065
* https://github.com/google/oss-fuzz/pull/12066
* https://github.com/google/oss-fuzz/pull/12067

**Pull request closed without merging**
