### PR TITLE
Add libplist

### PR DESCRIPTION
**Pull request by nikias**
Please add libplist to oss-fuzz!
My github email is not associated with any google account.

### CODE REVIEW

**Comment by nikias** [comment]
I signed it!

**Comment by Dor1s** [comment]
Hi @nikias! Would you mind sharing who are customers of `libplist` project? Do you know big projects relying on it?

**Comment by nikias** [comment]
Of course, libimobiledevice depends on it, to allow communication between iOS devices and host. See http://www.libimobiledevice.org and the corresponding projects on github: https://github.com/libimobiledevice. It's part of almost every Linux distribution by now.

**Comment by nikias** [comment]
Thanks for merging! Will follow up with fuzz targets soon.

**Pull request merged**
