### PR TITLE
Add Wireshark

### PR DESCRIPTION
**Pull request by moshekaplan**

### CODE REVIEW

**Comment by moshekaplan** [comment]
I signed it!

**Comment by oliverchang** [comment]
Thanks for the request. Are you and the people included in project.yaml Wireshark developers?

**Comment by moshekaplan** [comment]
security@wireshark.org is the distribution list for security issues.

David and I are not the core maintainers, but I have worked with the Wireshark team in the past to fix vulnerabilities and add new features. David will be helping me generate Wireshark's fuzzing corpus.

**Comment by mikea** [comment]
Moshe,

We are definitely excited to see Wireshark here. Sorry to be a bit paranoid, but could you help us to establish some chain of trust to maintainers? Simply showing up here and vouching for this PR would work.

**Comment by Lekensteyn** [comment]
Hi,

@moshekaplan has recently added some features, see https://code.wireshark.org/review/#/q/owner:%22Moshe+Kaplan+%253Cme%2540moshekaplan.com%253E%22

I'd like to discuss this with other -core developers, can you hold off this PR for a moment? Ping @alagoutte @crondaemon (see also https://wiki.wireshark.org/Developers).

Kind regards,
Peter Wu

**Comment by inferno-chromium** [comment]
@Lekensteyn - Just a fyi, for primary contact we would prefer to be an actual person than a mailing list. auto-cc list can be a mailing list. +1 on the excitement to have Wireshark in OSS-Fuzz.

**Comment by Manouchehri** [comment]
Just to clarify, will I have full access to the results? If not, makes more
sense for me to continue this as a private project.

On Dec 11, 2016 21:32, "inferno-chromium" <notifications@github.com> wrote:

@Lekensteyn <https://github.com/Lekensteyn> - Just a fyi, for primary
contact we would prefer to be an actual person than a mailing list. auto-cc
list can be a mailing list. +1 on the excitement to have Wireshark in
OSS-Fuzz.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/google/oss-fuzz/pull/161#issuecomment-266330276>, or mute
the thread

**Comment by oliverchang** [comment]
Yes, if the Wireshark code developers approve, and you are in the CC list, you will have access to the results.

**Comment by crondaemon** [comment]
Then I think that having Gerald Combs (Wireshark creator) as primary contact would be the best. We are discussing which solution (an existing mailing list or a brand new one) would fit best as CC contact. @Manouchehri and @moshekaplan will be part of this list or be added as individuals, no one is making objection in having them in the circle (so far). Please hold on until the discussion between cores ends, and we will update you.

**Comment by Lekensteyn** [comment]
Congratulations on reaching 1k commits oss-fuzz!

@oliverchang From the documentation (FAQ, New project guide) it is not clear how access control works. Can we (as a project) grant arbitrary accounts access or do they have to be present in the Cc list?

One possible outcome is that we openi all os-fuzz reports to the public (considering it part of the normal fuzzing activity that is done, these would automatically open a public bug on issues). Is that possible and/or recommended?

**Comment by oliverchang** [comment]
Thanks!

We require emails (Google accounts) to be present in the CC list in project.yaml for complete access. There two places where you have to login to access things: our [issue tracker](https://bugs.chromium.org/p/oss-fuzz/issues/list), and [ClusterFuzz](https://github.com/google/oss-fuzz/blob/master/docs/clusterfuzz.md) to access fuzzing statistics, detailed crash information, as well as to download reproducers. Mailing lists won't work beyond getting an email notification on new bugs filed in the issue tracker.

We don't recommend opening all reports to the public by default because of the potential impact of these bugs. By default we apply access restrictions for 90 days. If the bug is fixed earlier, we remove the restrictions after 7 days. Keeping issues private was the reason we decided to go with monorail for issue tracking, as opposed to some thing like github issues, which does not support private issues.

**Comment by crondaemon** [comment]
Then how would be the workflow if we add Gerald as primary and a ML as CC? We would get notified in the ML, but how would we track the issue down?

**Comment by oliverchang** [comment]
I think there was some miscommunication here -- ML can be one of the CCs, but you would still need to add individual accounts for full access.

**Comment by crondaemon** [comment]
Thanks @oliverchang, it was exactly the clarification I was looking for.

**Comment by Manouchehri** [comment]
@crondaemon Submitted a sample report of a bug I found a few hours ago, surprised how quick it was to find one. https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=13246 There's a lot of these, seems like a good fit for OSS-Fuzz.

**Comment by crondaemon** [comment]
@oliverchang can you please clarify how individual people can request access to the bugs? Is the primary contact involved in this process or is it totally your business? Thanks!

**Comment by inferno-chromium** [comment]
@crondaemon - if you add these people to the auto_cc list in yaml file, then bugs are auto-filed and both primary contact and auto_cc list people are cced. Or, if you want to add a person to a particular bug, then either primary contact or any of those auto cc folks can add more people to cc list.

**Comment by Manouchehri** [comment]
Both I and @moshekaplan have already gotten some work done on this, would be great to hear if there's still interest.

screen shot 2016-12-19 at 4 24 39

**Comment by crondaemon** [comment]
There is, at least my side. I'll try to push a little bit more on the core ML, since I don't want you to loose interest in that.

**Comment by Manouchehri** [comment]
Sorry, which list? Can't find it.

**Comment by Lekensteyn** [comment]
Update: we are ready to go!

@moshekaplan Can you replace the primary contact by gerald@wireshark.org (@geraldcombs)?

Additionally, can you add me to Cc: peter@lekensteyn.nl
@crondaemon @alagoutte @rknall also showed interest, what email addresses should be added for you?

**Comment by inferno-chromium** [comment]
LGTM, merged.

**Comment by crondaemon** [comment]
To be in the CC list, are the users required to sign the CLA?

**Comment by inferno-chromium** [comment]
@crondaemon - not for this, but if you plan to contribute new code for OSS-Fuzz, like as part of Wireshark, then you need to sign CLA that time.

**Comment by crondaemon** [comment]
Ok, thanks. Are new emails added by PR as well?

**Comment by inferno-chromium** [comment]
@crondaemon - check out https://github.com/google/oss-fuzz/blob/master/projects/wireshark/project.yaml. if anything is missing, just submit a pull request.

**Pull request merged**
