### PR TITLE
Enable UBSan without vptr for ffmpeg.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by kcc** [comment]
LGTM, and thanks a lot, please merge once tested locally. 
I've just remembered that there are 100+ unique int overflows in the existing corpus, 
so we'll spam monorail a bit.

**Comment by inferno-chromium** [comment]
It fails to link with -lFuzzingEngine since this does not override CFLAGS or CXXFLAGS in compile_libfuzzer. I tried to add "FFMPEG_FUZZERS_COMMON_FLAGS="-lFuzzingEngine -fno-sanitize=vptr" but still fails.

/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../libFuzzingEngine.a(FuzzerSHA1.o): In function `std::__1::basic_stringbuf<char, std::__1::char_traits<char>, std::__1::allocator<char> >::str() const':
/usr/local/bin/../include/c++/v1/sstream:448: undefined reference to `__ubsan_vptr_type_cache'

**Comment by kcc** [comment]
yea, right, if we disable vptr for the target, we also need to disable it for libfuzzer. grrr. 
Will look at this next week (or will wait for @mikea...)

**Comment by kcc** [comment]
it may help to also add -fno-sanitize=vptr to libfuzzer build flags.
Can't check now -- base-builder fails to build, something is broken with debian packages. 
```
E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/main/b/bind9/libisc-export160_9.10.3.dfsg.P4-8ubuntu1.4_amd64.deb  404  Not Found [IP: 91.189.88.162 80]
```

**Pull request closed without merging**
