### PR TITLE
Adds project glog

### PR DESCRIPTION
**Pull request by catenacyber**
@sergiud are you interested in having glog running on oss-fuzz ?

see also https://github.com/google/glog/issues/816 cc @autofuzzoss

I also quickly find a timeout with input `_ZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZZ_`

### CODE REVIEW

**Comment by sergiud** [comment]
Fuzz testing is certainly useful, thanks. @drigz might want to take a look as well since the setup seems to Bazel based.

**Comment by catenacyber** [comment]
Do you prefer Bazel or cmake ?
There is a bit of a hack to get bazel to work...

**Comment by sergiud** [comment]
Personally, I would prefer using CMake especially because we use it to build multiple combinations of the project (in different configurations) on the CI that should all be fuzz tested. I guess using a single build system is also sufficient, no?

**Comment by catenacyber** [comment]
Okay, so there is one PR to glog https://github.com/google/glog/pull/878 and this PR to oss-fuzz (which needs to be modified to use glog main repo once the PR for it is merged)

**Comment by Alan32Liu** [comment]
Seems to alright on the OSS-Fuzz side, let's wait for https://github.com/google/glog/pull/878.

**Comment by catenacyber** [comment]
@Alan32Liu upstream PR was merged, this one is now ready for merge

**Review by Alan32Liu — APPROVED** [review]

**Pull request merged**
