### PR TITLE
Add maintainer for libsass.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@mgreter @xzyfer, can you please provide your email contacts to add here. This will help to send security and stability bugs found by OSS-Fuzz your way. Please read about our initiative here - https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html

**Comment by inferno-chromium** [comment]
@nex3 - do you want to be added as maintainer contact here as well ?

**Comment by nex3** [comment]
No thanks! I don't work on LibSass.

**Comment by xzyfer** [comment]
You can use mine. It's my GitHub handle at gmail dot com.

**Comment by inferno-chromium** [comment]
Thanks a lot @xzyfer

**Pull request merged**
