### PR TITLE
Adds project mysql

### PR DESCRIPTION
**Pull request by catenacyber**
Follows #2647 and #2593 

Some changes from the code review...

Meanwhile, some bugs appear to have been fixed :
https://github.com/mysql/mysql-server/commit/ee94b90e1feee88a9109a403593c8c2a4de05eb4#diff-177e3b8c195a010740987c9ae1754b8aR735

### CODE REVIEW

**Comment by catenacyber** [comment]
CI failure is due to compile timeout (takes 3 hours on my laptop)

**Comment by catenacyber** [comment]
Sorry, I have been doing the PR too fast.
mysqld fuzz target requires a change, cf https://github.com/catenacyber/oss-fuzz/commit/a4134a8d78c87bf30e7fac9f1f30319f90c01c73
And testing is still going on...

**Comment by inferno-chromium** [comment]
@catenacyber - build is broken, can you please investigate, see https://oss-fuzz-build-logs.storage.googleapis.com/log-cfc87ce5-5c14-46db-8826-90af83881968.txt

**Comment by catenacyber** [comment]
Version 8.0.17 for mysql needs more rework for the fuzz targets. Sorry I missed it. I will do it but in some weeks...

**Pull request merged**
