### PR TITLE
[django-fuzzers]

### PR DESCRIPTION
**Pull request by guidovranken**
Initial OK from devs here: https://groups.google.com/d/msg/django-developers/-WweB07YiVQ/uCu23CnZCQAJ

Awaiting further response from devs and resolution of some (security) bugs this fuzzer found. Do not merge yet (main fuzzing repository is still private).

### CODE REVIEW

**Comment by guidovranken** [comment]
@kcc @Dor1s I assume Django fuzzers will be accepted into OSS-Fuzz?

**Comment by Dor1s** [comment]
> I assume Django fuzzers will be accepted into OSS-Fuzz?

Yes!

**Comment by guidovranken** [comment]
They are working to resolve the bugs and issue security advisories. I don't think it will be too long until we can merge.

**Comment by guidovranken** [comment]
Release on August 1: https://github.com/django/django/commit/f13147c8de725eed7038941758469aeb9bd66503
We can merge that day.

**Comment by guidovranken** [comment]
@Dor1s

This found 3 CVE's in Django so far https://github.com/django/django/blob/master/docs/releases/2.2.4.txt

Those persons in the auto_ccs are aware of this integration.

django-fuzzers repo made public: https://github.com/guidovranken/django-fuzzers

We can now merge.

**Comment by Dor1s** [comment]
Nice, thanks for the update, @guidovranken ! What's up with the build failures?

**Comment by guidovranken** [comment]
@Dor1s 

I think I've fixed it. Can you run Travis again?

**Comment by inferno-chromium** [comment]
Done, retriggered Travis.

**Comment by guidovranken** [comment]
OK, so it's just the AFL build failing now, apparently due to a 1 second time out on one of the inputs.

However I get an average runs/second of about 170 on my system (with libFuzzer).

I think it might be the Travis server being slow (or overloaded)?

Apart from that, a single input in the corpus that takes 1 second to run is not necessarily a problem in this case, because the fuzzer speed is not representative of a production Python environment (the fuzzer is slowed down by instrumentation and sanitizers).

**Comment by Dor1s** [comment]
> OK, so it's just the AFL build failing now, apparently due to a 1 second time out on one of the inputs.

@jonathanmetzman will it be a problem when running on ClusterFuzz?

Otherwise, we should be good to merge this.

**Comment by jonathanmetzman** [comment]
> > OK, so it's just the AFL build failing now, apparently due to a 1 second time out on one of the inputs.
> 
> @jonathanmetzman will it be a problem when running on ClusterFuzz?
> 
> Otherwise, we should be good to merge this.

+1, if it becomes a problem on CF or in jenkins, we can disable AFL. No need to block this.

**Comment by jonathanmetzman** [comment]
[Looks like build is failing because of AFL](https://oss-fuzz-build-logs.storage.googleapis.com/log-d384f6b2-dc09-4271-b026-40d5e8e57dee.txt). You should probably disable AFL

**Pull request merged**
