### PR TITLE
Disable golang snappy project

### PR DESCRIPTION
**Pull request by catenacyber**
As requested here https://github.com/google/oss-fuzz/issues/5442#issuecomment-850925681
cc @nigeltao

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
Sad we have to disable this.

**Comment by inferno-chromium** [comment]
> > Sad we have to disable this.
> 
> @jonathanmetzman do you know who (in the golang team ?) may understand and fix the bug described in #5442 ?

Is this only happening on snappy or anything else as well.

**Comment by catenacyber** [comment]
All the golang projects (since go 1.16)
Seemed to happen before (with go 1.15) on some projects (grpc-go)
One recent example https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34648

**Comment by inferno-chromium** [comment]
@mdempsky - any thoughts on this.
@catenacyber - do you have ways to reproduce this, can you share reproduction steps?

**Comment by catenacyber** [comment]
Alas no I cannot reproduce it...

**Pull request merged**
