### PR TITLE
[clickhouse] Move submodule sync to build script

### PR DESCRIPTION
**Pull request by nikitamikhaylov**
I just try to enable CIFuzz here https://github.com/ClickHouse/ClickHouse/pull/32005 and noticed that it doesn't allow the recursive cloning

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
I think it's related to https://github.com/google/oss-fuzz/issues/6755

**Comment by nikitamikhaylov** [comment]
> I think it's related to #6755

Maybe, I found this PR and decided to do the same https://github.com/google/oss-fuzz/pull/6923

**Comment by nikitamikhaylov** [comment]
@DavidKorczynski Maybe merge it without waiting so I can test it in out CI? I tested it locally, everything works fine, but your checks are stuck...

**Comment by jonathanmetzman** [comment]
Could you do me a favor and not merge this, but wait for https://github.com/google/oss-fuzz/pull/6941 to land? Should land tonight.

**Comment by nikitamikhaylov** [comment]
Ahh, of course, this will be the best solution.

**Pull request closed without merging**
