### PR TITLE
Golang coverage summary updated to version 2.0.1

### PR DESCRIPTION
**Pull request by catenacyber**
cf #5337 cc @jonathanmetzman 

On gonids sample, I get
```
{"data":[{"totals":{"functions":{"count":105,"covered":52,"notcovered":53,"percent":49.523809523809526},"lines":{"count":942,"covered":578,"notcovered":364,"percent":61.3588110403397},"regions":{"count":670,"covered":388,"notcovered":282,"percent":57.91044776119403},"instantiations":{"count":0,"covered":0,"notcovered":0,"percent":0},"branches":{"count":0,"covered":0,"notcovered":0,"percent":0}},"files":[{"summary":{"functions":{"count":1,"covered":1,"notcovered":0,"percent":100},"lines":{"count":23,"covered":11,"notcovered":12,"percent":47.82608695652174},"regions":{"count":13,"covered":7,"notcovered":6,"percent":53.84615384615385},"instantiations":{"count":0,"covered":0,"notcovered":0,"percent":0},"branches":{"count":0,"covered":0,"notcovered":0,"percent":0}},"filename":"github.com/google/gonids/fuzz.go"},{"summary":{"functions":{"count":31,"covered":28,"notcovered":3,"percent":90.3225806451613},"lines":{"count":172,"covered":159,"notcovered":13,"percent":92.44186046511628},"regions":{"count":110,"covered":100,"notcovered":10,"percent":90.9090909090909},"instantiations":{"count":0,"covered":0,"notcovered":0,"percent":0},"branches":{"count":0,"covered":0,"notcovered":0,"percent":0}},"filename":"github.com/google/gonids/lex.go"},{"summary":{"functions":{"count":6,"covered":1,"notcovered":5,"percent":16.666666666666668},"lines":{"count":45,"covered":8,"notcovered":37,"percent":17.77777777777778},"regions":{"count":40,"covered":8,"notcovered":32,"percent":20},"instantiations":{"count":0,"covered":0,"notcovered":0,"percent":0},"branches":{"count":0,"covered":0,"notcovered":0,"percent":0}},"filename":"github.com/google/gonids/linters.go"},{"summary":{"functions":{"count":5,"covered":1,"notcovered":4,"percent":20},"lines":{"count":42,"covered":12,"notcovered":30,"percent":28.571428571428573},"regions":{"count":31,"covered":10,"notcovered":21,"percent":32.25806451612903},"instantiations":{"count":0,"covered":0,"notcovered":0,"percent":0},"branches":{"count":0,"covered":0,"notcovered":0,"percent":0}},"filename":"github.com/google/gonids/optimize.go"},{"summary":{"functions":{"count":21,"covered":19,"notcovered":2,"percent":90.47619047619048},"lines":{"count":387,"covered":338,"notcovered":49,"percent":87.33850129198966},"regions":{"count":264,"covered":223,"notcovered":41,"percent":84.46969696969697},"instantiations":{"count":0,"covered":0,"notcovered":0,"percent":0},"branches":{"count":0,"covered":0,"notcovered":0,"percent":0}},"filename":"github.com/google/gonids/parser.go"},{"summary":{"functions":{"count":41,"covered":2,"notcovered":39,"percent":4.878048780487805},"lines":{"count":273,"covered":50,"notcovered":223,"percent":18.315018315018314},"regions":{"count":212,"covered":40,"notcovered":172,"percent":18.867924528301888},"instantiations":{"count":0,"covered":0,"notcovered":0,"percent":0},"branches":{"count":0,"covered":0,"notcovered":0,"percent":0}},"filename":"github.com/google/gonids/rule.go"}]}],"type":"oss-fuzz.go.coverage.json.export","version":"2.0.1"}
```

Does it look good to you ?

### CODE REVIEW

**Comment by catenacyber** [comment]
It does both summary and per-target json cf `git grep gocovsum`

**Comment by jonathanmetzman** [comment]
I can't really test this directly without the per-target data. We don't use the summary data that (I think) you gave me.
Let's merge this for now and then check if it works in production.

**Comment by jonathanmetzman** [comment]
If you want me to test directly can you give me the per target data?

**Comment by catenacyber** [comment]
> I can't really test this directly without the per-target data. We don't use the summary data that (I think) you gave me.

This is also the per-target data (there is only one target in this case)

**Pull request merged**
