### PR TITLE
afl++ commit id update

### PR DESCRIPTION
**Pull request by vanhauser-thc**
among other fixes, this changes the -t + parameter to autodetect the timeout value to up to the specified value, depending on the slowest seed in the initial corpus.

maybe it is time now to switch to the stable branch of afl++ so the commit id doesnt need to be updated anymore?

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
Do some tests run against a stable branch. The problem that worries me if we get a broken afl++ version one night, it can close hundreds of bugs the next day. If there can be a good test in CI that builds a sample project, run fuzzers in it and makes sure it does not crash, that would be ideal to have.

**Comment by vanhauser-thc** [comment]
> Do some tests run against a stable branch. The problem that worries me if we get a broken afl++ version one night, it can close hundreds of bugs the next day. If there can be a good test in CI that builds a sample project, run fuzzers in it and makes sure it does not crash, that would be ideal to have.

We have a test setup that runs on every commit where nearly all features are tested.
plus we only push to stable when we have a stable state, which is about every 2-4 weeks and in the push too the CI tests run.
So IMHO that is very unlikely that something would break.
but its up to you :)
the tests can be started with "make tests" if you want to try them out.

**Comment by inferno-chromium** [comment]
> > Do some tests run against a stable branch. The problem that worries me if we get a broken afl++ version one night, it can close hundreds of bugs the next day. If there can be a good test in CI that builds a sample project, run fuzzers in it and makes sure it does not crash, that would be ideal to have.
> 
> We have a test setup that runs on every commit where nearly all features are tested.
> plus we only push to stable when we have a stable state, which is about every 2-4 weeks and in the push too the CI tests run.
> So IMHO that is very unlikely that something would break.
> but its up to you :)
> the tests can be started with "make tests" if you want to try them out.

ah didn't know, then everything is fine, i should have looked more closely. Where are those tests run, can you share the link. Probably me, @jonathanmetzman should note it down somewhere.

**Comment by vanhauser-thc** [comment]
https://github.com/AFLplusplus/AFLplusplus/runs/2002781937
open the "run tests" folder from that CI run and scroll down.

**Comment by vanhauser-thc** [comment]
this does not protect against llvm 13+ changes that break things though, but that is something that should be done in oss-fuzz when updating llvm.

**Comment by inferno-chromium** [comment]
> this does not protect against llvm 13+ changes that break things though, but that is something that should be done in oss-fuzz when updating llvm.

@jonathanmetzman - do you think if we should run these tests when compiling afl++ in oss-fuzz. it protects us against unintended breakage from latest clang. 
@vanhauser-thc - how long these tests take, can we run any basic tests that take like <30-60sec

**Comment by vanhauser-thc** [comment]
```
time make tests
[...]
[-] not all test cases were executed
[+] all tests were successful :-)

real	1m30,034s
user	1m2,839s
sys	0m30,784s
```
Note that is runs afl-fuzz several times and checks if it is able to solve paths, etc. - in bad random circumstances the dices may not roll as they should and result in a test fail - but so is fuzzing :) ... a very rare event.

**Pull request merged**
