### PR TITLE
Add stub project.yaml for Samba

### PR DESCRIPTION
**Pull request by douglasbagnall**
We would like to add Samba to oss-fuzz.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@douglasbagnall - we would love to have Samba integrated in OSS-Fuzz!

**Comment by abartlet** [comment]
When @douglasbagnall next updates this, he will include me as abartlet+google@catalyst.net.nz as a CC.  This comment may assist connecting my samba.org identity seen in the commits with that address. 

We have this almost ready to go, when we submit we will have 128 fuzzers and a corpus generated from the traffic seen in our 'make test'!

We just need to get the branch into our master and the CLA signed.

**Comment by inferno-chromium** [comment]
@abartlet - that is exciting to know you already have the fuzzers written.
@douglasbagnall - can you please sign the cla and then we will merge.

**Comment by jonathanmetzman** [comment]
Just add a build.sh script so we can start building your targets.

**Comment by abartlet** [comment]
If we got things right, then that should all be done.

We want to maintain the build.sh part on the Samba side, so we did
this:

https://gitlab.com/samba-team/samba/tree/master/lib/fuzzing/oss-fuzz

The build_image.sh called from the Dockerfile copies in build.sh, which
is a stub which calls the in-tree build_samba.sh.  Is that OK?

**Comment by abartlet** [comment]
I see the problem.

It should be 

WORKDIR samba

not 

WORKDIR /home/samba

**Comment by jonathanmetzman** [comment]
> If we got things right, then that should all be done. We want to maintain the build.sh part on the Samba side, so we did this: https://gitlab.com/samba-team/samba/tree/master/lib/fuzzing/oss-fuzz The build_image.sh called from the Dockerfile copies in build.sh, which is a stub which calls the in-tree build_samba.sh. Is that OK?

Ah I think that should be fine.

> I see the problem. It should be WORKDIR samba not WORKDIR /home/samba

I didn't notice that, but that will be a problem.

**Comment by abartlet** [comment]
Thanks all!  We are up and fuzzing!

We have filled in the help url with clues on how to work with oss-fuzz for Samba developers: https://wiki.samba.org/index.php/Fuzzing

**Comment by inferno-chromium** [comment]
Very nice work @abartlet , thanks for your integration. let us know if you have any questions or any way we can improve your fuzzing workflow.

**Pull request merged**
