### PR TITLE
[brpc] initial integration

### PR DESCRIPTION
**Pull request by 0x34d**
Hello,
@zyearn @wwbmmm @serverglen @tanzhongyi003 

thought on integration of brpc.

Signed-off-by: 0x34d <ajsinghyadav00@gmail.com>

### CODE REVIEW

**Comment by zyearn** [comment]
Hi, Arjun

Could you give us some context on integration of brpc?

**Comment by 0x34d** [comment]
> Could you give us some context on integration of brpc?

To find memory corruption related bugs in JSON, HTTP parser of `brpc`.

can you Review [Fuzz_http.cpp](https://github.com/google/oss-fuzz/pull/8887/files#diff-d55769d9c18ca004b8847f267be568a4bf330c38a5f990052acbdfd2e10e0064) [Fuzz_json.cpp](https://github.com/google/oss-fuzz/pull/8887/files#diff-b07121ae48dccda8bffc2a216bcf31f938da9cea0c781927debfdeb327a20a27) files for harness.

**Comment by 0x34d** [comment]
@zyearn call for merge?
if you can fix the bugs reported by oss-fuzz.

**Comment by zyearn** [comment]
Hi, Arjun

1) Is there anything we should do other than fixing the bugs reported by oss-fuzz?
2) Where is the report?

**Comment by 0x34d** [comment]
> 1. Is there anything we should do other than fixing the bugs reported by oss-fuzz?

Nothing else.

> 2. Where is the report?

You will receive it after the oss-fuzz team merges this PR.

@Alan32Liu @jonathanmetzman can you merge?

**Review by Alan32Liu — APPROVED** [review]

**Pull request merged**
