### PR TITLE
Support named experiments

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Named experiments will be tagged: `branch-$EXPERIMENT_NAME`

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
re: https://buganizer.corp.google.com/issues/291852633

**Review by Alan32Liu — COMMENTED** [review]
LGTM

**Review by oliverchang — COMMENTED** [review]
Thanks! How does `branch` get propagated here?

**Comment by oliverchang** [comment]
> Thanks! How does `branch` get propagated here?

Oh, I see this is answered in https://github.com/google/oss-fuzz/pull/10725/files :)

**Pull request merged**
