### PR TITLE
Adds project music player daemon

### PR DESCRIPTION
**Pull request by catenacyber**
cc @MaxKellermann
Would you like continuous fuzzing for Music Player Daemon ?
This PR enables it on oss-fuzz with your existing CUE fuzz target.

### CODE REVIEW

**Comment by MaxKellermann** [comment]
Great idea, thanks! Obviously, we need more fuzzers. But your work is a good way to get started with oss-fuzz.

**Comment by catenacyber** [comment]
> Great idea, thanks! Obviously, we need more fuzzers. But your work is a good way to get started with oss-fuzz.

This should be generic so that new fuzzers (added to the test/fuzzer/ directory) should be automatically taken into account by oss-fuzz

Trying a little patch, so that meson sets only one sanitizer at a time (oss-fuzz CI does not like `-fsanitize=address,undefined`)

**Comment by catenacyber** [comment]
@MaxKellermann what do you think about patch.diff ?
Only setting sanitizers with the `fuzzer` option if they are not already defined by the generic meson `b_sanitize` option ?

**Comment by MaxKellermann** [comment]
> Only setting sanitizers with the `fuzzer` option if they are not already defined by the generic meson `b_sanitize` option ?

Right now, MPD's `meson.build` manually sets `-fsanitize=fuzzer,address,undefined`, but using `b_sanitize` would probably be better. I just think Meson doesn't support `b_sanitize=fuzzer`.

**Comment by inferno-chromium** [comment]
Where is this project used and can you expand on customers (and how it is critical to OSS ecosystem)?

**Comment by catenacyber** [comment]
Music player daemon is a server-side application for playing music, and there are a lot of clients (client as in TCP) which interact with it 
cf https://www.musicpd.org/clients/

**Comment by inferno-chromium** [comment]
> Music player daemon is a server-side application for playing music, and there are a lot of clients (client as in TCP) which interact with it
> cf https://www.musicpd.org/clients/

I dont see anything interesting with regards to those clients, anything super popular or in prominent use by oss community?

**Pull request closed without merging**
