### PR TITLE
base-runner: bump python to 3.10

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Fixes: https://github.com/google/oss-fuzz/issues/11419

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
> I guess an alternative would be to bump the base image to Ubuntu 22.04, similar to #6305 . However, that may be more of a breaking change, so maybe it is less painful by bumping to 24.04 in one go, in the future.

I think this would probably be preferred -- it would be nice to not fall to far behind the latest distro. But I'm not sure about the impact on all the projects.

**Comment by jonathanmetzman** [comment]
It will probably be a year before we update Ubuntu image

**Comment by DaveLak** [comment]
@DavidKorczynski I took a slightly different approach at this in #12027.

Would you please take a look and let me know what you think whenever you get a chance?

 Thanks!

**Comment by radarhere** [comment]
#12027 has been merged instead.

**Pull request closed without merging**
