### PR TITLE
[muduo] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
Initial integration of [muduo](https://github.com/chenshuo/muduo).

About Muduo usage:

- Muduo is deployed in production to serve hundreds of millions of daily connections (https://github.com/chenshuo/muduo/pull/199#issue-71736961)
- Is considered a competitor to evpp - a project that is used to handle 1000+ billions networking communications every day in production (https://github.com/Qihoo360/evpp#benchmark)
------------------------------------------------------------
@chenshuo Are you interested in fuzzing muduo?
This PR adds sets up continuous fuzzing through OSS-fuzz. To complete the PR a maintainers email address is needed for bug reports.

### CODE REVIEW

**Comment by chenshuo** [comment]
Hi Adam,

Thank you for setting up fuzzer for muduo.  My email address is chenshuo@chenshuo.com .

Regards,
Shuo Chen

**Comment by AdamKorcz** [comment]
@inferno-chromium @oliverchang @jonathanmetzman @asraa Ready for review.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
> > What are some important users of muduo?
> 
> @jonathanmetzman See the updated first message in this pr.

Could you be more specific about this please?

**Comment by chenshuo** [comment]
Muduo is a popular C++ network library in Chinese community. There's a book written in Chinese describing how to use and (re-)implement it http://chenshuo.com/book/, thie book has sold 28,000+ copies.

AFAIK, many junior programmers and new grads in China study Muduo as their first non-trivial C++ project, learning networking, multithreading and modern C++ from it, sometimes re-write in their own ways, occasionally list "Deep understanding of Muduo" on their resumes. You can tell its popularity from the number of stars (9.2k+) and forks (4.2k+) of https://github.com/chenshuo/muduo . Someone describes Muduo as a modern version of ACE, whether it's compliment or complaint :-)

Having said that, Muduo is more like an educational project to show some good practices of C++ network programming in multi-core era. I've heard that some Chinese companies use it internally, but no major open-source project depends on it.

I think it's good to run fuzzer on Muduo to catch any errors and make it more robust, the errors found will also be informative on how to write good C++ code by avoiding such common or subtle errors.

Thanks,
Shuo Chen

**Comment by AdamKorcz** [comment]
> Muduo is deployed in production to serve hundreds of millions of daily connections (chenshuo/muduo#199 (comment))

Muduo is also being used in production.

**Pull request merged**
