### PR TITLE
RawSpeed project change

### PR DESCRIPTION
**Pull request by LebedevRI**
Specify one cmake option, in hope that it might magically fix strange Ill crashes, which are not reproducible locally.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2816

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@Dor1s - please check results later and update the bug if the issue is resolved.

**Comment by Dor1s** [comment]
Thanks Roman, it looks fixed now! There is one more top crasher: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=2463

That one happens not so often, but worth to be fixed as well :)

**Comment by LebedevRI** [comment]
@Dor1s 
> Thanks Roman, it looks fixed now!

Awesome! Now please, do document it in this repo.
(something like "NOTE: your code should *not* be compiled with `-march=native` / `-mtune=native`, because the docker images and the actual fuzzer runs may happen on machines with significantly different processors. You may however use `-mtune=generic`")

Yes, X3fDecoder is a troublemaker, perhaps i should fix it by simply removing all `*X3f*`, since it's not even fully working on the raw samples we have...

**Comment by Dor1s** [comment]
Makes sense, uploaded a PR: https://github.com/google/oss-fuzz/pull/753

**Pull request merged**
