### PR TITLE
Proposing new project: Python cbor2

### PR DESCRIPTION
**Pull request by mschwager**
`cbor2` is a Python CBOR (de)serializer with extensive tag support.

It has nearly [2,000 dependents](https://github.com/agronholm/cbor2/network/dependents) on GitHub. It's used by many large blockchain projects, such as:

- https://github.com/bitcoin-core/HWI
- https://github.com/Blockstream/Jade
- https://github.com/vyperlang/vyper
- https://github.com/lidofinance/lido-dao
- https://github.com/fetchai/cosmpy
- https://github.com/OpShin/opshin

And other non-blockchain projects, such as:

- https://github.com/project-chip/connectedhomeip
- https://github.com/pritunl/pritunl
- https://github.com/amazon-ion/ion-python

I received approval from this project here: https://github.com/agronholm/cbor2/pull/204#issuecomment-1874467670

### CODE REVIEW

**Comment by mschwager** [comment]
Hey @oliverchang, would you mind approving the CI workflows? That way I can work on any potential failures while the rest of the review process proceeds 👍

**Comment by mschwager** [comment]
Looks like everything is all green! Is there anything else I can do to help this move along?

**Comment by jonathanmetzman** [comment]
Sorry for the delay. We approve of adding this project.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
