### PR TITLE
gnupg: Try to fix build issues

### PR DESCRIPTION
**Pull request by MarcoFalke**
According to https://oss-fuzz-build-logs.storage.googleapis.com/index.html#gnupg the build is failing for the last 4 months.

For example https://oss-fuzz-build-logs.storage.googleapis.com/log-57c64478-ca6d-42f7-b498-f153dad5fe1a.txt ends with:

```
Step #4: + cd gnupg
Step #4: + mkdir tests/fuzz
Step #4: + cp ../fuzz_decrypt.c ../fuzz_decrypt.options ../fuzz_import.c ../fuzz_list.c ../fuzz_list.options ../fuzz_verify.c tests/fuzz
Step #4: + git apply ../fuzz.diff
Step #4: error: patch failed: configure.ac:991
Step #4: error: configure.ac: patch does not apply
Step #4: error: patch failed: g10/Makefile.am:164
Step #4: error: g10/Makefile.am: patch does not apply
Step #4: error: patch failed: tests/Makefile.am:18
Step #4: error: tests/Makefile.am: patch does not apply
Step #4: ********************************************************************************
Step #4: Failed to build.
Step #4: To reproduce, run:
Step #4: python infra/helper.py build_image gnupg
Step #4: python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 gnupg
Step #4: ********************************************************************************
Finished Step #4
ERROR
ERROR: build step 4 "gcr.io/oss-fuzz/gnupg" failed: step exited with non-zero status: 1
```

Another issue I ran into was an outdated `automake`.

I worked around both issues.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
cc @catenacyber from #2906

**Comment by MarcoFalke** [comment]
Looks like afl runs into another unrelated build problem

**Review by inferno-chromium — APPROVED** [review]
Thanks a lot, would appreciate if you or @catenacyber propose a patch upstream for this configure and makefile changes, these patches here in oss-fuzz break badly. gnupg is a very important project.

**Comment by catenacyber** [comment]
Thanks @MarcoFalke 
Did you just rebase the patch and fix the conflicts ?

@inferno-chromium I had already proposed the patch upstream cf https://dev.gnupg.org/T3914
But it was rejected, the point being that gnupg is a program and should not be compiled as a library

**Comment by MarcoFalke** [comment]
Yes, just did a rebase. Agree that ideally the fuzzing efforts are maintained directly in the gnupg git source.

**Pull request merged**
