### PR TITLE
zeek: Prune cc list

### PR DESCRIPTION
**Pull request by timwoj**
This prunes a big number of duplicates out of our cc list, since all of those people get the security@ mails already.

### CODE REVIEW

**Comment by timwoj** [comment]
Well.... crap. Ok, there's a couple I can take off there because they're no longer active anyways. I was mostly trying to reduce the amount of duplicate emails people get.

**Comment by jonathanmetzman** [comment]
> Well.... crap. Ok, there's a couple I can take off there because they're no longer active anyways. I was mostly trying to reduce the amount of duplicate emails people get.

Yeah sorry. Let me know when this is good to land!

**Comment by timwoj** [comment]
This is ready now.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
