### PR TITLE
tensorflow: fix fuzztest set up

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Follow up to https://github.com/google/oss-fuzz/pull/8992

Re-enabling the Tensorflow changes from there. Depends on https://github.com/tensorflow/tensorflow/pull/58646#issuecomment-1324005035

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
See build failure.

**Comment by DavidKorczynski** [comment]
> See build failure.

Thanks, the error
```
+ bazel build --config=oss-fuzz --subcommands --spawn_strategy=sandboxed --action_env=ASAN_OPTIONS=detect_leaks=0,detect_odr_violation=0 --define force_libcpp=enabled --verbose_failures --strip=never --copt=-UNDEBUG --config=monolithic --
ERROR: Config value 'oss-fuzz' is not defined in any .rc file
ERROR:root:Building fuzzers failed.
```

happens because we're waiting on https://github.com/tensorflow/tensorflow/pull/58646 to be merged. That PR will bump fuzztest on the Tensorflow repo, which is needed to have `oss-fuzz` defined in the `.rc` file.

**Comment by jonathanmetzman** [comment]
Any updates on this?

**Comment by DavidKorczynski** [comment]
This is now solved elsewhere, closing this one.

**Pull request closed without merging**
