### PR TITLE
[freerdp] update build requirements

### PR DESCRIPTION
**Pull request by ligurio**

### CODE REVIEW

**Comment by ligurio** [comment]
commits from this PR https://github.com/google/oss-fuzz/pull/10558 should be added too, right? @akallabeth

**Comment by akallabeth** [comment]
@ligurio yes

**Comment by ligurio** [comment]
@akallabeth currently desired commits cannot pass CI. Sorry, I don't want fixing raised problems, so take this on your side and let me know. I'll help with merging.

**Comment by akallabeth** [comment]
@ligurio looks like it is building `SDL` client and failing to link for some reason? just add `-DWITH_CLIENT_SDL=OFF` should be sufficient.

**Comment by akallabeth** [comment]
@ligurio heads up, we now also require `libsdl2-tty-dev`

**Comment by ligurio** [comment]
@akallabeth packages `libcjson-dev` and `libcjson1` are installed, but linking failed:

```
: && /usr/local/bin/clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION  -fprofile-instr-generate -fcoverage-mapping -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -Wno-c11-extensions -Wno-gnu -fno-omit-frame-pointer -g -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION  -fprofile-instr-generate -fcoverage-mapping -pthread -Wl,--no-as-needed -Wl,-ldl -Wl,-lm -Wno-unused-command-line-argument -stdlib=libc++    -L/usr/lib/x86_64-linux-gnu/mit-krb5 -lkrb5 -lk5crypto -lcom_err libfreerdp/common/test/CMakeFiles/TestFuzzCommonAssistanceHexStringToBin.dir/TestFuzzCommonAssistanceHexStringToBin.c.o -o Testing/TestFuzzCommonAssistanceHexStringToBin  libfreerdp/libfreerdp3.a  winpr/libwinpr/libwinpr3.a  -lrt  /usr/lib/x86_64-linux-gnu/libssl.a  /usr/lib/x86_64-linux-gnu/libcrypto.a  -ldl  -lm  -lkrb5  -lk5crypto  -lcom_err  /usr/lib/x86_64-linux-gnu/libicui18n.a  /usr/lib/x86_64-linux-gnu/libicuuc.a  /usr/lib/x86_64-linux-gnu/libicuio.a  -fsanitize=fuzzer && :
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
libfreerdp/libfreerdp3.a(aad.c.o): in function `cJSON_GetNumberValue':
aad.c:(.text+0x16): undefined reference to `cJSON_IsNumber'
/usr/bin/ld: aad.c:(.text+0x22): undefined reference to `cJSON_GetStringValue'
/usr/bin/ld: libfreerdp/libfreerdp3.a(aad.c.o): in function `cJSON_ParseWithLength':
aad.c:(.text+0xd2): undefined reference to `cJSON_Parse'
/usr/bin/ld: libfreerdp/libfreerdp3.a(aad.c.o): in function `aad_client_begin':
aad.c:(.text+0x662): undefined reference to `cJSON_Parse'
/usr/bin/ld: aad.c:(.text+0x895): undefined reference to `cJSON_Delete'
/usr/bin/ld: aad.c:(.text+0x906): undefined reference to `cJSON_Delete'
/usr/bin/ld: libfreerdp/libfreerdp3.a(aad.c.o): in function `aad_recv':
aad.c:(.text+0xb7d): undefined reference to `cJSON_Parse'
/usr/bin/ld: aad.c:(.text+0xd68): undefined reference to `cJSON_Parse'
/usr/bin/ld: aad.c:(.text+0xdb8): undefined reference to `cJSON_IsNumber'
/usr/bin/ld: aad.c:(.text+0x15aa): undefined reference to `cJSON_Delete'
/usr/bin/ld: libfreerdp/libfreerdp3.a(aad.c.o): in function `json_get_const_string':
aad.c:(.text+0x1892): undefined reference to `cJSON_IsString'
/usr/bin/ld: aad.c:(.text+0x18a5): undefined reference to `cJSON_GetStringValue'
/usr/bin/ld: libfreerdp/libfreerdp3.a(aad.c.o): in function `json_get_object':
aad.c:(.text+0x19f7): undefined reference to `cJSON_HasObjectItem'
/usr/bin/ld: aad.c:(.text+0x1a06): undefined reference to `cJSON_GetObjectItem'
/usr/bin/ld: /usr/bin/ld: DWARF error: invalid or unhandled FORM value: 0x25
libfreerdp/libfreerdp3.a(arm.c.o): in function `arm_create_request_json':
arm.c:(.text+0x97f): undefined reference to `cJSON_CreateObject'
```

Do you know why?

**Comment by akallabeth** [comment]
@ligurio no, we link `CJSON` public to `libfreerdp` and provide some fallback implementations for some functions `cJSON` only added in recent versions

**Comment by akallabeth** [comment]
but github seems to be experiencing some issue, I can´t merge pull requests on freerdp currently, it fails at rebasing (although the branch is up to date)

**Comment by ligurio** [comment]
> @ligurio no, we link CJSON public to libfreerdp and provide some fallback implementations for some functions cJSON only added in recent versions

So what is a recommended way to resolve it? If a project relies on bleeding edge version of a library, it is a popular way t o add a library source code as Git submodule and build it as a part of the project.

**Comment by akallabeth** [comment]
@ligurio `git submodules` are from hell ;)
anyway, no too recent version required.

**Comment by ligurio** [comment]
@akallabeth `WITH_AAD=OFF`

**Comment by akallabeth** [comment]
@ligurio looks like it works, but curious, I can do a static build with it enabled quite fine (for e.g. `sdl-freerdp`, `freerdp-proxy`, ... builds)

**Comment by ligurio** [comment]
> @ligurio looks like it works, but curious, I can do a static build with it enabled quite fine (for e.g. sdl-freerdp, freerdp-proxy, ... builds)

Me too with local build. The problem reproduces fine with building in OSS Fuzz:

```sh
git clone https://github.com/google/oss-fuzz/
cd oss-fuzz
sudo ./infra/helper.py build_fuzzers --engine libfuzzer freerdp
```

**Comment by ligurio** [comment]
@jonathanmetzman please review

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
