### PR TITLE
[clickhouse] Fix fuzzing build failures

### PR DESCRIPTION
**Pull request by nikitamikhaylov**

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
Build with UBSan was failed because of the typo in our code. Fixed here https://github.com/ClickHouse/ClickHouse/pull/42627

**Comment by nikitamikhaylov** [comment]
Build with MSan was killed by OOM. Locally everything is Ok 
``` 
> python infra/helper.py check_build --sanitizer memory clickhouse       
INFO:root:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=memory -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c++ -e HELPER=True -v /home/jakalletti/oss-fuzz/build/out/clickhouse:/out -t gcr.io/oss-fuzz-base/base-runner test_all.py.
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/double_delta_decompress_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/create_parser_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/mergetree_checksum_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/compressed_buffer_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/delta_decompress_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/select_parser_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/codegen_select_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/lexer_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/lz4_decompress_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/encrypted_decompress_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/columns_description_fuzzer
INFO: performing bad build checks for /tmp/not-out/tmpkbhvkehv/names_and_types_fuzzer
INFO:root:Check build passed.
```

**Comment by nikitamikhaylov** [comment]
Again, build with MSan is just killed. @jonathanmetzman Can you please take a look?

**Comment by jonathanmetzman** [comment]
I'm rerunning the build. 
But a past build failed with this issue.
```
FAILED: src/CMakeFiles/dbms.dir/Interpreters/HashJoin.cpp.o 
/usr/bin/ccache /usr/local/bin/clang++ --target=x86_64-linux-gnu --sysroot=/src/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64/x86_64-linux-gnu/libc -DBOOST_ASIO_HAS_STD_INVOKE_RESULT=1 -DBOOST_ASIO_STANDALONE=1 -DENABLE_MULTITARGET_CODE=1 -DHAS_RESERVED_IDENTIFIER -DLZ4_DISABLE_DEPRECATE_WARNINGS=1 -DPOCO_ENABLE_CPP11 -DPOCO_HAVE_FD_EPOLL -DPOCO_OS_FAMILY_UNIX -DSTD_EXCEPTION_HAS_STACK_TRACE=1 -DUNALIGNED_OK -DWITH_COVERAGE=1 -DWITH_GZFILEOP -DX86_64 -DZLIB_COMPAT -D_LIBCPP_ENABLE_THREAD_SAFETY_ANNOTATIONS -I/src/ClickHouse/build/includes/configs -I/src/ClickHouse/src -I/src/ClickHouse/build/src -I/src/ClickHouse/build/src/Core/include -I/src/ClickHouse/base/base/.. -I/src/ClickHouse/build/base/base/.. -I/src/ClickHouse/contrib/cctz/include -I/src/ClickHouse/base/pcg-random/. -I/src/ClickHouse/contrib/miniselect/include -I/src/ClickHouse/contrib/zstd/lib -I/src/ClickHouse/contrib/lz4/lib -isystem /src/ClickHouse/contrib/libcxx/include -isystem /src/ClickHouse/contrib/libcxxabi/include -isystem /src/ClickHouse/contrib/libunwind/include -isystem /src/ClickHouse/contrib/libdivide/. -isystem /src/ClickHouse/contrib/abseil-cpp -isystem /src/ClickHouse/contrib/croaring/cpp -isystem /src/ClickHouse/contrib/croaring/include -isystem /src/ClickHouse/contrib/cityhash102/include -isystem /src/ClickHouse/contrib/boost -isystem /src/ClickHouse/contrib/poco/Net/include -isystem /src/ClickHouse/contrib/poco/Foundation/include -isystem /src/ClickHouse/contrib/poco/NetSSL_OpenSSL/include -isystem /src/ClickHouse/contrib/poco/Crypto/include -isystem /src/ClickHouse/contrib/boringssl/include -isystem /src/ClickHouse/contrib/poco/Util/include -isystem /src/ClickHouse/contrib/poco/JSON/include -isystem /src/ClickHouse/contrib/poco/XML/include -isystem /src/ClickHouse/contrib/replxx/include -isystem /src/ClickHouse/contrib/fmtlib-cmake/../fmtlib/include -isystem /src/ClickHouse/contrib/magic_enum/include -isystem /src/ClickHouse/contrib/double-conversion -isystem /src/ClickHouse/contrib/dragonbox/include -isystem /src/ClickHouse/contrib/re2 -isystem /src/ClickHouse/build/contrib/re2-cmake -isystem /src/ClickHouse/contrib/zlib-ng -isystem /src/ClickHouse/build/contrib/zlib-ng-cmake -isystem /src/ClickHouse/contrib/pdqsort -isystem /src/ClickHouse/contrib/xz/src/liblzma/api -isystem /src/ClickHouse/contrib/snappy -isystem /src/ClickHouse/build/contrib/snappy-cmake -isystem /src/ClickHouse/contrib/fast_float/include -isystem /src/ClickHouse/contrib/poco/MongoDB/include -isystem /src/ClickHouse/contrib/sparsehash-c11 -isystem /src/ClickHouse/contrib/protobuf/src -isystem /src/ClickHouse/contrib/consistent-hashing --gcc-toolchain=/src/ClickHouse/cmake/linux/../../contrib/sysroot/linux-x86_64 -std=c++20 -nostdlib++  -fsanitize=fuzzer-no-link  -g -fno-omit-frame-pointer -DSANITIZER -fsanitize=memory -fsanitize-memory-use-after-dtor -fsanitize-memory-track-origins -fno-optimize-sibling-calls -fsanitize-blacklist=/src/ClickHouse/tests/msan_suppressions.txt -fdiagnostics-color=always -Xclang -fuse-ctor-homing -fsized-deallocation  -gdwarf-aranges -mssse3 -msse4.1 -msse4.2 -mpclmul -mpopcnt -fasynchronous-unwind-tables -ffile-prefix-map=/src/ClickHouse=. -falign-functions=32 -mbranches-within-32B-boundaries -fprofile-instr-generate -fcoverage-mapping -fdiagnostics-absolute-paths -fstrict-vtable-pointers -fexperimental-new-pass-manager -O2 -g -DNDEBUG -O3 -g -gdwarf-4  -fno-pie   -D OS_LINUX -Werror -nostdinc++ -std=gnu++20 -MD -MT src/CMakeFiles/dbms.dir/Interpreters/HashJoin.cpp.o -MF src/CMakeFiles/dbms.dir/Interpreters/HashJoin.cpp.o.d -o src/CMakeFiles/dbms.dir/Interpreters/HashJoin.cpp.o -c /src/ClickHouse/src/Interpreters/HashJoin.cpp
ninja: build stopped: subcommand failed.
ERROR:root:Building fuzzers failed.
```
Not sure if this is a real error but looks like an OOM

**Comment by nikitamikhaylov** [comment]
In our repo code is builds are passing on master. But yes, probably it this file is just so huge to fit in memory because of all template instantiations. I also notices the same behaviour with another file - ActionsDAG.cpp

**Comment by nikitamikhaylov** [comment]
But probably (to be 100% sure) I will rerun all the builds on my machine.

**Pull request merged**
