### PR TITLE
libzmq: update maintainers, add network tests

### PR DESCRIPTION
**Pull request by bluca**
zeromq is a networking framework, so the most relevant way to receive untrusted data (that would be good to fuzz) is via the network.
Add 2 simple tests to start exercising the internal engine, via loopback ipv4 tcp sockets. If these work I can add more, and then there's also a few APIs that take in free-form data that would be good to fuzz as well.

If using TCP sockets in these tests is frowned upon, I could switch to AF_UNIX with minimal changes - the code paths internally are _mostly_ the same between them anyway. I took care of using ephemeral and dynamically allocated free ports in both cases, which is usually the first objection for these kind of tests.

This is the first time I work with fuzzing, so please bear with me if I'm doing something not quite right. Also for some reason Travis is not syncing repos right now, so I can't test this by simply pushing, a PR is needed.

I am also adding @somdoron - zeromq co-maintainer - to the list of CC'ed folks for bugs. I also added my gmail account - when I provided my address I didn't realize the bug tracker is using Google accounts, so can't see the tickets at the moment.

### CODE REVIEW

**Comment by bluca** [comment]
Do existing tickets need to be updated for the new addresses manually? I can't see them at the moment due to the Google account issue

https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21831
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21832
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21833
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21846
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=21834

**Comment by inferno-chromium** [comment]
@bluca - existing bugs don't need to be updated, once you add any email address, the new folks will get auto-cced.
For the fuzzers and build.sh, it is best to move them to the project repo. Then build.sh just calls your $SRC/whatever path to build.sh. See https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/
For now, i am committing this, so that you will get results. For future updates, best to move it to your project repo, then you can iterate quickly :)

**Comment by inferno-chromium** [comment]
We wont have cycles to review the fuzzer since this is project specific code. If you have any specific questions, we are happy to answer them. We advise checking https://oss-fuzz.com/fuzzer-stats after 1-2 days for fuzzer statistics, that usually tells what are the main issues (if any) with the fuzzers.

**Comment by bluca** [comment]
> @bluca - existing bugs don't need to be updated, once you add any email address, the new folks will get auto-cced.
> For the fuzzers and build.sh, it is best to move them to the project repo. Then build.sh just calls your $SRC/whatever path to build.sh. See https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/
> For now, i am committing this, so that you will get results. For future updates, best to move it to your project repo, then you can iterate quickly :)

Thanks - I've been working on that already, almost ready. Will send a follow up when it is.

**Pull request merged**
