### PR TITLE
add libzmf

### PR DESCRIPTION
**Pull request by dtardon**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@caolanm - are these already fuzzed as part of libreoffice fuzzing. Can you also check out the open pull requests from @dtardon, i think some of these might be already covered by libreoffice fuzz targets. https://github.com/google/oss-fuzz/blob/master/projects/libreoffice/Dockerfile#L99

**Comment by caolanm** [comment]
No, there's no overlap. The LibreOffice fuzzing is fuzzing formats directly supported by LibreOffice, and dtardon is fuzzing formats supported by LibreOffice via that menagerie of standalone libraries.

**Comment by inferno-chromium** [comment]
@caolanm @dtardon - can all these pull requests be combined into one project libreoffice_standalone_libs or something. I don't see a reason to do all targets seperately since that splits our vm resources onto these tiny targets.

+ @kcc @oliverchang for thoughts as well.

**Comment by dtardon** [comment]
@inferno-chromium It would be possible to fuzz the formats supported by the librevenge-based libraries as part of libreoffice, but it would be impractical: libreoffice bundles all the libraries, but it builds from released tarballs, so fix verification would be delayed to next release(s)... We typically think about the libs as parts of a single project (even though they are made by several different people and use several different hosting sites), so it makes some sense to combine them. On the other side, AFAIK I'm the only person who does have commit access to all of them...

**Comment by inferno-chromium** [comment]
Closing this since it is already merged in dlp libs project.

**Pull request closed without merging**
