### PR TITLE
[build-infra] bad build check using --privileged,--cap-add=all to enable netdriver

### PR DESCRIPTION
**Pull request by jonathanmetzman**
May fix https://github.com/google/oss-fuzz/issues/8601

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py mongoose --sanitizer address --fuzzing-engine libfuzzer honggfuzz

**Comment by jonathanmetzman** [comment]
This passes CI (including trial-build: https://github.com/google/oss-fuzz/runs/9126126089) and is ready to land

**Comment by jonathanmetzman** [comment]
> This passes CI (including trial-build: https://github.com/google/oss-fuzz/runs/9126126089) and is ready to land

Actually, maybe worth rebuilding everything since this change affects all builds?

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine all

**Comment by Alan32Liu** [comment]
> > This passes CI (including trial-build: https://github.com/google/oss-fuzz/runs/9126126089) and is ready to land
> 
> Actually, maybe worth rebuilding everything since this change affects all builds?

Yeah, it's probably safer to test them?
Hope I used the right command for this.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Review by oliverchang — APPROVED** [review]
thanks!!!

**Comment by DavidKorczynski** [comment]
The same issue is being reported https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52885

**Comment by oliverchang** [comment]
@jonathanmetzman did we deploy this?

**Comment by oliverchang** [comment]
From the logs it seems like we didn't. I'll deploy now.

Thanks @DavidKorczynski for flagging.

**Comment by DavidKorczynski** [comment]
Awesome -- the build is passing now!

**Comment by jonathanmetzman** [comment]
Thanks for the deploy @oliverchang and for the help @DavidKorczynski

**Comment by DavidKorczynski** [comment]
Am not sure if this is working as expected, when I'm trying to access the status of the fuzzer I get no data:
https://oss-fuzz.com/fuzzer-stats?project=mongoose&fuzzer=Unknown&job=honggfuzz_asan_mongoose&group_by=by-fuzzer

**Comment by DavidKorczynski** [comment]
Chaning my search criteria does, however, show some results: https://oss-fuzz.com/fuzzer-stats?group_by=by-day&date_start=2022-11-14&date_end=2022-11-20&fuzzer=honggfuzz_mongoose_fuzz_netdriver_http&job=honggfuzz_asan_mongoose&project=mongoose

Although, am not sure the data is as expected?
```
date | testcases_executed | total_crashes | new_crashes | known_crashes
-- | -- | -- | -- | --
Nov 20, 2022 | 0 | 0 | 0 | 0
Nov 19, 2022 | 0 | 0 | 0 | 0
Nov 18, 2022 | 0 | 0 | 0 | 0
Nov 17, 2022 | 0 | 0 | 0 | 0
Nov 16, 2022 | 0 | 0 | 0 | 0
Nov 15, 2022 | 0 | 0 | 0 | 0
```

**Pull request merged**
