### PR TITLE
Improve fuzzing coverage of STB

### PR DESCRIPTION
**Pull request by jsnv-dev**
This pull request introduces additional fuzzers to enhance the fuzzing coverage of the stb_image.h library, specifically targeting the testing of various image format loader functions.

### CODE REVIEW

**Comment by jsnv-dev** [comment]
@DonggeLiu, @randy408, @devtty1er, @Dor1s, if you have time to review. Let me know if you have any feedback. Thank you!

**Comment by DonggeLiu** [comment]
Thanks @jsnv-dev, would it be OK to maintain the fuzz targets upstream (in the project under test)?

**Comment by jsnv-dev** [comment]
> Thanks @jsnv-dev, would it be OK to maintain the fuzz targets upstream (in the project under test)?

Thanks @DonggeLiu, Yeah, it makes sense. I'll close this PR and make PR on their end.

**Comment by DonggeLiu** [comment]
Thanks @jsnv-dev!

**Pull request closed without merging**
