### PR TITLE
infra: bazel_build_fuzz_tests: do not force O0

### PR DESCRIPTION
**Pull request by DavidKorczynski**
This is causing issues for e.g. Fuzz Introspector where some data, e.g. mapping of binary to source, is optimized out.

We don't need to sets the flags in the first place, considering the `oss-fuzz` rule applies the `CFLAGS` https://github.com/bazelbuild/rules_fuzzing/blob/master/docs/guide.md#configuration-flags

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector address

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector address

**Comment by DavidKorczynski** [comment]
The errors shown from the trial build are all unrelated to this PR (the changes in this PR does not run for these projects either, since they don't call `bazel_build_fuzz_tests`). This is good to go!

**Review by AdamKorcz — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
The CLA check is stuck on this done -- this is superseded by https://github.com/google/oss-fuzz/pull/11718

**Pull request closed without merging**
