### PR TITLE
Add ntopng project

### PR DESCRIPTION
**Pull request by patacca**
This a new project proposal to start fuzzing ntopng.

The project it is still in early stage but in the near future we plan to enable other sanitizers and fuzzing engines

cc @lucaderi

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Can you share some details of why ntopng is critical? WHo are some of the users? How many of them are there?

**Comment by patacca** [comment]
ntopng is a network traffic monitoring tool that can provide real-time insights into traffic patterns and usage, it can be used in conjunction with IDS to better identify potential security threats.
Its core engine is written in C/C++ and involves a lot of raw pointers manipulations, making it susceptible to memory violation bugs that could result in information leaks or arbitrary code execution.
Due to the sensitive content it might process (coming from the traffic being analyzed) ntopng raises security concerns.

I can't tell precise statistics about the users of ntopng because I am not part of the organization (I am only working on the fuzzing project) but it has **5.3k stars** on github, **+100** contributors, a score of **0.66187** calculated using [ossf/criticality_score](https://github.com/ossf/criticality_score) (to put in perspective it's roughly equivalent to apache [httpd](https://github.com/apache/httpd)).
The ntopng (**ntop** **n**ext **g**eneration) project falls under the ntop umbrella that was first introduced in the '90s (I think around 1997 but I am not 100% sure of it) that makes it a quite old project with a strong userbase.
Moreover ntopng is highly portable, since it works on virtually every Unix platform, including Linux and FreeBSD, MacOS and on Windows as well.

**Comment by jonathanmetzman** [comment]
I'm asking the committee to consider this project. Thank you for the detailed response.

**Review by Alan32Liu — APPROVED** [review]

**Comment by patacca** [comment]
I guess the project has been approved, thanks for the opportunity.
Feel free to merge this one when you can.

**Comment by Alan32Liu** [comment]
> Ha yes it has been approved.

quadra-approved.

**Pull request merged**
