### PR TITLE
[skia] Fix build after SkTMax refactor

### PR DESCRIPTION
**Pull request by kjlubick**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
LGTM. Just waiting for travis.

**Comment by kjlubick** [comment]
I'm not sure what those failures are - did clang crash?

**Comment by jonathanmetzman** [comment]
Assigning to current sherriff @mbarbella-chromium.

**Comment by mbarbella-chromium** [comment]
I don't want to block this since I can't imagine how this change would have affected the failures we're seeing in travis. I'll try to keep an eye out for build failures that would need a fix on our side, but if you see any after we merge this please let me know and I'll investigate more.

**Pull request merged**
