### PR TITLE
Fuzz OSS-Fuzz with Atheris and ClusterFuzzLite

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
The failures are a bug I caught.

**Comment by jonathanmetzman** [comment]
Ping

**Review by oliverchang — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
> The failures are a (somewhat contrived) bug the fuzzer caught.

Could you elaborate what you mean here?

Looking at the OSS-Fuzz actions logs, it looks like the fuzzer continues to run into unreproducible bugs:
```
2022-12-15 10:32:32,348 - root - WARNING - Could not download artifact: cifuzz-corpus-coverage_atheris_fuzzer.
2022-12-15 10:32:32,348 - root - INFO - Done downloading corpus. Contains 0 elements.
2022-12-15 10:32:32,348 - root - INFO - Starting fuzzing
INFO: Using preloaded libfuzzer
2022-12-15 10:42:42,745 - root - INFO - Fuzzer: coverage_atheris_fuzzer. Detected bug.
/github/workspace/build-out/coverage_atheris_fuzzer.pkg -timeout=[25](https://github.com/google/oss-fuzz/actions/runs/3703241904/jobs/6274451069#step:5:26) -rss_limit_mb=2560 -len_control=0 -seed=1337 -artifact_prefix=/tmp/tmpye9s71y_/ -max_total_time=600 -print_final_stats=1 /github/workspace/cifuzz-corpus/coverage_atheris_fuzzer >fuzz-0.log 2>&1
2022-12-15 10:42:42,746 - root - INFO - Trying to reproduce crash using: /tmp/tmpye9s71y_/tmpulgq0lye.
pulse...
2022-12-15 10:43:12,854 - root - ERROR - Reproducing timed out..
2022-12-15 10:43:12,854 - root - INFO - Crash is not reproducible.
```

I'm asking because I'm struggling with ClusterFuzzLite on the fuzz introspector repository. The status is ClusterFuzzLite always reports a bug is found, but I don't get a stack trace and the artifact produced is just an empty file. See e.g. https://github.com/ossf/fuzz-introspector/pull/713

The fuzzer does not run into a bug locally -- neither when run outside the docker images and locally in the docker images. First, I thought it had to do with timeouts in the instrumentation (https://github.com/google/oss-fuzz/issues/9222) however, after having reduced the instrumentation time a lot (to a few seconds, which should be less than the 25 seconds for a reproducer), ClusterFuzzLite still reports a bug.

I'm confused why clusterfuzz picks up a non-zero exit code. The fuzzer log shows
```
2022-12-16T22:13:13.3522545Z #549258	DONE   cov: 53 ft: 67 corp: 10/170b lim: 4096 exec/s: 1824 rss: 95Mb
2022-12-16T22:13:13.3522900Z ###### Recommended dictionary. ######
2022-12-16T22:13:13.3523260Z "\000\000\000\000\000\000\000\000" # Uses: 14003
2022-12-16T22:13:13.3523531Z "\001\000" # Uses: 14384
2022-12-16T22:13:13.3523818Z "\001\000\000\000" # Uses: 13768
2022-12-16T22:13:13.3524139Z "---" # Uses: 8274
2022-12-16T22:13:13.3524413Z ###### End of recommended dictionary. ######
2022-12-16T22:13:13.3524762Z Done 549258 runs in 301 second(s)
2022-12-16T22:13:13.3840318Z stat::number_of_executed_units: 549258
2022-12-16T22:13:13.3840834Z stat::average_exec_per_sec:     1824
2022-12-16T22:13:13.3841121Z stat::new_units_added:          52
2022-12-16T22:13:13.3841441Z stat::slowest_unit_time_sec:    0
2022-12-16T22:13:13.3842019Z stat::peak_rss_mb:              95
2022-12-16T22:13:13.3843051Z /github/workspace/build-out/test_fuzz_report_generation.pkg -timeout=25 -rss_limit_mb=2560 -len_control=0 -seed=1337 -artifact_prefix=/tmp/tmpa_eokvhw/ -max_total_time=300 -print_final_stats=1 /github/workspace/cifuzz-corpus/test_fuzz_report_generation >fuzz-1.log 2>&1
2022-12-16T22:13:20.8520101Z 2022-12-16 22:13:20,843 - root - INFO - Reproduce command returned: 1. Reproducible on /github/workspace/build-out/test_fuzz_report_generation.
2022-12-16T22:13:20.8520622Z 2022-12-16 22:13:20,843 - root - INFO - Crash is reproducible.
```

Where the `Done 549258 runs in 301 second(s)` indicates the atheris went well and a Graceful exit with exit code of 0 is done: https://github.com/google/atheris/blob/d588ea015b67ee34a3404f93729cd7858300781c/src/native/core.cc#L172-L174

**Pull request merged**
