### PR TITLE
Adds grpc-go project

### PR DESCRIPTION
**Pull request by catenacyber**
cc @menghanl

Would you be interested in continuous fuzzing for grpc-go ?
If so, I can make a Pull Request to merge the fuzz targets in grpc-go's repository

### CODE REVIEW

**Comment by menghanl** [comment]
cc @dfawley

**Comment by dfawley** [comment]
How does this integrate with github?  Can we get a preview of any current findings?

**Comment by inferno-chromium** [comment]
> How does this integrate with github? Can we get a preview of any current findings?

GitHub does not support private issues, so OSS-Fuzz puts in a secure issue tracker (we use monorail, also used by Chrome). See trophies - https://github.com/google/oss-fuzz#trophies. We fuzz critical OSS, e.g. OpenSSL, Kubernetes, etc. Full list here - https://github.com/google/oss-fuzz/tree/master/projects

**Comment by dfawley** [comment]
So the findings all show up in a separate, private issue tracker?  How would we access it?

Is there a way to get a preview of things it finds in our project without turning on the integrations yet?

What would need to be merged into our repo to enable this?

**Comment by inferno-chromium** [comment]
> So the findings all show up in a separate, private issue tracker? How would we access it?

All automatic, if your email is in project.yaml (this PR), you will get auto-access.

> 
> Is there a way to get a preview of things it finds in our project without turning on the integrations yet?
> 
> What would need to be merged into our repo to enable this?

Nothing for now, you can just see results from this PR merged in OSS-Fuzz. And then later move fuzzer in your repo, see https://google.github.io/oss-fuzz/advanced-topics/ideal-integration/

**Comment by catenacyber** [comment]
Thank @dfawley for these interesting questions

> Can we get a preview of any current findings?

No bugs found in 20 minutes of fuzzing for each target (client and server) reaching a corpus about 300 elements (that means 300 different inputs covering different code paths)

> Is there a way to get a preview of things it finds in our project without turning on the integrations yet?

You can try locally yourself (and run for longer than 20 minutes)
To do so, checkout this branch, then run 
```
python infra/helper.py build_image grpc-go
python infra/helper.py build_fuzzers grpc-go
python infra/helper.py run_fuzzer grpc-go fuzz_helloserver
```

There are more ways and options to achieve this if you are interested, let me know

> How does this integrate with github?

As Abhishek said, there is a separate, private issue tracker.

Furthermore, once your project is integrated into oss-fuzz, you can use CIFuzz, which is a Github CI action to run fuzzers on PR (and prevent bugs from being merged in main branch)

> What would need to be merged into our repo to enable this?

As Abhishek said, it is recommended to have the fuzz targets (ie in this case the file fuzz_hello.go) in your repository.

**Pull request merged**
