### PR TITLE
ron: support upstream changes

### PR DESCRIPTION
**Pull request by manunio**
- This pr adds support for additional fuzz targets
-  ~Pins rust version for https://github.com/ron-rs/ron/pull/462 (Build was failing locally with `unknown feature proc_macro_span_shrink` error)~

cc @juntyr

### CODE REVIEW

**Comment by juntyr** [comment]
@manunio I thought I had fixed the unknown feature bug already by removing the Cargo.lock file from the fuzzer, which had pinned an old version of proc-macro2.

**Comment by juntyr** [comment]
> @juntyr checked it against ci its failing.
> 
> ```
>  error[E0635]: unknown feature `proc_macro_span_shrink`
>   --> /rust/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/lib.rs:92:30
>    |
> 92 |     feature(proc_macro_span, proc_macro_span_shrink)
>    |                              ^^^^^^^^^^^^^^^^^^^^^^
> ```

Oh dang that’s my fault, sorry. The PR branch wasn’t rebased yet - let me fix that quickly

**Comment by juntyr** [comment]
Ok, let’s see if CI works now. If it does, I’ll merge the PR into ron and we can change this PR to just point at the ron head again.

**Comment by juntyr** [comment]
> > Ok, let’s see if CI works now. If it does, I’ll merge the PR into ron and we can change this PR to just point at the ron head again.
> 
> @juntyr ci is passing now.

Thank you so much for your help! I've merged the PR into ron.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
