### PR TITLE
pistache: add fuzzer corpus

### PR DESCRIPTION
**Pull request by tyler92**
The fuzzing for pistachio/pistache project has been improved and now has a corpus. Please let me know if I add it correctly to this MR

### CODE REVIEW

**Review by DavidKorczynski — APPROVED** [review]
Look good!

**Comment by tyler92** [comment]
For some reason, the corpus wasn't used in the [latest build](https://oss-fuzz-build-logs.storage.googleapis.com/log-499e2aac-c6e3-4d72-979f-58cef15197df.txt):

```
Step #39 - "compile-libfuzzer-undefined-x86_64": + zip -q -r -j /workspace/out/libfuzzer-undefined-x86_64/fuzz_parsers_seed_corpus.zip ../tests/fuzzers/corpus

...

Step #42: Already have image: gcr.io/oss-fuzz/pistache
Step #42:   adding: fuzz_parsers (deflated 67%)
Step #42:   adding: fuzz_parsers_seed_corpus.zip (stored 0%)
Step #42:   adding: llvm-symbolizer (deflated 64%)
```

Here we have `stored 0%` for `fuzz_parsers_seed_corpus.zip`, and I guess the .zip file is empty despite the fact that the command

```
zip -q -r -j fuzz_parsers_seed_corpus.zip ../tests/fuzzers/corpus
```

produces not an empty file in my local environment. 

@DavidKorczynski Could you please help me with the investigation?

**Comment by DaveLak** [comment]
@tyler92 I think your issue is due to a typo:

Your fuzz harness is `fuzz_parser`[^1] but your seed corpus zip file has an "s", i.e., `fuzz_parsers_`...[^2]

Changing your zip command to write `fuzz_parser_seed_corpus.zip` instead of `fuzz_parsers_seed_corpus.zip` this should resolve the issue:
```shell
zip -q -r -j $OUT/fuzz_parser_seed_corpus.zip ../tests/fuzzers/corpus
```

[Seed corpra zips must be prefixed with the same name of the fuzz target/fuzz harness they're used for (with the exact spelling.)](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#seed-corpus)


[^1]: https://github.com/google/oss-fuzz/blob/840631a49e4c24c2fddb43ef93ab95a0ff623150/projects/pistache/build.sh#L22

[^2]: https://github.com/google/oss-fuzz/blob/840631a49e4c24c2fddb43ef93ab95a0ff623150/projects/pistache/build.sh#L24

**Comment by tyler92** [comment]
Yeah, I checked this "s" many times :smiling_face_with_tear: 

Anyway, thank you very much for the help. I reproduced the issue locally, so let me debug it and I hope I will come back with a solution.

**Comment by DavidKorczynski** [comment]
How do you reach the conclusion the corpus is not uploaded? Am not 100% what the logging messages indicate, but the same output happens for other projects during uploading e.g. from binutils:

```sh
Step #15: Already have image: gcr.io/oss-fuzz/binutils
Step #15:   adding: fuzz_addr2line (deflated 61%)
Step #15:   adding: fuzz_addr2line.options (stored 0%)
Step #15:   adding: fuzz_addr2line_seed_corpus.zip (stored 0%)
Step #15:   adding: fuzz_as (deflated 61%)
Step #15:   adding: fuzz_as.options (stored 0%)
Step #15:   adding: fuzz_bfd (deflated 61%)
Step #15:   adding: fuzz_bfd_ext (deflated 61%)
Step #15:   adding: fuzz_bfd_ext_seed_corpus.zip (stored 0%)
Step #15:   adding: fuzz_bfd_seed_corpus.zip (stored 0%)
Step #15:   adding: fuzz_disas_ext-bfd_arch_arc (deflated 74%)
```

I would assume the corpus is used

**Comment by DavidKorczynski** [comment]
It's due to these lines here: https://github.com/google/oss-fuzz/blob/840631a49e4c24c2fddb43ef93ab95a0ff623150/infra/build/functions/build_project.py#L471-L500

This is from the pistache image locally when running these commands:

```sh
root@e0368111cb96:/out# zip -r *                                                                                                                         
  adding: fuzz_parsers_seed_corpus.zip (stored 0%)
  adding: llvm-symbolizer (deflated 64%)
```

All is work and the corpus is added

**Comment by tyler92** [comment]
Yeah, right now all is working fine, as expected. I was just confused that

- we added a corpus at 20240425
- the next coverage report looked as if the corpus wasn't applied: [20240426](https://storage.googleapis.com/oss-fuzz-coverage/pistache/reports/20240426/linux/report.html)
- today's coverage report looks good: [20240427](https://storage.googleapis.com/oss-fuzz-coverage/pistache/reports/20240427/linux/report.html)

Anyway, right now everything is OK, thank you, guys, for the support!

**Pull request merged**
