### PR TITLE
Delete old builds before doing a new one

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
As discussed in #1388 
Also, I don't think this affects incremental builds (which I'm not sure we actually do) since most build.sh files will build to a fixed directory and then copy it to $OUT.

**Comment by inferno-chromium** [comment]
Will let @oliverchang review this. Also, he can evaluate the consequence of this on incremental builds in infra/helper.py. i think correctness is important than having bad artifact since it can confuse bad_build_check on run on stale fuzz targets on a different sanitizer build.

**Comment by oliverchang** [comment]
clearing $OUT seems reasonable to me, but since this is fixing a helper.py use case we should probably do it there? if there are a permission issues you can just run the docker image with the rm command.

**Comment by inferno-chromium** [comment]
ok did it in https://github.com/google/oss-fuzz/pull/1389.

**Pull request closed without merging**
