### PR TITLE
Update AFL++ commit ID

### PR DESCRIPTION
**Pull request by vanhauser-thc**
Adds a few features that are very beneficial for CI fuzzing. e.g. AFL_IGNORE_SEED_PROBLEMS
This also fixes several minor bugfixes.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
@Alan32Liu @jonathanmetzman 
there will be a corresponding clusterfuzz PR, that adds a few features, some of them command line options that were added in the June oss-fuzz AFL++ update.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine afl

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py spirv-tools tint --sanitizer address --fuzzing-engine afl

**Review by jonathanmetzman — COMMENTED** [review]
LGTM

**Pull request merged**
