### PR TITLE
Fix rules_fuzzing presubmit

### PR DESCRIPTION
**Pull request by fmeum**
Work around https://github.com/bazelbuild/bazel/issues/21592 as discovered in https://github.com/bazelbuild/rules_fuzzing/pull/242#issuecomment-1974913042.

### CODE REVIEW

**Comment by fmeum** [comment]
FYI @stefanbucur

**Review by DavidKorczynski — COMMENTED** [review]
Do you know if this should should be propagated into the bazel builder script as well?
 
https://github.com/google/oss-fuzz/blob/9d034750a9e6f6d7327c71c9eeccd3511472e2dd/infra/base-images/base-builder/bazel_build_fuzz_tests#L50-L62

**Comment by fmeum** [comment]
@DavidKorczynski It shouldn't: Standalone builds are (slightly) faster and thus are better for large, real projects. The incompatibility is only with `--features=layering_check`, which rules_fuzzing specifies for itself to ensure that it is also compatible with end user projects using that feature - this isn't relevant for those.

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski It shouldn't: Standalone builds are (slightly) faster and thus are better for large, real projects. The incompatibility is only with `--features=layering_check`, which rules_fuzzing specifies for itself to ensure that it is also compatible with end user projects using that feature - this isn't relevant for those.

Thanks!

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
