### PR TITLE
capstone: update target branch and infomation

### PR DESCRIPTION
**Pull request by kabeor**
Get ready for capstone v5 branch. v4 is archived.

### CODE REVIEW

**Review by Alan32Liu — APPROVED** [review]

**Comment by Alan32Liu** [comment]
@kabeor could you please take a look at the CI failures? Thanks!

**Comment by kabeor** [comment]
@Alan32Liu Hi, thanks for approving. The failures will be fixed automately after we release V5 (will release this week). After we release that, I'll come back to request a rerun for CI.

**Comment by Alan32Liu** [comment]
> @Alan32Liu Hi, thanks for approving. The failures will be fixed automately after we release V5 (will release this week). After we release that, I'll come back to request a rerun for CI.

OK, thanks for the explanation.
I disabled auto-merge. Let's rerun them later.

**Comment by kabeor** [comment]
@Alan32Liu Hi, we have released Capstone V5.0 yesterday. Can you please rerun the CI? Thanks.

**Comment by kabeor** [comment]
Hi. Can this PR be merged? CI is passed.

**Pull request merged**
