### PR TITLE
[nio-multipart-parser-address] Remove

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Project build never succeeded, causing us exceptions in ClusterFuzz.
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#nio-multipart-parser

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@aschaich @0roman Please fix this or I will need to remove it. It's causing a lot of exceptions on our infra.

**Comment by Alan32Liu** [comment]
+1

**Comment by Alan32Liu** [comment]
BTW, would it be difficult to automatically cc the initial integration PR submitter if the project failed in its first gcloud build/run?
I recall the project owner will be informed, but will the submitter be aware of this?

**Comment by jonathanmetzman** [comment]
We already file a bug, that usually should be enough (though it does take 2 days)..

**Comment by 0roman** [comment]
@jonathanmetzman I'll ping the team and we'll fix this.

**Pull request merged**
