### PR TITLE
Bump Boost download URL in Cryptofuzz-related projects

### PR DESCRIPTION
**Pull request by maflcko**
This is required for newer compilers, such as clang-18. Otherwise, an error may be encountered:

```
/usr/include/boost/container_hash/hash.hpp:131:33: error: no template named 'unary_function' in namespace 'std'; did you mean '__unary_function'?
  131 |         struct hash_base : std::unary_function<T, std::size_t> {};
      |                            ~~~~~^
/usr/local/bin/../include/c++/v1/__functional/unary_function.h:46:1: note: '__unary_function' declared here
   46 | using __unary_function = __unary_function_keep_layout_base<_Arg, _Result>;
      | ^
1 error generated.

### CODE REVIEW

**Review by DavidKorczynski — COMMENTED** [review]
@guidovranken could help review here? For context, these efforts are part of upgrading clang/llvm (https://github.com/google/oss-fuzz/pull/11714) across OSS-Fuzz so the goal is to prepare such that projects do not break once the upgrade happens.

**Comment by guidovranken** [comment]
rustcrypto has been failing for a while, I'll check today and fix it.

libressl has been failing for 1 day unrelated to this PR, CC @botovq

You can either merge this already as neither failure is related to this PR, or wait until we diagnose the issues, whichever you prefer.

**Comment by botovq** [comment]
On Thu, Mar 28, 2024 at 03:49:15AM -0700, Guido Vranken wrote:
> rustcrypto has been failing for a while, I'll check today and fix it.
> 
> libressl has been failing for 1 day unrelated to this PR, CC @botovq

Thanks. I don't get notified of such failures and a few hours ago the
fuzzing badge on our main page was still green.

**Comment by guidovranken** [comment]
> On Thu, Mar 28, 2024 at 03:49:15AM -0700, Guido Vranken wrote: rustcrypto has been failing for a while, I'll check today and fix it. libressl has been failing for 1 day unrelated to this PR, CC @botovq
> Thanks. I don't get notified of such failures and a few hours ago the fuzzing badge on our main page was still green.

I think it has to fail for 2 consecutive days before we get an email.

**Comment by botovq** [comment]
Should be fixed by https://github.com/libressl/portable/commit/95b74a0b10ccd36e6462778cbf246a25dcf196c4

**Comment by DavidKorczynski** [comment]
@maflcko -- the CI looks to be turning green, if it does do you prefer merging this one or the spinouts (are they the same?)?

**Comment by DavidKorczynski** [comment]
Ah sorry, I didn't realise this had been reduced in terms of projects in this PR. Sounds good, will go through them as they turn green.

**Pull request closed without merging**
