### PR TITLE
Adds project freeradius

### PR DESCRIPTION
**Pull request by catenacyber**
@arr2036 would you be interested in continuous fuzzing for freeradius ?
This PR enables it with the fuzz targets already there.

As oss-fuzz does not allow to define environment variables before running the fuzzers, a small patch was needed to find the right directories...

### CODE REVIEW

**Comment by arr2036** [comment]
Of course :) Does oss-fuzz allow passing arguments? The dict dir is already setable with `-D` I could add something for that library path if that'd help?

**Comment by catenacyber** [comment]
@inferno-chromium do you have ideas about this ?
The freeradius fuzz targets use directories which can be referenced by environment variables or by arguments when launching the fuzzer.
I do not know of oss-fuzz allowing this

**Comment by inferno-chromium** [comment]
> @inferno-chromium do you have ideas about this ?
> The freeradius fuzz targets use directories which can be referenced by environment variables or by arguments when launching the fuzzer.
> I do not know of oss-fuzz allowing this

nope that model does not work with oss-fuzz, we need libfuzzer based targets

**Comment by catenacyber** [comment]
> > @inferno-chromium do you have ideas about this ?
> > The freeradius fuzz targets use directories which can be referenced by environment variables or by arguments when launching the fuzzer.
> > I do not know of oss-fuzz allowing this
> 
> nope that model does not work with oss-fuzz, we need libfuzzer based targets

I guess I did not make myself clear.
Those are libfuzzer based targets.

They use an initialization step with `LLVMFuzzerInitialize`, which uses some environment variables to find the paths to certain configuration files.
For oss-fuzz, I needed a dummy patch to hard code the use of a subdirectory from where the fuzz target is launched (like `$OUT/somepath`)
Is there a better way ?

**Comment by inferno-chromium** [comment]
> > > @inferno-chromium do you have ideas about this ?
> > > The freeradius fuzz targets use directories which can be referenced by environment variables or by arguments when launching the fuzzer.
> > > I do not know of oss-fuzz allowing this
> > 
> > 
> > nope that model does not work with oss-fuzz, we need libfuzzer based targets
> 
> I guess I did not make myself clear.
> Those are libfuzzer based targets.
> 
> They use an initialization step with `LLVMFuzzerInitialize`, which uses some environment variables to find the paths to certain configuration files.
> For oss-fuzz, I needed a dummy patch to hard code the use of a subdirectory from where the fuzz target is launched (like `$OUT/somepath`)
> Is there a better way ?

$OUT wont work on CF infra since that is not set on bots. can you find path of running binary and create relative path from it.

**Comment by catenacyber** [comment]
> $OUT wont work on CF infra since that is not set on bots. can you find path of running binary and create relative path from it.

That is what I did ;-)

**Comment by asraa** [comment]
Thanks! Is this ready for review?

**Comment by catenacyber** [comment]
> Thanks! Is this ready for review?

Yes it is :-)

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
