### PR TITLE
Add libproxy project

### PR DESCRIPTION
**Pull request by janbrummer**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
1. Please sign the CLA.
2. Who are some prominent users of this project?

**Comment by janbrummer** [comment]
> 1. Please sign the CLA.

I've an already CLA: herrvorragend81@gmail.com and the requested mail jan.brummer@tabos.org is set as additional mail. GitHub account name is the same.

> 
>     2. Who are some prominent users of this project? Are there many users?

Firefox, libQt5Network, glib-networking, openconnect, wget, ...

**Comment by jonathanmetzman** [comment]
We accept this project.

**Comment by jonathanmetzman** [comment]
You should look at the details here: https://github.com/google/oss-fuzz/pull/11771/checks I looked up that you have signed but not every maintainer knows how to do this.

**Pull request merged**
