### PR TITLE
Fix build of several projects

### PR DESCRIPTION
**Pull request by guidovranken**
Spent a lot of time trying to fix build with new clang/AFL (https://github.com/google/oss-fuzz/pull/11714) but didn't succeed right now so disabling AFL for some projects.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
Is it fine to merge this despite the failures?

**Comment by guidovranken** [comment]
> Is it fine to merge this despite the failures?

Yes this + https://github.com/google/oss-fuzz/pull/11943 should make the projects succeed.

**Comment by guidovranken** [comment]
Can this be merged? Optionally retrigger CI; now that https://github.com/google/oss-fuzz/pull/11943 has been merged, it should succeed now

**Pull request closed without merging**
