### PR TITLE
Update ClickHouse project

### PR DESCRIPTION
**Pull request by nickitat**

### CODE REVIEW

**Review by nikitamikhaylov — APPROVED** [review]

**Review by oliverchang — APPROVED** [review]

**Comment by nickitat** [comment]
@oliverchang what can we do about this:

```
2024-08-06T02:18:32.7015417Z ##[warning]You are running out of disk space. The runner will stop working when the machine runs out of disk space. Free space left: 10 MB
2024-08-06T02:18:33.0393847Z strip: /src/ClickHouse/build/programs/server/fuzzers/stMmFdCN[.text]: No space left on device
```

**Comment by nickitat** [comment]
build with coverage doesn't succeed for an unclear reason. i'd prefer if we investigate it later and merge now the fix for other build types.

@oliverchang @maflcko could you guys press the merge button pls

**Comment by nickitat** [comment]
i already tried and the result looked the same

**Comment by nickitat** [comment]
@oliverchang kind ping

**Comment by nickitat** [comment]
@DavidKorczynski maybe you could help pls

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
