### PR TITLE
Add projects/tesseract

### PR DESCRIPTION
**Pull request by stweil**
Signed-off-by: Stefan Weil <sw@weilnetz.de>

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Just sign the CLA and I'll merge this.

**Comment by jonathanmetzman** [comment]
ping @stweil

**Comment by stweil** [comment]
@jonathanmetzman, the problem is that I want to understand the details of the CLA before I can sign it. I am not a lawyer and have difficulties with legal texts in a foreign language (such texts can even be difficult in my native language).

**Comment by Dor1s** [comment]
@stweil, did you have a chance to understand the details of the CLA? What should we do with your pull request?

**Comment by Dor1s** [comment]
@stweil, are you still interested? I've also pinged https://github.com/tesseract-ocr/tesseract/issues/1351

**Comment by stweil** [comment]
See https://groups.google.com/forum/#!topic/tesseract-dev/ZFn38UEOWM8 with a discussion to extend URL support to get traineddata models, too.

**Comment by stweil** [comment]
This pull request is superseded by #2210.

**Pull request closed without merging**
