### PR TITLE
[tensorflow] New fuzzing targets from core/kernels/fuzzing

### PR DESCRIPTION
**Pull request by kobrineli**
Hi! We added new targets for Tensorflow from `tensorflow/core/kernels/fuzzing`, which we tried to build earlier here tensorflow/tensorflow#55183, discussing it with @mihaimaruseac.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by SweetVishnya** [comment]
It seems that CI runners may run out of memory. Is there are a way to get more feedback from failed runners? How many cores does one runner have? Decreasing number of parallel building cores from nproc to some lower number can help.

**Comment by SweetVishnya** [comment]
> > It seems that CI runners may run out of memory. Is there are a way to get more feedback from failed runners? How many cores does one runner have? Decreasing number of parallel building cores from nproc to some lower number can help.
> 
> I think there are only two cores. We have limited control over the machines. If you have tested it locally and it works I will take your word for it. The actual builders we use are far beefier and lowering nproc will just slow those down.

Yeah, we tested it locally: docker image successfully builds, fuzzing starts with both corpus and dictionary, lcov coverage works.

**Comment by jonathanmetzman** [comment]
We use clang cov btw.

**Comment by SweetVishnya** [comment]
> We use clang cov btw.

My bad, I mean that I saw an html (generated via infra scripts) displaying appropriate coverage.

**Comment by mihaimaruseac** [comment]
We removed these from TF because of timeout issue and the fact that they were huge. We were planning a migration at the time, happy to see that they are back in!

**Pull request merged**
