### PR TITLE
[bignum-fuzzer] Update mpdecimal to version 2.5.1

### PR DESCRIPTION
**Pull request by skrah**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
CLA is complaining, could you sign it @skrah? Then I think we should be ready after that. The same applies here https://github.com/google/oss-fuzz/pull/5679

**Comment by skrah** [comment]
@DavidKorczynski I just signed using my gmail address from https://github.com/google/oss-fuzz/blob/master/projects/bignum-fuzzer/project.yaml and my GitHub user name.

The CLA bot seems unimpressed. :)  I thought the GitHub user name is sufficient, I don't use the gmail address for commits.

**Comment by skrah** [comment]
@googlebot I signed it!

**Comment by skrah** [comment]
Maybe that helps ...

**Comment by DavidKorczynski** [comment]
Looks like the signing worked!

**Comment by jonathanmetzman** [comment]
CC @skrah

**Comment by jonathanmetzman** [comment]
CC @guidovranken

**Comment by guidovranken** [comment]
The AFL build fails due to some Clang crash, probably the same issue as here: https://github.com/google/oss-fuzz/pull/5636#issuecomment-824782096

**Pull request merged**
