### PR TITLE
Redis

### PR DESCRIPTION
**Pull request by siscia**
First iteration for Redis.

At the moment most of the work is done in my own fork of Redis.

I want to make sure that this work is ok from the oss-fuzz point of view and that everything works fine.

I will follow up pointing to my PR to Redis itself. 

If my PR to Redis get accepted it will be necessary to change the repo from where I download the code pointing to the official repository.

### CODE REVIEW

**Comment by siscia** [comment]
Here the relative PR to redis: https://github.com/antirez/redis/pull/4232

**Comment by siscia** [comment]
I signed it!

**Comment by siscia** [comment]
CLA try again

**Comment by inferno-chromium** [comment]
@antirez - are you ok with fuzzing Redis as part of OSS-Fuzz, see our blog post here - https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html

@siscia - Thanks for creating this PR. We are happy to accept Redis, but please work with @antirez to get the fuzzer code in official repo and then modify current pull request to point to it. We can't accept code from personal repo.

**Comment by siscia** [comment]
Surely, I wait feedback from antirez in the other thread and I will mirror any important informqtion in this thread.

**Comment by oliverchang** [comment]
Has there been any updates here?

**Comment by siscia** [comment]
Not really, I will try to send a personal email to antirez.

I am sure he is very busy.

**Comment by antirez** [comment]
Sorry I'm not able to handle this, it would be great to receive a contribution in form of bug reports. Otherwise there is to understand first from people willing to do this, if there is any improvement compared to the fuzz testing we are already extensively doing in Redis via the API itself. After I would receive serious bug reports found with such techniques, I would surely consider to change Redis to make this process simpler. Thanks.

**Comment by siscia** [comment]
Makes perfect sense, thanks to express your concerns.

If it is of any interest I can try to provide a fork with my modification for integration with oss-fuzz.
The modifications on Redis are mostly on the main (server.c) and in the Makefile, also, those modifications are quite limited in space.
Moreover, Redis being a huge project, that makes of stability on of its pride point, moves quite slowly in terms of commits.
It seems a reasonable effort.

Let me know :)

**Comment by siscia** [comment]
@oliverchang , @inferno-chromium , 

Sorry, not sure if my English was understandable and if you saw my previous message :)

**Comment by inferno-chromium** [comment]
@siscia - sorry, missed your comment. 

Seeing @antirez response, it looks like we have to prove value of Oss-Fuzz first. Since the patches are simple, we can just keep them in oss-fuzz/projects/redis itself (like fuzz target, dictionary, etc) and then apply them as part of DockerFile. Once it starts finding bugs, it will provide value and then we can convince @antirez to upstream those fuzz target changes.

**Comment by Dor1s** [comment]
@siscia, do you have any plans on adding .diff files for you patches to oss-fuzz/projects/redis folder and applying them in build.sh file?

**Comment by siscia** [comment]
Wow you brings back so many memories, it seems like ages ago I was working on this project.

I need to check if I still have the source code somewhere, I guess it is the same linked above but I need to check and now I am from mobile.

There are still the money bounty for this project?

**Comment by Dor1s** [comment]
Yes, the reward program hasn't changed since then: https://opensource.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html

**Comment by Dor1s** [comment]
@siscia, are you still interested?

**Comment by siscia** [comment]
Hi,

No, without the financial incentives does not make sense for me to work on this.

Nor Google nor any body else is authorised to use my code for any purposes.

Thanks

**Comment by inferno-chromium** [comment]
@siscia - we do provide financial incentive for your efforts in OSS-Fuzz integration and improving the security and stability of your product for everyone else. Please see details here - https://security.googleblog.com/2017/05/oss-fuzz-five-months-later-and.html . Would really appreciate if you give it a chance, most integrations can be done in < 100 lines of code (and <1-2 days of max effort).

**Comment by siscia** [comment]
We already discussed some years ago and we are in a catch 22 like situation.

You guys demand that the code is merged into the main Redis branch (understandable) @antirez demands to show some results before to even think about merging the code into the main codebase (understandable).

Honestly without being sure that my efforts will be remunerate I won't work on it.

Especially since I am talking with Google that takes much more from the open source world that what gives back.

I am definitely not going to ask @antirez to easy his position. But I am definitely going to ask Google to do so.

You guys are really one of the very few companies that don't need neither engineering capabilities nor cheap work. Please do not demand it from open source developers.

And by the way this integration is quite complex...

**Comment by inferno-chromium** [comment]
@siscia - for initial integration, the fuzzer and build.sh can be in oss-fuzz repo. For main redis branch, that is only a later requirement when doing ideal integration. in most cases, we have seen that everyone likes the minimized crash reports on tip-of-tree trunk. I personally don't agree with your viewpoint about Google, so you are free to make this decision. All we ask is help scale the testing for better overall product. ~10K bug finds (https://bugs.chromium.org/p/oss-fuzz/issues/list?can=1&q=status%3AFixed%2CVerified+label%3AClusterFuzz&colspec=ID+Pri+M+Stars+ReleaseBlock+Component+Status+Owner+Summary+OS+Modified&x=m&y=releaseblock&cells=ids) speak about efforts we are trying to pursue and it can't scale if we try to do this ourselves (no one can write a better fuzz target than the developers who wrote the code or folks that understand this well).

**Pull request closed without merging**
