### PR TITLE
[pupnp] initial integration

### PR DESCRIPTION
**Pull request by 0x34d**
Hello, @mrjimenez
Any thoughts on PR?

Other harnesses are not included due to test failure of :
[test_UpnpHttpHeaderList.cpp](https://github.com/pupnp/pupnp/blob/branch-1.14.x/gtest/test_UpnpHttpHeaderList.cpp)
[test_upnpapi.cpp](https://github.com/pupnp/pupnp/blob/branch-1.14.x/gtest/test_upnpapi.cpp)

Signed-off-by: 0x34d <ajsinghyadav00@gmail.com>

### CODE REVIEW

**Comment by mrjimenez** [comment]
Hi Arjun,

I don't know if I can help with those tests, maybe @Vollstrecker can. We have started to add those tests, but I am not sure we have completed the work.

Anyway, shouldn't CheckXML() in FuzzIxml.c have its return value checked in LLVMFuzzerTestOneInput()?

Regards,
Marcelo.

**Comment by 0x34d** [comment]
> I don't know if I can help with those tests, maybe @Vollstrecker can. We have started to add those tests, but I am not sure we have completed the work.

It's alright.
When Mr. Vollstrecker fixes these tests, I will add them in the future.

> Anyway, shouldn't CheckXML() in FuzzIxml.c have its return value checked in LLVMFuzzerTestOneInput()?

Thanks, It's fixed now https://github.com/google/oss-fuzz/pull/8603/commits/fc67f17c3bac5a96a7be8697c265e61cc60cd180

**Comment by Vollstrecker** [comment]
I'm sorry but I don't even know what test you're talking about. I just made sure everything get's compiled and ist runable.

**Comment by Vollstrecker** [comment]
Now I remember. Iirc they where written by Ingo(?). But as they work in our env, this needs to bei checked. I never read these parts at all, just took his code and included it in the build, so as long as the problem isn't related to build and running them, I can't help.

**Comment by 0x34d** [comment]
Hello, Mr. Jimenez. 
After Working on 
- test_UpnpHttpHeaderList.cpp
- test_upnpapi.cpp

I believe they are not good harnesses at all. 
I'm dropping both files for now, and advocating for the merge.

**Comment by mrjimenez** [comment]
> Hello, Mr. Jimenez.  After Working on 

Hi @0x34d . No "Mister", please. The M and R in front of Jimenez are the first letters of my two first names :laughing: 

> * test_UpnpHttpHeaderList.cpp
> * test_upnpapi.cpp
> 
> I believe they are not good harnesses at all.  I'm dropping both files for now, and advocating for the merge.

I'm ok with that, thank you for your efforts!

Regards,
Marcelo.

**Comment by jonathanmetzman** [comment]
Who uses punp? Why is it critical software?

**Comment by Vollstrecker** [comment]
Have you ever checked what functionality is provided by this lib? Look at your PC, Smartphone or even SmartTV and see where this function could be used. And then go and search for alternatives to this lib.

Over the thumb: Many use this lib.

**Comment by jonathanmetzman** [comment]
>Have you ever checked what functionality is provided by this lib?

No. I work on OSS-Fuzz and I ask this question about every project. Some projects (e.g. Apache HTTPD) are so famous even ignorant people like me have heard of them :-) Others I haven't heard of and need to ask about.

> Look at your PC, Smartphone or even SmartTV and see where this function could be used

I see. I think this is enough info, let me ask the committe. If you can name any specific product that uses this it would help a lot.

**Comment by Vollstrecker** [comment]
> I see. I think this is enough info, let me ask the committe. If you can name any specific product that uses this it would help a lot.

Like always this is not really advertised. I remember a Trekstor media player that tells you in his help. But to name at least something (maybe not very well known): vlc uses it, see [here](https://github.com/videolan/vlc-3.0/blob/master/configure.ac#L4079)

**Comment by mrjimenez** [comment]
> > Have you ever checked what functionality is provided by this lib?
> 
> No. I work on OSS-Fuzz and I ask this question about every project. Some projects (e.g. Apache HTTPD) are so famous even ignorant people like me have heard of them :-) Others I haven't heard of and need to ask about.
> 
> > Look at your PC, Smartphone or even SmartTV and see where this function could be used
> 
> I see. I think this is enough info, let me ask the committe. If you can name any specific product that uses this it would help a lot.

Hi @jonathanmetzman ,

We have a [list here](https://pupnp.github.io/pupnp/) in the section `Other projects that are using the SDK`, but it is not up to date, since people rarely advertise the fact that their project uses it. On the open source domain, I think that the most known programs that use it are Gerbera and VLC.

Regards,
Marcelo.

**Comment by jonathanmetzman** [comment]
Thanks folks. Let's see what others say

**Review by jonathanmetzman — APPROVED** [review]
lgtm.
We approve of adding this project

**Pull request merged**
