### PR TITLE
[FFmpeg] Add small seed corpus for HEVC

### PR DESCRIPTION
**Pull request by michaelni**
Currently the HEVC coverage is relativly poor, this should improve it

Signed-off-by: Michael Niedermayer <michaelni@gmx.at>

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
It looks like there is an issue with no disk left on device when copying the fuzzers to `OUT`:
```
mv: error writing '/out/ffmpeg_dem_SER_fuzzer': No space left on device
Building fuzzers failed.
```
I think this is something that others have had troubles with lately as well e.g. 
- https://github.com/google/oss-fuzz/pull/5720
- https://github.com/google/oss-fuzz/issues/5729

Is there any way we can reduce the amount of disk copied to OUT?

**Comment by michaelni** [comment]
> It looks like there is an issue with no disk left on device when copying the fuzzers to `OUT`:
> 
> ```
> mv: error writing '/out/ffmpeg_dem_SER_fuzzer': No space left on device
> Building fuzzers failed.
> ```
> 
> I think this is something that others have had troubles with lately as well e.g.
> 
> * #5720
> * #5729
> 
> Is there any way you can reduce the amount of disk copied to OUT?

This failure seems to occur before anything this pull request changes. I belive the zip added later by the pull request is about 3.2mb.
We have 120gb of additional samples (not just hevc) in our archieve which may be of interrest as seeds if space was available and google wants us to add them.

**Comment by DavidKorczynski** [comment]
I see. I think the issue should only happen during the CI check. Could you try limiting the amount of fuzzers that you copy to $OUT during the CI check? See the bitcoin-core project for a reference - in that project the number of fuzzers that are copied to out is limited in the event of CIFuzz. The specific code check is right here:
https://github.com/google/oss-fuzz/blob/0da70e1c01e9f14d0792e0d7b64c433cdc2dbbaf/projects/bitcoin-core/build.sh#L52

**Comment by DavidKorczynski** [comment]
Now that https://github.com/google/oss-fuzz/pull/5741 has been merged, could you retrigger CI here? You have to do a noop commit for that to happen

**Comment by DavidKorczynski** [comment]
The CI passes now - thanks for your patience @michaelni

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
