### PR TITLE
Openssl update

### PR DESCRIPTION
**Pull request by kroeckx**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
LGTM, merged.

**Comment by kroeckx** [comment]
So $SRC wasn't correct ....

**Comment by inferno-chromium** [comment]
@mikea - actually this is pain, copy first to $SRC and then $SRC to $OUT.

**Comment by kroeckx** [comment]
The ubsan target doesn't seem to link.

**Comment by mikea** [comment]
@inferno-chromium yeah, unfortunately. You can use the glob or copy everything: `COPY . $SRC/`

**Pull request merged**
