### PR TITLE
Update centipede

### PR DESCRIPTION
**Pull request by Alan32Liu**
Update `Centipede` to check if we can remove the extra link flags, which have caused many build errors.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
Not sure if any upstream commits removed the requirement of `weak.o`, but this could be a good chance to test out a newer version of `Centipede`, since it is under active development.

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
OK, the build errors imply `weak.o` is still necessary.
Trying to update `Centipede` without other changes.

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer none --fuzzing-engine centipede

**Pull request merged**
