### PR TITLE
infra: bump fuzz-introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Two updates since last:
- Argument name extraction has improved for all functions, and it's added to `summary.json` files.
- All function names as they are in the binaries are saved. This has effect only for C++ where the underlying function name is a mangled function name. Having the raw makes it possible to e.g. demangle it and get a better-looking name than what currently exists in the reports.

### CODE REVIEW

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by DavidKorczynski** [comment]
Trial build is already done? Nice!

It would be great if this then could be merged as I think we can make it before the next cycle of base-builder builds

**Comment by oliverchang** [comment]
> Trial build is already done? Nice!
> 
> It would be great if this then could be merged as I think we can make it before the next cycle of base-builder builds

Trial build appears to have totally broken somehow :)

**Comment by DavidKorczynski** [comment]
> > Trial build is already done? Nice!
> > It would be great if this then could be merged as I think we can make it before the next cycle of base-builder builds
> 
> Trial build appears to have totally broken somehow :)

ah, only saw the all-checks passed -- was indeed surprised how fast it went. oh well!

**Comment by DavidKorczynski** [comment]
Seems like trial build was also skipped in https://github.com/google/oss-fuzz/pull/10772

**Comment by oliverchang** [comment]
Let's not block on the trial build breakage. I'll merge this for now, and we can handle any failures afterwards if there are any.

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
