### PR TITLE
Switch to using afl-clang-fast for afl++.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

Probably better to wait to land this since it affects every AFL build.

**Comment by inferno-chromium** [comment]
> LGTM
> 
> Probably better to wait to land this since it affects every AFL build.

Yes will do sunday night. Also, @vanhauser-thc as fyi.

**Comment by vanhauser-thc** [comment]
LGTM. this will give a performance improvement due direct map coverage (no call) and in-memory fuzz cases - and allow for enabling LAF, CMPLOG and/or DICT2FILE features in a future PR.

**Comment by evverx** [comment]
Looks like this PR broke the last two systemd builds somehow: https://github.com/google/oss-fuzz/pull/5084

**Pull request merged**
