### PR TITLE
capstone/keystone/unicorn: add to auto_ccs

### PR DESCRIPTION
**Pull request by StalkR**
Follow-up to #4451, I was just working on a couple reports for https://github.com/aquynh/capstone

 - https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=14912 fixed by aquynh/capstone#1684 & aquynh/capstone#1685

 - https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=22236 potential fix by aquynh/capstone#1687 & aquynh/capstone#1688

But I couldn't access the report because of permission denied:

> Detailed Report: https://oss-fuzz.com/testcase?key=5666610666012672

Adding to capstone but also related keystone/unicorn that I've been looking at.
I don't know what are the restrictions to be added to projects, so I'm trying this pull request.

Using my GSuite account (stalkr@stalkr.net), let's see if it works otherwise I also have a Gmail account (@gmail.com).

My Google CLA is up to date.

Thanks!

### CODE REVIEW

**Comment by inferno-chromium** [comment]
For getting access to keystone, unicorn, can you add the github id in a comment here and ask for permission. they just need to say yes.

**Comment by StalkR** [comment]
hey @aquynh would you allow me access to the oss-fuzz reports for capstone/unicorn/keystone? thanks!

(@aquynh is the main author and maintainer of the "Reversing Trilogy: Capstone (capstone-engine.org), Unicorn (unicorn-engine.org) & Keystone (keystone-engine.org)")

**Comment by jonathanmetzman** [comment]
Ping @aquynh. Are you fine with @StalkR having access to the bug reports for capstone, unicorn and keystone before they are public?

@StalkR if @aquynh doesn't respond in about a week I'll close this PR.

**Comment by aquynh** [comment]
very sorry that i missed this message!

yes, i am fine, please give him access.

Thanks,

**Review by jonathanmetzman — APPROVED** [review]

**Comment by StalkR** [comment]
Thanks!

**Pull request merged**
