### PR TITLE
Golang coverage improvements

### PR DESCRIPTION
**Pull request by catenacyber**
cc @inferno-chromium 

- One fix (did not break the projects already there but broke go-ethereum which had a package named bus in a directory named bls1321)
- One improvement to get the report over all the repository (and not restricted to the subdirectory/package where the target resides)

This should be tested as it concerns all golang projects

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]
Can you try
python infra/helper.py build_image base-builder
followed by building a few golang projects and see if this works.
Once you confirm, then will merge.

**Comment by jonathanmetzman** [comment]
> Can you try
> python infra/helper.py build_image base-builder
> followed by building a few golang projects and see if this works.
> Once you confirm, then will merge.

I think CI will do this for you if you just modify some golang projects in this PR and push.
(undo the modification after doing this).

**Comment by inferno-chromium** [comment]
> > Can you try
> > python infra/helper.py build_image base-builder
> > followed by building a few golang projects and see if this works.
> > Once you confirm, then will merge.
> 
> I think CI will do this for you if you just modify some golang projects in this PR and push.
> (undo the modification after doing this).

Was there some bug that if you modify something in infra/, we just build base images, but skip building projects, probably need to fix that.

**Comment by catenacyber** [comment]
> Can you try
python infra/helper.py build_image base-builder
followed by building a few golang projects and see if this works.
Once you confirm, then will merge.

Ok, will do.

**Comment by jonathanmetzman** [comment]
> > > Can you try
> > > python infra/helper.py build_image base-builder
> > > followed by building a few golang projects and see if this works.
> > > Once you confirm, then will merge.
> > 
> > 
> > I think CI will do this for you if you just modify some golang projects in this PR and push.
> > (undo the modification after doing this).
> 
> Was there some bug that if you modify something in infra/, we just build base images, but skip building projects, probably need to fix that.

I don't think so.

**Comment by inferno-chromium** [comment]
> > > > Can you try
> > > > python infra/helper.py build_image base-builder
> > > > followed by building a few golang projects and see if this works.
> > > > Once you confirm, then will merge.
> > > 
> > > 
> > > I think CI will do this for you if you just modify some golang projects in this PR and push.
> > > (undo the modification after doing this).
> > 
> > 
> > Was there some bug that if you modify something in infra/, we just build base images, but skip building projects, probably need to fix that.
> 
> I don't think so. I'm almost certain it doesn't entirely skip building projects, since I'm pretty sure it will always rebuild skcms. but hopefully it will rebuild the modified projects as well.

@jonathanmetzman - Here is the code - https://github.com/google/oss-fuzz/blob/a23d9bc6fb84a5607f8aff8e3261e999b50c62d6/infra/ci/build.py#L242
if something in infra is modified, it just return on its result, it does not proceed with build_modified_projects step, probably needs fixing ?

**Comment by catenacyber** [comment]
Seems to work on go-coredns and gonids
```
python infra/helper.py build_image base-builder
python infra/helper.py build_fuzzers --sanitizer=coverage gonids
python infra/helper.py coverage --corpus-dir /path/to/some --fuzz-target fuzz_parserule
```

**Comment by inferno-chromium** [comment]
> Seems to work on go-coredns and gonids
> 
> ```
> python infra/helper.py build_image base-builder
> python infra/helper.py build_fuzzers --sanitizer=coverage gonids
> python infra/helper.py coverage --corpus-dir /path/to/some --fuzz-target fuzz_parserule
> ```

Merging then. Please keep an eye tomorrow on some go projects build results.

**Comment by catenacyber** [comment]
Looks good so far in https://oss-fuzz-build-logs.storage.googleapis.com/index.htm

**Pull request merged**
