### PR TITLE
Add myself to the list of auto CCs for libyaml

### PR DESCRIPTION
**Pull request by sigmavirus24**
As the lead maintainer of libyaml, it would be helpful to get CC'd on
any findings of OSS Fuzz.

### CODE REVIEW

**Comment by sigmavirus24** [comment]
cc @alex

**Comment by sigmavirus24** [comment]
I signed it!

**Comment by inferno-chromium** [comment]
@sigmavirus24 - happy to add you, but i think you should switch the values between primary_contact and auto_ccs. i think you should be the primary and @alex should the auto_cc.

**Comment by sigmavirus24** [comment]
@alex thoughts? I'm fine either way.

**Comment by alex** [comment]
sgtm

**Comment by inferno-chromium** [comment]
Ok flipped the order and merged.

**Pull request merged**
