### PR TITLE
Add sean@compactcloud.co.uk to urllib3 project.yaml

### PR DESCRIPTION
**Pull request by sethmlarson**
cc @DavidKorczynski @sg3-141-592

### CODE REVIEW

**Review by DavidKorczynski — COMMENTED** [review]
LGTM, please sign the CLA and we can merge this

**Comment by sethmlarson** [comment]
I've signed it with my Github account and refreshed, is there anything else I need to do?

**Comment by DavidKorczynski** [comment]
Just to confirm, did you sign the CLA with your email `seth.....@gmail.com` which made the commit or the email you put in `project.yaml`?

**Comment by sethmlarson** [comment]
I wonder if the commit is using the `sethmlarson@users.noreply.github.com` email since I used the GitHub UI, I assumed because it asked for my GitHub username that that would be okay? Maybe I need to recreate this branch with my normal git flow.

**Comment by sethmlarson** [comment]
@DavidKorczynski Now the CLA is registering as green.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
FYI: to see the detailed bug reports the email in the `project.yaml` needs to be affiliated with a Google account (as the primary email) due to how the authentication is implemented.

**Pull request merged**
