### PR TITLE
Clean up build infra issues.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
0. Don't clone fuzz-introspector to /src since it breaks builds.
1. Install packages in python install script properly. Previously
pip install atheris>=2.0.6 was interpreted as "redirect the output
from pip install atheris" to the file "=2.0.6".
3. Clean up some miscellanious issues.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I assume this will break fuzz-introspector somewhere, but I'm not sure where. It should be easy to fix though and I don't think we need to block this PR on adjusting that code since FI isn't production code yet.

**Review by DavidKorczynski — COMMENTED** [review]
Am not sure if I missed something, but where is the change that causes fuzz-introspector not to cloned in /src (change num 0 you mention)? I can't spot the diff that causes this?

**Comment by jonathanmetzman** [comment]
> Am not sure if I missed something, but where is the change that causes fuzz-introspector not to cloned in /src (change num 0 you mention)? I can't spot the diff that causes this?

You're not missing anything. I am :facepalm: I forgot to include it.
Fixed!

**Review by DavidKorczynski — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
> > Am not sure if I missed something, but where is the change that causes fuzz-introspector not to cloned in /src (change num 0 you mention)? I can't spot the diff that causes this?
> 
> You're not missing anything. I am facepalm I forgot to include it. Fixed!

ah cool! lgtm!

**Comment by jonathanmetzman** [comment]
Hmm...maybe I'll rewrite this to only include the introspector removal so we don't break anything.
Kinda torn about merging this now. On the one hand: build fixes good, on the other: patches before the weekend bad

**Comment by oliverchang** [comment]
Thanks @jonathanmetzman ! Let's try this.

**Pull request merged**
