### PR TITLE
[libxml2] Add hash-based combination of flags as an "options" argument.

### PR DESCRIPTION
**Pull request by Dor1s**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
LGTM.

**Comment by kcc** [comment]
I kind-of deliberately did not do it because there are tons of known problems with libxml2 when some of the flags are used (including e.g. doing network access, which under some flags is not actually a bug).
But ok, let's see how this goes. 

@vitalybuka FYI, you may want to steal parts of this fuzz target (xmlSaveDoc) for the one using protos.

**Comment by Dor1s** [comment]
@kcc, +1 to your concern. I've been thinking that I had to always nullify some `options` bits after hash calculation, but I haven't seen any really annoying stuff so far.

One more point: since libxml2 maintainers are not updating the target, we can do anything we want, file bugs, and only then disable some flags based on feedback from the upstream :)

**Comment by kcc** [comment]
https://github.com/google/libprotobuf-mutator/blob/master/examples/libxml2/libxml2_example.cc#L46 has the flags that @vitalybuka found annoying.  But your plan SGTM too.

**Pull request merged**
