### PR TITLE
infra/rust/coverage: copy right toolchain sources

### PR DESCRIPTION
**Pull request by catenacyber**
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=65817

### CODE REVIEW

**Comment by catenacyber** [comment]
@DonggeLiu could this be taken in to fix suricata fuzzing coverage ? (and maybe other rust projects using a custom toolchain)

**Comment by DonggeLiu** [comment]
Requesting help from @jonathanmetzman : )

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py rust --fuzzing-engines libfuzzer --sanitizers address

**Review by jonathanmetzman — APPROVED** [review]
LGTM if testing passes.

**Comment by catenacyber** [comment]
So, gcb says this fixes suricata but breaks surrealdb

Looking into it

**Comment by catenacyber** [comment]
Got the fix easy.
`oak` is the other project using a custom rust version

**Comment by catenacyber** [comment]
friendly ping @jonathanmetzman as ClusterFuzz-External reminds me that suricata Coverage build is still failing ;-)

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py rust --fuzzing-engines libfuzzer --sanitizers address

**Comment by catenacyber** [comment]
trial build all green :-)

**Comment by DonggeLiu** [comment]
@jonathanmetzman is the CFLite failure related/expected to this PR?

**Comment by catenacyber** [comment]
@DonggeLiu this PR does not change anything for python ;-)

**Pull request merged**
