### PR TITLE
[Infra] base-images: do build `openmp` runtime too

### PR DESCRIPTION
**Pull request by LebedevRI**
I'm guessing this needs tests?

See https://github.com/google/oss-fuzz/issues/11547
X-Ref: https://github.com/darktable-org/rawspeed/pull/631

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py librawspeed --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
OK. Let's make sure it doesn't break anything, and I'll add it. I can't say I fully understand why this library is part of the compiler though.

**Comment by LebedevRI** [comment]
> /gcbrun trial_build.py librawspeed --sanitizer address --fuzzing-engine libfuzzer

Note that https://github.com/darktable-org/rawspeed/pull/631 is needed to actually check that it works.
I **DON'T** know this works, but it should since it works outside of oss-fuzz.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman thank you for looking into this! Would it be helpful if i merge the "prepreq" change on my side and this PR's checks are re-run? Or is the fact that the build of this PR did not fail is good enough to start with?

Yeah if you can that would help!

**Comment by LebedevRI** [comment]
Merged

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py librawspeed --sanitizer address --fuzzing-engine libfuzzer

**Comment by LebedevRI** [comment]
https://oss-fuzz-gcb-logs.storage.googleapis.com/log-0e3c9ed4-b7e3-4624-b177-0f503ec32491.txt
```
Step #19 - "compile-libfuzzer-address-x86_64": -- Looking for OpenMP
Step #19 - "compile-libfuzzer-address-x86_64": -- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0") 
Step #19 - "compile-libfuzzer-address-x86_64": -- Found OpenMP: TRUE (found version "5.0")  
Step #19 - "compile-libfuzzer-address-x86_64": -- Looking for OpenMP - found (system)
```
so it at least built successfully.

**Comment by LebedevRI** [comment]
@jonathanmetzman is this sufficient evidence to get this merged? thanks!

**Comment by LebedevRI** [comment]
(If this isn't merged in next ~6 hours i'll have to revert https://github.com/darktable-org/rawspeed/pull/631 since both my CI and oss-fuzz's librawspeed build are broken.)

**Comment by jonathanmetzman** [comment]
Ah sorry. Let me just test that it doesn't break other projects please.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py c c++ --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
I'll merge it in five hours after a sufficient number of projects complete.

**Comment by LebedevRI** [comment]
Sure, by all means!
Thank you for taking a look!

**Comment by jonathanmetzman** [comment]
Sorry, I probably won't merge this right now since there's a few projects failing with this message which I think this change is responsible for.


```
Step #19 - "compile-libfuzzer-address-x86_64": clang-15: error: linker command failed with exit code 1 (use -v to see invocation)
Step #19 - "compile-libfuzzer-address-x86_64": /usr/bin/ld: xtrans_demosaic.cpp:(.text..omp_outlined.[.omp_outlined.]+0x4c5b): undefined reference to `__kmpc_dispatch_next_4u'
Step #19 - "compile-libfuzzer-address-x86_64": /usr/bin/ld: xtrans_demosaic.cpp:(.text..omp_outlined.[.omp_outlined.]+0x5f1): undefined reference to `omp_get_thread_num'
Step #19 - "compile-libfuzzer-address-x86_64": /usr/bin/ld: xtrans_demosaic.cpp:(.text..omp_outlined.[.omp_outlined.]+0x38e): undefined reference to `__kmpc_dispatch_next_4u'
Step #19 - "compile-libfuzzer-address-x86_64": xtrans_demosaic.cpp:(.text..omp_outlined.[.omp_outlined.]+0x2ed): undefined reference to `__kmpc_dispatch_init_4u'
```


Weirdly, libraw is failing with the attatched message. But yesterday it passed. Did you revert the change already.

[libraw.txt](https://github.com/google/oss-fuzz/files/14131851/libraw.txt)

Is there some flag we can add to fix all the other projects?

**Comment by LebedevRI** [comment]
libraw != librawspeed

**Comment by LebedevRI** [comment]
@LebedevRI pushed a commit to this PR which will fix the failure.
Are there other failed projects?

**Comment by LebedevRI** [comment]
> [](https://github.com/google/oss-fuzz/files/14131851/libraw.txt)
> 
> Is there some flag we can add to fix all the other projects?

It is fundamentally impossible to do that.
Each project just needs to pass an option to it's buildsystem to explicitly disable OpenMP.
If you can give me a list, i could do that, but it's the same thing as updating a compiler in the base-image,
each project should ideally just handle their part of the problem.

**Comment by jonathanmetzman** [comment]
> > Is there some flag we can add to fix all the other projects?
> 
> It is fundamentally impossible to do that. Each project just needs to pass an option to it's buildsystem to explicitly disable OpenMP. If you can give me a list, i could do that, but it's the same thing as updating a compiler in the base-image, each project should ideally just handle their part of the problem.

hmmm...Maybe i'll ask some teammates about this. My first thought is I'd rather not do a change that breaks more projects (even if it can be fixed) than it helps.

**Comment by LebedevRI** [comment]
Once again, do you have a complete list of the failed projects?

**Comment by jonathanmetzman** [comment]
tesseract-ocr
libraw
kimageformats
imagemagick

**Comment by LebedevRI** [comment]
That's it? just 3? :) Let me take a look.

**Comment by jonathanmetzman** [comment]
Based on these numbers there's a ~1-2% chance any new projects are affected by this change. I guess that's maybe not worth worrying about.
My main concern isn't these projects which we can change to opt-out. It's new projects. I don't want to make integration harder for them.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py swift python jvm rust go javascript --sanitizer none address --fuzzing-engine libfuzzer

**Comment by LebedevRI** [comment]
- [*] tesseract-ocr https://github.com/tesseract-ocr/tesseract/pull/4186
- [*] libraw (in this PR)
- [ ] kimageformats
- [ ] imagemagick

**Comment by jonathanmetzman** [comment]
I'll test the non-C/C++ projects in case they have issues too.

**Comment by jonathanmetzman** [comment]
I don't think I'll make the 5.5 hour deadline unfortunately

**Comment by LebedevRI** [comment]
@jonathanmetzman 
Hm actually, wait. I think i'm rushing things. Let's try another approach first,
let's just not build libomptarget, only libomp.

Could you please kill all build jobs and try again?

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman Hm actually, wait. I think i'm rushing things. Let's try another approach first, let's just not build libomptarget, only libomp.
> 
> Could you please kill all build jobs and try again?

Killed.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py c c++ swift python jvm rust go javascript --sanitizer none address --fuzzing-engine libfuzzer

**Comment by LebedevRI** [comment]
And an orthogonal question, just so it was considered when it comes back later:
for the projects that don't explicitly opt-out, and thus will now implicitly opt-in,
this may result in them using parallelizm internally.
How bad would that be, from oss-fuzz's point of view?

Might it be a good idea to add
```
export OMP_NUM_THREADS=1
export OMP_THREAD_LIMIT=1
```
somewhere in `google/clusterfuzz` to generally force them to use a single thread?

**Comment by LebedevRI** [comment]
Ok, i've workarounded this stuck PR by just building libomp as part of my build.
It's super, err, non-glamour, but it seems to work.
And cifuzz already found an issue: https://github.com/darktable-org/rawspeed/pull/640/commits/bd605541db9df3c75338dad5b34f18ee0d6d1db5

I'm worried that oss-fuzz is stuck at LLVM15,
and i suspect that i might need to patch libomp,
so for now, i'll just drop this PR i guess.

Thank you, and sorry for the noise!

**Pull request closed without merging**
