### PR TITLE
Port sqlite3 fuzzer

### PR DESCRIPTION
**Pull request by tanin47**
- It needs fossil. Therefore, the build.sh looks weird.
- I can't make sqlite3.a. So, I use sqlite3.o. I have no idea how they are different. (Not a C++ person here.)

### CODE REVIEW

**Comment by tanin47** [comment]
I signed it!

**Comment by Dor1s** [comment]
Verified locally, it works. Also it's worth to add a dictionary. I'll add it.

**Comment by oliverchang** [comment]
I was actually waiting to merge this because I knew that it wouldn't actually work on our builder, but should be fine to keep it checked in for now.

**Comment by Dor1s** [comment]
I didn't know that, sorry! :)
Let's post comments for other pull requests, if there are any blockers for merging.

**Pull request merged**
