### PR TITLE
Adds target for pyyaml project

### PR DESCRIPTION
**Pull request by catenacyber**
cc @DavidKorczynski

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM
Will merge if  @DavidKorczynski approves.

**Comment by DavidKorczynski** [comment]
Looks good @jonathanmetzman 

Thanks @catenacyber

**Comment by catenacyber** [comment]
By the way, should I have added myself in auto_ccs ?

**Comment by inferno-chromium** [comment]
> By the way, should I have added myself in auto_ccs ?

yes please do, so you can see any immediate fuzzer issues or build failures, etc.

**Comment by catenacyber** [comment]
Asked in https://github.com/google/oss-fuzz/pull/4949

**Pull request merged**
