### PR TITLE
ngolo-fuzzing: fuzz golang x packages

### PR DESCRIPTION
**Pull request by catenacyber**
cc @AdamKorcz for the latest x/text CVE ;-)

### CODE REVIEW

**Comment by catenacyber** [comment]
Is there a limit for the number of fuzz targets per project ?

Cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52488

It looks like the targets get built but not run...

**Comment by jonathanmetzman** [comment]
> Is there a limit for the number of fuzz targets per project ?
> 
> Cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52488
> 
> It looks like the targets get built but not run...

I don't think so.

**Comment by catenacyber** [comment]
Maybe it was happening about the same time as what should be fixed by https://github.com/google/oss-fuzz/pull/8916

**Comment by catenacyber** [comment]
@jonathanmetzman do you know why there is not any stats for https://oss-fuzz.com/fuzzer-stats?project=ngolo-fuzzing&fuzzer=libFuzzer&job=libfuzzer_asan_ngolo-fuzzing&group_by=by-fuzzer (404 error) when the build looks fine cf https://oss-fuzz-build-logs.storage.googleapis.com/index.html#ngolo-fuzzing ?

Should I revert this ? Or split into 2 projects ngolo_x and ngolo_std ?

**Comment by catenacyber** [comment]
Build takes too much disk space ? Or running  (and corpora) ?

**Comment by jonathanmetzman** [comment]
The build

**Pull request merged**
