### PR TITLE
Add base-builder-go-codeintelligencetesting for 15 go projects

### PR DESCRIPTION
**Pull request by 0roman**

### CODE REVIEW

**Comment by 0roman** [comment]
https://github.com/google/oss-fuzz/issues/7164

**Comment by DavidKorczynski** [comment]
On these projects will the change have potential impact on stability, e.g. should we be ready for potential disturbances in the form of build failures or false positives?

**Comment by 0roman** [comment]
> On these projects will the change have potential impact on stability, e.g. should we be ready for potential disturbances in the form of build failures or false positives?

We have already tested the go-instrumentation improvements with most of the oss-fuzz projects in a case study and we did not observed any impact on stability such as false positives. Any Build Failure will be resolved before Merge.

**Comment by DavidKorczynski** [comment]
> We have already tested the go-instrumentation improvements with most of the oss-fuzz projects in a case study and we did not observed any impact on stability such as false positives. Any Build Failure will be resolved before Merge.

perfect, thanks!

**Comment by 0roman** [comment]
@oliverchang how should I fix "No space left on device" Error?

**Comment by oliverchang** [comment]
> @oliverchang how should I fix "No space left on device" Error?

Looks like the failure is istio, which is rather large -- @DavidKorczynski @AdamKorcz have you seen our CI fail on trying to build istio in the past?

**Comment by AdamKorcz** [comment]
> > @oliverchang how should I fix "No space left on device" Error?
> 
> Looks like the failure is istio, which is rather large -- @DavidKorczynski @AdamKorcz have you seen our CI fail on trying to build istio in the past?

Yes: https://github.com/google/oss-fuzz/issues/6857 - The solution was to increase disk space.

**Comment by DavidKorczynski** [comment]
> 
> Yes: #6857 - The solution was to increase disk space.

We could make the CI work by reducing the number of fuzzers the CI builds using this approach https://github.com/google/oss-fuzz/blob/4c109322213e64ab5f09a6d0f1ae39c56b6f0ad2/projects/binutils/build.sh#L52

**Comment by AdamKorcz** [comment]
Should be fixed with https://github.com/google/oss-fuzz/pull/7349 using @DavidKorczynski 's suggestion. Try and run CI again.

**Review by oliverchang — APPROVED** [review]
Looks good to go!

**Comment by oliverchang** [comment]
And thanks a lot @AdamKorcz for adding the CI workaround :)

**Pull request merged**
