### PR TITLE
[CIFuzz] Note which languages are supported

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Related #5195

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]
I am very sad to see this, we need to support python, rust and others, those run like libfuzzer targets. is that feasible, need to get some help.

**Comment by jonathanmetzman** [comment]
> I am very sad to see this, we need to support python, rust and others, those run like libfuzzer targets. is that feasible, need to get some help.

It probably is pretty easy to support this. Probably only need to get language instead of hardcoding. But I don't have time to test right now (I think actually go and rust targets might work currently since compiling these fuzzers with LANGUAGE=c++ works fine.

**Comment by jonathanmetzman** [comment]
> I am very sad to see this, we need to support python, rust and others, those run like libfuzzer targets. is that feasible, need to get some help.

Frankly, I think the language attribute in project.yaml was not well thought out. It's bad that builds rely on a yaml attribute despite the fact that helper.py doesn't understand yaml and needs to use regex to do so.
This also annoying to support for non-OSS-Fuzz users, since helper.py won't be able to get the language in the same way for them.
I'm not sure if I want this mess in CIFuzz. I might force non-C++ projects to do `ENV LANGUAGE python`.

**Comment by inferno-chromium** [comment]
> > I am very sad to see this, we need to support python, rust and others, those run like libfuzzer targets. is that feasible, need to get some help.
> 
> Frankly, I think the language attribute in project.yaml was not well thought out. It's bad that builds rely on a yaml attribute despite the fact that helper.py doesn't understand yaml and needs to use regex to do so.
> This also annoying to support for non-OSS-Fuzz users, since helper.py won't be able to get the language in the same way for them.
> I'm not sure if I want this mess in CIFuzz. I might force non-C++ projects to do `ENV LANGUAGE python`.

Why can't CIFuzz action install pyyaml ? how do we parse sanitizers and other attributes ?

**Comment by jonathanmetzman** [comment]
> > > I am very sad to see this, we need to support python, rust and others, those run like libfuzzer targets. is that feasible, need to get some help.
> > 
> > 
> > Frankly, I think the language attribute in project.yaml was not well thought out. It's bad that builds rely on a yaml attribute despite the fact that helper.py doesn't understand yaml and needs to use regex to do so.
> > This also annoying to support for non-OSS-Fuzz users, since helper.py won't be able to get the language in the same way for them.
> > I'm not sure if I want this mess in CIFuzz. I might force non-C++ projects to do `ENV LANGUAGE python`.
> 
> Why can't CIFuzz action install pyyaml ? how do we parse sanitizers and other attributes ?

CIFuzz can install pyyaml, but this means there's another way we are grabbing this.
We don't parse sanitizers in CIFuzz, we get them from env vars. I may just make people do this, I don't want to use project.yaml as another input for CIFuzz.

**Pull request merged**
