### PR TITLE
lua: introduce fuzz introspector config

### PR DESCRIPTION
**Pull request by ligurio**
Follows up #10931

### CODE REVIEW

**Comment by ligurio** [comment]
@DavidKorczynski David, could you review introduced config?
The idea is to exclude libprotobuf-mutator and protobuf sources from  Fuzz Introspector report (https://storage.googleapis.com/oss-fuzz-introspector/lua/inspector-report/20230925/fuzz_report.html#Fuzzer:-luaL_loadbuffer_proto_test)

**Comment by DavidKorczynski** [comment]
I ran it locally and this is the result (see the number of functions at the button) Screenshot from 2023-09-29 11-28-31

Looks good?

**Comment by ligurio** [comment]
Seems looks correct. The current number of functions is 9,022.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by ligurio** [comment]
After merging Fuzz Introspector config all tests except `fuzz_lua` has been removed from Fuzz Introspector report, see https://storage.googleapis.com/oss-fuzz-introspector/lua/inspector-report/20230930/fuzz_report.html
Seems removing `testdir/tests` with test's source code was superfluous.

**Pull request merged**
