### PR TITLE
Add a better check for crash during bisection.

### PR DESCRIPTION
**Pull request by oliverchang**
Return codes are not reliable.

### CODE REVIEW

**Comment by oliverchang** [comment]
TBR to get some early results.

**Comment by jonathanmetzman** [comment]
LGTM.
Do you think if we are not doing this in CIFuzz we should be? Maybe I'll factor this out into an error detection library and use it there too.

**Comment by oliverchang** [comment]
> LGTM.
> Do you think if we are not doing this in CIFuzz we should be? Maybe I'll factor this out into an error detection library and use it there too.

I think so. Before this we were considering missing fuzzers and ASan crashes to be the same.

**Comment by jonathanmetzman** [comment]
Ah, I would guess we don't have the missing fuzzers problem in CIFuzz though

**Pull request merged**
