### PR TITLE
Jazzer Pro

### PR DESCRIPTION
**Pull request by kyakdan**

### CODE REVIEW

**Comment by kyakdan** [comment]
@oliverchang The infra test fails with the following error: `Executing command "git fetch origin refs/pull/3415/merge" failed with error: fatal: couldn't find remote ref refs/pull/3415/merge`. Can it be because #3415 is closed?

**Comment by oliverchang** [comment]
> @oliverchang The infra test fails with the following error: `Executing command "git fetch origin refs/pull/3415/merge" failed with error: fatal: couldn't find remote ref refs/pull/3415/merge`. Can it be because #3415 is closed?

Yep, just reopened it!

**Comment by oliverchang** [comment]
@kyakdan can you please check if any of the failures [here](https://github.com/google/oss-fuzz/pull/12375/checks?check_run_id=28993783532) look related to this change?

```
Step #1: INFO:root:apache-felix-dev, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-3bbccbd9-eb73-46fc-98d6-49d1e6a4007a.txt
Step #1: INFO:root:apache-felix-dev, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-22d739e8-703b-4ffc-8687-e58bf429a4fe.txt
Step #1: INFO:root:apache-felix-dev, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-e3974415-d6e1-41c7-9e17-63ba7cfc7f54.txt
Step #1: INFO:root:cglib, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-d10e317c-f49b-4339-b027-0a295c365e35.txt
Step #1: INFO:root:dom4j, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-c1c9cb98-0246-42e4-a703-12055e489b3b.txt
Step #1: INFO:root:dom4j, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-36008d18-c8a1-43a4-8838-c4e70571e387.txt
Step #1: INFO:root:dom4j, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-67c54ec6-53a7-44b0-9e14-f098464f00aa.txt
Step #1: INFO:root:java-jwt, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-61da3836-3539-41c5-aef3-9e9c54e30222.txt
Step #1: INFO:root:java-jwt, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-1f835ec4-6e27-4d64-992b-6de03aa4e78b.txt
Step #1: INFO:root:java-jwt, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-9d74eb1c-9ce2-4fbe-8b05-107bbea2e4a8.txt
Step #1: INFO:root:kryo, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-9edf91ef-ee64-45e8-8636-529ff1f77d44.txt
Step #1: INFO:root:kryo, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-f43f4274-08fb-444f-9466-6355e2b410b4.txt
Step #1: INFO:root:kryo, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-d9fa3c6b-7740-4850-83ab-5cb35611c953.txt
Step #1: INFO:root:ohc, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-2f89044e-632e-42ce-a9a3-7693bf59f9b6.txt
Step #1: INFO:root:xstream, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-e19bdebd-8dbf-464f-b568-79dfa1c852bf.txt
Step #1: INFO:root:xstream, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-f82bdf1f-f183-4b5b-a447-d97dbc1d953f.txt
Step #1: INFO:root:xstream, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-da849015-523e-4092-b376-ee9079a0723b.txt
Step #1: INFO:root:hive, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-f92bf72d-c82c-4c48-8248-f8ab8ec692c6.txt
Step #1: INFO:root:arrow-java, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-a9d4fe6c-81d1-4d50-ad79-e59b5cc01ae5.txt
```

**Comment by kyakdan** [comment]
@oliverchang Yes. These projects need to be built (and some of them also run) with Java versions prior to Java 17. However, Java 17 is needed to use some of the features in Jazzer's new mutation framework. I adjusted these projects to be built and run with the changes introduced in this PR.

> @kyakdan can you please check if any of the failures [here](https://github.com/google/oss-fuzz/pull/12375/checks?check_run_id=28993783532) look related to this change?
> 
> ```
> Step #1: INFO:root:apache-felix-dev, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-3bbccbd9-eb73-46fc-98d6-49d1e6a4007a.txt
> Step #1: INFO:root:apache-felix-dev, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-22d739e8-703b-4ffc-8687-e58bf429a4fe.txt
> Step #1: INFO:root:apache-felix-dev, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-e3974415-d6e1-41c7-9e17-63ba7cfc7f54.txt
> Step #1: INFO:root:cglib, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-d10e317c-f49b-4339-b027-0a295c365e35.txt
> Step #1: INFO:root:dom4j, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-c1c9cb98-0246-42e4-a703-12055e489b3b.txt
> Step #1: INFO:root:dom4j, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-36008d18-c8a1-43a4-8838-c4e70571e387.txt
> Step #1: INFO:root:dom4j, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-67c54ec6-53a7-44b0-9e14-f098464f00aa.txt
> Step #1: INFO:root:java-jwt, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-61da3836-3539-41c5-aef3-9e9c54e30222.txt
> Step #1: INFO:root:java-jwt, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-1f835ec4-6e27-4d64-992b-6de03aa4e78b.txt
> Step #1: INFO:root:java-jwt, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-9d74eb1c-9ce2-4fbe-8b05-107bbea2e4a8.txt
> Step #1: INFO:root:kryo, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-9edf91ef-ee64-45e8-8636-529ff1f77d44.txt
> Step #1: INFO:root:kryo, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-f43f4274-08fb-444f-9466-6355e2b410b4.txt
> Step #1: INFO:root:kryo, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-d9fa3c6b-7740-4850-83ab-5cb35611c953.txt
> Step #1: INFO:root:ohc, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-2f89044e-632e-42ce-a9a3-7693bf59f9b6.txt
> Step #1: INFO:root:xstream, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-e19bdebd-8dbf-464f-b568-79dfa1c852bf.txt
> Step #1: INFO:root:xstream, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-f82bdf1f-f183-4b5b-a447-d97dbc1d953f.txt
> Step #1: INFO:root:xstream, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-da849015-523e-4092-b376-ee9079a0723b.txt
> Step #1: INFO:root:hive, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-f92bf72d-c82c-4c48-8248-f8ab8ec692c6.txt
> Step #1: INFO:root:arrow-java, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-a9d4fe6c-81d1-4d50-ad79-e59b5cc01ae5.txt
> ```

**Comment by oliverchang** [comment]
Thanks!

**Review by oliverchang — APPROVED** [review]

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
