### PR TITLE
spring-security: initial integration spring-security-oauth2-jose

### PR DESCRIPTION
**Pull request by JTrossen**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Is this actually an "initial integration" or is this named wrong? I think I'm missing something.

**Comment by JTrossen** [comment]
It is an initial integration.

**Comment by jonathanmetzman** [comment]
> It is an initial integration.

But projects/spring-security already exists and is fuzzed on oss-fuzz

**Comment by jonathanmetzman** [comment]
This might be semantics but for us it can't be an "initial integration" unless something new is being cloned or a new directory in projects/ is being made.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
> This might be semantics but for us it can't be an "initial integration" unless something new is being cloned or a new directory in projects/ is being made.

Please use this convention, it will make your PRs faster to merge.

**Pull request merged**
