### PR TITLE
[pjsip] initial integration

### PR DESCRIPTION
**Pull request by 0x34d**
@ismangil @trengginas @bennylp @sauwming @nanangizz 

- Thoughts on integration (can pjsip team fix security issues reported by oss-fuzz)?
- Review the harness code.

 

Signed-off-by: 0x34d <ajsinghyadav00@gmail.com>

### CODE REVIEW

**Comment by sauwming** [comment]
Thank you for your contribution.

Currently we're preparing for release 2.13, so we can only revisit the integration discussion after that, probably December at the earliest.

As for the security issues, yes, we will fix them and we have also fixed a number of such issues reported by various fuzzing tests in the past, which can be seen here: https://github.com/pjsip/pjproject/security/advisories

So if there are any new issues, please don't hesitate to contact us. Thank you in advance.

**Comment by Alan32Liu** [comment]
> Currently we're preparing for release 2.13, so we can only revisit the integration discussion after that, probably December at the earliest.

Shall we merge this after releasing 2.13 and re-discuss integration?

**Comment by sauwming** [comment]
Right, I will bring up the idea of integrating the fuzzer into pjsip codebase in our team meeting post release.

**Comment by 0x34d** [comment]
@Alan32Liu @sauwming  Ping

**Comment by sauwming** [comment]
Thanks for reminding us.

Yes, we'd be glad to use oss-fuzz in our project.
But will it possible for you to create a PR in our repo and move the fuzz target code into `tests/fuzz` directory? Since this seems to have some advantages such as:
- you can use our build's config, so you can take advantage of the compilation flags and the library names, instead of hardcoded ones
- it allows us to easily add more tests in the future, such as DNS and RTCP.

**Comment by 0x34d** [comment]
> But will it possible for you to create a PR in our repo and move the fuzz target code into `tests/fuzz` directory? 

Alright, Give me 1-2 days.

**Comment by sauwming** [comment]
The fuzz target on our side has been merged in https://github.com/pjsip/pjproject/pull/3297. Thanks.

**Comment by 0x34d** [comment]
@Alan32Liu ping

**Comment by 0x34d** [comment]
@Alan32Liu can you Merge the PR?

**Review by Alan32Liu — APPROVED** [review]

**Pull request merged**
