### PR TITLE
libzmq: add maintainer, add UBSAN

### PR DESCRIPTION
**Pull request by bluca**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
looks like libFuzzer MSan and AFL builds are broken in travis, can you fix those or disable those configs in project.yaml

**Comment by bluca** [comment]
> looks like libFuzzer MSan and AFL builds are broken in travis, can you fix those or disable those configs in project.yaml

These are working fine in oss-fuzz runs,  when reproducing locally and in the repo's CI, any idea what could be the issue?

**Comment by inferno-chromium** [comment]
For MSan build,
BAD BUILD: /tmp/not-out/test_bind_curve_fuzzer seems to have either startup crash or exit:
This fuzzer is crashing on an uninitialized error. 
This is not a build error, but crash on verifying if fuzzer works and does not instantly crash on startup, see https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-build-failures

**Comment by bluca** [comment]
> For MSan build,
> BAD BUILD: /tmp/not-out/test_bind_curve_fuzzer seems to have either startup crash or exit:
> This fuzzer is crashing on an uninitialized error.
> This is not a build error, but crash on verifying if fuzzer works and does not instantly crash on startup, see https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-build-failures

I already tried as the page suggests, and even running the check_build option of infra/helper.py, and it all looks fine:

$ infra/helper.py check_build libzmq --engine libfuzzer --sanitizer memory
Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=memory -e ARCHITECTURE=x86_64 -v /home/luca/git/oss-fuzz/build/out/libzmq:/out -t gcr.io/oss-fuzz-base/base-runner test_all
INFO: performing bad build checks for /tmp/not-out/test_connect_curve_fuzzer.
INFO: performing bad build checks for /tmp/not-out/test_bind_curve_fuzzer.
INFO: performing bad build checks for /tmp/not-out/test_bind_null_fuzzer.
INFO: performing bad build checks for /tmp/not-out/test_z85_decode_fuzzer.
INFO: performing bad build checks for /tmp/not-out/test_connect_null_fuzzer.
INFO: performing bad build checks for /tmp/not-out/test_connect_fuzzer.
INFO: performing bad build checks for /tmp/not-out/test_bind_fuzzer.
7 fuzzers total, 0 seem to be broken (0%).
Check build passed.

**Comment by bluca** [comment]
The AFL issue seems to be just a timeout that is too short. I do not see a way in the documentation to change it.

**Comment by inferno-chromium** [comment]
> The AFL issue seems to be just a timeout that is too short. I do not see a way in the documentation to change it.

Yes just disable that fuzzing engine, afl one we keep a low one for efficiency.

**Comment by inferno-chromium** [comment]
Can easily reproduce the failure, probably you didn't pull latest images (with newer clang) ?
```
python infra/helper.py pull_images
python infra/helper.py build_fuzzers libzmq --engine libfuzzer --sanitizer memory
python infra/helper.py check_build libzmq --engine libfuzzer --sanitizer memory
```

```
BAD BUILD: /tmp/not-out/test_connect_null_fuzzer seems to have either startup crash or exit:
INFO: Seed: 1337
INFO: Loaded 1 modules   (17921 inline 8-bit counters): 17921 [0xc2e998, 0xc32f99), 
INFO: Loaded 1 PC tables (17921 PCs): 17921 [0xc32fa0,0xc78fb0), 
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
==265==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x59d213 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__get_pointer() const /usr/local/bin/../include/c++/v1/string:1517:17
    #1 0x559fd1 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::data() const /usr/local/bin/../include/c++/v1/string:1245:75
    #2 0x60e9c4 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char const*, unsigned long) const /usr/local/bin/../include/c++/v1/string:3471:10
    #3 0x60e4d0 in zmq::socket_base_t::parse_uri(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /src/libzmq/src/socket_base.cpp:329:44
    #4 0x615d4e in zmq::socket_base_t::connect_internal(char const*) /src/libzmq/src/socket_base.cpp:792:9
    #5 0x615a82 in zmq::socket_base_t::connect(char const*) /src/libzmq/src/socket_base.cpp:773:12
    #6 0x5362ac in zmq_connect /src/libzmq/src/zmq.cpp:337:15
    #7 0x522b30 in LLVMFuzzerTestOneInput /src/libzmq/tests/test_connect_null_fuzzer.cpp:52:5
    #8 0x45a141 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:556:15
    #9 0x45bc66 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:743:3
    #10 0x45c0d9 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:794:3
    #11 0x44b3ae in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:826:6
    #12 0x473b82 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #13 0x7f2993eb182f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #14 0x41fab8 in _start (/tmp/not-out/test_connect_null_fuzzer+0x41fab8)

DEDUP_TOKEN: std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__get_pointer() const--std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::data() const--std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::find(char const*, unsigned long) const
  Uninitialized value was created by an allocation of 'uri' in the stack frame of function '_ZN3zmq13socket_base_t9parse_uriEPKcRNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEESA_'
    #0 0x60e3b0 in zmq::socket_base_t::parse_uri(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&) /src/libzmq/src/socket_base.cpp:325

DEDUP_TOKEN: zmq::socket_base_t::parse_uri(char const*, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >&)
SUMMARY: MemorySanitizer: use-of-uninitialized-value /usr/local/bin/../include/c++/v1/string:1517:17 in std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >::__get_pointer() const
Unique heap origins: 32
Stack depot allocated bytes: 3472
Unique origin histories: 1
History depot allocated bytes: 24
Exiting
```

**Comment by bluca** [comment]
I did pull - tried again, same result, works fine

**Comment by bluca** [comment]
Tried purging everything in docker, still works just fine. I'll just ignore this, the important thing is that it works in oss-fuzz itself.

I set the fuzzing_engines to libfuzzer in project.yaml, which I think should disable afl.

**Comment by bluca** [comment]
> Tried purging everything in docker, still works just fine. I'll just ignore this, the important thing is that it works in oss-fuzz itself.

Looks like it's failing in oss-fuzz too now. Still can't reproduce, but I can get test builds on travis-ci.com now so I'll try a few things there

**Comment by inferno-chromium** [comment]
MSan can be fixed in another CL, merging this.

**Comment by bluca** [comment]
MSAN failures seem to be false positive in Clang, see: https://github.com/google/oss-fuzz/issues/3855

**Comment by inferno-chromium** [comment]
@bluca - just fyi, libzmq build is failing https://oss-fuzz-build-logs.storage.googleapis.com/index.html#libzmq because when check_build runs the fuzz targets, they create lot of junk/temporary files in that dir and then zip operation to create build archive fails. This seems bad, fuzz targets should clean their temp files before exit or ideally just operate on data in memory, can you please fix that, that will fix the build archiving.

```
tep #44:   adding: ^B
Step #44: 	zip warning: could not open for reading: ^B
Step #44:   adding: ^B^A
Step #44: 	zip warning: could not open for reading: ^B^A
Step #44:   adding: ^B^B�^C^B^B^B
Step #44: 	zip warning: could not open for reading: ^B^B�^C^B^B^B
```

**Comment by bluca** [comment]
@inferno-chromium strange, I'm not sure which files would be created, I'll have a look

**Comment by bluca** [comment]
there are no files created by the tests, I'm really not sure what the ci is complaining about

**Comment by bluca** [comment]
corpora for the tests is built and installed alongside the binaries, as the documentation suggests - could that be the problem?

**Comment by bluca** [comment]
same for dictionaries

**Comment by inferno-chromium** [comment]
@bluca - i looked more and found that this fuzzer is the issue

```
python infra/helper.py build_fuzzers libzmq
python infra/helper.py shell libzmq
cd /out
./test_bind_fuzzer -dict=test_bind_fuzzer.dict
```
ctrl+c after a 10-20 sec,
see ton of bad files in /out
```
root@3ed60d06b5e6:/out# ls
?                                 ::::::::::*:::::::;::::::         :::u%p  endpoint.dict                           test_connect_curve_fuzzer                  ~
?                                 :::::::::::::::?                  ::u%%p  instrumented_libraries                  test_connect_curve_fuzzer.dict             ?
?                                 ::::::::::::::::::0::::::::::j    :j      p%                                      test_connect_curve_fuzzer_seed_corpus.zip  ??
!?                                ::::::::::::::::::::$             :wwww   p:                                      test_connect_fuzzer                        ??cy:p:
%:`::p                            :::::::::::::::::::::::::         :z      test_bind_curve_fuzzer                  test_connect_fuzzer.dict                   ?????
:                                 :::::::::::::::::::::::::::::::j  ;       test_bind_curve_fuzzer.dict             test_connect_null_fuzzer                   ?????????????:j
:'                                :::::::::::::::::::::::::::::j    A:j     test_bind_curve_fuzzer_seed_corpus.zip  test_connect_null_fuzzer.dict              ??????????????
::                                :::::::::::::::::::::`:::::::j    S:      test_bind_fuzzer                        test_connect_null_fuzzer_seed_corpus.zip   ????????????????????????????:j
::1:`:\                           ::::::::::??:::::::::::::::::j    \::     test_bind_fuzzer.dict                   test_z85_decode_fuzzer
::::::::*::::::::::::::::::::::j  ::::::::::??:::::::::\:::::::j    `%p.    test_bind_null_fuzzer                   u+:
::::::::::*::::::::::::::         ::::::::`::::::?                  c:      test_bind_null_fuzzer.dict              z:
::::::::::*:::::::;::::8:         ::::`??????                       ci?     test_bind_null_fuzzer_seed_corpus.zip   zmtp.dict
```

**Comment by bluca** [comment]
Ah, I see: it's socket files. Thanks to the dict, the test is interpreting the input as AF_UNIX paths, so socket files are created. I'll change the test so that they go into an ephemeral directory. Thanks for pointing this out.

**Pull request merged**
