### PR TITLE
fix build failure for aptos-core

### PR DESCRIPTION
**Pull request by gedigi**
This PR asets the rust `nightly` version to generic to solve a build issue.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I think the failure is spurious right?

**Comment by gedigi** [comment]
> I think the failure is spurious right?

Yes

**Comment by jonathanmetzman** [comment]
I think this won't work. Let me figure out an alternative.

**Comment by gedigi** [comment]
gentle reminder. this PR is waiting to be merged for several weeks. how can we get it approved? thank you.

**Pull request merged**
