### PR TITLE
roaring-bitmap: initial integration

### PR DESCRIPTION
**Pull request by arthurscchan**
Initial integration for project RoaringBitmap.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@lemire would you be interested in enrolling this?

**Comment by lemire** [comment]
Sure. I did not know you guys did Java.

We can always use more testing. It never happened to me that I thought... "hmmm, this library is too well tested..."

**Comment by lemire** [comment]
cc @ richardstartin

**Comment by lemire** [comment]
I looked at the tests and it seemed sensible.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by richardstartin** [comment]
FWIW the 32 bit versions (`RoaringBitmap`, `ImmutableRoaringBitmap`, `MutableRoaringBitmap`) are more widely used than the 64 bit version.

**Comment by Alan32Liu** [comment]
> FWIW the 32 bit versions (`RoaringBitmap`, `ImmutableRoaringBitmap`, `MutableRoaringBitmap`) are more widely used than the 64 bit version.

@arthurscchan Would you like to add that in this PR?
I don't mind either way : )

**Comment by arthurscchan** [comment]
@richardstartin Thanks for your suggestions. I will try to add in more fuzzers for these classes in later PRs.
@lemire I have added your email in the project.yaml file. Thanks.
@Alan32Liu I think the PR is good for now. I will add more fuzzers in later PRs. Thanks.

**Comment by lemire** [comment]
@arthurscchan It seems that the fuzzer broke.

Here is the error:

> Could not get resource 'https://plugins.gradle.org/m2/io/github/gradle-nexus/publish-plugin/1.0.0/publish-plugin-1.0.0.module'.
Step #3 - "compile-libfuzzer-address-x86_64":             Could not GET 'https://jcenter.bintray.com/io/github/gradle-nexus/publish-plugin/1.0.0/publish-plugin-1.0.0.module'. Received status code 502 from server: Bad Gateway


I don’t think we are using bintray in RoaringBitmap.

I do not understand the error.

**Pull request merged**
