### PR TITLE
Update project.yaml for libpng

### PR DESCRIPTION
**Pull request by thealberto**
HI all,
I would like to participate to the project improving the coverage provided by the fuzzer. Could you accept me as a cc so I can access to the current corpora and improve it as well?

Thanks

### CODE REVIEW

**Review by DavidKorczynski — CHANGES_REQUESTED** [review]
Are you a maintainer of the project? If not, please make sure maintainers are happy to have you see issues.

**Comment by thealberto** [comment]
Hi David,
no I'm not. I'll contact the current maintainer and ask him to comment on this PR. Is it OK? Thanks

**Comment by DavidKorczynski** [comment]
yes

**Comment by jonathanmetzman** [comment]
Unfortunately the main maintainer, glenn, passed away, I don't think he will respond.

**Comment by thealberto** [comment]
Hi @jonathanmetzman ,
yes sure I'm aware of it. That is why I tagged the most active user... How could we better approach this situation?

Thanks

**Comment by kcc** [comment]
I guess a comment from an active committer would be enough.

**Comment by thealberto** [comment]
@kcc,
unfortunately there hasn't been any push this year for `libpng`. Hopefully someone will reply soon

**Comment by jonathanmetzman** [comment]
> @kcc, unfortunately there hasn't been any push this year for `libpng`. Hopefully someone will reply soon

I don't think this will happen. The upstream maintainer for libpng, Glenn Randers-Pehrson has passed away.

**Pull request merged**
