### PR TITLE
new project: memcached

### PR DESCRIPTION
**Pull request by bxa-stripe**
This PR adds `memcached` as a supported project to OSS-Fuzz, sans initial integration work. This will follow after acceptance. 

Memcached is a high-performance, distributed memory object caching system used by a large number of firms, including Netflix and Stripe. More information about the project can be found at the project's homepage.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
Thanks, @bxa-stripe.
May I ask if you have the maintainer's approval?
Thanks!

**Comment by bxa-stripe** [comment]
Yes, we've got the maintainer's approval.

**Comment by Alan32Liu** [comment]
> Yes, we've got the maintainer's approval.

Thanks! I'ved asked the panel.

**Comment by Alan32Liu** [comment]
Hi @bxa-stripe, the panel has approved this.
Please feel free to proceed.

**Comment by Alan32Liu** [comment]
I will convert this to a draft for now, but please feel free to convert it back once ready : )

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
