### PR TITLE
[tarantool] Enable centipede engine

### PR DESCRIPTION
**Pull request by ligurio**

### CODE REVIEW

**Comment by oliverchang** [comment]
Looks like the build is failing: https://github.com/google/oss-fuzz/actions/runs/3479908728/jobs/5819035559

@Alan32Liu any ideas why?

**Comment by Alan32Liu** [comment]
I reckon this is another side-effect of `Centipede`'s linking requirement.
It expects us to separate build flags from linking flags, but we did not.
Here when we are building C objects for `tzcode`, we also pass `-ldl`, `-lrt`, `-lpthread`, and its `weak.o`, which should be used when linking.

Sometimes that only gives a warning, and other times this exits with an error.
I am not sure if there is an easy way to fix it: We also had similar issues with some benchmarks in FuzzBench and I can only exclude those benchmarks from Centipede's experiments.

**Comment by Alan32Liu** [comment]
Merged #9030 to master but it seems the new version has not taken effect yet.
The CI tests still use the old set of flags.
Maybe rerun that test in a few hours.

**Comment by Alan32Liu** [comment]
We updated `Centipede` to its latest version in the main branch.
Merged that change here as well.

**Comment by Alan32Liu** [comment]
Thanks, I will have another look at it today.
A quick guess is that although our flag `-Wno-error=unused-command-line-argument` is more specific and can always overwrite their general flags `-Werror -Wall`, they added another `-Wno-unused-parameter` which specifically overwrites our `-Wno-error=unused-command-line-argument`.
I will look for solutions and keep everyone updated.

**Comment by oliverchang** [comment]
Hmm, this looks different:

```
: && /usr/local/bin/clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize-coverage=trace-loads -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fno-builtin -fsanitize-coverage=trace-pc-guard,pc-table,trace-cmp -O2 -gline-tables-only  -Wno-error=unused-command-line-argument -ldl -lrt -lpthread /src/centipede/weak.o  -fsanitize=fuzzer-no-link -fexceptions -funwind-tables -fno-common -msse2  -fmacro-prefix-map=/src/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Wno-unused-parameter -g -ggdb -O0 -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize-coverage=trace-loads -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fno-builtin -fsanitize-coverage=trace-pc-guard,pc-table,trace-cmp -O2 -gline-tables-only  -Wno-error=unused-command-line-argument -ldl -lrt -lpthread /src/centipede/weak.o  -fsanitize=fuzzer-no-link -stdlib=libc++    -rdynamic test/fuzz/CMakeFiles/csv_fuzzer.dir/csv_fuzzer.c.o -o test/fuzz/csv_fuzzer  src/lib/csv/libcsv.a  -Wl,-Bstatic  -lFuzzingEngine  -Wl,-Bdynamic && :
/usr/bin/ld: /lib/libFuzzingEngine.a(runner.pic.o): in function `LLVMFuzzerMutate':
runner.cc:(.text.LLVMFuzzerMutate+0x43): undefined reference to `operator new(unsigned long)'
/usr/bin/ld: runner.cc:(.text.LLVMFuzzerMutate+0xae): undefined reference to `operator delete(void*)'
/usr/bin/ld: runner.cc:(.text.LLVMFuzzerMutate+0xeb): undefined reference to `operator delete(void*)'
/usr/bin/ld: /lib/libFuzzingEngine.a(runner.pic.o): in function `centipede::DumpPcTable(char const*)':
```

**Comment by Alan32Liu** [comment]
> Hmm, this looks different:
> 
> ```
> : && /usr/local/bin/clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize-coverage=trace-loads -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fno-builtin -fsanitize-coverage=trace-pc-guard,pc-table,trace-cmp -O2 -gline-tables-only  -Wno-error=unused-command-line-argument -ldl -lrt -lpthread /src/centipede/weak.o  -fsanitize=fuzzer-no-link -fexceptions -funwind-tables -fno-common -msse2  -fmacro-prefix-map=/src/tarantool=. -std=c11 -Wall -Wextra -Wno-gnu-alignof-expression -Wno-cast-function-type -Werror -Wno-unused-parameter -g -ggdb -O0 -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize-coverage=trace-loads -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fno-builtin -fsanitize-coverage=trace-pc-guard,pc-table,trace-cmp -O2 -gline-tables-only  -Wno-error=unused-command-line-argument -ldl -lrt -lpthread /src/centipede/weak.o  -fsanitize=fuzzer-no-link -stdlib=libc++    -rdynamic test/fuzz/CMakeFiles/csv_fuzzer.dir/csv_fuzzer.c.o -o test/fuzz/csv_fuzzer  src/lib/csv/libcsv.a  -Wl,-Bstatic  -lFuzzingEngine  -Wl,-Bdynamic && :
> /usr/bin/ld: /lib/libFuzzingEngine.a(runner.pic.o): in function `LLVMFuzzerMutate':
> runner.cc:(.text.LLVMFuzzerMutate+0x43): undefined reference to `operator new(unsigned long)'
> /usr/bin/ld: runner.cc:(.text.LLVMFuzzerMutate+0xae): undefined reference to `operator delete(void*)'
> /usr/bin/ld: runner.cc:(.text.LLVMFuzzerMutate+0xeb): undefined reference to `operator delete(void*)'
> /usr/bin/ld: /lib/libFuzzingEngine.a(runner.pic.o): in function `centipede::DumpPcTable(char const*)':
> ```

Ah thanks, I just started looking at the errors.
Very happy it is not about flags again: FuzzBench had that issue, and I do not know the solution to it.

This is also new to me, I will see what I can do to fix this.

**Comment by Alan32Liu** [comment]
Hi @ligurio, we fixed the second error by [modifying the CMakeLists.txt](https://github.com/google/oss-fuzz/commit/92d4e951c3a10b8b3d67ccd061ddaba71f01a328).
Would there be a better way to implement it upstream? (i.e., when the fuzzer is `centipede`, always add `-lc++` after centipede's `LIB_FUZZING_ENGINE` during compilation)

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
