### PR TITLE
infra/java: Improve reproducibility of memory issues

### PR DESCRIPTION
**Pull request by fmeum**
When reproducing, use slightly lower limits on heap and stack size so that minimal changes to fuzz targets, fuzzer and runtime do not cause memory issues to fail to reproduce.

### CODE REVIEW

**Comment by fmeum** [comment]
The PR has the CI time out. Should I split it into smaller chunks?

**Comment by Alan32Liu** [comment]
> The PR has the CI time out. Should I split it into smaller chunks?

Not sure what is the best/conventional solution to this, maybe @jonathanmetzman could help? : )

**Comment by jonathanmetzman** [comment]
> When reproducing, use slightly lower limits on heap and stack size so that minimal changes to fuzz targets, fuzzer and runtime do not cause memory issues to fail to reproduce.

Interesting idea. THere may be some unintended consequences since now some crashes will be OOMs.
To test, just add some dummy file to infra, and we can do a trial build on all projects.

**Comment by fmeum** [comment]
@jonathanmetzman Done, just created `infra/trigger_test`.

**Comment by jonathanmetzman** [comment]
This breaks
rxjava
spring-security
spring-retry
spring-data-redis
spring-data-jpa
spring-boot
spring-amqp
spring-cloud-commons
apache-commons-bcel
all with errors like:
```
/tmp/not-out/tmp5lkxqzen/BindAuthenticatorFuzzer: 4: Syntax error: "(" unexpected
```
 I think you need to replace sh with bash in these projects. Then I'll merge this on Monday.

**Comment by fmeum** [comment]
@jonathanmetzman I went over all usages of `/bin/sh` and changed them to `/bin/bash`. Along the way I found some projects I had missed on the first run.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Comment by fmeum** [comment]
@jonathanmetzman Looks like something is still failing. Could you share the info from the trial build log with me?

**Comment by jonathanmetzman** [comment]
failing projects:
apache-commons
boost-json

```
Broken fuzz targets 1
('/tmp/not-out/tmpbkf69i4e/BcelFuzzer', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmpbkf69i4e/BcelFuzzer'], returncode=1, stdout=b"BAD BUILD: /tmp/not-out/tmpbkf69i4e/BcelFuzzer seems to have either startup crash or exit:\n/tmp/not-out/tmpbkf69i4e/BcelFuzzer -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null\n/tmp/not-out/tmpbkf69i4e/BcelFuzzer: line 4: unexpected token `(', conditional binary operator expected\n/tmp/not-out/tmpbkf69i4e/BcelFuzzer: line 4: syntax error near `(^'\n/tmp/not-out/tmpbkf69i4e/BcelFuzzer: line 4: `if [[  =~ (^| )-runs=\\d+($| ) ]]; then'\n", stderr=b''))
BAD BUILD: /tmp/not-out/tmpbkf69i4e/BcelFuzzer seems to have either startup crash or exit:
/tmp/not-out/tmpbkf69i4e/BcelFuzzer -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null
/tmp/not-out/tmpbkf69i4e/BcelFuzzer: line 4: unexpected token `(', conditional binary operator expected
/tmp/not-out/tmpbkf69i4e/BcelFuzzer: line 4: syntax error near `(^'
/tmp/not-out/tmpbkf69i4e/BcelFuzzer: line 4: `if [[  =~ (^| )-runs=\d+($| ) ]]; then'
```
apache one looks like a bash script fix

[log-ef94f8eb-cb21-4e1c-a183-845cba903721.txt](https://github.com/google/oss-fuzz/files/9822648/log-ef94f8eb-cb21-4e1c-a183-845cba903721.txt)

**Comment by fmeum** [comment]
@jonathanmetzman The Bash failures should be fixed.

apache-commons is broken in an earlier stage of the build, doesn't seem to be related to this PR.
boost-json isn't even a Java project and not touched by this PR.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
