### PR TITLE
Disable UBSan vptr on harfbuzz, enable UBSan for other features.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@kcc as fyi.

this works, even though it crashes on startup, will let CF file this bug.

INFO: -max_len is not provided, using 74856
#0	READ units: 66
hb-font.cc:1245:5: runtime error: call to function _hb_ot_font_destroy(hb_ot_font_t*) through pointer to incorrect function type 'void (*)(void *)'
/src/harfbuzz/src/hb-ot-font.cc:462: note: _hb_ot_font_destroy(hb_ot_font_t*) defined here
    #0 0x4727e3 in hb_font_destroy /src/harfbuzz/src/hb-font.cc:1245:5
    #1 0x42e826 in LLVMFuzzerTestOneInput /src/harfbuzz/./test/fuzzing/hb-fuzzer.cc:48:3
    #2 0x43a3c4 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/libfuzzer/FuzzerLoop.cpp:550:13

**Comment by inferno-chromium** [comment]
@behdad - fyi. this will easily reproduce this.

python infra/helper.py --nopull build_fuzzers --sanitizer undefined harfbuzz
python infra/helper.py --nopull run_fuzzer harfbuzz hb-fuzzer

**Comment by kcc** [comment]
sweet!
ultimately, we'll need to fix vptr vs no-rtti bug in the clang driver.

**Comment by inferno-chromium** [comment]
sure filed tracking https://github.com/google/oss-fuzz/issues/406

**Pull request merged**
