### PR TITLE
serenity: Add myself to the mailing list

### PR DESCRIPTION
**Pull request by nico**

### CODE REVIEW

**Review by ADKaster — APPROVED** [review]

**Review by AtkinsSJ — APPROVED** [review]
Nico is a regular Serenity contributor.

**Comment by ADKaster** [comment]
As an aside, our project config has `view_restrictions: none`. Is there any way to make that openness extend to the testcase detail pages from cluster fuzz?

**Comment by jonathanmetzman** [comment]
> As an aside, our project config has `view_restrictions: none`. Is there any way to make that openness extend to the testcase detail pages from cluster fuzz?

I don't think so. I think the page is set up so that people with access to it can force tasks and other things we can't have anyone do.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
Oh didn't even realize until I saw the email address, hi Nico!

**Pull request merged**
