### PR TITLE
Add myself to several xiph projects

### PR DESCRIPTION
**Pull request by tmatth**
I currently have access to `speex` and `tremor` (the fixed-point version of `vorbis`)

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Can you ask some of the maintainers (I assume you know some of those listed) for permission.

**Comment by tmatth** [comment]
> Can you ask some of the maintainers (I assume you know some of those listed) for permission.

ping @jmvalin @tdaede

**Comment by tysmith** [comment]
+1 for sure!

**Comment by jonathanmetzman** [comment]
@guidovranken for libtheora what do you think?

**Comment by guidovranken** [comment]
> @guidovranken for libtheora what do you think?

I once wrote this fuzzer independently and don't know anyone from the project so I cannot attest to OP's involvement with the project.

**Comment by tmatth** [comment]
> > @guidovranken for libtheora what do you think?
> 
> I once wrote this fuzzer independently and don't know anyone from the project so I cannot attest to OP's involvement with the project.

For context:
https://gitlab.xiph.org/xiph/theora/-/commits/master?author=Tristan%20Matthews
(I have commit access to libtheora as well)

**Comment by tdaede** [comment]
+1

**Comment by tmatth** [comment]
@jonathanmetzman I've gotten a +1 above from a cc or vendor_cc for each of these projects, is that sufficient?

**Comment by jonathanmetzman** [comment]
Would prefer not vendor_cc if possible.
Could you list the approver for each project for me please? Thanks!

**Comment by tmatth** [comment]
> Would prefer not vendor_cc if possible. Could you list the approver for each project for me please? Thanks!

- libtheora: @tdaede (`vendor_cc`), @tysmith (`vendor_cc`)
- opus: @jmvalin (`primary_contact`), @tysmith (`vendor_cc`)
- opus_file: @jmvalin (`primary_contact`)
- vorbis: @tdaede (`primary_contact`), @tysmith (`vendor_cc`)

**Comment by tmatth** [comment]
> > Would prefer not vendor_cc if possible. Could you list the approver for each project for me please? Thanks!
> 
>     * libtheora: @tdaede (`vendor_cc`), @tysmith (`vendor_cc`)
> 
>     * opus: @jmvalin (`primary_contact`), @tysmith (`vendor_cc`)
> 
>     * opus_file: @jmvalin (`primary_contact`)
> 
>     * vorbis: @tdaede (`primary_contact`), @tysmith (`vendor_cc`)

@jonathanmetzman ping

**Comment by jonathanmetzman** [comment]
I can merge the other three but not for libtheora since a maintainer hasn't approved it

**Comment by jonathanmetzman** [comment]
Well it's not clear if anyone from libtheora is involved here so let's merge.

**Comment by tmatth** [comment]
@jonathanmetzman cheers

**Pull request merged**
