### PR TITLE
[libxml2] Added new fuzzers

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Initiated work on libxml2 and added eight new fuzzers for now. I also added myself to the auto_ccs as I would like to observe progress and identify where we miss coverage.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Thanks a lot @DavidKorczynski, this is exciting.

@nwellnhof, can you please help to review these new libxml2 fuzzers. Are these hitting independent code or should they be combined ? Can these be landed in libxml2 repo ?

**Comment by nwellnhof** [comment]
> Can these be landed in libxml2 repo ?

No, we want fuzz targets written in C and MIT-licensed. I already started working on this and I'll submit a pull request kicking off initial integration of our own fuzzers in the next days.

Sorry for the delay.

@DavidKorczynski If you're interested in fuzzing libxml2 and maybe even want to help fixing any issues found, get in touch with me.

**Comment by inferno-chromium** [comment]
> > Can these be landed in libxml2 repo ?
> 
> No, we want fuzz targets written in C and MIT-licensed. I already started working on this and I'll submit a pull request kicking off initial integration of our own fuzzers in the next days.
> 
> Sorry for the delay.
> 
> @DavidKorczynski If you're interested in fuzzing libxml2 and maybe even want to help fixing any issues found, get in touch with me.

Sounds good, thanks @nwellnhof , look forward to those fuzzer integration.

@DavidKorczynski - please work with @nwellnhof to discuss fuzzers, get fuzzers landed directly in libxml2 repo first. Closing the PR here, next PR could be just updating build.sh then :)

**Comment by DavidKorczynski** [comment]
@nwellnhof reached out to you by your email!

**Pull request closed without merging**
