### PR TITLE
[Fluent-bit] Refactor build script 

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Refator of the fluent-bit build script as the upstream repo is about to manage the building of the fuzzers. 

Cross-referencing: https://github.com/fluent/fluent-bit/pull/2502

Waiting for the CR PR to be merged, only after then will this succeed.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I'll mark this as draft for now to not confuse maintainers. Just comment and flip from draft when it's ready to merge.

**Comment by DavidKorczynski** [comment]
Merged has happened upstream, this should pass now.

**Comment by DavidKorczynski** [comment]
@jonathanmetzman tagging you for convenience.

**Comment by jonathanmetzman** [comment]
Looks like AFL build is failing.

**Comment by DavidKorczynski** [comment]
Argh apologies for the early notification! Should be good now.

**Review by Dor1s — APPROVED** [review]

**Pull request merged**
