### PR TITLE
[libxaac] Initial integration

### PR DESCRIPTION
**Pull request by harishdm**
This is initial integration of libxaac codecs

### CODE REVIEW

**Comment by harishdm** [comment]
This integrates libxaac (https://github.com/ittiam-systems/libxaac) decoder and encoder for continuous fuzzing. I am one of the maintainers of libxaac project. 

libxaac supports encoding and decoding of various AAC profiles (LC, He-AAC v1, He-AAC v2, USAC, eSBR, ELD, ELDv2 etc) along with MPEG-D Dynamic Range Control.

**Comment by jonathanmetzman** [comment]
> This integrates libxaac (https://github.com/ittiam-systems/libxaac) decoder and encoder for continuous fuzzing. I am one of the maintainers of libxaac project.
> 
> libxaac supports encoding and decoding of various AAC profiles (LC, He-AAC v1, He-AAC v2, USAC, eSBR, ELD, ELDv2 etc) along with MPEG-D Dynamic Range Control

Could you share where these are used? (e.g. embeded systems, video game consoles etc).

After, I'll ask the committee if we support this integration.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
We approve of adding this project.

**Pull request merged**
