### PR TITLE
Enable centipede on a bunch of projects

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I'm gonna revert this once centipede is made a default.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer none address --fuzzing-engine centipede

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer none address --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
There are some CI errors, but it LGTM:
1. `Presumbmit` failed as `main_repo` is missing from some projects' `project.yaml`. I don't think this PR caused that, e.g., `xerces-c` does not have that attribute in the first place.
2. Project tests failed due to unable to pull the base-builder-fuzzbench image. Is it because of some recent changes we made?

**Comment by jonathanmetzman** [comment]
Not gonna merge this till monday.
I think the test failure and presubmit fail can be ignored.

**Comment by Alan32Liu** [comment]
Thanks!

**Pull request merged**
