### PR TITLE
solidity: Update seed corpus

### PR DESCRIPTION
**Pull request by bshastry**
I am not sure https://github.com/google/oss-fuzz/issues/3370#issuecomment-584893074 is having the desired effect.

Here we force a seed corpus update with every build

### CODE REVIEW

**Comment by Dor1s** [comment]
@bshastry please take a look at the Travis failure:

```
[ 81%] Building CXX object libsolidity/CMakeFiles/solidity.dir/codegen/ir/IRGeneratorForStatements.cpp.o
/src/solidity/libsolidity/codegen/ir/IRGeneratorForStatements.cpp:971:5: error: no viable conversion from 'int' to 'const std::variant<std::string, unsigned int>' (aka 'const variant<basic_string<char, char_traits<char>, allocator<char> >, unsigned int>')
                                0
                                ^
/usr/local/include/c++/v1/variant:1195:3: note: candidate constructor not viable: no known conversion from 'int' to 'const std::__1::variant<std::__1::basic_string<char>, unsigned int> &' for 1st argument
  variant(const variant&) = default;
  ^
/usr/local/include/c++/v1/variant:1196:3: note: candidate constructor not viable: no known conversion from 'int' to 'std::__1::variant<std::__1::basic_string<char>, unsigned int> &&' for 1st argument
  variant(variant&&) = default;
  ^
/usr/local/include/c++/v1/variant:1208:13: note: candidate template ignored: substitution failure [with _Arg = int, $1 = 0, $2 = 0, $3 = 0]: no type named 'type' in 'std::__1::invoke_result<std::__1::__variant_detail::__all_overloads<std::__1::__variant_detail::__overload<std::__1::basic_string<char>, 0>, std::__1::__variant_detail::__overload<unsigned int, 1> >, int, int>'
  constexpr variant(_Arg&& __arg) noexcept(
            ^
1 error generated.
```

**Comment by bshastry** [comment]
@Dor1s this has now been fixed upstream. Could you please re trigger ci?

**Comment by Dor1s** [comment]
Sure, done!

**Comment by bshastry** [comment]
> Sure, done!

Ah, sorry. This is a new bug :) Fixed it now

**Pull request merged**
