### PR TITLE
Update CCs for linkerd2/project.yaml

### PR DESCRIPTION
**Pull request by olix0r**

### CODE REVIEW

**Review by DavidKorczynski — APPROVED** [review]
Could you sign the CLA @olix0r ?

**Comment by olix0r** [comment]
@DavidKorczynski Unfortunately the UI serves a cryptic error telling me to reach out to a Googler.

image

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski Unfortunately the UI serves a cryptic error telling me to reach out to a Googler.
> 
> image

huh, I have no idea about this. If we just want this merged then I can submit the patch for you?

**Comment by olix0r** [comment]
@DavidKorczynski That would be great! Thank you in advance. I'll close this PR now then.

**Pull request closed without merging**
