### PR TITLE
Tor oss fuzzing configuration

### PR DESCRIPTION
**Pull request by nmathewson**

### CODE REVIEW

**Comment by kcc** [comment]
Thanks!

**Comment by inferno-chromium** [comment]
@nmathewson Nick - do you plan to commit these changes (and fuzz corpora) in the main Tor repro. It will be great to fuzz on tip-of-tree trunk on https://gitweb.torproject.org/tor.git/ and not on a custom fork.

**Comment by nmathewson** [comment]
That's the plan -- they're currently awaiting code review.

**Comment by inferno-chromium** [comment]
Thanks Nick!

**Comment by inferno-chromium** [comment]
@nmathewson Nick - looks like the fuzzers are crashing on startup. Can you please check.
https://oss-fuzz-build-logs.storage.googleapis.com/status.html
https://oss-fuzz-build-logs.storage.googleapis.com/build_logs/tor/latest.txt

oss-fuzz-microdesc -rss_limit_mb=2048 -timeout=25 -runs=32 /tmp/seed_corpus/
oss-fuzz-microdesc: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
ERROR: bad exit code: 127
testing oss-fuzz-descriptor
Using seed corpus: oss-fuzz-descriptor_seed_corpus.zip
oss-fuzz-descriptor -rss_limit_mb=2048 -timeout=25 -runs=32 /tmp/seed_corpus/
oss-fuzz-descriptor: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
ERROR: bad exit code: 127
testing oss-fuzz-vrs
Using seed corpus: oss-fuzz-vrs_seed_corpus.zip
oss-fuzz-vrs -rss_limit_mb=2048 -timeout=25 -runs=32 /tmp/seed_corpus/
oss-fuzz-vrs: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
ERROR: bad exit code: 127
testing oss-fuzz-http
Using seed corpus: oss-fuzz-http_seed_corpus.zip
oss-fuzz-http -rss_limit_mb=2048 -timeout=25 -runs=32 /tmp/seed_corpus/
oss-fuzz-http: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
ERROR: bad exit code: 127
testing oss-fuzz-extrainfo
Using seed corpus: oss-fuzz-extrainfo_seed_corpus.zip
oss-fuzz-extrainfo -rss_limit_mb=2048 -timeout=25 -runs=32 /tmp/seed_corpus/
oss-fuzz-extrainfo: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
ERROR: bad exit code: 127
testing oss-fuzz-consensus
Using seed corpus: oss-fuzz-consensus_seed_corpus.zip
oss-fuzz-consensus -rss_limit_mb=2048 -timeout=25 -runs=32 /tmp/seed_corpus/
oss-fuzz-consensus: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
ERROR: bad exit code: 127
testing oss-fuzz-iptsv2
Using seed corpus: oss-fuzz-iptsv2_seed_corpus.zip
oss-fuzz-iptsv2 -rss_limit_mb=2048 -timeout=25 -runs=32 /tmp/seed_corpus/
oss-fuzz-iptsv2: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
ERROR: bad exit code: 127
testing oss-fuzz-hsdescv2
Using seed corpus: oss-fuzz-hsdescv2_seed_corpus.zip
oss-fuzz-hsdescv2 -rss_limit_mb=2048 -timeout=25 -runs=32 /tmp/seed_corpus/
oss-fuzz-hsdescv2: error while loading shared libraries: libevent-2.0.so.5: cannot open shared object file: No such file or directory
ERROR: bad exit code: 127
8 fuzzers total (8 failed).

**Comment by kcc** [comment]
Ah, yes, we installed libevent into the docker container, but forgot that we need to link libevent statically
(the execution environment does not use docker and does not install any deps)

**Comment by nmathewson** [comment]
Does the execution environment have zlib and openssl?  Or should I link those statically too?

**Pull request merged**
