### PR TITLE
[cifuzz] Dont report crash on process timeout.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Just because nonzero is reported doesn't mean there's a crash.

Related: https://github.com/google/oss-fuzz/issues/9470 https://github.com/google/oss-fuzz/issues/9318
https://github.com/prometheus/prometheus/issues/11810

### CODE REVIEW

**Review by DavidKorczynski — APPROVED** [review]
LGTM! with the caveat I don't know the full details of `result.timed_out`.

One question, what does `result.timed_out` specifically mean? Does it mean e.g. if process X took Y seconds but was only set to run (using libFuzzer arguments) for Z seconds, where Y > Z, then `result.timed_out` is set? If so, very nice too as I think this will solve the false positives we've seen with Python Atheris in CIFuzz (described in second half of https://github.com/google/oss-fuzz/pull/8985#issuecomment-1355740809).

**Review by oliverchang — COMMENTED** [review]
LGTM

**Pull request merged**
