### PR TITLE
Adds project catch2

### PR DESCRIPTION
**Pull request by catenacyber**
cc @pauldreik @horenmar
would you be interested in oss-fuzz fuzzing continuously Catch2 ?
This PR enables it with your 3 fuzz targets

### CODE REVIEW

**Comment by catenacyber** [comment]
CI fails on wasmtime, I do not know why...

**Comment by pauldreik** [comment]
Thanks for taking the effort to write adaption to oss-fuzz.

Fuzzing catch2 seems to be of little value outside the project itself, I 
have a hard time coming up with a reason any vulnerability in catch2 
would be dangerous? In my opinion, oss fuzz resources are better spent 
on other projects.

I think it would be better to run fuzzing in catch2 CI instead!

PS.
Please don't put other peoples email adresses in machine parsable code 
without asking first. Use ***@***.***

**Comment by pauldreik** [comment]
Seems like github sanitized the email adress.

Please use the one in 
https://github.com/google/oss-fuzz/blob/8f899a86607bb44dcda62acbdf525f1281e5f5f4/projects/fmt/project.yaml#L3

**Comment by catenacyber** [comment]
> Please use the one in fmt

Ok, sorry about that

> I think it would be better to run fuzzing in catch2 CI instead!

Well, integration in oss-fuzz would allow you to have CIFuzz, that is running fuzzing in CI
cf https://google.github.io/oss-fuzz/getting-started/continuous-integration/

> I have a hard time coming up with a reason any vulnerability in catch2 would be dangerous?

You can still catch bugs even if they have no security impact, and I guess that is the reason why you wrote these 3 fuzz targets, right ?

**Comment by pauldreik** [comment]
> 
>     I think it would be better to run fuzzing in catch2 CI instead!
> 
> Well, integration in oss-fuzz would allow you to have CIFuzz, that is 
> running fuzzing in CI
> cf 
> https://google.github.io/oss-fuzz/getting-started/continuous-integration/ <https://google.github.io/oss-fuzz/getting-started/continuous-integration/>
> 
>     I have a hard time coming up with a reason any vulnerability in
>     catch2 would be dangerous?
> 
> You can still catch bugs even if they have no security impact, and I 
> guess that is the reason why you wrote these 3 fuzz targets, right ?
> 

Sure! But oss fuzz is not the only way to get fuzzing in CI. I have 
added github action based CI fuzzing for boost.json (see 
https://github.com/boostorg/json/actions/workflows/run_fuzzer.yml). I 
setup a similar job for simdjson, even if simdjson is already on 
oss-fuzz. See 
https://github.com/simdjson/simdjson/actions/workflows/fuzzers.yml. It 
also runs fuzzing on the arm and power architecture, something oss-fuzz 
does not do (yet?).

I think json libraries are highly likely to run on untrusted input and a 
good fit for oss-fuzz.

**Comment by catenacyber** [comment]
Thanks for your comment, closing

**Pull request closed without merging**
