### PR TITLE
gitoxide: initial integration

### PR DESCRIPTION
**Pull request by silvergasp**
Signed-off-by: Nathaniel Brough <nathaniel.brough@gmail.com>

### CODE REVIEW

**Comment by silvergasp** [comment]
cc @Byron

Gitoxide is critical to global infrastructure and;
- Has an [ossf/criticality_score](https://github.com/ossf/criticality_score) of  0.59309
- 5.5k stars on github
- There is an ongoing effort to replace the libgit bindings used in cargo (the rust package manager) with gitoxide https://github.com/rust-lang/cargo/pull/11448.

**Comment by Byron** [comment]
I hereby agree with `gitoxide` being added to `oss-fuzz`. Special thanks to @silvergasp without whom this wouldn't be happening this soon.

**Comment by jonathanmetzman** [comment]
I'm asking the committee what we think of adding this project.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
