### PR TITLE
tcpreplay: initial integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
@fklassen I have set up continuous fuzzing of tcpreplay. The benefits are that the fuzzer will be run on a regular basis and bug reports will be send to your email with information such as inputs that trigger the bugs, stack traces and more. Is this something you would be happy to have set up? If so, the only thing needed from your end is an email that will receive the bugs reports - notice this email should be attached to a Google account for you to see the reports.

### CODE REVIEW

**Comment by fklassen** [comment]
I don't know why I missed this for 3 years. Sorry about that. Is this still viable? In that case, I could give you my email address.

**Comment by fklassen** [comment]
@DavidKorczynski would you suggest merging this instead of [#15924](https://github.com/google/oss-fuzz/pull/15924) ?

I can't sign the CLA due to corporate policies.

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski would you suggest merging this instead of [#15924](https://github.com/google/oss-fuzz/pull/15924) ?
> 
> I can't sign the CLA due to corporate policies.

If you can't sign the CLA, would it be easier if I make a similar PR to yours and then we can land that?

**Comment by fklassen** [comment]
Yes please. Please land it in 4.6.1-beta1

**Pull request closed without merging**
