### PR TITLE
ngolo-fuzzing: fix build by using python3

### PR DESCRIPTION
**Pull request by catenacyber**
Was this the only project where this happened ?
Meant to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=52844

### CODE REVIEW

**Review by Navidem — APPROVED** [review]
LGTM

**Comment by Navidem** [comment]
> Was this the only project where this happened ? 

@jonathanmetzman Do you know about these?

**Comment by jonathanmetzman** [comment]
> > Was this the only project where this happened ?
> 
> @jonathanmetzman Do you know about these?

I can't find any other. Do you ask because you think this is related to the bazel probelm?

**Comment by jonathanmetzman** [comment]
> > > Was this the only project where this happened ?
> > 
> > 
> > @jonathanmetzman Do you know about these?
> 
> I can't find any other. Do you ask because you think this is related to the bazel probelm?

I guess the root cause, us uninstalling python3 from the base image could be the same. But it's weird because we do install python3.8.

**Comment by catenacyber** [comment]
> Do you ask because you think this is related to the bazel probelm?

No, just out of curiosity that `python` is gone even if `python3` is still there in base-builder-go

**Comment by Alan32Liu** [comment]
Merging this as I reckon it is ready.
Please let me know if you'd like me to revert it.

**Comment by catenacyber** [comment]
Thanks for merging

**Pull request merged**
