### PR TITLE
Update requests version 2.2.0

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Landing trivial change.
Change doesn't break `build_fuzzers` or `build_image` or `coverage`.

**Comment by Dor1s** [comment]
> Change doesn't break build_fuzzers or build_image or coverage.

I'm not sure if `helper.py` uses this. This is a dependency needed for GCB scripts (e.g. https://github.com/google/oss-fuzz/blob/master/infra/gcb/build_project.py).

Since you've already landed this, we can manually kick off some project build (I've just launched zlib) and see if it goes through.

**Comment by Dor1s** [comment]
Yeah, both regular build and coverage job finished successfully, thanks for the upgrade!

**Comment by oliverchang** [comment]
thanks! was there something that prompted this?

**Comment by jonathanmetzman** [comment]
https://github.com/google/oss-fuzz/network/alerts?q=is%3Aclosed

**Pull request merged**
