### PR TITLE
[google-cloud-go] Initial integration

### PR DESCRIPTION
**Pull request by codyoss**

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by AdaLogics** [comment]
Hey @codyoss. 
Respectfully and politely, it would be nice to acknowledge the PR (https://github.com/google/oss-fuzz/pull/3824) I previously did  - which found a bug that was reported and fixed (https://github.com/googleapis/google-cloud-go/issues/2196) - where I integrated the project, as I can see you use my work in your commit https://github.com/googleapis/google-cloud-go/pull/2909 

I am not too bothered about attribution although it certainly has its merits, but since there is an integration reward I think it would be fair to attribute the original author.

**Comment by AdamKorcz** [comment]
Hey @codyoss.
Respectfully and politely, it would be nice to acknowledge the PR (#3824) I previously did - which found a bug that was reported and fixed (googleapis/google-cloud-go#2196) - where I integrated the project, as I can see you use my work in your commit googleapis/google-cloud-go#2909

I am not too bothered about attribution although it certainly has its merits, but since there is an integration reward I think it would be fair to attribute the original author.

**Comment by inferno-chromium** [comment]
> Hey @codyoss.
> Respectfully and politely, it would be nice to acknowledge the PR (#3824) I previously did - which found a bug that was reported and fixed ([googleapis/google-cloud-go#2196](https://github.com/googleapis/google-cloud-go/issues/2196)) - where I integrated the project, as I can see you use my work in your commit [googleapis/google-cloud-go#2909](https://github.com/googleapis/google-cloud-go/pull/2909)
> 
> I am not too bothered about attribution although it certainly has its merits, but since there is an integration reward I think it would be fair to attribute the original author.

@AdamKorcz - since you proposed the original PR to google-cloud-go project, we would gladly consider you for integration reward.
@codyoss - you would be still the owner for this pipeline since we always encourage actual project devs to own the fuzzing integration, get access to bugs, and fix them. if you have any concerns about Adam's reward, feel free to reach out to me directly over email.

**Comment by codyoss** [comment]
@inferno-chromium All sounds good to me, thanks.

**Pull request merged**
