### PR TITLE
Update Dockerfile to retrieve seed file from repo,

### PR DESCRIPTION
**Pull request by hho2**

### CODE REVIEW

**Comment by hho2** [comment]
CLA has been signed.

**Comment by jzern** [comment]
lgtm from the libvpx side.

**Comment by inferno-chromium** [comment]
@hho2 - did you sign an individual cla or signed under a corporate cla. does https://cla.developers.google.com/clas show signed for you ?

**Comment by hho2** [comment]
Individual. Yeah the URL does  shows up for me as signed.

**Comment by Dor1s** [comment]
Is the email you signed CLA for associated with you GitHub account? The same email should also be used in `git config user.email`. What I'm seeing in your patches is some auto-generated email provided by GitHub:

```
Author: Hien Ho <45771997+hho2@users.noreply.github.com>  2018-12-10 13:34:42
```

**Comment by hho2** [comment]
Probably because I created those  patches via the UI not on my local workspace.?

**Comment by hho2** [comment]
I had started here last week, and just setup my github account. I had my email setting  set to private which would send the auto-generated email address when I created the patches. Will create a new patch.

**Comment by hho2** [comment]
will create a new patch

**Pull request closed without merging**
