### PR TITLE
infra: bump fuzz introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Includes
- Several bug fixes for builds
- Refinement of how static analysis is matched with code coverage data (https://github.com/ossf/fuzz-introspector/issues/812)
- More output to `summary.json` to make the following logic less hacky: https://github.com/google/oss-fuzz/blob/3d2ec74dba753ba9a91a3efd942615739f5028be/infra/build/build_status/fuzz_introspector_page_gen.py#L250-L260
- Improvements to the Sink analyser for detecting e.g. code injections: https://fuzz-introspector.readthedocs.io/en/latest/user-guides/analyse-sink-function.html
- Various improvements to the java frontend

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Review by oliverchang — APPROVED** [review]

**Review by Alan32Liu — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
given there's two approvals does that mean no trial run is needed?

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by DavidKorczynski** [comment]
Friendly ping on this one -- the timeout shown:
```
Step #1: INFO:root:Polling: defaultdict(<class 'list'>, {'hiredis-py': ['eb554224-df92-4daf-9978-af80c0ab65b1'], 'retry': ['cbe00c45-03f5-4c19-af75-0d1ddce50481'], 'tidy-html5': ['34645d01-9085-4723-855a-5bc8528bed84']})
Step #1: INFO:root:Polling: defaultdict(<class 'list'>, {'hiredis-py': ['eb554224-df92-4daf-9978-af80c0ab65b1'], 'retry': ['cbe00c45-03f5-4c19-af75-0d1ddce50481'], 'tidy-html5': ['34645d01-9085-4723-855a-5bc8528bed84']})
Step #1: INFO:root:Polling: defaultdict(<class 'list'>, {'hiredis-py': ['eb554224-df92-4daf-9978-af80c0ab65b1'], 'retry': ['cbe00c45-03f5-4c19-af75-0d1ddce50481'], 'tidy-html5': ['34645d01-9085-4723-855a-5bc8528bed84']})
Step #1: INFO:root:Polling: defaultdict(<class 'list'>, {'hiredis-py': ['eb554224-df92-4daf-9978-af80c0ab65b1'], 'retry': ['cbe00c45-03f5-4c19-af75-0d1ddce50481'], 'tidy-html5': ['34645d01-9085-4723-855a-5bc8528bed84']})
Step #1: INFO:root:Polling: defaultdict(<class 'list'>, {'hiredis-py': ['eb554224-df92-4daf-9978-af80c0ab65b1'], 'retry': ['cbe00c45-03f5-4c19-af75-0d1ddce50481'], 'tidy-html5': ['34645d01-9085-4723-855a-5bc8528bed84']})
Step #1: INFO:root:Polling: defaultdict(<class 'list'>, {'hiredis-py': ['eb554224-df92-4daf-9978-af80c0ab65b1'], 'retry': ['cbe00c45-03f5-4c19-af75-0d1ddce50481'], 'tidy-html5': ['34645d01-9085-4723-855a-5bc8528bed84']})
Step #1: INFO:root:Polling: defaultdict(<class 'list'>, {'hiredis-py': ['eb554224-df92-4daf-9978-af80c0ab65b1'], 'retry': ['cbe00c45-03f5-4c19-af75-0d1ddce50481'], 'tidy-html5': ['34645d01-9085-4723-855a-5bc8528bed84']})
Step #1: INFO:root:Polling: defaultdict(<class 'list'>, {'hiredis-py': ['eb554224-df92-4daf-9978-af80c0ab65b1'], 'retry': ['cbe00c45-03f5-4c19-af75-0d1ddce50481'], 'tidy-html5': ['34645d01-9085-4723-855a-5bc8528bed84']})
Ste
```

I assume we don't care about this?

**Comment by oliverchang** [comment]
Sorry for the delay. Let's just get this one in.

**Pull request merged**
