### PR TITLE
Stop fuzzing urllib3

### PR DESCRIPTION
**Pull request by pquentin**
We were grateful for the opportunity but in practice we only got emails about broken builds and never got a useful report. This is not currently worth the effort for our team.

Thank you!

### CODE REVIEW

**Review by sethmlarson — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Sorry to hear that -- Apologies for the recent broken build email! This is due to https://github.com/google/oss-fuzz/issues/7615 and I hope it's getting resolved soon (hopefully https://github.com/google/oss-fuzz/pull/7641 does it).

If you're interested, perhaps a way to get better outcome is moving the set up upstream which enables you to easily write your own fuzzers and extend on the integration?

**Comment by pquentin** [comment]
I like the idea of fuzzing in general, but I don't think we'll find anything in urllib3 without more effort: after all, the URL parsing was the most promising part. Maybe there's a way to start with valid inputs and use fuzzing to mutate them slightly?

We're not ready to make those efforts, however, so please respect our decision.

**Comment by DavidKorczynski** [comment]
> I like the idea of fuzzing in general, but I don't think we'll find anything in urllib3 without more effort: after all, the URL parsing was the most promising part. Maybe there's a way to start with valid URLs and use fuzzing to mutate them slightly?
> 

My gut feeling is the parsing code has been explored in full by now and that the coverage feedback engine was enough to get the code explored. The new python coverage visualisation we're integrating can assist in making this judgement though. 

> We're not ready to make those efforts, however, so please respect our decision.

Understood -- before merging there might be interest in keeping the project but removing your emails (so you will not be spammed anymore) similar to e.g. Libxml2 https://github.com/google/oss-fuzz/pull/6090 @jonathanmetzman @oliverchang ?

**Comment by pquentin** [comment]
That would work for me but I'm afraid you're losing your time. @sethmlarson What do you think?

**Comment by pquentin** [comment]
That would work for me but I'm afraid you're losing your time. @sethmlarson What do you think?

**Comment by DavidKorczynski** [comment]
> That would work for me but I'm afraid you're losing your time. @sethmlarson What do you think?

I think the point here would be if a bug happens then we would report it further to you!

**Comment by sethmlarson** [comment]
That's fine, let's try this.

**Pull request closed without merging**
