### PR TITLE
Improve a bit the bs4 fuzzer

### PR DESCRIPTION
**Pull request by jvoisin**
- Don't install 2to3 anymore
- Fuzz the css selector as well

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by leonardr** [comment]
This change sent me [a spurious-looking fuzzer failure](https://oss-fuzz.com/testcase-detail/5270998950477824). My best guess from looking at it is that this old code:

```
idx = int(data[0]) % len(parsers)
```

Is semi-randomly choosing a parser to use for the fuzz test based on the first byte of the fuzzed data. But the new code is treating `data` as a list, which it isn't.

```
idx = int(data.pop()) % len(parsers)
```

I'd guess changing that line back will fix the problem, assuming that the CSS selector (which now begins `data`) is fuzzed just like the markup is.

**Comment by jvoisin** [comment]
Absolutely: I sent https://github.com/google/oss-fuzz/pull/10268 to fix it. Sorry about this :/

**Comment by jvoisin** [comment]
This has been fixed in #10303

**Pull request merged**
