### PR TITLE
This allows users to skip CIFuzz's logic to only run affected fuzz

### PR DESCRIPTION
**Pull request by jonathanmetzman**
targets.
Fixes: https://github.com/google/clusterfuzzlite/issues/85

### CODE REVIEW

**Comment by evverx** [comment]
@jonathanmetzman looking at `CiFuzzTargetRunner` where `quit_on_bug_found` always returns `True` I'm not sure how `keep-unaffected-fuzz-targets` can prevent CFLite from stopping as soon as a bug is discovered. My understanding is that `keep-unaffected-fuzz-targets` should be used to always run all fuzz targets (which is kind of part of https://github.com/google/clusterfuzzlite/issues/85) but it isn't enough to emulate the batch mode without uploading corpora.

**Comment by evverx** [comment]
Having said that it could be I'm missing something. I've just updated https://github.com/evverx/systemd/pull/8 so once this PR lands I'll retrigger it to figure whether both fuzz targets fail there by analogy with the batch mode.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman looking at `CiFuzzTargetRunner` where `quit_on_bug_found` always returns `True` I'm not sure how `keep-unaffected-fuzz-targets` can prevent CFLite from stopping as soon as a bug is discovered. My understanding is that `keep-unaffected-fuzz-targets` should be used to always run all fuzz targets (which is kind of part of [google/clusterfuzzlite#85](https://github.com/google/clusterfuzzlite/issues/85)) but it isn't enough to emulate the batch mode without uploading corpora.

That's right, it won't solve the problem fully then I guess but it is a prerequisite to solving it.

**Review by oliverchang — APPROVED** [review]

**Comment by evverx** [comment]
@jonathanmetzman could you reopen that issue? I can't seem to do that.

**Comment by evverx** [comment]
> it is a prerequisite to solving it

Other than that it seems it would also have helped to get around https://github.com/google/oss-fuzz/issues/7195.

**Comment by evverx** [comment]
Thanks! I've just opened https://github.com/systemd/systemd/pull/22482 to get around issues related to coverage.

@jonathanmetzman it seems https://github.com/google/clusterfuzzlite/issues/85 was closed again automatically.

**Pull request merged**
