### PR TITLE
prost: initial integration.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
https://crates.io/crates/prost Protocol buffers implementation in Rust.

Has 291 reverse dependencies: https://crates.io/crates/prost/reverse_dependencies and 3.5 million downloads.

@danburkert I have set up continuous fuzzing of Prost. I thought it would be nice to have this set up as there are a fair amount of projects relying on Prost. Is this something you would be happy to have set up? The benefits are that the fuzzers will be run on a regular basis and bug reports will be send to your email with information such as inputs that trigger the bugs, stack traces and more. If you would like to get Prost in, the only thing needed from your end is an email that will receive the bugs reports - notice this email should be attached to a Google account for you to see the reports.

### CODE REVIEW

**Comment by danburkert** [comment]
Hey @DavidKorczynski , this sounds great.   Is the requested email address put into this config, or is it kept private?

**Comment by DavidKorczynski** [comment]
it's put in this config and thus publicly available.

**Comment by danburkert** [comment]
OK sounds good, please add dan@danburkert.com.  Thanks for setting this up.

**Comment by DavidKorczynski** [comment]
> OK sounds good, please add [dan@danburkert.com](mailto:dan@danburkert.com). Thanks for setting this up.

Great. Will do that. Also, FYI the email can be changed whenever too - so if you decide later to have another one or add more emails, then it's no problem at all.

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
