### PR TITLE
update to afl++ release version

### PR DESCRIPTION
**Pull request by vanhauser-thc**
the only noteworthy change is that for asan the input buffer is now tagged according to the input size (can now detect read buffer overruns on the input buffer to LLVMFuzzerTestOneInput).

### CODE REVIEW

**Comment by radarhere** [comment]
Hi. I suggest rebasing on master so that #7192 is included. That should fix the failing CI jobs.

**Comment by jonathanmetzman** [comment]
Sorry for the slow response here.
We're pretty nervous about updating AFL++ right now (it's also a busy time for us here).
I wanted to wait for #7145
I think I can make progress on that issue next week.
Is that OK?

**Comment by vanhauser-thc** [comment]
the PR will make detecting asan read overflows in the input buffer possible. otherwise little changes. there is little risk.

**Comment by vanhauser-thc** [comment]
this can be merged. this supports llvm15 (tested with latest commit from wednesday) and has no negative performance (as tested with fuzzbench)

**Comment by jonathanmetzman** [comment]
> this can be merged. this supports llvm15 (tested with latest commit from wednesday) and has no negative performance (as tested with fuzzbench)

We have a test environment now. Let me play with it!

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
@vanhauser-thc May want to unsubscribe from this issue, I'm probably going to spam it.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine afl

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine afl

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine afl

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms abseil-cpp aiohttp alembic arduinojson --sanitizer address --fuzzing-engine afl

**Comment by jonathanmetzman** [comment]
I'm probably gonna merge this as part of https://github.com/google/oss-fuzz/pull/7595 so I can modify the test environment more easily

**Comment by jonathanmetzman** [comment]
https://github.com/google/oss-fuzz/pull/7595

**Pull request merged**
