### PR TITLE
feat(wasmer): Update build scripts to latest release

### PR DESCRIPTION
**Pull request by xdoardo**
We recently released a new version of Wasmer and, among other things, we now use LLVM 18 and rust 1.81: this small patch bumps them to the correct versions in the scripts.

### CODE REVIEW

**Comment by vitorguidi** [comment]
> xdoardo is a new contributor to [projects/wasmer](https://github.com//google/oss-fuzz/tree/master/projects/wasmer). The PR must be approved by known contributors before it can be merged. The past contributors are: catenacyber, manunio

@syrusakbary does this look good to you? The change in primary contact caught my eye.

**Comment by syrusakbary** [comment]
Yes, looks good on our side.
Thanks for checking in

**Comment by vitorguidi** [comment]
> We recently released a new version of Wasmer and, among other things, we now use LLVM 18 and rust 1.81: this small patch bumps them to the correct versions in the scripts.

@xdoardo ready to merge once tests get fixed

**Comment by xdoardo** [comment]
Thanks for the ping, I'll look into it as soon as possible.

**Comment by xdoardo** [comment]
Thanks @manunio. I removed those lines, let's see if CI passes.

**Review by vitorguidi — APPROVED** [review]
lgtm

**Pull request merged**
