### PR TITLE
Fix spuriously failing test

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I think this issue is related to #5213

**Comment by inferno-chromium** [comment]
i dont understand this, will let @oliverchang review.

**Comment by jonathanmetzman** [comment]
> i dont understand this, will let @oliverchang review.

What don't you understand?
The test is really awful and depends on the real gonids project in OSS-Fuzz.
gonids is now broken because of an issue with go get. 
I think we don't need to land this if go get issue is fixed soon.

**Comment by inferno-chromium** [comment]
> > i dont understand this, will let @oliverchang review.
> 
> What don't you understand?
> The test is really awful and depends on the real gonids project in OSS-Fuzz.
> gonids is now broken because of an issue with go get.
> I think we don't need to land this if go get issue is fixed soon.

Why not remove gonids completely from 
https://github.com/google/oss-fuzz/blob/ee7031c4a528b4a24c98ce4e61c04fb3cd90ae1c/infra/test_repos.py#L61
or subsitute it with another repo. i see 2 already there, so can remove gonids completely too.

**Comment by inferno-chromium** [comment]
ping, infra-tests is breaking in every test, can you please check this in. might be best to just remove gonids altogether or add another go project.

**Pull request merged**
