### PR TITLE
[libigl] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
Initial integration of [libigl](https://github.com/libigl/libigl).

Companies that use libigl include: 

- Adobe
- Electronic Arts, Inc
- Epic Games
- Microsoft Research
- Ubisoft

An list of selected users can be found here: https://libigl.github.io/#projectsuniversities-using-libigl

______________________________________________________________

@jdumas Are you interested in integrating Libigl into OSS-fuzz?
All we need is an email address for bug reports to complete this PR.
If this gets merged, then https://github.com/libigl/libigl/pull/1802 can be closed.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
@jdumas Kind ping.

**Comment by jdumas** [comment]
Oh sorry I forgot to answer. Please use `github [at] jdumas.org` for the email address. Thanks!

**Comment by AdamKorcz** [comment]
@inferno-chromium @oliverchang @jonathanmetzman @asraa @DavidKorczynski Libigl is ready for review

**Review by oliverchang — APPROVED** [review]

**Comment by Chongruiyuan893** [comment]
Unsubscribe

**Comment by jdumas** [comment]
@AdamKorcz I have received several reports from OSS fuzz, but I cannot click on the links to get access to the detailed reports. It is expecting me to login with a gmail account (different from the email I provided to receive the bug reports), but when I try to do so it tells me that `You (email=xxx) are not authorized to access this page!`. Is there any way around that?

**Comment by AdamKorcz** [comment]
@jdumas Only the email addresses in `project.yaml` have access. Are you logging in with github [at] jdumas.org?

**Comment by jdumas** [comment]
I don't see any option to login with a non-gmail account.

**Comment by jdumas** [comment]
Screen Shot 2021-07-02 at 9 06 22 AM

**Comment by AdamKorcz** [comment]
It does not have to be a gmail account, but some email extensions are not approved to access the bug reports. 

If you cannot log in with the current email address it would be because jdumas.org is not recognized.

I can add another email address to `project.yaml` for you if you'd like.

**Comment by DavidKorczynski** [comment]
@AdamKorcz @jdumas The account need not be a gmail account but the emails in `project.yaml` must be affiliated with a google account

**Comment by jdumas** [comment]
Do you mean I should add this as an alternate email to my gmail account?

Screen Shot 2021-07-02 at 9 18 33 AM

**Comment by DavidKorczynski** [comment]
You could either link `github@jdumas.org` to a Google account or we could put your gmail account in the `project.yaml` - either works.

**Comment by jdumas** [comment]
Sorry I'm still not super clear on how to "link" an email to a google account. The link you provided above explains how to create a new account, not how to link an email to an existing account. Do you mean to enter the email as an alternate email as described in the screenshot I posted above?

**Comment by DavidKorczynski** [comment]
> Sorry I'm still not super clear on how to "link" an email to a google account. The link you provided above explains how to create a new account, not how to link an email to an existing account. Do you mean to enter the email as an alternate email as described in the screenshot I posted above?

Ah apologies, I also misunderstood. Yes that should work!

**Comment by jdumas** [comment]
Yeah I'm still getting a permission denied.

**Comment by DavidKorczynski** [comment]
Ah sorry! Many apologies here. It looks like there are some limitations for alternate emails (https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/): *If you use an alternate email address linked to a Google Account, you’ll only get access to filed bugs in the issue tracker, not to the ClusterFuzz dashboard. This is due to appengine API limitations.*

Sorry for the confusion. Would it be possible to use a Google account without an alternate email?

**Comment by jdumas** [comment]
I'd rather not be forced to use a gmail address due to stupid arbitrary limitations.

**Comment by DavidKorczynski** [comment]
it doesn't force you to use a gmail. I use david@adalogics and many others use non-gmail addresses. The alternative aspect refers to an email that is not the primary email of a Google account. If you have a Google account where you primary email is your github@jdumas, then that should work.

**Comment by jdumas** [comment]
Fine I guess I'll be create a new account specifically for this purpose then... Still pretty annoying tbh.

**Comment by DavidKorczynski** [comment]
Thanks for the flexibility - and yeah it would be great to have additional authentication features added. 

Cross-referencing: 
https://github.com/google/oss-fuzz/issues/1915
https://github.com/google/oss-fuzz/issues/2261

**Pull request merged**
