### PR TITLE
[aarch64] Add ARM support to helper.py

### PR DESCRIPTION
**Pull request by jonathanmetzman**
This is probably a lot of what is needed for CFL support (though there's probably a lot of other stuff left).
Related: https://github.com/google/oss-fuzz/issues/8164

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py zlib --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py zlib --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py zlib --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Review by Navidem — APPROVED** [review]

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
