### PR TITLE
Revert "Update Centipede"

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Reverts google/oss-fuzz#11151 as it breaks the base builder

Ref: https://github.com/google/oss-fuzz/pull/11151#issuecomment-2208641953

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py all --fuzzing-engines centipede --sanitizers address none

**Comment by DavidKorczynski** [comment]
PR is failing because of the unit tests as in here: https://github.com/google/oss-fuzz/pull/12153

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py ruby --fuzzing-engines libfuzzer --sanitizers coverage

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py all --fuzzing-engines centipede --sanitizers address none

**Comment by jonathanmetzman** [comment]
> /gcbrun trial_build.py ruby --fuzzing-engines libfuzzer --sanitizers coverage

The ruby stuff is broken.

**Comment by jonathanmetzman** [comment]
LGTM

**Comment by DavidKorczynski** [comment]
> > /gcbrun trial_build.py ruby --fuzzing-engines libfuzzer --sanitizers coverage
> 
> The ruby stuff is broken.

Ah, I had missed the `ruby` part of the trail run actually -- so much for not remembering the gcbrun commands and relying on copy paste.

Will land this if the CI is happy

**Pull request merged**
