### PR TITLE
Add `handle_sigsegv=1` to Wasmtime's options

### PR DESCRIPTION
**Pull request by alexcrichton**
This is an attempt to handle #4264

### CODE REVIEW

**Comment by alexcrichton** [comment]
FWIW I'm not confident on the exact syntax here, I know the env var uses `handle_segv` but we already had `handle_sigill` in the options file so I'm figuring that there may be a difference that this should be `handle_sigsegv`. It'd be good if someone could confirm that though!

**Comment by inferno-chromium** [comment]
OPtion name is handle_segv, so i renamed it.

**Comment by inferno-chromium** [comment]
Please keep an eye and let us know tmrw if the bug is closed.

**Comment by alexcrichton** [comment]
This looks to have done the trick! The bug just lost the "reproducible" label and the logs show that the latest attempt doesn't reproduce. Given that this test would otherwise deterministically segfault I think this config change is indeed working.

**Pull request merged**
