### PR TITLE
Correct my email address in the openssh cc list.

### PR DESCRIPTION
**Pull request by daztucker**

### CODE REVIEW

**Review by DavidKorczynski — APPROVED** [review]
Thanks.

For reference, @daztucker  is a top maintainer on the repo https://github.com/openssh/openssh-portable/graphs/contributors

**Comment by DavidKorczynski** [comment]
@daztucker it looks like there is a problem with one of the fuzzers when compiling with afl. Would it be possible to fix this up?

**Comment by daztucker** [comment]
Yes but I need to figure out how to drive it first.  (I didn't set this up, but I'm talking to the guy who did today.)

**Comment by djmdjm** [comment]
I've tried to reproduce this crash locally but can't. I tried

```
python3 infra/helper.py build_image openssh
python3 infra/helper.py build_fuzzers openssh --engine afl --sanitizer address --architecture x86_64
python3 infra/helper.py check_build openssh --engine afl --sanitizer address --architecture x86_64
```

and the checks passed fine. Could this be a flake?

**Comment by inferno-chromium** [comment]
> ```
> python3 infra/helper.py check_build openssh --engine afl --sanitizer address --architecture x86_64
> ```

I cant reproduce it either, so merged this and we will see if builders complain. they file a bug if the failure repeats twice.

**Pull request merged**
