### PR TITLE
[jackson-dataformats-binary] Initial integration

### PR DESCRIPTION
**Pull request by fmeum**
Signed off by @cowtowncoder in https://github.com/FasterXML/jackson-dataformats-binary/issues/254#issuecomment-798792202

### CODE REVIEW

**Review by jonathanmetzman — COMMENTED** [review]
Who are some of the users of jackson-dataformats-binary?

**Comment by fmeum** [comment]
> Who are some of the users of jackson-dataformats-binary?

It's not used in a large number of bigger open-source projects as the formats it covers are rather specialized and low-level. However, it does appear to be the only reputable choice for parsing e.g. CBOR in Java, which in turn is gaining importance as a building block of the FIDO 2FA standard. A major open-source projects that uses this library for CBOR parsing is https://github.com/redisson/redisson.

**Comment by cowtowncoder** [comment]
Of codecs included in `jackson-dataformats-binary` (avro, cbor, amazon-ion, protobuf, smile), Smile and CBOR backends are rather widely used; not sure where the impression came that they might be obscure?

Looking at Maven Central dependencies of all Jackson backends:

https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat

* CBOR is used by 387 other projects (https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor) -- like Spring Boot, Spring Web, Elastic Search and Kafka, just to name a few top ones.
* Smile is used by 338 other projects (https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-smile) -- similarly by various Spring projects, Elastic & Logstash, Solr, Radisson (cache)

Alternatively if looking at downloads via https://oss.sonatype.org/, CBOR has bit over 5 million monthly downloads, and smile about 1.3 million.

Dependency analysis from Github shows some usage as well:

* CBOR, 2878 deps: https://github.com/FasterXML/jackson-dataformats-binary/network/dependents?package_id=UGFja2FnZS0xODEwNzEyMjI%3D
* Smile, 2241 deps: https://github.com/FasterXML/jackson-dataformats-binary/network/dependents?package_id=UGFja2FnZS0xODAwNTc1NzM%3D

I hope this helps.

**Comment by fmeum** [comment]
I just pushed a new version of the integration commit that includes a Smile fuzzer.

**Comment by jonathanmetzman** [comment]
> Of codecs included in `jackson-dataformats-binary` (avro, cbor, amazon-ion, protobuf, smile), Smile and CBOR backends are rather widely used; not sure where the impression came that they might be obscure?

Didn't mean to imply it was obscure. I'm just not familiar with the library since I don't do much java development.
This type of question is common for projects trying to use OSS-Fuzz.

> Perhaps one reason might be that a lot of usage is indirectly via frameworks like Spring Boot, JAX-RS providers (RESTeasy, Jersey, Restlet), Solar, ElasticSearch.
> 
> Looking at Maven Central dependencies of all Jackson backends:
> 
> https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat
> 
> * CBOR is used by 387 other projects (https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-cbor) -- like Spring Boot, Spring Web, Elastic Search and Kafka, just to name a few top ones. The second most common Java CBOR codec after Jackson one is used by only 20 other projects (https://mvnrepository.com/tags/cbor)
> * Smile is used by 338 other projects (https://mvnrepository.com/artifact/com.fasterxml.jackson.dataformat/jackson-dataformat-smile) -- similarly by various Spring projects, Elastic & Logstash, Solr, Radisson (cache)
> 
> Alternatively if looking at downloads via https://oss.sonatype.org/, CBOR has bit over 5 million monthly downloads, and smile about 1.3 million.
> 
> Dependency analysis from Github shows some usage as well:
> 
> * CBOR, 2878 deps: https://github.com/FasterXML/jackson-dataformats-binary/network/dependents?package_id=UGFja2FnZS0xODEwNzEyMjI%3D
> * Smile, 2241 deps: https://github.com/FasterXML/jackson-dataformats-binary/network/dependents?package_id=UGFja2FnZS0xODAwNTc1NzM%3D
> 
> I hope this helps.

It does thanks.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
