### PR TITLE
[juju] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
Initial integration of [Juju](https://github.com/juju/juju). 

Users of Juju include [[src](https://juju.is/)]: 

- Deutsche Telekom
- IBM
- Intel
- Microsoft Azure
- Cisco
- China Telekom
- HP
- Yahoo
- Verizon
- Panasonic
- BT
- Rabobank
- Tele2
____________________________________________________________

@SimonRichardson @achilleasa @wallyworld @ycliuhw

I have been working on setting up continuous fuzzing for Juju and have set up this draft integration application with build files and a fuzzer to get things started.

Integrating with OSS-fuzz is free but is offered with an implied expectation that found bugs are fixed. Once Juju is integrated OSS-fuzz will run all Jujus fuzzers continuously and report bugs to maintainers on the mailing list. 

To finish the integration at least on email address is needed for bug reports.

Let me know if you are interested continuing with integration.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
@SimonRichardson @achilleasa @wallyworld @ycliuhw Kind ping. Are you interested in integrating Juju into OSS-fuzz for continuous fuzzing? If so, a maintainers email address is needed for bug reports.

**Comment by SimonRichardson** [comment]
@AdamKorcz yeah, just send it to mine on my profile, for now, we can always change it later on.

**Comment by AdamKorcz** [comment]
@inferno-chromium @jonathanmetzman @oliverchang @asraa @DavidKorczynski Juju is ready for review

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
