### PR TITLE
Set introspector env variable in compile

### PR DESCRIPTION
**Pull request by Navidem**

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by Navidem** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer --force

**Comment by jonathanmetzman** [comment]
> /gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer --force

After this passes, please remove this redundant setting https://github.com/google/oss-fuzz/blob/master/infra/build/functions/build_and_run_coverage.py#L319, and then run another trial_build (with only one project, e.g. unrar, to not waste money)

**Comment by jonathanmetzman** [comment]
> > /gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer --force
> 
> After this passes, please remove this redundant setting https://github.com/google/oss-fuzz/blob/master/infra/build/functions/build_and_run_coverage.py#L319, and then run another trial_build (with only one project, e.g. unrar, to not waste money)

You can even do it now to be honest, just make sure to check that the build you just did was successful
(you can use tags:branch-set_introspector_env to view trial builds from this branch)

**Comment by Navidem** [comment]
> > /gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer --force
> 
> After this passes, please remove this redundant setting https://github.com/google/oss-fuzz/blob/master/infra/build/functions/build_and_run_coverage.py#L319, 

I've already removed that in this PR!

**Comment by jonathanmetzman** [comment]
> > > /gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer --force
> > 
> > 
> > After this passes, please remove this redundant setting https://github.com/google/oss-fuzz/blob/master/infra/build/functions/build_and_run_coverage.py#L319,
> 
> I've already removed that in this PR!

Ha I must've got the idea for this change somewhere :-)

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib unrar c-ares --sanitizer introspector --fuzzing-engine libfuzzer --force

**Pull request merged**
