### PR TITLE
Add wolfSSL project

### PR DESCRIPTION
**Pull request by levi-wolfssl**

### CODE REVIEW

**Comment by kcc** [comment]
The change looks good, but I don't see you (at least, this github account) as one of the wolfSSL committers. May I ask you to get 'ok' from one of the active wolfSSL committers here? 
Also, you will need to sign the CLA

**Comment by JacobBarthelmeh** [comment]
Hello kcc, thanks for reviewing the changes. Levi did open this pull request on behalf of wolfSSL. Currently though we are reviewing the CLA.
Regards,
Jacob

**Comment by kcc** [comment]
Perfect! We'll merge this if/when you sign the CLA. 
Thanks for doing this, looking forward to merging the Dockerfile/build.sh.

**Comment by levi-wolfssl** [comment]
We over here at wolfSSL have signed the CLA.

**Comment by kcc** [comment]
Thanks! If this is a corp CLA, it may take a day or two to propagate.

**Comment by renaudd** [comment]
In order for this PR to proceed, please have the Google CCLA signed by an authorized executive of wolfSSL.

**Comment by Dor1s** [comment]
The CLA seems to be finally signed, wooho! I'm merging this!

**Comment by Dor1s** [comment]
WolfSSL folks, do you plan on improving your fuzzing coverage? The latest report is available at https://oss-fuzz.com/v2/coverage-report/job/libfuzzer_asan_wolfssl/latest

It feels like it might be worth to add new fuzz targets: https://blog.fuzzing-project.org/63-Stack-buffer-overflow-in-WolfSSL-before-3.13.0.html

**Comment by JacobBarthelmeh** [comment]
Hi Dor1s, Thank you for the question and coverage stats. I'll discuss increasing use of oss-fuzz internally with the team.

**Comment by JacobBarthelmeh** [comment]
Dor1s, to get back to the question about improving fuzzing coverage, yes we plan on improving the fuzzing coverages with oss-fuzz!

**Pull request merged**
