### PR TITLE
[igraph] build libxml2 without ICU

### PR DESCRIPTION
**Pull request by szhorvat**
This is to work around a crash in ICU, see https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44854 and https://unicode-org.atlassian.net/browse/ICU-21932

### CODE REVIEW

**Comment by szhorvat** [comment]
I'm not sure what is going wrong with the 32-bit build here. I get:

```
error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

But I do install `libz-dev:i386`, which in turn installs `zlib1g:i386` (per the logs), which should contain this file (https://packages.ubuntu.com/focal/i386/zlib1g/filelist)

**Comment by szhorvat** [comment]
@DavidKorczynski, is this a problem with OSS-fuzz? Shouldn't the same 64- and 32-bit libraries be present on the runner?

**Comment by szhorvat** [comment]
For now, I have disabled libz support when building libxml2, as I think we don't need it.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski, is this a problem with OSS-fuzz? Shouldn't the same 64- and 32-bit libraries be present on the runner? Or perhaps we are supposed to link libz statically as well?

I would think the packages should be the same, but am not certain about this. I'm also not not certain if the packages of the various distributions will be compiled in the same manner (excluding difference in architecture) and whether this could lead to differences in behaviour.

Building statically against dependencies is the recommended approach though.

**Pull request merged**
