### PR TITLE
Fix build breakage due to nasm >= 2.13.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@michaelni - does this seem fine ? ffmpeg build has been broken for a week, can you please setup a weekly reminder to check build page. We are working on some notifications for this, but wont come until Q3.
see breakage on https://oss-fuzz-build-logs.storage.googleapis.com/log-433ec840-1fc6-4e78-adb0-456ffbdbb8fa.txt

**Comment by michaelni** [comment]
> @michaelni - does this seem fine ? ffmpeg build has been broken for a week, can you please setup a weekly reminder to check build page. We are working on some notifications for this, but wont come until Q3.

It seems the build failure is from x264, it may be more robust to not use x264.git HEAD but a unchanging checkout of it so changes to its dependencies do not break build. (also x264 is i think not really used currently in any test run). The patch as is should be fine too if it works. About a remainder, i do work on ossfuzz ffmpeg issues now more or less daily (though not by using docker as its slow), i should thus theoretically notice if fixed bugs stop being detected as fixed, and i did notice but thought there maybe was a change in how often it runs or updates, hadnt thought it failed. Is there a easy place online where the build status of it can be checked ?

**Comment by Dor1s** [comment]
@michaelni we have a Build Status page (https://oss-fuzz-build-logs.storage.googleapis.com/index.html), it is also referenced in README: https://github.com/google/oss-fuzz#build-status

**Comment by inferno-chromium** [comment]
@michaelni - until we setup email notification for such build failures, we would really appreciate if you can look at the build status once every few days to make sure build is fine. Thanks a lot for fixing all those bugs!

**Pull request merged**
