### PR TITLE
Adds ntp project with ntpd fuzz target

### PR DESCRIPTION
**Pull request by catenacyber**
Comments are welcome

Any idea on how to use bit keeper to get latest sources ?

### CODE REVIEW

**Comment by catenacyber** [comment]
CI is failing for AFL (and working for libfuzzer)...
Any idea why ?

**Comment by jonathanmetzman** [comment]
> CI is failing for AFL (and working for libfuzzer)...
> Any idea why ?

yep. It says "No instrumentation detected" when it tries to run AFL target.
Over [here](https://github.com/google/oss-fuzz/pull/2645/files#diff-6710ed27c5d053825a3c6fb0dc24f82dR16) you hardcoded -fsanitize=fuzzer instead of using `$LIB_FUZZING_ENGINE` which is different for AFL.

**Comment by catenacyber** [comment]
Thanks @jonathanmetzman 
Hopefully, this patch will fix AFL compilation on oss-fuzz

**Comment by catenacyber** [comment]
So, there is still something wrong with AFL.
Can you guess what it is ?
It looks related to C++ stdlib but I did not manage to hack it...

**Comment by jonathanmetzman** [comment]
Weird. I don't know what's happening here. I'm fine if this lands without AFL support.

**Comment by catenacyber** [comment]
Works now with linking to libstdc++ with the right order for flags...

**Comment by jonathanmetzman** [comment]
> Works now with linking to libstdc++ with the right order for flags...

Not the first time I've seen this. I really don't like that this happens.

Thanks for solving this!

**Pull request merged**
