### PR TITLE
Set up coverage build properly

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
archive.ubuntu.com having some trouble :-(

**Review by jonathanmetzman — COMMENTED** [review]
TBR

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --engine libfuzzer --sanitizer address

**Review by Alan32Liu — COMMENTED** [review]
LGTM

**Pull request merged**
