### PR TITLE
Add c-blosc2 project

### PR DESCRIPTION
**Pull request by nmoinvaz**
This PR adds version 2 of c-blosc to OSS-Fuzz. @FrancescAlted

A previous discussion located [here](https://github.com/Blosc/c-blosc2/commit/099db918ea1e0eea81dae205e3aed0f61064994f).

### CODE REVIEW

**Comment by nmoinvaz** [comment]
If there is support for this from OSS-Fuzz I can continue to try and solve the issues.

**Comment by inferno-chromium** [comment]
@nmoinvaz - can you comment on the users of c-blosc2 ? Also, can you see the CI failures for MSan+x64, ASan+i386 builds.

**Comment by nmoinvaz** [comment]
@FrancescAlted would be able to better answer the question about the users of it. I figured it would be a shoe-in because version 1 is already part of OSS-Fuzz. 

I can see some errors on the GitHub Actions ci failures.
```
i386:x86-64 architecture of input file `./build_dir/blosc/libblosc2.a(blosc2.c.o)' is incompatible with i386 output
```
And 
```
INFO: performing bad build checks for /tmp/not-out/compress_fuzzer.
INFO: performing bad build checks for /tmp/not-out/decompress_fuzzer.
Broken fuzz targets (2):
compress_fuzzer:
BAD BUILD: /tmp/not-out/compress_fuzzer seems to have only partial coverage instrumentation.
decompress_fuzzer:
BAD BUILD: /tmp/not-out/decompress_fuzzer seems to have only partial coverage instrumentation.
```
I cannot see the fuzzing errors, but I have thought about adding myself to the email in the project files. I am just wanting to see this will be accepted, and if so then I can do the extra work to make it work for you. It already works locally with your scripts.

**Comment by inferno-chromium** [comment]
> @FrancescAlted would be able to better answer the question about the users of it. I figured it would be a shoe-in because version 1 is already part of OSS-Fuzz.

Ok fine, we can accept it then.

> 
> I can see some errors on the GitHub Actions ci failures.
> 
> ```
> i386:x86-64 architecture of input file `./build_dir/blosc/libblosc2.a(blosc2.c.o)' is incompatible with i386 output
> ```
> 
> And
> 
> ```
> INFO: performing bad build checks for /tmp/not-out/compress_fuzzer.
> INFO: performing bad build checks for /tmp/not-out/decompress_fuzzer.
> Broken fuzz targets (2):
> compress_fuzzer:
> BAD BUILD: /tmp/not-out/compress_fuzzer seems to have only partial coverage instrumentation.
> decompress_fuzzer:
> BAD BUILD: /tmp/not-out/decompress_fuzzer seems to have only partial coverage instrumentation.
> ```
> 
> I also noticed recent changes OSS-Fuzz with regard to GitHub Actions so I wonder if that might be it too.

Shouldn't be. it should reproduce with infra/helper.py with right sanitizer, engine and architecture options, can you try that. https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-build-failures

> 
> I cannot see the fuzzing errors, but I have thought about adding myself to the email in the project files. I am just wanting to see this will be accepted, and if so then I can do the extra work to make it work for you. It already works locally with your scripts.

**Comment by FrancescAlted** [comment]
Hi.  Just chiming in to say that C-Blosc2 is the next major version of C-Blosc and that we are in the latests stages before making C-Blosc2 ready for production, so I think this is a good timing for start testing it with tools like OSS-Fuzz.  Regarding users of C-Blosc2, I foresee that most of existing C-Blosc 1.x users would like to use the 2.x series, provided the API compatibility and improved features.

@nmoinvaz has been very helpful with various aspects of Blosc projects, specially in making them safer.  Thanks in advance!

**Comment by nmoinvaz** [comment]
I want to update the fuzzers for c-blosc first then I will get back to c-blosc2.

**Comment by nmoinvaz** [comment]
@inferno-chromium should be gtg.

**Pull request merged**
