### PR TITLE
fixed spelling errors or typos

### PR DESCRIPTION
**Pull request by sinapis-amicus**
fixing a few spelling errors and typos. was fuzzedLibaryVersion intentionally Libary?

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I don't think we should land this. I don't think the typos actually affect people's understanding, but this commit would make tools like git-blame harder to use.

**Comment by Alan32Liu** [comment]
@oliverchang What's the best way to handle this? Thanks!

**Comment by oliverchang** [comment]
Indeed the blast radius is a bit big here. Fixing this up in our own infra code seems OK, but this touches a lot of other project configs where it may cause other issues.

**Comment by Alan32Liu** [comment]
Thanks, converted this into a draft, then : )

**Pull request closed without merging**
