### PR TITLE
[hdf5] Initial integration [Draft]

### PR DESCRIPTION
**Pull request by AdamKorcz**
Initial integration of hdf5.

@byrnHDF @derobins @qkoziol @gnuoyd @fortnern @jhendersonHDF
Are you interested in integrating hdf5 into OSS-fuzz for continuous fuzzing and get notified if bugs are found?
This PR integrates hdf5 with its first fuzzer.

To complete the integration, we need a maintainers email address for bug reports.

### CODE REVIEW

**Comment by schwehr** [comment]
@AdamKorcz Thanks for working on this!

**Comment by AdamKorcz** [comment]
@schwehr Would you like to integrate? If so, we need an email address for bug reports and we are good to go

**Comment by schwehr** [comment]
> @schwehr Would you like to integrate? If so, we need an email address for bug reports and we are good to go

I'm not involved on either the hdf5 or google oss-fuzz side, so I can't speak to what the HDF5 folks would like to provide as an email.

**Comment by AdamKorcz** [comment]
@byrnHDF @derobins @qkoziol @gnuoyd @fortnern @jhendersonHDF Kind ping to see if this is something you are interested in.

**Comment by derobins** [comment]
Sorry, we've not been great at getting around to GitHub issues (we were formerly an Atlassian shop). If you are still interested in this, feel free to use my email address (derobins@hdfgroup.org).

**Comment by DavidKorczynski** [comment]
This got a bit outdated. A new pull request with refined set up was opened here: https://github.com/google/oss-fuzz/pull/9413

**Pull request closed without merging**
