### PR TITLE
Add project.yaml for Dfinity's IC & Candid

### PR DESCRIPTION
**Pull request by venkkatesh-sekar**
Hi, 

I'm one of the security engineers working on the Internet Computer project (https://dfinity.org/). I would like to add our codebase to Google's OSS fuzz infrastructure and utilize fuzzing to discover bugs within our rust codebase. We would also like to fuzz projects outside our main repo as well, including Candid (https://github.com/dfinity/candid).

This PR adds the initial project.yaml for the project.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
I'm not familiar with this project.
Could you explain why it is critical software?
After I get this, I'll start our approval process.

**Comment by jonathanmetzman** [comment]
Ping

**Comment by venkkatesh-sekar** [comment]
Internet Computer is an open source project which is a general purpose decentralised censorship free smart contract platform ([https://dfinity.org/](https://dfinity.org/)). As an advanced smart contract platform, users have the ability to host DEFI applications, web applications backed by smart contracts and opens up many more opportunities to host many different types of applications that are still being discovered as the platform evolves.  The Internet computer is fully community driven and offers a very sophisticated governance system for the community to participate in shaping the system (https://dashboard.internetcomputer.org/governance). The governance provides interfaces for the community to drive features, verify changes, curate contents, etc. The Internet computer is powered by the advanced Internet Computer Protocol (ICP) and the specification for it is available at [https://smartcontracts.org/docs/interface-spec/index.html](https://smartcontracts.org/docs/interface-spec/index.html). 

All the source repositories related to Internet computers are located at [https://github.com/dfinity](https://github.com/dfinity). The project’s main repo ([https://github.com/dfinity/ic](https://github.com/dfinity/ic)) contains many different pieces (including testing and other infrastructure components), but the most important one is the source code for the Rust implementation of the "replica" that is compiled and run by the node machines that together make up the Internet Computer. In addition, the repo includes several internal crates which power the cryptographic logic, network architecture, consensus and message routing of the Internet computer.  

With fuzzing, we aim to improve the robustness of the underlying software and provide stronger security guarantees for the dapps on the Internet Computer ecosystem. Since genesis, the Internet computer hosts over 30,000 smart contracts which run over 414 node machines with specialised hardware ([https://dashboard.internetcomputer.org/](https://dashboard.internetcomputer.org/)).

The dapps hosted on the internet computer cover a variety of sectors including finance, games, social, infrastructure. See [https://dfinity.org/showcase/](https://dfinity.org/showcase/).

**Comment by jonathanmetzman** [comment]
We don't really think dfinity has the userbase we want for acceptance into OSS-Fuzz yet.
Would you like help in setting up [clusterfuzzlite](https://google.github.io/clusterfuzzlite)? Since ClusterFuzzLite is a new project I'm very happy to help potential users.

**Comment by jonathanmetzman** [comment]
Send me an email metzman@chromium.org if you want help with ClusterFuzzLite

**Pull request closed without merging**
