### PR TITLE
infra: fix golang coverage path to corpus

### PR DESCRIPTION
**Pull request by catenacyber**
Completes #9812

### CODE REVIEW

**Comment by catenacyber** [comment]
@jonathanmetzman could you please run gcbrun ?

**Comment by catenacyber** [comment]
Should fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=56596 and others

**Comment by catenacyber** [comment]
I guess I had forgotten to run `python3 infra/helper.py build_image --no-pull base-builder` in my test sequence...

**Comment by catenacyber** [comment]
cc @Alan32Liu

**Comment by Alan32Liu** [comment]
> cc @Alan32Liu

Thanks for the ping.
I will take a look and merge this on Monday, just in case anything breaks during the weekend : )

**Comment by catenacyber** [comment]
Well, all golang coverage builds seem broken for now ...

**Comment by catenacyber** [comment]
(I wonder why gcbrun was green on the faulty PR)

**Comment by catenacyber** [comment]
ping @Alan32Liu

**Comment by catenacyber** [comment]
Gcbrun is green ;-)

**Review by Alan32Liu — APPROVED** [review]

**Comment by catenacyber** [comment]
Thanks :-) all golang coverage builds seem fixed

**Pull request merged**
