### PR TITLE
Don't install git via ppa

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Reduce complexity and bloat

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by oliverchang** [comment]
I wonder if this breaks anything that relies on a newer git. Can we run trial_build on more projects?

**Comment by jonathanmetzman** [comment]
> /gcbrun trial_build.py skcms --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

I assumed that the new version of git from the upgrade to Ubuntu 20 is good enough for them.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address--fuzzing-engine libfuzzer afl

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
