### PR TITLE
[infra] Update Jazzer to v0.17.1

### PR DESCRIPTION
**Pull request by fmeum**
Reuses the previous Jazzer file names so that no changes to ClusterFuzz are required.

### CODE REVIEW

**Comment by fmeum** [comment]
@oliverchang @jonathanmetzman Could you run a trial build for this PR? Still doing some manual testing before I will mark this as ready for review.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py java --sanitizer address coverage undefined.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py java --sanitizer address coverage undefined

**Comment by jonathanmetzman** [comment]
Looks like all is good. Can I merge?

**Comment by fmeum** [comment]
@jonathanmetzman We identified some open crashes that we would like to view restrict before merging, but this should be good to go after that. Will follow up with you.

**Comment by fmeum** [comment]
@jonathanmetzman Everything cleared up, no need to restrict anything. Please merge!

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py java --sanitizer address coverage undefined

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
Ah crap. I didn't test anything because, it's "jvm" not "java"

**Pull request merged**
