### PR TITLE
wazuh: initial integration.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Wazuh is a free, open source and enterprise-ready security monitoring solution for threat detection, integrity monitoring, incident response and compliance. On the main homepage: https://wazuh.com/ you can see the list of users, which includes salesforce, groupon and other large organisations.

@vikman90 I have set up continuous fuzzing of wazuh.  Is this something you would be happy to have set up? The benefits are that the fuzzers will be run on a regular basis and bug reports will be send to your email with information such as inputs that trigger the bugs, stack traces and more. If you would like to get Wazuh in, the only thing needed from your end is an email that will receive the bugs reports - notice this email should be attached to a Google account for you to see the reports.

### CODE REVIEW

**Comment by vikman90** [comment]
@DavidKorczynski thank you for setting up this! 

We're not fuzz-testing Wazuh yet, but that will definitely add much reliability to our project. In addition to the XML parser, I think that the most interesting component we should test is the inter-process communication:

- Agent communication.
- Agent registration.
- API endpoints.
- Inter-component requests.
- Active response.

In your code, the new function works as a white-box test. Is it possible to run tests with oss-fuzz on a running service?

Looking forward to knowing more about this.

Thank you for taking this step.
Best regards.

**Comment by DavidKorczynski** [comment]
We can certainly do some fuzzing of a running service, although - without knowing too much about the wazuh internals - I assume it would require a non-trivial set up. As such, I would approach this incrementally and start with more low-hanging fruit, e.g. protocols and parsers inside of wazuh. 

We could also move the fuzzing set up to the wazuh main code? 

In either case, it seems you are happy to start this process and integrate the project? If so, could you provide an email that will receive the error reports?

**Comment by vikman90** [comment]
Hi! Absolutely. I need to spend some time on this to learn how to get started and define the tests with the QA team at Wazuh, but I find fuzz testing very interesting.

We could receive reports in devel@wazuh.com.

Thank you again for contacting us!
Best regards.

**Comment by DavidKorczynski** [comment]
> Hi! Absolutely. I need to spend some time on this to learn how to get started and define the tests with the QA team at Wazuh, but I find fuzz testing very interesting.
> 
> We could receive reports in [devel@wazuh.com](mailto:devel@wazuh.com).
> 
> Thank you again for contacting us!
> Best regards.

Sounds good. I am also happy to push this a bit further by getting things upstream and perhaps adding a few more fuzzers. But for now we should be ready to integrate it and get the initial set up running.

**Comment by DavidKorczynski** [comment]
@inferno-chromium @asraa @jonathanmetzman @oliverchang this one is ready for review.

**Review by asraa — APPROVED** [review]
Thanks, looking forward to direct integration in main!

**Pull request merged**
