### PR TITLE
[skia] Remove patches

### PR DESCRIPTION
**Pull request by kjlubick**
This helps get Skia closer to use CI Fuzz. It requires https://skia-review.googlesource.com/c/skia/+/316536 to land first.

Going forward, we do not have a separate build that has the memory constraints - all fuzzer builds will have them.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Can you check CI faillures

```
The build continued as if that argument was unspecified.

Done. Made 164 targets from 59 files in 88ms
+ /src/depot_tools/ninja -C out/Fuzz android_codec animated_image_decode api_create_ddl api_draw_functions api_gradients api_image_filter api_mock_gpu_canvas api_null_canvas api_path_measure api_pathop api_polyutils api_raster_n32_canvas api_svg_canvas image_decode image_decode_incremental image_filter_deserialize jpeg_encoder path_deserialize png_encoder region_deserialize region_set_path skdescriptor_deserialize skjson skottie_json skp skruntimeeffect sksl2glsl sksl2metal sksl2pipeline sksl2spirv svg_dom textblob_deserialize webp_encoder
ninja: Entering directory `out/Fuzz'
ninja: error: unknown target 'android_codec'
Building fuzzers failed.
Running: docker build -t gcr.io/oss-fuzz/skia projects/skia
Keeping existing build artifacts as-is (if any).
Running: docker run --rm --privileged --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c++ -v /home/runner/work/oss-fuzz/oss-fuzz/build/out/skia:/out -v /home/runner/work/oss-fuzz/oss-fuzz/build/work/skia:/work -t gcr.io/oss-fuzz/skia
Building project skia
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_fuzzers skia --engine libfuzzer --sanitizer address --architecture x86_64
Failed projects: skia
##[error]Process completed with exit code 1.

```

**Comment by kjlubick** [comment]
I fully expect this to fail until https://skia-review.googlesource.com/c/skia/+/316536 lands

**Comment by kjlubick** [comment]
I'll ping this thread when it is ready for review (and the CI should pass)

**Comment by kjlubick** [comment]
Hopefully the builds should pass now since the appropriate CLs landed in Skia.

**Comment by kjlubick** [comment]
PTAL: Passed all checks, so this should fix the build

**Review by jonathanmetzman — APPROVED** [review]

**Pull request merged**
