### PR TITLE
infra: Copy fuzzer classes to JVM coverage report

### PR DESCRIPTION
**Pull request by arthurscchan**
This PR copies all the fuzzer classes to the class dump directory for Jacoco HTML report generation and removes duplication of fuzzer classes if it exists. This PR adds as a supplement for #10906 when fuzzer classes are missing in the class dump directory.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
The CI issue should be fixed in https://github.com/google/oss-fuzz/pull/10941, let's retest

**Comment by DavidKorczynski** [comment]
@jonathanmetzman @Alan32Liu would it be possible to run trial build on this?

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jvm --sanitizer address coverage undefined --fuzzing-engines libfuzzer

**Comment by jonathanmetzman** [comment]
There's quite a few failures here: https://github.com/google/oss-fuzz/pull/10917/checks?check_run_id=16824676782

**Comment by arthurscchan** [comment]
This PR is no longer needed.

**Pull request closed without merging**
