### PR TITLE
infra: bump fuzz introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
This contains a minor fix in accummulated code complexity for the annotated CFG feature, used by https://introspector.oss-fuzz.com/api/annotated-cfg -- in some cases the value would be 0 incorrectly.

Also includes:
- a refined definition of top-level API fra annotated-cfg extraction: 
  - PR: https://github.com/ossf/fuzz-introspector/pull/1191
  - fixes: https://github.com/ossf/fuzz-introspector/pull/1180#issuecomment-1667163532
- Extended type recognition for C/C++ projects:
  - PR: https://github.com/ossf/fuzz-introspector/pull/1190
  - fixes: https://github.com/ossf/fuzz-introspector/issues/1188
- Converts arg types to array of strings rather a string representation entirely:
  - PR: https://github.com/ossf/fuzz-introspector/pull/1189 
  - fixes: https://github.com/ossf/fuzz-introspector/issues/1187)

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Converted this to draft as some more updates will come shortly

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by DavidKorczynski** [comment]
Looking at the failed projects from the trial builds:

curvesapi:
```
Step #12: gcr.io/oss-fuzz-base/base-builder-go-testing-davidkorczynski-patch-8:latest
Step #1: CommandException: No URLs matched: gs://oss-fuzz-coverage/curvesapi/textcov_reports/20230808/*
Step #1: CommandException: 1 file/object could not be transferred.
```
Coverage issue? Not related. Also, curvesapi fails already.

mrab-regex:
```
Step #12: Status: Downloaded newer image for gcr.io/oss-fuzz-base/base-builder-go-testing-davidkorczynski-patch-8:latest
Step #12: gcr.io/oss-fuzz-base/base-builder-go-testing-davidkorczynski-patch-8:latest
Step #1: CommandException: No URLs matched: gs://oss-fuzz-coverage/mrab-regex/textcov_reports/20230808/*
Step #1: CommandException: 1 file/object could not be transferred.
Finished Step #12
```
Coverage issue? Not related. Also mrab-regex fails already.

p11-kit:
```
Step #12: Status: Downloaded newer image for gcr.io/oss-fuzz-base/base-builder-go-testing-davidkorczynski-patch-8:latest
Step #12: gcr.io/oss-fuzz-base/base-builder-go-testing-davidkorczynski-patch-8:latest
Step #1: CommandException: No URLs matched: gs://oss-fuzz-coverage/p11-kit/textcov_reports/20230808/*
Step #1: CommandException: 1 file/object could not be transferred.
```

Coverage issue? Not related. Also, p11-kit fails already.

uwebsockets:
```
Step #22 - "compile-libfuzzer-introspector-x86_64": [Log level 1] : 08:46:33 : Ended wrapping all functions
Step #22 - "compile-libfuzzer-introspector-x86_64": [Log level 1] : 08:46:33 : Finished introspector module
Step #22 - "compile-libfuzzer-introspector-x86_64": clang-15: [0;1;31merror: [0m[1munable to execute command: Segmentation fault (core dumped)[0m
Step #22 - "compile-libfuzzer-introspector-x86_64": clang-15: [0;1;31merror: [0m[1mlinker command failed due to signal (use -v to see invocation)[0m
Step #22 - "compile-libfuzzer-introspector-x86_64": make: *** [Makefile:29: oss-fuzz] Error 254
```

Well-known compiler issue. However, uwebsockets already fails introspector builds so not a regression.

wolf-ssl:
```
Step #12: Digest: sha256:c5b3aca596a8121bf521b104e0e812bf55b05617ef570ed08a1fa06e5941b41d
Step #12: Status: Downloaded newer image for gcr.io/oss-fuzz-base/base-builder-go-testing-davidkorczynski-patch-8:latest
Step #12: gcr.io/oss-fuzz-base/base-builder-go-testing-davidkorczynski-patch-8:latest
Step #1: CommandException: No URLs matched: gs://oss-fuzz-coverage/wolfssl/textcov_reports/20230808/*
Step #1: CommandException: 1 file/object could not be transferred.
Finished Step #12
```

jackson-dataformats-binary:

fails due to a recursion issue in the Python part of Fuzz Introspector. This is not a regression, but looks to be something spurious as the jackson-dataformat-binary project fails a bit on-and-off looking at the history.

I'd say this is good to merge.

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
