### PR TITLE
cras: Build fuzzers with bazel

### PR DESCRIPTION
**Pull request by afq984**
This change corresponds to https://crrev.com/c/4127648.
Which will allow us to migrate away from autotools.

### CODE REVIEW

**Comment by afq984** [comment]
@b92paul the coverage timeout is due to https://crrev.com/c/3657216 creating loops in the fs

**Comment by jonathanmetzman** [comment]
Is this ready for merge?

**Comment by afq984** [comment]
> Is this ready for merge?

this is pending on https://crrev.com/c/3660780

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
