### PR TITLE
[infra] use $src and $out in build scripts instead of /src and /out

### PR DESCRIPTION
**Pull request by mikea**
This will make it possible to run scripts outside of docker container.

I am not 100% sure about this one. WDYT? Will this make build scripts easier to write or not?

If yes, I'll update the documentation.

### CODE REVIEW

**Comment by kcc** [comment]
Yes, I think it's much better to use env vars instead of hard paths and then document how one can use the build script outside of docker. 

I only think that we should follow the standard convention and name the vars with capitals.
Probably also make it clear that this is a DIR:

$SRC_DIR $OUT_DIR ?

**Comment by oliverchang** [comment]
+1 to Kostya's comment.

**Comment by mikea** [comment]
For me these variables differ a little from other like `CFLAGS`. That's why I chose a different case (lowercase) in the instance. Don't feel strongly though. As for `_DIR` suffix I prefer brevity. Do you feel strongly about it?

**Comment by kcc** [comment]
$SRC and $OUT are fine too, if you prefer.

**Comment by mikea** [comment]
PTAL

**Comment by oliverchang** [comment]
LGTM!

**Pull request merged**
