### PR TITLE
infra: bump and add java support in introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Adds introspector support for java builds. Most of this work is referenced by way of
https://github.com/ossf/fuzz-introspector/issues/536

Also bumps introspector, which comes with a fix for https://github.com/ossf/fuzz-introspector/issues/679

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@Navidem FYI I have not touched the cloud build functions

**Comment by Navidem** [comment]
> @Navidem FYI I have not touched the cloud build functions

Thanks!
I assume the changes in jvm coverage will be a separate PR (matching https://github.com/ossf/fuzz-introspector/pull/689)?

**Comment by DavidKorczynski** [comment]
Before merging this, let's just get the latest fix for this one with it https://github.com/google/oss-fuzz/issues/9209

> I assume the changes in jvm coverage will be a separate PR
Yeah, will handle these after. All should still work (as in no breaking), however, some links into the coverage report will be to lines that does not have an ID attach to them -- the consequence is the user will end up at the top of the coverage page.

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib idna antlr4-java  --sanitizer introspector coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
> Before merging this, let's just get the latest fix for this one with it #9209
> 
> > I assume the changes in jvm coverage will be a separate PR
> > Yeah, will handle these after. All should still work (as in no breaking), however, some links into the coverage report will be to lines that does not have an ID attach to them -- the consequence is the user will end up at the top of the coverage page.

Sure, will re-run trial_build once having that.

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib idna antlr4-java --sanitizer introspector coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib idna antlr4-java --sanitizer introspector coverage --fuzzing-engine libfuzzer

**Comment by DavidKorczynski** [comment]
Bumped to include https://github.com/ossf/fuzz-introspector/pull/691 -- this PR now adds java introspector support and several bug fixes

**Comment by DavidKorczynski** [comment]
This is now bumped once more to include:
- https://github.com/ossf/fuzz-introspector/pull/694
- https://github.com/ossf/fuzz-introspector/pull/695
- https://github.com/ossf/fuzz-introspector/pull/696

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib idna antlr4-java --sanitizer introspector coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py ndpi glom apache-commons-cli archaius-core arrow-java --sanitizer introspector coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
Testing on more projects...

**Review by Navidem — APPROVED** [review]
LGTM

**Comment by DavidKorczynski** [comment]
Is this ready to be merged in?

**Comment by Navidem** [comment]
> Is this ready to be merged in?

Yes, but I'd say let's merge it on Monday for any potential side-effects.

**Comment by DavidKorczynski** [comment]
Did this get deployed? Checked the build logs for htslib and ndpi from the 20th and it seems to use the set up as prior to this commit

**Comment by Navidem** [comment]
As I checked the `base-clang` is not getting updated.

base-images are failing to build for the past 3 days: https://github.com/google/oss-fuzz/issues/9251

**Pull request merged**
