### PR TITLE
Add garydgregory to project.yaml

### LINKED ISSUE #10329: Can't see details
Hi,
I can't see the details for https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53743&q=label%3AProj-apache-commons-imaging

I am also ggregory at apache dot org, Apache Commons PMC Chair.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Fixes #10329

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @garydgregory

**Comment by jonathanmetzman** [comment]
@garydgregory there seems to be an issue building the project by the way.

**Comment by garydgregory** [comment]
> @garydgregory there seems to be an issue building the project by the way.

Hi @jonathanmetzman 
The GHA build is green https://github.com/apache/commons-compress/actions
Or are you talking about a different buils?

**Comment by jonathanmetzman** [comment]
Sorry, I'm referring to the builds of the fuzzers in OSS-Fuzz https://github.com/google/oss-fuzz/actions/runs/4982264234/jobs/8917674872 https://github.com/google/oss-fuzz/actions/runs/4982264234/jobs/8917675329

**Pull request merged**
