### PR TITLE
infra: add proj name to env for fuzz introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Depends on https://github.com/ossf/fuzz-introspector/pull/327

Ref: https://github.com/ossf/fuzz-introspector/issues/317

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
need to bump too when the fuzz-introspector PR is merged

**Comment by Navidem** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

**Comment by DavidKorczynski** [comment]
> /gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

Quick heads up -- the testing should fail as this line  https://github.com/google/oss-fuzz/pull/7856/files#diff-43e6fb06733014791deb946732e00f7aa84e62bd1d856b363e5be922573a0e0dR243 depends on merging https://github.com/ossf/fuzz-introspector/pull/327 -- i.e. the `main.py` does not accept `--name` before merge and should fail because of this

**Comment by DavidKorczynski** [comment]
@Navidem updated now

**Comment by DavidKorczynski** [comment]
> > > /gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer
> > 
> > 
> > Quick heads up -- the testing should fail as this line https://github.com/google/oss-fuzz/pull/7856/files#diff-43e6fb06733014791deb946732e00f7aa84e62bd1d856b363e5be922573a0e0dR243 depends on merging [ossf/fuzz-introspector#327](https://github.com/ossf/fuzz-introspector/pull/327) -- i.e. the `main.py` does not accept `--name` before merge and should fail because of this
> 
> This is more to test regression on other builds. I expect this trial_build to succeed, as it is not an introspector build.

Ah, sounds good

**Comment by Navidem** [comment]
Is it normal `test_projects.py` take over 1 hour? I am not seeing any progress when running locally.
Will check it again in the morning.

**Comment by DavidKorczynski** [comment]
Yeah it should take more than 1 hour, but less than 2. You see no progress? as in, what's the log and what about the processes running? Also make sure to have this update https://github.com/ossf/fuzz-introspector/pull/328 -- am not 100% sure if it's needed but it could be.

**Comment by Navidem** [comment]
> Yeah it should take more than 1 hour, but less than 2. You see no progress? what's the log/output and what about the processes running? Also make sure to have this update [ossf/fuzz-introspector#328](https://github.com/ossf/fuzz-introspector/pull/328) -- am not 100% sure if it's needed but it could be.

Went on successfully after removing the previous `oss-fuzz` dir, and re-building images.

**Review by Navidem — APPROVED** [review]
LGTM

**Pull request merged**
