### PR TITLE
Get rid of :introspector images. Build introspector in main images

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Actually install introspector in every image.
Don't do extra introspector build steps.
Fixes https://github.com/google/oss-fuzz/issues/8625

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector address coverage memory undefined --fuzzing-engine libfuzzer afl centipede honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer coverage address memory undefined introspector --fuzzing-engine libfuzzer

**Review by Navidem — APPROVED** [review]
LGTM, thanks for finishing it up.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer --force-build

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer --force

**Comment by jonathanmetzman** [comment]
Cancelled the last builds due to some confusion

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer --force

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer introspector --fuzzing-engine libfuzzer --force

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector --fuzzing-engine libfuzzer --force

**Pull request merged**
