### PR TITLE
[espv2] Fix build failures due to OOM

### PR DESCRIPTION
**Pull request by nareddyt**
- ESPv2 builds have been failing with OOM since we updated our envoy dependency. Example error is below. Copy relevant portions from Envoy's build script to workaround this issue.
- Fix ubsan and coverage build by moving a `--copt` to only be defined in address builds.
- Update primary contact for the project due to a change in team members.

```
Step #13: (11:02:55) [3,248 / 3,318] Compiling external/envoy/test/mocks/router/mocks.cc; 2034s linux-sandbox ... (32 actions running)
Step #13: 
Step #13: Server terminated abruptly (error code: 14, error message: 'Socket closed', log file: '/builder/home/.cache/bazel/_bazel_root/28d323c1ffc0c0ec503bc89d22bdf549/server/jvm.out')
Step #13: 
Step #13: rules_foreign_cc: Cleaning temp directoriesrules_foreign_cc: Cleaning temp directoriesrules_foreign_cc: Cleaning temp directoriesrules_foreign_cc: Cleaning temp directories********************************************************************************
Step #13: Failed to build.
Step #13: To reproduce, run:
Step #13: python infra/helper.py build_image esp-v2
Step #13: python infra/helper.py build_fuzzers --sanitizer undefined --engine libfuzzer --architecture x86_64 esp-v2
Step #13: ********************************************************************************
Finished Step #13
ERROR
ERROR: build step 13 "gcr.io/oss-fuzz/esp-v2" failed: step exited with non-zero status: 1
```

Signed-off-by: Teju Nareddy <nareddyt@google.com>

### CODE REVIEW

**Comment by nareddyt** [comment]
Hi @asraa, were there any other changes Envoy made to work around the OOMs earlier in the year? This is the only relevant portion I could find in the build scripts.

**Comment by asraa** [comment]
Yes! making sure there's enough memory per thread has solved our OOM issues so far (once we needed to re-tune).

**Comment by inferno-chromium** [comment]
can you check ubsan and coverage failures

```
Execution platform: @local_config_platform//:host

Use --sandbox_debug to see verbose messages from the sandbox
(18:57:52) [2,065 / 2,072] ...n_info_proto_cc_proto_validate; 0s linux-sandbox

clang-12: warning: '-fuse-ld=' taking a path is deprecated. Use '--ld-path=' instead
bazel-out/k8-fastbuild/bin/external/envoy/test/mocks/upstream/_objs/cluster_manager_mocks/cluster_manager.pic.o:cluster_manager.cc:function absl::container_internal::SanitizerUnpoisonMemoryRegion(void const*, unsigned long): error: undefined reference to '__asan_unpoison_memory_region'
bazel-out/k8-fastbuild/bin/external/envoy/source/common/config/_objs/config_provider_lib/config_provider_impl.pic.o:config_provider_impl.cc:function absl::container_internal::SanitizerPoisonMemoryRegion(void const*, unsigned long): error: undefined reference to '__asan_poison_memory_region'
bazel-out/k8-fastbuild/bin/external/envoy/source/common/http/_objs/filter_manager_lib/filter_manager.pic.o:filter_manager.cc:function absl::base_internal::UnalignedLoad64(void const*): error: undefined reference to '__sanitizer_unaligned_load64'
bazel-out/k8-fastbuild/bin/external/envoy/source/common/http/_objs/filter_manager_lib/filter_manager.pic.o:filter_manager.cc:function absl::base_internal::UnalignedLoad32(void const*): error: undefined reference to '__sanitizer_unaligned_load32'
external/com_google_absl/absl/container/fixed_array.h:894: error: undefined reference to '__sanitizer_annotate_contiguous_container'
bazel-out/k8-fastbuild/bin/external/envoy/source/common/upstream/_objs/load_balancer_lib/load_balancer_impl.pic.o:load_balancer_impl.cc:function absl::FixedArray<unsigned long, 18446744073709551615ul, std::__1::allocator<unsigned long> >::NonEmptyInlinedStorage::AnnotateConstruct(unsigned long): error: undefined reference to '__sanitizer_annotate_contiguous_container'
external/com_google_absl/absl/container/fixed_array.h:810: error: undefined reference to '__sanitizer_annotate_contiguous_container'
bazel-out/k8-fastbuild/bin/external/envoy/source/common/upstream/_objs/load_balancer_lib/load_balancer_impl.pic.o:load_balancer_impl.cc:function absl::FixedArray<unsigned long, 18446744073709551615ul, std::__1::allocator<unsigned long> >::NonEmptyInlinedStorage::AnnotateDestruct(unsigned long): error: undefined reference to '__sanitizer_annotate_contiguous_container'
bazel-out/k8-fastbuild/bin/external/com_google_absl/absl/strings/_objs/internal/escaping.pic.o:escaping.cc:function absl::base_internal::UnalignedLoad16(void const*): error: undefined reference to '__sanitizer_unaligned_load16'
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
(18:57:52) [2,065 / 2,072] ...n_info_proto_cc_proto_validate; 0s linux-sandbox

(18:57:53) INFO: Elapsed time: 7106.843s, Critical Path: 201.95s
(18:57:53) [2,066 / 2,072] checking cached actions

(18:57:53) INFO: 1608 processes: 1607 linux-sandbox, 1 local.
(18:57:53) [2,066 / 2,072] checking cached actions

(18:57:53) FAILED: Build did NOT complete successfully

(18:57:53) FAILED: Build did NOT complete successfully
Building fuzzers failed.
Running: docker build -t gcr.io/oss-fuzz/esp-v2 projects/esp-v2
Keeping existing build artifacts as-is (if any).
Running: docker run --rm --privileged --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=undefined -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c++ -v /home/runner/work/oss-fuzz/oss-fuzz/build/out/esp-v2:/out -v /home/runner/work/oss-fuzz/oss-fuzz/build/work/esp-v2:/work -t gcr.io/oss-fuzz/esp-v2
Building project esp-v2
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_fuzzers esp-v2 --engine libfuzzer --sanitizer undefined --architecture x86_64
Failed projects: esp-v2
Error: Process completed with exit code 1.
```

**Comment by nareddyt** [comment]
All the jobs now fail with the following error:

```
ERROR: [0m/src/esp-v2/tests/fuzz/structured_inputs/BUILD:45:1: undeclared inclusion(s) in rule '//tests/fuzz/structured_inputs:service_control_filter_proto_cc_proto':
2020-10-29T00:31:18.7380297Z this rule is missing dependency declarations for the following files included by 'tests/fuzz/structured_inputs/service_control_filter.pb.cc':
2020-10-29T00:31:18.7381473Z   'bazel-out/k8-fastbuild/bin/external/com_google_googleapis/google/api/resource.pb.h'
2020-10-29T00:31:18.7382329Z (00:31:18) [32m[3,241 / 3,290][0m ...//google/api:monitored_resource_proto; 0s local
```

Fairly certain this is a problem in our repository that we can fix. Can we merge in this PR in the meantime?

**Comment by nareddyt** [comment]
Well actually I changed the spawn strategy, maybe that is affecting it. I will change back.

**Comment by nareddyt** [comment]
FYI coverage error is:

```
2020-10-29T05:18:33.0108508Z + cp bazel-bin/src/envoy/http/path_matcher/path_matcher_filter_fuzz_test_driverless /out/path_matcher_filter_fuzz_test
2020-10-29T05:19:07.7562515Z cp: error writing '/out/path_matcher_filter_fuzz_test': No space left on device
2020-10-29T05:19:11.3135767Z Building fuzzers failed.
```

It'll probably work fine when actually building in OSS Fuzz instead of CI.

**Comment by inferno-chromium** [comment]
> FYI coverage error is:
> 
> ```
> 2020-10-29T05:18:33.0108508Z + cp bazel-bin/src/envoy/http/path_matcher/path_matcher_filter_fuzz_test_driverless /out/path_matcher_filter_fuzz_test
> 2020-10-29T05:19:07.7562515Z cp: error writing '/out/path_matcher_filter_fuzz_test': No space left on device
> 2020-10-29T05:19:11.3135767Z Building fuzzers failed.
> ```
> 
> It'll probably work fine when actually building in OSS Fuzz instead of CI.

Yes right.!

**Pull request merged**
