### PR TITLE
OpenSC: added fuzzing tests

### PR DESCRIPTION
**Pull request by frankmorgner**

### CODE REVIEW

**Comment by frankmorgner** [comment]
How can I reproduce the AFL build problem locally?

**Comment by jonathanmetzman** [comment]
`python infra/helper.py build_fuzzers opensc --engine afl` should repro

**Comment by frankmorgner** [comment]
[OpenSSL solved this problem by using `clang++` as loader](https://github.com/google/oss-fuzz/issues/1037), which I couldn't achieve by simply passing `LD=clang++` to `./configure` or `make` (`libtool` still uses `clang` instead)...

[oss-fuzz has an open issue about the build problem](https://github.com/google/oss-fuzz/issues/2164) and I tried using [`FUZZING_LIBS="-fsanitize=fuzzer"` instead of `FUZZING_LIBS="$LIB_FUZZING_ENGINE"`](https://github.com/google/oss-fuzz/pull/2726/commits/d9fc4587945b3f95710387eb7df499d86e29346e), which works locally (`python infra/helper.py check_build opensc --engine afl && python infra/helper.py check_build opensc --engine afl`), but CI [still complains about broken fuzzing binaries in case of using AFL](https://travis-ci.org/google/oss-fuzz/jobs/574863508)...

I'm not sure how to proceed, do you have any advice?

**Comment by jonathanmetzman** [comment]
>`FUZZING_LIBS="-fsanitize=fuzzer" instead of FUZZING_LIBS="$LIB_FUZZING_ENGINE`

Please don't do this. It will certainly fail for AFL and any other engine we would like to build with in the future.

I'm not sure why you say this works because AFAIK it should definitely fail. Was this command:

>(python infra/helper.py check_build opensc --engine afl && python infra/helper.py check_build opensc --engine afl)

A typo? Because to test it should be: `python infra/helper.py build_fuzzers opensc --engine afl && python infra/helper.py check_build opensc --engine afl`

Since `FUZZING_LIBS="$LIB_FUZZING_ENGINE` worked for libFuzzer but not AFL previously, and we can't figure out why AFL isn't working, let's just switch back to `FUZZING_LIBS="$LIB_FUZZING_ENGINE` and add
```
engines:
  - libFuzzer
```

to the project.yaml to disable AFL.

It isn't the end of the world if we don't use AFL, so if it is to much trouble just give up on it :-)

**Comment by frankmorgner** [comment]
> > (python infra/helper.py check_build opensc --engine afl && python infra/helper.py check_build opensc --engine afl)
> 
> A typo? Because to test it should be: `python infra/helper.py build_fuzzers opensc --engine afl && python infra/helper.py check_build opensc --engine afl`

Yes, indeed that was a typo.

The build now passes with limiting the scope to libFuzzer

**Pull request merged**
