### PR TITLE
[centipede] fix sanitizer issue in bad build check

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
You need something like this to get bad build check (and CI) working for centipede (at least temporarily)

**Comment by jonathanmetzman** [comment]
Note that our CI calls helper.py so you can reproduce failures in CI by calling build_fuzzers and check_build with helper.py

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
Thanks! I reckon this is the simplest way to solve the CI failure in #8690, but it also disables sanitizer checking.
I think I will be able to fix it in a different way in #8697, which could be overkill but could keep the sanitizer checks and add new tests.
If I failed, I will happily merge this instead : )

**Comment by Alan32Liu** [comment]
IIUC, we've made #8697 succeed: )

**Pull request closed without merging**
