### PR TITLE
[fuzzbench] Added Command-Line Argument for Fuzzing Engine Selection in FuzzBench Integration

### PR DESCRIPTION
**Pull request by Shivam7-1**
About PR:
This PR introduces a command-line argument to specify the fuzzing engine in fuzzbench, replacing the hard-coded value for enhanced flexibility and usability. This enhancement supports seamless integration of new fuzzing engines.

The modification aims to improve the fuzzbench script's adaptability and enable potential performance advancements by allowing users to define the fuzzing engine directly.

### CODE REVIEW

**Comment by Shivam7-1** [comment]
Hii @jonathanmetzman 
Could You Please Review This PR 
Thanks

**Comment by jonathanmetzman** [comment]
Could you explain why this is useful? Are you using this and need this feature?

**Comment by Shivam7-1** [comment]
Hii @jonathanmetzman Thanks For Reviewing 
This change is based on a TODO in the original code, which suggests making the fuzzing engine selection a command-line argument rather than a hard-coded value. Implementing this change provides greater flexibility, as it allows users to specify different fuzzing engines without needing to modify the code directly. This is especially useful for testing and benchmarking multiple fuzzing engines within the FuzzBench framework, potentially optimizing results or enabling new fuzzing strategies.

By making this feature a command-line argument, this update also makes fuzzbench easier to integrate with continuous integration (CI) setups and other automated environments, as it reduces the need for custom code modifications each time a different fuzzing engine is required.

Thanks

**Comment by Shivam7-1** [comment]
Hii @jonathanmetzman Do  required any other information?
Thanks

**Comment by Shivam7-1** [comment]
Hii @jonathanmetzman
Is there Anything Else is Required From My Side?
 Do required any other information?
Thanks

**Comment by jonathanmetzman** [comment]
Thanks for the PR. 
I don't think I will merge this. This feature isn't really supported and I don't want to add code that people wont use.

**Comment by Shivam7-1** [comment]
Hii @jonathanmetzman 
Thanks For Reviewing 
But in the Original Code it is TODO task which is commented 
So I think it would be pending task?
Regards

**Comment by jonathanmetzman** [comment]
Sorry. I'm not going to merge this now.

**Pull request closed without merging**
