### PR TITLE
bitcoin-core: Enable libc++ "Debug" hardening mode

### PR DESCRIPTION
**Pull request by hebasto**
This PR enables libc++ "Debug" hardening mode.

See https://github.com/google/oss-fuzz/pull/11725#issuecomment-2084937398.

### CODE REVIEW

**Comment by hebasto** [comment]
cc @maflcko @fanquake

**Comment by fanquake** [comment]
Seems fine as long as we still have LTO. Although not sure if the flags will make any difference here? given builds are with libc++, and the LLVM debug mode wont work as-is as far as I'm aware (It's also the legacy mode).

**Review by DavidKorczynski — COMMENTED** [review]
Based on the comments in the PR I'm not entirely sure if the Bitcoin maintainers would like to see this merged? @maflcko

**Comment by fanquake** [comment]
> I think it is fine, but let's wait for clang-18-trunk, so that it can be tested :)

If Clang is bumped to 18 then https://github.com/bitcoin/bitcoin/pull/29781 will also be needed, as the current macro will still be a no-op.

**Comment by DonggeLiu** [comment]
Thanks @hebasto and @maflcko,
I will convert this to a draft for now until it is verified : )

**Comment by hebasto** [comment]
> This should be good to go now. Please merge or rebase with master.

Rebased.

**Comment by fanquake** [comment]
The added comment says we aren't using CPPFLAGS, but then a few lines down we do use it.

Given we established the other flags mentioned in your PR description don't actually matter (could also be re-written now that it's outdated), why not just put `-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG` into CPPFLAGS, and leave everything else untouched?

**Comment by hebasto** [comment]
> The added comment says we aren't using CPPFLAGS, but then a few lines down we do use it.
> 
> Given we established the other flags mentioned in your PR description don't actually matter (could also be re-written now that it's outdated), why not just put `-D_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_DEBUG` into CPPFLAGS, and leave everything else untouched?

Thanks! Reworked.

**Review by fanquake — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Apologies for the delay! Will land this once the CI is green!

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
