### PR TITLE
[pidgin] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds initial integration of Pidgin IM

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@grimmy - can you please help to review.

@AdamKorcz - really appreciate your efforts to find vulns in pidgin!

**Comment by DavidKorczynski** [comment]
@grimmy - @AdamKorcz and I are looking at getting more fuzzers for Pidgin, at the moment we just got an initial set up going for one of the xml functions, but we should have more fuzzers shortly targeting other parts of the pidgin code.

**Comment by grimmy** [comment]
Hiya, sorry just now noticed this. I'm pretty new to fuzzing... Like I understand what it does, but, like I signed up on this repo years ago and then never got around to digging into it. I'm more than happy to help review and of course fix whatever, but I'm going to need a bit of direction here.

As for what else to fuzz, I'd say probably `irc_parse_msg` from `libpurple/protocols/irc/parse.c` and basically every `purple_markup_*` in `libpurple/util.c`.

Also I just released 2.14.5 last night that plugged a bunch of issues scan-build found but none of those seemed concerning.

**Comment by DavidKorczynski** [comment]
Wonderful @grimmy - I think we are in a good place now to get this merged then, as it should give us some initial results. We target several of the `purple_markup_*` functions and I will take a look at the `irc_parse_msg` in the future. It will also be easier to identify what parts we are missing once we get coverage out. I updated to use the latest version of pidgin. 

Feel free to pings us here or just create an issue if you face problems or have questions, meanwhile we will continue to get some more fuzzers up.

**Comment by DavidKorczynski** [comment]
@inferno-chromium this one should be good to go.

**Review by inferno-chromium — APPROVED** [review]
Thanks a lot!

**Comment by grimmy** [comment]
So my biggest question is, if the fuzzers find something, where is that reported?

**Comment by inferno-chromium** [comment]
> So my biggest question is, if the fuzzers find something, where is that reported?

They are reported in a secure issue tracker, see here - https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label:Proj-pidgin
once bugs are fixed, oss-fuzz auto-verifies and closes them. you should be getting emails on  gary.kramlich [at] gmail

**Comment by JordyZomer** [comment]
Hey @inferno-chromium and @DavidKorczynski !

I recently added built-in fuzzing support to pidgin2, you'll be able to find my changes in:

https://keep.imfreedom.org/pidgin/pidgin/rev/97c51d97d375

Perhaps we can work together and get your fuzzers in the build-system as well? :)

Best Regards,

Jordy

**Comment by inferno-chromium** [comment]
@JordyZomer - you can always upload a PR to get them in - https://github.com/google/oss-fuzz/blob/master/projects/pidgin/build.sh
test locally using https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally

**Comment by grimmy** [comment]
From the requirements on https://google.github.io/oss-fuzz/getting-started/integration-rewards/, upstream integration in the project is key. Also we would like to do as much of this as we can as we could very much use any funding assuming Google is still giving away this award.

**Comment by inferno-chromium** [comment]
> From the requirements on https://google.github.io/oss-fuzz/getting-started/integration-rewards/, upstream integration in the project is key. Also we would like to do as much of this as we can as we could very much use any funding assuming Google is still giving away this award.

Sure, lets have you do the ideal integration and fetch those rewards.

**Comment by DavidKorczynski** [comment]
It would be nice migrating all of it together in one place, although it seems there is a fair amount of overlap in terms of coverage the fuzzers added to the main repo as the ones we have here. @grimmy - did you look at the initial results from the fuzzers and are they useful?

**Comment by QuLogic** [comment]
Is there a particular reason that libxml2 and glib2 had to be built from source instead of using apt packages?

**Comment by DavidKorczynski** [comment]
> Is there a particular reason that libxml2 and glib2 had to be built from source instead of using apt packages?

I cant remember specifics now, but most likely it had something to do with the final linking - namely that we needed static libraries. If you look around oss-fuzz glib2 is build from source in several projects. 

If you can get it to work without building from source then that's perfect.

**Pull request merged**
