### PR TITLE
Trial builds for fuzz introspector

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer introspector --fuzzing-engine libfuzzer

**Review by Navidem — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py libpng --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
Thanks @jonathanmetzman !

**Pull request merged**
