### PR TITLE
cbor-java: initial integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Integrating cbor-java. I mainly integrated this because it's part of the external libraries on the Android platform (https://android.googlesource.com/platform/external/cbor-java)

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@bbadour - would you be interested in getting cbor-java fuzzed? I am asking you here as I see your name on the log of cbor-java https://android.googlesource.com/platform/external/cbor-java/+log

**Comment by c-rack** [comment]
@DavidKorczynski yes, that would be very appreciated!

**Comment by DavidKorczynski** [comment]
Wonderful @c-rack - the only thing needed is an email(s) connected to a Google account that can be used for receiving the bugs reports, which email can I use?

**Comment by DavidKorczynski** [comment]
@c-rack ping?

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
