### PR TITLE
[ninja] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds initial integration of Ninja.

We are currently waiting for the fuzzer and build script to be merged upstream: https://github.com/ninja-build/ninja/pull/1893

For the Ninja maintainers: The files in this PR allows the fuzzer in the PR above to be run continuously. All that is needed on this side is at least one maintainers email address in the project.yaml file. You can add it per your convenience or you can leave your email address in this thread and I will make sure to add it. The list can be changed at any time by making a pull request with the desired changes. If you have any questions about this integration, feel free to drop them in this PR or in the PR on the Ninja repository. Please note that I have added my own email address on the mailing list to see the integration through to completion. This does mean that all bugs and vulnerabilities will be visible by me as all email addresses on that list will have access to these, and if you prefer me off the list, just let me know, and I will remove myself.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
@jhasse The integration now runs end-to-end and the last step is to provide at least one maintainers email address for bug reports. Is that something you can help with?

**Comment by inferno-chromium** [comment]
can add @nico email as well.

**Comment by AdamKorcz** [comment]
> can add @nico email as well.

Sure. Are we waiting for a confirmation from Nico, or can we add?

**Comment by inferno-chromium** [comment]
lets wait on @jhasse and @nico to respond.

**Comment by jhasse** [comment]
You can put in jhasse@bixense.com

**Comment by AdamKorcz** [comment]
@jonathanmetzman @inferno-chromium With one maintainers email address having been added, I am marking this one as ready for review.

**Review by inferno-chromium — APPROVED** [review]

**Comment by jhasse** [comment]
It seems that it would be better if you add my Google Account. Because as it is right now, I can't access the reports. Can you change the mail to jhasse@gmail.com?

**Comment by inferno-chromium** [comment]
> It seems that it would be better if you add my Google Account. Because as it is right now, I can't access the reports. Can you change the mail to [jhasse@gmail.com](mailto:jhasse@gmail.com)?

done, should show in 30 min or so.

**Comment by nico** [comment]
Please don't auto-cc me.

FWIW we used to have an oss-fuzzer of the parser but we deleted it many years ago. Ninja doesn't free memory for speed reasons (and since it's a run-then-quit app), which isn't great for fuzzing. And the fuzzer didn't find anything interesting after the initial bugs (other than lots of OOM) back then.

**Comment by AdamKorcz** [comment]
> Please don't auto-cc me.
> 
> FWIW we used to have an oss-fuzzer of the parser but we deleted it many years ago. Ninja doesn't free memory for speed reasons (and since it's a run-then-quit app), which isn't great for fuzzing. And the fuzzer didn't find anything interesting after the initial bugs (other than lots of OOM) back then.

Removing you shortly.

Yeah I noticed the issues you raise with Ninja. Do you happen to know how extensive of a task it would be to add a "DWITH_OSS_FUZZ" that would then free memory when fuzzing? Are we getting deep into the mechanics of Ninja?

**Pull request merged**
