### PR TITLE
add a fuzz driver of fzf

### PR DESCRIPTION
**Pull request by secsys-go**
Overview
The purpose of this fuzz driver is to rigorously test the Tokenize API in fzf project by injecting mutated data into its arguments. By doing so, we aim to enhance our continuous testing efforts and ensure the robustness of this API.

Details
The fuzz driver has been designed to thoroughly exercise the Tokenize API.
It accomplishes this by systematically injecting various forms of mutated data into the API's arguments.
Through this approach, we identified potential vulnerabilities and edge cases that might otherwise go unnoticed.

### CODE REVIEW

**Comment by secsys-go** [comment]
We have sent an invitation to project maintainer to help us review this PR.

**Comment by DonggeLiu** [comment]
> We have sent an invitation to project maintainer to help us review this PR.

Thanks, @secsys-go! Do you happen to have any updates?

**Comment by dvaldivia** [comment]
@DonggeLiu 🚩🚩🚩 I urge you no to take this PR, seems oddly suspicious given the pattern of behavior of this account, other contributions have been flagged as well https://github.com/go-gitea/gitea/pull/26954#issuecomment-1710683316

**Comment by DonggeLiu** [comment]
> go-gitea/gitea#26954 (comment)

Yep, thanks for reporting this!
We will not merge PRs unless they are approved by the project's maintainer.

Given the context you provided, I will close this PR.

**Pull request closed without merging**
