### PR TITLE
[meshoptimizer] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds initial integration of Meshoptimizer.

For this integration a fuzzer has been added upstream: https://github.com/zeux/meshoptimizer/pull/209 and we are currently working on updates in the build system upstream: https://github.com/zeux/meshoptimizer/pull/212/files

### For the Meshoptimizer maintainers (@zeux):
The files in this PR allows Meshoptimizer fuzzer to be run continuously. All that is needed on this side is at least one maintainers email address in the `project.yaml` file. You can add it per your convenience or you can leave your email address in this thread and I will make sure to add it. The list can be changed at any time by making a pull request with the desired changes. If you have any questions about this integration, feel free to drop them in this PR or in the PR on the Meshoptimizer repository. Please note that I have added my own email address on the mailing list to see the integration through to completion. This does mean that all bugs and vulnerabilities will be visible by me as all email addresses on that list will have access to these, and if you prefer me off the list, just let me know, and I will remove myself.

### CODE REVIEW

**Comment by zeux** [comment]
Please add `arseny.kapoulkine@gmail.com` to the e-mail list. You're welcome to keep your own.

**Comment by AdamKorcz** [comment]
@inferno-chromium @jonathanmetzman Ready for review.

**Review by jonathanmetzman — APPROVED** [review]
Thanks. I'm finding out right now if we want to accept this project. If so I will merge.

**Comment by jonathanmetzman** [comment]
Please fix the issues I pointed out.

**Pull request merged**
