### PR TITLE
Make `Centipede` a default fuzzing engine

### PR DESCRIPTION
**Pull request by Alan32Liu**
1. Add `centipede` to `DEFAULT_ENGINES`.
2. Remove the `fuzzing_engines` attribute from `project.yaml`s if redundant (i.e., all default engines are included in that YAML file).
3. Temporarily disable `centipede` on `c`/`c++` projects that previously use all `DEFAULT_ENGINES` (200 projects did not specify `fuzzing_engines` in `project.yaml`) so that we can gradually enable centipede later them later.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
`presubmit` failed due to missing `main_repo` in some projects:
```
Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/lzma/project.yaml: main_repo section is missing.
Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/freeimage/project.yaml: main_repo section is missing.
Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/xpdf/project.yaml: main_repo section is missing.
Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/lzo/project.yaml: main_repo section is missing.
Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/dlplibs/project.yaml: main_repo section is missing.
Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/xerces-c/project.yaml: main_repo section is missing.
Failed.
```

Shall I contact their owners to add that?

**Comment by oliverchang** [comment]
> `presubmit` failed due to missing `main_repo` in some projects:
> 
> ```
> Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/lzma/project.yaml: main_repo section is missing.
> Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/freeimage/project.yaml: main_repo section is missing.
> Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/xpdf/project.yaml: main_repo section is missing.
> Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/lzo/project.yaml: main_repo section is missing.
> Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/dlplibs/project.yaml: main_repo section is missing.
> Error in /home/runner/work/oss-fuzz/oss-fuzz/projects/xerces-c/project.yaml: main_repo section is missing.
> Failed.
> ```
> 
> Shall I contact their owners to add that?

Just ignore for now and file a bug :) We can probably just add this ourselves very quickly.

**Comment by Alan32Liu** [comment]
The trial build failed due to [a temporary build failure in project `minizip`](https://oss-fuzz-build-logs.storage.googleapis.com/index.html#minizip).
It's not specific to `Centipede`.
Other projects seem to build fine.

**Review by oliverchang — APPROVED** [review]
LGTM assuming all the failures are unrelated to your change!

**Comment by Alan32Liu** [comment]
> LGTM assuming all the failures are unrelated to your change!

There is one `Infra tests`, I am fixing it now : )

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
@oliverchang, I found an undesired side effect of a previous decision and am unsure what's the best way to address it.
We [append 'none' to sanitizers](https://github.com/google/oss-fuzz/blob/fb32d86890a4c97cbd50129ada8987de7305e74a/infra/build/functions/build_project.py#L126) for `Centipede` so that it can have an unsanitized binary for fuzzing.
However, that [affects the build steps of `libFuzzer`](https://github.com/google/oss-fuzz/pull/10109/commits/1e5192342c26d60e617d3e63181c186d480a8708) because `none` is also [a supported sanitizer of it](https://github.com/google/oss-fuzz/blob/fb32d86890a4c97cbd50129ada8987de7305e74a/infra/build/functions/build_lib.py#L63). I don't think those build steps are necessary because they only exist because we manually appended `none`.

This was not an issue until we made `Centipede` a default fuzzer in this PR.

Should we tolerate this undesired extra build or is there any way to avoid it?

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
Passed `trial-build`.
The build test error in `libfuzzer, address/coverage`  seems irrelevant.

**Pull request merged**
