### PR TITLE
java: Fix bash escaping in memory setting logic

### PR DESCRIPTION
**Pull request by fmeum**
These issues were missed in 5b1953b20174adca72d06a8b4e893a46591b7f4a and prevent the new logic from applying correctly for some projects.

### CODE REVIEW

**Comment by fmeum** [comment]
@jonathanmetzman

**Comment by jonathanmetzman** [comment]
Fabian can you add another trigger file.
@Navidem can you test this using trial builds and merge it if it works? The current sheriff is Oliver.

**Comment by fmeum** [comment]
@jonathanmetzman Added the file.

I first thought I would just delete the previous one, but you already deleted it. Thanks for keeping infra tidy :-)

**Comment by Navidem** [comment]
/gcbrun trial_build.py all --sanitizer address coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
> @Navidem can you test this using trial builds and merge it if it works? The current sheriff is Oliver.

trial_build is timing out. Will try a lighter one.

**Comment by Navidem** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Comment by fmeum** [comment]
@Navidem I found more syntax errors in a subset of the projects and pushed a new commit to fix them.

**Comment by Navidem** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
> trial_build is timing out. Will try a lighter one.

You can ignore the timeouts.

**Comment by Navidem** [comment]
/gcbrun trial_build.py java-example jetty smh mysql-connector-j protobuf-java retrofit rxjava spring-amp spring-boot-actuator spring-boot spring-cloud-commons spring-data-jpa spring-data-keyvalye spring-data-mongodb spring-data-redis spring-framework spring-integration spring-ldap spring-retry spring-security spring-shell tomcat --sanitizer address --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
Trial build succeeds on the affected projects. 

Project tests need attention @fmeum.

**Comment by fmeum** [comment]
@Navidem Java projects don't usually build with the "undefined" sanitizer. The error seems to be related to centipede:
```
2022/10/25 14:34:08 could not resolve the version 'latest' to an actual version number: unable to determine latest version: could not list available releases for 5.3.2: could not list GCS objects at https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/&prefix=5.3.2/release/: unexpected status code while reading https://www.googleapis.com/storage/v1/b/bazel/o?delimiter=/&prefix=5.3.2/release/: 503
The command '/bin/sh -c precompile_centipede' returned a non-zero code: 1
```

**Comment by Navidem** [comment]
For the record build test for address is timing out, and the build test for address is running out of disk.

**Review by Navidem — APPROVED** [review]
LGTM

**Pull request merged**
