### PR TITLE
infra: base-runner: add filtering to python cov reports

### PR DESCRIPTION
**Pull request by DavidKorczynski**
This is to avoid reporting coverage on files that are essentially not part of a given project, which butchers the summarised coverage stats at the moment.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
An example is https://storage.googleapis.com/oss-fuzz-coverage/pyyaml/reports/20230213/linux/index.html where this addition will cause the report to only be based on the `site-packages/yaml` files and the fuzzer files.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py python --engine libfuzzer --sanitizer coverage

**Comment by DavidKorczynski** [comment]
@jonathanmetzman please do let me know any failures this caused in the trial run as I wasn't expecting any

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py python --fuzzing-engine libfuzzer --sanitizers coverage

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman please do let me know any failures this caused in the trial run as I wasn't expecting any

You can now see the results (after the test completes) of gcbrun. I think this error was just due to me holding it wrong.

**Comment by DavidKorczynski** [comment]
Am not entirely sure how to interpret the output, but it seems like there's some timeout in psycopg2 -- this should be unrelated to the PR I recon.

**Comment by oliverchang** [comment]
/gcbrun trial_build.py psycopg2 --fuzzing-engine libfuzzer --sanitizers coverage

**Comment by oliverchang** [comment]
(all checks passed prior to the master merge)

**Comment by oliverchang** [comment]
/gcbrun trial_build.py psycopg2 --fuzzing-engine libfuzzer --sanitizers coverage

**Review by AdamKorcz — APPROVED** [review]

**Pull request merged**
