### PR TITLE
dozer: initial integration

### PR DESCRIPTION
**Pull request by arthurscchan**
Initial integration for project dozer.

### CODE REVIEW

**Review by DavidKorczynski — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
Since dozer is being deprecated maybe lets skip this

**Comment by jonathanmetzman** [comment]
See the README: https://github.com/DozerMapper/Dozer

**Comment by Alan32Liu** [comment]
+1 on skipping this due to likely deprecation.

**Comment by DavidKorczynski** [comment]
Closing due to project being made deprectated.

**Pull request closed without merging**
