### PR TITLE
new: dpp project

### PR DESCRIPTION
**Pull request by braindigitalis**
requesting merge of this project so that i may use the fuzz suite.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Who are some users of dpp?

**Comment by braindigitalis** [comment]
does it have to be a critical project? Nothing in your documentation said you were selective about which projects could use this facility?
What defines a critical project?
It is used by thousands of C++ developers to develop discord bots. I do not keep metrics, beyond what GitHub provide.

**Comment by jonathanmetzman** [comment]
> does it have to be a critical project? Nothing in your documentation said you were selective about which projects could use this facility? What defines a critical project? It is used by thousands of C++ developers to develop discord bots. I do not keep metrics, beyond what GitHub provide.

Do you happen to know of any high profile users?

To some extent, yes, it does need to be critical for us to accept it, see [these docs.](https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/) I'll ask the team what they think.

**Comment by braindigitalis** [comment]
I guess i count as a high profile user myself. I run a bot using this library which is my livelihood, and also has 200,000 discord servers using it, visible to approximately 41 million people on discord.
The stats for that are here: https://triviabot.co.uk/botstats/
There are potentially many other bots of this kind of size using the library, but as we do not require attribution i have no way to tell. It is also being integrated into games and mods. I'll leave it with you and the team.

I found my way here while trying to improve the security of the project.

To be honest, after submitting here i felt that this was a bigger thing than i'd anticipated, and happy to work with you in whatever is needed to proceed if we can.

**Comment by jonathanmetzman** [comment]
We approve. Do you still want to join OSS-Fuzz?

**Comment by jonathanmetzman** [comment]
> yes please! What is the next step?

Wait for bug!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
