### PR TITLE
croaring: fix cpp fuzz harness

### PR DESCRIPTION
**Pull request by lemire**
@silvergasp contributed a great test function in https://github.com/google/oss-fuzz/pull/9794

It quickly found a new bug. Great.

Unfortunately, it is now running out of memory without bugs, causing false-positive reports. The problem is that a single bitmap may use slightly over 512 MB, furthermore, the function serialize the bitmap to a 32-bit array, which may lead to gigabytes of memory usage.

I propose to replace the unbounded `ConsumeIntegral<uint32_t>()` throughout by `ConsumeIntegralInRange<uint32_t>(range_start, range_end)` for reasonable range values. This should avoid unreasonable memory usage in the normal course of operation. That is, we want that an out-of-memory error has to do with a bug.

cc @K2  @DavidKorczynski

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Does it make sense to move the fuzzers upstream in the Croaring library? That would be great since then you can patch them without going through OSS-Fuzz?

**Comment by lemire** [comment]
I don’t expect to bug you repeatedly. Even so, if someone wants to issue a PR to CRoaring, it will be accepted.

Meanwhile I recommend accepting my PR. I promise not to issue PRs repeatedly. I am only doing it now because I am facing a false-positive and I need to sort it out. I take bug reports seriously.

**Review by DavidKorczynski — APPROVED** [review]
LGTM

Thanks @lemire!

@silvergasp could you help navigate the fuzzers upstream?

**Comment by DavidKorczynski** [comment]
Thanks @lemire -- I did not mean that your PRs are bugging! It was more that you can have complete control if they are in the upstream repository and that would probably be an easier workflow for you!

Sounds great that upstream fuzzers will be accepted. I'm happy to get that done -- but am just checking up if @silvergasp is up for the task.

**Comment by silvergasp** [comment]
@DavidKorczynski I'm happy to sort that, I'll open a couple of PRs later today.

**Comment by DavidKorczynski** [comment]
Thanks a ton @silvergasp -- no rush, please do it when convenient :)

**Comment by lemire** [comment]
Thanks folks. Your work is appreciated.

**Pull request merged**
