### PR TITLE
expat: Use upstream fuzzer build (retain dictionaries)

### PR DESCRIPTION
**Pull request by bshastry**
This PR mainly addresses this comment (see https://github.com/google/oss-fuzz/issues/402#issuecomment-554773333)

It looks like the upstream `parsebuffer` fuzzers don't anticipate null input. This PR now depends on this upstream PR https://github.com/libexpat/libexpat/pull/365

TODO: Investigate afl CI failure

### CODE REVIEW

**Comment by bshastry** [comment]
This is the error message I get inside an afl engine docker image

```
-fsanitize-coverage=trace-pc-guard is no longer supported by libFuzzer.
Please either migrate to a compiler that supports -fsanitize=fuzzer
or use an older version of libFuzzer
```

Could someone please tell me what I could be doing wrong?

**Comment by jonathanmetzman** [comment]
It sounds like the AFL fuzz target it accidentally being compiled with libFuzzer.
Is `-fsanitize=fuzzer` hardcoded anywhere?

**Comment by bshastry** [comment]
Ah right, thanks for the hint @jonathanmetzman

This calls for another upstream PR

**Comment by bshastry** [comment]
Fixed the afl build failure via https://github.com/libexpat/libexpat/pull/366

TODO:
  - Wait for https://github.com/libexpat/libexpat/pull/366 to land
  - Update libexpat link in docker file

**Comment by bshastry** [comment]
This PR is now ready for review. The upstream PR has been reviewed and merged by @hartwork

**Pull request merged**
