### PR TITLE
Pin LLVM revision used for Swift llvm-symbolizer patch.

### LINKED ISSUE #7383: swift base is failing
https://github.com/google/oss-fuzz/pull/7375#issuecomment-1067162474

### PR DESCRIPTION
**Pull request by oliverchang**
Fixes #7383

### CODE REVIEW

**Comment by oliverchang** [comment]
@catenacyber FYI. we should pin LLVM either way, and keep this more in sync with our base-clang version.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by catenacyber** [comment]
Thanks @oliverchang :-)

**Review by jonathanmetzman — COMMENTED** [review]
LGTM
This image is really annoying to rebuild. And it seems like most of the time is spent in the clone, not sure if depth 1 made it much faster.

**Comment by catenacyber** [comment]
> And it seems like most of the time is spent in the clone, not sure if depth 1 made it much faster.

Maybe the best way forward would be for swift to have the symbolizer as part of their package...

**Comment by jonathanmetzman** [comment]
+1 or we could build the swift symbolizer in base-clang.

**Pull request merged**
