### PR TITLE
Support i386 in Lua

### PR DESCRIPTION
**Pull request by ligurio**
- lua: support i386 architecture
- lua: fix compiler warning
- lua: fix homepage url

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
Are you a maintainer of this project by the way?

**Comment by ligurio** [comment]
> Are you a maintainer of this project by the way?

Seems so. I'm quite interested in testing Lua runtimes (PUC Rio Lua, LuaJIT).
I am building a testsuite [1] that is suitable for all Lua runtimes because of common Lua C API and I'm interested in running these tests in OSS Fuzz.

1. https://github.com/ligurio/lua-c-api-tests

**Comment by jonathanmetzman** [comment]
> BTW, when aarch64 arch will be available for everyone on OSS Fuzz?

This is not an official estimate but I'd guess around this winter. I'm doing a big refactor of ClusterFuzz that should make it doable. We don't have a solution for build infra though (GCB only supports intel).

**Pull request merged**
