### PR TITLE
infra: base-builder: fix introspector builds

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Fixes: https://github.com/google/oss-fuzz/issues/11466

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
CFLite issue is a false positive as far as I can tell

**Review by oliverchang — APPROVED** [review]

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --fuzzing-engines ndpi --sanitizers introspector

**Comment by oliverchang** [comment]
/gcbrun trial_build.py ndpi --fuzzing-engines libfuzzer --sanitizers introspector

**Comment by oliverchang** [comment]
/gcbrun trial_build.py ndpi --fuzzing-engine libfuzzer --sanitizers introspector

**Comment by DavidKorczynski** [comment]
I'm not entirely sure what the error is here?

**Comment by oliverchang** [comment]
> I'm not entirely sure what the error is here?

Will dig into this later. Let's just merge this for now!

**Comment by DavidKorczynski** [comment]
> Will dig into this later. Let's just merge this for now!

Sounds good, this shouldn't have any negative impact -- and at maximum on fuzz introspector builds.

**Pull request merged**
