### PR TITLE
Reland Make bad_build_check more likely to catch hardcoding /out (#3180)

### PR DESCRIPTION
**Pull request by jonathanmetzman**
This reverts commit 689c3f4b65b77ca27e882de828b4e741121238fc.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Will land https://github.com/google/oss-fuzz/pull/3205 right after this.

**Comment by inferno-chromium** [comment]
Did you test this with the AFL fix locally ?

**Comment by inferno-chromium** [comment]
Can also, just combine that CL in this one for more clarity.

**Comment by jonathanmetzman** [comment]
I tested it yesterday. I only reverted this to prevent two bad builds from happening in a row.

**Pull request merged**
