### PR TITLE
Add dependabot config file

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Related: https://github.com/google/oss-fuzz/issues/7425

### CODE REVIEW

**Review by asraa — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
CC @oliverchang

**Comment by evverx** [comment]
In the meantime I unsubscribed from the notifications there and turned off GHActions so as not to clog up my GHActions pool. It seems to be the only way to deal with those PRs unfortunately.

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman due to a GitHub bug every fork receives PRs from Dependabot like https://github.com/evverx/oss-fuzz/pulls. It would be great if it was possible to switch from daily updates to weekly (or even monthly) updates to reduce the noise. It's also possible to limit the number of PRs Dependabot can create with `open-pull-requests-limit: `

Oy, really stupid of dependabot to do this.
I'm going to get rid of it.

**Comment by evverx** [comment]
It was reported back in 2019 in https://github.com/dependabot/dependabot-core/issues/2198 and I'm not sure why it hasn't been fixed. Renovatebot is better in this regard in the sense that it has to be enabled explicitly but it has its own issues.

**Comment by jonathanmetzman** [comment]
I got rid of dependabot btw: https://github.com/google/oss-fuzz/pull/7453

**Comment by evverx** [comment]
Last time I checked it wasn't human-friendly. For example it just showed commit hashes instead of versions when dependencies were pinned to shas: https://github.com/evverx/systemd/pull/30

**Comment by jonathanmetzman** [comment]
:-\
Luckily it looks you might have been the only user hit by this https://github.com/search?q=dependabot+fork%3Aonly+%22bump+google-api-python-client+from+1.9.3+to+2.42.0+in+%2Finfra%2Fbuild%2Ffunctions%22&type=issues

I guess to get the issue you need to:
1. Have dependabot enabled on your account (?)
2. Updated after I added dependabot
3. Updated before I merged all of dependabot's PRs.

**Comment by evverx** [comment]
> Have dependabot enabled on your account

I don't think I have ever enabled Dependabot there. I tried to investigate that in https://github.com/systemd/systemd/issues/21343 but the scenario described there doesn't seem to be the only way to trigger it.

> Updated after I added dependabot

Yes it pops up once forks are updated. It can take some time but eventually every fork created before Dependabot is introduced seems to hit by it. The latest example would be https://github.com/ssahani/systemd/pull/9#issuecomment-1048069595 where I was asked what was that.

**Pull request merged**
