### PR TITLE
[zabbix] initial integration

### PR DESCRIPTION
**Pull request by 0x34d**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Who are some of the users of zabbix? WHy is it critical.

**Comment by Alan32Liu** [comment]
> > Who are some of the users of zabbix? WHy is it critical.
> 
> Link: https://www.zabbix.com/users
> 
> still working with Zabbix team.

OK, please let us know once it is ready.

**Comment by 0x34d** [comment]
DEADEND

**Comment by mfocuz** [comment]
Why this PR wasn't merged?

Around the world in 2024, over 11,553 companies have started using Zabbix as application-performance-monitoring tool. Companies using Zabbix for application-performance-monitoring are majorly from United States with 2,643 customers. 36.83% of Zabbix customers are from the United States.

This is critical because Zabbix is monitoring system collecting data from every server under monitoring. Every server under monitoring has zabbix_agent installed. 

@jonathanmetzman

**Comment by DonggeLiu** [comment]
> Why this PR wasn't merged?

Feel free to take over.

@0x34d: Would you mind kindly helping us understand why it became a dead end before it was ready? Thanks!

**Comment by 0x34d** [comment]
> @0x34d: Would you mind kindly helping us understand why it became a dead end before it was ready? Thanks!

There was no follow-up response from them.

**Comment by DonggeLiu** [comment]
> There was no follow-up response from them.

Thanks!

**Pull request closed without merging**
