### PR TITLE
Pin Jazzer to older revision.

### PR DESCRIPTION
**Pull request by oliverchang**
For #7483.

### CODE REVIEW

**Comment by oliverchang** [comment]
@fmeum FYI

**Comment by fmeum** [comment]
@oliverchang Sorry for the inconvenience. I will fix this  in Jazzer shortly and think about how to set up a proper CI check for OSS-Fuzz compatibility.

**Comment by oliverchang** [comment]
> 

No worries! That sounds great, thanks!

**Comment by jonathanmetzman** [comment]
LGTM

**Pull request merged**
