### PR TITLE
[orbit] A first build configuration

### PR DESCRIPTION
**Pull request by beckerhe**
That's a first shot of a build configuration.
Works on my machine so far (using `infra/helper.py`)

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
The disk filled up on CI. It probably won't fill up when we do the actual build ClusterFuzz actually uses. But it's possible we will need to revert this PR if it does fill up or if the tests we do for bad builds after building fai.

**Comment by jonathanmetzman** [comment]
It might be worth it for you to change this build so that the disk doesn't fill up on CI. But of course, that might not be possible.

**Comment by jonathanmetzman** [comment]
Did you run check_build btw? I think building fuzzers but not doing this is a major reason why a build would work locally but not on our infra. I have no evidence that you didn't, just wanted to check.

**Comment by beckerhe** [comment]
> Did you run check_build btw? I think building fuzzers but not doing this is a major reason why a build would work locally but not on our infra. I have no evidence that you didn't, just wanted to check.

Hi Jonathan,
sorry for being late. Yes, I did run check_build locally. Seems to be fine.

Nevertheless, the build currently seems not to work. I get a "No space left on the device". I've checked - when running locally i need a little over 10 gigs, mainly due to building LLVM as part of the project. According to the docs the limit should be closer to 250 gigs than to 10 gigs. Is there anything I'm missing?

Thanks,
Henning

**Pull request merged**
