### PR TITLE
Reland "[infra] Update Jazzer to v0.17.1" (#10537)"

### PR DESCRIPTION
**Pull request by jonathanmetzman**
This reverts commit cac7ccd85bfefe90dc51d251567df73ad14654e1.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jvm --sanitizer coverage address undefined

**Comment by jonathanmetzman** [comment]
CC @fmeum

**Comment by fmeum** [comment]
@jonathanmetzman The current failure looks like a flake (network issue), could you retrigger it?

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jvm --sanitizer coverage address undefined

**Comment by jonathanmetzman** [comment]
Failures:
```
xnio-api fuzzing
struts fuzzing
jxls fuzzing
httpcomponents-core fuzzing
jose4j coverage
hdrhistogram fuzzing
closure-compiler fuzzing
apache-axis2 fuzzing
jose4j coverage
jackson-dataformat-xml coverage
jackson-dataformats-text coverage
httpcomponents-client coverage
bc-java coverage
```

**Comment by fmeum** [comment]
@jonathanmetzman Does this list only include projects that build successfully on main?

**Comment by DavidKorczynski** [comment]
A number of them are failing, but not all e.g. `bc-java`. See here https://introspector.oss-fuzz.com/indexing-overview where you can search for "jvm" in the table -- which should give a nice overview on which currently fail coverage on master

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman Does this list only include projects that build successfully on main?

It's supposed to. It's also from yesterday. I usually look at https://oss-fuzz-build-logs.storage.googleapis.com/index.html to tall

**Comment by DavidKorczynski** [comment]
> It's supposed to.

of the above list `closure-compiler`, `struts` and `jxls` are failing in coverage builds on master -- and they've not had a successful coverage build yet as reported by https://oss-fuzz-build-logs.storage.googleapis.com/index.html

**Comment by fmeum** [comment]
I tested the listed projects locally:

* `xnio-api`: passes
* `jose4j`: passes
* `struts`: fails in `apt-get`, seems unrelated
* `jxls`: has a regular finding in `check_build`
* `hdrhistogram`: has a regular finding in `check_build`
* `closure-compiler`: failure is expected as rules_fuzzing will need to be updated to account for this Jazzer update. Since it runs OSS-Fuzz in CI, I can only do this after merging this PR. I have a [draft PR](https://github.com/bazelbuild/rules_fuzzing/pull/218) ready with the update.
* `apache-axi2` and `httpcomponents-core` trigger the new SSRF bug detector in `check_build`. I allowlisted the host and port they attempt to connect to, which gets `check_build` to pass with https://github.com/google/oss-fuzz/pull/10550.

@jonathanmetzman Could you merge https://github.com/google/oss-fuzz/pull/10550 into the reland PR?

The coverage build failures I either couldn't reproduce or they seemed unrelated.

**Pull request merged**
