### PR TITLE
Use now main branch for dovecot project

### PR DESCRIPTION
**Pull request by catenacyber**
Should fix build failure https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=29552

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by inferno-chromium** [comment]
Fuzzers have startup crashes that need fixing, otherwise builds wont be archived. @catenacyber can you tell the devs on this.

```
=================================================================
==71==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000005708c7 bp 0x7ffd952c3190 sp 0x7ffd952c30e0 T0)
==71==The signal is caused by a READ memory access.
==71==Hint: address points to the zero page.
SCARINESS: 10 (null-deref)
    #0 0x5708c7 in io_loop_destroy /src/dovecot/src/lib/ioloop.c:849:38
    #1 0x558301 in fuzzer_deinit /src/dovecot/src/lib-test/fuzzer.c:32:2
    #2 0x555b80 in LLVMFuzzerTestOneInput /src/dovecot/src/lib-imap/fuzz-imap-utf7.c:15:1
    #3 0x45a6f1 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:599:15
    #4 0x45bd06 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:792:3
    #5 0x45c1b9 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, fuzzer::fuzzer_allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:845:3
    #6 0x44a63b in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:906:6
    #7 0x474672 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #8 0x7ff8869fa83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #9 0x41f398 in _start (/tmp/not-out/fuzz-imap-utf7+0x41f398)

DEDUP_TOKEN: io_loop_destroy--fuzzer_deinit--LLVMFuzzerTestOneInput
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /src/dovecot/src/lib/ioloop.c:849:38 in io_loop_destroy
==71==ABORTING
```

**Comment by catenacyber** [comment]
Should we wait for https://github.com/dovecot/core/pull/151 ?

**Comment by inferno-chromium** [comment]
> Should we wait for [dovecot/core#151](https://github.com/dovecot/core/pull/151) ?

it is fine, it is merged already, so can let your cl merge as well.

**Pull request merged**
