### PR TITLE
ngolo-fuzzing: cleans while building

### PR DESCRIPTION
**Pull request by catenacyber**
cc @jonathanmetzman 
This should consume less hard drive space for the build...

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
This won't make a difference. I'm not saying the build is too big to complete. I'm saying it's too big to unpack.

**Comment by catenacyber** [comment]
Ok, what is unpacking here ?

**Comment by jonathanmetzman** [comment]
> Ok, what is unpacking here ?

The build, it unpacks all the fuzzers from the zip and the combination of that size plus the size of the zip fills the disk up. Splitting the projects can probably avoid this issue.

**Comment by catenacyber** [comment]
Ok... I guess I will split the project then...

**Comment by catenacyber** [comment]
@jonathanmetzman I just split the project in two, let's see...

**Comment by catenacyber** [comment]
Coverage is not yet working for x packages. Can this be merged already so that it fixes ngolo-fuzzing on std library ? (and start fuzzing x packages)

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
