### PR TITLE
infra: update fuzz introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Contains updates for:

- java coverage analysis improvements
- test-to-harness conversion (https://github.com/google/oss-fuzz-gen/issues/494)

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector

**Comment by DavidKorczynski** [comment]
The two failing projects are not due to this PR. This is good to go.

**Review by AdamKorcz — APPROVED** [review]

**Pull request merged**
