### PR TITLE
kimageformats: Use latest builder

### PR DESCRIPTION
**Pull request by maflcko**

### CODE REVIEW

**Comment by tsdgeos** [comment]
Why is that extra lib needed?

**Comment by jonathanmetzman** [comment]
@tsdgeos do you approve?

**Comment by tsdgeos** [comment]
My concern is "how am i supposed to know to do that"?

I´d be happier if it was a $VARIABLE that one is supposed to use for linking and here we aren´t , do you know if it that exists?

If not i guess we can go ahead.

**Comment by tsdgeos** [comment]
> > I´d be happier if it was a $VARIABLE that one is supposed to use for linking and here we aren´t , do you know if it that exists?
> 
> My understanding is that this is normally not needed to be specified manually. I do not yet understand why it is needed here, so if you want I can mark it as "temporary linker workaround" for this project specifically, so that someone can look into it in the future?

Yes please, let's do that :)

**Comment by tsdgeos** [comment]
Looks good to me.

Please merge :)

**Pull request merged**
