### PR TITLE
infra: bump fuzz introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Contains improvements in various areas, including:

- Copies more source code files such that introspector.oss-fuzz.com can reference them
- Improvements on function signature generation

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
ClusterFuzzLite CI failure is not related to this PR

**Comment by DavidKorczynski** [comment]
The build failures stem from some issues when installer java/jazzer:

```
#5 9.529 ERROR: Error computing the main repository mapping: no such package '@com_grail_bazel_toolchain//toolchain': java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp8161481898454060247/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
#5 ERROR: process "/bin/sh -c install_java.sh" did not complete successfully: exit code: 1
------
 > [2/2] RUN install_java.sh:
9.519 ERROR: An error occurred during the fetch of repository 'com_grail_bazel_toolchain':
9.519    Traceback (most recent call last):
9.519 	File "/root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
9.519 		download_info = ctx.download_and_extract(
9.519 Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp8161481898454060247/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
9.519 ERROR: /src/jazzer/WORKSPACE.bazel:34:13: fetching http_archive rule //external:com_grail_bazel_toolchain: Traceback (most recent call last):
9.519 	File "/root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
9.519 		download_info = ctx.download_and_extract(
9.519 Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp8161481898454060247/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
9.529 ERROR: Error computing the main repository mapping: no such package '@com_grail_bazel_toolchain//toolchain': java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp8161481898454060247/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
------
Dockerfile:24
--------------------
  22 |     ENV JAZZER_API_PATH "/usr/local/lib/jazzer_api_deploy.jar"
  23 |     
  24 | >>> RUN install_java.sh
  ```

**Comment by mzlatko8219** [comment]
Was ist das und wer bist duVon meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: DavidKorczynski ***@***.***>Datum: So., 18. Feb. 2024, 03:03An: google/oss-fuzz ***@***.***>Cc: Subscribed ***@***.***>Betreff: Re: [google/oss-fuzz] infra: bump fuzz introspector (PR #11611)
The build failures stem from some issues when installer java/jazzer:
#5 9.529 ERROR: Error computing the main repository mapping: no such package ***@***.***_grail_bazel_toolchain//toolchain': java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp8161481898454060247/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
#5 ERROR: process "/bin/sh -c install_java.sh" did not complete successfully: exit code: 1
------
 > [2/2] RUN install_java.sh:
9.519 ERROR: An error occurred during the fetch of repository 'com_grail_bazel_toolchain':
9.519    Traceback (most recent call last):
9.519 	File "/root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
9.519 		download_info = ctx.download_and_extract(
9.519 Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp8161481898454060247/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
9.519 ERROR: /src/jazzer/WORKSPACE.bazel:34:13: fetching http_archive rule //external:com_grail_bazel_toolchain: Traceback (most recent call last):
9.519 	File "/root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
9.519 		download_info = ctx.download_and_extract(
9.519 Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp8161481898454060247/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
9.529 ERROR: Error computing the main repository mapping: no such package ***@***.***_grail_bazel_toolchain//toolchain': java.io.IOException: Error downloading [https://github.com/grailbio/bazel-toolchain/archive/refs/tags/0.6.3.tar.gz] to /root/.cache/bazel/_bazel_root/e3c2be7f6be7a238950c8073a90fc93c/external/com_grail_bazel_toolchain/temp8161481898454060247/0.6.3.tar.gz: Checksum was a0a45349bf5d57bbefe2669225cda802c5d9ab8ea412a5e683f52bdcf3f16c65 but wanted da607faed78c4cb5a5637ef74a36fdd2286f85ca5192222c4664efec2d529bb8
------
Dockerfile:24
--------------------
  22 |     ENV JAZZER_API_PATH "/usr/local/lib/jazzer_api_deploy.jar"
  23 |     
  24 | >>> RUN install_java.sh

**Review by DonggeLiu — APPROVED** [review]
Approving this because it appears all failures are caused by errors downloading `Java`.

**Comment by DonggeLiu** [comment]
Re-running CIs to use this PR to double-check if the Java error is flaky.

**Comment by DavidKorczynski** [comment]
Created this for the Java build issues: https://github.com/google/oss-fuzz/issues/11613

**Comment by DonggeLiu** [comment]
@oliverchang Would you mind if I merge this to unblock FI? Thanks!
I don't think the errors are irrelevant to this PR.

**Comment by DavidKorczynski** [comment]
Fix for java broken base image here: https://github.com/google/oss-fuzz/pull/11614

**Review by oliverchang — APPROVED** [review]

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector

**Comment by mzlatko8219** [comment]
Hellp my kenne mich nicht gut aus hat mir helfen ich weiß nicht was ich gemacht habe ich habe dem Programm Von meinem Huawei-Telefon gesendet-------- Ursprüngliche Nachricht --------Von: Oliver Chang ***@***.***>Datum: So., 18. Feb. 2024, 23:55An: google/oss-fuzz ***@***.***>Cc: mzlatko8219 ***@***.***>, Comment ***@***.***>Betreff: Re: [google/oss-fuzz] infra: bump fuzz introspector (PR #11611)
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector

**Pull request merged**
