### PR TITLE
GSoC Adding pyhf into OSS Fuzz

### PR DESCRIPTION
**Pull request by PatriceJada**
Main Maintainer @matthewfeickert

### CODE REVIEW

**Comment by matthewfeickert** [comment]
cc @kratsg, @lukasheinrich

**Comment by matthewfeickert** [comment]
@PatriceJada @DonggeLiu Just curious what's actually the status on all of this. Is the work that we were approached on going to happen, or did that fall through?

**Comment by DonggeLiu** [comment]
> @PatriceJada @DonggeLiu Just curious what's actually the status on all of this. Is the work that we were approached on going to happen, or did that fall through?

They fall through, unfortunately.
It's a joint decision from the OSS-Fuzz panel.

**Comment by matthewfeickert** [comment]
Okay, thanks for the information. This was strange to have been approached to participate in a program and then have no follow up. :?

**Pull request closed without merging**
