### PR TITLE
[libtheora]

### PR DESCRIPTION
**Pull request by guidovranken**
Green-lighted per https://github.com/google/oss-fuzz/issues/2790#issuecomment-528694725

I've sent a message to the theora-dev list,  awaiting reply.

@posidron I added you to vendor_ccs, please confirm that this is ok.

This fuzzer finds some bugs. @posidron If I get no reply from Xiph or they are not interested, is Mozilla willing to fix bugs and upstream patches?

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Also please fix travis failures.

**Comment by posidron** [comment]
@guidovranken, thanks for thinking ahead and adding me already!

We had some employees who were/are involved in the Xiph organization namely @rillian but AFAICT we would now redirect issues upstream for fixing.

**Comment by guidovranken** [comment]
OK, does this mean that you will look after the bugs and we don't need to add additional maintainers for now?

**Comment by posidron** [comment]
So, I forgot and just noticed that Timothy B. Terriberry is in the Authors file, so I probably would file all related bugs in Bugzilla directly. The main goal is of course to look out for security bugs - I would have no time to look after every null-ptr crash or other bizarre issues.

**Comment by guidovranken** [comment]
I think we're set, except that there will be memory bugs coming from writeImage (https://github.com/guidovranken/oss-fuzz-fuzzers/blob/master/libtheora/fuzzer.cpp#L144). I don't know if this is a bug in libtheora or in my code. What I did was use the logic I found in mplayer. Unfortunately the libtheora docs are not very specific. Maybe I should comment out that code for now?

**Comment by jonathanmetzman** [comment]
I guess this is fine to merge since mozilla will look fix bugs.

**Comment by jonathanmetzman** [comment]
> I think we're set, except that there will be memory bugs coming from writeImage (https://github.com/guidovranken/oss-fuzz-fuzzers/blob/master/libtheora/fuzzer.cpp#L144). I don't know if this is a bug in libtheora or in my code. Unfortunately the libtheora docs are not very specific. Maybe I should comment out that code for now?

Not sure :-)

**Comment by buweilv** [comment]
@guidovranken we use oss-fuzz test libtheora, we indeed found some memory bugs in TheoraDecoder::writeImage, Is there a problem in the function TheoraDecoder::writeImage?

**Pull request merged**
