### PR TITLE
[libphonenumber] Initial integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
URL to upstream project: https://github.com/google/libphonenumber/

@penmetsaa or @lararennie Could you take a look at this? I believe libphonenumber is important to Google and it would be nice to have it fuzzed. OSS-Fuzz is a service run by Google that performs continuous fuzzing of a given project. It would be nice to merge the fuzzer of this PR as well as some additional build changes to the upstream libphonenumber later on. If you are happy to have the project fuzzed, could you provide me with an email that will received updates, e.g. bug-reports, about the fuzzing. I will also take care of the failures in the CI.

### CODE REVIEW

**Review by penmetsaa — APPROVED** [review]
LGTM. Thanks for the changes.
Other details I have mentioned in the email.

**Review by inferno-chromium — APPROVED** [review]
Later can submit Pr to submit fuzzer to main project repo.

**Comment by DavidKorczynski** [comment]
Thanks @penmetsaa - would you be happy to have the fuzzers integrated upstream? I would be happy to do so and this is also preferred from an OSS-Fuzz perspective.

**Comment by penmetsaa** [comment]
+1
Curious to see some potential issues in the library :)

**Pull request merged**
