### PR TITLE
Removed packages that we no longer need to install and enabled memory sanitizer

### PR DESCRIPTION
**Pull request by dlemstra**

### CODE REVIEW

**Comment by Navidem** [comment]
Tests are failing, could you check please?

**Comment by dlemstra** [comment]
I will investigate why this is happening.

**Comment by dlemstra** [comment]
The build issues have been fixed @Navidem.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by Navidem** [comment]
> The build issues have been fixed @Navidem.

Thanks!

**Pull request merged**
