### PR TITLE
Revert "[google-uuid] initial integration (#10241)"

### PR DESCRIPTION
**Pull request by jonathanmetzman**
This reverts commit 9baf54ccb06118d6a3509c91648c02204710ae72.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @AdamKorcz

**Comment by jonathanmetzman** [comment]
CC @Alan32Liu

**Comment by jonathanmetzman** [comment]
@DavidKorczynski Do you remember the last time this happened? I'm trying to find it, I suspect it might be the reason our new project setup isn't working but I'm not sure.

**Comment by DavidKorczynski** [comment]
Yeah, it was under a python project and why their called `g-py` -- let met just find the PR

**Comment by DavidKorczynski** [comment]
https://github.com/google/oss-fuzz/pull/7900

**Pull request merged**
