### PR TITLE
Revert clang workaround for Envoy

### PR DESCRIPTION
**Pull request by asraa**
Fixes for Envoy: https://github.com/google/oss-fuzz/issues/3157

Signed-off-by: Asra Ali <asraa@google.com>

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Build is still failing, i didnt wait for travis as envoy build is usually slow and fails on timeout.

@asraa - can you please check if this works

```
python infra/helper.py pull_images
python infra/helper.py build_image envoy
python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 envoy
```

**Comment by asraa** [comment]
@inferno-chromium Running!

**Comment by asraa** [comment]
The build succeeded for me locally!

**Comment by inferno-chromium** [comment]
@oliverchang - any thoughts here, i tried this too, locally it succeeds, but fails on gcb, what could be different here.

**Comment by Dor1s** [comment]
Checking the latest build failure on GCB:

```
2020-04-17T17:17:01.304832901Z Step #40: Failed to build. I 
2020-04-17T17:17:01.304836377Z Step #40: To reproduce, run: I 
2020-04-17T17:17:01.304838097Z Step #40: python infra/helper.py build_image envoy I 
2020-04-17T17:17:01.304839441Z Step #40: python infra/helper.py build_fuzzers --sanitizer undefined --engine honggfuzz --architecture x86_64 envoy I 
```

looks like libFuzzer ASan is building fine?

**Comment by jonathanmetzman** [comment]
Why are we doing honggfuzz/ubsan builds? I don't think we use them right? We can probably save build cycles.

**Comment by inferno-chromium** [comment]
> Why are we doing honggfuzz+ubsan builds? I don't think we use them right? IIRC we only use ASAN with honggfuzz. We can probably save compute and developer cycles by not doing them.

This was a mistake i think, check https://github.com/google/oss-fuzz/pull/3667

**Comment by oliverchang** [comment]
From https://oss-fuzz-build-logs.storage.googleapis.com/log-2ceeeef5-1f48-4287-bfad-ed4360ac2739.txt

```
Step #13: Execution platform: @local_config_platform//:host
Step #13: clang: error: unable to execute command: Killed
Step #13: clang: error: clang frontend command failed due to signal (use -v to see invocation)
```

Possible OOM?

**Comment by asraa** [comment]
I think so. We seems to get these non-reproducible build failures every once in a while, is there some way to fix this on our end?

**Comment by inferno-chromium** [comment]
@asraa - maybe can try removing some test targets to avoid this OOM, e.g. last one was
[4,315 / 4,378] Compiling test/mocks/upstream/mocks.cc; 886s local ... (23 actions running)

are these test targets even needed for build ?

**Comment by asraa** [comment]
Yep, that's a dependency of some fuzz targets, but I can mark some stable utility fuzz targets as nofuzz, which will remove them from the build!

**Pull request merged**
