### PR TITLE
[infra] Enable dead code stripping in code coverage builds (#2110).

### PR DESCRIPTION
**Pull request by Dor1s**
Testing with various projects locally. If nothing breaks, can try landing and testing at scale next week.

### CODE REVIEW

**Comment by Dor1s** [comment]
Hey @kcc, this doesn't seem to work as expected. I've tried libpng locally and obtained precisely the same report w/ and w/o these extra flags.

Trying some other projects now.

**Comment by kcc** [comment]
frankly, I don't know how dead code stripping affects clang coverage, if at all. 
What did you expect?

**Comment by Dor1s** [comment]
I expected that unused code regions (e.g. the one you mentioned in #2110) would be removed from the binary and therefore wouldn't be counted as non covered code. Good point that it might not work with code coverage instrumentation, but that would be not cool :|

**Comment by Dor1s** [comment]
openssl -- the same.

Noticed the following in https://clang.llvm.org/docs/SourceBasedCodeCoverage.html#drawbacks-and-limitations

> Prior to version 2.26, the GNU binutils BFD linker is not able link programs compiled with `-fcoverage-mapping` in its `--gc-sections` mode. Possible workarounds include disabling `--gc-sections`, upgrading to a newer version of BFD, or using the Gold linker.

**Comment by Dor1s** [comment]
Although

```
root@210737f47ea4:/src/openssl# ld --version
GNU ld (GNU Binutils for Ubuntu) 2.26.1
Copyright (C) 2015 Free Software Foundation, Inc.
This program is free software; you may redistribute it under the terms of
the GNU General Public License version 3 or (at your option) a later version.
This program has absolutely no warranty.
```

**Comment by Dor1s** [comment]
It also doesn't work with BFD linker 2.31.1 nor with the Gold linker :/

**Comment by Dor1s** [comment]
Apparently there is a test that uses `--gc-sections`, has an unused function, and still asserts that it's present as uncovered in the report: https://github.com/llvm/llvm-project/blob/05ebaa62e0db67d7a04d47b2f50eb2faa8597cc8/compiler-rt/test/profile/Linux/coverage_test.cpp#L26

**Comment by Dor1s** [comment]
Asked in https://github.com/llvm/llvm-project/commit/0fc35d0a42057ab416737b38a9f836d6c99aac4c

**Pull request closed without merging**
