### PR TITLE
[Poppler] [WIP-not ready] New fuzzers - v2

### PR DESCRIPTION
**Pull request by ecalp-tps**
This is a new PR that fixes some of the issues with the [previous PR](https://github.com/google/oss-fuzz/pull/4635) that was merged and reverted.

Thanks!
Ceyhun
ceyhunalp@google.com

### CODE REVIEW

**Comment by ecalp-tps** [comment]
@inferno-chromium I made the following changes:

- It fetches Poppler and the fuzzers from the main Poppler branch. I removed the fuzz targets from this repository since Albert merged my fuzzers to the main Poppler branch earlier today.
- MSan is enabled again. I had to disable both glib and qt builds (and the corresponding fuzzers) since building these libraries from their sources fail when MSan is enabled.
- I removed the `FuzzedDataProvider.h` file from this repository since it created license errors. However, this caused problems with the include path. I added three small patches to change the include path in three fuzzers to `<fuzzer/FuzzedDataProvider.h>`. Maybe Albert can fix the include paths in the original Poppler repository so that we can remove these patches.

**Comment by inferno-chromium** [comment]
@ecalp-tps - please rebase after @tsdgeos recent change. Is this PR still applicable ?

**Comment by ceyhunalp** [comment]
> @ecalp-tps - please rebase after @tsdgeos recent change. Is this PR still applicable ?

We can close this PR since the changes from @tsdgeos solve the qt5 build issue.

**Comment by ecalp-tps** [comment]
> @ecalp-tps - please rebase after @tsdgeos recent change. Is this PR still applicable ?

We can close this PR since the changes from @tsdgeos solve the qt5 build issue.

**Comment by tsdgeos** [comment]
@inferno-chromium please close? :)

**Comment by inferno-chromium** [comment]
> @inferno-chromium please close? :)

Done!

**Pull request closed without merging**
