### PR TITLE
[Hiredis] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
Hi PR adds initial integration on Hiredis.

We are currently waiting for a fuzzer to be merged here: https://github.com/redis/hiredis/pull/902

For the Hiredis maintainers: The files in this PR allows the fuzzer in the PR above to be run continuously. All that is needed on this side is at least one maintainers email address in the `project.yaml` file. You can add it per your convenience or you can leave your email address in this thread and I will make sure to add it. The list can be changed at any time by making a pull request with the desired changes. If you have any questions about this integration, feel free to drop them in this PR or in the PR on the Hiredis repository. Please note that I have added my own email address on the mailing list to see the integration through to completion. This does mean that all bugs and vulnerabilities will be visible by me as all email addresses on that list will have access to these, and if you prefer me off the list, just let me know, and I will remove myself.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
@jonathanmetzman @inferno-chromium Ready for review.

**Comment by inferno-chromium** [comment]
> @jonathanmetzman @inferno-chromium Ready for review.

This does not feel important even though it was in that list. It looks like just a CLI tool for redis. Might have to drop this one, or what were your thoughts of how this was important.

**Comment by michael-grunder** [comment]
Maintainer of Hiredis here.

Hiredis is the official C library for Redis so will be used anywhere people are communicating with Redis in C.  It is also built into Redis and is how [Redis Sentinel](https://github.com/redis/redis/blob/unstable/src/sentinel.c) communicates with the various servers it monitors.

Additionally many Redis libraries are just thin wrappers around Hiredis.

The folks at Redis labs (e.g. @yossigo or @itamarhaber) may know more about production use.

That being said, I have no strong opinion about this.  The commit is easy to revert.

Cheers

**Comment by yossigo** [comment]
I didn't have the bandwidth to look into the details of how the fuzzing is done, but at a high level I think it will be useful for `hiredis` as it's part of quite a lot of tools and other libraries.

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
