### PR TITLE
Updates for mysql 8.22

### PR DESCRIPTION
**Pull request by catenacyber**
Try to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=26134

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Ci failing, please check.

**Comment by catenacyber** [comment]
CI fails with 
No space left on device

mysql fuzz targets take a few Gb

What should we do ?

**Comment by inferno-chromium** [comment]
Is this ready to merge ? are other failures expected ?

**Comment by catenacyber** [comment]
At least, libfuzzer, address, x86_64 is now working again

**Comment by inferno-chromium** [comment]
> At least, libfuzzer, address, x86_64 is now working again

Ok merged, probably disable others that dont work in another pr.

**Comment by catenacyber** [comment]
Looks like it is working this way https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24223#c5

**Pull request merged**
