### PR TITLE
mercurial: move fuzzing build to Python 3

### PR DESCRIPTION
**Pull request by durin42**
There's some extra tidiness along for the ride here, but nothing I felt
merited a separate change.

### CODE REVIEW

**Comment by durin42** [comment]
Sigh, looks like I need to do something to get an msan build of openssl. I'll get back to this eventually...

**Comment by inferno-chromium** [comment]
> Sigh, looks like I need to do something to get an msan build of openssl. I'll get back to this eventually...

you can also remove msan for now, by removing that sanitizer from project.yaml. see docs https://google.github.io/oss-fuzz/getting-started/new-project-guide/#sanitizers

**Comment by durin42** [comment]
Yeah, I know. Having msan has been important for the hg-specific code though, so I really just want to do this right. Too much going on to shave the whole yak today. :)

**Comment by durin42** [comment]
Finally got time to look at this in more detail today, and got it all passing. :)

**Comment by inferno-chromium** [comment]
> Finally got time to look at this in more detail today, and got it all passing. :)

Do you need to build python 3.8, it is already installed in the image - https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L42, can you simplify Dockerfile ?

**Comment by durin42** [comment]
AIUI I need a fuzzer-built Python or nothing will work, since Python is embedded in the fuzz target as a library (and mallocs etc flow through Python).

This is exactly what we did for Python 2, FWIW.

**Comment by inferno-chromium** [comment]
> AIUI I need a fuzzer-built Python or nothing will work, since Python is embedded in the fuzz target as a library (and mallocs etc flow through Python).
> 
> This is exactly what we did for Python 2, FWIW.

Thanks for confirming.

**Comment by durin42** [comment]
Sorry, just realized the openssl cruft in there was cruft. Pushed a version with that trimmed out. It should still work, that was leftover from a false start.

**Comment by durin42** [comment]
(builds done, all passed)

**Pull request merged**
