### PR TITLE
update aptos-core project file

### PR DESCRIPTION
**Pull request by gedigi**
- fixes coverage build due to an incorrect `coverage_extra_args`
- updates `auto_ccs`

solves [coverage build failure](https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61762).

### CODE REVIEW

**Comment by gedigi** [comment]
@Alan32Liu can you please approve?

**Review by Alan32Liu — APPROVED** [review]

**Comment by gedigi** [comment]
thanks for approving @Alan32Liu - how can I merge this?

image

**Comment by DavidKorczynski** [comment]
> thanks for approving @Alan32Liu - how can I merge this?
> 
> image

The CI needs to be green to merge, could you fix the CI failures?

**Comment by gedigi** [comment]
> The CI needs to be green to merge, could you fix the CI failures?

The CI problem is caused by low resources on the runners that cannot complete the build process. We had this issue during the [initial integration PR](https://github.com/google/oss-fuzz/actions/runs/5931487218) as well. See https://github.com/google/oss-fuzz/pull/10757#issuecomment-1658581686

**Pull request merged**
