### PR TITLE
Adds project swift

### PR DESCRIPTION
**Pull request by catenacyber**
cc @dcci @shahmishal @tbkka
Would you be interested in continuous fuzzing for swift ?
I see that there are already 2 fuzz targets
swift-reflection-fuzzer, which needed a small patch to compile, crashes also immediately with read overflow
Within a minute, I get a NULL dereference with swift-demangle-fuzzer
 
cc @thomasvl

### CODE REVIEW

**Comment by catenacyber** [comment]
> swift-reflection-fuzzer, which needed a small patch to compile, crashes also immediately with read overflow

This looks normal as it does not use `Size` before reading the data...

**Comment by catenacyber** [comment]
CI failure is `No space left on device` 
I guess this project is too big ;-)

Maybe there is a way to have a more efficient build reusing the base-builder llvm instead of recompiling one...

**Comment by tbkka** [comment]
> Maybe there is a way to have a more efficient build reusing the base-builder llvm instead of recompiling one...

@shahmishal would know better than I, but I don't think this is feasible due to regular small changes to LLVM libraries specifically to support the Swift compiler.

**Comment by catenacyber** [comment]
@tbkka, even if CI fails with a limited space on disk, do you approve oss-fuzz integration for the swift demangler fuzzer ? (there is not such a low disk space limit for oss-fuzz, cf dart project)

**Comment by tbkka** [comment]
I think @airspeedswift would be better placed to address that.

**Comment by catenacyber** [comment]
cc @gottesmm would you be interested in the swift demangler fuzzer being run continuously on oss-fuzz ?
cf https://bugs.swift.org/browse/SR-7574

Last time I checked, it quickly found a NULL dereference

**Comment by catenacyber** [comment]
@thomasvl would you have good points of contact for this ?

**Comment by tbkka** [comment]
This is still likely not much help to us.

As you noticed, our fuzzers find issues pretty quickly, so at-desk testing suffices for now. We'll be in touch once we get to a point that we need the additional cycles.

I'll also talk to some related projects that may be in a better position to take advantage of this.

**Comment by catenacyber** [comment]
Thanks for the feedback @tbkka 

> As you noticed, our fuzzers find issues pretty quickly, so at-desk testing suffices for now. 

My experience is that oss-fuzz can find new bugs after months/years of fuzzing...
(But if you already have a big backlog of known bugs to fix first, I understand)
Should I close this PR ? Or keep it open and revisit it in some time ?

> I'll also talk to some related projects that may be in a better position to take advantage of this.

Thanks, that is appreciated. oss-fuzz supports swift language (see swift-nio project for instance)

**Comment by tbkka** [comment]
It will be a while before we work through our existing backlog.  It probably makes sense to close this for now.

**Comment by catenacyber** [comment]
Ok thanks Tim

**Pull request closed without merging**
