### PR TITLE
Fix WORKDIR for Samba

### PR DESCRIPTION
**Pull request by abartlet**
The previous PR had the wrong WORKDIR, this one has been tested.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Please see the build failure. Our build system rejects builds that have too many fuzzers that are trivial to find bugs in (to prevent uploading of accidentally broken builds).

**Comment by abartlet** [comment]
On Fri, 2019-12-06 at 14:49 -0800, jonathanmetzman wrote:
> Please see the build failure. Our build system rejects builds that
> have too many fuzzers that are trivial to find bugs in (to prevent
> uploading of accidentally broken builds).

Yeah, I was aware of the fuzz failure in fuzz_lzxpress:

https://bugzilla.samba.org/show_bug.cgi?id=14190

That is just pending someone finding time to fix the code.

However I don't know how to fix the AFL fuzz_tiniparser issue, that
didn't show up in the docker-based tests, so any advise most
appreciated.

Thanks!

Andrew Bartlett

**Comment by abartlet** [comment]
Patches that should fix the remaining issues by:
* pushing the failed fuzzer under 10% after adding many more fuzzers
* fixing the build for undefined behaviour sanitizer

are at https://gitlab.com/samba-team/samba/merge_requests/965

These will hopefully be merged into Samba soon.

**Comment by jonathanmetzman** [comment]
>However I don't know how to fix the AFL fuzz_tiniparser issue, that didn't show up in the docker-based tests, so any advise most appreciated. Thanks! Andrew Bartlett

Do you have a link to where this happened?

**Comment by abartlet** [comment]
> > However I don't know how to fix the AFL fuzz_tiniparser issue, that didn't show up in the docker-based tests, so any advise most appreciated. Thanks! Andrew Bartlett
> 
> Do you have a link to where this happened?

Samba can't build for AFL at the moment as we can't currently build pure static.

**Comment by jonathanmetzman** [comment]
ACK

**Pull request merged**
