### PR TITLE
Cleanup build script, fix tensorflow build

### PR DESCRIPTION
**Pull request by mihaimaruseac**
Add new fuzzer and ensure that it builds successfully.

### CODE REVIEW

**Comment by mihaimaruseac** [comment]
Oh, the demo fuzzer is too small. Will create a larger one and retrigger

**Comment by inferno-chromium** [comment]
> Oh, the demo fuzzer is too small. Will create a larger one and retrigger

You can always verify things locally, see
https://google.github.io/oss-fuzz/advanced-topics/reproducing/#reproducing-build-failures
you can just test on all fuzzers directly and keep disabling one-by-one as needed.

**Comment by mihaimaruseac** [comment]
I'll do that and when ready convert this PR to a normal (non-draft) one

**Comment by mihaimaruseac** [comment]
This should be ready now. I will add more fuzzers in the future as I'm working on enabling them, having smaller disk footprint and shorter compile time. When adding fuzzers which need corpus and dictionaries will add the corresponding sections to the build file.

**Comment by inferno-chromium** [comment]
> This should be ready now. I will add more fuzzers in the future as I'm working on enabling them, having smaller disk footprint and shorter compile time. When adding fuzzers which need corpus and dictionaries will add the corresponding sections to the build file.

Perfect, CI is green, merging!

**Pull request merged**
