### PR TITLE
Added initial integration of Lexbor.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Cross-reference: https://github.com/lexbor/lexbor/pull/70

Still waiting for the merge upstream and will update here when it happens.

### CODE REVIEW

**Comment by lexborisov** [comment]
Hi @DavidKorczynski 

Path to compile the `decode.c` file is incorrectly.
I'm not sure, but shouldn't it be `../test/fuzzers/lexbor/encoding/decode.c`?

Please, see [Job #2131.2](https://travis-ci.org/github/google/oss-fuzz/jobs/674535231#L722).
At the time of the compiler call `clang -O1 -fno-omit-frame-pointer ...` we are in the directory created earlier: [build](https://travis-ci.org/github/google/oss-fuzz/jobs/674535231#L323).

**Comment by DavidKorczynski** [comment]
The reason the path is not correct is because the path has not been merged upstream! Please merge upstream and I will make sure it all compiles and runs well here.

**Comment by lexborisov** [comment]
@DavidKorczynski 

Ok, merged!

**Comment by inferno-chromium** [comment]
@DavidKorczynski - who are the users for Lexbor library ?

**Comment by lexborisov** [comment]
Hi @inferno-chromium

Since I once found myself here...

> who are the users for Lexbor library?

The library is not used by a large number of users.
If only popular projects are used here, then you can close the PR. Thanks.

Thanks to @DavidKorczynski for the initiative.

**Comment by inferno-chromium** [comment]
> Hi @inferno-chromium
> 
> Since I once found myself here...
> 
> > who are the users for Lexbor library?
> 
> The library is not used by a large number of users.
> If only popular projects are used here, then you can close the PR. Thanks.
> 
> Thanks to @DavidKorczynski for the initiative.

Any examples of projects where it is used, is it part of any package distros ?

**Comment by DavidKorczynski** [comment]
@inferno-chromium @lexborisov is the core developer and knows where the project is used, so from what he says it seems the use of it is limited at the moment. The main reason I integrated the project is because it strikes me as an ambitious project, e.g. judging from its roadmap https://lexbor.com/roadmap/ and the fact that @lexborisov has mad a very nice structure around the project with well-maintained documentation, IRC channel and more. Initially, @AdamKorcz reached out to @lexborisov about integrating https://github.com/lexborisov/myhtml which is a well-used html parser, but @lexborisov (who is the maintainer of both) was rather interested in integrating Lexbor. To make a long story short I thought integrating the project at this stage could be useful as the fuzzers would inevitably be integrated as the project progresses.

If it's not well-suited for OSS-Fuzz then no stress you can close the PR (I will be happy to continue contributing fuzzers to the project nonetheless @lexborisov).

**Comment by lexborisov** [comment]
@inferno-chromium 

> Any examples of projects where it is used, is it part of any package distros ?

Sorry, but I don’t have such information.

Thanks again to @DavidKorczynski , but I didn’t disseminate information about the project anywhere. So the project is in development. As soon as he begins to "draw" then his popularity will increase significantly. Maybe then @DavidKorczynski  should add it here. I dont know.

But, in any case, thank you all for your time.

**Comment by inferno-chromium** [comment]
Yes we recommend integrating with OSS-Fuzz once you have more users.

**Pull request closed without merging**
