### PR TITLE
[Leptonica] Update to auto-cc list

### PR DESCRIPTION
**Pull request by AdamKorcz**
By agreement with the author.
@timothy-king should have been informed about this.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@stweil - are you ok with getting full bug access (including security bugs) to @AdamKorcz ?

**Comment by AdamKorcz** [comment]
@inferno-chromium Is there a way to seperate fuzzer statistics and bug reports? I have requested access to the fuzzer statistics with the author and don't need access to the bug reports at this time.

**Comment by inferno-chromium** [comment]
nope not currently, but we are thinking of ways to give broader fuzzer stats access. 

for time being, it is upto maintainer to make that call.

**Comment by AdamKorcz** [comment]
@inferno-chromium Duly noted!

**Comment by timothy-king** [comment]
> are you ok with getting full bug access (including security bugs) to @AdamKorcz ?
After talking with talking with @DanBloomberg, I think this is ok.

**Comment by stweil** [comment]
> are you ok with getting full bug access (including security bugs) to @AdamKorcz?

Dan is the right one who should be asked.

**Comment by DanBloomberg** [comment]
Yes, I believe it will help Adam do his job, so I'm fine with it.

**Pull request merged**
