### PR TITLE
infra: bump fuzz-introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
- Contains improvements in debug information handling
  - function signature improvements
  - more raw type-related data
  - fix for providing source code for e.g. header files
- The version of Fuzz Introspector is compatible with LLVM18 so the soon-to-occur bump should be more painfree with this version of Introspector.

### CODE REVIEW

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector

**Comment by DavidKorczynski** [comment]
Went through the errors and all but 1 was due to an issue in the patch. I suggest merging now and will follow up afterwards with fix to that project.

**Review by AdamKorcz — APPROVED** [review]

**Pull request merged**
