### PR TITLE
Application for realm-core

### PR DESCRIPTION
**Pull request by emanuelez**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Can you comment on the popular applications using realm-core ?

**Comment by emanuelez** [comment]
It's most likely the second most installed database in the world after SQLite with around one billion installs. It is used by many popular mobile apps, including Netflix, Starbucks, Ebay and more... some of them are listed here: https://realm.io/

**Comment by inferno-chromium** [comment]
Thanks!

**Comment by inferno-chromium** [comment]
Oops, can you please sign the CLA!

**Comment by emanuelez** [comment]
Signed the CLA. Now working on writing some libfuzzer tests

**Pull request merged**
