### PR TITLE
[FreeRDP] Pass CMake flag BUILD_TESTING and use a target for building fuzzers

### PR DESCRIPTION
**Pull request by ligurio**
Depends on PR https://github.com/FreeRDP/FreeRDP/pull/9019

### CODE REVIEW

**Comment by ligurio** [comment]
```
[320/322] Linking C executable Testing/TestFuzzCommonAssistanceBinToHexString                                                                                         
FAILED: Testing/TestFuzzCommonAssistanceBinToHexString                                                                                                                
: && /usr/local/bin/clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-sc
ope -fsanitize=fuzzer-no-link -Wno-c11-extensions -Wno-gnu -fno-omit-frame-pointer -fsanitize=address -fsanitize-blacklist=/src/FreeRDP/scripts/blacklist-address-sani
tizer.txt -fsanitize-address-use-after-scope -g -flto=thin -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=addres
s -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -fsanitize=address libfreerdp/common/test/CMakeFiles/TestFuzzCommonAssistanceBinToHexStr
ing.dir/TestFuzzCommonAssistanceBinToHexString.c.o -o Testing/TestFuzzCommonAssistanceBinToHexString  libfreerdp/libfreerdp3.a  winpr/libwinpr/libwinpr3.a  -lrt  -lm 
 /usr/lib/x86_64-linux-gnu/libicui18n.a  /usr/lib/x86_64-linux-gnu/libicuuc.a  /usr/lib/x86_64-linux-gnu/libicuio.a  /usr/lib/x86_64-linux-gnu/libssl.a  /usr/lib/x86_
64-linux-gnu/libcrypto.a  -ldl  -fsanitize=fuzzer && :
clang-15: error: unable to execute command: Segmentation fault (core dumped)                                                                                          
clang-15: error: linker command failed due to signal (use -v to see invocation)                                                                                       
[321/322] Linking C executable Testing/TestFuzzCommonAssistanceHexStringToBin                                                                                         
FAILED: Testing/TestFuzzCommonAssistanceHexStringToBin                                                                                                                
: && /usr/local/bin/clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-sc
ope -fsanitize=fuzzer-no-link -Wno-c11-extensions -Wno-gnu -fno-omit-frame-pointer -fsanitize=address -fsanitize-blacklist=/src/FreeRDP/scripts/blacklist-address-sani
tizer.txt -fsanitize-address-use-after-scope -g -flto=thin -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=addres
s -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -fsanitize=address libfreerdp/common/test/CMakeFiles/TestFuzzCommonAssistanceHexStringTo
Bin.dir/TestFuzzCommonAssistanceHexStringToBin.c.o -o Testing/TestFuzzCommonAssistanceHexStringToBin  libfreerdp/libfreerdp3.a  winpr/libwinpr/libwinpr3.a  -lrt  -lm 
 /usr/lib/x86_64-linux-gnu/libicui18n.a  /usr/lib/x86_64-linux-gnu/libicuuc.a  /usr/lib/x86_64-linux-gnu/libicuio.a  /usr/lib/x86_64-linux-gnu/libssl.a  /usr/lib/x86_
64-linux-gnu/libcrypto.a  -ldl  -fsanitize=fuzzer && :
clang-15: error: unable to execute command: Segmentation fault (core dumped)                                                                                          
clang-15: error: linker command failed due to signal (use -v to see invocation)                                                                                       
[322/322] Linking C executable Testing/TestFuzzCommonAssistanceParseFileBuffer                                                                                        
FAILED: Testing/TestFuzzCommonAssistanceParseFileBuffer                                                                                                               
: && /usr/local/bin/clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-sc
ope -fsanitize=fuzzer-no-link -Wno-c11-extensions -Wno-gnu -fno-omit-frame-pointer -fsanitize=address -fsanitize-blacklist=/src/FreeRDP/scripts/blacklist-address-sani
tizer.txt -fsanitize-address-use-after-scope -g -flto=thin -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=addres
s -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -fsanitize=address libfreerdp/common/test/CMakeFiles/TestFuzzCommonAssistanceParseFileBu
ffer.dir/TestFuzzCommonAssistanceParseFileBuffer.c.o -o Testing/TestFuzzCommonAssistanceParseFileBuffer  libfreerdp/libfreerdp3.a  winpr/libwinpr/libwinpr3.a  -lrt  -
lm  /usr/lib/x86_64-linux-gnu/libicui18n.a  /usr/lib/x86_64-linux-gnu/libicuuc.a  /usr/lib/x86_64-linux-gnu/libicuio.a  /usr/lib/x86_64-linux-gnu/libssl.a  /usr/lib/x
86_64-linux-gnu/libcrypto.a  -ldl  -fsanitize=fuzzer && :
clang-15: error: unable to execute command: Segmentation fault (core dumped)  
```

**Comment by ligurio** [comment]
@jonathanmetzman could you review, please?

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
Do you have to disable MSAN?

**Comment by ligurio** [comment]
> Do you have to disable MSAN?

Right. Due to false positive in OpenSSL.
I don't have enough power to instrument all dependencies by MSan to avoid FP's.

**Comment by jonathanmetzman** [comment]
Sorry about that. I don't think we do, and to be honest, I don't think we pay a whole lot of attention to what goes in the messages.
Would developers squashing their commits themselves fix this issue?

**Pull request merged**
