### PR TITLE
[Rolling out Centipede] Project 1 - 5

### PR DESCRIPTION
**Pull request by Alan32Liu**
Given that `Centipede` works fine on our test project `github-scarecrow`, we will gradually roll it out to let more real-world fuzzing targets benefit from it.
The first round contains the following 5 projects:
1. `brotli`,
2. `brunsli`,
3. `draco`,
4. `http-pattern-matcher`,
5. `woff2`.

Projects are selected because:
1. They are `C++` projects,
2. They are from `Google`.

There will be another two rounds (5 + 10) as soon as we can confirm that `Centipede` works fine in the first round.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
See CI for more details.

**Comment by jonathanmetzman** [comment]
I suggest doing skcms as a project since:
1. It's a simple project
2. It builds fast.
3. We use it as a canary build, meaning when we change infra we test it automatically in CI even if the project isn't changed.

You will need to update a unittest though.

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
Waiting for the approval for #8697.

**Comment by Alan32Liu** [comment]
> I suggest doing skcms as a project since:
> 
> 1. It's a simple project
> 2. It builds fast.
> 3. We use it as a canary build, meaning when we change infra we test it automatically in CI even if the project isn't changed.
> 
> You will need to update a unittest though.

Sure, thanks! 
We plan to add 20 in total, leaving 15 to go. Please let me know if there are any other projects you'd recommend : )
I will add them once we can confirm this round works successfully!

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
CI fails because the `base-runner` is not up-to-date.
It does not build locally but [pulls from the cloud](https://github.com/google/oss-fuzz/actions/runs/3261851704/jobs/5357664912#step:8:716).
Would there be a better way to update `base-runner` to the cloud? I am not authorized to push my local image.

**Comment by Alan32Liu** [comment]
> CI fails because the `base-runner` is not up-to-date. It does not build locally but [pulls from the cloud](https://github.com/google/oss-fuzz/actions/runs/3261851704/jobs/5357664912#step:8:716):
> 
> ```shell
> Unable to find image 'gcr.io/oss-fuzz-base/base-runner:latest' locally
> latest: Pulling from oss-fuzz-base/base-runner
> ```
> 
> Would there be a better way to update `base-runner` to the cloud? I am not authorized to push my local image.

`base-runner` updated automatically, all CI passed.

**Comment by Alan32Liu** [comment]
@jonathanmetzman: As our #8697 has fixed all CI failures here, could you please have another look at this? 
Thanks!
I reckon this is related to production, hence it is better to double-check with you before merging : )

**Comment by Alan32Liu** [comment]
The second round of rollout is also ready at #8801.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
