### PR TITLE
Upstream existing openweave-core fuzzers to oss-fuzz

### PR DESCRIPTION
**Pull request by bshastry**
As the title reads. CC @kcc 

TBD items
  - Who is the primary contact for openweave-core? (See project.yaml)

For the near future
  - How useful are the existing fuzzers?
  - What can be done to improve coverage?

### CODE REVIEW

**Comment by bshastry** [comment]
Working on a fix for the build failure reported by CI. Seems to be related to https://github.com/openweave/openweave-core/issues/7 but not sure.

**Comment by guidovranken** [comment]
I started work on enhancing the existing fuzzers after @kcc notified me of it. I currently don't have time to finish this. Feel free to take and use my existing work. https://github.com/guidovranken/openweave-core/tree/fuzzing

**Comment by bshastry** [comment]
Just realized my approach is wrong. openweave's build configuration does not generate a self contained fuzzing binary, so even if the current build failure were fixed, `check_build` is going to fail.

This needs more work than I initially thought. Should I keep this PR open or close it and open a new one when I have figured out a solution?

**Comment by kcc** [comment]
If this needs more than several days, please close this PR and open another one, when ready. 
Thanks!! 
(and thanks @guidovranken for sharing your work)

**Comment by guidovranken** [comment]
@bshastry you can clone my branch and ```./configure --enable-fuzzing && make -j12``` and it will generate fuzzer binaries.

Alternatively, @kcc you can integrate my branch into OSS-Fuzz. It's better than nothing. I will not apply for a bounty for this because I haven't finished it.

**Comment by bshastry** [comment]
Feel free to close this PR and merge @guidovranken version

**Comment by bshastry** [comment]
Closing PR. Will open a new one when I have an update

**Pull request closed without merging**
