### PR TITLE
Don't use centipede's install script

### PR DESCRIPTION
**Pull request by jonathanmetzman**
We can't simply autoremove the packages it installs and it adds 500 MB to the image size.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer introspector address --fuzzing-engine libfuzzer centipede

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer centipede

**Comment by jonathanmetzman** [comment]
We need to be more disciplined about installing packages in base-images. Now there are projects that depend on these that will have to be manually fixed (e.g. envoy on python3)

**Comment by jonathanmetzman** [comment]
failures:
```
kimageformats - looks like flake
libraw - can't find -lz
librdkafka - can't find -lz
libreoffice - configure: error: select TLS backend(s) or disable TLS with --without-ssl. (spurious, happening in prod)
mp4parse-rust - looks spurious `help: ensure that all possible cases are being handled by adding a match arm with a wildcard pattern, a match arm with multiple or-patterns as shown, or multiple match arms` 
nogolo-fuzz looks spurious
`
 clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -fsanitize=fuzzer fuzz_ng_net_rpc/ngolofuzz.pb.o fuzz_ng_net_rpc//ngolofuzz.o fuzz_ng_net_rpc.a /src/LPM/src/libfuzzer/libprotobuf-mutator-libfuzzer.a /src/LPM/src/libprotobuf-mutator.a /src/LPM/external.protobuf/lib/libprotobuf.a -o /workspace/out/libfuzzer-address-x86_64/fuzz_ng_net_rpc
clang-15: error: no such file or directory: 'fuzz_ng_net_rpc.a'`
envoy: no python3

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py kimageformats libraw librdkafka libreoffice mp4parse-rust nogolo-fuzz envoy --sanitizer address --fuzzing-engine libfuzzer centipede

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py kimageformats libraw librdkafka libreoffice mp4parse-rust nogolo-fuzz envoy --sanitizer address --fuzzing-engine libfuzzer centipede

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py kimageformats libraw librdkafka libreoffice mp4parse-rust nogolo-fuzz envoy --sanitizer address --fuzzing-engine libfuzzer centipede --force

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py kimageformats libraw librdkafka libreoffice mp4parse-rust nogolo-fuzz envoy --sanitizer address --fuzzing-engine libfuzzer centipede --force

**Comment by jonathanmetzman** [comment]
cancelled last builds due to confusion

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py kimageformats libraw librdkafka libreoffice mp4parse-rust nogolo-fuzz envoy --sanitizer address --fuzzing-engine libfuzzer centipede --force

**Review by Alan32Liu — APPROVED** [review]
Thanks for removing the unnecessary installations from `base-builder` and adding the necessary dependencies to projects.
I am not sure if I fully understand why this would cause `envoy`'s `'no python3'` error though, as the [`./install_denependencies_debian.sh`](https://github.com/google/centipede/blob/main/install_dependencies_debian.sh) script does not seem to install `python3` either?

**Comment by jonathanmetzman** [comment]
> Thanks for removing the unnecessary installations from `base-builder` and adding the necessary dependencies to projects. I am not sure if I fully understand why this would cause `envoy`'s `'no python3'` error though, as the [`./install_denependencies_debian.sh`](https://github.com/google/centipede/blob/main/install_dependencies_debian.sh) script does not seem to install `python3` either?

I could be wrong, but I think when I autoremoved the stuff installed by this script (manually during testing) it removed python3. I think this pulls in python3 implicitly (along with llvm-10 which we don't need)

**Comment by jonathanmetzman** [comment]
> > Thanks for removing the unnecessary installations from `base-builder` and adding the necessary dependencies to projects. I am not sure if I fully understand why this would cause `envoy`'s `'no python3'` error though, as the [`./install_denependencies_debian.sh`](https://github.com/google/centipede/blob/main/install_dependencies_debian.sh) script does not seem to install `python3` either?
> 
> I could be wrong, but I think when I autoremoved the stuff installed by this script (manually during testing) it removed python3. I think this pulls in python3 implicitly (along with llvm-10 which we don't need)

Also, my fix to envoy of installing python3 in its Dockerfile seems to have worked.

**Comment by Alan32Liu** [comment]
I see, I will be more careful about installing packages into the base images in the future, then.

**Comment by jonathanmetzman** [comment]
> I see, I will be more careful about installing packages into the base images in the future, then.

Sorry, this wasn't really directed at you in particular.

**Comment by Alan32Liu** [comment]
> > I see, I will be more careful about installing packages into the base images in the future, then.
> 
> Sorry, this wasn't really directed at you in particular. :-) Thanks for doing the centipede work!

No worries at all!
I do think that if I had a better understanding of this when I added the installation script, I should have checked through it more thoroughly and not simply installed them all.

**Comment by jonathanmetzman** [comment]
By trying to save money and only rerunning the trial build on "broken projects", I think I let this issue slip through: https://github.com/google/oss-fuzz/issues/8915

**Pull request merged**
