### PR TITLE
s/test_all/test_all.py for google cloud build.

### PR DESCRIPTION
**Pull request by inferno-chromium**
Fixes https://github.com/google/oss-fuzz/issues/4781

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
FYI, this shouldn't need a base-runner rebuild to test.

**Comment by inferno-chromium** [comment]
> FYI, this shouldn't need a base-runner rebuild to test.

need it for fuzzing build, as it runs check_build. base-images is in process of being rebuilt, will then verify again

**Comment by inferno-chromium** [comment]
@jonathanmetzman @oliverchang 
fyi, i missed this part about running https://github.com/google/oss-fuzz/blob/master/infra/build/functions/deploy.sh
this is needed for any changed build steps to work, otherwise fuzzing build were still failing, now it seems to be ok.

**Comment by oliverchang** [comment]
LGTM

**Pull request merged**
