### PR TITLE
[skia] Use older version of base-builder to use clang-12.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Skia requested a roll back so they have time to fix swiftshader bug.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @kjlubick

**Comment by kjlubick** [comment]
I think I have a solution with having the swiftshader ignore some compiler warnings.

I'm adding `-Wno-deprecated-declarations -Wno-deprecated-copy` to the `CXXFLAGS` before the call to `cmake`

**Comment by kjlubick** [comment]
`-Wno-deprecated-copy` isn't working because they specify `-Wdeprecated-copy` We might need to upstream a fix there

**Comment by kjlubick** [comment]
https://swiftshader-review.googlesource.com/c/SwiftShader/+/57028 for the upstream change

**Comment by kjlubick** [comment]
https://github.com/google/oss-fuzz/pull/6433 for silencing not-related warning messages. With the swiftshader patch, everything appears to compile locally.

**Pull request closed without merging**
