### PR TITLE
New : OSSF Scorecard webapp

### PR DESCRIPTION
**Pull request by naveensrinivasan**
- Fuzzing scorecard webapp

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

### CODE REVIEW

**Comment by naveensrinivasan** [comment]
@azeemshaikh38 @laurentsimon FYI...

**Comment by naveensrinivasan** [comment]
@oliverchang, I see this error https://github.com/google/oss-fuzz/runs/8139758565?check_suite_focus=true. What am I doing wrong?

**Comment by jonathanmetzman** [comment]
Please fix build failures.

**Comment by naveensrinivasan** [comment]
> Please fix build failures.

There is a go.mod already, and I don't know why it is failing. Would you be able to help? Thanks

**Comment by jonathanmetzman** [comment]
@AdamKorcz @DavidKorczynski do you know what's going wrong here?

**Comment by AdamKorcz** [comment]
Started a review but it is stuck as "pending". The WORKDIR looks incorrect in the Dockerfile. I believe it should be `WORKDIR $SRC/scorecard-webapp/app/server`

**Comment by naveensrinivasan** [comment]
> $SRC/scorecard-webapp/app/server

Thanks, it seems to be stuck after I changed that. 

```
INFO:root:Keeping existing build artifacts as-is (if any).
INFO:root:Running: docker run --rm --privileged --platform linux/amd64 -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e PROJECT_NAME=scorecard-web -e FUZZING_LANGUAGE=go -v /Users/naveen/go/src/github.com/naveensrinivasan/oss-fuzz/build/out/scorecard-web:/out -v /Users/naveen/go/src/github.com/naveensrinivasan/oss-fuzz/build/work/scorecard-web:/work -t gcr.io/oss-fuzz/scorecard-web.
---------------------------------------------------------------
Compiling libFuzzer to /usr/lib/libFuzzingEngine.a...  done.
---------------------------------------------------------------
CC=clang
CXX=clang++
CFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link
CXXFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++
RUSTFLAGS=--cfg fuzzing -Zsanitizer=address -Cdebuginfo=1 -Cforce-frame-pointers
---------------------------------------------------------------
+ go install github.com/AdamKorcz/go-118-fuzz-build@latest
go: downloading github.com/AdamKorcz/go-118-fuzz-build v0.0.0-20220830201510-13aab664f5f8
+ go get github.com/AdamKorcz/go-118-fuzz-build/utils
go: downloading github.com/AdaLogics/go-fuzz-headers v0.0.0-20220824214621-3c06a36a6952
go: downloading github.com/cyphar/filepath-securejoin v0.2.3
go: added github.com/AdamKorcz/go-118-fuzz-build v0.0.0-20220830201510-13aab664f5f8
+ compile_native_go_fuzzer github.com/ossf/scorecard-webapp/app/server FuzzVerifyWorkflow FuzzVerifyWorkflow
go: downloading github.com/cyberphone/json-canonicalization v0.0.0-20220623050100-57a0ce2678a7
go: downloading github.com/go-openapi/strfmt v0.21.3
go: downloading github.com/go-openapi/runtime v0.24.1
go: downloading github.com/google/go-github/v42 v42.0.0
go: downloading github.com/rhysd/actionlint v1.6.16
go: downloading github.com/transparency-dev/merkle v0.0.1
go: downloading gocloud.dev v0.24.1-0.20211119014450-028788aaaa4c
go: downloading github.com/asaskevich/govalidator v0.0.0-20210307081110-f21760c49a8d
go: downloading github.com/go-openapi/errors v0.20.3
go: downloading github.com/mitchellh/mapstructure v1.4.3
go: downloading github.com/oklog/ulid v1.3.1
go: downloading go.mongodb.org/mongo-driver v1.10.0
go: downloading github.com/go-openapi/swag v0.22.3
go: downloading github.com/go-openapi/validate v0.22.0
go: downloading github.com/go-openapi/analysis v0.21.4
go: downloading github.com/go-openapi/loads v0.21.2
go: downloading github.com/go-openapi/spec v0.20.7
go: downloading github.com/google/go-querystring v1.1.0
go: downloading golang.org/x/crypto v0.0.0-20220622213112-05595931fe9d
go: downloading github.com/fatih/color v1.13.0
go: downloading github.com/mattn/go-colorable v0.1.12
go: downloading github.com/mattn/go-runewidth v0.0.13
go: downloading github.com/robfig/cron v1.2.0
go: downloading golang.org/x/sync v0.0.0-20220513210516-0976fa681c29
go: downloading golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading cloud.google.com/go/compute v1.6.0
go: downloading cloud.google.com/go/iam v0.3.0
go: downloading cloud.google.com/go v0.100.2
go: downloading cloud.google.com/go/storage v1.22.0
go: downloading github.com/google/wire v0.5.0
go: downloading github.com/googleapis/gax-go/v2 v2.3.0
go: downloading golang.org/x/oauth2 v0.0.0-20220411215720-9780585627b5
go: downloading google.golang.org/api v0.75.0
go: downloading google.golang.org/genproto v0.0.0-20220414192740-2d67ff6cf2b4
go: downloading go.opencensus.io v0.23.0
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/mattn/go-isatty v0.0.14
go: downloading github.com/rivo/uniseg v0.2.0
go: downloading github.com/go-openapi/jsonreference v0.20.0
go: downloading google.golang.org/grpc v1.46.0
go: downloading google.golang.org/protobuf v1.28.0
go: downloading golang.org/x/xerrors v0.0.0-20220411194840-2f41105eb62f
go: downloading github.com/golang/protobuf v1.5.2
go: downloading github.com/googleapis/go-type-adapters v1.0.0
go: downloading github.com/josharian/intern v1.0.0
go: downloading golang.org/x/net v0.0.0-20220722155237-a158d28d115b
go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
go: downloading github.com/google/go-cmp v0.5.8
go: downloading golang.org/x/text v0.3.7
replacing *testing.F
```

**Comment by AdamKorcz** [comment]
> > $SRC/scorecard-webapp/app/server
> 
> Thanks, it seems to be stuck after I changed that.
> 
> ```
> INFO:root:Keeping existing build artifacts as-is (if any).
> INFO:root:Running: docker run --rm --privileged --platform linux/amd64 -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e PROJECT_NAME=scorecard-web -e FUZZING_LANGUAGE=go -v /Users/naveen/go/src/github.com/naveensrinivasan/oss-fuzz/build/out/scorecard-web:/out -v /Users/naveen/go/src/github.com/naveensrinivasan/oss-fuzz/build/work/scorecard-web:/work -t gcr.io/oss-fuzz/scorecard-web.
> ---------------------------------------------------------------
> Compiling libFuzzer to /usr/lib/libFuzzingEngine.a...  done.
> ---------------------------------------------------------------
> CC=clang
> CXX=clang++
> CFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link
> CXXFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++
> RUSTFLAGS=--cfg fuzzing -Zsanitizer=address -Cdebuginfo=1 -Cforce-frame-pointers
> ---------------------------------------------------------------
> + go install github.com/AdamKorcz/go-118-fuzz-build@latest
> go: downloading github.com/AdamKorcz/go-118-fuzz-build v0.0.0-20220830201510-13aab664f5f8
> + go get github.com/AdamKorcz/go-118-fuzz-build/utils
> go: downloading github.com/AdaLogics/go-fuzz-headers v0.0.0-20220824214621-3c06a36a6952
> go: downloading github.com/cyphar/filepath-securejoin v0.2.3
> go: added github.com/AdamKorcz/go-118-fuzz-build v0.0.0-20220830201510-13aab664f5f8
> + compile_native_go_fuzzer github.com/ossf/scorecard-webapp/app/server FuzzVerifyWorkflow FuzzVerifyWorkflow
> go: downloading github.com/cyberphone/json-canonicalization v0.0.0-20220623050100-57a0ce2678a7
> go: downloading github.com/go-openapi/strfmt v0.21.3
> go: downloading github.com/go-openapi/runtime v0.24.1
> go: downloading github.com/google/go-github/v42 v42.0.0
> go: downloading github.com/rhysd/actionlint v1.6.16
> go: downloading github.com/transparency-dev/merkle v0.0.1
> go: downloading gocloud.dev v0.24.1-0.20211119014450-028788aaaa4c
> go: downloading github.com/asaskevich/govalidator v0.0.0-20210307081110-f21760c49a8d
> go: downloading github.com/go-openapi/errors v0.20.3
> go: downloading github.com/mitchellh/mapstructure v1.4.3
> go: downloading github.com/oklog/ulid v1.3.1
> go: downloading go.mongodb.org/mongo-driver v1.10.0
> go: downloading github.com/go-openapi/swag v0.22.3
> go: downloading github.com/go-openapi/validate v0.22.0
> go: downloading github.com/go-openapi/analysis v0.21.4
> go: downloading github.com/go-openapi/loads v0.21.2
> go: downloading github.com/go-openapi/spec v0.20.7
> go: downloading github.com/google/go-querystring v1.1.0
> go: downloading golang.org/x/crypto v0.0.0-20220622213112-05595931fe9d
> go: downloading github.com/fatih/color v1.13.0
> go: downloading github.com/mattn/go-colorable v0.1.12
> go: downloading github.com/mattn/go-runewidth v0.0.13
> go: downloading github.com/robfig/cron v1.2.0
> go: downloading golang.org/x/sync v0.0.0-20220513210516-0976fa681c29
> go: downloading golang.org/x/sys v0.0.0-20220722155257-8c9f86f7a55f
> go: downloading gopkg.in/yaml.v3 v3.0.1
> go: downloading cloud.google.com/go/compute v1.6.0
> go: downloading cloud.google.com/go/iam v0.3.0
> go: downloading cloud.google.com/go v0.100.2
> go: downloading cloud.google.com/go/storage v1.22.0
> go: downloading github.com/google/wire v0.5.0
> go: downloading github.com/googleapis/gax-go/v2 v2.3.0
> go: downloading golang.org/x/oauth2 v0.0.0-20220411215720-9780585627b5
> go: downloading google.golang.org/api v0.75.0
> go: downloading google.golang.org/genproto v0.0.0-20220414192740-2d67ff6cf2b4
> go: downloading go.opencensus.io v0.23.0
> go: downloading github.com/mailru/easyjson v0.7.7
> go: downloading github.com/go-openapi/jsonpointer v0.19.5
> go: downloading github.com/mattn/go-isatty v0.0.14
> go: downloading github.com/rivo/uniseg v0.2.0
> go: downloading github.com/go-openapi/jsonreference v0.20.0
> go: downloading google.golang.org/grpc v1.46.0
> go: downloading google.golang.org/protobuf v1.28.0
> go: downloading golang.org/x/xerrors v0.0.0-20220411194840-2f41105eb62f
> go: downloading github.com/golang/protobuf v1.5.2
> go: downloading github.com/googleapis/go-type-adapters v1.0.0
> go: downloading github.com/josharian/intern v1.0.0
> go: downloading golang.org/x/net v0.0.0-20220722155237-a158d28d115b
> go: downloading github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da
> go: downloading github.com/google/go-cmp v0.5.8
> go: downloading golang.org/x/text v0.3.7
> replacing *testing.F
> ```

Could you push the changes to the PR?

**Comment by AdamKorcz** [comment]
Working now. Please correct year in header @naveensrinivasan

**Comment by naveensrinivasan** [comment]
> Working now. Please correct year in header @naveensrinivasan

Thanks! I took care of it!

**Pull request merged**
