### PR TITLE
[infra] Save logs when generating code coverage for Go projects (#2817, #2714).

### PR DESCRIPTION
**Pull request by Dor1s**

### CODE REVIEW

**Review by Dor1s — COMMENTED** [review]
TBR and giving another try //cc @catenacyber

**Review by inferno-chromium — COMMENTED** [review]
LGTM

**Comment by catenacyber** [comment]
Looks good to me as well.

Now I can see go-dns coverage report on oss-fuzz.com
But not the other projects yet.
Are they coming ?

I notice golang project failed because of dummy mistake cf https://github.com/google/oss-fuzz/pull/4685

**Comment by Dor1s** [comment]
> Are they coming ?

Yes, they should appear in a day or two. go-dns and syzkaller I launched manually yesterday for testing purposes.

**Comment by catenacyber** [comment]
Thanks, will take a look tomorrow

**Pull request merged**
