### PR TITLE
[mp4parse-rust] Update project.yaml

### PR DESCRIPTION
**Pull request by tysmith**

### CODE REVIEW

**Comment by Navidem** [comment]
It's clear the CI error is not from your changes, but can you please inspect and see why is that happening?

**Comment by tysmith** [comment]
I've open https://github.com/mozilla/mp4parse-rust/issues/384 for the build failure.

**Comment by tysmith** [comment]
@Navidem the build has been fixed.

**Comment by Navidem** [comment]
> @Navidem the build has been fixed.

Thanks! Restarted CI.

**Review by Navidem — APPROVED** [review]

**Pull request merged**
