### PR TITLE
Add viktor@openssl.org to openssl project at oss-fuzz

### PR DESCRIPTION
**Pull request by vdukhovni**
I'll be one of the reviewers of extent and future issues.

### CODE REVIEW

**Review by Sashan — APPROVED** [review]
I think pull request needs to be re-submitted after singing google-cla.

**Comment by vdukhovni** [comment]
> I think pull request needs to be re-submitted after singing google-cla.

Pushed update with minor change in commit message, which should assuage the CLA check.

**Comment by vdukhovni** [comment]
> I think pull request needs to be re-submitted after singing google-cla.

Please re-approve, since the repush may supersede the prior approval.

**Review by Sashan — APPROVED** [review]
my approval still holds.

**Pull request merged**
