### PR TITLE
[trial build] Push images in parallel.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Saves about 10% of the time of a build.

### CODE REVIEW

**Review by Alan32Liu — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
Not gonna bother with this for now. Too much complexity required. But the time it takes to do trial builds is quite annoying.

**Comment by Alan32Liu** [comment]
> Not gonna bother with this for now. Too much complexity required. But the time it takes to do trial builds is quite annoying.

Maybe put it into a draft?

**Pull request closed without merging**
