### PR TITLE
Change GraphicsMagick Hg clone URL to Heptapod.  Add more depencency …

### PR DESCRIPTION
**Pull request by bobfriesenhahn**
The GraphicsMagick Hg URL is changed from (dead) OSDN to Heptapod. Additional dependency libraries are cloned for the build.

### CODE REVIEW

**Review by alex — APPROVED** [review]

**Review by reaperhulk — APPROVED** [review]

**Comment by bobfriesenhahn** [comment]
It seems that my Google CLA is now signed.  Maybe triggering this pull request again will go through?

**Comment by reaperhulk** [comment]
@bobfriesenhahn now that it's signed we just need a maintainer to approve the workflows to run (this is a defense against CI abuse that GitHub uses for new contributors). One of the Google folks will hopefully be able to do that soon 😄

**Comment by bobfriesenhahn** [comment]
Work has been done on the build script (not part of this merge request), which will hopefully allow the build tests to succeed.

**Comment by bobfriesenhahn** [comment]
I am not aware of any reason that the GraphicsMagick oss-fuzz tests should be taking appreciably longer than before, but the latest failure appears to be due to the validation time exceeding a 6 hour limit.  The tests appear to be progressing, but the sum of the time required is currently exceeding the arbitrary limit.

**Comment by bobfriesenhahn** [comment]
For some reason, many of the project tests are reporting:

```
Specified build: engine: libfuzzer, sanitizer: undefined, architecture: x86_64 not enabled for this project: graphicsmagick. Skipping build.
```

This seems odd.  I am unware of doing anything which might have influenced this.

**Comment by DavidKorczynski** [comment]
> For some reason, many of the project tests are reporting:
> 
> ```
> Specified build: engine: libfuzzer, sanitizer: undefined, architecture: x86_64 not enabled for this project: graphicsmagick. Skipping build.
> ```
> 
> This seems odd. I am unware of doing anything which might have influenced this.

This is only for UBSAN builds? And this happens because UBSAN is not included in the `sanitizer` list:

https://github.com/google/oss-fuzz/blob/f4ad98d71b6200ae4feb26af076090c694a13a72/projects/graphicsmagick/project.yaml#L9-L13C11


It looks like the CI is going to pass, thanks for adjusting @bobfriesenhahn -- just confirming with you that this is ready for merge (assuming the CI will pass)?

**Comment by bobfriesenhahn** [comment]
> It looks like the CI is going to pass, thanks for adjusting @bobfriesenhahn -- just confirming with you that this is ready for merge (assuming the CI will pass)?

Unfortunately, it did not pass.  The tests failed with:

```
cat: /tmp/not-out/tmp18m_mtqe/afl_options.txt: No such file or directory
```
My build script removes the content of $WORK and $OUT at the start of the build (to ease use of the shell 'compile' program).  This is the only thing I can imagine which might provoke the above problem, so I have now removed that.

Once the builds do pass, then everything needed should be in place.  The core of the change set is a change to the repository URL and cloning some additional repositories, since most of the build is controlled by a script and program in the GraphicsMagick repository.

**Review by DavidKorczynski — APPROVED** [review]
Awesome, thanks for your patience @bobfriesenhahn -- I think in the future the limited CI will hopefully be easier to work with.

**Pull request merged**
