### PR TITLE
Reduce size of instrospector install by 70 MB

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer coverage address memory undefined introspector --fuzzing-engine libfuzzer honggfuzz afl centipede

**Review by Navidem — APPROVED** [review]
LGTM

**Review by oliverchang — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer coverage address memory undefined introspector --fuzzing-engine libfuzzer honggfuzz afl centipede

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer coverage address memory undefined introspector --fuzzing-engine libfuzzer honggfuzz afl centipede

**Pull request merged**
