### PR TITLE
nginx: request access

### PR DESCRIPTION
**Pull request by DavidKorczynski**
@andrey-zelenkov I would like to submit fuzzers to nginx and in this context having the coverage information from clusterfuzz would be great, so I added myself on the CC list of the `project.yaml`. Are you okay with me getting access here? FYI I am regular oss-fuzz contributor and working on many different oss-fuzz projects https://github.com/google/oss-fuzz/commits?author=DavidKorczynski

### CODE REVIEW

**Comment by inferno-chromium** [comment]
i think maintainer list is all stale, @mdounin should we add you here ?

**Comment by mdounin** [comment]
> i think maintainer list is all stale, @mdounin should we add you here ?

I'm not familiar with oss-fuzz, @andrey-zelenkov is a better person to work with. I'll ping him to make sure he'll look at this.

**Comment by andrey-zelenkov** [comment]
Hi @DavidKorczynski! I missed this notification, sorry about that. Feel free to add yourself to the CC list and get access.

**Comment by DavidKorczynski** [comment]
Thanks @andrey-zelenkov ! 

@inferno-chromium should I remove the two googlers on the auto_ccs as I believe they are no longer active on it?

**Comment by inferno-chromium** [comment]
Yes please remove those inactive googlers

**Review by AdamKorcz — APPROVED** [review]

**Comment by andrey-zelenkov** [comment]
Hi @DavidKorczynski, could you also add my colleague to the CC list as well (his email is pluknet@gmail.com) http://hg.nginx.org/nginx/log?rev=Sergey+Kandaurov? He is better person to address issues with nginx.

**Comment by DavidKorczynski** [comment]
> Hi @DavidKorczynski, could you also add my colleague to the CC list as well (his email is [pluknet@gmail.com](mailto:pluknet@gmail.com)) http://hg.nginx.org/nginx/log?rev=Sergey+Kandaurov? He is better person to address issues with nginx.

Yep, done: https://github.com/google/oss-fuzz/pull/6225

FYI I will look into improving the fuzzing of Nginx in the near future so you should see activity from my side in a few weeks!

**Comment by andrey-zelenkov** [comment]
Ok, thank you!

**Comment by andrey-zelenkov** [comment]
Hi @DavidKorczynski, sorry for disturbing you again. About the following issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32649

Could you please take a look at the patch below from Sergey (he doesn't have a github account):
```diff --git a/projects/nginx/fuzz/http_request_fuzzer.cc b/projects/nginx/fuzz/http_request_fuzzer.cc
index d70e7199..317826c1 100644
--- a/projects/nginx/fuzz/http_request_fuzzer.cc
+++ b/projects/nginx/fuzz/http_request_fuzzer.cc
@@ -230,6 +230,9 @@ extern "C" int InitializeNginx(void) {
   ngx_event_actions.init = init_event;
   ngx_io.send_chain = send_chain;
   ngx_event_flags = 1;
+  ngx_queue_init(&ngx_posted_accept_events);
+  ngx_queue_init(&ngx_posted_next_events);
+  ngx_queue_init(&ngx_posted_events);
   ngx_event_timer_init(cycle->log);
   return 0;
 }
```

It should fix mentioned issue.

**Comment by DavidKorczynski** [comment]
> Hi @DavidKorczynski, sorry for disturbing you again. About the following issue: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=32649
> 
> Could you please take a look at the patch below from Sergey (he doesn't have a github account):
> 
> ```diff
> index d70e7199..317826c1 100644
> --- a/projects/nginx/fuzz/http_request_fuzzer.cc
> +++ b/projects/nginx/fuzz/http_request_fuzzer.cc
> @@ -230,6 +230,9 @@ extern "C" int InitializeNginx(void) {
>    ngx_event_actions.init = init_event;
>    ngx_io.send_chain = send_chain;
>    ngx_event_flags = 1;
> +  ngx_queue_init(&ngx_posted_accept_events);
> +  ngx_queue_init(&ngx_posted_next_events);
> +  ngx_queue_init(&ngx_posted_events);
>    ngx_event_timer_init(cycle->log);
>    return 0;
>  }
> ```
> 
> It should fix mentioned issue.

No problem! Feel free to disturb/ask/request for help with nginx fuzzing whenever.

**Comment by andrey-zelenkov** [comment]
Thank you again!

**Pull request merged**
