### PR TITLE
Properly fix stripping of -fsanitize=fuzzer-no-link for afl++

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Basically we don't need this https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L118 for afl++, see comment https://github.com/google/oss-fuzz/pull/5087#issuecomment-771086051

**Comment by inferno-chromium** [comment]
tbr

**Comment by oliverchang** [comment]
LGTM

**Review by jonathanmetzman — COMMENTED** [review]
LGTM

**Pull request merged**
