### PR TITLE
[libecc] Add project libecc

### PR DESCRIPTION
**Pull request by guidovranken**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Can you give us some background on this library and why it's important for us to fuzz?

**Comment by guidovranken** [comment]
@jonathanmetzman Response to your question from the libecc developer:

> First of all, libecc has been developed to have a fully compliant EC{*}DSA signature algorithms library (as per ISO14888-3). To the best of our knowledge, no other popular/general purpose C library offers out of the box variants of ECDSA such as ECKCDSA, ECFSDSA and so on. We also wanted to have compatibility with rather small embedded devices, and try (our best) to include best practices for security (both software and against physical attacks): in such a context, we strongly believe that fuzzing is a cornerstone for continuous improvement of the library.
>
> Libecc is used in open source projects such as the WooKey project (https://wookey-project.github.io/tataouine/externals.html) that implements an open hardware encryption device, and the french government "stopcovid19" project (https://gitlab.inria.fr/stopcovid19/CLEA-exposure-verification/-/tree/master/CLEA-lib/c). It has also been used as a companion library for tests and comparisons in the academic research area (https://www.theses.fr/2019PSLEE048.pdf, https://ntnuopen.ntnu.no/ntnu-xmlui/bitstream/handle/11250/2624671/no.ntnu:inspera:39602101:18515083.pdf?sequence=1, https://dspace.vutbr.cz/bitstream/handle/11012/186727/520_eeict2019.pdf?sequence=1, http://pari.math.u-bordeaux.fr/Events/PARI2020/talks/MPHELL.pdf, etc.).
Finally, as a BSD licensed software, it is also used in closed source projects that are not disclosed. These include, to the best of our knowledge, banking services and aerospace embedded firmware areas.

**Comment by randombit** [comment]
@guidovranken Curious if cryptofuzz is cross checking ECKCDSA or ECGDSA at the moment. Could be some interesting finds there.

**Comment by jonathanmetzman** [comment]
@guidovranken Seems pretty important.
We approve.

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by guidovranken** [comment]
x

> @guidovranken Curious if cryptofuzz is cross checking ECKCDSA or ECGDSA at the moment. Could be some interesting finds there.

Not yet. Does Botan support any of these?

> @guidovranken Seems pretty important.
> We approve.

Thanks!

**Comment by randombit** [comment]
@guidovranken Yes Botan has ECKCDSA and ECGDSA. And I believe what libecc calls ECRDSA is equivalent to Botan's GOST 34.10. ECFSDSA I have never heard of and all the hits for it on Google are to libecc (maybe this is something invented by ANSSI themselves?). I think Crypto++ has ECGDSA as well.

**Comment by rb-anssi** [comment]
Hi,

Thanks @guidovranken for his great work integrating libecc to Cryptofuzz, and thanks to the OSS-Fuzz team for this approval. 

Here are some details and insights about the signature standards supported by libecc, and their origins (as these can be a bit convoluted). All the signatures supported by libecc are described in [ISO/IEC-14888-3](https://www.iso.org/obp/ui/fr/#iso:std:iso-iec:14888:-3:ed-4:v1:en) (this standard, as many ISO ones, is unfortunately not free). These include EC-DSA, and variants from different countries standards: EC-KCDSA (Korean) [1], EC-GDSA (German) [2], EC-RDSA (Russian) [3]. EC-RDSA is indeed as @randombit spotted an equivalent to GOST 34.10 also described by [IETF RFC 7091](https://tools.ietf.org/html/rfc7091), with the difference that the Russian standard seems to make it mandatory that the hash function is GOST R 34.11-2012, while EC-RDSA accepts any hash function (and libecc only supports SHA-2 and SHA-3 for now).

Beyond these standards specific to countries, ISO also provides variants of the Shnorr signature scheme adapted to Elliptic Curves (EC-Shnorr) through EC-SDSA [4], EC-OSDSA ("optimized" EC-SDSA) [5], and EC-FSDSA (for "Full-Shnorr") also taken from [4].

Sorry for the rather long answer, but I hope that this makes things a little bit clearer regarding this EC based signatures standards mess ... And indeed, crosschecking signature schemes beyond EC-DSA between libraries supporting them would be great! :-)

(NOTE: the following references are extracted from the ISO-14888-3 standard)

[1] TTAK.KO-12.0015/R2, Digital Signature Mechanism with Appendix - Part 3: Korean Certificatebased Digitial Signature Algorithm using Elliptic Curves EC-KCDSA, 2014. (In Korean) 
[2] Erwin H., & Pascale S. Digital Signature Scheme EC-GDSA, German Federal Office for Information
Security, December 2005
[3] GOST R 34.10-2012, State Standard of the Russian Federation, “Information technology.
Cryptographic data security. Signature and verification processes of [electronic] digital signature.”
State Committee of the Russian Federation on Standards and Metrology, 2012. (In Russian)
[4] Schnorr C.P. Efficient signature generation for smart cards. J. Cryptol. 1991, 4 pp. 161–174
[5] Neven G., Smart N., Warinschi B. Hash function requirements for Schnorr signatures. Journal
of Mathematical Cryptology. 2009, 3 pp. 69–87

**Pull request merged**
