### PR TITLE
[protobuf-java] Initial integration

### PR DESCRIPTION
**Pull request by fmeum**
@acozzette Would you be interested in OSS-Fuzz integration for the Protobuf Java library? This is the fuzzer that found the bugs fixed in https://github.com/protocolbuffers/protobuf/commit/4008d229aa7505775486d6a86705efd2800599b3#diff-39e30ba0f9474a5c558a5c5496dd085d7ff93ae2f3521416735287a1ae4153e3.

### CODE REVIEW

**Comment by acozzette** [comment]
I haven't worked a whole lot on protobuf Java in particular, but that sounds great to have fuzzer coverage for it!

**Comment by fmeum** [comment]
If that's fine with you, the two of us will receive the fuzzer reports. Since I have also set up Java fuzzing in OSS-Fuzz, that will give me the chance to diagnose issues with the fuzzer as well as provide help when reproducing issues locally.

@acozzette Is that okay for you?

@inferno-chromium This is ready for review now and can be merged if @acozzette has given confirmed the above.

**Comment by acozzette** [comment]
Yes, sounds great. Thanks for setting this up!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
