### PR TITLE
Update primary contact and CCs for USBGuard project

### PR DESCRIPTION
**Pull request by ZoltanFridrich**

### CODE REVIEW

**Comment by ZoltanFridrich** [comment]
@googlebot I signed it!

**Comment by Allen-Webb** [comment]
I can confirm these contacts need to be updated.

**Comment by inferno-chromium** [comment]
@Allen-Webb - note that builds are broken atm

```
*** Warning: Linking the shared library libusbguard.la against the
*** static library /usr/lib/x86_64-linux-gnu/libqb.a is not portable!

*** Warning: Linking the shared library libusbguard.la against the
*** static library /usr/lib/x86_64-linux-gnu/libprotobuf.a is not portable!
copying selected object files to avoid basename conflicts...
ar: `u' modifier ignored since `D' is the default (see `U')
++ nproc
+ make -j2 -C src/Tests/Fuzzers fuzzer-rules fuzzer-usb-descriptor fuzzer-uevent
make: Entering directory '/src/usbguard/src/Tests/Fuzzers'
  CXX      fuzzer-rules.o
  CXX      fuzzer-usb-descriptor.o
fuzzer-rules.cpp:26:10: fatal error: 'tao/pegtl/contrib/tracer.hpp' file not found
#include <tao/pegtl/contrib/tracer.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Makefile:437: recipe for target 'fuzzer-rules.o' failed
```

**Comment by Allen-Webb** [comment]
A pull request was just merged that resolves those errors:
https://github.com/USBGuard/usbguard/pull/458

**Pull request merged**
