### PR TITLE
Bump introspector

### PR DESCRIPTION
**Pull request by Navidem**

### CODE REVIEW

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib unrar leveldb c-ares --sanitizer introspector --fuzzing-engine libfuzzer

**Review by oliverchang — APPROVED** [review]

**Review by oliverchang — CHANGES_REQUESTED** [review]
I think a number of things are broken in the latest version. e.g. https://storage.googleapis.com/oss-fuzz-introspector/libarchive/inspector-report/20220802/fuzz_report.html#fuzz_blocker0 

The call sites links don't work.

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib unrar leveldb c-ares --sanitizer introspector --fuzzing-engine libfuzzer

**Review by oliverchang — APPROVED** [review]

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib unrar leveldb c-ares --sanitizer introspector --fuzzing-engine libfuzzer

**Pull request merged**
