### PR TITLE
pigweed: Fix build by switching to bazel

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
TODO:
- [ ] Once [CL/175618](https://pigweed-review.googlesource.com/c/pigweed/pigweed/+/175618) is merged switch the git clone back to the main pigweed remote.

**Comment by silvergasp** [comment]
CC @armandomontanez

**Review by armandomontanez — APPROVED** [review]
LGTM

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
