### PR TITLE
[trial-build] Test changes to base-runner

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
This trial build should fail because of https://github.com/google/oss-fuzz/pull/8188 .

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address coverage memory undefined --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
I think the breakage is probably due to Ubuntu's apt-get having net work failures.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

**Review by oliverchang — COMMENTED** [review]
LGTM

**Pull request merged**
