### PR TITLE
Ignore fuzz setup problem detection during building with afl++

### PR DESCRIPTION
**Pull request by vanhauser-thc**
This disables checking for fuzz setup problems while still building the target.

### CODE REVIEW

**Comment by vanhauser-thc** [comment]
see #7026 
most likely cpython and mercurial will still fail when doing the testing of the fuzz target. but this will need to be corrected in the target.

**Comment by vanhauser-thc** [comment]
this fixes all known current issues: mercurial, cypthon, openssl and libxml

@DavidKorczynski @jonathanmetzman 

Jonathan please note I also created a PR in clusterfuzz.

**Review by jonathanmetzman — APPROVED** [review]
LGTM, thanks!
Nervous about landing this because it bumps AFL++.
We will merge this on Tuesday (monday is public holiday)

**Comment by vanhauser-thc** [comment]
A fix for iselect instrumentation in llvm14 as well as fixing a corner case in LAF intel string handling.

**Comment by vanhauser-thc** [comment]
(fixes #6879)

**Pull request merged**
