### PR TITLE
Go 1.21

### PR DESCRIPTION
**Pull request by catenacyber**
cc @DavidKorczynski 

Should replace https://github.com/google/oss-fuzz/pull/9950

Should fix ngolo-fuzzing build cf https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60807

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py go --sanitizer address coverage undefined --fuzzing-engines libfuzzer

**Comment by catenacyber** [comment]
From CI, It looks like there is something wrong with base-builder-javascript, so unrelated to this PR, right ?

**Comment by jonathanmetzman** [comment]
Blocked on https://github.com/google/oss-fuzz/issues/10936

**Comment by catenacyber** [comment]
#10936 was solved, and I rebased to fix a conflict

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py go --sanitizer address coverage undefined --fuzzing-engines libfuzzer

**Comment by catenacyber** [comment]
gcbrun failed due to some quota ?

**Comment by jonathanmetzman** [comment]
> gcbrun failed due to some quota ?

I think there's a genuine failure in Kubeedge
https://oss-fuzz-gcb-logs.storage.googleapis.com/log-466e06e4-99c8-46a1-bf17-d724568ab38d.txt

```
Step #19 - "compile-libfuzzer-address-x86_64": go: downloading gopkg.in/fsnotify.v1 v1.4.7
Step #19 - "compile-libfuzzer-address-x86_64": go: downloading golang.org/x/text v0.3.0
Step #19 - "compile-libfuzzer-address-x86_64": go: finding module for package github.com/AdaLogics/go-fuzz-headers
Step #19 - "compile-libfuzzer-address-x86_64": go: downloading github.com/AdaLogics/go-fuzz-headers v0.0.0-20230811130428-ced1acdcaa24
Step #19 - "compile-libfuzzer-address-x86_64": go: found github.com/AdaLogics/go-fuzz-headers in github.com/AdaLogics/go-fuzz-headers v0.0.0-20230811130428-ced1acdcaa24
Step #19 - "compile-libfuzzer-address-x86_64": github.com/kubeedge/viaduct/pkg/lane
Step #19 - "compile-libfuzzer-address-x86_64": github.com/kubeedge/viaduct/pkg/lane
Step #19 - "compile-libfuzzer-address-x86_64": Running go-fuzz -tags gofuzz -func FuzzLaneReadMessage -o fuzz_lane_read_message.a github.com/kubeedge/viaduct/pkg/lane
Step #19 - "compile-libfuzzer-address-x86_64": ++ cp /src/cncf-fuzzing/projects/kubeedge/dtmanager_fuzzer.go /src/kubeedge/edge/pkg/devicetwin/dtmanager/
Step #19 - "compile-libfuzzer-address-x86_64": ++ mv /src/kubeedge/edge/pkg/devicetwin/dtmanager/twin_test.go /src/kubeedge/edge/pkg/devicetwin/dtmanager/twint_test_fuzz.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ cd /src/kubeedge
Step #19 - "compile-libfuzzer-address-x86_64": ++ go mod tidy
Step #19 - "compile-libfuzzer-address-x86_64": ++ go mod vendor
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/klog\./\/\/klog\./g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/twin.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/\"k8s\.io\/klog\/v2"/\/\/\"k8s\.io\/klog\/v2\"/g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/twin.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/klog\./\/\/klog\./g' -i /src/kubeedge/edge/pkg/devicetwin/dtcontext/dtcontext.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/\"k8s\.io\/klog\/v2"/\/\/\"k8s\.io\/klog\/v2\"/g' -i /src/kubeedge/edge/pkg/devicetwin/dtcontext/dtcontext.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/klog\./\/\/klog\./g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/communicate.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/\"k8s\.io\/klog\/v2"/\/\/\"k8s\.io\/klog\/v2\"/g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/communicate.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/klog\./\/\/klog\./g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/membership.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/\"k8s\.io\/klog\/v2"/\/\/\"k8s\.io\/klog\/v2\"/g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/membership.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/klog\./\/\/klog\./g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/device.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ sed 's/\"k8s\.io\/klog\/v2"/\/\/\"k8s\.io\/klog\/v2\"/g' -i /src/kubeedge/edge/pkg/devicetwin/dtmanager/device.go
Step #19 - "compile-libfuzzer-address-x86_64": ++ compile_go_fuzzer github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager FuzzdealTwinActions fuzz_deal_twin_actions
Step #19 - "compile-libfuzzer-address-x86_64": /usr/local/bin/compile_go_fuzzer: line 28: cd: /root/go/src/github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager: No such file or directory
Step #19 - "compile-libfuzzer-address-x86_64": github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager
Step #19 - "compile-libfuzzer-address-x86_64": github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager
Step #19 - "compile-libfuzzer-address-x86_64": Running go-fuzz -tags gofuzz -func FuzzdealTwinActions -o fuzz_deal_twin_actions.a github.com/kubeedge/kubeedge/edge/pkg/devicetwin/dtmanager
Step #19 - "compile-libfuzzer-address-x86_64": # github.com/cilium/ebpf/internal/btf
Step #19 - "compile-libfuzzer-address-x86_64": vendor/github.com/cilium/ebpf/internal/btf/fuzz.go:20:15: undefined: loadNakedSpec
Step #19 - "compile-libfuzzer-address-x86_64": 2023/09/13 14:04:18 failed to build packages:exit status 1
Step #19 - "compile-libfuzzer-address-x86_64": ********************************************************************************
Step #19 - "compile-libfuzzer-address-x86_64": Failed to build.
Step #19 - "compile-libfuzzer-address-x86_64": To reproduce, run:
Step #19 - "compile-libfuzzer-address-x86_64": python infra/helper.py build_image kubeedge
Step #19 - "compile-libfuzzer-address-x86_64": python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 kubeedge
```

**Comment by catenacyber** [comment]
Solved 
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60808#c8
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=60807#c10
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61406#c6
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61077#c7

@AdamKorcz did you have other golang projects back ?

**Pull request merged**
