### PR TITLE
hyperium: update project.yaml

### PR DESCRIPTION
**Pull request by DavidKorczynski**
@seanmonstar I am adding @olix0r and @hawkw from the Buoyant team as CCs on hyperium. Can you confirm this is okay?

### CODE REVIEW

**Comment by seanmonstar** [comment]
I mean, I don't mind if they're added, but have you checked with them if they want to get the emails?

**Comment by DavidKorczynski** [comment]
> I mean, I don't mind if they're added, but have you checked with them if they want to get the emails?

Yep - we are in contact and they would be happy to receive them!

**Comment by seanmonstar** [comment]
Huh, so I tried looking at the details of an issue, and it's complaining that I'm not authorized. I presume it's because the yaml has `seanmonstar` but my Google account forwards the name `sean.monstar`?

**Comment by DavidKorczynski** [comment]
hmm - the authorisation should use the email `seanmonstar@gmail.com` - I dont see a reason it would forward the name `sean.monstar`?

**Comment by seanmonstar** [comment]
It is, and I understand that periods with gmail usually can be placed anywhere. My guess is that the auth check on the oss-fuzz thing is strictly comparing emails, cause I see:

> You (email=sean.monstar@gmail.com) are not authorized to access this page!

**Comment by DavidKorczynski** [comment]
>  My guess is that the auth check on the oss-fuzz thing is strictly comparing emails, cause I see:
> 
> > You (email=[sean.monstar@gmail.com](mailto:sean.monstar@gmail.com)) are not authorized to access this page!

Most likely, we can try and add a period to the contact email in the `project.yaml` and see if it gets sorted?

**Review by asraa — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
For future references it seems the period in the email resolved the issue - can you confirm this @seanmonstar ?

**Comment by seanmonstar** [comment]
Yep, I can view them now, thank you!

**Pull request merged**
