### PR TITLE
Adds project libav

### PR DESCRIPTION
**Pull request by catenacyber**
With avprobe fuzz target

Waiting for upstream approval

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Is libav used anywhere now, looks like distros that switched are back to ffmpeg - https://en.wikipedia.org/wiki/Libav

**Comment by catenacyber** [comment]
Found it referenced here : https://hackerone.com/ibb-data

**Comment by inferno-chromium** [comment]
> Found it referenced here : https://hackerone.com/ibb-data

This can be stale data. I dont see project active - see last release date on https://www.libav.org/, also https://github.com/libav/libav/commits/master

**Comment by catenacyber** [comment]
Yes, I saw.
So, should I close this ?

**Comment by inferno-chromium** [comment]
Yes closing.

**Pull request closed without merging**
