### PR TITLE
[infra] exits with a non-zero code when a fuzzer doesn't pass the build checks

### PR DESCRIPTION
**Pull request by evverx**
Closes https://github.com/google/oss-fuzz/issues/1987.

### CODE REVIEW

**Comment by Dor1s** [comment]
Uploaded https://github.com/google/oss-fuzz/pull/1993

**Comment by Dor1s** [comment]
Thanks again for the patch, we've landed #1933 that should solve the issue (just wait for the base images to get rebuilt and don't forget to run `python infra/helper.py pull_images` locally

**Comment by evverx** [comment]
Thank you! I've just rebuilt the base-runner image locally with `./infra/helper.py build_image base-runner` and for some reason `bash` is complaining that `/usr/local/bin/bad_build_check: line 208: return: BAD: numeric argument required` when I'm trying to check the systemd fuzzers.

**Comment by Dor1s** [comment]
Ahh, missed that part, just give me a couple minutes!

**Comment by Dor1s** [comment]
Looks like https://github.com/google/oss-fuzz/commit/9eb9f3bb639b4622ed708fd7310be232ee22d888 works well, thanks for following up!

**Comment by Dor1s** [comment]
Sure, it is possible to make it configurable (e.g. via project.yaml or .options file), but we have to be careful with adding more and more options :( if you could file a separate bug for this, I think we could see if there is more demand for that and discuss it with others as well.

**Comment by evverx** [comment]
> we have to be careful with adding more and more options :(

Can't argue with that :-) I'll revisit this idea in a week or so and open an issue if it still makes sense to me then :-)

**Pull request closed without merging**
