### PR TITLE
add acl dependency

### PR DESCRIPTION
**Pull request by tstruk**
Update docker file and add access control list tool dependency

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by tstruk** [comment]
@inferno-chromium It failed with https://github.com/google/oss-fuzz/runs/2123033084?check_suite_focus=true#step:8:4276
but I have no idea what the problem might be. Any hint?

**Comment by tstruk** [comment]
afl is failing, but it should be fixed by https://github.com/google/oss-fuzz/pull/5414 already merged

**Comment by tstruk** [comment]
@inferno-chromium if you could merge this one, and I will push the one to disable afl again because something got screwed up. Thanks

**Comment by tstruk** [comment]
> @inferno-chromium if you could merge this one, and I will push the one to disable afl again because something got screwed up. Thanks

New PR is here: https://github.com/google/oss-fuzz/pull/5417

**Pull request merged**
