### PR TITLE
Submit Apache Arrow for inclusion

### PR DESCRIPTION
**Pull request by pitrou**
Arrow is both an efficient in-memory format for tabular data, an IPC format with zero-copy capabilities, and a set of interoperable language implementations (~10 languages currently: C++, Python, Java, Rust, Go...).

This submission is for fuzzing the Arrow C++ IPC reader. If accepted, we plan to add other fuzz targets, for example for reading Parquet files.

### CODE REVIEW

**Comment by pitrou** [comment]
cc @wesm, @emkornfield

**Comment by pitrou** [comment]
The presubmit script [complains weirdly](https://travis-ci.org/google/oss-fuzz/jobs/637461077#L229) about the `primary_contact` address...

**Comment by fsaintjacques** [comment]
It expects a [list](https://github.com/google/oss-fuzz/blob/master/infra/presubmit.py#L148).

**Comment by inferno-chromium** [comment]
Should be fixed in https://github.com/google/oss-fuzz/pull/3234, we added these presubmit rules recently!.

**Comment by emkornfield** [comment]
If there are any issues with justifying integration with oss-fuzz, please let me know (happy to discuss here or internally). Google integrates with Apache Arrow across several products so I think this will be valuable, both for Google and Arrow.

**Pull request merged**
