### PR TITLE
update Shuduo's email address

### PR DESCRIPTION
**Pull request by sangshuduo**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@sangshuduo please sign the CLA and then this should be good to go.

**Comment by sangshuduo** [comment]
@googlebot I signed it!

**Review by DavidKorczynski — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
@sangshuduo it may take a short amount of time before you get access, please let me know if you don't get access within the next 24 hours.

**Comment by sangshuduo** [comment]
> @sangshuduo it may take a short amount of time before you get access, please let me know if you don't get access within the next 24 hours.

Sure. Will let you know if I can or can't. :)

**Comment by sangshuduo** [comment]
@DavidKorczynski  I can see the bug report now. Thanks.

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski I can see the bug report now. Thanks.

Thanks for letting me know!

**Pull request merged**
