### PR TITLE
bitcoin-core: Use dictionaries

### PR DESCRIPTION
**Pull request by dergoegge**

### CODE REVIEW

**Comment by dergoegge** [comment]
cc @MarcoFalke @fanquake

**Comment by fanquake** [comment]
cc @darosior

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Review by darosior — COMMENTED** [review]
Maybe also set the dictionary for other engines than libfuzzer?
https://github.com/google/oss-fuzz/blob/0d4dde8067eb2c45b78225cdde43a82a6921e348/projects/bitcoin-core/project.yaml#L17-L21

The format should be compatible with AFL and Hongfuzz. Don't know about Centipede (or is it FuzzTest?).

**Comment by dergoegge** [comment]
> Maybe also set the dictionary for other engines than libfuzzer?

I think that happens automatically, see: https://github.com/google/oss-fuzz/blob/4f27f997b742bbf14bc4158622b3c1dab9758276/infra/base-images/base-runner/run_fuzzer#LL51C8-L51C8

**Comment by darosior** [comment]
ACK 0d4dde8067eb2c45b78225cdde43a82a6921e348

**Comment by hogo6002** [comment]
@dergoegge please close and reopen this PR to trigger the latest pr helper.

**Review by fanquake — APPROVED** [review]
ACK 0d4dde8067eb2c45b78225cdde43a82a6921e348

**Pull request merged**
