### PR TITLE
infra: update swift to 5.8.1

### PR DESCRIPTION
**Pull request by catenacyber**
As done last year by @thomasvl cf https://github.com/google/oss-fuzz/pull/8501

Hopefully fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=61809

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jvm --sanitizer address coverage undefined  --fuzzing-engines libfuzzer

**Comment by catenacyber** [comment]
@jonathanmetzman I guess you rather want `s/jvm/swift/` in your gcbrun command ;-)

**Comment by jonathanmetzman** [comment]
Whoops. Yeah

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py swift --sanitizer address coverage undefined --fuzzing-engines libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py swift --sanitizer address coverage undefined --fuzzing-engines libfuzzer

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
