### PR TITLE
Fix workdir for serenity project

### PR DESCRIPTION
**Pull request by nico**
With this, can build fuzzers against a local checkout with:

    python3 infra/helper.py build_fuzzers serenity $HOME/src/serenity

Similar to 14452cfb3d87f3f54ced75b9d5dd67b1470f2080

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]
Thank you Sir!

**Comment by inferno-chromium** [comment]
There is a build failure atm,

```
FAILED: /usr/local/bin/clang++  -I../../.. -I../../../Userland -I../../../Userland/Libraries -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -DOSS_FUZZ=ON -std=c++2a -fPIC -g -Wno-deprecated-copy -Wconsumed -Wno-overloaded-virtual -MD -MT CMakeFiles/Lagom.dir/src/serenity/Userland/Libraries/LibJS/AST.cpp.o -MF CMakeFiles/Lagom.dir/src/serenity/Userland/Libraries/LibJS/AST.cpp.o.d -o CMakeFiles/Lagom.dir/src/serenity/Userland/Libraries/LibJS/AST.cpp.o -c /src/serenity/Userland/Libraries/LibJS/AST.cpp
/src/serenity/Userland/Libraries/LibJS/AST.cpp:58:34: error: member access into incomplete type 'const std::type_info'
    return demangle(typeid(*this).name()).substring(4);
                                 ^
/usr/local/bin/../include/c++/v1/cxxabi.h:32:7: note: forward declaration of 'std::type_info'
class type_info; // forward declaration
      ^
1 error generated.

[16/282] Building CXX object CMakeFiles/Lagom.dir/src/serenity/Userland/Libraries/LibJS/Console.cpp.o
[16/282] Building CXX object CMakeFiles/Lagom.dir/src/serenity/Userland/Libraries/LibLine/Editor.cpp.o
ninja: build stopped: subcommand failed.
```

Unrelated to this CL, so merging.

**Comment by nico** [comment]
That build failure is fixed with https://github.com/SerenityOS/serenity/pull/5023

However, I see another build failure that's due to oss-fuzz using an old-ish Ubuntu and the fix for that is a bit gnarly: https://github.com/SerenityOS/serenity/pull/5026 Are there better approaches for this type of thing?

**Comment by inferno-chromium** [comment]
> That build failure is fixed with [SerenityOS/serenity#5023](https://github.com/SerenityOS/serenity/pull/5023)
> 
> However, I see another build failure that's due to oss-fuzz using an old-ish Ubuntu and the fix for that is a bit gnarly: [SerenityOS/serenity#5026](https://github.com/SerenityOS/serenity/pull/5026) Are there better approaches for this type of thing?

Sorry about this, we will update our ubuntu sometime this year. we want to avoid 18.04 and directly jump to 20.04/10 [just waiting for things to be a little more stable before uptake].

**Pull request merged**
