### PR TITLE
[Arrow] Also checkout git submodules

### PR DESCRIPTION
**Pull request by pitrou**
This will allow us to enhance the seed corpuses.

### CODE REVIEW

**Comment by pitrou** [comment]
@emkornfield @fsaintjacques

**Comment by pitrou** [comment]
@fsaintjacques The plan is to add all Parquet test data to the seed corpus, so that the fuzzer explores more possibilities (encoding types, etc.). I don't know if that would help cover all encodings and data types, though (we will have to check the coverage stats at some point).

**Comment by emkornfield** [comment]
LGTM, @pitrou does that happen automatically or is there going to be another PR?

**Comment by pitrou** [comment]
It's gonna be a PR to the Arrow repo.

**Pull request merged**
