### PR TITLE
Adding myself to access freetype2's fuzzing results

### PR DESCRIPTION
**Pull request by HinTak**
Adding my gmail address to the list of people receiving freetype2's fuzzing results.

### CODE REVIEW

**Comment by HinTak** [comment]
I signed it!

**Comment by inferno-chromium** [comment]
Are you a freetype2 developer. Bug access is restricted to developers / maintainers of that project (in this case @lemzwerg has to approve).

**Comment by lemzwerg** [comment]
While not a core developer, he is the maintainer of FontValidator (originally from Microsoft), also providing valuable patches for FreeType.  I thus fully approve that Hin-Tak gets access to FreeType's fuzzing stuff.

**Comment by inferno-chromium** [comment]
Thanks, merged.

**Pull request merged**
