### PR TITLE
Adds golang project pprof

### PR DESCRIPTION
**Pull request by catenacyber**
@aalexand would you be interested in continuous fuzzing for pprof ?
This PR enables it on oss-fuzz with the fuzz target already present in pprof repository
Let me know if you have any questions

### CODE REVIEW

**Comment by aalexand** [comment]
We looked at it in the past and decided it was not very valuable. See [here](https://github.com/google/pprof/pull/481#issuecomment-521160305).

**Comment by catenacyber** [comment]
Thanks @aalexand 
Would you like me to investigate the use of libprotobuf-mutator for pprof ?

**Comment by aalexand** [comment]
@catenacyber is libprotobuf-mutator available for Go now? Previously there was only C++ one.

**Comment by catenacyber** [comment]
> is libprotobuf-mutator available for Go now? Previously there was only C++ one.

I can look into adapting it

**Comment by catenacyber** [comment]
@aalexand here is a try to use libprotobuf-mutator to fuzz pprof

The trick is to :
1 use libprotobufmutator in C++ to generate a valid(?) `perftools::profiles::Profile` using proto/profile.proto
2 encode it in binary with `SerializeToArray`
3 send the binary encoded profile the to Go fuzz target, compiled with a special go-fuzz-build
4 run the go fuzz target, which will decode the binary-encoded Profile

This does not seem to match the custom protocol buffer decoder from pprof :

For 
```

sample {
  label {
    num: 576460752303423488
  }
}
```
getting encoded in Binary as `[18 12 26 10 24 128 128 128 128 128 128 128 128 8]`
I get `parsing profile: unrecognized profile format: (*profile.Profile)(nil)`

What do you think about it ?

**Comment by catenacyber** [comment]
Thank you @aalexand for your input.
So indeed, not all inputs generated by libprotobuf-mutator pass the semantic checks (like `string_table[0] must be ''`) but some do.
What do you think of this target ?

**Comment by catenacyber** [comment]
was merged in #10291 thanks Oliver for cleaning up

**Pull request closed without merging**
