### PR TITLE
fast_float: Initial integration

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
cc @lemire what are your thoughts on integrating fast_float?

**Comment by silvergasp** [comment]
The fast float project is critical to the global IT infrastructure and;
- Has an OSSF criticality score of  0.50653
- Is used by various high-impact projects including;
   - GCC (as of version 12)
   - [WebKit](https://github.com/WebKit/WebKit), the engine behind Safari (Apple's web browser)
   - [LLVM standard libraries](https://github.com/llvm/llvm-project/commit/87c016078ad72c46505461e4ff8bfa04819fe7ba)

**Comment by silvergasp** [comment]
TODO:
- [ ] Point the Dockerfile git clone at the main repo rather than my personal fork

**Comment by lemire** [comment]
@silvergasp Go.

**Pull request merged**
