### PR TITLE
Add libreoffice as a project

### PR DESCRIPTION
**Pull request by caolanm**
We've been fuzzing somewhat adhoc for a while, but lack good infrastructure to manage it properly.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
LGTM, please sign the sla and we will merge this.

**Comment by caolanm** [comment]
I signed it

**Comment by caolanm** [comment]
other me also signed it now

**Comment by inferno-chromium** [comment]
@caolanm - do you guys have a https mirror for dev-www.libreoffice.org ? I see a ton of http url which would be preferable to move to https.

**Comment by caolanm** [comment]
I've asked the admin team about it and they're apparently looking into adding https to that box now

**Comment by inferno-chromium** [comment]
Awesome, thanks @caolanm - much appreciated! libreoffice fuzzing is rocking and thanks for your help integrating and maintaining it!

**Pull request merged**
