### PR TITLE
(fix) fix typos

### PR DESCRIPTION
**Pull request by hi-artem**
see title

### CODE REVIEW

**Comment by hi-artem** [comment]
signed cla

**Comment by jonathanmetzman** [comment]
Thanks. I'm not sure we want this since it will mess up git blame somewhat. Let me think a bit

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

**Comment by hi-artem** [comment]
@jonathanmetzman no worries - if it's messing up with the existing workflows

**Pull request closed without merging**
