### PR TITLE
Revised PNG_CLEANUP to avoid destroying already-destroyed structs

### PR DESCRIPTION
**Pull request by glennrp**

### CODE REVIEW

**Comment by glennrp** [comment]
Recent crashes may be due to over-zealous CLEANUP.  This patch avoids destroying png structs that have already been destroyed.

**Comment by oliverchang** [comment]
Thanks for this change!

Is there any chance that this fuzzer file could be included in the upstream libpng repository?

**Comment by glennrp** [comment]
Sure.  Would that be considered the master, then, so if we update the file
in libpng repo
it gets updated at oss-fuzz automatically?

**Comment by oliverchang** [comment]
Yep! We checkout libpng during build, so we can just point our [build script](https://github.com/google/oss-fuzz/blob/master/projects/libpng/build.sh#L34) to that file instead.
 
Ideally, libpng would also provide build system support (see https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md#build-support), but that can come later :)

**Comment by glennrp** [comment]
The licensing comment at the top of libpng_read_fuzzer.cc is a little
ambigous.  It talks about a BSD-style
license found in the LICENSE file.  But the only LICENSE file I can find is
at the top of oss-fuzz, and that
is Apache-2.0.  That's OK with me, but the comments at the top of
libpng_read_fuzzer.cc aren't exactly
what Apache-2.0 requires.

If we move it to the libpng repo I'd rather have it under the libpng
license anyway.

Glenn

**Comment by glennrp** [comment]
I've pushed libpng_read_fuzzer.cc to the libpng16 distribution, in
contrib/oss-fuzz

Have a look.

Glenn

**Comment by oliverchang** [comment]
Thanks! 

I've pushed https://github.com/google/oss-fuzz/commit/c1d4fe1a7b2bc4b12c94805940baba7974030ad1 so that we are building the upstream fuzzer, so this PR is no longer needed.

**Comment by glennrp** [comment]
You didn't answer my questions about copyright/license, above.  What LICENSE file is the
commentary at the top of libpng_read_fuzzer.cc talking about?  It doesn't seem to be about
Apache-2.0.

**Comment by oliverchang** [comment]
My bad, missed that.

I believe the LICENSE file is referring to the one in chromium, where we copied the file from: https://cs.chromium.org/chromium/src/LICENSE?q=LICENSE&sq=package:chromium&dr 

I'm afraid I don't know how to answer "If it was talking about the libpng license, that would be great.".

**Comment by oliverchang** [comment]
Unfortunately it looks like the new changes have caused a build error:

```
Step #3: /src/libpng/contrib/oss-fuzz/libpng_read_fuzzer.cc:94:18: error: use of undeclared identifier 'read_ptr'
```

Could you please take a look at this?

**Comment by glennrp** [comment]
Fixed in libpng repo (read_ptr should have been png_handler.png_ptr)

Glenn

**Comment by glennrp** [comment]
Updated the README.txt and libpng_read_fuzzer.cc in contrib/oss-fuzz to
point to the Chromium LICENSE.

**Comment by oliverchang** [comment]
Thanks! Confirmed that the build is working again.

**Pull request closed without merging**
