### PR TITLE
Centipede skips seed corpus in build test

### PR DESCRIPTION
**Pull request by Alan32Liu**
In #9427, some projects [failed on `bad_build_check`](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/31a7e835-32aa-49c8-81f1-f8d2eab9e3c1;step=20?project=oss-fuzz) (e.g., [`matio`](https://github.com/google/oss-fuzz/tree/master/projects/matio) has seed corpus) without explicit reason.
This is because `Centipede` [does not skip seed corpus in `run_fuzzer`](https://github.com/google/oss-fuzz/blob/a5ee351ed1cfb97b73eab96787c0a86434cfd99e/infra/base-images/base-runner/run_fuzzer#L89) like [other fuzzers](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/bad_build_check#L147).

This PR sets the environment variable so that `Centipede` also skips seeds and pass the `bad_build_check`.

### CODE REVIEW

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer none --fuzzing-engine centipede

**Review by oliverchang — APPROVED** [review]
LGTM, but do we know exactly why Centipede is broken with this? libFuzzer doesn't have this enabled right?

**Comment by Alan32Liu** [comment]
> LGTM, but do we know exactly why Centipede is broken with this?

I am not sure if it is broken because of `Centipede`: It is more likely caused by [the `unzip` command in `run_fuzzer`](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/run_fuzzer#L91).
I inserted some `echo`s before and after that line, and found nothing was printed after it.
I will spend more time understanding why `unzip` is broken here, but I will paste the output below in a sec.

> libFuzzer doesn't have this enabled right?

I reckon it does.
`libFuzzer` enables this [when it is called with `run_fuzzer`](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/bad_build_check#L147).
It did not enable it in [function `check_engine`](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/bad_build_check#L73) as `Centipede` and [other fuzzers](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/bad_build_check#L93), because it did not invoke `run_fuzzer` there and this is only useful for `run_fuzzer`.

**Comment by oliverchang** [comment]
Good point, 

> > LGTM, but do we know exactly why Centipede is broken with this?
> 
> I am not sure if it is broken because of `Centipede`: It is more likely caused by [the `unzip` command in `run_fuzzer`](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/run_fuzzer#L91). I inserted some `echo`s before and after that line, and found nothing was printed after it. I will spend more time understanding why `unzip` is broken here, but I will paste the output below in a sec.
> 
> > libFuzzer doesn't have this enabled right?
> 
> I reckon it does. `libFuzzer` enables this [when it is called with `run_fuzzer`](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/bad_build_check#L147). It did not enable it in [function `check_engine`](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/bad_build_check#L73) as `Centipede` and [other fuzzers](https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/bad_build_check#L93), because it did not invoke `run_fuzzer` there and this is only useful for `run_fuzzer`.

Good point. It's likely just broken in general then if it's never used anywhere. Let's add a TODO to investigate more and just merge this.

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py all --sanitizer none --fuzzing-engine centipede

**Comment by Alan32Liu** [comment]
The output is pasted below, it seems this is due to paths being skipped?
```
INFO:root:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e FUZZING_ENGINE=centipede -e SANITIZER=none -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c++ -e HELPER=True -v /usr/local/google/home/donggeliu/Code/oss-fuzz/build/out/matio:/out -t gcr.io/oss-fuzz-base/base-runner test_all.py.
INFO: performing bad build checks for /tmp/not-out/tmpwc321r2p/matio_fuzzer
Retrying failed fuzz targets sequentially 1
INFO: performing bad build checks for /tmp/not-out/tmpwc321r2p/matio_fuzzer
Broken fuzz targets 1
('/tmp/not-out/tmpwc321r2p/matio_fuzzer', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmpwc321r2p/matio_fuzzer'], returncode=1, stdout=b'BAD BUILD: fuzzing /tmp/not-out/tmpwc321r2p/matio_fuzzer with centipede failed.\nUsing seed corpus: matio_fuzzer_seed_corpus.zip\nCorpus directory /tmp/matio_fuzzer_corpus exists.\nCorpus file matio_fuzzer_seed_corpus.zip exists.\nArchive:  matio_fuzzer_seed_corpus.zip\nwarning:  skipped "../" path component(s) in ../share/\n   creating: /tmp/matio_fuzzer_corpus/share/\nwarning:  skipped "../" path component(s) in ../share/test_le_hdf5.mat\n  inflating: /tmp/matio_fuzzer_corpus/share/test_le_hdf5.mat  \nwarning:  skipped "../" path component(s) in ../share/test_file_hdf5.mat\n  inflating: /tmp/matio_fuzzer_corpus/share/test_file_hdf5.mat  \nwarning:  skipped "../" path component(s) in ../share/test_be.mat\n  inflating: /tmp/matio_fuzzer_corpus/share/test_be.mat  \nwarning:  skipped "../" path component(s) in ../share/test_le_v6.mat\n  inflating: /tmp/matio_fuzzer_corpus/share/test_le_v6.mat  \nwarning:  skipped "../" path component(s) in ../share/test.mat\n  inflating: /tmp/matio_fuzzer_corpus/share/test.mat  \nwarning:  skipped "../" path component(s) in ../share/test_file.mat\n  inflating: /tmp/matio_fuzzer_corpus/share/test_file.mat  \nwarning:  skipped "../" path component(s) in ../share/test_be_v6.mat\n  inflating: /tmp/matio_fuzzer_corpus/share/test_be_v6.mat  \nwarning:  skipped "../" path component(s) in ../share/test_le.mat\n  inflating: /tmp/matio_fuzzer_corpus/share/test_le.mat  \nwarning:  skipped "../" path component(s) in ../share/test_file_v6.mat\n  inflating: /tmp/matio_fuzzer_corpus/share/test_file_v6.mat  \n', stderr=b''))
BAD BUILD: fuzzing /tmp/not-out/tmpwc321r2p/matio_fuzzer with centipede failed.
Using seed corpus: matio_fuzzer_seed_corpus.zip
Corpus directory /tmp/matio_fuzzer_corpus exists.
Corpus file matio_fuzzer_seed_corpus.zip exists.
Archive:  matio_fuzzer_seed_corpus.zip
warning:  skipped "../" path component(s) in ../share/
   creating: /tmp/matio_fuzzer_corpus/share/
warning:  skipped "../" path component(s) in ../share/test_le_hdf5.mat
  inflating: /tmp/matio_fuzzer_corpus/share/test_le_hdf5.mat
warning:  skipped "../" path component(s) in ../share/test_file_hdf5.mat
  inflating: /tmp/matio_fuzzer_corpus/share/test_file_hdf5.mat
warning:  skipped "../" path component(s) in ../share/test_be.mat
  inflating: /tmp/matio_fuzzer_corpus/share/test_be.mat
warning:  skipped "../" path component(s) in ../share/test_le_v6.mat
  inflating: /tmp/matio_fuzzer_corpus/share/test_le_v6.mat
warning:  skipped "../" path component(s) in ../share/test.mat
  inflating: /tmp/matio_fuzzer_corpus/share/test.mat
warning:  skipped "../" path component(s) in ../share/test_file.mat
  inflating: /tmp/matio_fuzzer_corpus/share/test_file.mat
warning:  skipped "../" path component(s) in ../share/test_be_v6.mat
  inflating: /tmp/matio_fuzzer_corpus/share/test_be_v6.mat
warning:  skipped "../" path component(s) in ../share/test_le.mat
  inflating: /tmp/matio_fuzzer_corpus/share/test_le.mat
warning:  skipped "../" path component(s) in ../share/test_file_v6.mat
  inflating: /tmp/matio_fuzzer_corpus/share/test_file_v6.mat

ERROR: 100.0% of fuzz targets seem to be broken. See the list above for a detailed information.
ERROR:root:Check build failed.
```

**Comment by jonathanmetzman** [comment]
> LGTM, but do we know exactly why Centipede is broken with this? libFuzzer doesn't have this enabled right?

Frankly libfuzzer should be using the seed corpus in bad build check but I think we punted doing this because it caused failures and never got around to turning this on.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
I want to do some testing. I'm gonna merge this.

**Pull request merged**
