### PR TITLE
[infra] Don't build cmake or include it in the image

### PR DESCRIPTION
**Pull request by jonathanmetzman**
We shouldn't have people depending on it.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Maybe do this instead of https://github.com/google/oss-fuzz/pull/8681

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Review by Alan32Liu — APPROVED** [review]

**Review by oliverchang — COMMENTED** [review]
is this still needed?

**Comment by jonathanmetzman** [comment]
Probably not, but I may ressurect this if I measure things and don't like the size I'm seeing from cmake

**Comment by oliverchang** [comment]
Ok closing for now

**Pull request closed without merging**
