### PR TITLE
fix: Fix config files for opendal

### PR DESCRIPTION
**Pull request by Xuanwo**

### CODE REVIEW

**Comment by Xuanwo** [comment]
> Xuanwo is a new contributor to [projects/opendal](https://github.com//google/oss-fuzz/tree/master/projects/opendal). The PR must be approved by known contributors before it can be merged. The past contributors are: dqhl76

@dqhl76, I couldn't sign the CLA for Google. Could you help me incorporate those changes?

**Comment by Xuanwo** [comment]
@dqhl76, I couldn't sign the CLA for Google. Could you help me incorporate those changes?

**Comment by dqhl76** [comment]
> @dqhl76, I couldn't sign the CLA for Google. Could you help me incorporate those changes?

Hi, of course. How can I do that?

**Comment by Xuanwo** [comment]
> Hi, of course. How can I do that?

Submit a PR with changes in this PR is good enough.

**Comment by Xuanwo** [comment]
Close for already having https://github.com/google/oss-fuzz/pull/11452

**Pull request closed without merging**
