### PR TITLE
Update Jazzer to the latest version (Apache 2.0)

### LINKED ISSUE #11652: Jazzer open source project has been discontinued
Jazzer and Jazzer.js which are used by a lot of Java and JavaScript projects here have unfortunately been discountinued as open source projects, see READMEs:
- https://github.com/CodeIntelligenceTesting/jazzer
- https://github.com/CodeIntelligenceTesting/jazzer.js

Are there any plans yet how to handle this? Or will oss-fuzz for now continue using Jazzer until things break with the current versions?

### PR DESCRIPTION
**Pull request by oliverchang**
Fixes #11652

### CODE REVIEW

**Comment by kyakdan** [comment]
@oliverchang Sorry, but I have overseen your last comment on my original PR. I rebased and fixed the error that caused the project tests to fail here in the original branch: https://github.com/CodeIntelligenceTesting/oss-fuzz/tree/update-jazzer-apache2

Feel free to integrate these changes here or reopen the original PR.

**Comment by DavidKorczynski** [comment]
/gcbrun trial_build.py jvm --sanitizer address --fuzzing-engine libfuzzer

**Comment by DavidKorczynski** [comment]
Rebasing following https://github.com/google/oss-fuzz/pull/12876

**Comment by DavidKorczynski** [comment]
2 projects fail both due to timeout, this is good to go.

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
