### PR TITLE
Enable ClickHouse

### PR DESCRIPTION
**Pull request by nikitamikhaylov**

### CODE REVIEW

**Comment by nikitamikhaylov** [comment]
@jonathanmetzman Everything is fixed. Can you please take a look and merge? Build under UBSan is disabled, but will be added soon in another PR.

**Comment by nikitamikhaylov** [comment]
Rebased on top of master. I saw an Ubuntu upgrade related commits in master.

**Comment by nikitamikhaylov** [comment]
@AdamKorcz Any chance to get a review?

**Review by DavidKorczynski — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Thanks @nikitamikhaylov

**Comment by nikitamikhaylov** [comment]
Thank you!

**Comment by nikitamikhaylov** [comment]
@DavidKorczynski Excuse me, but how to get an access to a web interface? email: jakalletti@gmail.com

**Comment by DavidKorczynski** [comment]
You get access through https://oss-fuzz.com - what do you see when you log on there?

**Comment by nikitamikhaylov** [comment]
I tried to log in just after merge. Now it is working, sorry.

**Comment by DavidKorczynski** [comment]
Okay - could we give it a day or so? The only other possibility is that your email is not the primary one on your Google account but I don't think this is the case with gmails.

**Comment by nikitamikhaylov** [comment]
> Okay - could we give it a day or so? The only other possibility is that your email is not the primary one on your Google account but I don't think this is the case with gmails.

It is not a primary account, yes. I just interest if I am doing something wrong.

**Comment by DavidKorczynski** [comment]
@nikitamikhaylov any updates here? Did you get access now?

**Pull request merged**
