### PR TITLE
base-runner: adjust python cov helper to py 3.9

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Fixes: https://github.com/google/oss-fuzz/issues/10350

### CODE REVIEW

**Comment by Alan32Liu** [comment]
The trial build failed due to timeout, which I presume is because of too many projects (482).

May be it makes sense to run them in groups? I split them into 5 groups (~100 each) and can start one with the first 100:
```
Group 1:
abseil-py adal aiohttp airflow aniso8601 ansible argcomplete arrow-py asn1crypto astroid asttokens autoflake autopep8 azure-sdk-for-python babel black bleach botocore bottleneck bs4 bz2file cachetools cffi chardet charset_normalizer click configparser connexion coveragepy croniter cssselect dask decorator defusedxml digest dill distlib dnspython docutils ecdsa-python et-xmlfile face filelock filesystem_spec flask-jwt-extended flask-restx flask-wtf fonttools ftfy g-api-auth-httplib2 g-api-auth-library-python g-api-pubsub g-api-py-api-common-protos g-api-py-oauthlib g-api-python-bigquery-storage g-api-python-client g-api-python-cloud-core g-api-python-firestore g-api-python-tasks g-api-resource-manager g-api-resumable-media-python g-api-secret-manager g-apis-py-api-core g-cloud-logging-py g-py-bigquery g-py-crc32c gast gc-iam gcloud-error-py gcp-python-cloud-storage genshi gitdb github_scarecrow glom gprof2dot grpc-py gunicorn h11 h5py hiredis-py html2text html5lib-python httpcore httplib2 httpretty httpx idna ijson imageio importlib_metadata iniconfig ipaddress ipykernel ipython isodate itsdangerous jedi jinja2 jmespathpy joblib
Group 2:
jsmin jsonpickle jsonschema jupyter-nbconvert jupyter_server kafka keras kiwisolver lark-parser libcst looker-sdk lxml mako markdown-it-py markupsafe mccabe mdit-py-plugins mdurl more-itertools mrab-regex msal msgpack-python multidict mutagen nbclassic nbformat netaddr-py networkx nfstream ntlm-auth ntlm2 numexpr numpy oauth2 oauthlib olefile openapi-schema-validator opencensus-python openpyxl opt_einsum oracle-py-cx orjson oscrypto packaging parse parsimonious parso pasta pathlib2 pem pendulum pillow pip ply presidio proto-plus-python protobuf-python psqlparse psutil psycopg2 py-serde pyasn1 pyasn1-modules pycparser pycrypto pydateutil pygments pyjson5 pyjwt pymysql pynacl pyodbc pyparsing pyrsistent pytest-py python-ecdsa python-email-validator python-fastjsonschema python-future python-graphviz python-hyperlink python-jose python-markdown python-markdownify python-nameparser python-nvd3 python-pathspec python-phonenumbers python-prompt-toolkit python-rison python-rsa python-tabulate python3-openid pytz pyxdg pyyaml pyzmq redis-py retry rfc3967
Group 3:
rich sacremoses scapy scikit-learn scipy setuptools simplejson six smart_open soupsieve sqlalchemy sqlalchemy-utils sqlalchemy_jsonfield sqlparse stack_data tensorflow-addons tinycss2 toml tomli tomlkit toolbelt toolz tqdm typing_extensions ujson underscore uritemplate urlextract urllib3 validators w3lib websocket-client websockets wheel wtforms xlrd xmltodict yarl zipp abseil-py adal aiohttp airflow aniso8601 argcomplete arrow-py asn1crypto asteval astroid asttokens autoflake autopep8 azure-sdk-for-python babel black bleach botocore bottleneck bs4 bz2file cachetools cffi chardet charset_normalizer click configparser connexion coveragepy croniter cssselect dask decorator defusedxml digest dill distlib dnspython docutils ecdsa-python et-xmlfile face filelock filesystem_spec flask flask-jwt-extended flask-restx flask-wtf fonttools ftfy g-api-auth-httplib2 g-api-auth-library-python g-api-pubsub g-api-py-api-common-protos g-api-py-oauthlib g-api-python-bigquery-storage g-api-python-client g-api-python-cloud-core g-api-python-firestore g-api-python-tasks g-api-resource-manager
Group 4:
g-api-resumable-media-python g-api-secret-manager g-apis-py-api-core g-cloud-logging-py g-py-bigquery g-py-crc32c gast gc-iam gcloud-error-py gcp-python-cloud-storage genshi gitdb github_scarecrow gitpython glom gprof2dot grpc-py gunicorn h11 h5py hiredis-py html2text html5lib-python httpcore httplib2 httpretty httpx idna ijson importlib_metadata iniconfig ipaddress ipykernel ipython isodate itsdangerous jedi jinja2 jmespathpy joblib jsmin jsonpickle jsonschema jupyter-nbconvert jupyter_server kafka kiwisolver lark-parser libcst looker-sdk lxml mako markdown-it-py markupsafe matplotlib mccabe mdit-py-plugins mdurl more-itertools mrab-regex msal msgpack-python multidict mutagen nbclassic nbformat netaddr-py networkx nfstream ntlm-auth ntlm2 numexpr numpy oauth2 oauthlib olefile openapi-schema-validator opencensus-python openpyxl opt_einsum oracle-py-cx orjson oscrypto packaging parse parsimonious parso pasta pathlib2 pdoc pem pendulum pillow pip ply presidio proto-plus-python protobuf-python psqlparse psutil
Group 5:
psycopg2 py-serde pyasn1 pyasn1-modules pycparser pycrypto pydateutil pygments pyjson5 pyjwt pymysql pynacl pyodbc pyparsing pyrsistent pytest-py python-ecdsa python-email-validator python-fastjsonschema python-future python-graphviz python-hyperlink python-jose python-lz4 python-markdown python-markdownify python-nameparser python-nvd3 python-pathspec python-phonenumbers python-prompt-toolkit python-rison python-rsa python-tabulate python3-openid pytz pyxdg pyyaml pyzmq redis-py requests retry rfc3967 rich sacremoses scapy scikit-learn scipy setuptools simplejson six smart_open soupsieve sqlalchemy sqlalchemy_jsonfield sqlparse stack_data tensorflow-addons tensorflow-py tinycss2 toml tomli tomlkit toolbelt toolz tqdm typing_extensions ujson underscore uritemplate urlextract urllib3 validators w3lib websocket-client websockets wheel wtforms xlrd xmltodict yarl zipp
```

**Comment by Alan32Liu** [comment]
/gcbrun trial_build.py abseil-py adal aiohttp airflow aniso8601 ansible argcomplete arrow-py asn1crypto astroid asttokens autoflake autopep8 azure-sdk-for-python babel black bleach botocore bottleneck bs4 bz2file cachetools cffi chardet charset_normalizer click configparser connexion coveragepy croniter cssselect dask decorator defusedxml digest dill distlib dnspython docutils ecdsa-python et-xmlfile face filelock filesystem_spec flask-jwt-extended flask-restx flask-wtf fonttools ftfy g-api-auth-httplib2 g-api-auth-library-python g-api-pubsub g-api-py-api-common-protos g-api-py-oauthlib g-api-python-bigquery-storage g-api-python-client g-api-python-cloud-core g-api-python-firestore g-api-python-tasks g-api-resource-manager g-api-resumable-media-python g-api-secret-manager g-apis-py-api-core g-cloud-logging-py g-py-bigquery g-py-crc32c gast gc-iam gcloud-error-py gcp-python-cloud-storage genshi gitdb github_scarecrow glom gprof2dot grpc-py gunicorn h11 h5py hiredis-py html2text html5lib-python httpcore httplib2 httpretty httpx idna ijson imageio importlib_metadata iniconfig ipaddress ipykernel ipython isodate itsdangerous jedi jinja2 jmespathpy joblib --sanitizer coverage address

**Comment by jonathanmetzman** [comment]
> The trial build failed due to timeout, which I presume is because of too many projects (482).
> 
> May be it makes sense to run them in groups? I split them into 5 groups (~100 each) and can start with the first 100:
> 
> ```
> Group 1:
> abseil-py adal aiohttp airflow aniso8601 ansible argcomplete arrow-py asn1crypto astroid asttokens autoflake autopep8 azure-sdk-for-python babel black bleach botocore bottleneck bs4 bz2file cachetools cffi chardet charset_normalizer click configparser connexion coveragepy croniter cssselect dask decorator defusedxml digest dill distlib dnspython docutils ecdsa-python et-xmlfile face filelock filesystem_spec flask-jwt-extended flask-restx flask-wtf fonttools ftfy g-api-auth-httplib2 g-api-auth-library-python g-api-pubsub g-api-py-api-common-protos g-api-py-oauthlib g-api-python-bigquery-storage g-api-python-client g-api-python-cloud-core g-api-python-firestore g-api-python-tasks g-api-resource-manager g-api-resumable-media-python g-api-secret-manager g-apis-py-api-core g-cloud-logging-py g-py-bigquery g-py-crc32c gast gc-iam gcloud-error-py gcp-python-cloud-storage genshi gitdb github_scarecrow glom gprof2dot grpc-py gunicorn h11 h5py hiredis-py html2text html5lib-python httpcore httplib2 httpretty httpx idna ijson imageio importlib_metadata iniconfig ipaddress ipykernel ipython isodate itsdangerous jedi jinja2 jmespathpy joblib
> Group 2:
> jsmin jsonpickle jsonschema jupyter-nbconvert jupyter_server kafka keras kiwisolver lark-parser libcst looker-sdk lxml mako markdown-it-py markupsafe mccabe mdit-py-plugins mdurl more-itertools mrab-regex msal msgpack-python multidict mutagen nbclassic nbformat netaddr-py networkx nfstream ntlm-auth ntlm2 numexpr numpy oauth2 oauthlib olefile openapi-schema-validator opencensus-python openpyxl opt_einsum oracle-py-cx orjson oscrypto packaging parse parsimonious parso pasta pathlib2 pem pendulum pillow pip ply presidio proto-plus-python protobuf-python psqlparse psutil psycopg2 py-serde pyasn1 pyasn1-modules pycparser pycrypto pydateutil pygments pyjson5 pyjwt pymysql pynacl pyodbc pyparsing pyrsistent pytest-py python-ecdsa python-email-validator python-fastjsonschema python-future python-graphviz python-hyperlink python-jose python-markdown python-markdownify python-nameparser python-nvd3 python-pathspec python-phonenumbers python-prompt-toolkit python-rison python-rsa python-tabulate python3-openid pytz pyxdg pyyaml pyzmq redis-py retry rfc3967
> Group 3:
> rich sacremoses scapy scikit-learn scipy setuptools simplejson six smart_open soupsieve sqlalchemy sqlalchemy-utils sqlalchemy_jsonfield sqlparse stack_data tensorflow-addons tinycss2 toml tomli tomlkit toolbelt toolz tqdm typing_extensions ujson underscore uritemplate urlextract urllib3 validators w3lib websocket-client websockets wheel wtforms xlrd xmltodict yarl zipp abseil-py adal aiohttp airflow aniso8601 argcomplete arrow-py asn1crypto asteval astroid asttokens autoflake autopep8 azure-sdk-for-python babel black bleach botocore bottleneck bs4 bz2file cachetools cffi chardet charset_normalizer click configparser connexion coveragepy croniter cssselect dask decorator defusedxml digest dill distlib dnspython docutils ecdsa-python et-xmlfile face filelock filesystem_spec flask flask-jwt-extended flask-restx flask-wtf fonttools ftfy g-api-auth-httplib2 g-api-auth-library-python g-api-pubsub g-api-py-api-common-protos g-api-py-oauthlib g-api-python-bigquery-storage g-api-python-client g-api-python-cloud-core g-api-python-firestore g-api-python-tasks g-api-resource-manager
> Group 4:
> g-api-resumable-media-python g-api-secret-manager g-apis-py-api-core g-cloud-logging-py g-py-bigquery g-py-crc32c gast gc-iam gcloud-error-py gcp-python-cloud-storage genshi gitdb github_scarecrow gitpython glom gprof2dot grpc-py gunicorn h11 h5py hiredis-py html2text html5lib-python httpcore httplib2 httpretty httpx idna ijson importlib_metadata iniconfig ipaddress ipykernel ipython isodate itsdangerous jedi jinja2 jmespathpy joblib jsmin jsonpickle jsonschema jupyter-nbconvert jupyter_server kafka kiwisolver lark-parser libcst looker-sdk lxml mako markdown-it-py markupsafe matplotlib mccabe mdit-py-plugins mdurl more-itertools mrab-regex msal msgpack-python multidict mutagen nbclassic nbformat netaddr-py networkx nfstream ntlm-auth ntlm2 numexpr numpy oauth2 oauthlib olefile openapi-schema-validator opencensus-python openpyxl opt_einsum oracle-py-cx orjson oscrypto packaging parse parsimonious parso pasta pathlib2 pdoc pem pendulum pillow pip ply presidio proto-plus-python protobuf-python psqlparse psutil
> Group 5:
> psycopg2 py-serde pyasn1 pyasn1-modules pycparser pycrypto pydateutil pygments pyjson5 pyjwt pymysql pynacl pyodbc pyparsing pyrsistent pytest-py python-ecdsa python-email-validator python-fastjsonschema python-future python-graphviz python-hyperlink python-jose python-lz4 python-markdown python-markdownify python-nameparser python-nvd3 python-pathspec python-phonenumbers python-prompt-toolkit python-rison python-rsa python-tabulate python3-openid pytz pyxdg pyyaml pyzmq redis-py requests retry rfc3967 rich sacremoses scapy scikit-learn scipy setuptools simplejson six smart_open soupsieve sqlalchemy sqlalchemy_jsonfield sqlparse stack_data tensorflow-addons tensorflow-py tinycss2 toml tomli tomlkit toolbelt toolz tqdm typing_extensions ujson underscore uritemplate urlextract urllib3 validators w3lib websocket-client websockets wheel wtforms xlrd xmltodict yarl zipp
> ```

Can you look into dealing with rate limiting while avoiding this problem?

**Comment by jonathanmetzman** [comment]
The only thing this breaks is dask: 
```
Already have image (with digest): gcr.io/cloud-builders/docker
---------------------------------------------------------------
Compiling libFuzzer to /usr/lib/libFuzzingEngine.a...  done.
---------------------------------------------------------------
CC=clang
CXX=clang++
CFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -fno-sanitize=function,leak,vptr,
CXXFLAGS=-O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -fno-sanitize=function,leak,vptr
RUSTFLAGS=--cfg fuzzing -Zsanitizer=address -Cdebuginfo=1 -Cforce-frame-pointers
---------------------------------------------------------------
+ pip3 install .
Processing /src/dask
  Installing build dependencies ... - \ | / - done
  Getting requirements to build wheel ... - done
  Installing backend dependencies ... - \ done
    Preparing wheel metadata ... - done
ERROR: Package 'dask-2023.5.1-2.g8803b3ae5' requires a different Python: 3.8.3 not in '>=3.9'
WARNING: You are using pip version 19.2.3, however version 23.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
********************************************************************************
Failed to build.
To reproduce, run:
python infra/helper.py build_image dask
python infra/helper.py build_fuzzers --sanitizer address --engine libfuzzer --architecture x86_64 dask
```
I'm fine with breaking one project if you want.

**Comment by DavidKorczynski** [comment]
That's good for me, I'll fix up dask right after this is merged

**Comment by Alan32Liu** [comment]
Project `dask` seems to be the only fuzzer failing for [the same reason](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/06d3ba59-27bb-480c-baf1-2a45bf7907c9;step=19?project=oss-fuzz):

Some projects's [`coverage` and `introspector` build failed](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1?project=oss-fuzz&pageState=(%22builds%22:(%22f%22:%22%255B%257B_22k_22_3A_22Tags_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22trial-build_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22tags_22%257D_2C%257B_22k_22_3A_22Tags_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22branch-align-pycov-to-39_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22tags_22%257D_2C%257B_22k_22_3A_22Status_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22Failed_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22status_22%257D%255D%22))). Do we mind them?

For example:
1. `lark-parser`
```
Opening: /src/fuzz_parse.py
INFO:pycg.pycg:Done analysis: /src/fuzz_parse.py
INFO:pycg.processing.postprocessor:We found the call to atheris
INFO:pycg.processing.postprocessor:[<ast.Attribute object at 0x7f5da300d4f0>, <ast.Name object at 0x7f5da300d370>]
INFO:pycg.processing.postprocessor:The second argument: <ast.Name object at 0x7f5da300d370>
INFO:pycg.processing.postprocessor:Name: TestOneInput
Opening: /src/pyintro-pack-deps/lark/__init__.py
Opening: /src/pyintro-pack-deps/lark/exceptions.py
Opening: /src/pyintro-pack-deps/lark/utils.py
Opening: /src/pyintro-pack-deps/lark/lexer.py
Opening: /src/pyintro-pack-deps/lark/common.py
Opening: /src/pyintro-pack-deps/lark/lark.py
Opening: /src/pyintro-pack-deps/lark/parsers/lalr_interactive_parser.py
Opening: /src/pyintro-pack-deps/lark/parsers/__init__.py
Opening: /src/pyintro-pack-deps/lark/load_grammar.py
/usr/local/bin/compile_python_fuzzer: line 55:   768 Killed                  python /fuzz-introspector/frontends/python/main.py $ARGS
********************************************************************************
Failed to build.
To reproduce, run:
python infra/helper.py build_image lark-parser
python infra/helper.py build_fuzzers --sanitizer introspector --engine libfuzzer --architecture x86_64 lark-parser
********************************************************************************
```

2. `mrab-regex`
```
Already have image (with digest): gcr.io/cloud-builders/gsutil
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/coverage_html.js#1685587836188568...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/d_40982218527bfe26_fuzz_match_py.html#1685587836366149...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/d_40982218527bfe26_fuzz_search_py.html#1685587836220551...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/d_98cea5242c65255c___init___py.html#1685587836321303...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/d_98cea5242c65255c__regex_core_py.html#1685587836359745...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/favicon_32.png#1685587836352798...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/d_98cea5242c65255c_regex_py.html#1685587836220378...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/keybd_closed.png#1685587836156476...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/keybd_open.png#1685587836164122...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/index.html#1685587836348816...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/style.css#1685587836321397...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/status.json#1685587836337324...
Removing gs://oss-fuzz-coverage-testing/mrab-regex/reports/20230601/linux/summary.json#1685587836295115...
/ [1/13 objects]   7% Done                                                      
Operation completed over 13 objects.                                             
Already have image (with digest): gcr.io/cloud-builders/gsutil
CommandException: No URLs matched. Do the files you're operating on exist?
```

3. `numexpr`
```
Opening: /src/fuzz_numexpr.py
Traceback (most recent call last):
  File "/fuzz-introspector/frontends/python/main.py", line 393, in <module>
    sys.exit(main())
  File "/fuzz-introspector/frontends/python/main.py", line 381, in main
    exit_code = run_fuzz_pass(
  File "/fuzz-introspector/frontends/python/main.py", line 116, in run_fuzz_pass
    cg.analyze()
  File "/fuzz-introspector/frontends/python/PyCG/pycg/pycg.py", line 192, in analyze
    self.do_pass(PostProcessor, False,
  File "/fuzz-introspector/frontends/python/PyCG/pycg/pycg.py", line 157, in do_pass
    processor = cls(input_file, input_mod,
  File "/fuzz-introspector/frontends/python/PyCG/pycg/processing/postprocessor.py", line 43, in __init__
    self.closured = self.def_manager.transitive_closure()
  File "/fuzz-introspector/frontends/python/PyCG/pycg/machinery/definitions.py", line 112, in transitive_closure
    dfs(current_def)
  File "/fuzz-introspector/frontends/python/PyCG/pycg/machinery/definitions.py", line 102, in dfs
    items = dfs(self.defs[name])
  File "/fuzz-introspector/frontends/python/PyCG/pycg/machinery/definitions.py", line 102, in dfs
    items = dfs(self.defs[name])
  File "/fuzz-introspector/frontends/python/PyCG/pycg/machinery/definitions.py", line 102, in dfs
    items = dfs(self.defs[name])
  [Previous line repeated 988 more times]
  File "/fuzz-introspector/frontends/python/PyCG/pycg/machinery/definitions.py", line 88, in dfs
    name_pointer = defi.get_name_pointer()
RecursionError: maximum recursion depth exceeded
********************************************************************************
Failed to build.
To reproduce, run:
python infra/helper.py build_image numexpr
python infra/helper.py build_fuzzers --sanitizer introspector --engine libfuzzer --architecture x86_64 numexpr
********************************************************************************
```

**Comment by DavidKorczynski** [comment]
> Some projects's [`coverage` and `introspector` build failed](https://pantheon.corp.google.com/cloud-build/builds;region=us-central1?project=oss-fuzz&pageState=(%22builds%22:(%22f%22:%22%255B%257B_22k_22_3A_22Tags_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22trial-build_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22tags_22%257D_2C%257B_22k_22_3A_22Tags_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22branch-align-pycov-to-39_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22tags_22%257D_2C%257B_22k_22_3A_22Status_22_2C_22t_22_3A10_2C_22v_22_3A_22_5C_22Failed_5C_22_22_2C_22s_22_3Atrue_2C_22i_22_3A_22status_22%257D%255D%22))). Do we mind them?

I'm the contact on those projects and can fix the issues afterwards, so am happy to merge despite them failing.

**Comment by jonathanmetzman** [comment]
I'm fine. Let's merge this on Monday

**Pull request merged**
