### PR TITLE
Orbit: Fix broken build

### PR DESCRIPTION
**Pull request by beckerhe**
This is adjusting the build script and Dockerfile for the Orbit project to work with upstream changes of the build scripts.

It also removes some hacks that are not needed anymore.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
Looks like theres still an issue with coverage builds.

**Comment by beckerhe** [comment]
> Looks like theres still an issue with coverage builds.

The log file lists the following:

```
Killed
make[2]: *** [source/lib/Target/AMDGPU/Utils/CMakeFiles/LLVMAMDGPUUtils.dir/build.make:90: source/lib/Target/AMDGPU/Utils/CMakeFiles/LLVMAMDGPUUtils.dir/AMDGPUBaseInfo.cpp.o] Error 137
make[1]: *** [CMakeFiles/Makefile2:11297: source/lib/Target/AMDGPU/Utils/CMakeFiles/LLVMAMDGPUUtils.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

Could this job be hitting some memory limit or some timeout? Have you seen this before?

(I'm gonna retrigger the job - to see if it is reproducible.)

**Comment by jonathanmetzman** [comment]
OK. I think this is ready to merge. Want me to do it?

**Comment by beckerhe** [comment]
> OK. I think this is ready to merge. Want me to do it?

Cool. Thank you. I would be great if you could take care of it since you can probably better time branch updates with submits.

**Pull request merged**
