### PR TITLE
Allow specifying experimental sanitizers.

### PR DESCRIPTION
**Pull request by oliverchang**
See #378.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
LGTM

**Comment by mikea** [comment]
Not sure why would you want to do this. Why not simply comments in project.yaml?

```yaml
sanitizers:
  - undefined # experimental
```

**Comment by oliverchang** [comment]
it's much easier to parse. I don't think yaml parser preserves comments?

**Comment by oliverchang** [comment]
please take another look. Changed to support:

```yaml
sanitizers:
  undefined:
    experimental: true
```

and 

```yaml
sanitizers:
  - undefined:
      experimental: true
```

In addition to what we already support (list of sanitizer strings)

**Comment by oliverchang** [comment]
Thanks. Will merge this next week, since Mike is testing builder changes.

**Pull request merged**
