### PR TITLE
infra: bump introspector and update python compile script

### PR DESCRIPTION
**Pull request by DavidKorczynski**
This is a follow-up to https://github.com/google/oss-fuzz/pull/8952

This bump is needed to have the Python projects work properly. Scan should be done for all projects now, so have switched it on by default in fuzz introspector.

Bump also contains
- Fix for util-linux where per-target coverage report links were broken.
- Reduced logging.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib aspell yara glom pyyaml idna --sanitizer introspector --fuzzing-engine libfuzzer

**Review by Navidem — APPROVED** [review]
LGTM

**Comment by DavidKorczynski** [comment]
The i386 build failure is unrelated to this PR:
```
jdk-15.0.2/lib/server/libjvm.so
jdk-15.0.2/lib/src.zip
jdk-15.0.2/lib/tzdb.dat
jdk-15.0.2/release
+ rm -f openjdk-15.0.2_linux-x64_bin.tar.gz
+ rm -rf /usr/lib/jvm/java-15-openjdk-amd64/jmods /usr/lib/jvm/java-15-openjdk-amd64/lib/src.zip
+ cd /src/
+ git clone https://github.com/CodeIntelligenceTesting/jazzer
Cloning into 'jazzer'...
+ cd jazzer
+ git checkout c9f9347b7a72a4e65441d0442c7381790aa4c538
Note: switching to 'c9f9347b7a72a4e65441d0442c7381790aa4c538'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at c9f9347 tests: Rename expected_findings to allowed_findings and improve docs
+ bazel build --java_runtime_version=local_jdk_15 -c opt --cxxopt=-stdlib=libc++ --linkopt=-lc++ //agent:jazzer_agent_deploy.jar //driver:jazzer_driver //driver:jazzer_driver_asan //driver:jazzer_driver_ubsan //agent:jazzer_api_deploy.jar
2022/11/09 14:53:35 Downloading https://releases.bazel.build/5.3.0/rc1/bazel-5.3.0rc1-linux-x86_64...
2022/11/09 14:53:36 could not download Bazel: could not copy from https://releases.bazel.build/5.3.0/rc1/bazel-5.3.0rc1-linux-x86_64 to /root/.cache/bazelisk/downloads/bazelbuild/bazel-5.3.0rc1-linux-x86_64/bin/download628637892: read tcp 172.17.0.2:32818->130.211.22.235:443: read: connection reset by peer
The command '/bin/sh -c install_java.sh' returned a non-zero code: 1
ERROR:root:Docker build failed.
Pulling and building base images first.
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py pull_images
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_image base-image --no-pull --cache
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_image base-builder --no-pull --cache
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_image base-builder-go --no-pull --cache
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_image base-builder-go-codeintelligencetesting --no-pull --cache
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_image base-builder-javascript --no-pull --cache
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_image base-builder-jvm --no-pull --cache
```

**Comment by Navidem** [comment]
Does this bump have anything with coverage? Looks like for `idna` and `glom` the coverage builds are failing causing the introspector build not to see any .covreport files.

**Comment by DavidKorczynski** [comment]
> Does this bump have anything with coverage? Looks like for `idna` and `glom` the coverage builds are failing causing the introspector build not to see any .covreport files.

Looks to be the coverage builds that is failing by default: https://oss-fuzz-build-logs.storage.googleapis.com/index.html#idna

**Comment by DavidKorczynski** [comment]
This line looks wrong: https://github.com/google/oss-fuzz/blob/67deda412c808bb601cf66527130b0f052013e9c/infra/base-images/base-runner/coverage#L320

**Comment by DavidKorczynski** [comment]
It's strange because the coverage build is working on/off https://oss-fuzz-build-logs.storage.googleapis.com/index.html#pyyaml

The step that uses gsutil:
```
- [20/38 files][  2.8 MiB/  3.5 MiB]  80% Done                                  
Copying file:///workspace/out/libfuzzer-coverage-x86_64/report/linux/d_6f2a7d53d095d69c___init___py.html [Content-Type=text/html]...
Step #7: - [20/38 files][  2.8 MiB/  3.5 MiB]  80% Done                                  
- [21/38 files][  3.3 MiB/  3.5 MiB]  92% Done                                  
- [22/38 files][  3.3 MiB/  3.5 MiB]  92% Done                                  
- [23/38 files][  3.3 MiB/  3.5 MiB]  93% Done                                  
- [24/38 files][  3.4 MiB/  3.5 MiB]  96% Done                                  
- [25/38 files][  3.4 MiB/  3.5 MiB]  96% Done                                  
- [26/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [27/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [28/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [29/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [30/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [31/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [32/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [33/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [34/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [35/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [36/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [37/38 files][  3.5 MiB/  3.5 MiB]  99% Done                                  
- [38/38 files][  3.5 MiB/  3.5 MiB] 100% Done                                  
Step #7: Operation completed over 38 objects/3.5 MiB.                                     
Finished Step #7
Starting Step #8
Step #8: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #8: CommandException: 1 files/objects could not be removed.
TIMEOUT
ERROR: context deadline exceeded
```

Do you know what this means?

**Comment by DavidKorczynski** [comment]
@Navidem I'm not entirely sure what's happening with the coverage builds, but all python coverage builds started failing today.

I see error messages:
```
- [415/415 files][ 46.1 MiB/ 46.1 MiB] 100% Done                                
Step #7: Operation completed over 415 objects/46.1 MiB.                                   
Finished Step #7
Starting Step #8
Step #8: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #8: CommandException: 1 files/objects could not be removed.
Finished Step #8
Starting Step #9
Step #9: Already have image (with digest): gcr.io/cloud-builders/gsutil
Step #9: CommandException: No URLs matched. Do the files you're operating on exist?
Finished Step #9
```
This must be related to the deployment we did yesterday -- am not entirely sure about which gsutil step is failing as I don't know that logic well. It looks like a copy is made for something that is not there -- could this be related to per-fuzzer coverage reports?

**Comment by DavidKorczynski** [comment]
okay. I've disabled per-fuzzre coverage reports for Python fuzz-introspector for now. Would it be possible to avoid this step for python fuzzer introspector builds?

**Comment by Navidem** [comment]
> Would it be possible to avoid this step for python fuzz-introspector builds?

It should be. Will look into it.

**Comment by Navidem** [comment]
> okay. I've disabled per-fuzzer coverage reports for Python fuzz-introspector for now.

Separate PR?

**Comment by Alan32Liu** [comment]
Please let me know if there is anything I could help with, I am on sheriffing this week : )

**Pull request merged**
