### PR TITLE
Remove unmaintained jsonnet.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@Betsy-Wang, this project is unmaintained, so removing it. If you still want it, please re-upload with no experimental bit. please see https://github.com/google/oss-fuzz/pull/1757#issuecomment-511058323 for context.

**Comment by inferno-chromium** [comment]
@sparkprime - do you want to bring this integration back, we would really appreciate if you can fix the stability and security bugs, and we can remove the experimental bit.

**Comment by evverx** [comment]
> if you can fix the stability and security bugs, and we can remove the experimental bit

Is my understanding correct that whoever has had access to those bug reports has been sitting on potentially security bugs that has never been looked into and reported to anyone and they are going to fixed silently and only after that the flag is going to be flipped?

**Comment by evverx** [comment]
I missed https://github.com/google/oss-fuzz/pull/2597. The bugs were fixed silently. The bit has just been flipped.

**Comment by sparkprime** [comment]
As far as I know, all fuzz bugs were fixed some time ago. Please let me know if this is not the case, thanks.

**Comment by inferno-chromium** [comment]
Yes I already brought it back. Problem was the experimental flag in project.yaml. this is now removed and bugs will be filed in oss-fuzz tracker so that community can see them once they were fixed.

**Comment by sparkprime** [comment]
Great, thanks!

**Pull request merged**
