### PR TITLE
Adds ygot project

### PR DESCRIPTION
**Pull request by catenacyber**
cc @robshakir

Would you be interested in continuous fuzzing for ygot ?
This PR enables it with oss-fuzz
Let me know if you have more questions

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@catenacyber, in the future could you mark Pull Requests as "Draft" if they aren't ready to be merge/reviewed by the OSS-Fuzz team?
It makes it easier for us to deal with the many open PRs we have.

**Comment by robshakir** [comment]
@wenovus -- do you see any reason not to have this fuzzing enabled? I'm happy to.

If we can make sure that ygot-maintainers@google.com is used for the reports, that'd be great.

**Comment by catenacyber** [comment]
> If we can make sure that ygot-maintainers@google.com is used for the reports, that'd be great.

Thanks for the feedback, just changed it

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
