### PR TITLE
Add the Qt Project

### PR DESCRIPTION
**Pull request by rlohning**
Adding project.yaml with basic info.

### CODE REVIEW

**Comment by rlohning** [comment]
Am 31.08.2018 um 19:52 schrieb Abhishek Arya:
> Merged #1779 into master.
> 

Wouldn't I have to sign one of the license agreements before?
I mean, I don't see a problem with signing it, I just didn't do it yet. 
Please let me know if I still need to sign it.

Best Regards,
Robert

**Comment by Dor1s** [comment]
@rlohning Thanks for noticing! Yeah, could you please sign the CLA?

**Comment by rlohning** [comment]
Am 04.09.2018 um 23:42 schrieb Max Moroz:
> @rlohning Thanks for noticing! Yeah, could you please sign the CLA?
> 

Done.
I choose the corporate CLA. On
https://cla.developers.google.com/clas
I can still read: "We don't have any individual agreements on file for you."
Is that just because the CLA was not yet confirmed by an authorized
manager or is there anything else I'll have to do myself?

Best Regards,
Robert

**Comment by Dor1s** [comment]
Thanks, @rlohning ! I'm seeing "The Qt COmpany", is that what you've signed as?

I think we also may need to ensure that an email address associated with your GitHub account is added to the company Google Group, if I understand the process right :)

**Comment by rlohning** [comment]
Am 05.09.2018 um 22:40 schrieb Max Moroz:
> Thanks, @rlohning ! I'm seeing "The Qt COmpany", is that what you've signed as?
> 
> I think we also may need to ensure that an email address associated with your GitHub account is added to the company Google Group, if I understand the process right :)
> 
> 

I hoped it was "The Qt Company" but in principle, that's correct.

If I understood correctly, I need to use a GMail-address in oss-fuzz
which I did:
rlohningqt@gmail.com
Besides that, I'd like to use my company address whenever possible:
robert.loehning@qt.io

In the Google group, I'm visible with the GMail-address, but I'm not
able to invite my company address because that seems to be already
considered a member.

What should we do?

Best Regards,
Robert

**Comment by Dor1s** [comment]
I'm not sure if that email is attached to your GitHub account an used for commits. For that commit I'm seeing:

```
Author: Robert Löhning <35148430+rlohning@users.noreply.github.com>  2018-08-31 10:51:58
```

 Please see the link in the bottom of googlebot's comment: https://github.com/google/oss-fuzz/pull/1779#issuecomment-417726483

**Comment by rlohning** [comment]
Am 06.09.2018 um 18:40 schrieb Max Moroz:
> I'm not sure if that email is attached to your GitHub account an used for commits. For that commit I'm seeing:
> 
> 
> 
> ```
> 
> Author: Robert Löhning <35148430+rlohning@users.noreply.github.com>  2018-08-31 10:51:58
> 
> ```
> 
> 
> 
>   Please see the link in the bottom of googlebot's comment: https://github.com/google/oss-fuzz/pull/1779#issuecomment-417726483
> 
> 
> 

Oh, yes. That was the default privacy setting. I now set this to the 
GMail-address and made that the primary address in the Google group. Is 
that supposed to work now?

Thank you for your patience...

Best Regards,
Robert

**Comment by Dor1s** [comment]
@rlohning, sorry for the inconvenience, but can you please re-upload your pull request again using a commit created with a proper email address? I've reverted the previous one.

**Comment by rlohning** [comment]
Am 06.09.2018 um 19:12 schrieb Max Moroz:
> @rlohning, sorry for the inconvenience, but can you please re-upload your pull request again using a commit created with a proper email address? I've reverted the previous one.
> 

Phew, that was tough, but I think I made it. Better now?

Best Regards,
Robert

**Pull request merged**
