### PR TITLE
Fix pcapplusplus build

### PR DESCRIPTION
**Pull request by sashashura**
https://oss-fuzz-build-logs.storage.googleapis.com/index.html#pcapplusplus

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@zlowram do you approve?

**Review by Lasso66 — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
Are you a pcap++ maintainer? I'm not sure I can merge this without zlowram's approva.

**Review by seladb — APPROVED** [review]

**Comment by seladb** [comment]
Hi @jonathanmetzman , I'm the maintainer of PcapPlusPlus, I think we should merge the PR

cc @sashashura

**Comment by DavidKorczynski** [comment]
> Could someone please start the workflows again?

done

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
