### PR TITLE
unbound: fix new fuzzer names

### PR DESCRIPTION
**Pull request by DavidKorczynski**
https://github.com/google/oss-fuzz/issues/6841

### CODE REVIEW

**Review by asraa — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
@gthess this shoudl fix unbound. But could you please confirm you are okay with me inserting license headers in the fuzzers?

**Comment by gthess** [comment]
We (NLnet Labs) don't mind since these are not part of NLnet Labs' Unbound code.
However these files were contributed by @luisx41 (https://github.com/google/oss-fuzz/pull/3210) as a result of the OSTIF security audit.

**Comment by DavidKorczynski** [comment]
@luisx41 are you okay with me adding license headers to the fuzzers you contributed for Unbound?

**Comment by luisx41** [comment]
Please, also merge https://github.com/google/oss-fuzz/pull/6950.

**Pull request merged**
