### PR TITLE
Update fuzzers to new Atheris version

### PR DESCRIPTION
**Pull request by TheShiftedBit**
Upcoming Atheris changes will change how coverage is collected. This updates the oss-fuzz fuzzers to use the new coverage.

DO NOT SUBMIT until new Atheris is released - likely today.

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
just ping me on chat whenever you want me to merge this. or builds dont start later in night like 9-10pm, so fine to merge as well.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by inferno-chromium** [comment]
We had build failures due to unpinned version, so pinning to old version for now (your cl will need to updated to master to take the change). See details in https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=36305#c1

**Comment by DavidKorczynski** [comment]
@TheShiftedBit could you clarify if fuzzers need to be updated due to this PR? You modified the python fuzzers in the OSS-Fuzz repo, should we do the same for usptream ones e.g. https://github.com/httplib2/httplib2/blob/master/tests/fuzz_request.py

**Comment by TheShiftedBit** [comment]
@DavidKorczynski Yes, it does. Instrumentation is no longer automatic.
Note that the breaking changes were included in a new major version, so anything that pins atheris 1.x.x won't be broken.

**Pull request merged**
