### PR TITLE
Remove libchewing.

### PR DESCRIPTION
**Pull request by oliverchang**
It seems like no one has been paying attention to libchewing bugs for the past few months (https://github.com/chewing/libchewing/issues), and it generates a fair amount of noise. It also probably wasn't the best fit for oss-fuzz in the first place, since it only accepts user input.

What do people think? Should it be removed? In the future we'll have a mechanism to limit execution of such fuzzers to a single CPU, but we don't have this right now.

@kcwu @kcc @Dor1s  @inferno-chromium @mikea

### CODE REVIEW

**Comment by inferno-chromium** [comment]
LGTM. If no-one cares about fixing bugs found, there is no need to have it in OSS-Fuzz. Also, i agree this was not the right fit for OSS-Fuzz in first place.

**Comment by kcwu** [comment]
Regarding to oss-fuzz fitness, input method engine sometimes is included in embedded system. ChromeOS did so in the past. Bugs of input method engine may open the door to let users break the security boundary. Anyway, it doesn't matter if no one fixing bugs.

I agreed to remove it because no people, including me, have time to fix bugs found.

cc some libchewing's contributors. @czchen, @jserv

**Comment by jserv** [comment]
I agree with @kcwu . At the moment, oss-fuzz already submitted more and more issues than what libchewing contributors can take care of.

**Comment by Dor1s** [comment]
LGTM

and +1 to kcc@'s idea to have it running on ~1 CPU once it became possible.

**Comment by kcc** [comment]
If everyone including the owners don't mind, sure, let's remove. 
But an alternative to completely removing is to disable it somehow and when we can enable it back on a tiny amount of cores. If anything, this will allow us to automatically report when any of the bugs get fixed.

**Comment by oliverchang** [comment]
Sure, we can keep building and verifying fixes for this. I'll add a disabled: true flag to the project.yaml

**Pull request closed without merging**
