### PR TITLE
askama: initial integration

### PR DESCRIPTION
**Pull request by manunio**
Hi, [Askama](https://github.com/djc/askama) is one of the popular template rendering engine based on [Jinja](https://jinja.palletsprojects.com/).
 - It has `3 million+` downloads as per [crates.io](https://crates.io/crates/askama).
 - It being used by projects like:
   - [mozilla/uniffi-rs](https://github.com/mozilla/uniffi-rs)
     - a multi-language bindings generator for rust. 
    - It also used along with web frameworks like [actix](https://crates.io/crates/actix), [axum](https://crates.io/crates/axum), [warp](https://crates.io/crates/warp).

### CODE REVIEW

**Comment by djc** [comment]
> [Plotly.js](https://www.npmjs.com/package/plotly.js)
> 
>     * Plotly.js is a standalone Javascript data visualization library, and it also powers the Python and R modules named plotly in those respective ecosystems (referred to as [Plotly.py](https://plotly.com/python) and [Plotly.R](http://plotly.com/r)).

Where are you getting this? The plotly.js repo doesn't contain any Rust code, so I'm confused about how it might be using Askama.

**Comment by Alan32Liu** [comment]
Thanks, @manunio!
I guess this is not ready for review yet : )
Let me convert this to a draft, but please always feel free to convert it back once ready.

**Comment by Alan32Liu** [comment]
> Hi @Alan32Liu it's ready for review. I have striked out/removed wrong info from description of this pr.
> 
> cc @djc

OK, I will ask the panel.

**Comment by Alan32Liu** [comment]
Panel approved, let's merge it if it looks good to @djc .

**Review by Alan32Liu — APPROVED** [review]

**Pull request merged**
