### PR TITLE
[yajl-ruby] Add yajl-ruby fuzzer

### PR DESCRIPTION
**Pull request by titanous**
yajl-ruby is an extremely popular Ruby gem that uses a C extension to parse JSON.

@brianmario @tenderlove :wave: This fuzzer will be added to OSS-Fuzz and continuously fuzz the JSON parser for various memory safety bugs and crashes.

### CODE REVIEW

**Comment by brianmario** [comment]
👋  Hi!

This appears to be only testing the yajl C APIs. Which is totally fine as the yajl sources embedded in yajl-ruby are a slightly modified version of upstream [yajl](https://github.com/lloyd/yajl)'s 1.x branch.  So I'd definitely love to have them tested here. But should we also test the yajl-ruby C extension code as well? Not sure if we'd have to go through a Ruby program in order to do that or if we could just use the C symbols exposed for Ruby to use along with Ruby's C APIs. @tenderlove have you by chance used C extension code in that way before?

**Comment by titanous** [comment]
@brianmario Yeah, covering that code is totally doable. It's more work and I wanted to get this going quickly, so my thought was that we could merge this and I could update it to have more coverage in a subsequent PR.

**Comment by brianmario** [comment]
Oh cool ok! 👍

**Comment by inferno-chromium** [comment]
Can you please comment on who are the consumers of yail-ruby, we need to understand how widely is this project used.

**Comment by titanous** [comment]
yajl-ruby has >20M downloads and is used in tens of thousands of Ruby programs and web applications: https://rubygems.org/gems/yajl-ruby

**Pull request merged**
