### PR TITLE
krb5: Add gss_accept_sec_context fuzz harness

### PR DESCRIPTION
**Pull request by philipturnbull**
`gss_accept_sec_context` is one of the main APIs used for server applications and typically accepts untrusted data via the `input_token` parameter.

@greghudson: fyi, here's the improvements to the fuzzing setup that we discussed via email.

### CODE REVIEW

**Comment by oliverchang** [comment]
@greghudson: please confirm if these changes look good, thanks!

**Review by greghudson — APPROVED** [review]
I'm not sure that <stdio.h> or <stdint.h> are needed in Fuzz_gss_accept_sec_context.c, but substantively this looks good.

**Comment by greghudson** [comment]
I would keep <stdlib.h> since that code uses malloc(), although it won't matter in practice because krb5.h includes stdlib.h and that's unlikely to change.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
