### PR TITLE
bitcoin-core: Work around llvm bugs in OUR_LLVM_REVISION

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Comment by guidovranken** [comment]
> 32-bit CI failure can be ignored. It is caused by [guidovranken/cryptofuzz@c9827bb](https://github.com/guidovranken/cryptofuzz/commit/c9827bbb0bc98409b8b1a579593ace0b9395a270) cc @guidovranken

I've fixed the issue https://github.com/guidovranken/cryptofuzz/commit/94ac5046e92357049d0ae4bbde52781f217d5321

**Comment by MarcoFalke** [comment]
rfm? :pray:

**Comment by MarcoFalke** [comment]
@jonathanmetzman Mind taking a look here? Our project doesn't compile right now.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by MarcoFalke** [comment]
Thanks :+1:

**Comment by jonathanmetzman** [comment]
Thanks David!

**Pull request merged**
