### PR TITLE
Add Exiv2

### PR DESCRIPTION
**Pull request by kevinbackhouse**
[Exiv2](https://github.com/Exiv2/exiv2) is a command-line utility and C++ library for reading, writing, deleting, and modifying the metadata of image files. It would be great if you could add it to OSS-Fuzz!

I have fixed all the ASAN/UBSAN bugs that I am aware of. However, there are a few results like this, which I consider to be false positives:

```bash
/home/kev/exiv2/src/tiffvisitor_int.cpp:778:29: runtime error: null pointer passed as argument 2, which is declared to never be null
/usr/include/string.h:44:28: note: nonnull attribute specified here
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/kev/exiv2_0.27/src/tiffvisitor_int.cpp:778:29 in 
```

That error is due to calling `memcpy()` with a null pointer, but the size argument is zero, so I don't think it's a bug. The issue is discussed [here on stackoverflow](https://stackoverflow.com/questions/16362925/can-i-pass-a-null-pointer-to-memcmp). Will that be a problem on OSS-Fuzz? If so, I will postpone this pull request until I have fixed those issues. (I am planning to do so anyway, but I am keen to get Exiv2 enrolled in OSS-Fuzz as soon as possible.)

### CODE REVIEW

**Comment by kevinbackhouse** [comment]
@googlebot I signed it!

**Comment by kevinbackhouse** [comment]
Please could you try running the checks again? I have made some changes and tested locally using [these instructions](https://google.github.io/oss-fuzz/getting-started/new-project-guide/#testing-locally).

**Comment by jonathanmetzman** [comment]
Done.

**Comment by kevinbackhouse** [comment]
I dropped AFL and honggfuzz, so the checks pass now. (I tested it on [my own fork](https://github.com/kevinbackhouse/oss-fuzz/pull/1).) In the previous commit, I got the AFL build to pass by changing the way that I create the seed corpus, but honggfuzz was still failing with the message "ERROR: 100.0% of fuzz targets seem to be broken". Our [fuzz target](https://github.com/Exiv2/exiv2/blob/f8bfad1551e1b96a673c2b129bce720d79ddd6a6/fuzz/fuzz-read-print-write.cpp#L7) uses `LLVMFuzzerTestOneInput`, so our cmake build uses [`-fsanitize=fuzzer-no-link`](https://github.com/Exiv2/exiv2/blob/f8bfad1551e1b96a673c2b129bce720d79ddd6a6/cmake/compilerFlags.cmake#L78) and [`-fsanitize=fuzzer`](https://github.com/Exiv2/exiv2/blob/f8bfad1551e1b96a673c2b129bce720d79ddd6a6/fuzz/CMakeLists.txt#L7). I guess those are libFuzzer features that shouldn't be used with AFL and honggfuzz, but I am not sure how to build the fuzzing target without them (there would be no `main` function). So the easiest solution is to drop AFL and honggfuzz, but please let me know if you have any advice on how to make our build system compatible with them.

**Comment by inferno-chromium** [comment]
> I dropped AFL and honggfuzz, so the checks pass now. (I tested it on [my own fork](https://github.com/kevinbackhouse/oss-fuzz/pull/1).) In the previous commit, I got the AFL build to pass by changing the way that I create the seed corpus, but honggfuzz was still failing with the message "ERROR: 100.0% of fuzz targets seem to be broken". Our [fuzz target](https://github.com/Exiv2/exiv2/blob/f8bfad1551e1b96a673c2b129bce720d79ddd6a6/fuzz/fuzz-read-print-write.cpp#L7) uses `LLVMFuzzerTestOneInput`, so our cmake build uses [`-fsanitize=fuzzer-no-link`](https://github.com/Exiv2/exiv2/blob/f8bfad1551e1b96a673c2b129bce720d79ddd6a6/cmake/compilerFlags.cmake#L78) and [`-fsanitize=fuzzer`](https://github.com/Exiv2/exiv2/blob/f8bfad1551e1b96a673c2b129bce720d79ddd6a6/fuzz/CMakeLists.txt#L7). I guess those are libFuzzer features that shouldn't be used with AFL and honggfuzz, but I am not sure how to build the fuzzing target without them (there would be no `main` function). So the easiest solution is to drop AFL and honggfuzz, but please let me know if you have any advice on how to make our build system compatible with them.

OSS-Fuzz passes the right cflags and cxxflags when needing to build afl++ and honggfuzz, can you avoid setting those when run in OSS-Fuzz build environment ? AFL++ coverage is important as it finds its unique set of bugs.

**Comment by kevinbackhouse** [comment]
@inferno-chromium: If I remove the `-fsanitize=fuzzer` flag from our cmake config then all the builds fail with the error "undefined reference to main" ([link to test PR](https://github.com/kevinbackhouse/oss-fuzz/pull/2)). That's because our [fuzz target](https://github.com/Exiv2/exiv2/blob/f8bfad1551e1b96a673c2b129bce720d79ddd6a6/fuzz/fuzz-read-print-write.cpp#L7) only defines `LLVMFuzzerTestOneInput`, and the `main` function is auto-generated by libFuzzer.

Is there a way to add a `main` function that is compatible with libFuzzer, AFL, and honggfuzz?

**Comment by kevinbackhouse** [comment]
Ok, apparently the solution is to add `$LIB_FUZZING_ENGINE` as a linker flag ([link to test PR](https://github.com/kevinbackhouse/oss-fuzz/pull/3)).

I have created a [pull request](https://github.com/Exiv2/exiv2/pull/1875) to update our cmake configuration. When that's merged, I'll add another commit to this PR to update `build.sh`. I'll switch this PR to draft until that's ready.

**Comment by jonathanmetzman** [comment]
> Ok, apparently the solution is to add `$LIB_FUZZING_ENGINE` as a linker flag ([link to test PR](https://github.com/kevinbackhouse/oss-fuzz/pull/3)).
> 
> I have created a [pull request](https://github.com/Exiv2/exiv2/pull/1875) to update our cmake configuration. When that's merged, I'll add another commit to this PR to update `build.sh`. I'll switch this PR to draft until that's ready.

Right, the main function for AFL/LibFuzzer/HF is linked in via LIB_FUZZING_ENGINE

**Comment by kevinbackhouse** [comment]
This should pass the automated checks now ([link to test PR](https://github.com/kevinbackhouse/oss-fuzz/pull/4)).

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
