### PR TITLE
Revert addition of libressl

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Build fails because check_fuzzer fails on ASAN builds (`client` + `server` targets).

```
I  Step #5: ERROR: 22% of fuzz targets seem to be broken. See the list above for a detailed information. 
I  Step #5: INFO: A corpus is not provided, starting from an empty corpus 
I  Step #5: INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes 
I  Step #5: INFO: Loaded 1 PC tables (33403 PCs): 33403 [0xd2fe68,0xdb2618),  
I  Step #5: INFO: Loaded 1 modules   (33403 inline 8-bit counters): 33403 [0xd27be8, 0xd2fe63),  
I  Step #5: INFO: Seed: 1018820602 
I  Step #5: BAD BUILD: /workspace/out/address/server seems to have either startup crash or exit: 
I  Step #5: server: 
I  Step #5: INFO: A corpus is not provided, starting from an empty corpus 
I  Step #5: INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes 
I  Step #5: INFO: Loaded 1 PC tables (33371 PCs): 33371 [0xd2db48,0xdb00f8),  
I  Step #5: INFO: Loaded 1 modules   (33371 inline 8-bit counters): 33371 [0xd258e8, 0xd2db43),  
I  Step #5: INFO: Seed: 1018583564 
I  Step #5: BAD BUILD: /workspace/out/address/client seems to have either startup crash or exit: 
I  Step #5: client: 
I  Step #5: Broken fuzz targets (2): 
```

You can test this locally using the `check_fuzzer` command. I'll reland once you confirm it is fixed.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @thypon
btw, my fix in #2197 was useful, but the build is failing for another reason now. Since it's up to project maintainers to fix those, i'll revert the project addition to stop the exceptions we get in ClusterFuzz when a new project's builds fail.

**Comment by Dor1s** [comment]
The builder still tries to build the project (I think our auto-setup script doesn't delete projects). We should either manually delete it from the builder to reland the integration. @thypon do you plan on fixing the build?

**Comment by thypon** [comment]
Yep, my plan is to fix end of this week, maximum.

**Comment by thypon** [comment]
@Dor1s I have the fixes, I am working to mainline them.

**Pull request merged**
