### PR TITLE
Rename execSan to SystemSan.

### PR DESCRIPTION
**Pull request by oliverchang**
All of the bug detectors we've built (or plan to build) relate to system
state.

Also update our README.

### CODE REVIEW

**Review by Alan32Liu — APPROVED** [review]
LGTM!

**Comment by jonathanmetzman** [comment]
> All of the bug detectors we've built (or plan to build) relate to system state.
> 

Not XSS and SQL IMO

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by oliverchang** [comment]
> > All of the bug detectors we've built (or plan to build) relate to system state.
> 
> Not XSS and SQL IMO

Good point. some of those might need different approaches anyway (e.g. XSS would need that browser environment).

"System" may also be generic enough to apply to SQL. I thought about this for a while but didn't have any other suggestions for names.

**Pull request merged**
