### PR TITLE
Add skia-bugs-central@skia-public.iam.gserviceaccount.com to auto_ccs

### PR DESCRIPTION
**Pull request by jonathanmetzman**
So that this service account has view access.
@oliverchang Is that the best way to give this service account access to skia bugs?

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @kjlubick

**Comment by oliverchang** [comment]
> So that this service account has view access. @oliverchang Is that the best way to give this service account access to skia bugs?

What does the service account need to access? Monorail? CF?

**Comment by kjlubick** [comment]
View the monorail issues

**Comment by rmistry** [comment]
For my understanding: The service account will now have access to all existing Skia issues, not just new Skia issues. Is that correct?

**Comment by oliverchang** [comment]
> For my understanding: The service account will now have access to all existing Skia issues, not just new Skia issues. Is that correct?

That's right. The service account will be auto-CC'ed on existing open issues.

**Comment by rmistry** [comment]
> > For my understanding: The service account will now have access to all existing Skia issues, not just new Skia issues. Is that correct?
> 
> That's right. The service account will be auto-CC'ed on existing open issues.

Thanks for the confirmation!

**Pull request merged**
