### PR TITLE
Add vendors to Python projects.

### PR DESCRIPTION
**Pull request by oliverchang**

### CODE REVIEW

**Comment by Navidem** [comment]
The CI failure is irrelevant to the changes, it is running out of disk space.

**Review by Navidem — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
Somewhat unfortunate this PR makes a lot of unrelated changes (like moving the order)

**Comment by oliverchang** [comment]
> Somewhat unfortunate this PR makes a lot of unrelated changes (like moving the order)

Note sure what to do about that, this is just the YAML parser reordering.

**Pull request merged**
