### PR TITLE
Populate a bunch of main_repo values.

### PR DESCRIPTION
**Pull request by oliverchang**
Also enforce this for future integrations.

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]
Should we call it "source_repo"
Should we strip out ".git" from template and other urls ?

**Comment by oliverchang** [comment]
> Should we call it "source_repo"
> Should we strip out ".git" from template and other urls ?

Clusterfuzz code etc already relies on main_repo so will be a bit involved to rename at this point. I also think "main" is clearer as there can be many repos checked out in a project? 

Not sure if stripping out ".git" is always correct -- I think that is dependent on the git server implementation. I'm not 100% sure but for some servers may not be optional?

**Comment by inferno-chromium** [comment]
> > Should we call it "source_repo"
> > Should we strip out ".git" from template and other urls ?
> 
> Clusterfuzz code etc already relies on main_repo so will be a bit involved to rename at this point. I also think "main" is clearer as there can be many repos checked out in a project?
> 
> Not sure if stripping out ".git" is always correct -- I think that is dependent on the git server implementation. I'm not 100% sure but for some servers may not be optional?

ok skip both then.

**Comment by jonathanmetzman** [comment]
LGTM

**Pull request merged**
