### PR TITLE
[qt] Clone the latest combination of qtbase and qtsvg which passed upstream CI

### PR DESCRIPTION
**Pull request by rlohning**
The super-repo qt5.git contains the revisions which were last tested successfully with all
submodules together. That is much older.

The super repo can be removed as soon as the build script was updated in upstream repo.

### CODE REVIEW

**Comment by rlohning** [comment]
afl-clang-fast++ crashing again. Is anybody already working on that? Should be unrelated to this change.

**Comment by rlohning** [comment]
Building Qt passed in https://github.com/google/oss-fuzz/pull/7028 , which did not build Qt Widgets. In case that made the difference, I'll try another run of this here when https://codereview.qt-project.org/c/qt/qtqa/+/386883 was merged upstream, the change which was cherry-picked into https://github.com/google/oss-fuzz/pull/7028.

**Comment by rlohning** [comment]
Could someone please merge this? Because of problems on Qt's (our) side, the tested code is more than a month old already. This change here allow us to circumvent that.

Should anything be missing in the change, please let me know and I'll fix it.

**Review by DavidKorczynski — APPROVED** [review]

**Comment by rlohning** [comment]
Oh, that was quick! Thank you very much. :-)

**Comment by DavidKorczynski** [comment]
> Oh, that was quick! Thank you very much. :-)

You're welcome :)!

**Pull request merged**
