### PR TITLE
kcodecs: fix build

### PR DESCRIPTION
**Pull request by tyler92**
Changes:

1. `-DBUILD_TESTING=OFF` for `extra-cmake-modules` and `kcodecs`
2. `-qt-zlib` for `qtbase`

### CODE REVIEW

**Comment by vitorguidi** [comment]
> tyler92 is a new contributor to [projects/kcodecs](https://github.com//google/oss-fuzz/tree/master/projects/kcodecs). The PR must be approved by known contributors before it can be merged. The past contributors are: tsdgeos, maflcko, DonggeLiu, devtty1er, Dor1s

@tsdgeos @maflcko @devtty1er does this look good to you?

**Comment by tsdgeos** [comment]
Is the build failing? I don't remember getting an email about it

**Comment by tyler92** [comment]
Yes, it's failing, e.g. logs for today: https://oss-fuzz-build-logs.storage.googleapis.com/log-26ddcf53-8c88-43bb-96c2-20f39a6991e9.txt

**Comment by tsdgeos** [comment]
The code is fine, please someone merge it.

I am sad that I am no longer receiving emails for failures :/

**Review by vitorguidi — APPROVED** [review]
lgtm

**Pull request merged**
