### PR TITLE
open62541: fix build to work with CIFuzz

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
THis breaks the build it seems.
Maybe it isn't needed given that I no longer clobber the repo.

**Comment by DavidKorczynski** [comment]
The build is broken, I have informed maintainers here https://github.com/open62541/open62541/pull/4803#issuecomment-981493576

**Comment by jpfr** [comment]
Fixed by #4826.

**Comment by DavidKorczynski** [comment]
Thanks @jpfr - I think this PR might no longer be needed because Jonathan solved the problem, we should try out a CIFuzz run on the main repo to see if things work now

**Comment by DavidKorczynski** [comment]
Testing here: https://github.com/open62541/open62541/pull/4841

**Comment by DavidKorczynski** [comment]
Wonderful - it works without this PR now. Thanks @jpfr and @jonathanmetzman

**Pull request closed without merging**
