### PR TITLE
rust coverage: fix binary ids padding

### PR DESCRIPTION
**Pull request by catenacyber**
Following #6517 

Since then, the new LLVM 14 commit b9f547e8e51182d32f1912f97a3e53f4899ea6be https://reviews.llvm.org/D110365
added a new change (adding a padding and erroring if a field size is not a multiple of sizeof(uint64))

cc @jonathanmetzman

### CODE REVIEW

**Comment by catenacyber** [comment]
Tested on flate2-rs

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
@catenacyber Could you convert this to python please?

**Comment by catenacyber** [comment]
Thanks Johnathan.
I did not forget about python, but I want to check that rust goes green first

**Comment by catenacyber** [comment]
Most rust projects seem to have coverage fixed

Some rust projects have their fuzzing build broken :
libra, oak, prost, rust-regex, suricata

Some projects have their fuzzing build ok but their coverage build broken :
linkerd2-proxy (same problem as rustls), opensk (relative path instead of absolute for some rust sources), rustls (problem of path of C files compiled by rust)
So these are other problems, likely missing `remap-path-prefix`

Not yet rebuilt today :
servo, wastime

So, next is to rewrite in python

**Pull request merged**
