### PR TITLE
afl++ fixes

### PR DESCRIPTION
**Pull request by vanhauser-thc**
This fixes CTX compile mode and CMPLOG when encountering floating point vectors.
#7021 - fixes mupdf, cjson and qt.
let's hope these are all the bugs.

@oliverchang @Navidem @jonathanmetzman

### CODE REVIEW

**Review by DavidKorczynski — APPROVED** [review]
I tested this on 3 of the projects from https://github.com/google/oss-fuzz/issues/7021 and they all pass, will await for others to determine when to merge in though

**Comment by MarcoFalke** [comment]
Thank you. We are still seeing the bug [1] regularly, so +1 on merging this.

[1] https://bugs.chromium.org/p/oss-fuzz/issues/list?q=bitcoin-core%20float%20%20ASSERT%20encoded_in_memory&can=1

**Comment by MarcoFalke** [comment]
Let me know if I should manually test this on `bitcoin-core`, or if it is good to go in as-is.

**Comment by MarcoFalke** [comment]
@oliverchang @jonathanmetzman Anything needed to do here?

**Comment by vanhauser-thc** [comment]
CI failure is not mine:
```
=================================== FAILURES ===================================
_________________ GenerateImplTest.test_generate_swift_project _________________
[gw1] linux -- Python 3.8.12 /opt/hostedtoolcache/Python/3.8.12/x64/bin/python

self = <helper_test.GenerateImplTest testMethod=test_generate_swift_project>

    def test_generate_swift_project(self):
      """Tests that the swift project uses the correct base image."""
      helper._generate_impl(helper.Project(self.PROJECT_NAME), 'swift')
>     self._verify_templated_files(
          templates.TEMPLATES,
          os.path.join(helper.OSS_FUZZ_DIR, 'projects', self.PROJECT_NAME),
          'swift')

infra/helper_test.py:156: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
infra/helper_test.py:129: in _verify_templated_files
    self.assertEqual(contents, template % template_args)
E   AssertionError: '#!/b[23 chars]t 2022 Google LLC\n#\n# Licensed under the Apa[869 chars].a\n' != '#!/b[23 chars]t 2021 Google LLC\n#\n# Licensed under the Apa[869 chars].a\n'
E   Diff is 1041 characters long. Set self.maxDiff to None to see it.
=========================== short test summary info ============================
FAILED infra/helper_test.py::GenerateImplTest::test_generate_swift_project - ...
============= 1 failed, 223 passed, 8 skipped in 404.07s (0:06:44) =============
```

**Comment by oliverchang** [comment]
@jonathanmetzman Let's get ready to try this this week? I also have https://github.com/google/clusterfuzz/pull/2520 out to give us an extra day to revert if something goes wrong.

**Comment by vanhauser-thc** [comment]
this is now open for 4 weeks ...  @jonathanmetzman @DavidKorczynski @inferno-chromium 

step 1: geht this merged and see if anything still fails
step 2: update llvm and see if anything new fails

**Review by MarcoFalke — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
> this is now open for 4 weeks ... @jonathanmetzman @DavidKorczynski @inferno-chromium
> 
> step 1: geht this merged and see if anything still fails step 2: update llvm and see if anything new fails

My position remains as above: https://github.com/google/oss-fuzz/pull/7026#pullrequestreview-834608465 - this lgtm (and thanks for fixing it up!!) and will wait for others to merge in

**Comment by inferno-chromium** [comment]
@jonathanmetzman - i am merging this since some folks have tested this. please keep an eye.

**Comment by rlohning** [comment]
Thanks for merging. I'll let you know if I notice anything strange in Qt.

**Comment by jonathanmetzman** [comment]
Let's wait before rolling clang.

**Comment by jonathanmetzman** [comment]
By my count, this causes the following breakages:
[cpython3](https://oss-fuzz-build-logs.storage.googleapis.com/log-8fa121ea-3850-44e7-9103-a8ae36a50970.txt):  FATAL: forkserver is already up, but an instrumented dlopen() library loaded afterwards. You must AFL_PRELOAD such libraries to be able to fuzz them or LD_PRELOAD to run outside of afl-fuzz.
[libxml](https://oss-fuzz-build-logs.storage.googleapis.com/log-8c37588e-62f8-46e1-8cc2-346ecc9efc93.txt) Null deref at runtime (genSeed)
[mercurial](https://oss-fuzz-build-logs.storage.googleapis.com/log-35923305-49cc-4a8f-9e41-c67f2033a796.txt): FATAL: forkserver is already up, but an instrumented dlopen() library loaded afterwards. You must AFL_PRELOAD such libraries to be able to fuzz them or LD_PRELOAD to run outside of afl-fuzz.

**Comment by vanhauser-thc** [comment]
mercurial and cpython3 fail and it is good that they fail as this is a bad setup (that is why the behaviour changed. before it was silently just being less effective). there is an env to ignore this, but rather the setup should be fixed. I can help the devs to get this working. I can also set that env var that keeps ignoring it though.

libxml - I will take a look.

**Pull request merged**
