### PR TITLE
[Libmediaart] Initial integration

### PR DESCRIPTION
**Pull request by ecalp-tps**
Hello,

I am a Software Engineering Intern at Google, working with the Third Party Security (TPS) team. As part of my internship I am working on fuzzing GNOME/freedesktop libraries and Libmediaart is one of the libraries that we have picked for this work.

You can find the MR for integrating my fuzzers into the main Libmediaart repository [here](https://gitlab.gnome.org/GNOME/libmediaart/-/merge_requests/5). I've been in talks with the upstream to identify a contact point from their end, but they are still working on it. I’m fetching the Libmediaart repo from my personal fork in the Dockerfile. Once the upstream approves my MR, I will update this PR with the link to the main Libmediaart repo.

Thanks!
Ceyhun
ceyhunalp@google.com

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
It's not clear to me that it is worth fuzzing this project. [Here](https://gitlab.gnome.org/GNOME/libmediaart/-/merge_requests/5) they say it's just a wrapper around gstreamer and gdk-pixbuf. Can you clarify with the owners whether they think this is likely to find any bugs in libmediaart itself?

**Comment by ecalp-tps** [comment]
> It's not clear to me that it is worth fuzzing this project. [Here](https://gitlab.gnome.org/GNOME/libmediaart/-/merge_requests/5) they say it's just a wrapper around gstreamer and gdk-pixbuf. Can you clarify with the owners whether they think this is likely to find any bugs in libmediaart itself?

Hello Jonathan - thank you for the comment. I forwarded your question to the owners and here's their [response](https://gitlab.gnome.org/GNOME/libmediaart/-/merge_requests/5#note_970859). I also want to note that my fuzz targets have already caused crashes in libmediaart itself because of missing input sanitizations.

This also brings me to my next question. You will notice that the build check for `undefined` fails because of two fuzz targets. These are the targets that cause the crashes in libmediaart. Do you have any suggestions on how I can work around this problem?

**Review by inferno-chromium — CHANGES_REQUESTED** [review]
Please modify to use upstream repo and add fuzzers here, similar to other PR.

For UBSan startup crash, can leave it as-is and we will see if maintainer fixes them.

Try getting maintainer email in project.yaml

**Review by Google-Autofuzz — APPROVED** [review]

**Comment by inferno-chromium** [comment]
@ecalp-tps, can you post another PR to add the fuzzers and use upstream repo, instead of your personal fork soon. This caused confusion on poppler and i dont want same thing to happen here.

**Comment by inferno-chromium** [comment]
Actually let me revert to avoid confusion, similar to poppler.

**Comment by ecalp-tps** [comment]
> Actually let me revert to avoid confusion, similar to poppler.

Thank you for the help Abhishek. I was still working on the PRs (adding both your and Julien's suggestions) when they were merged so I was slightly confused as well. Should I reopen an MR for all libraries? That might be easier since my development branches already have the updates that I have made since the PRs were merged. For poppler and libmediaart, these changes include using the upstream repo and bringing the fuzzers into OSS-Fuzz.

**Comment by ecalp-tps** [comment]
> Please modify to use upstream repo and add fuzzers here, similar to other PR.
> 
> For UBSan startup crash, can leave it as-is and we will see if maintainer fixes them.
> 
> Try getting maintainer email in project.yaml

- I modified the upstream repo and added the fuzzers here.
- I also re-enabled two fuzzers that I originally left out because they were causing the build checks to fail. However, as I mentioned before these fuzzers find crashes in libmediaart so I think it makes sense to keep them in.
- As you can see in this [thread](https://gitlab.gnome.org/GNOME/libmediaart/-/merge_requests/5#note_939377), upstream does not want to give a single person's email address so they started discussions with the GNOME folks to create a 'fuzz-testing' mail list.

**Comment by inferno-chromium** [comment]
@ecalp-tps - since poppler and libmediaart cls were reverted, please open new PRs, one for each library change.

**Pull request merged**
