### PR TITLE
liboqs: Initial integration

### PR DESCRIPTION
**Pull request by nathaniel-brough**

### CODE REVIEW

**Comment by silvergasp** [comment]
TODO:
- [ ] Add primary Author
- [ ] Switch clone repo over from my personal fork once https://github.com/open-quantum-safe/liboqs/pull/1905 is merged

**Comment by DonggeLiu** [comment]
Is this ready for review? Thanks : )

**Comment by silvergasp** [comment]
> Is this ready for review? Thanks : )

A yes/no on if oss-fuzz is interested in merging would be great. But no Im still waiting on https://github.com/open-quantum-safe/liboqs/pull/1905 to be merged. This draft PR is still downloading my fork which contains the new fuzz harnesses.

**Comment by nathaniel-brough** [comment]
@DonggeLiu this is now ready for review.

**Why is liboqs critical for global infrastructure?**
The [Open Quantum Safe (OQS) project](https://openquantumsafe.org/about) is an open-source project that aims to support the transition to [quantum-resistant cryptography](https://openquantumsafe.org/post-quantum-crypto). OQS is part of the [Linux Foundation](https://www.linuxfoundation.org/)’s [Post-Quantum Cryptography Alliance](https://pqca.org/) with members including but not limited to;
- AWS
- CISCO
- Google
- IBM
- NVIDIA

With increasing interest in general purpose quantum computing it is critical that quantum resistant encryption algorithms are stabilised and verified before the so-called "Q-day" when current encryption algorithms are vulnerable to quantum attacks. This fuzzing effort will accelerate the time-frame under which liboqs will be ready for general use.

**Comment by nathaniel-brough** [comment]
CC: @baentsch @dstebila @SWilson4

**Comment by baentsch** [comment]
Thanks @nathaniel-brough for initiating these first steps resolving a [long-standing issue to improve the code base](https://github.com/open-quantum-safe/liboqs/issues/1215)! Once deployed to at least the algorithms now standardized (ML-KEM, ML-DSA, SLH-DSA) and partially already included in the library, this will help improve the reliability of the code base. If explicitly needed, @DonggeLiu this is to state support and gratitude for this effort as [a maintainer of liboqs](https://github.com/open-quantum-safe/liboqs/blob/main/GOVERNANCE.md#maintainers-1).

**Comment by DonggeLiu** [comment]
Thanks @nathaniel-brough and @baentsch.
OSS-Fuzz panel is also happy to integrate this project.

I will merge the PR.

**Review by DonggeLiu — APPROVED** [review]

**Comment by dstebila** [comment]
Thanks for doing this!!

**Pull request merged**
