### PR TITLE
[freetype2] Enable 32-bit fuzzing (#643).

### PR DESCRIPTION
**Pull request by Dor1s**
//cc @lemzwerg better late than never!

### CODE REVIEW

**Comment by Dor1s** [comment]
@jonathanmetzman am I doing this right?

**Comment by jonathanmetzman** [comment]
Maybe? Let's see what travis says but if there's any object code that gets linked into the freetype build we'll need to install the 32 bit versions.

**Comment by Dor1s** [comment]
@lemzwerg could you please take  a look?

```
[  1%] Building CXX object src/fuzzers/CMakeFiles/fuzzer-legacy.dir/__/legacy/ftfuzzer.cc.o
[  2%] Building CXX object src/targets/CMakeFiles/fuzztargets.dir/__/iterators/faceloaditerator.cpp.o
[  3%] Linking CXX executable ../../bin/legacy
/usr/bin/ld: i386:x86-64 architecture of input file `../../../../external/bzip2/libbz2.a(bzlib.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `../../../../external/bzip2/libbz2.a(crctable.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `../../../../external/bzip2/libbz2.a(randtable.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `../../../../external/bzip2/libbz2.a(compress.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `../../../../external/bzip2/libbz2.a(decompress.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `../../../../external/bzip2/libbz2.a(blocksort.o)' is incompatible with i386 output
/usr/bin/ld: i386:x86-64 architecture of input file `../../../../external/bzip2/libbz2.a(huffman.o)' is incompatible with i386 output
[  4%] Building CXX object src/targets/CMakeFiles/fuzztargets.dir/__/iterators/faceprepiterator.cpp.o
clang-10: error: linker command failed with exit code 1 (use -v to see invocation)
src/fuzzers/CMakeFiles/fuzzer-legacy.dir/build.make:99: recipe for target 'bin/legacy' failed
make[2]: *** [bin/legacy] Error 1
CMakeFiles/Makefile2:778: recipe for target 'src/fuzzers/CMakeFiles/fuzzer-legacy.dir/all' failed
make[1]: *** [src/fuzzers/CMakeFiles/fuzzer-legacy.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Building CXX object src/targets/CMakeFiles/fuzztargets.dir/__/iterators/faceprepiterator-bitmaps.cpp.o
<...>
[ 37%] Building CXX object src/targets/CMakeFiles/fuzztargets.dir/__/utils/utils.cpp.o
/src/freetype2-testing/fuzzing/src/utils/tarreader.cpp:77:13: error: no matching function for call to 'archive_read_data_block'
        r = archive_read_data_block( archive.get(),
            ^~~~~~~~~~~~~~~~~~~~~~~
/src/freetype2-testing/fuzzing/../external/libarchive/libarchive/archive.h:601:15: note: candidate function not viable: no known conversion from 'off_t *' (aka 'long *') to 'la_int64_t *' (aka 'long long *') for 4th argument
__LA_DECL int archive_read_data_block(struct archive *a,
              ^
1 error generated.
src/targets/CMakeFiles/fuzztargets.dir/build.make:1118: recipe for target 'src/targets/CMakeFiles/fuzztargets.dir/__/utils/tarreader.cpp.o' failed
make[2]: *** [src/targets/CMakeFiles/fuzztargets.dir/__/utils/tarreader.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:106: recipe for target 'src/targets/CMakeFiles/fuzztargets.dir/all' failed
make[1]: *** [src/targets/CMakeFiles/fuzztargets.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
Building fuzzers failed.
Failed projects: freetype2
The command "./infra/travis/travis_build.py" exited with 1.
```

**Comment by lemzwerg** [comment]
@cherusker This 32bit stuff might be interesting for you, too :-)

**Comment by Dor1s** [comment]
Looks like there is some implicit pointer conversion which our build config doesn't like:

```
[ 37%] Building CXX object src/targets/CMakeFiles/fuzztargets.dir/__/utils/utils.cpp.o
/src/freetype2-testing/fuzzing/src/utils/tarreader.cpp:77:13: error: no matching function for call to 'archive_read_data_block'
        r = archive_read_data_block( archive.get(),
            ^~~~~~~~~~~~~~~~~~~~~~~
/src/freetype2-testing/fuzzing/../external/libarchive/libarchive/archive.h:601:15: note: candidate function not viable: no known conversion from 'off_t *' (aka 'long *') to 'la_int64_t *' (aka 'long long *') for 4th argument
__LA_DECL int archive_read_data_block(struct archive *a,
              ^
1 error generated.
src/targets/CMakeFiles/fuzztargets.dir/build.make:1118: recipe for target 'src/targets/CMakeFiles/fuzztargets.dir/__/utils/tarreader.cpp.o' failed
```

**Comment by lemzwerg** [comment]
@cherusker Armin?  Could you comment this, please?

**Comment by cherusker** [comment]
Hi guys, sorry for the late reply from my side, I'll have a look at this!

**Comment by cherusker** [comment]
Hope this resolves the issue: https://github.com/freetype/freetype2-testing/pull/85/files

**Comment by Dor1s** [comment]
Thanks! Re-running Travis.

**Comment by cherusker** [comment]
> Thanks! Re-running Travis.

Cool so that seems fixed, next are the external dependecies :disappointed:

**Comment by jonathanmetzman** [comment]
I don't think this PR is going to be landed. If we want 32 bit cov for freetype we can reopen this PR or make a new one.

**Pull request closed without merging**
