### PR TITLE
Runner without go

### PR DESCRIPTION
**Pull request by catenacyber**
For #8701 cc @jonathanmetzman

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
Ths fails to build in CI

**Comment by catenacyber** [comment]
Indeed, quick without test was not good enough.
Looks better with latest commit ;-)

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Comment by catenacyber** [comment]
Do you have a failing log ?

**Comment by jonathanmetzman** [comment]
I think all of the failure was flake.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
