### PR TITLE
sound-open-firmware: add Flavio to additional CCs

### PR DESCRIPTION
**Pull request by mengdonglin**
Add Flavio Ceolin from Intel.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@cujomalainey do you approve?

**Review by cujomalainey — APPROVED** [review]
Addition LGTM.

@mengdonglin can we also remove Harsha since she is no longer at Intel and anyone else no longer associated with the project? Only person I am unsure of is Adrian.

**Review by lgirdwood — APPROVED** [review]

**Comment by lgirdwood** [comment]
@abonislawski will need you here too. Can you send a PR @mwasko fyi.

**Comment by cujomalainey** [comment]
If @abonislawski is still active then I think we just need to remove Harsha then this change is good. Thanks @lgirdwood

**Comment by mengdonglin** [comment]
@lgirdwood @cujomalainey @mwasko Please review https://github.com/google/oss-fuzz/pull/10662 that add Flavio and remove Harsha.  And Adrian (@abonislawski ) is already in the extra cc list :)

**Comment by cujomalainey** [comment]
@mengdonglin I think you might have pushed the wrong thing, there is no diff

**Comment by mengdonglin** [comment]
> @mengdonglin I think you might have pushed the wrong thing, there is no diff

@cujomalainey Sorry. I did something wrong. Can you please check if https://github.com/google/oss-fuzz/pull/10662 looks good?

**Comment by cujomalainey** [comment]
> > @mengdonglin I think you might have pushed the wrong thing, there is no diff
> 
> @cujomalainey Sorry. I did something wrong. Can you please check if https://github.com/google/oss-fuzz/pull/10662 looks good? 

Approved thank you :)

**Pull request closed without merging**
