### PR TITLE
Adds java/jvm gson project

### PR DESCRIPTION
**Pull request by catenacyber**
@inder123 would you be interested in continuous fuzzing with oss-fuzz for gson ?
This Pull Request enables it with a simple target using `fromJson`

### CODE REVIEW

**Comment by catenacyber** [comment]
cc @eamonnmcmanus would you be interested in oss-fuzz for gson ?

**Comment by Marcono1234** [comment]
Might have been superseded by #6742

However, the current implementation does not seem to be completely identical. This pull request here seems to include a specific JSON corpus. Should this be integrated into the current Gson setup?

(Though maybe I am misunderstand this; I am not very familiar with this project)

**Comment by eamonnmcmanus** [comment]
I'm going to assume that this has indeed been superseded by #6742. If there are things in this PR that that one doesn't have then please make a new PR to add those things.

**Comment by DavidKorczynski** [comment]
Hi all! Unfortunately I didn't get to see this one before my PR, apologies!

**Pull request closed without merging**
