### PR TITLE
[astc-encoder] Temporarily disable astc_encode_decode_ise_fuzzer.

### PR DESCRIPTION
**Pull request by Dor1s**
@alsophian @solidpixel

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]
Upto you, we can even remove the astc_encode_decode_ise_fuzzer.cc altogether as well. Does this seem fixable.

**Comment by Dor1s** [comment]
Oops, forgot to mention that this was requested in https://github.com/google/oss-fuzz/issues/4481

@solidpixel does that target seem useful in general? after you suppress `astcenc` code paths?

**Comment by solidpixel** [comment]
@Dor1s In it's current format, I don't think that this particular fuzz target is that useful. 

For the compressor path , `symbolic_to_physical()`, the symbolic data that goes into `encode_ise()` is built by the application itself, so is basically trusted data.

For the decompressor path the data is untrusted - it comes from user input - , but the `decode_ise()` function that's currently fuzzed is really too far down the call hierarchy. Most of the validation for bad input is handled in the function above it `physical_to_symbolic()`; we don't expect `decode_ise()` itself to be robust to bad input.

**Comment by Dor1s** [comment]
@solidpixel should we delete it then, as @inferno-chromium suggested?

**Comment by solidpixel** [comment]
I'm working on a fuzz target based on fuzzing directly into `physical_to_symbolic()` - will either need to work out how we can contribute, or how we start hosting the fuzz test source in our repo.

**Comment by solidpixel** [comment]
@Dor1s Yes, happy for these to get deleted.

**Comment by alsophian** [comment]
@solidpixel I'm happy to help implement that fuzzer, either here in OSS-Fuzz or directly in the astc-encoder repo.

**Pull request merged**
