### PR TITLE
base-runner: refine python's summary.json

### PR DESCRIPTION
**Pull request by DavidKorczynski**
- Fix up so the dictionary follows the right structure using a list rather than a dictionary.
- Adds some of the statics corresponding to the stats given by summary.json for C/C++ targets, namely the line coverage stats.
- Sets some stat fields to 0 to have the same keys as C/C++ targets, but where we don't have the data for Python projects.

Fixes: https://github.com/google/clusterfuzz/issues/2971

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
The error looks unrelated to this PR?

**Review by jonathanmetzman — APPROVED** [review]
lgtm.
Thanks!

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
