### PR TITLE
mongodb: adds main mongodb project and libmongocrypt

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Adds fuzzing of the core `mongodb` project and also another mongodb repository `libmongocrypt`

This is almost ready to merge but waiting for upstream to confirm they are interested in having the central `mongodb` project integrated.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
> Adds fuzzing of the core `mongodb` project and also another mongodb repository `libmongocrypt`
> 
> This is almost ready to merge but waiting for upstream to confirm they are interested in having the central `mongodb` project integrated.

Great! Pretty excited to have mongodb in OSS-Fuzz. Might want to clean up those comments (/remove) once they confirm.

**Comment by DavidKorczynski** [comment]
> > Adds fuzzing of the core `mongodb` project and also another mongodb repository `libmongocrypt`
> > This is almost ready to merge but waiting for upstream to confirm they are interested in having the central `mongodb` project integrated.
> 
> Great! Pretty excited to have mongodb in OSS-Fuzz. Might want to clean up those comments (/remove) once they confirm.

Awesome - sounds good, will clean up and make it nice when things are ready. I am just confirming with the MongoDB people that they would like to have the core project fuzzed.

**Comment by DavidKorczynski** [comment]
@kevinAlbs for reference

**Comment by DavidKorczynski** [comment]
Am closing this PR due to the SSPL license of MongoDB. For reference, see this PR: https://github.com/google/oss-fuzz/pull/4968

Tagging @kevinAlbs

**Pull request closed without merging**
