### PR TITLE
Remove radare2 project as it is unmaintained.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by Dor1s** [comment]
Sad, radare2 is an interesting target. Let me try pinging more folks about it.

**Comment by XVilka** [comment]
FYI @radareorg

**Comment by inferno-chromium** [comment]
ping @radare @radareorg, would appreciate if you can respond and fix the build failure. otherwise, we would consider the project unmaintained (last three months) and remove it.

**Comment by radare** [comment]
Zlowram is the one who did this setup and he told me that he will come back to maintain it soon. I was waiting for his response in here. Ill ping him again.

Also in the #radare channel a couple of volunteers proposed to maintain it. But seems like no one showed up yet.

I would like to keep it and i dont see why it is failing right now but having it integrated in our ci badges would be helpful to avoid such issues again for that long time

**Comment by inferno-chromium** [comment]
Closing this PR then. Thanks @radare , look forward to build fix.

**Pull request closed without merging**
