### PR TITLE
[centipede] Turn off warnings during compilation.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Related: https://github.com/google/oss-fuzz/issues/9299

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address none --fuzzing-engine centipede

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address none --fuzzing-engine centipede

**Review by Alan32Liu — APPROVED** [review]
Thanks!

**Comment by jonathanmetzman** [comment]
Gonna wait until 2023 to merge this.

**Pull request merged**
