### PR TITLE
Enable jitting in pcre2

### PR DESCRIPTION
**Pull request by addisoncrump**
This corresponds to an issue on PCRE2 regarding fuzzer improvements w.r.t. JIT: https://github.com/PCRE2Project/pcre2/pull/317

### CODE REVIEW

**Comment by addisoncrump** [comment]
The linked PR has now been merged, so this should be ready to go. CI should probably be re-run as the latest changes from upstream need to be tested.

**Review by PhilipHazel — APPROVED** [review]

**Comment by addisoncrump** [comment]
There was an issue in the original PR. Please wait before merging! :)

**Comment by addisoncrump** [comment]
Blocked by https://github.com/PCRE2Project/pcre2/pull/322 which should be merged relatively soon.

**Comment by addisoncrump** [comment]
Upstream has updated, can this PR be evaluated?

**Comment by addisoncrump** [comment]
Build failures are due to known abort()s in the fuzzer target. I can temporarily disable these, or put them behind a build flag for now.

**Comment by PhilipHazel** [comment]
This pull request looks OK to me.

**Review by PhilipHazel — APPROVED** [review]
These changes seem fine.

**Comment by addisoncrump** [comment]
Pipeline should be fully re-evaluated as upstream has been fixed to address the checks.

**Comment by DavidKorczynski** [comment]
> Apologies for the issue. It seems my local brace expansion differs from CI; I have made this explicit, so this should now work as expected.

Restarted the CI

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
