### PR TITLE
Uses cmake for ecc-diff-fuzzer compilation

### PR DESCRIPTION
**Pull request by catenacyber**

### CODE REVIEW

**Comment by catenacyber** [comment]
CI should pass with latest commit to project : https://github.com/catenacyber/elliptic-curve-differential-fuzzer/commit/bc7de67f7651f6d0383d4371013fac50f82347af

**Comment by catenacyber** [comment]
One job fails because 
"The job exceeded the maximum log length, and has been terminated."
Wha should I do about this ?

The other failure should be fixed by https://github.com/catenacyber/elliptic-curve-differential-fuzzer/commit/19df151c0a35397e653f4d3ebc19d4faa30380e9

**Comment by Dor1s** [comment]
> One job fails because
> "The job exceeded the maximum log length, and has been terminated."
> Wha should I do about this ?

Will ignore it, re-running again to check the other fix

**Comment by jonathanmetzman** [comment]
The log length bug was hit again in the ubsan build but I think there's a genuine crash in i386

**Comment by catenacyber** [comment]
Indeed, I will try to debug this...

**Comment by catenacyber** [comment]
Finally it works except for the log length bug.
What's to do ?

**Pull request merged**
