### PR TITLE
infra: build: functions: cut corpus directory by last period

### PR DESCRIPTION
**Pull request by DavidKorczynski**
When a corpus zip file is unzipped the destination folder is set to be the directory corresponding to the filepath of the zip file but without ".zip" in the name. This is achieved by `for f in /corpus/*.zip; do unzip -q $f -d ${f%%.*}` where `f%%.*` substitutes the path of `f` based on the first occurrence of ".". This causes some issues with fuzztest fuzzers where a fuzzer name always has a "." in it, e.g.
`escaping_test@EscapingTest.EscapingAStringNeverTriggersUndefinedBehavior`

Substituting the name in this way causes issues for some coverage builds e.g.
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=53479

This changes it to substiute based on the last occurrence of ".", i.e. just cutting off the ".zip".

Alternatively, we could substitute over
e.g. ".zip", however, this may cause some issues as a fuzztest fuzzer may have ".zip" in the name.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
What do you think of waiting to merge this? Half of us are on vacation until next tuesday. The other half of us are only working half of that time ;-)

**Comment by DavidKorczynski** [comment]
> What do you think of waiting to merge this? Half of us are on vacation until next tuesday. The other half of us are only working half of that time ;-)

Am happy with waiting -- this effectively hurts no customers at the moment so rush in that sense.

**Comment by Alan32Liu** [comment]
The new substitution expression looks alright to me (thanks for the explanation!), but let's wait in case I missed anything : )

**Comment by DavidKorczynski** [comment]
Hope all enjoyed the holidays :-)! Are we ready to merge this?

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
> /gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

Let's just check it doesn't mess things up with trial build. If everything goes well, in six hours there will be a few spurious failures. If I can confirm theyre spurious we can land thsi.

**Comment by DavidKorczynski** [comment]
@jonathanmetzman I just noticed the infra test is failing since I didn't update this line: https://github.com/google/oss-fuzz/blob/11a21c2b6ab610ef4773cddb940dbd97cf7fb3e0/infra/build/functions/test_data/expected_coverage_build_steps.json#L90

Should I update this now or wait ~6 hours until the trial has finished?

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman I just noticed the infra test is failing since I didn't update this line:
> 
> https://github.com/google/oss-fuzz/blob/11a21c2b6ab610ef4773cddb940dbd97cf7fb3e0/infra/build/functions/test_data/expected_coverage_build_steps.json#L90
> 
> Should I update this now or wait ~6 hours until the trial has finished?

Update now. I will stop the current run.

**Comment by DavidKorczynski** [comment]
I'm confused now, since I actually did change it but the CI seems to report it's not changed.

**Comment by DavidKorczynski** [comment]
> I'm confused now, since I actually did change it but the CI seems to report it's not changed.

I was missing another `%` in the json file. Infra tests should pass now

**Comment by DavidKorczynski** [comment]
@jonathanmetzman -- all tests except trial run are passing now

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms fuzztest-rashka --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py all --sanitizer coverage --fuzzing-engine libfuzzer

**Review by Alan32Liu — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
I don't think I meant to merge this. I need to turn off automerge more often.

**Comment by DavidKorczynski** [comment]
> I don't think I meant to merge this. I need to turn off automerge more often.

Does this impact deployment? i.e. should I expect these changes to be deployed in the next 24 hours or so?

**Comment by DavidKorczynski** [comment]
@jonathanmetzman @Alan32Liu has this been deployed?

**Comment by jonathanmetzman** [comment]
Probably not. Let me do a deploy monday. Sorry.

**Comment by DavidKorczynski** [comment]
> Probably not. Let me do a deploy monday. Sorry.

np! Let me know when it has been deployed and I'll check if the issue this PR aims to fix has been resolved

**Comment by DavidKorczynski** [comment]
> Deployed

Awesome, can confirm the issue is resolved -- the Fuzztest projects are now producing correct code coverage reporting! https://storage.googleapis.com/oss-fuzz-coverage/fuzztest-raksha/reports/20230110/linux/proc/self/cwd/src/ir/datalog/value_test.cc.html 

Thanks a lot!

**Pull request merged**
