### PR TITLE
grok: change location of test data, to make CIFuzz happy

### PR DESCRIPTION
**Pull request by boxerab**

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM.
Though I imagine OSS-Fuzz's CI will fail until you update things in the script in grok.

**Comment by jonathanmetzman** [comment]
Let me know if you want me to merge this in spite of OSS-Fuzz's CI failing.
Otherwise, let me know when I should rerun it.

**Comment by boxerab** [comment]
> Let me know if you want me to merge this in spite of OSS-Fuzz's CI failing.
> Otherwise, let me know when I should rerun it.

Yes, please merge this :)

**Comment by boxerab** [comment]
btw, I just pushed the changes to Grok repo.

**Comment by boxerab** [comment]
thanks !

**Comment by jonathanmetzman** [comment]
Image is done rebuilding. CIFuzz should reflect this change now.

**Comment by boxerab** [comment]
yay!! working now

**Pull request merged**
