### PR TITLE
[imagemagick] build for i386

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
Hmm, it seems unable to find `libm` in the i386 build -- libm is part of the C standard library, which I sort of assumed was pre-compiled for i386. Is there a package I need to be installing with `apt-get` for it?

**Comment by alex** [comment]
Gentle ping: Does anyone know what the right package for i386 libm is?

**Comment by inferno-chromium** [comment]
No clue.

**Comment by alex** [comment]
Ok, seems to be working now. Should be good to review/land.

**Pull request merged**
