### PR TITLE
[zxing] Initial Integration

### PR DESCRIPTION
**Pull request by 0roman**
@srowen https://github.com/zxing/zxing/issues/1409

### CODE REVIEW

**Comment by srowen** [comment]
I was one of the primary developers; I don't have a strong need for the fuzzing but think it would be reasonable to add.

The main consumer of the project is the "Barcode Scanner" app on Android, which has tens of millions of users.
FWIW there are 28.1K stars on Github. And FWIW this was a Google OSS project originally.

**Comment by fmeum** [comment]
@asraa Friendly ping. Let me know if you require more information.

**Comment by inferno-chromium** [comment]
> I was one of the primary developers; I don't have a strong need for the fuzzing but think it would be reasonable to add.
> 
> The main consumer of the project is the "Barcode Scanner" app on Android, which has tens of millions of users.
> FWIW there are 28.1K stars on Github. And FWIW this was a Google OSS project originally.

Is the project in maintenance mode ? We prefer to add only active projects in OSS-Fuzz.

**Comment by srowen** [comment]
It is, not much is changing - yes that's a good reason not to add it, that's fine too

**Comment by TheLastProject** [comment]
As a downstream user of xzing, my feeling is that the way zxing uses the phrase "maintenance mode" is different from how many others use it.

In zxing it seems to mean: the main developers no longer write new features, but new features made by third parties in the form of merge requests are still welcomed.

So, to me, this project is still what I would personally consider "active", just a bit more hands-off than most other projects.

Of course, I am not the project owner, so my opinion clearly matters less, but as one of the downstream users of this great library, I would definitely be interested in seeing this library get security tests by fuzzing.

**Pull request merged**
