### PR TITLE
Added a seed corpus to libarchive fuzzer

### PR DESCRIPTION
**Pull request by AdamKorcz**
Coverage gains!

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@mmatuska - can you please review and also do you approve of having @AdamKorcz added to libfuzzer maintainers list / bugs.

**Comment by Dor1s** [comment]
@mmatuska ping :)

**Comment by AdamKorcz** [comment]
If it helps with getting the PR merged, I will be glad to remove my email address from the maintainers list.

**Comment by mmatuska** [comment]
@inferno-chromium I agree tho the the functional changes, especially adding additional library support. AdamKorcz is not a member of the libarchive project. What are the implications of having AdamKorcz in the auto-cc?

**Comment by AdamKorcz** [comment]
@mmatuska The implications of me being on the list is that I will be able to view old and new bug-reports, and I will receive e-mails whenever a bug is found.
I added myself to the cc-list because I would like to further work on fuzzing Libarchive, and monitoring the improvements of the bugs over time would help me in that regards.
In either case, I removed my e-mail address from the cc-list, and I am glad that the added corpus benefits the efforts of OSS-fuzz.

**Pull request merged**
