### PR TITLE
Update Pillow contact email

### PR DESCRIPTION
**Pull request by hugovk**
I'm a maintainer of the Pillow project, we'd like the notifications to go through Tidelift.

cc @DavidKorczynski @aclark4life

Thanks!

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@DavidKorczynski do you approve?

**Comment by DavidKorczynski** [comment]
Yes, looks good. 

For future references @hugovk is one of the core maintainers of Pillow and so if future emails will be put on/removed by @hugovk  I would assume it's all good.

**Comment by jonathanmetzman** [comment]
> Yes, looks good.
> 
> For future references @hugovk is one of the core maintainers of Pillow and so if future emails will be put on/removed by @hugovk I would assume it's all good.

Thanks!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
