### PR TITLE
[cryptofuzz, bignum-fuzzer] Fix AFL++ builds

### PR DESCRIPTION
**Pull request by guidovranken**
Build Golang with regular clang.

For instrumentation it doesn't matter because this is the Golang compiler, which isn't part of the output binaries.

### CODE REVIEW

**Review by inferno-chromium — CHANGES_REQUESTED** [review]
So golang is already installed in base-builder now [https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L67], maybe time now to actually remove this dependency completely from Dockerfile and build.sh

**Comment by guidovranken** [comment]
I've removed Golang from the build scripts. This assumes that the base image is refreshed daily with the latest Golang (from the master branch, not the latest stable release). If this is not the case, let me know and I'll revert this commit.

Interestingly, bignum-fuzzer and Cryptofuzz builds succeeded today.

**Comment by inferno-chromium** [comment]
> I've removed Golang from the build scripts. This assumes that the base image is refreshed daily with the latest Golang (from the master branch, not the latest stable release). If this is not the case, let me know and I'll revert this commit.
> 
> Interestingly, bignum-fuzzer and Cryptofuzz builds succeeded today.

yes if it succeeded, we can close this. we install go stable through https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-builder/Dockerfile#L69, so if you want nightly, then can keep as-is.

**Comment by guidovranken** [comment]
@inferno-chromium 

I ran `infra/helper.py check_build cryptofuzz` locally and this is what I get.

```sh
/tmp/not-out/cryptofuzz-openssl
BAD BUILD: /tmp/not-out/cryptofuzz-openssl seems to have either startup crash or exit:
/tmp/not-out/cryptofuzz-openssl -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 -dict=cryptofuzz-openssl.dict < /dev/null
Warning: AFL++ tools will need to set AFL_MAP_SIZE to 214816 to be able to run this instrumented program!
Running LLVMFuzzerInitialize ...
continue...
======================= INFO =========================
This binary is built for afl++.
To run the target function on individual input(s) execute this:
  /tmp/not-out/cryptofuzz-openssl INPUT_FILE1 [INPUT_FILE2 ... ]
To fuzz with afl-fuzz execute this:
  afl-fuzz [afl-flags] -- /tmp/not-out/cryptofuzz-openssl [-N]
afl-fuzz will run N iterations before re-spawning the process (default: 1000)
======================================================
```

That doesn't look like a bug with my build script but with `afl++` not getting called properly by `helper.py`?

**Comment by inferno-chromium** [comment]
You need to add --engine afl in check_build command

**Comment by guidovranken** [comment]
check_build works fine locally. Retriggering CI..

**Comment by guidovranken** [comment]
It passed, you can merge if you want.

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
