### PR TITLE
java projects: switch Maven link to permalink to fix build issues

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Comment by Marcono1234** [comment]
Might be good to mention "Maven" here somewhere (ideally in the pull request description, and commit messages), because it is apparently not mentioned here anywhere yet.

**Comment by DavidKorczynski** [comment]
> Might be good to mention "Maven" here somewhere (ideally in the pull request description, and commit messages), because it is apparently not mentioned here anywhere yet.

Good idea, thanks.

**Review by AdamKorcz — APPROVED** [review]

**Comment by Marcono1234** [comment]
Another solution might be to use https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven, that appears to be what the official Maven Wrapper [is using](https://github.com/apache/maven-wrapper/blob/2a0a17c8cc273c0aa63d181ce1968fa2dcedf21f/maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java#L65), so these URLs should be stable.
(I don't know though whether there are any mirrors in place and it is therefore necessary to verify the checksum)

Also thanks for fixing this!

**Review by AdamKorcz — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
@jonathanmetzman could you take a look at this one?  It will fix a couple of java projects build failures but can't merge due to the cancelled CI action.

**Comment by DavidKorczynski** [comment]
> that appears to be what the official Maven Wrapper [is using](https://github.com/apache/maven-wrapper/blob/2a0a17c8cc273c0aa63d181ce1968fa2dcedf21f/maven-wrapper-plugin/src/main/java/org/apache/maven/plugins/wrapper/WrapperMojo.java#L65)

Fair point I think -- I'm not opinionated in this context because I don't know much about Maven infra as such. I mainly did this due to the previous PR that relied on the same link https://github.com/google/oss-fuzz/pull/9335

That said, if you prefer to have something specific in gson (if I remember correctly you're involved in this project) please do submit a PR and am happy to get that in.

**Pull request merged**
