### PR TITLE
infra: bump fuzz-introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
This adds a feature where multiple focus functions are output by fuzz-introspector (https://github.com/ossf/fuzz-introspector/pull/252). 

Can confirm the fuzz-introspector oss-fuzz integration tests (https://github.com/ossf/fuzz-introspector/tree/main/oss_fuzz_integration#testing-before-bumping-oss-fuzz) pass.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by DavidKorczynski** [comment]
converting this to to draft as it would be nice to have one more update included from fuzz-introspector (https://github.com/ossf/fuzz-introspector/pull/252#issuecomment-1122651603). Will undraft and update commit once it's done

**Comment by DavidKorczynski** [comment]
Depends on https://github.com/ossf/fuzz-introspector/pull/253

**Review by Navidem — APPROVED** [review]
LGTM

**Pull request merged**
