### PR TITLE
[netaddr] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
This PR adds initial integration of [netaddr](https://github.com/inetaf/netaddr) which is used in production by [Tailscale](https://tailscale.com/).

@josharian Would you mind sharing the email addresses that can be used for bug reports for this project?

### CODE REVIEW

**Comment by josharian** [comment]
`{josh,danderson,bradfitz}@tailscale.com` please. @mdlayher may also want to be on the list.

**Comment by mdlayher** [comment]
Sure, mdlayher@gmail.com for me.

**Comment by AdamKorcz** [comment]
@inferno-chromium @jonathanmetzman @oliverchang Ready for review.

**Comment by oliverchang** [comment]
Hi, are there any other big users of this package apart from tailscale? There doesn't seem to be many large projects according to https://pkg.go.dev/inet.af/netaddr?tab=importedby

**Comment by josharian** [comment]
No other large projects using it that I am aware of. However, Brad's going to be giving a talk about it at FOSDEM shortly, so that may change soon. :)

**Comment by AdamKorcz** [comment]
> No other large projects using it that I am aware of. However, Brad's going to be giving a talk about it at FOSDEM shortly, so that may change soon. :)

Perhaps mentioning that the project is being fuzzed continuously through OSS-fuzz could also help in that regards :)

**Comment by oliverchang** [comment]
Thanks for explaining. Unfortunately we need to prioritise more heavily used and critical projects at this point. However perhaps recent/upcoming changes to CIFuzz would help provide fuzzing coverage here -- will keep you posted! 

@jonathanmetzman FYI for a potential test user :)

**Pull request closed without merging**
