### PR TITLE
Use base-builder-go-codeintelligencetesting for all go projects

### PR DESCRIPTION
**Pull request by 0roman**

### CODE REVIEW

**Comment by 0roman** [comment]
https://github.com/google/oss-fuzz/issues/7164

**Comment by jonathanmetzman** [comment]
Why not just move these patches into base-builder-go rather than change every go project's Dockerfile and then change it back?

**Comment by oliverchang** [comment]
Sorry for the delay here! Could you please take a look at the failures in https://github.com/google/oss-fuzz/runs/5250301540 ? 

The point of having a separate image was to have a more controlled rollout/experiment to prevent widespread issues (like possibly the one found by the CI) -- could you please pick say 10-20 projects to convert to this to the experimental image rather than do all of them?

**Comment by 0roman** [comment]
I will have a look at the failures. I will prepare a new pull request with a rollout to 10-20 go projects

**Comment by 0roman** [comment]
@oliverchang we fixed the issue. I will close this pull request and create new one for 15 projects.

**Pull request closed without merging**
