### PR TITLE
rauc: initial integration

### PR DESCRIPTION
**Pull request by jluebbe**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Let me know the answers to these questions so i can ask the committee to approve this project.
Who uses rauc? Why is it critical software?

**Comment by jluebbe** [comment]
> Who uses rauc?

RAUC is a system update tool, primarily for embedded systems. It is used by device manufacturers and system integrators. Some publicly known users are:

- [Valve Steam Deck](https://steamdeck-images.steamos.cloud/steamdeck/20230901.1/)
- [IKEA DIRIGERA](https://github.com/ikea-oss-distributions/DIRIGERA-hub/tree/v2.354.000/rauc-1.4-r0)
- [CESNET velia](https://github.com/CESNET/velia#system-management)
- [Eclipse SDV Leda](https://eclipse-leda.github.io/leda/docs/device-provisioning/self-update/rauc-integration/)
- [Home Assistant OS](https://github.com/home-assistant/operating-system/tree/dev/buildroot-external/ota)
- [DB Systel Linux4ICE passenger info displays](https://chemnitzer.linux-tage.de/2023/media/programm/folien/121.pdf)

> Why is it critical software?

As a system updater, it necessarily has full root privileges and is an attractive target for attacks. Accordingly secure authentication of the update payload is critical.

**Comment by jonathanmetzman** [comment]
> > Who uses rauc?
> 
> RAUC is a system update tool, primarily for embedded systems. It is used by device manufacturers and system integrators. Some publicly known users are:
> 
> * [Valve Steam Deck](https://steamdeck-images.steamos.cloud/steamdeck/20230901.1/)
> * [IKEA DIRIGERA hub](https://github.com/ikea-oss-distributions/DIRIGERA-hub/tree/v2.354.000/rauc-1.4-r0)
> * [CESNET velia](https://github.com/CESNET/velia#system-management)
> * [Eclipse SDV Leda](https://eclipse-leda.github.io/leda/docs/device-provisioning/self-update/rauc-integration/)
> * [Home Assistant OS](https://github.com/home-assistant/operating-system/tree/dev/buildroot-external/ota)
> * [DB Systel Linux4ICE passenger info displays](https://chemnitzer.linux-tage.de/2023/media/programm/folien/121.pdf)
> 
> > Why is it critical software?
> 
> As a system updater, it necessarily has full root privileges and is an attractive target for attacks. Accordingly, secure authentication of the update payload is critical.

Cool. Asking the committee

**Comment by jonathanmetzman** [comment]
We are glad to have rauc, we accept.

I think youre building the UBSAN build with ASAN:
```
('/tmp/not-out/tmpi1pzigzf/manifest_fuzzer', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmpi1pzigzf/manifest_fuzzer'], returncode=1, stdout=b'BAD BUILD: UBSan build of /tmp/not-out/tmpi1pzigzf/manifest_fuzzer seems to be compiled with ASan.\n', stderr=b''))
BAD BUILD: UBSan build of /tmp/not-out/tmpi1pzigzf/manifest_fuzzer seems to be compiled with ASan.

('/tmp/not-out/tmpi1pzigzf/bundle_fuzzer', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmpi1pzigzf/bundle_fuzzer'], returncode=1, stdout=b'BAD BUILD: UBSan build of /tmp/not-out/tmpi1pzigzf/bundle_fuzzer seems to be compiled with ASan.\n', stderr=b''))
BAD BUILD: UBSan build of /tmp/not-out/tmpi1pzigzf/bundle_fuzzer seems to be compiled with ASan.
```
Can you fix this issue? THen we will merge

**Comment by jluebbe** [comment]
@jonathanmetzman With https://github.com/rauc/rauc/pull/1247 I should have fixed the UBSAN issue.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jluebbe** [comment]
@jonathanmetzman It seems to me that the fuzzing has not started yet, while from the documentation it sounds like it should start working after one or two days.

https://introspector.oss-fuzz.com/indexing-overview reports failed coverage and inspector builds:

https://oss-fuzz-build-logs.storage.googleapis.com/log-045a10f6-2eeb-4ed8-ae48-b5a4c3116b7f.txt

> Step #5: unzip:  cannot find zipfile directory in one of /corpus/bundle_fuzzer.zip or
Step #5:         /corpus/bundle_fuzzer.zip.zip, and cannot find /corpus/bundle_fuzzer.zip.ZIP, period.
Step #5: Failed to unpack the corpus for bundle_fuzzer. This usually means that corpus backup for a particular fuzz target does not exist. If a fuzz target was added in the last 24 hours, please wait one more day. Otherwise, something is wrong with the fuzz target or the infrastructure, and corpus pruning task does not finish successfully.

Also, https://oss-fuzz.com/ reports "Access Denied" for both jluebbe@lasnet.de and jlu@pengutronix.de.

Is something going wrong or should I just wait some more? :)

**Pull request merged**
