### PR TITLE
Request access for the slint project (http://slint-ui.com/)

### PR DESCRIPTION
**Pull request by hunger**
Request access for the slint project. It would be cool if we could fuzz our compiler!

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Could talk a bit about who are the clients of slint to provide some perspective of what makes it a critical open source project?

Also, am not sure you're aware, adding a `project.yaml` won't enable fuzzing: you will have provide `Dockerfile` and `build.sh` and fuzzers for OSS-Fuzz to start working properly.

**Comment by hunger** [comment]
Yes, I am aware that more is needed, but I understood your documentation to require that I start by getting the project.yaml reviewed first, so that you can decide whether it makes sense for our little project to be part of OSS-fuzz or not.

Slint is a UI toolkit written in rust -- which obviously works well for rust projects and has convenient bindings to C++ and JS as well. The code is dual license (GPL or commercial). This is great as we have a few customers in (mostly in the telecommunications sector) that allow us to finance a small but growing team working on the code full time. So we do make constant progress.

Are we mission critical? I have to admit that we are probably not. A few open source projects are using Slint e.g. in [imagesieve](https://github.com/Futsch1/image-sieve), [moire](https://codeberg.org/Be.ing/moire), but none of these are critical to the wider software stack. Our customers are of course also preparing products built with Slint, but I am not sure how that factors into OSS-fuzz. I think we do have a lot of potential going forward though: Rust is such a damn efficient language! We do have a nice little demo running on a [Raspberry pi pico](https://slint-ui.com/thisweek/2022-03-14.html) with 264KiB of RAM and a screen connected via SPI. There are not that many other free software options that can cover such small hardware. But I am of course heavily biased!

Slint uses a compiler to turn a UI description into native code for rust/C++ and (in a limited way) Javascript. This approach lends itself very well to fuzzing: Running our existing fuzzers on my little laptop has found a couple of stupid bugs in the parser/lexer already.

**Comment by DavidKorczynski** [comment]
> Yes, I am aware that more is needed, but I understood your documentation to require that I start by getting the project.yaml reviewed first, so that you can decide whether it makes sense for our little project to be part of OSS-fuzz or not.

Thanks -- you're entirely correct I just wanted to double check.

Thanks for the description of customers! could you perhaps mention the names of a few of the telecommunication customers or is this non-public?

**Comment by hunger** [comment]
Sorry, I am not free to discuss customers in a public forum.

**Comment by DavidKorczynski** [comment]
Thanks @hunger!

@jonathanmetzman this one is ready for review by the board.

**Comment by jonathanmetzman** [comment]
Since this project is not mission critical, maybe [ClusterFuzzLite](https://google.github.io/clusterfuzzlite) would be a better option? Let me know if you'd like help setting it up

**Comment by hunger** [comment]
@jonathanmetzman oh, thanks for the hint, I'll definitely look into that!

**Comment by jonathanmetzman** [comment]
Sure. Please reach out to me (even by email: metzman at google.com) if you have any questions

**Pull request closed without merging**
