### PR TITLE
Upgrade cmake to latest release (3.19.2)

### PR DESCRIPTION
**Pull request by rlohning**

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]
LGTM.

PR in draft state, is it ready to merge ?

**Comment by rlohning** [comment]
I think so.

**Comment by rlohning** [comment]
This has been in for a week now but still my build script reports to find cmake 3.18: https://oss-fuzz-build-logs.storage.googleapis.com/log-24cf6535-a51e-42cc-8a53-713bda85cec4.txt

Did I upgrade the wrong thing or does this still need some kind of rebuild?

**Comment by inferno-chromium** [comment]
This is breaking base-clang build

```
-- Looking for os_signpost_interval_begin - not found
CMake Error at /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
  Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter)
Call Stack (most recent call first):
  /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.19/Modules/FindPython/Support.cmake:3148 (find_package_handle_standard_args)
  /usr/local/share/cmake-3.19/Modules/FindPython3.cmake:398 (include)
  CMakeLists.txt:711 (find_package)


-- Configuring incomplete, errors occurred!
See also "/work/llvm-stage1/CMakeFiles/CMakeOutput.log".
See also "/work/llvm-stage1/CMakeFiles/CMakeError.log".
The command '/bin/sh -c /root/checkout_build_install_llvm.sh' returned a non-zero code: 1
```

I will revert for now.
Locally, try building
```
python infra/helper.py build_image base-clang
python infra/helper.py build_image base-builder
```
to reproduce this issue.

**Comment by inferno-chromium** [comment]
> This is breaking base-clang build
> 
> ```
> -- Looking for os_signpost_interval_begin - not found
> CMake Error at /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:218 (message):
>   Could NOT find Python3 (missing: Python3_EXECUTABLE Interpreter)
> Call Stack (most recent call first):
>   /usr/local/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:582 (_FPHSA_FAILURE_MESSAGE)
>   /usr/local/share/cmake-3.19/Modules/FindPython/Support.cmake:3148 (find_package_handle_standard_args)
>   /usr/local/share/cmake-3.19/Modules/FindPython3.cmake:398 (include)
>   CMakeLists.txt:711 (find_package)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/work/llvm-stage1/CMakeFiles/CMakeOutput.log".
> See also "/work/llvm-stage1/CMakeFiles/CMakeError.log".
> The command '/bin/sh -c /root/checkout_build_install_llvm.sh' returned a non-zero code: 1
> ```
> 
> I will revert for now.
> Locally, try building with your patch (since revert will be in soon). I wonder why CI didnt fail, but that needs more investigation.
> 
> ```
> python infra/helper.py build_image base-clang
> python infra/helper.py build_image base-builder
> ```
> 
> to reproduce this issue.

Should we move python3 install from base-builder here to base-clang (before cmake install) ?

**Comment by rlohning** [comment]
That wasn't me. "Could NOT find Python3" happens without my change as well.

**Comment by inferno-chromium** [comment]
> That wasn't me. "Could NOT find Python3" happens without my change as well.

Ok, will give it a try today.

**Comment by rlohning** [comment]
Fixed it for me. Thank you!

**Pull request merged**
