### PR TITLE
Link with CXX

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @eustas I think this is why your centipede build fails.

**Comment by jonathanmetzman** [comment]
CC @eustas I think this is why your centipede build fails.

**Comment by jonathanmetzman** [comment]
CC @DavidKorczynski In the future could you link with CXX, we can end up with weird errors otherwise.

**Comment by DavidKorczynski** [comment]
> CC @DavidKorczynski In the future could you link with CXX, we can end up with weird errors otherwise.

Yep, got it.

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
