### PR TITLE
poppler

### PR DESCRIPTION
**Pull request by pdknsk**
The authors [have agreed](https://bugs.freedesktop.org/show_bug.cgi?id=106554). I'll add a corpus once approved.

### CODE REVIEW

**Comment by titanous** [comment]
Looks like we collided :) #1431

**Comment by pdknsk** [comment]
What happens now?

**Comment by titanous** [comment]
I think you can close this PR, I pulled a few build flags in from this one, and everything else looks equivalent in mine with the addition of a corpus/comprehensive dictionary.

**Comment by inferno-chromium** [comment]
Closing as per previous comment.

**Comment by pdknsk** [comment]
Personally I would've preferred a competition. The first fuzzer to find 10 bugs or so wins.

**Comment by inferno-chromium** [comment]
@pdknsk - you should submit an entry for oss-fuzz rewards as well. this came around the same time, so we will try to consider this special case. Looks like @titanous added some flags from your commit, if you have more things to add and you can improve the target even more (please send pull request), this will definitely strengthen the case.

**Pull request closed without merging**
