### PR TITLE
Rename google-cloud-go to gcloud-go.

### PR DESCRIPTION
**Pull request by oliverchang**
google-cloud-go causes issues as "google" is not allowed in bucket
names.

### CODE REVIEW

**Comment by oliverchang** [comment]
@codyoss FYI

**Comment by oliverchang** [comment]
TBR since this is blocking project setup.

**Comment by codyoss** [comment]
@oliverchang Thank you!

**Review by inferno-chromium — COMMENTED** [review]
LGTM

**Pull request merged**
