### PR TITLE
[harfbuzz] Disable enum sanitization

### PR DESCRIPTION
**Pull request by ebraminio**
Behdad apparently not interested on them

### CODE REVIEW

**Comment by ebraminio** [comment]
Hmm, let me close this till more understanding

**Comment by behdad** [comment]
@ebraminio do you remember what this was about?

**Comment by ebraminio** [comment]
> @ebraminio do you remember what this was about?

to prevent file for passing values not in range of enum I remember, but as mentioned was based on incorrect assumptions or something I remember thus closed.

**Comment by behdad** [comment]
> to prevent file for passing values not in range of enum I remember, but as mentioned was based on incorrect assumptions or something I remember thus closed.

Yeah I was wondering how we ended up not needing it. Anyway.

**Pull request closed without merging**
