### PR TITLE
Added a fuzzer for clamav

### PR DESCRIPTION
**Pull request by alex**
Refs #402

One interesting thing about this fuzzer is that I think the most sensible way to fuzz it would be to have multiple distinct corpuses, potentially one per file format it can parse, even though they'll all share the same fuzzer source. Does that make sense to folks? If yes, should I just make a few copies of the binary in `$OUT` with different names and do that?

CCing @micah-at-talos who appears to be one of the ClamAV devs (Hi! I'm not involved in ClamAV itself, but it was an interesting target to fuzz.) It's be great to get the fuzzer source included in the ClamAV upstream.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
CL looks good.

 @micah-at-talos - are you ok with this integration effort. Can you please review the CL as well to see if fuzzer initialized the state correctly and calls api the right way.

**Comment by micah-at-talos** [comment]
Sorry about the delay, I was on vacation and just am getting caught up and getting my mind back in the game. 

Thanks for the CC.  I'll take a look and bring it up with the team.

**Comment by alex** [comment]
@micah-at-talos FWIW, I can tell you from running for a few hours locally that it already finds a few memory leaks and at least one heap-buffer-overflow.

**Comment by micah-at-talos** [comment]
@alex Do you think you could give me an idea how the fuzzer source would integrate?  Would it be like an optional system test that we could run?  I'm assuming the fuzzer is to fuzz libclamav parsing various file formats.  Also, If you would, we would appreciate responsible disclosure if you want to report vulnerabilities to our bugzilla queue (bugzilla.clamav.net).

**Comment by alex** [comment]
@micah-at-talos Sure, so right, in this PR, now all the code lives in the OSS-Fuzz repo including both the fuzzer source and build scripts. https://github.com/ImageMagick/ImageMagick/issues/933 maps out a process for migrating from that configuration to more things living in the upstream repo and build system.

And yes, the fuzzer targets libclamav and the parsers.

If the contents of this PR looks good to you we can get it merged as-is and then gradually migrate the pieces into the clamav repo.

**Comment by alex** [comment]
(I'll report the sec-bug I found upstream shortly)

**Comment by alex** [comment]
@micah-at-talos First batch filed, I may follow up with some more. (It'd be great to get this landed, as OSS-Fuzz automates reports and closing them and verification).

**Comment by inferno-chromium** [comment]
@micah-at-talos - please checkout https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md, this explains why we recommend moving fuzz targets, their corpus, etc into your own repo. Also from @alex efforts, it seems clear that the fuzzer is effective and finding new issues.

**Comment by micah-at-talos** [comment]
Thanks @alex I saw the bugzilla tickets.  We'll take a look at them as soon as we are able.  Thanks @inferno-chromium for passing along the doc.  I'll check that out.

**Comment by Dor1s** [comment]
@alex @micah-at-talos friendly ping. Do you guys want to finish this?

**Comment by micah-at-talos** [comment]
As a heads up, I'm putting together a replacement PR to do oss-fuzz integration w/ ClamAV:
https://github.com/micah-at-talos/oss-fuzz/tree/add-clamav

With supporting changes for the clamav-devel repo, and for a new clamav-fuzz-corpus repo.  Presently staging these in personal repositories here:
https://github.com/micah-at-talos/clamav-devel/tree/fuzz-integration
https://github.com/micah-at-talos/clamav-fuzz-corpus

I think I have everything working correctly.  I'm able to test the fuzzer targets using the instructions here https://github.com/google/oss-fuzz/blob/master/docs/new_project_guide.md#testing-locally.  In addition, `make check` in clamav-devel/fuzz will test the standalone fuzz target, though it presently requires a checkout of clamav-fuzz-corpus next to clamav-devel.

**Comment by alex** [comment]
Great! Happy to see this moving forward.

**Comment by micah-at-talos** [comment]
Sure, I appreciate the work you did to get it started.  Frustrating to fix the bugs within deadlines and such, and I've felt guilty this has been in limbo so long... but overall a good thing for the project.

**Comment by alex** [comment]
I'll go ahead and close this then. Thanks!

**Pull request closed without merging**
