### PR TITLE
[CI] Remove clone step

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms abseil-cpp aiohttp alembic arduinojson --sanitizer address --fuzzing-engine afl

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms abseil-cpp aiohttp alembic arduinojson --sanitizer address --fuzzing-engine afl

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine afl

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine afl

**Comment by jonathanmetzman** [comment]
This fixes in our AFL++ test environment where the base-images were not built using the PR.

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
