### PR TITLE
jsign: initial integration

### PR DESCRIPTION
**Pull request by ebourg**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Can you please sign the CLA?
I've asked our panel to consider adding this project.

**Comment by ebourg** [comment]
> Can you please sign the CLA?

I did on last Monday.

>I've asked our panel to consider adding this project.

Thank you

**Comment by jonathanmetzman** [comment]
> > Can you please sign the CLA?
> 
> I did on last Monday.

I need to debug this then. The check says you didn't sign.

**Comment by oliverchang** [comment]
Looks like CLA is passing now after a re-run. Thanks!

**Review by oliverchang — APPROVED** [review]

**Comment by ebourg** [comment]
Thank you!

**Pull request merged**
