### PR TITLE
infra: bump introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**
The main changes are:
- improvements to code injection sink analyser
- output of data about all functions into summary.json. This is useful for e.g. comparing reports and making historical analysis.

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib aspell zlib yara xpdf glom --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py igraph h2o gpac giflib gnupg hermes harfbuzz hostap kamailio lame curl cups draco dropbear expat file firestore flac flatbuffers fluent-bit freetype speex perfetto opencv openjpeg openbabel ntp nginx mupdf liblouis botan --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by DavidKorczynski** [comment]
Any update on this one @Navidem -- if there were issues in the trial build could you let me know which projects failed?

**Comment by Navidem** [comment]
> Any update on this one @Navidem -- if there were issues in the trial build could you let me know which projects failed?

Yes, actually some projects failed. I will provide you the list.

**Comment by Navidem** [comment]
> /gcbrun trial_build.py igraph h2o gpac giflib gnupg hermes harfbuzz hostap kamailio lame curl cups draco dropbear expat file firestore flac flatbuffers fluent-bit freetype speex

Looks like it was a timeout. I break it to smaller trials.

**Comment by Navidem** [comment]
/gcbrun trial_build.py igraph h2o gpac giflib gnupg hermes harfbuzz hostap kamailio lame curl cups draco dropbear expat file firestore flac flatbuffers fluent-bit freetype speex

**Comment by Navidem** [comment]
/gcbrun trial_build.py igraph h2o gpac giflib gnupg hermes harfbuzz hostap kamailio lame curl cups draco --sanitizer introspector --fuzzing-engine libfuzzer

**Review by Navidem — APPROVED** [review]
LGTM

**Pull request merged**
