### PR TITLE
New project with fuzzer: xmltodict

### PR DESCRIPTION
**Pull request by CasperN**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
I think this library is no longer maintained? Also, please see: https://github.com/martinblech/xmltodict/issues/265

**Comment by DavidKorczynski** [comment]
@CasperN would it be possible for you to revive this PR? 

Substitute in `build.sh`:
```
for fuzzer in $(find $SRC -name '*_fuzzer.py'); do
  fuzzer_basename=$(basename -s .py $fuzzer)
  fuzzer_package=${fuzzer_basename}.pkg

  # To avoid issues with Python version conflicts, or changes in environment
  # over time on the OSS-Fuzz bots, we use pyinstaller to create a standalone
  # package. Though not necessarily required for reproducing issues, this is
  # required to keep fuzzers working properly in OSS-Fuzz.
  pyinstaller --distpath $OUT --onefile --name $fuzzer_package $fuzzer

  # Create execution wrapper. Atheris requires that certain libraries are
  # preloaded, so this is also done here to ensure compatibility and simplify
  # test case reproduction. Since this helper script is what OSS-Fuzz will
  # actually execute, it is also always required.
  # NOTE: If you are fuzzing python-only code and do not have native C/C++
  # extensions, then remove the LD_PRELOAD line below as preloading sanitizer
  # library is not required and can lead to unexpected startup crashes.
  echo "#!/bin/sh
# LLVMFuzzerTestOneInput for fuzzer detection.
this_dir=\$(dirname \"\$0\")
LD_PRELOAD=\$this_dir/sanitizer_with_fuzzer.so \
ASAN_OPTIONS=\$ASAN_OPTIONS:symbolize=1:external_symbolizer_path=\$this_dir/llvm-symbolizer:detect_leaks=0 \
\$this_dir/$fuzzer_package \$@" > $OUT/$fuzzer_basename
  chmod +x $OUT/$fuzzer_basename
done
```

to

```
for fuzzer in $(find $SRC -name '*_fuzzer.py'); do
  compile_python_fuzzer $fuzzer
done
```

**Comment by CasperN** [comment]
@DavidKorczynski hey, sorry I don't have time to prioritize this right now

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski hey, sorry I don't have time to prioritize this right now

Okay @CasperN -- are you okay with me fixing this up and making a PR then?

**Comment by CasperN** [comment]
Yeah, go ahead

**Comment by DavidKorczynski** [comment]
Would you still like to be emailed regarding issues?

**Comment by CasperN** [comment]
sure

**Pull request closed without merging**
