### PR TITLE
tcmalloc: initial integration.

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@ckennelly I looked at getting tcmalloc into OSS-Fuzz as I can see you already have fuzzers in the repo. Is this something you would be interested in? Atm only one of the four fuzzers are working in the oss-fuzz environment, but I can look into getting the remaining three to work if you are happy to get it into OSS-Fuzz.

**Comment by ckennelly** [comment]
Sure, I'd be interested.

Which ones are/aren't working?

**Comment by DavidKorczynski** [comment]
`experiment_fuzz`  `malloc_extension_fuzz` `runtime_size_classes_fuzz` are having issues atm. The reason is because a library is trying to be dynamically loaded at runtime whereas oss-fuzz wants the builds to be static. I will look a bit more into this shortly. 

Which email could I use for the bug reports?

**Comment by DavidKorczynski** [comment]
> The reason is because a library is trying to be dynamically loaded at runtime whereas oss-fuzz wants the builds to be static. I will look a bit more into this shortly.
> 

Not sure the above is true. This is the bug that's happening:
```
# gdb -q /out/experiment_fuzz
Reading symbols from /out/experiment_fuzz...done.
(gdb) r
Starting program: /out/experiment_fuzz 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000000000062c120 in TCMallocInternalCalloc () at tcmalloc/tcmalloc.cc:1983
1983    extern "C" void* TCMallocInternalCalloc(size_t n, size_t elem_size) noexcept {
```

**Comment by ckennelly** [comment]
For `experiment_fuzz`, I think things are getting confused by the attribute `malloc = ":tcmalloc"` on the target.  It looks like we've simultaneously linked in parts of ASan (guessing from both it being fuzzing and the ASan bits in that callstack) and TCMalloc (from the call to `TCMallocInternalCalloc`).  It's possible the fuzzing rules infrastruture isn't overwriting the `malloc` attribute--since it's reasonably rare--so we're getting malloc linked in via two paths.

If you delete the attribute on `experiment_fuzz`, does it run?  If so, I can fix this upstream.

I think we can do the same thing for the other targets too.

For an email: You can put down mine for now, (my github username) @google.com.

**Comment by DavidKorczynski** [comment]
I tried removing ASAN from the compilation process entirely, and the above error was no longer there (not in any of the fuzzers I listed above). Let me just try and delete the attribute as you suggest.

However, in the meantime, following removing ASAN I ran into an issue with some `absl` related logic it seems:

```
c# gdb -q /out/runtime_size_classes_fuzz
Reading symbols from /out/runtime_size_classes_fuzz...done.
(gdb) r
Starting program: /out/runtime_size_classes_fuzz
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6fda974 in __GI___clock_gettime (clock_id=4, tp=0x7fffffffd8d8) at ../sysdeps/unix/clock_gettime.c:115
115     ../sysdeps/unix/clock_gettime.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6fda974 in __GI___clock_gettime (clock_id=4, tp=0x7fffffffd8d8) at ../sysdeps/unix/clock_gettime.c:115
#1  0x00000000004d969f in absl::base_internal::ReadMonotonicClockNanos() () at external/com_google_absl/absl/base/internal/sysinfo.cc:152
#2  0x00000000004d95e5 in absl::base_internal::GetTimeTscPair() () at external/com_google_absl/absl/base/internal/sysinfo.cc:182
#3  0x00000000004d94ee in absl::base_internal::MeasureTscFrequencyWithSleep(int) () at external/com_google_absl/absl/base/internal/sysinfo.cc:198
#4  0x00000000004d93e8 in absl::base_internal::MeasureTscFrequency() () at external/com_google_absl/absl/base/internal/sysinfo.cc:216
#5  0x00000000004d9228 in absl::base_internal::GetNominalCPUFrequency() () at external/com_google_absl/absl/base/internal/sysinfo.cc:257
#6  0x00000000004d91c1 in absl::base_internal::NominalCPUFrequency()::$_1::operator()() const () at external/com_google_absl/absl/base/internal/sysinfo.cc:294
#7  0x00000000004d9191 in absl::base_internal::Callable::Invoke<absl::base_internal::NominalCPUFrequency()::$_1> () at external/com_google_absl/absl/base/internal/invoke.h:153
#8  0x00000000004d9161 in absl::base_internal::invoke<absl::base_internal::NominalCPUFrequency()::$_1> () at external/com_google_absl/absl/base/internal/invoke.h:180
#9  0x00000000004d90b7 in void absl::base_internal::CallOnceImpl<absl::base_internal::NominalCPUFrequency()::$_1>(std::__1::atomic<unsigned int>*, absl::base_internal::SchedulingMode, absl::base_internal::NominalCPUFrequency()::$_1&&) () at external/com_google_absl/absl/base/call_once.h:178
#10 0x00000000004d8daa in void absl::base_internal::LowLevelCallOnce<absl::base_internal::NominalCPUFrequency()::$_1>(absl::once_flag*, absl::base_internal::NominalCPUFrequency()::$_1&&) () at external/com_google_absl/absl/base/call_once.h:197
#11 0x00000000004d8d31 in absl::base_internal::NominalCPUFrequency() () at external/com_google_absl/absl/base/internal/sysinfo.cc:292
#12 0x00000000004d83a1 in absl::base_internal::UnscaledCycleClock::Frequency() () at external/com_google_absl/absl/base/internal/unscaledcycleclock.cc:59
#13 0x00000000004d81f1 in absl::base_internal::CycleClock::Frequency() () at external/com_google_absl/absl/base/internal/cycleclock.cc:83
#14 0x000000000054d689 in tcmalloc::tcmalloc_internal::PageAllocInfo::PageAllocInfo(char const*, int) () at ./tcmalloc/stats.h:255
#15 0x0000000000545313 in tcmalloc::tcmalloc_internal::PageAllocatorInterface::PageAllocatorInterface(char const*, tcmalloc::tcmalloc_internal::PageMap*, tcmalloc::tcmalloc_internal::MemoryTag) () at tcmalloc/page_allocator_interface.cc:78
#16 0x00000000005452b2 in tcmalloc::tcmalloc_internal::PageAllocatorInterface::PageAllocatorInterface(char const*, tcmalloc::tcmalloc_internal::MemoryTag) ()
    at tcmalloc/page_allocator_interface.cc:74
#17 0x0000000000535d1d in tcmalloc::tcmalloc_internal::HugePageAwareAllocator::HugePageAwareAllocator(tcmalloc::tcmalloc_internal::MemoryTag) ()
    at tcmalloc/huge_page_aware_allocator.cc:121
#18 0x0000000000544d3e in tcmalloc::tcmalloc_internal::PageAllocator::PageAllocator() () at tcmalloc/page_allocator.cc:100
#19 0x000000000054a420 in tcmalloc::tcmalloc_internal::Static::SlowInitIfNecessary() () at tcmalloc/static_vars.cc:106
#20 0x000000000051b3da in tcmalloc::tcmalloc_internal::Static::InitIfNecessary() () at ./tcmalloc/static_vars.h:177
#21 0x0000000000525931 in slow_alloc<tcmalloc::tcmalloc_internal::TCMallocPolicy<tcmalloc::tcmalloc_internal::MallocOomPolicy, tcmalloc::tcmalloc_internal::MallocAlignPolicy>, nullptr_t> () at tcmalloc/tcmalloc.cc:1802
#22 0x000000000051dc4e in fast_alloc<tcmalloc::tcmalloc_internal::TCMallocPolicy<tcmalloc::tcmalloc_internal::MallocOomPolicy, tcmalloc::tcmalloc_internal::MallocAlignPolicy>, nullptr_t> () at tcmalloc/tcmalloc.cc:1859
#23 TCMallocInternalCalloc () at tcmalloc/tcmalloc.cc:1989
#24 0x00007ffff74a6627 in _dlerror_run (operate=operate@entry=0x7ffff74a6020 <dlsym_doit>, args=args@entry=0x7fffffffdd80) at dlerror.c:141
#25 0x00007ffff74a6088 in __dlsym (handle=<optimized out>, name=<optimized out>) at dlsym.c:70
#26 0x000000000047b686 in getFuncAddr () at /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerInterceptors.cpp:32
#27 fuzzerInit () at /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerInterceptors.cpp:231
#28 0x00007ffff7de7862 in _dl_init (main_map=0x7ffff7ffe168, argc=1, argv=0x7fffffffde28, env=0x7fffffffde38) at dl-init.c:105
#29 0x00007ffff7dd7c6a in _dl_start_user () from /lib64/ld-linux-x86-64.so.2
#30 0x0000000000000001 in ?? ()
#31 0x00007fffffffe13a in ?? ()
#32 0x0000000000000000 in ?? ()

```

**Comment by DavidKorczynski** [comment]
@ckennelly your suggestion worked, and the issue above with absl is no longer valid. The fuzzers are running!

**Comment by ckennelly** [comment]
That change is now pushed.

**Comment by DavidKorczynski** [comment]
@inferno-chromium @jonathanmetzman @asraa @oliverchang calling on the current sheriff this one is ready to go!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
