### PR TITLE
[expr] Initial integration

### PR DESCRIPTION
**Pull request by antonmedv**
Expr is an expression language in Go. It's primary goal is to be safe to take unsanitized user input. 
Expr is already in //third_party in google3 ;)

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by antonmedv** [comment]
I don't understand why build libfuzzer,address,x86_64 failed.

**Comment by antonmedv** [comment]
@jonathanmetzman please help with tests. Thanks!

**Comment by jonathanmetzman** [comment]
Done

**Comment by jonathanmetzman** [comment]
Post back here if they pass please.

**Comment by antonmedv** [comment]
Please restart workflows.

**Comment by antonmedv** [comment]
I tried to test the build locally but got some problems with installing dependencies. 

Please, help me with this PR. Thanks! <3

**Comment by jonathanmetzman** [comment]
> I tried to test the build locally but got some problems with installing dependencies.
> 
> Please, help me with this PR. Thanks! <3

Installing deps for OSS-Fuzz? It's just docker and python.
Do you understand the error in CI? I don't

**Comment by antonmedv** [comment]
> Do you understand the error in CI? I don't

I don't too. 

>  It's just docker and python.

I was trying to install pip locally

**Comment by jonathanmetzman** [comment]
> > Do you understand the error in CI? I don't
> 
> I don't too.
> 
> > It's just docker and python.
> 
> I was trying to install pip locally

I don't think pip is required though,.

**Comment by antonmedv** [comment]
Found the docs: https://google.github.io/oss-fuzz/advanced-topics/reproducing/
It helped =)

**Comment by antonmedv** [comment]
Same error as in CI:

```
+ compile_native_go_fuzzer github.com/antonmedv/expr FuzzExpr fuzz_expr
main.1367621804.go:12:2: found packages expr (bench_test.go) and expr_test (fuzz_test.go_fuzz.go) in /src/expr
2023/08/23 12:17:06 failed to build packages:exit status 1
ERROR:__main__:Building fuzzers failed.
```

**Comment by antonmedv** [comment]
I trying to put fuzzers in a sep dir. Seems like it helped.

**Comment by antonmedv** [comment]
@jonathanmetzman please, approve CI builds.

**Comment by antonmedv** [comment]
@jonathanmetzman I'd like to get this done! I really appreciate any help you can provide.

**Comment by jonathanmetzman** [comment]
I see this error:
```
panic: open ./fuzz_corpus.txt: no such file or directory [recovered]
	panic: open ./fuzz_corpus.txt: no such file or directory
```
Is it trying to read a non-existent file?

**Comment by antonmedv** [comment]
I switched to `go:embed` for corpus. Looks like it working:

```
$ python infra/helper.py build_fuzzers --sanitizer address expr
...
+ cp /src/expr/test/fuzz/fuzz_expr_seed_corpus.zip /out/
+ cp /src/expr/test/fuzz/fuzz_expr.dict /out/
+ go get github.com/AdamKorcz/go-118-fuzz-build/testing
go: downloading github.com/AdamKorcz/go-118-fuzz-build v0.0.0-20230306123547-8075edf89bb0
go: downloading github.com/AdaLogics/go-fuzz-headers v0.0.0-20221206110420-d395f97c4830
go: downloading github.com/cyphar/filepath-securejoin v0.2.3
go: added github.com/AdaLogics/go-fuzz-headers v0.0.0-20221206110420-d395f97c4830
go: added github.com/AdamKorcz/go-118-fuzz-build v0.0.0-20230306123547-8075edf89bb0
go: added github.com/cyphar/filepath-securejoin v0.2.3
+ compile_native_go_fuzzer github.com/antonmedv/expr/test/fuzz FuzzExpr fuzz_expr
```

@jonathanmetzman PTAL

**Comment by jonathanmetzman** [comment]
Did you update the PR?

**Comment by antonmedv** [comment]
I only updated my repo.

**Comment by antonmedv** [comment]
Will update the branch.

**Comment by antonmedv** [comment]
@jonathanmetzman PTAL

**Pull request merged**
