### PR TITLE
Removes binutils patch, applied upstream

### PR DESCRIPTION
**Pull request by catenacyber**
Thanks to Alan Modra cf https://sourceware.org/bugzilla/show_bug.cgi?id=24960

Should fix build failure
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=19372

### CODE REVIEW

**Comment by catenacyber** [comment]
There seems to be another thing now blocking the build.
What is step 12 in https://oss-fuzz-build-logs.storage.googleapis.com/index.html#binutils ?

`python infra/helper.py build_fuzzers binutils` works locally but that seems to be step 4 in the log

**Comment by Dor1s** [comment]
That is `--sanitizer undefined`

**Comment by catenacyber** [comment]
Thanks, this was the new UBSAN pointer overflow which prevented the build.
Seems ok now

PS : How could I have known that set 12 is `--sanitizer undefined` ?

**Comment by Dor1s** [comment]
By looking at the build flags:

```
2019-12-13T03:28:55.059749176Z Step #12: + clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift,signed-integer-overflow,unsigned-integer-overflow,unreachable,vla-bound,vptr -fno-sanitize-recover=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,pointer-overflow,return,returns-nonnull-attribute,shift,signed-integer-overflow,unreachable,vla-bound,vptr -fsanitize=fuzzer-no-link -stdlib=libc++ fuzz/fuzz_disassemble.o -o /workspace/out/undefined/fuzz_disassemble -lFuzzingEngine opcodes/libopcodes.a bfd/libbfd.a libiberty/libiberty.a zlib/libz.a I 
2019-12-13T03:28:55.067533281Z Step #12: clang-10: error: no such file or directory: 'opcodes/libopcodes.a' I 
2019-12-13T03:28:55.068205724Z Step #12: clang-10: error: no such file or directory: 'bfd/libbfd.a' I 
2019-12-13T03:28:55.432127276Z Finished Step #12 I 
2019-12-13T03:28:55.488787626Z ERROR I 
```

that's definitely not a good UX, as it assumes the knowledge of various sanitizer options. I've added an action item in https://github.com/google/oss-fuzz/issues/3104

**Pull request merged**
