### PR TITLE
tdengine: initial integration.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
TDEngine is an open source big data platform designed for IoT. I think the main comparison is to databases such as Influxdb and the main advantage of TDEngine is performance. 

TDEngine and the company behind it has has 69 million in funding (https://www.crunchbase.com/organization/taos-data).

A list of users is given here https://github.com/taosdata/TDengine/issues/2432 and it seems that TDEngine has the majority of its customers in China. I had to do a bit of translation to identify the type of customers, but it seems quite a few of them are enterprises, e.g. https://github.com/taosdata/TDengine/issues/2432#issuecomment-870150444 which I think is a ~1500 employee company (https://www.bloomberg.com/profile/company/300066:CH). In short, it seems that TDengine sits in many IoT devices across the world. @sangshuduo please correct me if I am wrong. 

@inferno-chromium @jonathanmetzman @oliverchang @asraa this one is good to go.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
@guanshengliang @hjxilinx @sangshuduo I integrated fuzzing into tdengine by way of OSS-Fuzz. Would you be interested in getting continuous fuzzing on tdengine? If so, the only thing we need is a set of emails that can go into `project.yaml` which will receive bug reports and details about crashes and vulnerabilities found by OSS-Fuzz. This email should be affiliated with a Google account.

**Comment by sangshuduo** [comment]
I‘m in.

**Comment by DavidKorczynski** [comment]
> I‘m in.

Thanks @sangshuduo - could you perhaps list some of the users of TDengine? I can see you are a VC backed company with high profile investors (GGV and Sequoia China?) but it would be great to know who are the types of customers of TDEngine?

**Review by sangshuduo — APPROVED** [review]
LGTM

**Comment by sangshuduo** [comment]
@DavidKorczynski some whale customers like SF express (one of biggest mail services in the world), Lixiang Auto ([LI](https://www.google.com/search?newwindow=1&sxsrf=ALeKk03LS-xhsf6rHY6oMXTEj9yJ6XmwDg:1627780410531&q=NASDAQ:+LI&stick=H4sIAAAAAAAAAONgecRowS3w8sc9YSn9SWtOXmPU5OIKzsgvd80rySypFJLmYoOyBKX4uXj10_UNDbPNzMpLqswteBaxcvk5Brs4Blop-HgCAE2Rw9FKAAAA&sa=X&ved=2ahUKEwi89pDJ0o7yAhXB0p4KHWzODz8QsRUwY3oECCkQAw):  NASDAQ), RisingStar, etc. :)

**Comment by DavidKorczynski** [comment]
> s (one of biggest mail services in the world

Thanks a lot @sangshuduo!

**Comment by DavidKorczynski** [comment]
@jonathanmetzman @inferno-chromium @oliverchang this one is ready for review! Please check if the project is eligible given the above info

**Review by inferno-chromium — APPROVED** [review]

**Comment by sangshuduo** [comment]
@DavidKorczynski I received an email about TDengine potential fatal found by oss-fuzz from my business email address, but I can't access the bug link the email mentioned. I clicked the link to sign in. Then found my personal email (gmail) account logged on but still can't access the content. Could you please let me know how I can access it? Thanks.

**Comment by DavidKorczynski** [comment]
The emails listed in the `project.yaml` file are the ones that can access the reports: https://github.com/google/oss-fuzz/blob/master/projects/tdengine/project.yaml

We can add your personal gmail account to the `auto_ccs` list and then you will be able to access the bug reports from your account.

**Comment by sangshuduo** [comment]
please take care https://github.com/google/oss-fuzz/pull/6360. thanks.

**Pull request merged**
