### PR TITLE
Revert "Update afl++ (#7008)"

### PR DESCRIPTION
**Pull request by jonathanmetzman**
This reverts commit 95e437c59982cf242d01c53af44181e81a03e4ce.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Fixes https://github.com/google/oss-fuzz/pull/7008

**Review by inferno-chromium — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
> Fixes #7008

https://github.com/google/oss-fuzz/issues/7021 too

**Comment by rlohning** [comment]
Still crashes when building Qt: https://github.com/google/oss-fuzz/pull/7017

**Comment by DavidKorczynski** [comment]
> Still crashes when building Qt: #7017

I think the build hasn't been updated yet so it will still have used the old image. In 24 hours we should hopefully see the fix!

**Comment by jonathanmetzman** [comment]
Damn, I thought this revert would have prevented the bugs from being filed.

**Comment by DavidKorczynski** [comment]
> Damn, I thought this revert would have prevented the bugs from being filed.

FYI I have not received any failed-build emails from the projects I listed in the issue yesterday. I think it's two different bugs - the stack traces look different.

**Pull request merged**
