### PR TITLE
Adds project trillian

### PR DESCRIPTION
**Pull request by catenacyber**
@daviddrysdale would you be interested in continuous fuzzing for Trillian ?
This PR enables it with oss-fuzz with one structure-aware target about `trillian.Tree`

Questions and feedback are welcome

### CODE REVIEW

**Comment by catenacyber** [comment]
sorry @daviddrysdale I mistyped your name the first time

**Comment by daviddrysdale** [comment]
I don't work on Trillian at the moment, but one of these folk might be interested: @pavelkalinnikov @alcutter @Martin2112

**Comment by catenacyber** [comment]
Thank you David for forwarding

**Comment by pavelkalinnikov** [comment]
Not sure how much value this particular pull request adds, but maybe it would be interesting to fuzz bits of storage / hashes to make that proof verification fails accordingly.

**Comment by catenacyber** [comment]
> maybe it would be interesting to fuzz bits of storage / hashes to make sure that proof verification fails accordingly.

Would it not be interesting to fuzz the whole `trillian.Tree` structure ?

**Comment by pavelkalinnikov** [comment]
Probably no. The `trillian.Tree` structure is just a piece of metadata. Also, it's a protobuf, which is pretty well tested anyway.

**Pull request closed without merging**
