### PR TITLE
add aojea to kubernetes project

### PR DESCRIPTION
**Pull request by aojea**

### CODE REVIEW

**Comment by AdamKorcz** [comment]
The CI failure is unrelated to the PR. I will fix the CI issue upstream.

**Comment by aojea** [comment]
it failed with
```
+ find /src/kubernetes/vendor/github.com/cilium/ebpf/internal/btf -name fuzz.go -exec rm -rf '{}' ';'
+ compile_native_go_fuzzer k8s.io/kubernetes/test/fuzz/fuzzing FuzzParseQuantity fuzz_parse_quantity
replacing *testing.F
here we perform coverage build
# cover k8s.io/kubernetes/test/fuzz/fuzzing
2022/10/31 10:23:54 cover: /src/kubernetes/test/fuzz/fuzzing/api_marshaling_fuzzer.go: /src/kubernetes/test/fuzz/fuzzing/api_marshaling_fuzzer.go:2092:32: exceeded max scope depth during object resolution
```

**Comment by AdamKorcz** [comment]
> it failed with
> 
> ```
> + find /src/kubernetes/vendor/github.com/cilium/ebpf/internal/btf -name fuzz.go -exec rm -rf '{}' ';'
> + compile_native_go_fuzzer k8s.io/kubernetes/test/fuzz/fuzzing FuzzParseQuantity fuzz_parse_quantity
> replacing *testing.F
> here we perform coverage build
> # cover k8s.io/kubernetes/test/fuzz/fuzzing
> 2022/10/31 10:23:54 cover: /src/kubernetes/test/fuzz/fuzzing/api_marshaling_fuzzer.go: /src/kubernetes/test/fuzz/fuzzing/api_marshaling_fuzzer.go:2092:32: exceeded max scope depth during object resolution
> ```

Yep, let me fix that.

**Review by AdamKorcz — APPROVED** [review]
LGTM. Antonio is technical lead of SIG Testing: https://github.com/kubernetes/community/tree/master/sig-testing#technical-leads

**Pull request merged**
