### PR TITLE
[proxygen] Set rpath properly

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Speculative fix for proxygen.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @mhlakhani

**Comment by inferno-chromium** [comment]
Thanks a ton @jonathanmetzman !

**Comment by jonathanmetzman** [comment]
I'll kick off another build to see if this fix worked.

**Comment by inferno-chromium** [comment]
@jonathanmetzman - it might be interesting to add this trick on https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/ ? Thoughts ? this patchelf stuff keeps coming every now and then.

**Comment by mhlakhani** [comment]
thanks for putting up the patch so quickly!

**Comment by jonathanmetzman** [comment]
> thanks for putting up the patch so quickly!

No problem!

> it might be interesting to add this trick on https://google.github.io/oss-fuzz/further-reading/fuzzer-environment/ ? Thoughts ? this patchelf stuff keeps coming every now and then.

Sure, [doing it now](https://github.com/google/oss-fuzz/pull/2881).
An alternative would be adding this some kind of linker flags for OSS-Fuzz projects should use (kind of what $LIB_FUZZING_ENGINE should be IMO)

**Comment by jonathanmetzman** [comment]
This seems to have worked: https://console.cloud.google.com/storage/browser/_details/proxygen-logs.clusterfuzz-external.appspot.com/libFuzzer_proxygen_ProxygenHTTP1xFuzzer/libfuzzer_asan_proxygen/2019-09-23/23:27:01:122883.log

**Pull request merged**
