### PR TITLE
tinyusb: initial integration

### PR DESCRIPTION
**Pull request by silvergasp**
Signed-off-by: Nathaniel Brough <nathaniel.brough@gmail.com>

CC @hathach

### CODE REVIEW

**Comment by silvergasp** [comment]
@hathach Now that https://github.com/hathach/tinyusb/pull/1716 is merged I'm going to mark this as ready to review. I'm unsure if all emails in the project.yaml need to be in the git log or just some.

**Comment by silvergasp** [comment]
Attempting to address build failures in https://github.com/hathach/tinyusb/pull/1823

**Comment by jonathanmetzman** [comment]
We accept this project. Just fix the build failure please.

**Comment by silvergasp** [comment]
Just waiting on a review from @hathach on https://github.com/hathach/tinyusb/pull/1823 which fixes the build failure.

**Comment by silvergasp** [comment]
That PR has been merged. So I think the build should work now. I did go through and check each fuzzing engine and each santizer. But I didn't check the entire matrix of each combination of the two locally.

**Comment by silvergasp** [comment]
Apologies, it seems it's still broken. Is it possible somehow to run the complete CI locally?

**Comment by jonathanmetzman** [comment]
> Apologies, it seems it's still broken. Is it possible somehow to run the complete CI locally?

It doesn't look broken to me. Usually you just do what the CI job did locally (e.g. `python infra/helper.py --engine hongfuzz --sanitizer address tinyusb`)

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by jonathanmetzman** [comment]
> lgtm

Oh man I must've been looking at something stale. Gonna have to revert this and you can submit another PR. Sorry for the trouble.

**Comment by jonathanmetzman** [comment]
Yeah this must be some weird caching thing 
image

**Comment by jonathanmetzman** [comment]
> > Apologies, it seems it's still broken. Is it possible somehow to run the complete CI locally?
> 
> It doesn't look broken to me. Usually you just do what the CI job did locally (e.g. `python infra/helper.py --engine hongfuzz --sanitizer address tinyusb`)

The essential one is address (ASAN) so try to get that working first, and the others can be disabled (`python infra/helper.py --engine libfuzzer --sanitizer address tinyusb`

**Comment by jonathanmetzman** [comment]
> > > Apologies, it seems it's still broken. Is it possible somehow to run the complete CI locally?
> > 
> > 
> > It doesn't look broken to me. Usually you just do what the CI job did locally (e.g. `python infra/helper.py --engine hongfuzz --sanitizer address tinyusb`)
> 
> The essential one is address (ASAN) so try to get that working first, and the others can be disabled (`python infra/helper.py build_fuzzers --engine libfuzzer --sanitizer address tinyusb`

OK so your CI jobs are failing because they are failing the build check. To do this locally run the following command after running build_fuzzers: `python infra/helper.py check_build --engine libfuzzer --sanitizer <sanitizer, e.g. "address"> tinyusb`

**Comment by jonathanmetzman** [comment]
the specific errors i see are:
`clang-15: fatal error: invalid argument '-fsanitize=address' not allowed with '-fsanitize=memory'`
`BAD BUILD: ASan build of /tmp/not-out/tmpkpsh74_e/cdc seems to be compiled with UBSan.`
`BAD BUILD: UBSan build of /tmp/not-out/tmpwgxy6rrx/cdc seems to be compiled with ASan.`

(the last two will repro with check_build)

I think it is doing something weird in builds. I think it must be adding sanitizer flags instead of using our CXXFLAGS and CFLAGS

**Comment by silvergasp** [comment]
Yeah, that was 

> > > > Apologies, it seems it's still broken. Is it possible somehow to run the complete CI locally?
> > > 
> > > 
> > > It doesn't look broken to me. Usually you just do what the CI job did locally (e.g. `python infra/helper.py --engine hongfuzz --sanitizer address tinyusb`)
> > 
> > 
> > The essential one is address (ASAN) so try to get that working first, and the others can be disabled (`python infra/helper.py build_fuzzers --engine libfuzzer --sanitizer address tinyusb`
> 
> OK so your CI jobs are failing because they are failing the build check. To do this locally run the following command after running build_fuzzers: `python infra/helper.py check_build --engine libfuzzer --sanitizer <sanitizer, e.g. "address"> tinyusb`

Yeah ok, that was about what I was doing already. I was more curious if there was an easy way to iterate over all the combinations locally.

Anyway, I must have missed something, so I'll investigate further this afternoon, and open a new PR when I've ironed out the kinks.

**Pull request merged**
