### PR TITLE
bitcoin-core: remove ccs of past contributors

### PR DESCRIPTION
**Pull request by fanquake**

### CODE REVIEW

**Comment by fanquake** [comment]
cc @MarcoFalke

**Comment by MarcoFalke** [comment]
sgtm. If they want, they could re-add themselves, if they come back.

**Comment by jnewbery** [comment]
Yes, please go ahead and remove me. I'm no longer active in the project. Thanks @fanquake!

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
