### PR TITLE
XZ: update build.sh

### PR DESCRIPTION
**Pull request by mvatsyk-lsg**
Update build.sh to support 11 new fuzzing targets, added to the XZ repository in the [following pull request.](https://github.com/tukaani-project/xz/pull/73)

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Please fix this error.
@JiaT75 do you approve?

**Comment by mvatsyk-lsg** [comment]
If that's possible, I'd like to put this pull request on hold until the updated fuzzing configuration is merged into the main `xz` repo

**Comment by JiaT75** [comment]
@mvatsyk-lsg it's probably a good idea to mark this PR as a draft until the XZ Utils PR is merged

**Comment by DavidKorczynski** [comment]
@mvatsyk-lsg could you please sign the CLA?

**Comment by mvatsyk-lsg** [comment]
@DavidKorczynski done!

**Review by DavidKorczynski — APPROVED** [review]

**Pull request merged**
