### PR TITLE
yoga: Initial integration

### PR DESCRIPTION
**Pull request by silvergasp**

### CODE REVIEW

**Comment by silvergasp** [comment]
cc @NickGerleman

**Comment by silvergasp** [comment]
Approval from maintainer in this thread https://github.com/facebook/yoga/issues/1538#issuecomment-1968835448

**Comment by DonggeLiu** [comment]
Gentle ping. @NickGerleman : )
Would you approve this?

**Review by NickGerleman — APPROVED** [review]

**Comment by DonggeLiu** [comment]
@silvergasp  One last question: 
May I ask who the major users of the project are and why it is critical?
This will help the panel approve this PR.

**Comment by silvergasp** [comment]
> @silvergasp  One last question: 
> May I ask who the major users of the project are and why it is critical?
> This will help the panel approve this PR.

Hey @DonggeLiu the yoga project has 17.1k stars on github. It is primarily used as the [layout engine for react-native](https://reactnative.dev/blog/2024/04/22/release-0.74) and is shipped as a component of a large number of android and ios apps, although I don't have specific numbers on that.

**Pull request merged**
