### PR TITLE
[cgif] Initial integration

### PR DESCRIPTION
**Pull request by dloebl**
Add initial [cgif](https://github.com/dloebl/cgif) integration.
[cgif](https://github.com/dloebl/cgif) is a GIF encoding library written in C. It is used as the GIF encoding layer of [libvips](https://github.com/libvips/libvips).
Right now, it is only fuzzed indirectly via [libvips](https://github.com/libvips/libvips): https://github.com/google/oss-fuzz/pull/6241
Fuzzing [cgif](https://github.com/dloebl/cgif) directly would allow covering the complete API.

I would be happy to update this PR with the `Dockerfile` and `build.sh` once I have the OK from your side.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
> Add initial [cgif](https://github.com/dloebl/cgif) integration. [cgif](https://github.com/dloebl/cgif) is a GIF encoding library written in C. It is used as the GIF encoding layer of [libvips](https://github.com/libvips/libvips). Right now, it is only fuzzed indirectly via [libvips](https://github.com/libvips/libvips): #6241 Fuzzing [cgif](https://github.com/dloebl/cgif) directly would allow covering the complete API.
> 
> I would be happy to update this PR with the `Dockerfile` and `build.sh` once I have the OK from your side.

Who are some of the users of cgif, is it essentially every user of libvips.
Anything that would inform us how critical this software is helpful.

**Comment by dloebl** [comment]
> Who are some of the users of cgif, is it essentially every user of libvips.

Yes, cgif is the default encoder used when saving GIF images and animations via libvips since version 8.12:
[https://www.libvips.org/2021/11/14/What's-new-in-8.12.html](https://www.libvips.org/2021/11/14/What's-new-in-8.12.html)

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by dloebl** [comment]
Thanks for your review! I added the missing Google license headers with caebaed4b9b0e2e1c6498a2e55bf1906458b0c7d.

**Pull request merged**
