### PR TITLE
[c-blosc2] Remove email address from auto-css.

### PR DESCRIPTION
**Pull request by nmoinvaz**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Can I ask why you are removing yourself?
Do you also want to remove yourself from https://github.com/google/oss-fuzz/blob/master/projects/c-blosc/project.yaml#L5 ?

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by nmoinvaz** [comment]
I don't have time to review and fix issues and I don't want to be spammed with the e-mails in my inbox anymore. The other project I am fine remaining on as it is less spammy.

**Comment by jonathanmetzman** [comment]
> I don't have time to review and fix issues and I don't want to be spammed with the e-mails in my inbox anymore. The other project I am fine remaining on as it is less spammy.

Sorry to hear that.
Could you elaborate on what you mean by spam?
Is the volume of bug reports simply too large? Or are there false positives?

**Pull request merged**
