### PR TITLE
Ffmpeg test all decoders

### PR DESCRIPTION
**Pull request by michaelni**

### CODE REVIEW

**Comment by michaelni** [comment]
These commits are all under public domain.

**Comment by oliverchang** [comment]
@michaelni Thanks for this change. It looks like we're running out of disk space now (we have a hard limit of ~70GB during a build).

See https://oss-fuzz-build-logs.storage.googleapis.com/log-f1ab0bed-3852-4c07-91c5-46f18299e86e.txt

Is there any way that we could reduce the amount of disk used during a build?

**Comment by michaelni** [comment]
static linking with 1 binary per decoder and there being more than 400 decoders and clang creating more than 300mb sized binaries adds up. Iam not sure if the base size of the binaries can be reduced by some clang option it seems to me they are a bit large compared to normal builds. combing the tests in one binary, or using shared libs should reduce the size, IIUC ossfuzz wants static and one binary per test though

**Comment by kcc** [comment]
Does every of the 400 binaries link the entire ffmpeg?

**Comment by oliverchang** [comment]
I'm not sure fuzzing all 400 decoders would be effective on our infrastructure right now, since ffmpeg's share of CPUs would be split between all 400 of these..

Would it be possible to reduce this number to something smaller based on how important/frequently used they are?

**Comment by michaelni** [comment]
@kcc, the entire ffmpeg build with clang with the sanitizers with -Os is over 500mb the tool is just 200 with -Os. The tool atm uses libavformat too, i think this was a mistake, ill fix that. After that it seems iam down to 155mb and specifying the "unused" libs to the linker or not doesnt change the size.

@oliverchang, Which doors do you want to leave unlocked ? Generally with decoders the attacker can choose which will be used as the file supplied by the attacker needs to use the decoder it claims to need

**Comment by kcc** [comment]
> After that it seems iam down to 155mb

Is that down from 300mb? Does this make us fit into the ~70GB disk quota?

**Comment by michaelni** [comment]
i think its down from 3XYmb, iam not sure as i tested with different flags to speed build up, i dont know about 70gb, i do have 2 more ideas though that ill try

**Comment by michaelni** [comment]
Testing with docker and the scripts the smallest i could achive was slightly less than 200mb per tool by disabling all but the decoders and all external libs and -Os. that was still more than 80gb. Also we or someone may want to add tests for encoders, parsers, bitstream filters, filters, ...
Ill send a pull request for adding -Os iam not sure disabling stuff is the right way to go as it gets more messy when someone adds tests for encoders as they needs these parts, especially as this doesnt get us below 70gb

**Pull request merged**
