### PR TITLE
Remove antlr deps

### PR DESCRIPTION
**Pull request by bshastry**
Fixes solidity failing build

### CODE REVIEW

**Comment by asraa** [comment]
It looks like the build still fails based on some early crashes-- are these known?

**Comment by bshastry** [comment]
> It looks like the build still fails based on some early crashes-- are these known?

Sorry for keeping the PR open. Yes, they are known and tracked here: https://github.com/ethereum/solidity/issues/11343

Since the fix is not ready yet, shall we keep this PR open until one is ready or close and reopen the PR once it is ready?

**Comment by asraa** [comment]
We'll just keep as open -- just ping back when they're merged to restart CI!

**Comment by bshastry** [comment]
The previous build failed unrelated to this PR. I am rebasing on master in the hope that the problem goes away :-)

**Comment by inferno-chromium** [comment]
> The previous build failed unrelated to this PR. I am rebasing on master in the hope that the problem goes away :-)

you need to ping dev to fix this startup crash, otherwise new builds wont be generated. i am merging your pr.

```
=================================================================
==611==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fcad7f4de50 at pc 0x000000b6efcc bp 0x7ffe672e8750 sp 0x7ffe672e8748
READ of size 8 at 0x7fcad7f4de50 thread T0
SCARINESS: 23 (8-byte-read-stack-use-after-scope)
    #0 0xb6efcb in begin /usr/local/include/c++/v1/__tree:1115:67
    #1 0xb6efcb in begin /usr/local/include/c++/v1/set:610:60
```

**Comment by bshastry** [comment]
> > The previous build failed unrelated to this PR. I am rebasing on master in the hope that the problem goes away :-)
> 
> you need to ping dev to fix this startup crash, otherwise new builds wont be generated. i am merging your pr.
> 
> ```
> =================================================================
> ==611==ERROR: AddressSanitizer: stack-use-after-scope on address 0x7fcad7f4de50 at pc 0x000000b6efcc bp 0x7ffe672e8750 sp 0x7ffe672e8748
> READ of size 8 at 0x7fcad7f4de50 thread T0
> SCARINESS: 23 (8-byte-read-stack-use-after-scope)
>     #0 0xb6efcb in begin /usr/local/include/c++/v1/__tree:1115:67
>     #1 0xb6efcb in begin /usr/local/include/c++/v1/set:610:60
> ```

Hmm... I thought this was fixed already. Will take a closer look. Thanks!

**Pull request merged**
