### PR TITLE
Enable Introspector for jvm

### PR DESCRIPTION
**Pull request by Navidem**

### CODE REVIEW

**Comment by Navidem** [comment]
/gcbrun trial_build.py ndpi glom apache-commons-cli archaius-core arrow-java --sanitizer introspector coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py ndpi glom apache-commons-cli archaius-core  --sanitizer introspector coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py archaius-core --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py archaius-core --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py ndpi glom apache-commons-cli archaius-core --sanitizer introspector coverage --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py  apache-commons-cli archaius-core --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py apache-commons-cli archaius-core --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py apache-commons-cli archaius-core --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py log4j2 zip4j --sanitizer coverage introspector --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
/gcbrun trial_build.py apache-commons-cli zip4j --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by Navidem** [comment]
Sample reports for java projects: [apache-commons-cli](https://storage.googleapis.com/oss-fuzz-introspector/apache-commons-cli/inspector-report/20230119/fuzz_report.html), [zip4j](https://storage.googleapis.com/oss-fuzz-introspector/zip4j/inspector-report/20230119/fuzz_report.html)

**Review by oliverchang — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
@arthurscchan fyi

**Pull request merged**
