### PR TITLE
poco: Use latest builder

### PR DESCRIPTION
**Pull request by tyler92**
Also, unnecessary targets have been disabled to speed up compilation time and avoid issues with Clang 18.0.0 in Poco.Data.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@DavidKorczynski thoughts?

**Comment by DavidKorczynski** [comment]
@tyler92 could you coordinate these contributions with the maintainers of `poco`?

https://github.com/google/oss-fuzz/pull/4736 and https://github.com/google/oss-fuzz/pull/5925 with relevant PRs.

Ideally we should land the targets in upstream repositories. @obiltschnig  @aleks-f Recently @tyler92 has been contributing fuzzing to `poco`. could you help review the PRs?

**Review by DavidKorczynski — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Please follow-up with upstreaming from the other PR

**Comment by tyler92** [comment]
@DavidKorczynski upstreaming: https://github.com/pocoproject/poco/pull/4719 . I will update `project/poco` when that MR is merged.

**Pull request merged**
