### PR TITLE
Copy dictionaries over to help steer fuzzing.

### PR DESCRIPTION
**Pull request by thomasvl**
These just landed in apple/swift-protobuf/1166

cc @catenacyber @inferno-chromium

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by catenacyber** [comment]
Let's check https://oss-fuzz.com/fuzzer-stats?group_by=by-day&fuzzer=libFuzzer&job=libfuzzer_asan_swift-protobuf&project=swift-protobuf in a few days

**Comment by catenacyber** [comment]
Oh... I think these dictionaries work...

**Comment by thomasvl** [comment]
> Oh... I think these dictionaries work...

Yup, I'd still like to see the coverage data from them, but clearly we're getting some new reports because of them.  Might also need to double check the coverage on the binary side to see if we need to add some there also.

**Comment by catenacyber** [comment]
From 35.94% to 53.95% coverage in 2 days, nice ;-)

**Pull request merged**
