### PR TITLE
Golang project uses compile_go_fuzzer script

### PR DESCRIPTION
**Pull request by catenacyber**
And avoid infinite recursion from #4659

### CODE REVIEW

**Comment by catenacyber** [comment]
cc @Dor1s

**Comment by inferno-chromium** [comment]
Thanks!

**Comment by inferno-chromium** [comment]
Had to do https://github.com/google/oss-fuzz/commit/57ebc0c76ac59842908415bcd27141cccb4544c0 for unbound stuff.

**Comment by catenacyber** [comment]
Thanks for the unbound fix

**Pull request merged**
