### PR TITLE
Add nginx

### PR DESCRIPTION
**Pull request by andrey-zelenkov**
nginx is an HTTP and reverse proxy server, a mail proxy server, and a generic TCP/UDP proxy server. According to Netcraft, nginx served or proxied 28.30% busiest sites in January 2017.

### CODE REVIEW

**Comment by kcc** [comment]
excellent, thanks! please sign the CLA and we'll merge this.

**Comment by andrey-zelenkov** [comment]
I signed it!

**Comment by kcc** [comment]
weird. I don't see it. usually the system responds right away.

**Comment by kcc** [comment]
can you try once more?

**Comment by andrey-zelenkov** [comment]
I signed individual CLA last month (with these pull requests: https://github.com/google/oss-fuzz/commit/a55fd5a4362f30ef7e3baa314ec98363ec7d81a1 and https://github.com/google/oss-fuzz/commit/4350dec38edb3835a3981dfce603e67411115b03). But now I've noticed corporate type of CLA. Should I sign it too or my individual CLA will be enough?

**Comment by kcc** [comment]
Hm... Interesting. I can see your e-mail has a valid CLA, but I can't see that for your github account. 
Is your github associated with the e-mail mentioned in this pull request or some other? 
Merging now, but we need to sort this out, otherwise the system will continue complaining about the CLA...

**Comment by andrey-zelenkov** [comment]
Yes, my e-mail is associated with github account and even set as primary and public. But in profile settings I set "Don't show my email address". Can this be a problem?

**Comment by kcc** [comment]
... maybe. trying to figure this out. Anyway, we are unblocked now.
Looking forward to seeing the more PRs from you :)

**Comment by kcc** [comment]
aha. looks like you've used another e-mail to do the commits (your @nginx.com one): 
https://g3doc.corp.google.com/company/teams/opensource/cla/index.md?cl=head#wrong-email
I guess the simplest is to also sign a CLA with that e-mail too.

**Comment by andrey-zelenkov** [comment]
Ok, thank you. I'll try it.

**Comment by andrey-zelenkov** [comment]
@kcc No, I do not have such plans at the moment.

**Comment by yooyoo9** [comment]
Greetings @andrey-zelenkov !

I has a fuzz target for http requests for Nginx. I have been working on it for the initial integration of Nginx with OSS-Fuzz. I'd like to seek your consent to continue and thereby complete the integration. I submitted a pull request to OSS-Fuzz where you can review the target, then I can land it and we can get started fuzzing.
We (OSS-Fuzz) strongly prefer that fuzz targets live in the source repo of the code they fuzz so after this, we can move the target to Nginx, this will make contribution of other fuzzers and maintenance of this one as easy as possible for nginx devs.

Thank You !

Yooyoo9

**Pull request merged**
