### PR TITLE
Submit the websockets project.

### PR DESCRIPTION
**Pull request by aaugustin**

### CODE REVIEW

**Comment by aaugustin** [comment]
I force-pushed to re-run the CLA check, which is now passing.

**Comment by aaugustin** [comment]
Fuzzing targets are [available in the main branch of websockets](https://github.com/aaugustin/websockets/commit/fd17f4684ef41750bdad09e09e22ee9a653f1238).

I wasn't able to test them locally due to a qemu crash on M1. I would like to test them with CIFuzz; however, adding the project to OSS-Fuzz is a prerequisite to CIFuzz, creating a chicken <> egg situation.

If the fuzzing targets don't work in their current state, I'd still ask to merge this PR so I can configure CIFuzz and fix the targets without bothering you.

**Comment by DavidKorczynski** [comment]
> I wasn't able to test them locally due to a qemu crash on M1. I would like to test them with CIFuzz; however, adding the project to OSS-Fuzz is a prerequisite to CIFuzz, creating a chicken <> egg situation.

Have you tried ClusterFuzzLite? https://google.github.io/clusterfuzzlite/ This enables you to do fuzzing in the CI without OSS-Fuzz integration. I think that might be ideal for your case.

**Comment by aaugustin** [comment]
Thank you, I'm trying that now.

**Comment by aaugustin** [comment]
This PR passes the bad build checks.

My ClusterFuzzLite setup fails these checks, despite using the same configuration, with the following error:

<details>

Excerpt from https://github.com/aaugustin/websockets/runs/7983340083?check_suite_focus=true

```
Build check: stdout: INFO: performing bad build checks for /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parserINFO: performing bad build checks for
 /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser
Retrying failed fuzz targets sequentially 2
INFO: performing bad build checks for /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser
INFO: performing bad build checks for /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser
Broken fuzz targets 2
('/tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser'], returncode=2, stdout=b'BAD BUILD /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser is not built for architecture: x86_64\nfile command output: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: POSIX shell script, ASCII text executable\ncheck_mixed_sanitizers test will fail.\nBAD BUILD: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser does not seem to be compiled with ASan.\n', stderr=b'objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: file format not recognized\nobjdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: file format not recognized\nobjdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: file format not recognized\nobjdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: file format not recognized\n'))
BAD BUILD /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser is not built for architecture: x86_64
file command output: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: POSIX shell script, ASCII text executable
check_mixed_sanitizers test will fail.
BAD BUILD: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser does not seem to be compiled with ASan.
objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: file format not recognized
objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: file format not recognized
objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: file format not recognized
objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_request_parser: file format not recognized

('/tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser'], returncode=2, stdout=b'BAD BUILD /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser is not built for architecture: x86_64\nfile command output: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: POSIX shell script, ASCII text executable\ncheck_mixed_sanitizers test will fail.\nBAD BUILD: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser does not seem to be compiled with ASan.\n', stderr=b'objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: file format not recognized\nobjdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: file format not recognized\nobjdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: file format not recognized\nobjdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: file format not recognized\n'))
BAD BUILD /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser is not built for architecture: x86_64
file command output: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: POSIX shell script, ASCII text executable
check_mixed_sanitizers test will fail.
BAD BUILD: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser does not seem to be compiled with ASan.
objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: file format not recognized
objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: file format not recognized
objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: file format not recognized
objdump: /tmp/not-out/tmpa9ttl_vg/fuzz_http11_response_parser: file format not recognized

ERROR: 100.0% of fuzz targets seem to be broken. See the list above for a detailed information.
```

</details>

I'm not sure where to start to understand why `compile_python_fuzzer ` gives different results with OSS-Fuzz and ClusterFuzzLite.

Since the OSS-Fuzz setup appears to work, maybe we can go with that?

**Comment by jonathanmetzman** [comment]
> 

Not sure if this is the exact issue, but you need to specify python here instead of C++: https://github.com/aaugustin/websockets/actions/runs/2914902079/workflow#L26

**Comment by jonathanmetzman** [comment]
> > 
> 
> Not sure if this is the exact issue, but you need to specify python here instead of C++: https://github.com/aaugustin/websockets/actions/runs/2914902079/workflow#L26

Actually I think this is the problem

**Comment by aaugustin** [comment]
Yes that was the problem 🤦‍♂️

(FWIW the [clusterfuzz documentation](https://google.github.io/clusterfuzzlite/running-clusterfuzzlite/github-actions/#pr-fuzzing) says "copy paste-this and maybe customize `sanitizers` or `fuzz-seconds`". It doesn't mention `language` and I didn't spot it.)

Fuzzing targets [ran successfully](https://github.com/aaugustin/websockets/runs/7987940342?check_suite_focus=true) for a few minutes at 100k execs/second, which sounds like a good starting point. No crashes found yet.

**Comment by aaugustin** [comment]
Please let me know if you need anything else from me here!

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by aaugustin** [comment]
Thank you!

**Pull request merged**
