### PR TITLE
Integrate Aptos core repository

### PR DESCRIPTION
**Pull request by gedigi**
Aptos is a Move-based layer 1 blockchain designed for safe development and user experience.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Are you interested in integrating this into oss-fuzz? Please sign the CLA.

**Comment by gedigi** [comment]
Hi Jonathan, I'm working with our legal team to finalize the CLA for our organization. Sorry for the delay.

As far as the project, Aptos is a Move-based layer 1 blockchain designed for safe development and user experience. As it's an open source code and infrastructure, we would like to onboard into oss-fuzz for fuzz testing.

We are already partnering with Google on multiple fronts (e.g. https://medium.com/aptoslabs/aptos-and-google-cloud-partner-to-support-web3-builders-a9c8ba51c500 https://aptosfoundation.org/currents/aptos-commits-to-google-cloud-web3-startup-program)

**Comment by gedigi** [comment]
@jonathanmetzman I had the CLA signed for Aptos Labs but the check still shows as failing. Refreshed the test as instructed. Can you please check what’s missing? Thank you

**Comment by gedigi** [comment]
I followed the instructions in the CLA Check:
- The Google group regulating access to contribute to google is google-oss-contributors@aptoslabs.com, which I'm part of.
- My aptoslabs.com email is associated with my GitHub account
- I unchecked to keep my email private changed the commit's author

However I'm still not able to pass the test. Can you please assist?

**Comment by gedigi** [comment]
@jonathanmetzman @oliverchang this PR is ready for review - please advice on next steps.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
