### PR TITLE
Bump FI and adjust the path to main.py in compile

### PR DESCRIPTION
**Pull request by Navidem**
This only has to be merged after successful trial_build

### CODE REVIEW

**Comment by Navidem** [comment]
/gcbrun trial_build.py htslib leveldb jsoncpp unrar fio --sanitizer introspector --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
I didn't know that introspector worked with trial builds.

**Comment by DavidKorczynski** [comment]
Can we bump this first after https://github.com/ossf/fuzz-introspector/issues/412 is closed? I'm working on some minor nits that will be pushed in a few hours and then ready to go

**Comment by jonathanmetzman** [comment]
> I didn't know that introspector worked with trial builds.

It doesn't. Look how it isn't building the introspector images. The projects are built with an old (pre-PR) version of introspector
intro

**Comment by Navidem** [comment]
>Can we bump this first after https://github.com/ossf/fuzz-introspector/issues/412 is closed?

Not merging this until I have it tested.

>It doesn't. Look how it isn't building the introspector images. The projects are built with an old (pre-PR) version of introspector 

Thanks @jonathanmetzman for checking!

**Comment by Navidem** [comment]
/gcbrun trial_build.py skcms --sanitizer address --fuzzing-engine libfuzzer

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Pull request merged**
