### PR TITLE
Fix the build

### PR DESCRIPTION
**Pull request by kimkulling**
- Remove deprecated lib irrXml

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Build seems to still fail.

```
[230/230] Linking CXX static library lib/libassimp.a
+ clang++ -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=address -fsanitize-address-use-after-scope -fsanitize=fuzzer-no-link -stdlib=libc++ -std=c++11 -I/src/assimp/include fuzz/assimp_fuzzer.cc -o /out/assimp_fuzzer -fsanitize=fuzzer /src/assimp/lib/libassimp.a /src/assimp/lib/libzlibstatic.a
clang-12: error: no such file or directory: '/src/assimp/lib/libzlibstatic.a'
Building fuzzers failed.
Running: docker build -t gcr.io/oss-fuzz/assimp projects/assimp
Keeping existing build artifacts as-is (if any).
Running: docker run --rm --privileged --cap-add SYS_PTRACE -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c++ -v /home/runner/work/oss-fuzz/oss-fuzz/build/out/assimp:/out -v /home/runner/work/oss-fuzz/oss-fuzz/build/work/assimp:/work -t gcr.io/oss-fuzz/assimp
Building project assimp
Running command: python /home/runner/work/oss-fuzz/oss-fuzz/infra/helper.py build_fuzzers assimp --engine libfuzzer --sanitizer address --architecture x86_64
Failed projects: assimp
```

**Comment by kimkulling** [comment]
Right, I am still trying to find the time working on that issue.

**Comment by inferno-chromium** [comment]
you can try this locally using
python infra/helper.py build_fuzzers command
no need to worry about CI, can try locally on address sanitizer first.

**Comment by kimkulling** [comment]
I know, my linux is currently away. Sorry for the inconvenience!

**Comment by kimkulling** [comment]
Ok, I will solve this locally.

**Comment by DavidKorczynski** [comment]
This one can be closed now. It was fixed in https://github.com/google/oss-fuzz/pull/5560

**Pull request closed without merging**
