### PR TITLE
openssl: Remove hlandau@openssl.org as that e-mail is no longer active

### PR DESCRIPTION
**Pull request by t8m**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Could you please sign the CLA?

**Comment by t8m** [comment]
Do I have to for such trivial change?

**Comment by DavidKorczynski** [comment]
> Do I have to for such trivial change?

yes, but I put up a PR here https://github.com/google/oss-fuzz/pull/12134 with the same change -- can you add a LGTM to that PR then it can be merged from there without you signing the cla here.

**Comment by t8m** [comment]
Closing this as superseded by #12134

**Pull request closed without merging**
