### PR TITLE
Use git repo for Dropbear instead

### PR DESCRIPTION
**Pull request by mkj**
Git repo might work for code coverage

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Is this your personal repo ? We prefer official code repositories to be used in OSS-Fuzz (for code trust).

**Comment by mkj** [comment]
Yes it is. I'm avoiding pushing the fuzzing branch to the official github mirror until I've figured if it will be merged to the main branch.

I'd prefer to keep pointing at the canonical mercurial upstream (what it has currently) but thought this would solve code coverage not showing https://github.com/google/oss-fuzz/issues/628

**Comment by inferno-chromium** [comment]
@oliverchang - thoughts ? i am fine with this as a temporary solution if we can't fix #628.

**Comment by oliverchang** [comment]
Hmm, I'd rather we always use the official repositories. I think #628 should be fixable -- it should just be a matter of adding an entry to our source fetcher.

**Comment by oliverchang** [comment]
Closing this as #628 is now fixed.

**Pull request closed without merging**
