### PR TITLE
Update the Keycloak contacts

### PR DESCRIPTION
**Pull request by abstractj**
@arthurscchan @AdamKorcz @jonathanmetzman we created a dedicated mailing list for oss-fuzz and I would like us to change it. The change aims to have a focused communication channel for build failures and potential alerts about it. Could you please review?

//cc @stianst

### CODE REVIEW

**Comment by AdamKorcz** [comment]
@abstractj Could you sign the CLA?

**Comment by abstractj** [comment]
Thank you @AdamKorcz hopefully it is all set now.

**Comment by AdamKorcz** [comment]
@abstractj The CLA seems to not be signed yet for this email: `b***o​@abstractj.com`

**Comment by abstractj** [comment]
@AdamKorcz thank you, I hadn't realized that I had to trigger those checks again. Now, it should be ready.

**Review by AdamKorcz — APPROVED** [review]

**Pull request merged**
