### PR TITLE
Add gary miller to auto_ccs.

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Fixes #9274

**Comment by jonathanmetzman** [comment]
@garyemiller can you show me some proof youre a project maintainer?

**Comment by garyemiller** [comment]
Yo jonathanmetzman!

On Tue, 27 Dec 2022 08:59:22 -0800
jonathanmetzman ***@***.***> wrote:

> @garyemiller can you show me some proof youre a project maintainer?

Sure, send an email to security, or contact.  Or look in the git log.

You keep sending me emails with links I can't read, someone on your end
thinks I belong.

RGDS
GARY
---------------------------------------------------------------------------
Gary E. Miller Rellim 109 NW Wilmington Ave., Suite E, Bend, OR 97703
	***@***.***  Tel:+1 541 382 8588

	    Veritas liberabit vos. -- Quid est veritas?
    "If you can't measure it, you can't improve it." - Lord Kelvin

**Comment by jonathanmetzman** [comment]
> Yo jonathanmetzman!
> On Tue, 27 Dec 2022 08:59:22 -0800 jonathanmetzman ***@***.***> wrote: @garyemiller can you show me some proof youre a project maintainer?

Proof is here: https://gitlab.com/NTPsec/ntpsec/-/project_members

> Sure, send an email to security, or contact. Or look in the git log. You keep sending me emails with links I can't read, someone on your end thinks I belon

I'm guessin you were getting those emails because you receive mail from contact@ntpsec.org or security@ntpsec.org

**Comment by jonathanmetzman** [comment]
TBR

**Comment by garyemiller** [comment]
Yo jonathanmetzman!

On Tue, 27 Dec 2022 10:43:08 -0800
jonathanmetzman ***@***.***> wrote:

> > Yo jonathanmetzman!
> > On Tue, 27 Dec 2022 08:59:22 -0800 jonathanmetzman ***@***.***>
> > wrote: @garyemiller can you show me some proof youre a project
> > maintainer?  
> 
> Proof is here: https://gitlab.com/NTPsec/ntpsec/-/project_members

True that.

> > Sure, send an email to security, or contact. Or look in the git
> > log. You keep sending me emails with links I can't read, someone on
> > your end thinks I belon  
> 
> I'm guessin you were getting those emails because you receive mail
> from ***@***.*** or ***@***.***

Not an or, both.

RGDS
GARY
---------------------------------------------------------------------------
Gary E. Miller Rellim 109 NW Wilmington Ave., Suite E, Bend, OR 97703
	***@***.***  Tel:+1 541 382 8588

	    Veritas liberabit vos. -- Quid est veritas?
    "If you can't measure it, you can't improve it." - Lord Kelvin

**Pull request merged**
