### PR TITLE
Add more fileformats to libgd's fuzzer

### PR DESCRIPTION
**Pull request by Google-Autofuzz**
- Add more formats to libgd's fuzzer
- Reorder the fuzzer's names
- Add some corpus for the new fuzzers

### CODE REVIEW

**Comment by Dor1s** [comment]
Travis is unhappy, looks like there is no seed corpus for some of the formats, and `zip` command fails there. Did you try building this locally before uploading a PR?

**Comment by Google-Autofuzz** [comment]
Nope, I erroneously thought that this would be a trivial fix, and of course, it wasn't :)

**Comment by Dor1s** [comment]
The title says "WIP", is it still WIP or is ready to merge now?

**Comment by Google-Autofuzz** [comment]
Absolutely :)

**Pull request merged**
