### PR TITLE
[cryptofuzz] Update mpdecimal to version 2.5.1

### PR DESCRIPTION
**Pull request by skrah**

### CODE REVIEW

**Comment by skrah** [comment]
@googlebot I signed it!

**Review by inferno-chromium — APPROVED** [review]

**Comment by guidovranken** [comment]
Thanks @skrah !

```
 Step 23/35 : RUN hg clone https://gmplib.org/repo/gmp/ libgmp/
 ---> Running in 02dfc2fa1990
abort: HTTP Error 500: Internal Server Error
```

Unfortunately the libgmp server is frequently down, I wish they would get proper hosting like Github. Please retrigger to CI to retry.

**Comment by inferno-chromium** [comment]
> Thanks @skrah !
> 
> ```
>  Step 23/35 : RUN hg clone https://gmplib.org/repo/gmp/ libgmp/
>  ---> Running in 02dfc2fa1990
> abort: HTTP Error 500: Internal Server Error
> ```
> 
> Unfortunately the libgmp server is frequently down, I wish they would get proper hosting like Github. Please retrigger to CI to retry.

retriggered but some are still failing,.

**Comment by skrah** [comment]
The force push was supposed to trigger the build again, but apparently the workflow needs to be re-approved.

**Comment by DavidKorczynski** [comment]
> The force push was supposed to trigger the build again, but apparently the workflow needs to be re-approved.

re-triggered now.

**Comment by skrah** [comment]
Thank you!  I guess the `gmp` clone is still failing:

```
The command '/bin/sh -c hg clone https://gmplib.org/repo/gmp/ libgmp/' returned a non-zero code: 255
```

**Comment by DavidKorczynski** [comment]
Could we do something where we exit gracefully in case the server is down?

**Comment by skrah** [comment]
Perhaps https://gmplib.org/repo/gmp/ has a rate limit for GitHub?  I can clone just fine here (from Europe, tried multiple times).

**Pull request merged**
