### PR TITLE
Set parser recursion limit for fuzz tests.

### PR DESCRIPTION
**Pull request by jnthntatum**
Very large inputs that generate large ASTs can cause some of the sanitizers to timeout. Setting a smaller complexity limit should help filter out those cases.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by Navidem** [comment]
Please check the CI failures.

**Comment by jnthntatum** [comment]
I think I submitted the PR before the corresponding google/cel-go PR had been merged [#594](https://github.com/google/cel-go/pull/594). I was able to get sanitizers  building on my machine with the infra/helper.py tool -- is there anything else I should check?

**Review by Navidem — APPROVED** [review]
LGTM

**Pull request merged**
