### PR TITLE
infra: Update Jazzer to fix coverage build failures

### LINKED ISSUE #8241: Java coverage builds are failing
See https://oss-fuzz-build-logs.storage.googleapis.com/log-71bca0f6-29c8-448a-98b2-335054df3cb0.txt

@jonathanmetzman Could this be related to https://github.com/google/oss-fuzz/commit/ddd25e3c3f6990c3f2d32c7b7787092bbdcf7ea4? It looks like the report has been generated and uploaded at that point, which makes me think this is not a regression in Jazzer.

### PR DESCRIPTION
**Pull request by fmeum**
Fixes #8241

### CODE REVIEW

**Comment by fmeum** [comment]
@jonathanmetzman @oliverchang I manually verified that `run_fuzzer`, `reproduce` and `coverage` work for a representative project with this change.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jackson-core jackson-databind jackson-dataformat-xml jackson-dataformats-binary javaparser json-java --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by fmeum** [comment]
@jonathanmetzman Are the logs of the failed run publicly accessible? I just found a GCB link that isn't.

**Comment by jonathanmetzman** [comment]
THey are not public. But the failure is mine not yours.

**Comment by jonathanmetzman** [comment]
I need you to pull from master for me to test this properly
(I think it would be easier in the future if you allowed me to edit your forked repo, I can do this for most people and if I could do it for you I would have been able to test now :-)

**Comment by fmeum** [comment]
@jonathanmetzman Rebased onto master. I don't see the usual option to give you edit rights. Maybe that's because I'm pushing from an org fork and my org doesn't allow it? I will try pushing from a personal fork next time.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py jackson-core jackson-databind jackson-dataformat-xml jackson-dataformats-binary javaparser json-java --sanitizer address memory undefined coverage --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
Thanks! Lets hope this works

**Comment by fmeum** [comment]
@jonathanmetzman It does :)

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
