### PR TITLE
Improve ruby integration.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
1. Move more installation to the bash script.
2. Don't use apt, use apt-get instead.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
cc @mschwager @AdvenamTacet

**Review by AdvenamTacet — COMMENTED** [review]
LGTM, if it works.

I don't see how to fix the error, tho.

```
=> ERROR [stage-3 16/18] COPY --from=base-ruby /install/ruzzy /install/ruzzy                                                                                                                                 0.0s
------                                                                                                                                                                                                             
 > [stage-3 16/18] COPY --from=base-ruby /install/ruzzy /install/ruzzy:                                                                                                                                            
------ 
[...]
--------------------
  91 |     # Copy built ruby and ruzzy from builder
  92 |     COPY --from=base-ruby /usr/local/rvm /usr/local/rvm
  93 | >>> COPY --from=base-ruby /install/ruzzy /install/ruzzy
  94 |     COPY ruzzy /usr/bin/ruzzy
  95 |     ENV PATH="$PATH:/usr/local/rvm/rubies/ruby-3.3.1/bin"
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 662516d2-2996-48ac-8399-dc46261754d7::3kvt82hgl20wvq9ap7irioy8m: "/install/ruzzy": not found
```

This path doesn't exist in base-builder-ruby with that change.

Edit: interesting, it looks like it works in tests here, but not locally for me.

**Comment by jonathanmetzman** [comment]
Sorry, this PR is out of date, I'm not near a computer now but my latest
work on this problem is https://github.com/google/oss-fuzz/pull/12199 I
think we're close to fixing this because we only need to fix detection of
targets.

**Comment by oliverchang** [comment]
Closing in favour of [#12199](https://github.com/google/oss-fuzz/pull/12199)

**Pull request closed without merging**
