### PR TITLE
Bump to include latest changes

### PR DESCRIPTION
**Pull request by Navidem**

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by DavidKorczynski** [comment]
There has been some updates to the UI since this PR -- could we bump it to the latest as of this writing so we can get those as well?

Most recent commit as of this writing: https://github.com/ossf/fuzz-introspector/commit/2489496857f473b7bdd01f8cb7c2b3564d1273b4

**Comment by Navidem** [comment]
> There has been some updates to the UI since this PR -- could we bump it to the latest as of this writing so we can get those as well?
> 
> Most recent commit as of this writing: [ossf/fuzz-introspector@2489496](https://github.com/ossf/fuzz-introspector/commit/2489496857f473b7bdd01f8cb7c2b3564d1273b4)

Done.

**Comment by DavidKorczynski** [comment]
It seems like the issue is here? 

https://github.com/google/oss-fuzz/blob/dd8e46c38b11788db8ac42de0d27fc11abfcdbae/infra/base-images/base-builder/install_swift.sh#L45-L47

Maybe pin the LLVM version for swift? Or, use `sed` commands similar to fuzz-introspector (we use seds to avoid diffs failing when they shouldn't https://github.com/google/oss-fuzz/pull/7322#issuecomment-1049139810 -- althought it's hacky)

**Comment by DavidKorczynski** [comment]
> It seems like the issue is here?
> 
> https://github.com/google/oss-fuzz/blob/dd8e46c38b11788db8ac42de0d27fc11abfcdbae/infra/base-images/base-builder/install_swift.sh#L45-L47
> 
> Maybe pin the LLVM version for swift? Or, use `sed` commands similar to fuzz-introspector (we use seds to avoid diffs failing when they shouldn't [#7322 (comment)](https://github.com/google/oss-fuzz/pull/7322#issuecomment-1049139810) -- althought it's hacky)

CC @catenacyber @jonathanmetzman

**Comment by catenacyber** [comment]
I guess I just need to rebase the patch and fix there conflicts...

**Comment by DavidKorczynski** [comment]
> I guess I just need to rebase the patch and fix there conflicts...

yep, I was more thinking from a precautionary approach for future references though

**Pull request merged**
