### PR TITLE
bitcoin-core: Remove centipede for now

### PR DESCRIPTION
**Pull request by MarcoFalke**
Attempt to work around the build timeout for now ( https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=58304 )

### CODE REVIEW

**Review by fanquake — APPROVED** [review]
ACK 6c1dc6e96d9362d99b7978be8aa41b6fe73f16ea

**Comment by dergoegge** [comment]
Wasn't LTO the problem?

**Comment by fanquake** [comment]
It would be good to know more about how build resources are allocated. I guess the CI passing here is no indication that the builds will actually work / wont timeout.

**Comment by jonathanmetzman** [comment]
> It would be good to know more about how build resources are allocated. I guess the CI passing here is no indication that the builds will actually work / wont timeout.

Bitcoin is an edge case here. It's not a guarantee but it's a strong indication. Bitcoin passes CI but fails prod build because prod build is done sequentially while CI is done in parallel (so timeout for all builds is 36 hours instead of 6)

**Comment by dergoegge** [comment]
ACK 6c1dc6e96d9362d99b7978be8aa41b6fe73f16ea

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
