### PR TITLE
Fix jsc build

### PR DESCRIPTION
**Pull request by syg**
Apple engineers reached out to inform us that the JSC build is broken because WebKit has migrated from their own Git instance to GitHub.

### CODE REVIEW

**Comment by hogo6002** [comment]
@syg Hi Shu-yu, the PR failed due to a known issue. I have just checked-in the fix and will update branch and reopen the PR.

**Comment by syg** [comment]
I am a Googler btw. Not sure the CLA requirements around here.

**Comment by hogo6002** [comment]
> I am a Googler btw. Not sure the CLA requirements around here.

You may also want to modify the [docker file](https://github.com/google/oss-fuzz/blob/d6c046c00cca8eab1bf3a507250b284f01c8b9c8/projects/jsc/Dockerfile#LL20C1-L20C56)

**Comment by syg** [comment]
The failing test looks like a build failure in WK, not actionable from my side.

**Comment by ddkilzer** [comment]
@hogo6002 The "build" is failing now because the git repo URL no longer exists.

Please commit this fix first, then someone will be able to fix the actual build failure.

**Comment by ddkilzer** [comment]
Cc @inferno-chromium @oliverchang FYI

**Review by inferno-chromium — APPROVED** [review]

**Comment by inferno-chromium** [comment]
lgtm, i agree we need to merge this first and tests are expected to fail, but will let build failures propogate to the dev via bug filed.

**Comment by ddkilzer** [comment]
Thanks!  Fixing first build failure here:  https://github.com/WebKit/WebKit/pull/15373

**Pull request merged**
