### PR TITLE
[traefik] Initial integration

### PR DESCRIPTION
**Pull request by AdamKorcz**
@ldez @rtribotte @jbdoumenjou @juliens @kevinpollet
Are you insterested in integrating Traefik into OSS-fuzz for continuous fuzzing?
This PR adds the build files and two fuzzers.

To complete the PR, a maintainers email address is needed for bug reports.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
@SantoDE Are you interested in setting up continuous fuzzing for Traefik?

All that is needed at this point is a maintainers email address for potential bug reports, and we are ready to have this reviewed!

**Comment by AdamKorcz** [comment]
@santoDE kind ping.

**Comment by AdamKorcz** [comment]
@ldez @rtribotte @jbdoumenjou @juliens @kevinpollet Kind ping

**Comment by ldez** [comment]
Thank you, we are not interested for now.

**Pull request closed without merging**
