### PR TITLE
infra: fix ci failure

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
Trying to fix:

```sh
Run df -h
  df -h
  sudo swapoff -a
  sudo rm -f /swapfile
  sudo apt clean
  docker rmi $(docker images -a -q)
  df -h
  echo "Remove large unused folders, inspired by https://github.com/apache/flink/blame/master/tools/azure-pipelines/free_disk_space.sh"
  sudo bash -c '(ionice -c 3 nice -n 19 rm -rf /usr/share/dotnet/ /usr/local/graalvm/ /usr/local/.ghcup/ /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/android /usr/local/lib/node_modules)&'
  shell: /usr/bin/bash -e {0}
  env:
    ENGINE: centipede
    SANITIZER: none
    ARCHITECTURE: x86_64
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        7[2](https://github.com/google/oss-fuzz/actions/runs/12410013641/job/34644760311?pr=12870#step:4:2)G   44G   29G  61% /
tmpfs           7.9G   84K  7.9G   1% /dev/shm
tmpfs           [3](https://github.com/google/oss-fuzz/actions/runs/12410013641/job/34644760311?pr=12870#step:4:3).2G  1.1M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sdb16      881M   59M  761M   8% /boot
/dev/sdb15      105M  6.1M   99M   6% /boot/efi
/dev/sda1        7[4](https://github.com/google/oss-fuzz/actions/runs/12410013641/job/34644760311?pr=12870#step:4:4)G  4.1G   66G   6% /mnt
tmpfs           1.[6](https://github.com/google/oss-fuzz/actions/runs/12410013641/job/34644760311?pr=12870#step:4:6)G   12K  1.6G   1% /run/user/1001

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

"docker rmi" requires at least 1 argument.
See 'docker rmi --help'.

Usage:  docker rmi [OPTIONS] IMAGE [IMAGE...]

Remove one or more images
```

seen in https://github.com/google/oss-fuzz/pull/12870 and https://github.com/google/oss-fuzz/pull/12869

**Comment by DavidKorczynski** [comment]
CC @jonathanmetzman @oliverchang moving forward with this to get the CI working again

**Review by AdamKorcz — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
Interesting, I guess there are no images to remove.

**Comment by jonathanmetzman** [comment]
lgtm

**Pull request merged**
