### PR TITLE
netty: Add fuzz test for HttpRequestDecoder

### PR DESCRIPTION
**Pull request by yawkat**
This is my initial PR to get my feet wet, sort out the CLA, so it's just a small change.

The main change is a fuzzer for HttpRequestDecoder. This fuzzer reproduces the bug fixed by https://github.com/netty/netty/pull/13735 .

I also added myself to the contact list of the netty project. This was approved by @normanmaurer in January: https://github.com/netty/netty/issues/13033#issuecomment-1911318993 – unfortunately it took me until now to get corp approval for the CLA.

### CODE REVIEW

**Comment by yawkat** [comment]
@aschaich Can you approve this?

**Review by chrisvest — APPROVED** [review]

**Review by DonggeLiu — APPROVED** [review]

**Comment by yawkat** [comment]
@DonggeLiu It seems the original contributor is MIA, looks like it was one of the CodeIntelligence folks. I have approval from the netty team, including \@chrisvest, the primary contact for this project.

Also, while building #12773, I thought a similar approach may be useful for netty, to move the tests into a project in the netty github org. But I'll look at that in another PR.

**Comment by DonggeLiu** [comment]
OK I will merge this, thanks!

**Comment by yawkat** [comment]
Thanks!

**Pull request merged**
