### PR TITLE
tensorflow: fix build and ci

### PR DESCRIPTION
**Pull request by DavidKorczynski**
- Enables Fuzztest fuzzers for tensorflow
- Makes CI passable (almost, sometimes it passess other times it timeouts, it seems to be close to the time limit) by limiting instrumentation and number of fuzzers build in CI
- Adjusts some resources at build time to fix the Tensorflow build error: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=51443

Signed-off-by: David Korczynski <david@adalogics.com>

### CODE REVIEW

**Review by AdamKorcz — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
> Thank you!
> 
> CC @fcoUnda

np! @mihaimaruseac @fcoUnda are you happy with me going ahead with this? I'd like to assist with the Tensorflow fuzzing and I thought a good first step is getting the build to run again and also enable the fuzztest fuzzers.

Would you be okay with me putting my email in the `project.yaml`? That'll be helpful with tracking progress, build issues and bugs

**Comment by mihaimaruseac** [comment]
It's ok from my pov, but I left TF team last year to join GOSST. So depends on @fcoUnda and @learning-to-play

**Comment by learning-to-play** [comment]
Hi @mihaimaruseac, We're happy adding @DavidKorczynski. Will [this](https://github.com/google/oss-fuzz/pull/9401) help?

**Review by learning-to-play — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
> Hi @mihaimaruseac, We're happy adding @DavidKorczynski. Will [this](https://github.com/google/oss-fuzz/pull/9401) help?

Yes, that PR will do the job! I'm gonna rerun the CI in that PR now that this PR has been merged (which should fix the CI)

**Pull request merged**
