### PR TITLE
[gRPC] Update Bazel submodules

### LINKED ISSUE #1026: grpc build is broken
https://oss-fuzz-build-logs.storage.googleapis.com/index.html

```
Step #3: + bazel build --dynamic_mode=off --spawn_strategy=standalone --genrule_strategy=standalone --strip=never --copt=-O1 --linkopt=-O1 --copt=-fno-omit-frame-pointer --linkopt=-fno-omit-frame-pointer --copt=-gline-tables-only --linkopt=-gline-tables-only --copt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --linkopt=-DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION --copt=-fsanitize=address --linkopt=-fsanitize=address --copt=-fsanitize-address-use-after-scope --linkopt=-fsanitize-address-use-after-scope --copt=-fsanitize=fuzzer-no-link --linkopt=-fsanitize=fuzzer-no-link --copt=-fno-sanitize=vptr --linkopt=-fno-sanitize=vptr :all test/core/util/... test/core/end2end/... third_party/nanopb/... @boringssl//:all @submodule_zlib//:all @submodule_cares//:all
Step #3: Extracting Bazel installation...
Step #3: .........
Step #3: ERROR: no such package '@submodule_cares//': error loading package 'external': The repository named 'submodule_cares' could not be resolved.
Step #3: ERROR: no such package '@submodule_cares//': error loading package 'external': The repository named 'submodule_cares' could not be resolved.
Step #3: ____Elapsed time: 3.113s
Finished Step #3
ERROR
```

//cc @matt-kwong

### PR DESCRIPTION
**Pull request by matt-kwong**
Fixes #1026

### CODE REVIEW

**Comment by Dor1s** [comment]
Thanks Matt! Any chance to move build.sh script to the upstream up eventually? :)

**Comment by matt-kwong** [comment]
Is there a new policy that the build script should reside in the project's repo instead of oss-fuzz's? That's definitely doable for us.

**Comment by Dor1s** [comment]
It's part of the ideal integration guide: https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md#build-support

And it has obvious benefits, e.g. when someone is changing modules upstream, they would also do that for this particular script (or any other build rule incorporated in e.g. Makefile)

**Comment by matt-kwong** [comment]
Agreed about making things maintainable. The guide you link says to move build rules to our project, and we can defintiely make the build targets for fuzzers, but I don't see anything about keeping the script upstream. Is there a project that does this that I can look at for reference?

**Comment by Dor1s** [comment]
Sorry, I didn't mean literally moving the script. My question was about moving build rules to the upstream, so the build.sh script in OSS-Fuzz repo can be super-short, e.g.:

```
make_or_whatever_other_command foo_fuzzer
```

**Comment by matt-kwong** [comment]
Gotcha, will do.

**Pull request merged**
