### PR TITLE
Add project dde-dock

### PR DESCRIPTION
**Pull request by hualet**
Project dde-dock is a main component of deepin OS, a widely used the Linux distribution (we have users around the whole world). It's our duty to make sure that the code of this project is clean and secure, so please accept this pull request :)

### CODE REVIEW

**Comment by hualet** [comment]
I signed it!

**Comment by mikea** [comment]
Hi!

Can you tell more about what kind of component is this? From the sound of it - it is a GUI component. I'm not sure how useful fuzzing engine would be here. Which input points did you have in mind?

**Comment by hualet** [comment]
Hi @mikea 

Sorry for no reply for so long, just off home for a buddy's wedding last weekend :)  

Yeah, it's  a GUI application much like the Dock app of macOS and the Taskbar of Windows. The project it self is not ready to be integrated yet(no corpus and input targets yet), I just wanted to make sure if this project can be accepted, and I'll complement the corpus and input targets part as the manual say.

Any advises?

**Comment by oliverchang** [comment]
Hi! Unfortunately we are not able to accept this project at this time.

Our fuzzing engines won't work well with GUI components, and at this point we are prioritising projects that are critical to user/infrastructure security -- GUI components typically accept input from the user, which is considered to be trusted.

Please see https://github.com/google/oss-fuzz/blob/master/docs/faq.md#what-kind-of-projects-are-you-accepting.

**Pull request closed without merging**
