### PR TITLE
Apache Lucene: Initial integration

### PR DESCRIPTION
**Pull request by henryrneh**

### CODE REVIEW

**Comment by dweiss** [comment]
Thank you. Your contribution is appreciated but Lucene already uses what you call a "fuzzer" - a reproducible, pseudo-random component assembly for tests... In fact, we have used it for many years now and indeed it's been successful at finding bugs in both Lucene and the JVM runtime. I'm not sure if there's any added value in what this patch provides.

**Comment by henryrneh** [comment]
As discussed in https://github.com/apache/lucene/issues/12165, the project will be onboarded without a maintainer for now, and bugs will be reported via public issues.

**Review by oliverchang — APPROVED** [review]

**Comment by oliverchang** [comment]
Is this ready to merge?

**Comment by henryrneh** [comment]
> Is this ready to merge?

@oliverchang yes it is ready to be merged, thank you!

**Pull request merged**
