### PR TITLE
Don't hold back images that can be upgraded.

### PR DESCRIPTION
**Pull request by jonathanmetzman**
This allows these projects to be compiled with centipede
Related: https://github.com/google/oss-fuzz/issues/9583

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py wasmtime wolfssl bearssl php num-bigint relic libecc nettle

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py wasmtime wolfssl bearssl php num-bigint relic libecc nettle

**Comment by jonathanmetzman** [comment]
I want to use gcbrun to see if this breaks coverage

**Comment by jonathanmetzman** [comment]
Relic coverage failure on GHA is out-of-space (spurious)

**Comment by jonathanmetzman** [comment]
Merge this if the wolfssl build completes (in about 3 hours) https://pantheon.corp.google.com/cloud-build/builds;region=us-central1/a2c8d316-81b0-4f3a-bf27-5e80b8ceb6d6?project=oss-fuzz

**Review by Alan32Liu — APPROVED** [review]
LGTM.
How do we determine if we can upgrade an image?
For example, [`php` is also not using the latest image](https://github.com/google/oss-fuzz/blob/master/projects/php/Dockerfile#L18), can we upgrade it?

**Comment by jonathanmetzman** [comment]
> LGTM. How do we determine if we can upgrade an image? For example, [`php` is also not using the latest image](https://github.com/google/oss-fuzz/blob/master/projects/php/Dockerfile#L18), can we upgrade it?

I held back projects that break with newer images. Determining if they can be upgraded is straightforward, just check that the build works :-) We could even automate this.

**Pull request merged**
