### PR TITLE
python-email-validator: initial integration

### PR DESCRIPTION
**Pull request by manunio**
[python-email-validator](https://github.com/JoshData/python-email-validator) is a robust email address syntax and deliverability validation library for Python. It has millions of downloads as per pypi and is used by projects like [fastapi](https://github.com/tiangolo/fastapi) or [pydantic](https://github.com/samuelcolvin/pydantic). @DavidKorczynski @jonathanmetzman  can this project be added to oss-fuzz?

Edit: waiting for permission from maintainer here: https://github.com/JoshData/python-email-validator/issues/84.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
We approve of adding this project.
Can you get upstream permission please

**Comment by manunio** [comment]
> What I'm trying to figure out here is if this is going to end up opening a lot of misdirected or spurious issues --- i.e. is this going to create new busywork for me. Before adding this project to OSS-Fuzz, I would ask you to try to sort through any issues that are going to arise immediately. If you think there might be a bug with the fuzzed inputs you generate, feel free to list them here and we can work through it.

Hi @jonathanmetzman John have raised some valid questions. but i'm not sure how to address this, can you please share your thoughts regarding this :)
 
https://github.com/JoshData/python-email-validator/issues/84#issuecomment-1204262500

**Comment by manunio** [comment]
Question by Josh:
> What I'm trying to figure out here is if this is going to end up opening a lot of misdirected or spurious issues --- i.e. is this going to create new busywork for me. Before adding this project to OSS-Fuzz, I would ask you to try to sort through any issues that are going to arise immediately. If you think there might be a bug with the fuzzed inputs you generate, feel free to list them here and we can work through it.
https://github.com/JoshData/python-email-validator/issues/84#issuecomment-1204262500

Response by me:
> https://github.com/JoshData/python-email-validator/issues/84#issuecomment-1204702941

Closing for now, till josh gives explicit permission.

**Comment by jonathanmetzman** [comment]
Well does upstream agree now?

**Pull request merged**
