### PR TITLE
Add myself to the notification list for libc++

### PR DESCRIPTION
**Pull request by jfbastien**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
Please sign the cla and we will merge. Closing due to lack of response.

**Comment by jfbastien** [comment]
Signing the CLA is not something I can do.

**Comment by oliverchang** [comment]
I've added you myself in https://github.com/google/oss-fuzz/commit/4e82ca2bdf644c23e2041a18397a516e6e7ad893

**Comment by jfbastien** [comment]
@oliverchang thanks! Can you add me to LLVM as well?

**Comment by inferno-chromium** [comment]
done added you to llvm project as well.

**Pull request closed without merging**
