### PR TITLE
tesseract-ocr: fix build for latest base builder

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Review by AdamKorcz — APPROVED** [review]

**Comment by stweil** [comment]
@DavidKorczynski, why did you replace the installation of `jbigkit` and `libtiff` by build instructions which depend on the latest code? This increased the build costs, and currently there is a build failure because of broken `libtiff` code.

**Comment by DavidKorczynski** [comment]
The change was made when the base builder image was updated from Ubuntu 18.04 to 20.04 by switching the Docker container to inherit `FROM gcr.io/oss-fuzz-base/base-builder:xenial` to `FROM gcr.io/oss-fuzz-base/base-builder`, so I assume building packages in the newer Ubuntu broke the build and building from source was needed.

Let me see if I can fix this by using the `jbigkit` and `libtiff` packages with the new base build somehow!

**Comment by DavidKorczynski** [comment]
@stweil I tried switching it back now to use the packages rather than the compiled sources, and this is the issue I get:
```
make[2]: Leaving directory '/src/tesseract/tessdata/tessconfigs'                                                                                                                                      
make[2]: Entering directory '/src/tesseract/tessdata'                                                                                                     
make[2]: Nothing to be done for 'all-am'.                                                                                                                 
make[2]: Leaving directory '/src/tesseract/tessdata'                                                                                                                                                  
make[1]: Leaving directory '/src/tesseract/tessdata'                                                                                                                                                  
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libtiff.a(tif_webp.o): in function `TWebPSetupDecode':                                                             
(.text+0x285): undefined reference to `WebPPictureFree'                                                                                                                                               
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libtiff.a(tif_webp.o): in function `TWebPPostEncode':                                                              
(.text+0x355): undefined reference to `WebPPictureImportRGB'                                                                                                                                                                           
/usr/bin/ld: (.text+0x36f): undefined reference to `WebPEncode'                                                                                                                                                                        
/usr/bin/ld: (.text+0x3d9): undefined reference to `WebPPictureImportRGBA'                                                                                                                            
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libtiff.a(tif_webp.o): in function `TWebPSetupEncode':                                                                                                                                          
(.text+0x692): undefined reference to `WebPPictureInitInternal'                                                                                                                                       
/usr/bin/ld: (.text+0x6bc): undefined reference to `WebPConfigInitInternal'                                                                                                                                                            
/usr/bin/ld: (.text+0x6e0): undefined reference to `WebPValidateConfig'                                                                                                                                                                
/usr/bin/ld: (.text+0x740): undefined reference to `WebPIDelete'                                                                                                                                                                       
/usr/bin/ld: (.text+0x74c): undefined reference to `WebPFreeDecBuffer'                                                                                                                                                                 
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libtiff.a(tif_webp.o): in function `TWebPDecode':                                                                                                                                               
(.text+0x8c8): undefined reference to `WebPIAppend'                                                                                                                                                                                    
/usr/bin/ld: (.text+0x924): undefined reference to `WebPIDecGetRGB'                                                                                                                                                                    
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libtiff.a(tif_webp.o): in function `TWebPPreDecode':                                                                                                                                            
(.text+0xaea): undefined reference to `WebPIDelete'                                                                                                                                                                                    
/usr/bin/ld: (.text+0xaf2): undefined reference to `WebPFreeDecBuffer'                                                                                                                                                                 
/usr/bin/ld: (.text+0xb14): undefined reference to `WebPInitDecBufferInternal'                                                                                                                                                         
/usr/bin/ld: (.text+0xb5d): undefined reference to `WebPINewDecoder'                                                                                                                                                                   
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libtiff.a(tif_webp.o): in function `TWebPCleanup':                          
(.text+0xd2f): undefined reference to `WebPIDelete'                                                                
/usr/bin/ld: (.text+0xd3b): undefined reference to `WebPFreeDecBuffer'                                                                                                                                                                 
/usr/bin/ld: (.text+0xd9d): undefined reference to `WebPPictureFree'                                                                                                                                                                   
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libtiff.a(tif_zstd.o): in function `ZSTDEncode':                            
(.text+0xea): undefined reference to `ZSTD_compressStream'                                                         
/usr/bin/ld: (.text+0xf5): undefined reference to `ZSTD_isError'                                                   
/usr/bin/ld: (.text+0x15c): undefined reference to `ZSTD_getErrorName'                                                                                                                                                                 
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libtiff.a(tif_zstd.o): in function `ZSTDPostEncode':                        
```

That's most likely the same issue that happened previously and why I switched to building `libtiff` from source.

How about switching it to use a stable commit of `libtiff` instead of pulling the latest? What do you think?

**Comment by stweil** [comment]
Thanks.

The linker errors are something which must be fixed on the Tesseract side. I can reproduce them locally and will have a look.

**Comment by DavidKorczynski** [comment]
okay, let me know if you would like assistance as I am happy to help

**Comment by stweil** [comment]
The linker errors should be fixed with latest Tesseract code.

**Comment by DavidKorczynski** [comment]
let's try! Didn't run it locally but we can let the CI tell us if it works https://github.com/google/oss-fuzz/pull/7350

**Pull request merged**
