### PR TITLE
minify: get latest version of minify

### PR DESCRIPTION
**Pull request by tdewolff**
I'm getting build errors for v1 which is not a supported version anymore.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
There is still build failure

```
+ /root/go/src/github.com/tdewolff/minify/tests/oss-fuzz-build.sh
/src/build.sh: line 17: /root/go/src/github.com/tdewolff/minify/tests/oss-fuzz-build.sh: No such file or directory
Building fuzzers failed.
Running: docker build -t gcr.io/oss-fuzz/minify projects/minify
Keeping existing build artifacts as-is (if any).
```

**Comment by tdewolff** [comment]
Waiting for #5243, see https://github.com/tdewolff/minify/blob/master/tests/oss-fuzz-build.sh for the `build.sh` script

**Comment by inferno-chromium** [comment]
This got fixed in another cl from @catenacyber , same patch (since couple of go projects were impacted).

**Comment by catenacyber** [comment]
Thanks @tdewolff, I should have mentioned my PR in my mail

**Pull request closed without merging**
