### PR TITLE
Initial commit [antlr4]

### PR DESCRIPTION
**Pull request by vargen**
@kyakdan @oliverchang

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by DavidKorczynski** [comment]
Please see this PR already https://github.com/google/oss-fuzz/pull/5555

**Comment by oliverchang** [comment]
Thanks! Should we rename this antlr4-java or something similar in that case?

**Comment by oliverchang** [comment]
@vargen could you please rename this project?

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
