### PR TITLE
Rename BaseRepoManager -> RepoManager.

### PR DESCRIPTION
**Pull request by oliverchang**
This was renamed in b0b99d5ccdf5e2e49cfe3138fbcf64e6fef6ea7f

### CODE REVIEW

**Comment by oliverchang** [comment]
@jonathanmetzman did we disable tests for this? was there any progress with figuring out the issues?

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
> @jonathanmetzman did we disable tests for this? was there any progress with figuring out the issues?

Sorry what issues? I don't think we disabled tests so I'm confused why this wasn't caught.

**Comment by oliverchang** [comment]
> > @jonathanmetzman did we disable tests for this? was there any progress with figuring out the issues?
> 
> Sorry what issues? I don't think we disabled tests so I'm confused why this wasn't caught.

Hmm, I remember there were some failures with these tests that required sudo and docker. Haven't been following if they were fixed or disabled. If they weren't disabled it is indeed weird why this wasn't caught..

**Pull request merged**
