### PR TITLE
Integrate libreoffice

### PR DESCRIPTION
**Pull request by caolanm**
initial libreoffice oss-integration

### CODE REVIEW

**Comment by mikea** [comment]
Nice. Let's give it a chance to build & run.

**Comment by mikea** [comment]
First build was successful and one fuzzer was detected. But oh boy, the build is slow. (~2h). Is there any way not to build the whole universe but only what's needed for fuzzer?

**Comment by caolanm** [comment]
This one simple target doesn't need this much so could possibly be customized to shrink it down, but future targets like doc/xls/ppt will need a lot of the stuff currently built but unused. Lots of stuff is already disabled from the build :-) https://cgit.freedesktop.org/libreoffice/core/tree/distro-configs/LibreOfficeOssFuzz.conf i.e. hunks of the gui, printing, database stuff, all locales except english, java support

**Comment by mikea** [comment]
Did you see the reports we've filed? Do they seem useful? 

I understand that your build system is very complicated. Let's keep it as is as long we generate useful reports. I'll try to get more cores if your builder becomes backed up.

In addition to adding more fuzzers you may also enable more sanitizers for your project once this stops finding new issues. (https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-libfuzzer/README.md#sanitizer-configuration)

**Comment by caolanm** [comment]
Oh yes, I've seen the (4) reports filed so far and they're good stuff so I'm very happy that everything is working as I hoped for. They're definitely useful and I've fixed everything reported to date (they've definitely been autoclosed as verified anyway) so integration is a success as far as I can see.

The build status isn't listed at https://oss-fuzz-build-logs.storage.googleapis.com/status.html however, do I need to do something at my side to add that ?

I'll leave things as they are over the holiday season and once reports stop coming in for this fuzzer we can expand the sanitizers and then we have at least 27 more format fuzzers to add to the current wmf one.

tl-dr: it's great

**Pull request merged**
