### PR TITLE
Build base-images with llvm16

### PR DESCRIPTION
**Pull request by Navidem**

### CODE REVIEW

**Comment by Navidem** [comment]
/gcbrun trial_build.py bzip2 --sanitizer address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
Is this really ready for review? I think you need to test every project with the roll.

**Comment by Navidem** [comment]
> Is this really ready for review? I think you need to test every project with the roll. And base-images is broken

No, it is far from ready yet.

**Comment by jonathanmetzman** [comment]
Do you mind if i make this a draft in the meantime?

**Comment by jonathanmetzman** [comment]
> Do you mind if i make this a draft in the meantime?

Nevermind i see you did this. Thanks!

**Comment by alexey-milovidov** [comment]
We need it for ClickHouse: https://github.com/ClickHouse/ClickHouse/pull/49678
But tt will be better to switch straight to llvm-17: https://github.com/ClickHouse/ClickHouse/pull/53831

What is the preferred way to override it in my project - can I install a different compiler in the Docker image and use it?

**Comment by oliverchang** [comment]
Thanks @maflcko !

**Pull request closed without merging**
