### PR TITLE
libzip: re-enable memory tests

### PR DESCRIPTION
**Pull request by 0-wiz-0**

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
@DavidKorczynski can you please take a look at this one too?

**Comment by DavidKorczynski** [comment]
@0-wiz-0 The CI is failing due to some issues found by MSAN in the first run of the fuzzer:

```
Uninitialized bytes in __interceptor_fwrite at offset 0 inside [0x7ffdd40b2520, 28)
==182==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x5865fe in _zip_stdio_op_write /src/libzip/lib/zip_source_file_stdio_named.c:280:11
    #1 0x595da5 in read_file /src/libzip/lib/zip_source_file_common.c:382:16
    #2 0x56bad0 in _zip_source_call /src/libzip/lib/zip_source_call.c:48:15
    #3 0x57d535 in zip_source_write /src/libzip/lib/zip_source_write.c:45:12
    #4 0x5560d2 in _zip_write /src/libzip/lib/zip_io_util.c:126:14
    #5 0x5395e4 in copy_source /src/libzip/lib/zip_close.c:626:13
    #6 0x5395e4 in add_data /src/libzip/lib/zip_close.c:498:11
    #7 0x535bae in zip_close /src/libzip/lib/zip_close.c:228:17
    #8 0x532ed2 in LLVMFuzzerTestOneInput /src/libzip/regress/zip_write_encrypt_aes256_file_fuzzer.c:63:9
    #9 0x43ddb3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #10 0x43f164 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:804:3
    #11 0x43f639 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:857:3
    #12 0x42ec9f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
    #13 0x4582f2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #14 0x7f8b1c74f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)
    #15 0x41f6dd in _start (/tmp/not-out/tmp1o48tyjm/zip_write_encrypt_aes256_file_fuzzer+0x41f6dd)

DEDUP_TOKEN: _zip_stdio_op_write--read_file--_zip_source_call
  Uninitialized value was stored to memory at
    #0 0x4dbbb4 in __msan_memcpy /src/llvm-project/compiler-rt/lib/msan/msan_interceptors.cpp:1570:3
    #1 0x58f480 in _zip_buffer_read /src/libzip/lib/zip_buffer.c:144:15
    #2 0x58aa35 in winzip_aes_encrypt /src/libzip/lib/zip_source_winzip_aes_encode.c:126:24
    #3 0x56b9b6 in _zip_source_call /src/libzip/lib/zip_source_call.c:51:15
    #4 0x57785d in zip_source_read /src/libzip/lib/zip_source_read.c:65:18
    #5 0x5394ff in copy_source /src/libzip/lib/zip_close.c:625:17
    #6 0x5394ff in add_data /src/libzip/lib/zip_close.c:498:11
    #7 0x535bae in zip_close /src/libzip/lib/zip_close.c:228:17
    #8 0x532ed2 in LLVMFuzzerTestOneInput /src/libzip/regress/zip_write_encrypt_aes256_file_fuzzer.c:63:9
    #9 0x43ddb3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #10 0x43f164 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:804:3
    #11 0x43f639 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:857:3
    #12 0x42ec9f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
    #13 0x4582f2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #14 0x7f8b1c74f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: __msan_memcpy--_zip_buffer_read--winzip_aes_encrypt
  Uninitialized value was created by a heap allocation
    #0 0x4e23d0 in malloc /src/llvm-project/compiler-rt/lib/msan/msan_interceptors.cpp:895:3
    #1 0x58a127 in winzip_aes_new /src/libzip/lib/zip_source_winzip_aes_encode.c:234:37
    #2 0x58a127 in zip_source_winzip_aes_encode /src/libzip/lib/zip_source_winzip_aes_encode.c:70:16
    #3 0x5392be in add_data /src/libzip/lib/zip_close.c:483:24
    #4 0x535bae in zip_close /src/libzip/lib/zip_close.c:228:17
    #5 0x532ed2 in LLVMFuzzerTestOneInput /src/libzip/regress/zip_write_encrypt_aes256_file_fuzzer.c:63:9
    #6 0x43ddb3 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:611:15
    #7 0x43f164 in fuzzer::Fuzzer::ReadAndExecuteSeedCorpora(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:804:3
    #8 0x43f639 in fuzzer::Fuzzer::Loop(std::__Fuzzer::vector<fuzzer::SizedFile, std::__Fuzzer::allocator<fuzzer::SizedFile> >&) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:857:3
    #9 0x42ec9f in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:912:6
    #10 0x4582f2 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:20:10
    #11 0x7f8b1c74f082 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24082) (BuildId: 1878e6b475720c7c51969e69ab2d276fae6d1dee)

DEDUP_TOKEN: malloc--winzip_aes_new--zip_source_winzip_aes_encode
SUMMARY: MemorySanitizer: use-of-uninitialized-value /src/libzip/lib/zip_source_file_stdio_named.c:280:11 in _zip_stdio_op_write
Exiting
MS: 0 ; base unit: 0000000000000000000000000000000000000000
```

Could you fix the issue upstream? then the CI will pass and we should be good to merge

**Comment by 0-wiz-0** [comment]
We'll take a look. It's just a sign that msan should have been enabled a long time ago :)

Could this be related to https://github.com/google/oss-fuzz/issues/11010 ?

**Comment by DavidKorczynski** [comment]
> Could this be related to #11010 ?

I don't think so. I think there are some coverage issues happening in other some other projects as well. I'll investigate.

**Comment by 0-wiz-0** [comment]
@DavidKorczynski : We don't understand this problem yet, but I've added some code to help debug this. How can I trigger a re-build using the latest libzip sources?

**Comment by DavidKorczynski** [comment]
> @DavidKorczynski : We don't understand this problem yet, but I've added some code to help debug this. How can I trigger a re-build using the latest libzip sources?

You can open and close this PR, that will re-trigger the runs.

Alternatively, you can:

```
git clone https://github.com/google/oss-fuzz
cd oss-fuzz
python3 infra/helper.py build_fuzzers --sanitizer=memory libzip
python3 infra/helper.py run_fuzzer --sanitizer=memory libzip name_of_the_fuzzer_that_failed
```

**Comment by DavidKorczynski** [comment]
@0-wiz-0 this looks good now, could you confirm this is ready for merge?

**Comment by 0-wiz-0** [comment]
@DavidKorczynski Yes and no.
We use openssl functions that write to a buffer - if it fails, we don't use the buffer.
But the memory sanitizer does not seem to recognize this.
We added some `memset()` that we think are unnecessary:

https://github.com/nih-at/libzip/commit/4434b5d559d7efd2ead2e546ff8e07ecacc54f0e
https://github.com/nih-at/libzip/commit/f0abc644e7a3ffe1ee890af94181b5acf09de816
https://github.com/nih-at/libzip/commit/82e30546f3a36f251faed7fecf2498b0aa2862b7

Can you advise what to do about these? We'd like to remove them again since they are (in our opinion) not needed.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
