### PR TITLE
[graphicsmagick] build for i386

### PR DESCRIPTION
**Pull request by alex**
I'm not 100% certain that this will work, but I don't see any reason it shouldn't either!

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
[Looks like i386 has failed here](https://api.travis-ci.org/v3/job/587250936/log.txt) because graphicsmagick is using `-lFuzzingEngine` instead of the preferred `$LIB_FUZZING_ENGINE`.

**Comment by alex** [comment]
Should be fixed in GM now.

**Comment by jonathanmetzman** [comment]
Restarted i386 job.

**Comment by jonathanmetzman** [comment]
I wonder if I should even bother waiting. It's very unlikely travis finishes. But maybe it will catch some early issues like the previous one.

**Comment by alex** [comment]
If it got far enough for you to see a failure before, I suppose it'll at least get far enough for you to see it _not fail_ now :-)

**Comment by alex** [comment]
Seems the build portion at least succeeded.

**Comment by jonathanmetzman** [comment]
Oh wow. I was confused, *Imagemagick* has super long build times, not GraphicsMagick.
I'll land when it times out/finishes then.

**Comment by alex** [comment]
All green!

**Pull request merged**
