### PR TITLE
Fix MSAN on github actions

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py systemd mbedtls knot-dns --engine libfuzzer --sanitizer memory

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py systemd mbedtls knot-dns --fuzzing-engines libfuzzer --sanitizers memory

**Comment by jonathanmetzman** [comment]
Fixes: https://github.com/google/oss-fuzz/issues/11703
Can remove next week.

**Review by oliverchang — COMMENTED** [review]
lgtm.  can you add some more context for  this?

**Comment by evverx** [comment]
Ubuntu bumped ARCH_MMAP_RND_BITS to the maximum in https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/commit/?h=hwe-6.5-next--2024.03.04-1--auto&id=6b522637c6a7dabd8530026ae933fb5ff17e877f and when GitHub rolled out that image on GitHub actions it broke a lot of workflows because ASan/UBSan/TSan/MSan weren't compatible with that: https://github.com/google/sanitizers/issues/1614. Newer version of clang can work with that (for example MSan was fixed in https://github.com/llvm/llvm-project/pull/85142) but clang included in the default clang package and in the base builder OSS-Fuzz images isn't new enough.

I should have mentioned that in #11703. Sorry!

**Comment by evverx** [comment]
Even though GitHub should roll back that change this week I think local runs on the latest Ubuntu with `./infra/helper.py build_fuzzers --sanitizer=memory` are likely to be broken because as far as I know Ubuntu itself isn't planning to revert that change.

**Comment by evverx** [comment]
I reverted it in https://github.com/google/oss-fuzz/pull/11717. Thanks for getting it around here. It would have been time-consuming to change it in every project.

**Pull request merged**
