### PR TITLE
Update email address for primary contact of GSS-NTLMSSP

### PR DESCRIPTION
**Pull request by simo5**
Oss-fuzz is crearting bugs in https://bugs.chromium.org/p/oss-fuzz/issues/ and adding me in CC with my alias. Unfortunately that project uses Google's authentication and my employer does not have a mechanism to authenticate my mail alias. So change the contact to my "standard" email address. It is the same person I can confirm by whatever mean if needed. In fact if someone in the project could reassign issue 58049 to ssorce@redhat.com I could prove it by authenticating to the issues and leaving a comment.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Can you sign the CLA please?

**Comment by simo5** [comment]
For a change of email?
It will take forever to go through legal.
I can drop the PR an open an issue instead so the commit will be yours if you prefer.

**Comment by jonathanmetzman** [comment]
> For a change of email? It will take forever to go through legal. I can drop the PR an open an issue instead so the commit will be yours if you prefer.

Yeah sorry. I'll commit this myself, but I probably can't do this for real code in the future.

**Comment by jonathanmetzman** [comment]
Done https://github.com/google/oss-fuzz/commit/c1e5dbfe3d86e012f7aa5a610e78b672f483f8af
You should automatically get access to the issue soon.

**Comment by simo5** [comment]
Thanks!
If I were to commit code, I would go through legal to get CLA approval before opening a PR, for sure.

**Pull request closed without merging**
