### PR TITLE
Reduce cores for gdb build to prevent failures

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Latest builds are failing.
This is super annoying to waste time building frankly, maybe we won't build base-builder-debug in trial builds, IMO it's not worth slowing down trial builds by 20 minutes.

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address coverage memory undefined --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address coverage memory undefined --fuzzing-engine libfuzzer afl honggfuzz

**Review by oliverchang — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address coverage memory undefined --fuzzing-engine libfuzzer afl honggfuzz

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer address coverage memory undefined --fuzzing-engine libfuzzer afl honggfuzz

**Review by Navidem — APPROVED** [review]

**Pull request merged**
