### PR TITLE
oss-fuzz-example: initial integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
This integrates oss-fuzz-example for continuous fuzzing. I'm a maintainer of the oss-fuzz-example library.

### CODE REVIEW

**Comment by AdamKorcz** [comment]
Who are the users of oss-fuzz-example and why is it security critical?

**Comment by DavidKorczynski** [comment]
The users of oss-fuzz-example includes open source maintainers that wants to experiment with OSS-Fuzz. oss-fuzz-example is used by corp X and deployed on Y phones. Some cloud infrastructures e.g. Z also use it.

**Comment by AdamKorcz** [comment]
The board will review the integration and get back to you shortly.

**Review by AdamKorcz — APPROVED** [review]
The board approves, LGTM.

**Pull request merged**
