### PR TITLE
Fix librawspeed build

### PR DESCRIPTION
**Pull request by jonathanmetzman**
Use gold instead of ld.bfd

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CC @LebedevRI

**Comment by LebedevRI** [comment]
Oh, bfd was still being used?!
I think the global oss-fuzz default is wrong.

**Comment by jonathanmetzman** [comment]
> I think the global oss-fuzz default is wrong.

As in we should be using gold by default? or lld? I agree it would be better to use something other than BFD, but I think the last time someone tried switching things over (a few years ago) many project broke

**Comment by LebedevRI** [comment]
> As in we should be using gold by default? or lld?

Yes, at least gold.
Not sure about lld, there may be some issues there,

**Comment by jonathanmetzman** [comment]
> > As in we should be using gold by default? or lld?
> 
> Yes, at least gold.
> Not sure about lld, there may be some issues there,

My thoughts as well, I think we had tried to switch to lld. We won't do this before the long weekend though :-)

**Pull request merged**
