### PR TITLE
[kubernetes] Add CCs

### PR DESCRIPTION
**Pull request by AdamKorcz**

### CODE REVIEW

**Comment by asraa** [comment]
cc @mikedanese

**Comment by DavidKorczynski** [comment]
Notice we are also discussing this internally with Michael Winser on reaching a contact that can receive fuzzing issues

**Comment by asraa** [comment]
@mikedanese do you have a +1?

**Comment by DavidKorczynski** [comment]
It would be great if this one could be merged in. This is work done alongside CNCF and we have uploaded a set of fuzzers for Kubernetes here https://github.com/cncf/cncf-fuzzing

It would be great if we could get on to observe results.

**Review by asraa — APPROVED** [review]

**Comment by DavidKorczynski** [comment]
Thanks @asraa !!

**Pull request merged**
