### PR TITLE
grok: add dataflow support

### PR DESCRIPTION
**Pull request by boxerab**
@Dor1s I put your two commits together and got the build working.

### CODE REVIEW

**Comment by boxerab** [comment]
> Will need to wait until #3388 is addressed

Great, looking forward to that. Any idea on time frame for #3388 ?

**Comment by Dor1s** [comment]
Not earlier than June.

**Comment by Dor1s** [comment]
Ah, should've fixed PR description: enable MSan, my bad.

**Comment by boxerab** [comment]
> Not earlier than June.

Thanks, will check back in the summer then.

**Pull request merged**
