### PR TITLE
varnish: Migration to pcre2

### PR DESCRIPTION
**Pull request by Dridi**
See https://github.com/varnishcache/varnish-cache/pull/3635

### CODE REVIEW

**Comment by Dridi** [comment]
@googlebot I signed it!

**Comment by DavidKorczynski** [comment]
It looks like the `pcre` library linked is a dynamially linked executable:
```
Status: Downloaded newer image for gcr.io/oss-fuzz-base/base-runner:latest
INFO: performing bad build checks for /tmp/not-out/esi_parse_fuzzer
Retrying failed fuzz targets sequentially 1
INFO: performing bad build checks for /tmp/not-out/esi_parse_fuzzer
Broken fuzz targets 1
('/tmp/not-out/esi_parse_fuzzer', CompletedProcess(args=['bad_build_check', '/tmp/not-out/esi_parse_fuzzer'], returncode=1, stdout=b'BAD BUILD: /tmp/not-out/esi_parse_fuzzer seems to have either startup crash or exit:\n/tmp/not-out/esi_parse_fuzzer -rss_limit_mb=2560 -timeout=25 -seed=1337 -runs=4 < /dev/null\n/tmp/not-out/esi_parse_fuzzer: error while loading shared libraries: libpcre2-8.so.0: cannot open shared object file: No such file or directory\n', stderr=b''))
BAD BUILD: /tmp/not-out/esi_parse_fuzzer seems to have either startup crash or exit:
```

Could you set it up so the fuzzer executable is statically linked?

**Comment by Dridi** [comment]
I didn't realize there was such a limitation, changing the configure invocation to this should do the trick:

```
./configure PCRE2_LIBS=-l:libpcre2-8.a
```

I will try to update the pull request soon.

**Comment by DavidKorczynski** [comment]
It now issues with:
```
...
  CC       vxp_test-vxp_test.o
  CC       vsl_glob_test-vsl_glob_test.o
  CCLD     libvarnishapi.la
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/libpcre2-8.a(libpcre2_8_la-pcre2_compile.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-linux-gnu/5.4.0/../../../x86_64-linux-gnu/libpcre2-8.a: error adding symbols: Bad value
clang-12: error: linker command failed with exit code 1 (use -v to see invocation)
Makefile:744: recipe for target 'libvarnishapi.la' failed
make[4]: *** [libvarnishapi.la] Error 1
make[4]: *** Waiting for unfinished jobs....
...
```

I wonder if this is because you install pcre from the package manager. Maybe it would help if you build it from source? I do this in `libyang`: https://github.com/google/oss-fuzz/blob/9488d28ab06140607236418172f71281a06dc61e/projects/libyang/Dockerfile

and there it seems to link fine https://github.com/google/oss-fuzz/blob/9488d28ab06140607236418172f71281a06dc61e/projects/libyang/build.sh

**Comment by Dridi** [comment]
I will try something else, only build the fuzzer. Not involving `libvarnishapi.so` should hopefully be enough, and that should even avoid wasting cycles building nonfuzz artifacts.

**Review by DavidKorczynski — APPROVED** [review]
LGTM. Thanks for the patience with this one!

**Comment by Dridi** [comment]
Thank you too for your patience and advice!

**Pull request merged**
