### PR TITLE
Add seed corpus for curl fuzzer. Also update length for tests.

### PR DESCRIPTION
**Pull request by inferno-chromium**

### CODE REVIEW

**Comment by inferno-chromium** [comment]
@bagder, @yangtse - We are trying to fuzz curl as part of OSS-Fuzz initiative, see details here - https://opensource.googleblog.com/2016/12/announcing-oss-fuzz-continuous-fuzzing.html. Can you review this CL, also, can you recommended someone as primary contact we can add in project.yaml and any emails you want to auto-cc on new reports.

Also, it will be great if you can move https://github.com/google/oss-fuzz/blob/master/projects/curl/curl_fuzzer.cc fuzzer and options file in your upstream repo and improve the fuzz target. Then, we can just reference that, instead of keeping that in OSS-Fuzz repo.

**Comment by inferno-chromium** [comment]
Just fyi, fuzz target might be buggy as well, i don't see any crashes and also sets too many options in every case. Maybe we error out too much. @badger ideas on fixing this https://github.com/google/oss-fuzz/blob/master/projects/curl/curl_fuzzer.cc ?

**Comment by bagder** [comment]
(Just that my nick doesn't spell like the animal, that's someone else)

**Comment by inferno-chromium** [comment]
@bagder - Sorry Daniel for the typo in last comment.

**Comment by bagder** [comment]
You can certainly set me as primary contact for curl bugs/issues. At least initially I can receive them and then possibly add a mailing list to receive them at a later point.

About adding `curl_fuzzer.cc` to our repo I have a few questions:

1. How can we in our repo validate that the file is still OK ? It is C++ (at least by extension), and we don't write any code in C++ in our project. It seems error-prone and fragile to "own it" without being able to make sure it is still fine.

2. I couldn't find any documentation for what this file is meant to do and how it is supposed to work. Without that, I can't see any value in adding it to our repo since nobody will know what to do with it! I suppose this is only because of my inability to search correctly?

**Comment by bagder** [comment]
At https://github.com/google/oss-fuzz/blob/master/projects/curl/curl_fuzzer.cc#L101 the code disables verification of the server cert in the case of HTTP/2, why? The code should probably explain that in a comment if on purpose.

**Comment by inferno-chromium** [comment]
@bagder - ok added you in https://github.com/google/oss-fuzz/blob/master/projects/curl/project.yaml

Regarding C++ Fuzz target, this was just written as an experiment by a team member, so i think this could be buggy and not correctly initialized. We support both C and C++. So, please feel free to convert this to C target. Writing a fuzz target is really simple, see instructions at https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md#fuzz-target. E.g. c target for c-ares is here - https://github.com/c-ares/c-ares/blob/master/test/ares-test-fuzz.c and its build.sh code is https://github.com/google/oss-fuzz/blob/master/projects/c-ares/build.sh#L25

**Comment by kcc** [comment]
yes, what @inferno-chromium says. 
[docs/ideal_integration.md](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md)
describes how we see the best fuzzing integration and hopefully answers most of your questions. 

The interface between the "targets" and the fuzzing engines is C, so you may use any language that is supported by [Clang](http://clang.llvm.org), of course, including C.

**Pull request merged**
