### PR TITLE
New project: CommonMark

### PR DESCRIPTION
**Pull request by philipturnbull**
This PR adds support for fuzzing the reference implementation of [CommonMark](http://commonmark.org/), an unambiguous specification of Markdown. I have tested this locally and it has found two bugs: jgm/cmark#206 and [a2f1f76dc](https://github.com/jgm/cmark/commit/a2f1f76dc38a34d0e3d97f75d1fee527931b6e8a) 🎉 

I'm not a maintainer of jgm/cmark but [jgm is happy to get cmark integrated into oss-fuzz](https://github.com/jgm/cmark/issues/206#issuecomment-310683059).

One question I have: as I am not a cmark maintainer, who should be listed as the `primary_contact`? 🤔  I'm not sure if that is "primary contact for the project" or "primary contact for the oss-fuzz integration"

I have signed GitHub's corporate CLA.

/cc @jgm @kivikakk

### CODE REVIEW

**Comment by inferno-chromium** [comment]
primary_contact is the primary / important contributor/committer in the project. 

Can you please provide some examples of real world usage of these ?

**Comment by jgm** [comment]
+++ Abhishek Arya [Jun 27 17 16:59 ]:
>   Can you please provide some examples of real world usage of these ?

A fork of jgm/cmark is used to render all of the Markdown in GitHub.

**Comment by philipturnbull** [comment]
Sure! The reference implementation is [werapped by the Elixir, Go, Haskell, Python, Ruby, etc](https://github.com/jgm/CommonMark/wiki/List-of-CommonMark-Implementations) bindings. Of those, the most important is probably the Haskell bindings which are used by [pandoc](http://pandoc.org/)

**Comment by inferno-chromium** [comment]
Thanks for explaining the usage, LGTM, merging.

**Pull request merged**
