### PR TITLE
c-blosc2: drop autotools deps

### PR DESCRIPTION
**Pull request by fanquake**
This project uses CMake & make.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
@nmoinvaz do you approve of this change?
Does anyone look at the bugs oss-fuzz reports for this project now that your email is gone?

**Comment by nmoinvaz** [comment]
c-blosc2 only uses CMake AFAIK. So I approve. I believe the primary contact email might be @FrancescAlted. I'm not sure if he checks the emails or no.

**Review by FrancescAlted — APPROVED** [review]
Looks good.  Thanks!

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
