### PR TITLE
[krb5] update repo and maintainer email

### PR DESCRIPTION
**Pull request by pkillarjun**
My base PR has been merged in krb5: https://github.com/krb5/krb5/pull/1346. Can you merge this?

### CODE REVIEW

**Comment by pkillarjun** [comment]
Requesting this to be merged first https://github.com/krb5/krb5/pull/1346

**Comment by pkillarjun** [comment]
Trigger CI.

**Comment by pkillarjun** [comment]
@DonggeLiu ping, my other work is on hold due to this PR. Can you merge it?

**Review by DonggeLiu — APPROVED** [review]
Approved.
I was out traveling last week.

**Pull request merged**
