### PR TITLE
Migrate to LTS JDK 17

### PR DESCRIPTION
**Pull request by asomov**

### CODE REVIEW

**Comment by asomov** [comment]
I have to fix Jazzer

**Comment by fmeum** [comment]
@asomov There shouldn't be a need to fix anything in Jazzer. You have to specify that you want to use JDK 17 when building Jazzer by replacing `local_jdk_15` with `local_jdk_17` in [this line](https://github.com/google/oss-fuzz/pull/8479/files#diff-f8720da6a22d0a918031e4ffcc3d3352ad87eeeace38c15d50722c8afec27545R33).

**Comment by asomov** [comment]
@fmeum the file` install_java.sh` is in Jazzer (not in this project)

**Comment by fmeum** [comment]
It's in this repo (OSS-Fuzz): https://github.com/snakeyaml/oss-fuzz/blob/a6cc50a6150859cda674951e44df6c6940ef1af2/infra/base-images/base-builder/install_java.sh#L33
You change the first part of it in this PR, but not the second part that contains the command to build Jazzer from the checked out commit. We do test Jazzer with JDK 17, so I would expect it to work.

**Comment by asomov** [comment]
@fmeum the second part comes from another project ! This project clones Jazzer

**Comment by fmeum** [comment]
Which project? `install_java.sh` is part of the OSS-Fuzz infrastructure and used by all Java projects.

**Comment by asomov** [comment]
Yes, it is but does not have the Jazzer !
https://github.com/google/oss-fuzz/blob/master/infra/base-images/base-runner/install_java.sh

**Comment by asomov** [comment]
@fmeum thank you. I think I will make another PR. This is stuck

**Comment by asomov** [comment]
I will make another PR

**Comment by asomov** [comment]
@fmeum I created another PR:
https://github.com/google/oss-fuzz/pull/8484

**Pull request closed without merging**
