### PR TITLE
nDPI: add support for centipede

### PR DESCRIPTION
**Pull request by IvanNardi**
See #9415

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
CI seems completely borked.

**Comment by jonathanmetzman** [comment]
i don't know what's going on here so I'm gonna merge this. if the build fails oh well.

**Comment by IvanNardi** [comment]
@jonathanmetzman , there is something really wrong here... this commit is is not present in master but in ... ` centipede ` branch!
Some conflict between MY branch called ` centipede` and some existing branch with the same name in upstream?
Anyway: do you want I push another PR?

Very sorry for the confusion

**Comment by jonathanmetzman** [comment]
Oh crap. Yeah I think this might have been caused by us devs not deleting branches properly.

**Comment by jonathanmetzman** [comment]
Yeah just send another PR please.

**Pull request merged**
