### PR TITLE
adding libra to list of projects

### PR DESCRIPTION
**Pull request by mimoo**
Hey!

I'd like to add [libra](https://libra.org/en-US/) to oss fuzz. Here is the [project repository](https://github.com/libra/libra/).

Thanks!

### CODE REVIEW

**Comment by mimoo** [comment]
@googlebot I signed it!

**Comment by inferno-chromium** [comment]
Welcome to OSS-Fuzz!

**Comment by jonathanmetzman** [comment]
Rust fuzzing should 100% work and we are eager to support it.
But there is one sharp edge I know of that I haven't gotten around to investigating, you should probably look at [this](https://github.com/google/oss-fuzz/pull/3298).
Also, some runtime changes were made by the the first rust project integrated, I'm not sure if those are generally needed: https://github.com/google/oss-fuzz/commit/ec58a65f336a52c347b40a7767f175e82c63a922 https://github.com/google/oss-fuzz/commit/94d0c3a7b4a173a6f046d664efe6ab845ed5d7b4

**Comment by mimoo** [comment]
thanks for the pointer! I'll report back if I run into troubles :)

**Comment by mimoo** [comment]
Is there anyway to accept multiple fuzzers as one binary? The way we currently run our fuzzers is that we add a environment variable that specifies which fuzzer it is.

Otherwise I'll have to look into creating separate binaries.

**Comment by Dor1s** [comment]
OSS-Fuzz model requires multiple binaries. See https://github.com/google/oss-fuzz/pull/431/files for example

**Comment by mimoo** [comment]
Looks like it takes us more than the 70GB limit to build our fuzzers in release mode 😄 any way to increase this?

**Comment by Dor1s** [comment]
Are you seeing a failure anywhere, or you've read about 70GB limit in https://github.com/google/oss-fuzz/blob/d1ed6b87a740878117ce804734b92e65313d6b3c/docs/getting-started/new_project_guide.md#L261 ?

I see that actual limit is higher, so unless you experience a failure, we should probably fix the docs instead :)

**Comment by mimoo** [comment]
that's how I had set my docker settings, with more memory it builds!

**Comment by Dor1s** [comment]
Ack, I've updated the doc in https://github.com/google/oss-fuzz/commit/072457fd3c8529c8b7ea474959175fb26158a2cc, sorry for the confusion!

**Comment by mimoo** [comment]
question: is there a way to invite someone (who hasn't been CC'ed) to a finding?

**Comment by Dor1s** [comment]
I've granted your gmail account `EditIssueCc` rights, you should be able to manually CC people on Monorail issues.

**Comment by mimoo** [comment]
one question: is it possible to grant this to more people/non-google accounts? Also, is there a way on your side to create a distribution list that gets CC'ed? (We can do it on our side, but I'm not sure how it'll work when everybody tries to login as fuzzing@calibra.org on our list.)

**Comment by inferno-chromium** [comment]
You can add a mailing list in auto_ccs in project.yaml, that gives them access to monorail bug, but they wont be able to login to ClusterFuzz interface since that requires individual login.

**Comment by mimoo** [comment]
what if everyone logs in as `fuzzing@calibra.org`?

**Comment by inferno-chromium** [comment]
Then it should work.

**Pull request merged**
