### PR TITLE
phashmap: initial integration

### PR DESCRIPTION
**Pull request by DavidKorczynski**
@greg7mdp I have set up continuous fuzzing of parallel hashmap. The benefits are that the fuzzer will be run on a regular basis and bug reports will be send to your email with information such as inputs that trigger the bugs, stack traces and more. Is this something you would be happy to have set up? If so, the only thing needed from your end is an email that will receive the bugs reports - notice this email should be attached to a Google account for you to see the reports.

### CODE REVIEW

**Comment by greg7mdp** [comment]
That would be great, thanks a lot for doing this, I was not even aware it was possible. 
I would prefer if the name of the project was phmap instead of phashmap if possible.
My email is greg7mdp@gmail.com.
Thanks!

**Comment by DavidKorczynski** [comment]
Awesome @greg7mdp - I switched the name as well as added your email. It's all good to go now.

**Comment by greg7mdp** [comment]
Great, thanks a lot @DavidKorczynski, looking forward to getting a first email!

**Comment by inferno-chromium** [comment]
@greg7mdp - can you please comment on the current customers using phmap library.

**Comment by greg7mdp** [comment]
phmap is open-source, anyone can use it, and I don't track who uses it, so I really can't provide a customer list.

**Comment by DavidKorczynski** [comment]
Looked around and found some of the customers:
- it's packaged with freebsd https://www.freshports.org/devel/parallel-hashmap
- https://github.com/h2oai/datatable
- http://cab.spbu.ru/software/spades/
- https://github.com/baulk/baulk

**Comment by greg7mdp** [comment]
Thanks @DavidKorczynski .

Found some more customers:

- https://github.com/Twinklebear/ChameleonRT
- https://github.com/atom-moyer/getpy
- https://github.com/eth-sri/astarix
- https://github.com/Twinklebear/dxr-ao-bake
- https://github.com/nitvic793/dx12-engine-elixir
- https://github.com/Intsights/PyDeduplines
- https://github.com/pluracoin/PluraCoin

**Review by inferno-chromium — APPROVED** [review]

**Pull request merged**
