### PR TITLE
Solidity: update docker image and build script

### PR DESCRIPTION
**Pull request by bshastry**
Install new dependencies for fuzzer build and minor refactor of build script

### CODE REVIEW

**Comment by bshastry** [comment]
Not sure why CIs are failing. Rebased.

**Comment by jonathanmetzman** [comment]
Looks like theres some kind of bug in actions now that isn't allowing full logs to be shown. I'll retry CI.

**Comment by inferno-chromium** [comment]
@bshastry - can you try running the build_fuzzer locally to reproduce this. Something is up with CI, but you can see the failures locally too. try with sanitizer address, undefined and coverage

**Comment by bshastry** [comment]
@inferno-chromium local build passes. could it be a post build step that fails the CI?

**Comment by inferno-chromium** [comment]
> @inferno-chromium local build passes. could it be a post build step that fails the CI?

CI can be weird some times, let me merge this now and keep an eye if you receive any notifications on solidity build breakages.

**Pull request merged**
