### PR TITLE
add ntpsec project

### PR DESCRIPTION
**Pull request by fallenpegasus**
I am the project manager for the NTPsec Project   https://ntpsec.org/

We've started getting bug reports based on fuzzing, so we would like to formally join the oss-fuzz project to formalize that and make it easier for us to be fuzz tested.

### CODE REVIEW

**Comment by inferno-chromium** [comment]
We are happy to have NTPsec fuzzed as part of OSS-Fuzz. Please sign the CLA and then we can merge this.

**Comment by jonathanmetzman** [comment]
ping @fallenpegasus

**Comment by Dor1s** [comment]
@fallenpegasus, are you still interested?

**Comment by Dor1s** [comment]
Closing this pull request for now. Please let us know if you're still interested.

**Pull request closed without merging**
