### PR TITLE
Simplify build infra

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms systemd --sanitizer address coverage introspector

**Review by Alan32Liu — APPROVED** [review]
LGTM, may I ask why it is required? (e.g., general individual optimisation, or for a bigger project?)

**Comment by Alan32Liu** [comment]
> It's not required, but sometimes it's good to clean up code. I think the design I'm getting rid of was made by an intern a few years ago and we weren't expecting to change this code much. We did, and the initial design made it harder.

I see! Thanks for the explanation : )

**Comment by jonathanmetzman** [comment]
Going to land this on Monday.

**Pull request merged**
