### PR TITLE
Fix introspector trial builds

### PR DESCRIPTION
**Pull request by jonathanmetzman**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer introspector address --fuzzing-engine libfuzzer

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer introspector address --fuzzing-engine libfuzzer

**Review by Navidem — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
/gcbrun trial_build.py skcms --sanitizer introspector address --fuzzing-engine libfuzzer --force

**Pull request merged**
