### PR TITLE
opensk: initial integration.

### PR DESCRIPTION
**Pull request by DavidKorczynski**
OpenSK is an open-source implementation for security keys written in Rust that supports both FIDO U2F and FIDO2 standards.

https://security.googleblog.com/2020/01/say-hello-to-opensk-fully-open-source.html

@jmichelp @ia0 @gendx is it in the interest to enable continuous fuzzing of OpenSK? There are already quite a few of Google's open source repositories on OSS-Fuzz and I thought it would be nice to get OpenSK on as well. Let me know!

### CODE REVIEW

**Comment by ia0** [comment]
Thanks @DavidKorczynski for doing this. In addition of @jmichelp for approval, let me also add @kaczmarczyck who has worked on those fuzz targets. Note that we also have fuzzing for one of our [internal library](https://github.com/google/OpenSK/tree/stable/libraries/persistent_store), we may want to also continuously fuzz it.

I tried to look at the [documentation](https://google.github.io/oss-fuzz/getting-started/new-project-guide/rust-lang/), it's not explicitly written but from how the setup looks it seems that OSS-Fuzz will fuzz all fuzz targets using the union of all corpuses. Is that correct understanding? I'm also curious of the scheduling strategy for fuzz targets. Is there some doc regarding how OSS-Fuzz decides how long and how often to run a given fuzz target? I'm asking because I'm planning to split the fuzz target of the internal library mentioned above (because smaller fuzz targets improve fuzzing efficiency) and I'm trying to find a strategy to cycle between the different fuzz targets to balance coverage progression (e.g. not spending too much time on a fuzz target that would be saturated).

**Comment by DavidKorczynski** [comment]
@ia0 OSS-Fuzz relies on ClusterFuzz as the infrastructure for running the fuzzers (https://google.github.io/clusterfuzz/). And yes, if I remember correctly ClusterFuzz will use corpus sharing between fuzzers, although I am not 100% sure about the details. With regards to the approach ClusterFuzz uses for scheduling fuzzers (and other infrastructure questions) I think @oliverchang or @inferno-chromium are the best to answer that. However, integrating it into OSS-Fuzz will have all the benefits of ClusterFuzz, including computing power. In addition to this the scheduling of fuzzers will probably improve over time as ClusterFuzz too improves.

**Comment by DavidKorczynski** [comment]
@ia0 @jmichelp @kaczmarczyck have you had more thoughts on whether you would like to get integrated with OSS-Fuzz?

**Comment by kaczmarczyck** [comment]
We do, yes! Thanks for creating this PR.

**Comment by DavidKorczynski** [comment]
> We do, yes! Thanks for creating this PR.

Is that a yes to "have you had more thoughts about it" or "would like to get integrated"? (apologies for the double question). 

If you would like to get integrated, could I put down the emails attached to your Github account to be the ones receiving bug reports?

**Comment by kaczmarczyck** [comment]
We do like to be integrated, thanks for double checking. Please send bug reports to opensk@google.com

**Comment by DavidKorczynski** [comment]
@inferno-chromium @jonathanmetzman @oliverchang @asraa This one is good to go. FYI this is a Google project

**Review by oliverchang — APPROVED** [review]

**Pull request merged**
