### PR TITLE
[cryptsetup] Initial integration for cryptsetup

### PR DESCRIPTION
**Pull request by mbroz**
This patch adds fuzzers built for the upstream cryptsetup project.

Initially, we try to fuzz LUKS2 on-disk format using various binary and JSON header modification methods.
This produces basic coverage on on-disk header parsing code.

Fuzzers for other formats like LUKS1 will be added later.

Currently, we enable only binary fuzzer and plain JSON mutator with a pre-generated corpus from previous experiments.

Changes based on Daniel Zatovic's work.

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by mbroz** [comment]
For some reason build of xz as dependence for static link from git gets stuck during po4a call in jobs, I disabled that command in script. This works in local Docker though... strange.
Anyway,  it will need to restart the jobs... I also enabled i386 arch build now.

**Comment by mbroz** [comment]
Could anyone please trigger the build again? I removed the i386 arch again, as it it not working properly (we can fixed this later but not sure it it is worth it.)

**Comment by DavidKorczynski** [comment]
> Could anyone please trigger the build again?

Done!

**Comment by mbroz** [comment]
THX! Tests are ok now, please let me know what I can do to make this merged. @jonathanmetzman ?

**Review by Navidem — APPROVED** [review]
LGTM

**Pull request merged**
