### PR TITLE
Proposing Fastapi project

### PR DESCRIPTION
**Pull request by ToSeven**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Does upstream approve of this?

**Comment by jonathanmetzman** [comment]
I will accept this if they approve

**Comment by DonggeLiu** [comment]
> Does upstream approve of this?

@ToSeven: Gentle ping: )

**Comment by ToSeven** [comment]
I have tried to contact the maintainer. Now there is no response.
https://github.com/tiangolo/fastapi/discussions/11059

**Comment by DonggeLiu** [comment]
> I have tried to contact the maintainer. Now there is no response. [tiangolo/fastapi#11059](https://github.com/tiangolo/fastapi/discussions/11059)

I see! I will make this a draft if you don't mind.
Please feel free to convert it back once they approve this later : )

**Pull request closed without merging**
