### PR TITLE
Integrate the `black` autoformatter for Python

### PR DESCRIPTION
**Pull request by Zac-HD**
See also https://github.com/psf/black/pull/1930, to add Atheris integration to the existing Hypothesis fuzz task; and #4975 for an explanation of how fuzzing with a property-based test works.

### CODE REVIEW

**Review by JelleZijlstra — APPROVED** [review]

**Comment by Zac-HD** [comment]
@JelleZijlstra - we'll need to merge https://github.com/psf/black/pull/1930 before this CI will pass 😉

**Comment by inferno-chromium** [comment]
> @JelleZijlstra - we'll need to merge [psf/black#1930](https://github.com/psf/black/pull/1930) before this CI will pass 😉

Can you merge to head and do a push again.

**Comment by Zac-HD** [comment]
It's not clear to me why this is failing, especially when the same script worked for `ujson` 😕

**Comment by inferno-chromium** [comment]
> It's not clear to me why this is failing, especially when the same script worked for `ujson` 😕

Every project is different, hard to generalize it to script.

Did you try running the fuzzer ? you can do so
```
python infra/helper.py shell black
cd /out
./fuzz
```
Does that work ?

**Comment by Zac-HD** [comment]
Yep, it works locally once I get the build script into place, just not from this CI.

**Pull request closed without merging**
