### PR TITLE
Add main_repo and language to new project doc, and links to field explanations. Fix workflow reference to repo_url.

### PR DESCRIPTION
**Pull request by sparr**
The PR Helper workflow complains if a new project doesn't include a main_repo, so I've added that to the accepting new projects page.

I also added links from there to the specific fields in the new project guide.

I also changed a reference in the workflow output to refer to the yaml field name visible to submitters, rather than to the internal python name for the same field which doesn't match.

### CODE REVIEW

**Comment by sparr** [comment]
Checks on #10552 revealed that `language` is also required.

**Review by hogo6002 — APPROVED** [review]
LGTM

**Comment by sparr** [comment]
The initial PR tests fail if `main_repo` and `language` aren't included, so it seems important to tell the user to include those when creating the PR.

**Comment by hogo6002** [comment]
> The initial PR tests fail if `main_repo` and `language` aren't included, so it seems important to tell the submitter to include those when creating the PR.

We actually mentioned project.ymal format here https://google.github.io/oss-fuzz/getting-started/new-project-guide/#projectyaml

**Comment by sparr** [comment]
Yes, but that doesn't mention which items are mandatory.

And if you follow the link from an invitation issue to https://google.github.io/oss-fuzz/getting-started/accepting-new-projects/ you encounter the instructions I've modified and are directed to open a PR with insufficient information *before* being directed to the more verbose instructions.

Currently, following those instructions leads to errors.

**Review by oliverchang — APPROVED** [review]
thank you for the contribution!

**Comment by hogo6002** [comment]
> Both check failures seem unrelated to this PR. `The command '/bin/sh -c install_rust.sh' returned a non-zero code: 1`

I will merge the PR after all checks finish. Thanks!

**Pull request merged**
