### PR TITLE
bitcoin-core: Fix coverage build

### PR DESCRIPTION
**Pull request by MarcoFalke**

### CODE REVIEW

**Review by inferno-chromium — APPROVED** [review]

**Comment by MarcoFalke** [comment]
This broke AFL

**Comment by inferno-chromium** [comment]
> This broke AFL

```
fuzz: test/fuzz/fuzz.cpp:37: auto initialize()::(anonymous class)::operator()() const: Assertion `"false" && check' failed.
+ FUZZ_TARGETS='  ./src/test/fuzz/fuzz INPUT_FILE1 [INPUT_FILE2 ... ]
  afl-fuzz [afl-flags] -- ./src/test/fuzz/fuzz [-N]
======================= INFO =========================
======================================================
This binary is built for afl++.
To fuzz with afl-fuzz execute this:
To run the target function on individual input(s) execute this:
```

**Comment by MarcoFalke** [comment]
Size breakdown:

* 1.8 GB (zipped inputs)
* 23 GB (fuzz targets: 120MB * 177)
* 15 GB (docker? etc)
* 1.2 GB (base image, OS, ...)

Total: ~32 GB

**Comment by MarcoFalke** [comment]
Sorry, no idea how to fix this today. I'll try some more tomorrow.

**Comment by MarcoFalke** [comment]
Reverted to just the cleanup commit

**Comment by MarcoFalke** [comment]
Recycled once more to fix https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=34027

**Comment by MarcoFalke** [comment]
CI was green before and after, but I tested this locally:


```
 python infra/helper.py coverage bitcoin-core 
Downloading corpora for bitcoin-core project to /root/oss-fuzz/build/corpus/bitcoin-core
ServiceException: 401 Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
ServiceException: 401 Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
ServiceException: 401 Anonymous caller does not have storage.objects.get access to the Google Cloud Storage object.
WARNING: corpus for bitcoin-core_asmap not found:

WARNING: corpus for bitcoin-core_process_messages not found:

WARNING: corpus for bitcoin-core_llvm-symbolizer not found:

Running: docker run --rm --privileged -i -e FUZZING_ENGINE=libfuzzer -e FUZZING_LANGUAGE=c++ -e PROJECT=bitcoin-core -e SANITIZER=coverage -e HTTP_PORT=8008 -e COVERAGE_EXTRA_ARGS= -p 8008:8008 -v /root/oss-fuzz/build/corpus/bitcoin-core:/corpus -v /root/oss-fuzz/build/out/bitcoin-core:/out -t gcr.io/oss-fuzz-base/base-runner coverage
Running asmap
Running process_messages
[2021-05-07 07:20:36,361 INFO] Finding shared libraries for targets (if any).
[2021-05-07 07:20:36,377 INFO] Finished finding shared libraries for targets.
[2021-05-07 07:20:36,885 INFO] Finding shared libraries for targets (if any).
[2021-05-07 07:20:36,897 INFO] Finished finding shared libraries for targets.
[2021-05-07 07:20:37,702 INFO] Finding shared libraries for targets (if any).
[2021-05-07 07:20:37,723 INFO] Finished finding shared libraries for targets.
[2021-05-07 07:20:41,495 DEBUG] Finished generating per-file code coverage summary.
[2021-05-07 07:20:41,495 DEBUG] Generating file view html index file as: "/out/report/linux/file_view_index.html".
[2021-05-07 07:20:41,608 DEBUG] Finished generating file view html index file.
[2021-05-07 07:20:41,609 DEBUG] Calculating per-directory coverage summary.
[2021-05-07 07:20:41,667 DEBUG] Finished calculating per-directory coverage summary.
[2021-05-07 07:20:41,667 DEBUG] Writing per-directory coverage html reports.
[2021-05-07 07:20:44,101 DEBUG] Finished writing per-directory coverage html reports.
[2021-05-07 07:20:44,101 DEBUG] Generating directory view html index file as: "/out/report/linux/directory_view_index.html".
[2021-05-07 07:20:44,102 DEBUG] Finished generating directory view html index file.
[2021-05-07 07:20:44,102 INFO] Index file for html report is generated as: "file:///out/report/linux/index.html".
Serving the report on http://127.0.0.1:8008/linux/index.html
Serving HTTP on 0.0.0.0 port 8008 ...
^Z    ^C
Keyboard interrupt received, exiting.
Successfully generated clang code coverage report.

**Comment by MarcoFalke** [comment]
@DavidKorczynski I think this one is ready for merge

**Review by DavidKorczynski — APPROVED** [review]
LGTM!

**Pull request merged**
