### PR TITLE
[Libmediaart] Initial integration - v2

### PR DESCRIPTION
**Pull request by ecalp-tps**
This is a new PR that fixes some of the issues with the [previous PR](https://github.com/google/oss-fuzz/pull/4701) that was merged and reverted.

Thanks!
Ceyhun
ceyhunalp@google.com

### CODE REVIEW

**Review by inferno-chromium — CHANGES_REQUESTED** [review]
Check the crashes on CI.

**Comment by ecalp-tps** [comment]
> Check the crashes on CI.

Hello Abhishek -- as I mentioned in the [reverted libmediaart PR](https://github.com/google/oss-fuzz/pull/4701#issuecomment-733974937), the crashes are due to the bugs in the libmediaart code. The upstream is aware of the bugs but I believe they haven't fixed these bugs yet.

**Comment by inferno-chromium** [comment]
@Google-Autofuzz - can you please take this over. Can you do a review pass and get those upstream bugs fixed. if fuzzer crashes instantly, we wouldn't be able to merge as check_build just fails.

**Comment by Google-Autofuzz** [comment]
Sure

**Pull request closed without merging**
