### PR TITLE
[rabbitmq-c] enable all sanitizer

### PR DESCRIPTION
**Pull request by 0x34d**

### CODE REVIEW

**Comment by 0x34d** [comment]
Log:
```
[ 88%] Building C object fuzz/CMakeFiles/fuzz_url.dir/fuzz_url.c.o
cd /src/librabbitmq/build/fuzz && /usr/local/bin/clang -DAMQP_STATIC -DHAVE_CONFIG_H -I/src/librabbitmq/build/fuzz/../librabbitmq -I/src/librabbitmq/fuzz/../librabbitmq -I/src/librabbitmq/build/librabbitmq/../include -I/src/librabbitmq/librabbitmq/../include -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unsigned-integer-overflow,unreachable,vla-bound,vptr -fno-sanitize-recover=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unreachable,vla-bound,vptr -fsanitize=fuzzer-no-link -g -fvisibility=hidden -std=gnu99 -MD -MT fuzz/CMakeFiles/fuzz_url.dir/fuzz_url.c.o -MF CMakeFiles/fuzz_url.dir/fuzz_url.c.o.d -o CMakeFiles/fuzz_url.dir/fuzz_url.c.o -c /src/librabbitmq/fuzz/fuzz_url.c
[ 90%] Linking C executable fuzz_url
cd /src/librabbitmq/build/fuzz && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/fuzz_url.dir/link.txt --verbose=1
/usr/local/bin/clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unsigned-integer-overflow,unreachable,vla-bound,vptr -fno-sanitize-recover=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unreachable,vla-bound,vptr -fsanitize=fuzzer-no-link -g -fsanitize=fuzzer CMakeFiles/fuzz_url.dir/fuzz_url.c.o -o fuzz_url  ../librabbitmq/librabbitmq.a /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so -lrt 
```

there is somthing wrong in infra

**Comment by jonathanmetzman** [comment]
> Log:
> 
> ```
> [ 88%] Building C object fuzz/CMakeFiles/fuzz_url.dir/fuzz_url.c.o
> cd /src/librabbitmq/build/fuzz && /usr/local/bin/clang -DAMQP_STATIC -DHAVE_CONFIG_H -I/src/librabbitmq/build/fuzz/../librabbitmq -I/src/librabbitmq/fuzz/../librabbitmq -I/src/librabbitmq/build/librabbitmq/../include -I/src/librabbitmq/librabbitmq/../include -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unsigned-integer-overflow,unreachable,vla-bound,vptr -fno-sanitize-recover=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unreachable,vla-bound,vptr -fsanitize=fuzzer-no-link -g -fvisibility=hidden -std=gnu99 -MD -MT fuzz/CMakeFiles/fuzz_url.dir/fuzz_url.c.o -MF CMakeFiles/fuzz_url.dir/fuzz_url.c.o.d -o CMakeFiles/fuzz_url.dir/fuzz_url.c.o -c /src/librabbitmq/fuzz/fuzz_url.c
> [ 90%] Linking C executable fuzz_url
> cd /src/librabbitmq/build/fuzz && /usr/local/bin/cmake -E cmake_link_script CMakeFiles/fuzz_url.dir/link.txt --verbose=1
> /usr/local/bin/clang -O1 -fno-omit-frame-pointer -gline-tables-only -DFUZZING_BUILD_MODE_UNSAFE_FOR_PRODUCTION -fsanitize=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unsigned-integer-overflow,unreachable,vla-bound,vptr -fno-sanitize-recover=array-bounds,bool,builtin,enum,float-divide-by-zero,function,integer-divide-by-zero,null,object-size,return,returns-nonnull-attribute,shift,signed-integer-overflow,unreachable,vla-bound,vptr -fsanitize=fuzzer-no-link -g -fsanitize=fuzzer CMakeFiles/fuzz_url.dir/fuzz_url.c.o -o fuzz_url  ../librabbitmq/librabbitmq.a /usr/lib/x86_64-linux-gnu/libssl.so /usr/lib/x86_64-linux-gnu/libcrypto.so -lrt 
> ```
> 
> there is somthing wrong in infra

Not sure I agree, it looks like one of the fuzzers is tiny.

**Comment by jonathanmetzman** [comment]
Or not compiled with the right sanitizers

**Comment by 0x34d** [comment]
> Or not compiled with the right sanitizers

`python infra/helper.py check_build rabbitmq-c --engine libfuzzer --sanitizer undefined`
```
INFO:__main__:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=undefined -e ARCHITECTURE=x86_64 -e FUZZING_LANGUAGE=c -e HELPER=True -v /home/legion/project/oss-fuzz/build/out/rabbitmq-c:/out -t gcr.io/oss-fuzz-base/base-runner test_all.py.
INFO: performing bad build checks for /tmp/not-out/tmpen8izlnv/fuzz_url
INFO: performing bad build checks for /tmp/not-out/tmpen8izlnv/fuzz_table
INFO: performing bad build checks for /tmp/not-out/tmpen8izlnv/fuzz_server
Retrying failed fuzz targets sequentially 1
INFO: performing bad build checks for /tmp/not-out/tmpen8izlnv/fuzz_url
Broken fuzz targets 1
('/tmp/not-out/tmpen8izlnv/fuzz_url', CompletedProcess(args=['bad_build_check', '/tmp/not-out/tmpen8izlnv/fuzz_url'], returncode=1, stdout=b'BAD BUILD: /tmp/not-out/tmpen8izlnv/fuzz_url seems to have only partial coverage instrumentation.\nBAD BUILD: /tmp/not-out/tmpen8izlnv/fuzz_url does not seem to be compiled with UBSan.\n', stderr=b''))
BAD BUILD: /tmp/not-out/tmpen8izlnv/fuzz_url seems to have only partial coverage instrumentation.
BAD BUILD: /tmp/not-out/tmpen8izlnv/fuzz_url does not seem to be compiled with UBSan.

ERROR: 33.333333333333336% of fuzz targets seem to be broken. See the list above for a detailed information.
ERROR:__main__:Check build failed.
```

`checksec build/out/rabbitmq-c/fuzz_url`
```
[*] '/home/legion/project/oss-fuzz/build/out/rabbitmq-c/fuzz_url'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX enabled
    PIE:      No PIE (0x400000)
    MSAN:     Enabled
    UBSAN:    Enabled
```


`python infra/helper.py run_fuzzer    rabbitmq-c  fuzz_url`
```
INFO:__main__:Running: docker run --rm --privileged --shm-size=2g --platform linux/amd64 -i -e FUZZING_ENGINE=libfuzzer -e SANITIZER=address -e RUN_FUZZER_MODE=interactive -e HELPER=True -v /home/legion/project/oss-fuzz/build/out/rabbitmq-c:/out -t gcr.io/oss-fuzz-base/base-runner run_fuzzer fuzz_url.
Using seed corpus: fuzz_url_seed_corpus.zip
/out/fuzz_url -rss_limit_mb=2560 -timeout=25 /tmp/fuzz_url_corpus < /dev/null
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 3208621054
INFO: Loaded 1 modules   (72 inline 8-bit counters): 72 [0x51c2a8, 0x51c2f0), 
INFO: Loaded 1 PC tables (72 PCs): 72 [0x4eea08,0x4eee88), 
INFO:        1 files found in /tmp/fuzz_url_corpus
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 1 min: 34b max: 34b total: 34b rss: 29Mb
#2	INITED cov: 24 ft: 25 corp: 1/34b exec/s: 0 rss: 29Mb
#3	NEW    cov: 25 ft: 26 corp: 2/68b lim: 34 exec/s: 0 rss: 29Mb L: 34/34 MS: 1 ChangeBinInt-
#10	REDUCE cov: 25 ft: 26 corp: 2/35b lim: 34 exec/s: 0 rss: 29Mb L: 1/34 MS: 2 ChangeASCIIInt-CrossOver-
#11	NEW    cov: 27 ft: 30 corp: 3/69b lim: 34 exec/s: 0 rss: 29Mb L: 34/34 MS: 1 CopyPart-
#13	NEW    cov: 29 ft: 35 corp: 4/98b lim: 34 exec/s: 0 rss: 29Mb L: 29/34 MS: 2 ChangeBinInt-EraseBytes-
#14	NEW    cov: 30 ft: 36 corp: 5/124b lim: 34 exec/s: 0 rss: 29Mb L: 26/34 MS: 1 CrossOver-
#15	NEW    cov: 33 ft: 45 corp: 6/158b lim: 34 exec/s: 0 rss: 29Mb L: 34/34 MS: 1 CrossOver-
#21	NEW    cov: 34 ft: 49 corp: 7/192b lim: 34 exec/s: 0 rss: 29Mb L: 34/34 MS: 1 ChangeBinInt-
```


* The build is compiled with `UBSAN`.
* Other targets are functioning properly.
* I can also run the fuzz_url fuzzer.

I agree with you that the fuzzer is quite small.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
