### PR TITLE
projects/cosmos-sdk: add cuong and emmanuel as maintainers

### PR DESCRIPTION
**Pull request by cuonglm**

### CODE REVIEW

**Comment by cuonglm** [comment]
cc @odeke-em

**Review by AdamKorcz — APPROVED** [review]

**Comment by cuonglm** [comment]
@AdamKorcz Thanks for approving! When can the change be deployed? I tried accessing https://oss-fuzz.com/testcase-detail/4830166565126144 for details report using my email `cuong.manhle.vn@gmail.com`, but the page still returns 403 for me.

**Comment by DavidKorczynski** [comment]
> @AdamKorcz Thanks for approving! When can the change be deployed? I tried accessing https://oss-fuzz.com/testcase-detail/4830166565126144 for details report using my email `cuong.manhle.vn@gmail.com`, but the page still returns 403 for me.

Did you receive an email about the bug on your personal email? As far as I know you should receive one at some point after the auto_cc has been set and then it should be accessible.

**Comment by AdamKorcz** [comment]
> When can the change be deployed?

In my experience, it should take a few hours before the new users have access to the bug reports.

**Comment by cuonglm** [comment]
@AdamKorcz Thanks FYI.

@DavidKorczynski I receive an email via our group email `fuzzing@orijtech.com`, this PR add my personal email `cuong.manhle.vn@gmail.com` so that I can access the bug report.

**Pull request merged**
