### PR TITLE
[Litmus]: Added changes to run build.sh from source in litmuschaos project

### PR DESCRIPTION
**Pull request by Jonsy13**

### CODE REVIEW

**Comment by Jonsy13** [comment]
Hello @DonggeLiu  would you be able to help review this? Fixing the failed tests.

**Comment by DonggeLiu** [comment]
Sure! But I thought this would have the same effect.
Approving the CIs to check if the fix works.

**Comment by Jonsy13** [comment]
> Details



> Sure! But I thought this would have the same effect. Approving the CIs to check if the fix works.

Hi @DonggeLiu Can you rerun the github action workflow. Now the issue is fixed on upstream as well!

**Comment by DonggeLiu** [comment]
Done

**Review by DonggeLiu — APPROVED** [review]
The CI has passed, I will approve this PR if you'd like to merge it.
But I reckon the new code in the PR is equivalent to the old, it is the upstream code change that fixed the error.

Please let me know if I missed anything : )

**Comment by Jonsy13** [comment]
Yes we can merge it.
This is for fixing other issue. 
Context - When we run the github action for running fuzz tests on PRs, It doesn't take the build.sh changes which are in the PR in upstream, instead it runs the tests with build.sh with which it was build last time in clusterfuzz. So we are trying to see if this helps.

**Pull request merged**
