### PR TITLE
[rnp] add more fuzzers and update build script.

### PR DESCRIPTION
**Pull request by ni4**
This PR adds support for more fuzzers, added recently to rnp codebase.

Also it updates build script with following changes:
- remove some unneeded verbosity
- disable building of some modules in Botan
- stick to the $SRC folder when running commands
- detect fuzzers automatically instead of using hardcoded list
- use all available cores during make

@tomrittervg Could you please take a look whether it's ok?
Also I removed fuzzers building from the Botan, was it really needed?

### CODE REVIEW

**Comment by tomrittervg** [comment]
I think we probably want to keep building botan in fuzzing mode though.  Other than that looks good.

**Comment by ni4** [comment]
> I think we probably want to keep building botan in fuzzing mode: For example --unsafe-fuzzer-mode should remove some sanity checks that allow the fuzzer to reach deeper into library. In theory if Botan is fuzzed as well or better than rnp, we don't need this coverage and disabling it might increase execution by some %; but in lieu of trying to make that determination it'd be more conservative to keep it covered.

Got it, thanks. Force-pushed with Botan's fuzzing back in play.

**Comment by ronaldtse** [comment]
@googlebot I signed it!

**Comment by ronaldtse** [comment]
@googlebot I signed it!

We've already signed the CLA and should have details correct, perhaps we're just waiting for validation?

**Comment by ronaldtse** [comment]
@googlebot I signed it!

**Review by ronaldtse — APPROVED** [review]
LGTM

**Comment by ronaldtse** [comment]
@tomrittervg would you be able to help here? Looks like we need a review from someone with write access. Thanks!

**Comment by tomrittervg** [comment]
That's not me :)  One of the Google maintainers will review and merge this soon-ish.

**Comment by ronaldtse** [comment]
Thanks @jonathanmetzman !

**Pull request merged**
