### PR TITLE
infra: bump fuzz introspector

### PR DESCRIPTION
**Pull request by DavidKorczynski**

### CODE REVIEW

**Comment by oliverchang** [comment]
/gcbrun trial_build.py all --fuzzing-engines libfuzzer --sanitizers introspector

**Review by oliverchang — APPROVED** [review]
Thanks David!!

**Comment by DavidKorczynski** [comment]
For reference the CFLite is a false positive as far as I can tell -- I can take a look at fixing it up tomorrow but it shouldn't block this PR as such

**Comment by oliverchang** [comment]
Some failures:

```
Step #1: INFO:root:Trial build end time: 2024-01-25 03:52:13.166778
Step #1: INFO:root:Failed project, Statuses, Logs
Step #1: INFO:root:abseil-cpp, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-f30920ae-8f7c-49db-afe2-0396519297ea.txt
Step #1: INFO:root:apache-commons-bcel, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-6595d362-f52f-4043-99a0-be6859966fac.txt
Step #1: INFO:root:apache-commons-csv, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-1ec149be-77c8-487a-882f-d5d5cb069248.txt
Step #1: INFO:root:faad2, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-4edffc9d-9a3d-4a5f-9a6e-f28f6475f27b.txt
Step #1: INFO:root:grpc-httpjson-transcoding, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-c17811a6-3178-489b-9a2a-2862c2d0b39a.txt
Step #1: INFO:root:h3, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-5e69450e-455c-4785-bf69-5cbca82cbc17.txt
Step #1: INFO:root:jackson-datatype-joda, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-0674a58b-ca47-41ea-aa64-fa1f030de30b.txt
Step #1: INFO:root:janino, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-6c7d2373-0caf-4dfd-840f-be1e6a176511.txt
Step #1: INFO:root:javaparser, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-0305242b-1845-4f0d-b02d-47c9512d3054.txt
Step #1: INFO:root:logback, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-ac186d9c-3d5f-4771-a4c7-683aa4a45b50.txt
Step #1: INFO:root:myanmar-tools, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-b4b26ae7-18f5-41d8-aa26-f79bf1649aaa.txt
Step #1: INFO:root:pigweed, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-c3c1bb4c-5203-4cdd-874a-2a04e76b2e97.txt
Step #1: INFO:root:quantlib, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-9fb63cbc-32be-4527-a60b-6bc5ae8288b1.txt
Step #1: INFO:root:xmlunit, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-614eaa4a-3f3e-462e-89f7-1f8fb87b0345.txt
Step #1: INFO:root:ndpi, FAILURE, https://oss-fuzz-gcb-logs.storage.googleapis.com/log-6dba369c-8afc-4f22-9b66-d30a23849e41.txt
```

A couple of these at least look new. Looks like there might be some issues iwth bazel-based projects where the source paths are different during build?

```
Step #22 - "compile-libfuzzer-introspector-x86_64": 2024-01-24 21:39:28.020 INFO analysis - dump_debug_files: 
Step #22 - "compile-libfuzzer-introspector-x86_64": Traceback (most recent call last):
Step #22 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/main.py", line 154, in <module>
Step #22 - "compile-libfuzzer-introspector-x86_64":     main()
Step #22 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/main.py", line 138, in main
Step #22 - "compile-libfuzzer-introspector-x86_64":     return_code = commands.run_analysis_on_dir(
Step #22 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/commands.py", line 65, in run_analysis_on_dir
Step #22 - "compile-libfuzzer-introspector-x86_64":     html_report.create_html_report(introspection_proj, analyses_to_run,
Step #22 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/html_report.py", line 760, in create_html_report
Step #22 - "compile-libfuzzer-introspector-x86_64":     introspection_proj.dump_debug_files()
Step #22 - "compile-libfuzzer-introspector-x86_64":   File "/fuzz-introspector/src/fuzz_introspector/analysis.py", line 358, in dump_debug_files
Step #22 - "compile-libfuzzer-introspector-x86_64":     shutil.copy(file_elem['source_file'], dst)
Step #22 - "compile-libfuzzer-introspector-x86_64":   File "/usr/local/lib/python3.8/shutil.py", line 415, in copy
Step #22 - "compile-libfuzzer-introspector-x86_64":     copyfile(src, dst, follow_symlinks=follow_symlinks)
Step #22 - "compile-libfuzzer-introspector-x86_64":   File "/usr/local/lib/python3.8/shutil.py", line 261, in copyfile
Step #22 - "compile-libfuzzer-introspector-x86_64":     with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
Step #22 - "compile-libfuzzer-introspector-x86_64": FileNotFoundError: [Errno 2] No such file or directory: '/proc/self/cwd/string_utilities_fuzzer.cc'
```

**Comment by oliverchang** [comment]
Gonna merge to get some runs in early. Please revert if this ends up causing too much issues.

**Pull request merged**
