### PR TITLE
infra: use only valid targets for python coverage

### PR DESCRIPTION
**Pull request by DavidKorczynski**
Some python coverage reports gets clobbered because non-fuzz targets are
included in FUZZ_TARGETS. The problem is we use a wrapper script to call into python
packages where a package is an executable generated by pyinstaller, and both the script
and the package is executable. Thus, there are two executables per fuzzer -- we should only
have one and it should be the wrapper script. This PR fixes it.

### CODE REVIEW

**Comment by DavidKorczynski** [comment]
`aiohttp` is an example where it gets clobbered. There are 4 fuzz targets in total, but only 2 are included in the fuzz report

**Review by oliverchang — APPROVED** [review]

**Comment by oliverchang** [comment]
/gcbrun trial_build.py cryptography --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
/gcbrun trial_build.py aiohttp --sanitizer coverage --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
/gcbrun trial_build.py aiohttp --sanitizer address --fuzzing-engine libfuzzer

**Comment by oliverchang** [comment]
/gcbrun trial_build.py aiohttp --sanitizer coverage --fuzzing-engine libfuzzer

**Pull request merged**
