### PR TITLE
[skia] Temporarily use gold to hack around clang regression

### PR DESCRIPTION
**Pull request by jonathanmetzman**
We may want to do this to librawspeed/ntp depending on how long the clang fix/roll takes.

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
See https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=16777 for more details.

**Comment by jonathanmetzman** [comment]
Build passes locally and is already broken. I'll revert if jenkins build fails.

**Comment by jonathanmetzman** [comment]
cc @kjlubick this should unbreak the skia build

**Comment by kjlubick** [comment]
Thanks!

**Pull request merged**
