### PR TITLE
keycloak: Initial integration

### PR DESCRIPTION
**Pull request by arthurscchan**
This PR initialise the base fuzzing project for keycloak. For keycloak adopters, see [LINK](https://github.com/keycloak/keycloak/blob/main/ADOPTERS.md)

### CODE REVIEW

**Comment by AdamKorcz** [comment]
Keycloak is a Keycloak is an identity and access management project with adopters including Accenture, Capgemini, CERN, HP Enterprise, Hitachi, Okta, Wayfair [and others](https://github.com/keycloak/keycloak/blob/main/ADOPTERS.md).

**Comment by AdamKorcz** [comment]
@stianst would you like to integrate Keycloak into OSS-Fuzz? If so, which email can we use for bug reports?

**Comment by AdamKorcz** [comment]
@oliverchang @jonathanmetzman Ready for review.

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Pull request merged**
