### PR TITLE
Adds project openDNP3 (ICS protocol)

### PR DESCRIPTION
**Pull request by catenacyber**
See as well https://github.com/automatak/dnp3/pull/234

### CODE REVIEW

**Comment by kcc** [comment]
openDNP3 as a project looks great, thanks! 
We'd like to see an ACK from the project owners.

**Comment by jadamcrain** [comment]
Hi,

I'm the primary author and maintainer. @catenacyber has been coordinating with me.

I'll be able to review and merge the PR on opendnp3 by end of the week, but this is definitely something that we want, and feel free to proceed with configuring to fuzz the fork until I can merge.

thanks,
Adam

**Comment by kcc** [comment]
@jadamcrain thanks for confirming. 
@catenacyber the code looks good, merging. Let's see how it works.

**Comment by kcc** [comment]
Running locally.. looks like fuzzing works great. 
The seed corpus has some coverage but running the fuzzer for a minute doubles that, 
which means that the seed corpus could be significantly improved. 
I would recommend it as the first step towards improving the results.

**Comment by jadamcrain** [comment]
Ok,  I'll run locally later this week, review coverage, and think about how to improve seed corpus.

**Comment by catenacyber** [comment]
@jadamcrain about the seed corpus, we can 
- use more pcaps, but I am (over)cautious about IP rights 
- use the input of the unit tests, but then we need to combine together all the sublayers

**Comment by jadamcrain** [comment]
I don't see any DNP3 traffic captures there. Is this a repo of captures or something else?

@catenacyber There's another option. I could use some tools I have to generate a larger seed corpus. I first want to review the existing coverage to see where  the gaps are.

**Comment by kcc** [comment]
This is the corpus used for fuzzing wireshark. (I'm not an expert in networking, I can't tell if it's useful here)

**Comment by jadamcrain** [comment]
Oh, ok. That's explains it. I has stuff for all the core dissectors (IP, UDP, TCP, etc) but not for the myriad of application layer protocols.

**Comment by jadamcrain** [comment]
@kcc Does the cluster fuzz dashboard already have coverage info available? If so, can you authorize my google account (jadamcrain).

**Comment by Dor1s** [comment]
Not really. Existing coverage implementation is in process of being replaces with #799. You still can check coverage report on oss-fuzz.com, it might be useful. Another option would be to wait a little bit for the new coverage implementation to be added. And the third option is to follow https://github.com/google/oss-fuzz/issues/1441#issuecomment-391472291 and generate coverage report locally.

**Pull request merged**
