### PR TITLE
suricata: build cifuzz only against master branch

### PR DESCRIPTION
**Pull request by catenacyber**
cc @jonathanmetzman did I get it right ?

### CODE REVIEW

**Review by jonathanmetzman — APPROVED** [review]
LGTM

**Comment by jonathanmetzman** [comment]
Thanks!

**Comment by jonathanmetzman** [comment]
OO build failure

**Comment by jonathanmetzman** [comment]
I'm not 100% sure this shows up at build time. Let me verify

**Comment by jonathanmetzman** [comment]
(you can also test by opening a PR in suricata and pointing the github action at this branch instead of master)

**Comment by jonathanmetzman** [comment]
it shoudl be there for build.sh, so this should work

**Comment by catenacyber** [comment]
The error was

> /src/build.sh: line 89: CIFUZZ: unbound variable
ERROR:__main__:Building fuzzers failed.

So, I am now just testing if the variable is set

**Comment by catenacyber** [comment]
Pushed the revert of #11797 as this seems to have broken coverage build, by removing code files that are generated

**Comment by catenacyber** [comment]
friendly ping @jonathanmetzman :-)

**Pull request merged**
