### PR TITLE
[libjuice] initial integration

### PR DESCRIPTION
**Pull request by 0x34d**
A STUN library used in ```libdatachannel``` and ```violet server```.

Mr. @paullouisageneau [oss-fuzz](https://github.com/google/oss-fuzz) can do continuous fuzzing of the targeted project.
any thoughts on integration?

Signed-off-by: 0x34d <ajsinghyadav00@gmail.com>

### CODE REVIEW

**Comment by paullouisageneau** [comment]
Great, thank you for the integration!

**Comment by 0x34d** [comment]
@jonathanmetzman ping.

**Comment by oliverchang** [comment]
Do you have some examples of prominent users for this project?

**Comment by 0x34d** [comment]
use in [libdatachannel](https://libdatachannel.org/) backed support for WebRTC.
Mostly in Arch .

**Comment by paullouisageneau** [comment]
@olivierchang [libdatachannel](https://libdatachannel.org/) and therefore its ICE backend libjuice are used by open-source projects like [libtorrent](https://github.com/arvidn/libtorrent), the [Godot engine](https://github.com/godotengine/webrtc-native), or frameworks like [geckos.io](https://github.com/geckosio/geckos.io).

**Comment by paullouisageneau** [comment]
@oliverchang [libdatachannel](https://libdatachannel.org/) and therefore its ICE backend libjuice are used by open-source projects like [libtorrent](https://github.com/arvidn/libtorrent), the [Godot engine](https://github.com/godotengine/webrtc-native), or frameworks like [geckos.io](https://github.com/geckosio/geckos.io).

**Comment by 0x34d** [comment]
closing for not being popular.

**Pull request closed without merging**
