### PR TITLE
libwebp: add huffman_fuzzer

### PR DESCRIPTION
**Pull request by jzern**
This was added in:
https://chromium.googlesource.com/webm/libwebp/+/a35ea50de40066a6382b88b288ff0956ec7d0dc7
a35ea50d Add a fuzzer for ReadHuffmanCodes

### CODE REVIEW

**Comment by jzern** [comment]
@vrabaud

**Review by DavidKorczynski — APPROVED** [review]

**Comment by jonathanmetzman** [comment]
> This was added in: https://chromium.googlesource.com/webm/libwebp/+/a35ea50de40066a6382b88b288ff0956ec7d0dc7 a35ea50d Add a fuzzer for ReadHuffmanCodes

Does this fuzzer find the issue on older builds?

**Comment by jzern** [comment]
> > This was added in: https://chromium.googlesource.com/webm/libwebp/+/a35ea50de40066a6382b88b288ff0956ec7d0dc7 a35ea50d Add a fuzzer for ReadHuffmanCodes
> 
> Does this fuzzer find the issue on older builds?

That's a good question. I'll try to run it tonight after finalizing libwebp 1.3.2.

**Comment by jzern** [comment]
> > > This was added in: https://chromium.googlesource.com/webm/libwebp/+/a35ea50de40066a6382b88b288ff0956ec7d0dc7 a35ea50d Add a fuzzer for ReadHuffmanCodes
> > 
> > 
> > Does this fuzzer find the issue on older builds?
> 
> That's a good question. I'll try to run it tonight after finalizing libwebp 1.3.2.

Actually the code was modified to facilitate the fuzzer and uses new types introduced in the fix. This will take a little bit more effort.

**Pull request merged**
