### PR TITLE
Update PcapPlusPlus build script to work with CMake

### PR DESCRIPTION
**Pull request by seladb**

### CODE REVIEW

**Comment by jonathanmetzman** [comment]
Are you an owner/maintainer of pcapplusplus? Not sure who owns the oss-fuzz interation (maybe @zlowram ?)

**Comment by jonathanmetzman** [comment]
Please sign the CLA

**Comment by seladb** [comment]
> Are you an owner/maintainer of pcapplusplus? Not sure who owns the oss-fuzz interation (maybe @zlowram ?)

Yes I'm the maintainer of PcapPlusPlus. Initially @zlowram created the oss-fuzz integration but I'm not sure if he's available to update to CMake so I went ahead and opened the PR

**Comment by seladb** [comment]
> Please sign the CLA

I already did, not sure why it's not reflected here...any idea?

**Review by jonathanmetzman — APPROVED** [review]
lgtm

**Comment by seladb** [comment]
@jonathanmetzman can you please approve running the 2 workflows?

**Comment by jonathanmetzman** [comment]
You want me to merge despite MSAN failure?

**Comment by seladb** [comment]
> You want me to merge despite MSAN failure?

@jonathanmetzman yes, it would be great if we can merge it without MSAN. We need to fix it on our end.
In the meantime - is it possible to disable MSAN for this project?

cc @clementperon

**Comment by seladb** [comment]
> > You want me to merge despite MSAN failure?
> 
> @jonathanmetzman yes, it would be great if we can merge it without MSAN. We need to fix it on our end. In the meantime - is it possible to disable MSAN for this project?
> 
> cc @clementperon

@jonathanmetzman should we merge this?

**Pull request closed without merging**
